complete -c 7z -d 'Add'
complete -c 7z -d 'Benchmark'
complete -c 7z -d 'Delete'
complete -c 7z -d 'Extract'
complete -c 7z -d 'Hash'
complete -c 7z -d 'Show information about supported formats'
complete -c 7z -d 'List'
complete -c 7z -d 'Rename'
complete -c 7z -d 'Test'
complete -c 7z -d 'Update'
complete -c 7z -d 'Extract with full paths'
complete -c 7z -d 'Include archives'
complete -c 7z -d 'Disable archive_name field'
complete -c 7z -d 'Overwrite mode'
complete -c 7z -d 'Exclude archives'
complete -c 7z -d 'Set output log level'
complete -c 7z -d 'Disable progress indicator'
complete -c 7z -d 'Set output stream'
complete -c 7z -d 'Show execution time statistics'
complete -c 7z -d 'Include filenames'
complete -c 7z -d 'Set compression method'
complete -c 7z -d 'Set output directory'
complete -c 7z -d 'Set password'
complete -c 7z -d 'Recurse subdirectories'
complete -c 7z -d 'Set archive name mode'
complete -c 7z -d 'Set charset for console I/O'
complete -c 7z -d 'Set hash function'
complete -c 7z -d 'Set charset for list files'
complete -c 7z -d 'Delete files after compression'
complete -c 7z -d 'Send archive by email'
complete -c 7z -d 'Create SFX archive'
complete -c 7z -d 'Read data from stdin'
complete -c 7z -d 'Set large pages mode'
complete -c 7z -d 'Show technical information'
complete -c 7z -d 'Store NT security information'
complete -c 7z -d 'Store NTFS alternate streams'
complete -c 7z -d 'Store hard links'
complete -c 7z -d 'Store symbolic links'
complete -c 7z -d 'Write data to stdout'
complete -c 7z -d 'Disable wildcard matching'
complete -c 7z -d 'Eliminate duplication of root folder'
complete -c 7z -d 'Use fully qualified file paths'
complete -c 7z -d 'Set sensitive case mode'
complete -c 7z -d 'Compress shared files'
complete -c 7z -d 'Set archive timestamp'
complete -c 7z -d 'Set CPU thread affinity mask'
complete -c 7z -d 'Exclude archive type'
complete -c 7z -d 'Type of archive'
complete -c 7z -d 'Update options'
complete -c 7z -d 'Create volumes'
complete -c 7z -d 'Assign work directory'
complete -c 7z -d 'Exclude filenames'
complete -c 7z -d 'Assume yes on all queries'
