complete -c abbr -s 'a' -l 'add' -d 'Add abbreviation'
complete -c abbr -s 'q' -l 'query' -d 'Check if an abbreviation exists'
complete -c abbr -l 'rename' -d 'Rename an abbreviation'
complete -c abbr -s 'e' -l 'erase' -d 'Erase abbreviation'
complete -c abbr -s 's' -l 'show' -d 'Print all abbreviations'
complete -c abbr -s 'l' -l 'list' -d 'Print all abbreviation names'
complete -c abbr -s 'h' -l 'help' -d 'Help'
complete -c abbr -s 'p' -l 'position' -d 'Expand only as a command, or anywhere'
complete -c abbr -s 'f' -l 'function' -d 'Treat expansion argument as a fish function'
complete -c abbr -s 'r' -l 'regex' -d 'Match a regular expression'
complete -c abbr -l 'set-cursor' -d 'Position the cursor at % post-expansion'
