complete -c abook -s 'h' -d 'Show usage'
complete -c abook -s 'C' -l 'config' -d 'Use an alternative configuration file'
complete -c abook -l 'datafile' -d 'Use an alternative addressbook file'
complete -c abook -l 'mutt-query' -d 'Make a query for mutt'
complete -c abook -l 'add-email' -d 'Read email message from stdin and add the sender'
complete -c abook -l 'add-email-quiet' -d 'Same as --add-email. Without confirmation'
complete -c abook -l 'convert' -d 'Convert address book files'
complete -c abook -l 'informat' -d 'Input file format'
complete -c abook -l 'outformat' -d 'Output file format'
complete -c abook -l 'infile' -d 'Input file (default: stdin)'
complete -c abook -l 'outfile' -d 'Output file (default: stdout)'
complete -c abook -l 'formats' -d 'Print available formats'
