complete -c actionlint -d 'enable colorful output'
complete -c actionlint -d 'path to config file'
complete -c actionlint -d 'enable debug output'
complete -c actionlint -d 'custom template to format error messages'
complete -c actionlint -d 'regex matching to error messages you want to ignore'
complete -c actionlint -d 'generate default config file'
complete -c actionlint -d 'disable colorful output'
complete -c actionlint -d 'use one line per one error'
complete -c actionlint -d 'command name or path of `pyflakes`'
complete -c actionlint -d 'command name or path of `shellcheck`'
complete -c actionlint -d 'filename when reading input from stdin'
complete -c actionlint -d 'enable verbose output'
complete -c actionlint -d 'show version'
complete -c actionlint -s 'h' -d 'show help message'
