complete -c adb -d 'Listen on all network interfaces'
complete -c adb -d 'Use first USB device'
complete -c adb -d 'Use first TCP/IP device'
complete -c adb -d 'Use device with given serial'
complete -c adb -d 'Use device with given transport id'
complete -c adb -d 'Name of adb server host'
complete -c adb -d 'Port of adb server'
complete -c adb -d 'Listen on given socket for adb server'
complete -c adb -d 'Connect to device'
complete -c adb -d 'Disconnect from device'
complete -c adb -d 'List all connected devices'
complete -c adb -d 'Copy file to device'
complete -c adb -d 'Copy file from device'
complete -c adb -d 'Copy host->device only if changed'
complete -c adb -d 'Run remote shell [command]'
complete -c adb -d 'Run emulator console command'
complete -c adb -d 'View device log'
complete -c adb -d 'Install package'
complete -c adb -d 'Uninstall package'
complete -c adb -d 'List PIDs of processes hosting a JDWP transport'
complete -c adb -d 'Port forwarding'
complete -c adb -d 'Return bugreport information'
complete -c adb -d 'Perform device backup'
complete -c adb -d 'Restore device from backup'
complete -c adb -d 'Show adb version'
complete -c adb -d 'Show adb help'
complete -c adb -d 'Block until device is online'
complete -c adb -d 'Ensure that there is a server running'
complete -c adb -d 'Kill the server if it is running'
complete -c adb -d 'Remounts the /system partition on the device read-write'
complete -c adb -d 'Reboots the device, optionally into the bootloader or recovery program'
complete -c adb -d 'Prints state of the device'
complete -c adb -d 'Prints serial number of the device'
complete -c adb -d 'Prints device path'
complete -c adb -d 'Continuously print the device status'
complete -c adb -d 'Restart the adbd daemon with root permissions'
complete -c adb -d 'Restart the adbd daemon without root permissions'
complete -c adb -d 'Restart the adbd daemon listening on USB'
complete -c adb -d 'Restart the adbd daemon listening on TCP'
complete -c adb -d 'Run PPP over USB'
complete -c adb -d 'Sideloads the given package'
complete -c adb -d 'Kick current connection from host side and make it reconnect.'
complete -c adb -d 'Execute a command on the device and send its stdout back'
complete -c adb -s 'l' -d 'Forward-lock the app'
complete -c adb -s 'r' -d 'Reinstall the app keeping its data'
complete -c adb -s 's' -d 'Install on SD card instead of internal storage'
complete -c adb -l 'algo' -d 'Algorithm name'
complete -c adb -l 'key' -d 'Hex-encoded key'
complete -c adb -l 'iv' -d 'Hex-encoded iv'
complete -c adb -s 'k' -d 'Keep the data and cache directories'
complete -c adb -s 'l' -d 'Also list device qualifiers'
complete -c adb -d 'Device to disconnect'
complete -c adb -s 'f' -d 'File to write backup data to'
complete -c adb -d 'Enable backup of the .apks themselves'
complete -c adb -d 'Disable backup of the .apks themselves (default)'
complete -c adb -d 'Enable backup of any installed apk expansion'
complete -c adb -d 'Disable backup of any installed apk expansion (default)'
complete -c adb -d 'Back up all installed applications'
complete -c adb -d 'Include system applications in -all (default)'
complete -c adb -d 'Exclude system applications in -all'
complete -c adb -d 'Package(s) to backup'
complete -c adb -l 'list' -d 'List all forward socket connections'
complete -c adb -l 'no-rebind' -d 'Fails the forward if local is already forwarded'
complete -c adb -l 'remove' -d 'Remove a specific forward socket connection'
complete -c adb -l 'remove-all' -d 'Remove all forward socket connections'
complete -c adb -d 'Kick current connection from device side and make it reconnect.'
complete -c adb -d 'File on device'
complete -c adb -d 'File on device'
complete -c adb -d 'File on device'
complete -c adb -s 'L' -l 'last' -d 'Dump logs from prior to last reboot from pstore'
complete -c adb -s 'b' -l 'buffer' -d ' Request alternate ring buffer(s)'
complete -c adb -s 'c' -l 'clear' -d 'Clear (flush) the entire log and exit'
complete -c adb -l 'pid' -d 'Only print the logs for the given PID'
complete -c adb -l 'wrap' -d 'Sleep for 2 hours or when buffer about to wrap whichever comes first'
complete -c adb -s 'v' -l 'format' -d 'Sets log print format verb and adverbs'
complete -c adb -s 'D' -l 'dividers' -d 'Print dividers between each log buffer'
complete -c adb -s 'B' -l 'binary' -d 'Output the log in binary'
complete -c adb -s 'f' -l 'file' -d 'Log to file instead of stdout'
complete -c adb -s 'r' -l 'rotate-kbytes' -d 'Rotate log every kbytes, requires -f'
complete -c adb -s 'n' -l 'rotate-count' -d 'Sets number of rotated logs to keep, default 4'
complete -c adb -l 'id' -d 'If the given signature for logging changes, clear the associated files'
complete -c adb -s 'g' -l 'buffer-size' -d 'Get the size of the ring buffers within logd'
complete -c adb -s 'G' -l 'buffer-size' -d 'Set size of a ring buffer in logd'
complete -c adb -s 'S' -l 'statistics' -d 'Output statistics'
complete -c adb -s 'p' -l 'prune' -d 'Print prune rules'
complete -c adb -s 'P' -l 'prune' -d 'Set prune rules'
complete -c adb -s 's' -d 'Set default filter to silent'
complete -c adb -s 'e' -l 'regex' -d 'Only print lines where the log message matches'
complete -c adb -s 'm' -l 'max-count' -d 'Quit after print <count> lines'
complete -c adb -l 'print' -d 'Print all message even if they do not matches, requires --regex and --max-count'
complete -c adb -l 'uid' -d 'Only display log messages from UIDs present in the comma separate list <uids>'
complete -c adb -d 'Command on device'
complete -c adb -d 'Command on device'
complete -c adb -d 'Property to set'
complete -c adb -d 'Property to get'
