complete -c age -s 'e' -l 'encrypt' -d 'encrypt'
complete -c age -s 'r' -l 'recipient' -d 'public key'
complete -c age -s 'R' -l 'recipients-file' -d 'file with public key(s)'
complete -c age -s 'a' -l 'armor' -d 'PEM encode ciphertext'
complete -c age -s 'p' -l 'passphrase' -d 'passphrase'
complete -c age -s 'd' -l 'decrypt' -d 'decrypt'
complete -c age -s 'i' -l 'identity' -d 'file with private key(s)'
complete -c age -s 'j' -d 'plugin'
complete -c age -l 'version' -d 'print version number'
