complete -c alsactl -d 'Save current driver state'
complete -c alsactl -d 'Load driver state'
complete -c alsactl -d 'Restore and rescan for available soundcards'
complete -c alsactl -s 'F' -l 'force' -d 'Try to restore control elements as much as possible'
complete -c alsactl -s 'g' -l 'ignore' -d 'Ignore missing soundcards'
complete -c alsactl -s 'P' -l 'pedantic' -d 'Do not restore mismatching control elements'
complete -c alsactl -s 'I' -l 'no-init-fallback' -d 'Do not init if restore fails'
complete -c alsactl -d 'Initialize all devices to a default state'
complete -c alsactl -d 'Periodically save state'
complete -c alsactl -d 'Restore state and then periodically save it'
complete -c alsactl -d 'Notify daemon to do an operation'
complete -c alsactl -d 'Monitor events'
complete -c alsactl -s 'h' -l 'help' -d 'Show available flags and commands'
complete -c alsactl -s 'd' -l 'debug' -d 'Make output a bit more verbose'
complete -c alsactl -s 'v' -l 'version' -d 'Print alsactl version number'
complete -c alsactl -s 'f' -l 'file' -d 'Select the configuration file to use'
complete -c alsactl -s 'l' -l 'lock' -d 'Use a lock file'
complete -c alsactl -s 'L' -l 'no-lock' -d 'Do not use a lock file'
complete -c alsactl -s 'O' -l 'lock-state-file' -d 'Select the state lock file path'
complete -c alsactl -s 'r' -l 'runstate' -d 'Save restore and init state to this file'
complete -c alsactl -s 'R' -l 'remove' -d 'Remove runstate file at first'
complete -c alsactl -s 'E' -l 'env' -d 'Set environment variable'
complete -c alsactl -s 'i' -l 'initfile' -d 'The configuration file for init'
complete -c alsactl -s 'p' -l 'period' -d 'The store period in seconds for the daemon command'
complete -c alsactl -s 'e' -l 'pid-file' -d 'The PID file to use'
complete -c alsactl -s 'b' -l 'background' -d 'Run the task in background'
complete -c alsactl -s 's' -l 'syslog' -d 'Use syslog for messages'
complete -c alsactl -s 'c' -l 'sched-idle' -d 'Set the process scheduling policy to idle (SCHED_IDLE)'
