complete -c alsamixer -s 'h' -l 'help' -d 'Show help'
complete -c alsamixer -s 'c' -l 'card' -d 'Soundcard number or id to use'
complete -c alsamixer -s 'D' -l 'device' -d 'Mixer device to control'
complete -c alsamixer -s 'V' -l 'view' -d 'Starting view mode'
complete -c alsamixer -s 'g' -l 'no-color' -d 'Toggle the using of colors'
complete -c alsamixer -s 'a' -l 'abstraction' -d 'Mixer abstraction level'
