complete -c alternatives -l 'verbose' -d 'Generate more comments about what alternatives is doing'
complete -c alternatives -l 'help' -d 'Give some usage information'
complete -c alternatives -l 'version' -d 'Tell which version of alternatives this is'
complete -c alternatives -l 'keep-missing' -d 'If new variant doesn'"'"'t provide some files, keep previous links'
complete -c alternatives -l 'altdir' -d 'Specifies the alternatives directory'
complete -c alternatives -l 'admindir' -d 'Specifies the administrative directory'
complete -c alternatives -l 'install' -d 'Add a group of alternatives to the system'
complete -c alternatives -l 'slave' -d 'Add a slave link to the new group'
complete -c alternatives -l 'initscript' -d 'Add an initscript for the new group'
complete -c alternatives -l 'family' -d 'Set a family for the new group'
complete -c alternatives -l 'remove' -d 'Remove an alternative and all of its associated slave links'
complete -c alternatives -l 'set' -d 'Set link group to given path'
complete -c alternatives -l 'config' -d 'Open menu to configure link group'
complete -c alternatives -l 'auto' -d 'Switch the master symlink name to automatic mode'
complete -c alternatives -l 'display' -d 'Display information about the link group'
complete -c alternatives -l 'list' -d 'Display information about all link groups'
complete -c alternatives -l 'remove-all' -d 'Remove the whole link group name'
complete -c alternatives -l 'add-slave' -d 'Add a slave link to an existing alternative'
complete -c alternatives -l 'remove-slave' -d 'Remove slave from an existing alternative'
