complete -c animate -d 'Control alpha/matte channel of an image [option]'
complete -c animate -d 'Decipher image with this password [password]'
complete -c animate -d 'Display image centered on a backdrop'
complete -c animate -d 'Apply option to select image channels [type]'
complete -c animate -d 'Shared or Private [type]'
complete -c animate -d 'Alternate image colorspace [type]'
complete -c animate -d 'Convert cipher pixels to plain pixels [filename]'
complete -c animate -d 'Define one or more image format options [format:option]'
complete -c animate -d 'Display the next image after pausing [value]'
complete -c animate -d 'Horizontal and vertical density of the image [geometry]'
complete -c animate -d 'Image depth [value]'
complete -c animate -d 'Display image to this X server [server]'
complete -c animate -d 'Layer disposal method [method]'
complete -c animate -d 'Apply error diffusion to image [method]'
complete -c animate -d 'Choose filter when resizing an image [type]'
complete -c animate -d 'Output formatted image characteristics ["string"]'
complete -c animate -d 'Level of gamma correction [value]'
complete -c animate -d 'Preferred size and location of the Image window [geometry]'
complete -c animate -d 'Horizontal and vertical backdrop placement [type]'
complete -c animate -d 'Identify the format and characteristics of the image'
complete -c animate -d 'Displayed image cannot be modified'
complete -c animate -d 'Type of image interlacing scheme [type]'
complete -c animate -d 'Pixel color interpolation method [method]'
complete -c animate -d 'Pixel cache resource limit [type value]'
complete -c animate -d 'Loop images then exit [iterations]'
complete -c animate -d 'Display image using this Standard Colormap [type]'
complete -c animate -d 'Monitor progress'
complete -c animate -d 'Seconds to pause before reanimating'
complete -c animate -d 'Size and location of an image canvas (setting) [geometry]'
complete -c animate -d 'Reduce colors in this colorspace [colorspace]'
complete -c animate -d 'Suppress all warning messages'
complete -c animate -d 'Pay attention to warning messages'
complete -c animate -d 'Command execute a command in an remote display process'
complete -c animate -d 'Settings remain in effect until parenthesis boundary'
complete -c animate -d 'Horizontal and vertical sampling factor [geometry]'
complete -c animate -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c animate -d 'Attribute set an image attribute [value]'
complete -c animate -d 'Width and height of image [geometry]'
complete -c animate -d 'Transparent color [color]'
complete -c animate -d 'Color tree depth [value]'
complete -c animate -d 'Print detailed information about the image'
complete -c animate -d 'Display image using this visual type [type]'
complete -c animate -d 'Virtual pixel access method [method]'
complete -c animate -d 'Display image to background of this window [id]'
complete -c animate -d 'Preferred number of colors in the image [value]'
complete -c animate -d 'Preferred size and location of the cropped image [geometry]'
complete -c animate -d 'Extract area from image [geometry]'
complete -c animate -d 'Transform image to black and white'
complete -c animate -d 'Size and location of an image canvas (operator) [geometry]'
complete -c animate -d 'Change the resolution of an image [geometry]'
complete -c animate -d 'Resize the image [geometry]'
complete -c animate -d 'Apply Paeth rotation to the image [degrees]'
complete -c animate -d 'Strip image of all profiles and comments'
complete -c animate -d 'Create a thumbnail of the image [geometry]'
complete -c animate -d 'Trim image edges'
complete -c animate -d 'Merge a sequence of images'
complete -c animate -d 'Flatten a sequence of images'
complete -c animate -d 'Display copious debugging information [events]'
complete -c animate -d 'Print program options'
complete -c animate -d 'Print a list of supported option arguments [type]'
complete -c animate -d 'Format of debugging information [format]'
complete -c animate -d 'Print version information'
complete -c animate -d 'Store matte channel if the image has one'
complete -c animate -d 'Range image scene range'
complete -c animate -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
