complete -c ansible -s 'a' -l 'args' -d 'Module arguments'
complete -c ansible -l 'ask-vault-pass' -d 'Ask for vault password'
complete -c ansible -s 'B' -l 'background' -d 'Run asynchronously, failing after X seconds'
complete -c ansible -s 'C' -l 'check' -d 'Just check, don'"'"'t make any changes'
complete -c ansible -s 'D' -l 'diff' -d 'Show the differences in files and templates'
complete -c ansible -s 'e' -l 'extra-vars' -d 'Set additional variables as key=value or YAML/JSON'
complete -c ansible -s 'f' -l 'forks' -d 'Number of parallel processes to use (default=5)'
complete -c ansible -s 'h' -l 'help' -d 'Shows a help message'
complete -c ansible -s 'i' -l 'inventory' -d 'Specify inventory host path or comma separated host list'
complete -c ansible -s 'l' -l 'limit' -d 'Further limit selected hosts to an additional pattern'
complete -c ansible -l 'list-hosts' -d 'List all matching hosts'
complete -c ansible -s 'm' -l 'module-name' -d 'Module name to execute (default=command)'
complete -c ansible -s 'M' -l 'module-path' -d 'Specify path(s) to module library (default=None)'
complete -c ansible -l 'new-vault-password-file' -d 'New vault password file for rekey'
complete -c ansible -s 'o' -l 'one-line' -d 'Condense output'
complete -c ansible -l 'output' -d 'Output file name for encrypt or decrypt; use - for stdout'
complete -c ansible -s 'P' -d 'Set the poll interval if using -B (default=15)'
complete -c ansible -l 'syntax-check' -d 'Perform a syntax check on the playbook'
complete -c ansible -s 't' -l 'tree' -d 'Log output to this directory'
complete -c ansible -l 'vault-password-file' -d 'Vault password file'
complete -c ansible -s 'v' -l 'verbose' -d 'Verbose mode (-vv/-vvv/-vvvv for more)'
complete -c ansible -l 'version' -d 'Display version and exit'
complete -c ansible -s 'k' -l 'ask-pass' -d 'Ask for connection password'
complete -c ansible -l 'private-key' -d 'Use this file to authenticate the connection'
complete -c ansible -l 'key-file' -d 'Use this file to authenticate the connection'
complete -c ansible -s 'u' -l 'user' -d 'Connect as this user (default=None)'
complete -c ansible -s 'c' -l 'connection' -d 'Connection type to use (default=smart)'
complete -c ansible -s 'T' -l 'timeout' -d 'Set the connection timeout in seconds (default=10)'
complete -c ansible -l 'ssh-common-args' -d 'Specify common arguments to pass to sftp/scp/ssh'
complete -c ansible -l 'sftp-extra-args' -d 'Specify extra arguments to pass to sftp only'
complete -c ansible -l 'scp-extra-args' -d 'Specify extra arguments to pass to scp only'
complete -c ansible -l 'ssh-extra-args' -d 'Specify extra arguments to pass to ssh only'
complete -c ansible -s 'b' -l 'become' -d 'Run operations with become'
complete -c ansible -l 'become-method' -d 'Privilege escalation method to use (default=sudo)'
complete -c ansible -l 'become-user' -d 'Run operations as this user (default=root)'
complete -c ansible -s 'K' -l 'ask-become-pass' -d 'Ask for privilege escalation password'
