complete -c ansible-playbook -l 'ask-vault-pass' -d 'Ask for vault password'
complete -c ansible-playbook -s 'C' -l 'check' -d 'Just check, don'"'"'t make any changes'
complete -c ansible-playbook -s 'D' -l 'diff' -d 'Show the differences in files and templates'
complete -c ansible-playbook -s 'e' -l 'extra-vars' -d 'Set additional variables as key=value or YAML/JSON'
complete -c ansible-playbook -l 'flush-cache' -d 'Clear the fact cache'
complete -c ansible-playbook -l 'force-handlers' -d 'Run handlers even if a task fails'
complete -c ansible-playbook -s 'f' -l 'forks' -d 'Number of parallel processes to use (default=5)'
complete -c ansible-playbook -s 'h' -l 'help' -d 'Shows a help message'
complete -c ansible-playbook -s 'i' -l 'inventory' -d 'Specify inventory host path or comma separated host list'
complete -c ansible-playbook -s 'l' -l 'limit' -d 'Further limit selected hosts to an additional pattern'
complete -c ansible-playbook -l 'list-hosts' -d 'List all matching hosts'
complete -c ansible-playbook -l 'list-tags' -d 'List all available tags'
complete -c ansible-playbook -l 'list-tasks' -d 'List all tasks that would be executed'
complete -c ansible-playbook -s 'M' -l 'module-path' -d 'Specify path(s) to module library (default=None)'
complete -c ansible-playbook -l 'new-vault-password-file' -d 'New vault password file for rekey'
complete -c ansible-playbook -l 'output' -d 'Output file name for encrypt or decrypt; use - for stdout'
complete -c ansible-playbook -l 'skip-tags' -d 'Don'"'"'t run plays and tasks whose tags match these values'
complete -c ansible-playbook -l 'start-at-task' -d 'Start the playbook at the task matching this name'
complete -c ansible-playbook -l 'step' -d 'Confirm each task before running'
complete -c ansible-playbook -l 'syntax-check' -d 'Perform a syntax check on the playbook'
complete -c ansible-playbook -s 't' -l 'tags' -d 'Only run plays and tasks tagged with these values'
complete -c ansible-playbook -l 'vault-password-file' -d 'Vault password file'
complete -c ansible-playbook -s 'v' -l 'verbose' -d 'Verbose mode (-vv/-vvv/-vvvv for more)'
complete -c ansible-playbook -l 'version' -d 'Display version and exit'
complete -c ansible-playbook -s 'k' -l 'ask-pass' -d 'Ask for connection password'
complete -c ansible-playbook -l 'private-key' -d 'Use this file to authenticate the connection'
complete -c ansible-playbook -s 'u' -l 'user' -d 'Connect as this user (default=None)'
complete -c ansible-playbook -s 'c' -l 'connection' -d 'Connection type to use (default=smart)'
complete -c ansible-playbook -s 'T' -l 'timeout' -d 'Set the connection timeout in seconds (default=10)'
complete -c ansible-playbook -l 'ssh-common-args' -d 'Specify common arguments to pass to sftp/scp/ssh'
complete -c ansible-playbook -l 'sftp-extra-args' -d 'Specify extra arguments to pass to sftp only'
complete -c ansible-playbook -l 'scp-extra-args' -d 'Specify extra arguments to pass to scp only'
complete -c ansible-playbook -l 'ssh-extra-args' -d 'Specify extra arguments to pass to ssh only'
complete -c ansible-playbook -s 'b' -l 'become' -d 'Run operations with become'
complete -c ansible-playbook -l 'become-method' -d 'Privilege escalation method to use (default=sudo)'
complete -c ansible-playbook -l 'become-user' -d 'Run operations as this user (default=root)'
complete -c ansible-playbook -s 'K' -l 'ask-become-pass' -d 'Ask for privilege escalation password'
