complete -c ansible-vault -l 'version' -d 'Display version and exit'
complete -c ansible-vault -s 'h' -l 'help' -d 'Show help message and exit'
complete -c ansible-vault -s 'v' -l 'verbose' -d 'Verbose mode (-vvv for more, -vvvv to enable connection debugging)'
complete -c ansible-vault -l 'ask-vault-pass' -d 'Ask for vault password'
complete -c ansible-vault -l 'new-vault-id' -d 'the new vault identity to use for rekey'
complete -c ansible-vault -l 'new-vault-password-file' -d 'New vault password file for rekey'
complete -c ansible-vault -l 'vault-id' -d 'the vault identity to use'
complete -c ansible-vault -l 'vault-password-file' -d 'Vault password file'
complete -c ansible-vault -d 'Decrypt encrypted file or stdin'
complete -c ansible-vault -d 'Encrypt a file or stdin'
complete -c ansible-vault -d 'Create encrypted file'
complete -c ansible-vault -d 'Edit encrypted file'
complete -c ansible-vault -d 'Rekey encrypted file'
complete -c ansible-vault -d 'View contents of something encrypted'
complete -c ansible-vault -d 'Encrypt string'
complete -c ansible-vault -l 'stdin-name' -d 'Specify the variable name for stdin'
complete -c ansible-vault -s 'n' -l 'name' -d 'Specify the variable name'
complete -c ansible-vault -s 'p' -l 'prompt' -d 'Prompt for the string to encrypt'
complete -c ansible-vault -l 'encrypt-vault-id' -d 'the vault id used to encrypt (required if more than vault-id is provided)'
complete -c ansible-vault -l 'output' -d 'Output file name for encrypt or decrypt; use - for stdout'
