complete -c apkanalyzer -d 'Analyze APK file attributes'
complete -c apkanalyzer -d 'Analyze the files inside the APK file'
complete -c apkanalyzer -d 'Analyze the contents of the manifest file'
complete -c apkanalyzer -d 'Analyze the DEX files inside the APK file'
complete -c apkanalyzer -d 'View text, image and string resources'
complete -c apkanalyzer -s 'h' -l 'human-readable' -d 'Human-readable output'
complete -c apkanalyzer -d 'Prints the application ID, version code, and version name'
complete -c apkanalyzer -d 'Prints the total file size of the APK'
complete -c apkanalyzer -d 'Prints an estimate of the download size of the APK'
complete -c apkanalyzer -d 'Prints features used by the APK that trigger Play Store filtering'
complete -c apkanalyzer -d 'Compares the sizes of apk-file and apk-file'
complete -c apkanalyzer -l 'not-required' -d 'Include features marked as not required in the output'
complete -c apkanalyzer -l 'different-only' -d 'Prints directories and files with differences'
complete -c apkanalyzer -l 'files-only' -d 'Does not print directory entries'
complete -c apkanalyzer -l 'patch-size' -d 'Shows an estimate of the file-by-file patch instead of a raw difference'
complete -c apkanalyzer -d 'Lists all files in the APK'
complete -c apkanalyzer -d 'Prints out the file contents'
complete -c apkanalyzer -l 'file' -d 'Specify a path inside the APK'
complete -c apkanalyzer -d 'Prints the APK manifest in XML format'
complete -c apkanalyzer -d 'Prints the application ID value'
complete -c apkanalyzer -d 'Prints the version name value'
complete -c apkanalyzer -d 'Prints the version code value'
complete -c apkanalyzer -d 'Prints the minimum SDK version'
complete -c apkanalyzer -d 'Prints the target SDK version'
complete -c apkanalyzer -d 'Prints the list of permissions'
complete -c apkanalyzer -d 'Prints whether the APK is debuggable'
complete -c apkanalyzer -d 'Prints a list of the DEX files in the APK'
complete -c apkanalyzer -d 'Prints the number of method references in the specified DEX files'
complete -c apkanalyzer -d 'Prints the class tree from DEX'
complete -c apkanalyzer -d 'Prints the bytecode of a class or method in smali format'
complete -c apkanalyzer -l 'files' -d 'Indicate specific files that you want to include'
complete -c apkanalyzer -l 'defined-only' -d 'Includes only classes defined in the APK in the output'
complete -c apkanalyzer -l 'files' -d 'Specifies the DEX file names to include'
complete -c apkanalyzer -l 'proguard-folder' -d 'Specifies the Proguard output folder to search for mappings'
complete -c apkanalyzer -l 'proguard-mapping' -d 'Specifies the Proguard mapping file'
complete -c apkanalyzer -l 'proguard-seeds' -d 'Specifies the Proguard seeds file'
complete -c apkanalyzer -l 'proguard-usage' -d 'Specifies the Proguard usage file'
complete -c apkanalyzer -l 'show-removed' -d 'Shows classes and members that were removed by Proguard'
complete -c apkanalyzer -l 'class' -d 'Specifies the class name to print'
complete -c apkanalyzer -l 'method' -d 'Specifies the method name to print'
complete -c apkanalyzer -d 'Prints a list of the packages that are defined in the resources table'
complete -c apkanalyzer -d 'Prints a list of configurations for the specified type'
complete -c apkanalyzer -d 'Prints the value of the resource specified by config, name, and type'
complete -c apkanalyzer -d 'Prints a list of resource names for a configuration and type'
complete -c apkanalyzer -d 'Prints the human-readable form of a binary XML file'
complete -c apkanalyzer -l 'type' -d 'Specifies the resource type to print'
complete -c apkanalyzer -l 'packages' -d 'Specifies the packages to print'
complete -c apkanalyzer -l 'config' -d 'Specifies the configuration to print'
complete -c apkanalyzer -l 'name' -d 'Specifies the resource name to print'
complete -c apkanalyzer -l 'type' -d 'Specifies the resource type to print'
complete -c apkanalyzer -l 'packages' -d 'Specifies the packages to print'
complete -c apkanalyzer -l 'config' -d 'Specifies the configuration to print'
complete -c apkanalyzer -l 'type' -d 'Specifies the resource type to print'
complete -c apkanalyzer -l 'packages' -d 'Specifies the packages to print'
complete -c apkanalyzer -l 'file' -d 'Specifies the file to print'
