complete -c apt-cache -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-cache -d 'Build apt cache'
complete -c apt-cache -d 'Show package info'
complete -c apt-cache -d 'Show cache statistics'
complete -c apt-cache -d 'Show source package'
complete -c apt-cache -d 'Show packages in cache'
complete -c apt-cache -d 'Print available list'
complete -c apt-cache -d 'List unmet dependencies in cache'
complete -c apt-cache -d 'Display package record'
complete -c apt-cache -d 'Search packagename by REGEX'
complete -c apt-cache -l 'full' -d 'Search full package name'
complete -c apt-cache -l 'names-only' -d 'Search packagename only'
complete -c apt-cache -d 'List dependencies for the package'
complete -c apt-cache -d 'List reverse dependencies for the package'
complete -c apt-cache -d 'Print package name by prefix'
complete -c apt-cache -d 'Generate dotty output for packages'
complete -c apt-cache -d 'Debug preferences file'
complete -c apt-cache -s 'p' -l 'pkg-cache' -d 'Select file to store package cache'
complete -c apt-cache -s 's' -l 'src-cache' -d 'Select file to store source cache'
complete -c apt-cache -s 'q' -l 'quiet' -d 'Quiet mode'
complete -c apt-cache -s 'i' -l 'important' -d 'Print important dependencies'
complete -c apt-cache -s 'a' -l 'all-versions' -d 'Print full records'
complete -c apt-cache -s 'g' -l 'generate' -d 'Auto-gen package cache'
complete -c apt-cache -l 'all-names' -d 'Print all names'
complete -c apt-cache -l 'recurse' -d 'Dep and rdep recursive'
complete -c apt-cache -l 'installed' -d 'Limit to installed'
complete -c apt-cache -s 'v' -l 'version' -d 'Display version and exit'
complete -c apt-cache -s 'c' -l 'config-file' -d 'Specify config file'
complete -c apt-cache -s 'o' -l 'option' -d 'Specify options'
complete -c apt-cache -d 'Package'
