complete -c apt-proxy-import -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-proxy-import -s 'V' -l 'version' -d 'Display version and exit'
complete -c apt-proxy-import -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c apt-proxy-import -s 'q' -l 'quiet' -d 'No message to STDOUT'
complete -c apt-proxy-import -s 'r' -l 'recursive' -d 'Recurse into subdir'
complete -c apt-proxy-import -s 'i' -l 'import-dir' -d 'Dir to import'
complete -c apt-proxy-import -s 'u' -l 'user' -d 'Change to user'
complete -c apt-proxy-import -s 'd' -l 'debug' -d 'Debug level[default 0]'
