complete -c apt-ftparchive -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-ftparchive -d 'Generate package from source'
complete -c apt-ftparchive -d 'Generate source index file'
complete -c apt-ftparchive -d 'Generate contents file'
complete -c apt-ftparchive -d 'Generate release file'
complete -c apt-ftparchive -d 'Remove records'
complete -c apt-ftparchive -l 'md5' -d 'Generate MD5 sums'
complete -c apt-ftparchive -s 'd' -l 'db' -d 'Use a binary db'
complete -c apt-ftparchive -s 'q' -l 'quiet' -d 'Quiet mode'
complete -c apt-ftparchive -l 'delink' -d 'Perform delinking'
complete -c apt-ftparchive -l 'contents' -d 'Perform contents generation'
complete -c apt-ftparchive -s 's' -l 'source-override' -d 'Use source override'
complete -c apt-ftparchive -l 'readonly' -d 'Make caching db readonly'
complete -c apt-ftparchive -s 'v' -l 'version' -d 'Display version and exit'
complete -c apt-ftparchive -s 'c' -l 'config-file' -d 'Use config file'
complete -c apt-ftparchive -s 'o' -l 'option' -d 'Set config options'
