complete -c apt-mark -d 'Package'
complete -c apt-mark -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-mark -d 'Mark a package as automatically installed'
complete -c apt-mark -d 'Mark a package as manually installed'
complete -c apt-mark -d 'Mark all dependencies of meta packages as auto'
complete -c apt-mark -d 'Hold a package, prevent automatic installation or removal'
complete -c apt-mark -d 'Cancel a hold on a package'
complete -c apt-mark -d 'Show automatically installed packages'
complete -c apt-mark -d 'Show manually installed packages'
complete -c apt-mark -d 'Show held packages'
complete -c apt-mark -s 'v' -l 'version' -d 'Display version and exit'
complete -c apt-mark -s 'c' -l 'config-file' -d 'Specify a config file'
complete -c apt-mark -s 'o' -l 'option' -d 'Set a config option'
complete -c apt-mark -l 'color' -d 'Turn colors on'
complete -c apt-mark -l 'no-color' -d 'Turn colors off'
complete -c apt-mark -s 'f' -l 'file' -d 'Write package statistics to a file'
