complete -c apt-get -d 'Package'
complete -c apt-get -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-get -d 'Update sources'
complete -c apt-get -d 'Upgrade or install newest packages'
complete -c apt-get -d 'Use with dselect front-end'
complete -c apt-get -d 'Distro upgrade'
complete -c apt-get -d 'Install one or more packages'
complete -c apt-get -d 'Display changelog of one or more packages'
complete -c apt-get -d 'Remove and purge one or more packages'
complete -c apt-get -d 'Remove one or more packages'
complete -c apt-get -d 'Fetch source packages'
complete -c apt-get -d 'Install/remove packages for dependencies'
complete -c apt-get -d 'Update cache and check dependencies'
complete -c apt-get -d 'Clean local caches and packages'
complete -c apt-get -d 'Clean packages no longer be downloaded'
complete -c apt-get -d 'Remove automatically installed packages'
complete -c apt-get -l 'no-install-recommends' -d 'Do not install recommended packages'
complete -c apt-get -l 'no-install-suggests' -d 'Do not install suggested packages'
complete -c apt-get -s 'd' -l 'download-only' -d 'Download Only'
complete -c apt-get -s 'f' -l 'fix-broken' -d 'Correct broken dependencies'
complete -c apt-get -s 'm' -l 'fix-missing' -d 'Ignore missing packages'
complete -c apt-get -l 'no-download' -d 'Disable downloading packages'
complete -c apt-get -s 'q' -l 'quiet' -d 'Quiet mode'
complete -c apt-get -s 's' -l 'simulate' -l 'just-print' -l 'dry-run' -l 'recon' -l 'no-act' -d 'Perform a simulation'
complete -c apt-get -s 'y' -l 'yes' -l 'assume-yes' -d 'Automatic yes to prompts'
complete -c apt-get -l 'assume-no' -d 'Automatic no to prompts'
complete -c apt-get -s 'u' -l 'show-upgraded' -d 'Show upgraded packages'
complete -c apt-get -s 'V' -l 'verbose-versions' -d 'Show full versions for packages'
complete -c apt-get -s 'b' -l 'compile' -l 'build' -d 'Compile source packages'
complete -c apt-get -l 'install-recommends' -d 'Install recommended packages'
complete -c apt-get -l 'install-suggests' -d 'Install suggested packages'
complete -c apt-get -l 'ignore-hold' -d 'Ignore package Holds'
complete -c apt-get -l 'no-upgrade' -d 'Do not upgrade packages'
complete -c apt-get -l 'force-yes' -d 'Force yes'
complete -c apt-get -l 'print-uris' -d 'Print the URIs'
complete -c apt-get -l 'purge' -d 'Use purge instead of remove'
complete -c apt-get -l 'reinstall' -d 'Reinstall packages'
complete -c apt-get -l 'list-cleanup' -d 'Erase obsolete files'
complete -c apt-get -s 't' -l 'target-release' -l 'default-release' -d 'Control default input to the policy engine'
complete -c apt-get -l 'trivial-only' -d 'Only perform operations that are trivial'
complete -c apt-get -l 'no-remove' -d 'Abort if any packages are to be removed'
complete -c apt-get -l 'only-source' -d 'Only accept source packages'
complete -c apt-get -l 'diff-only' -d 'Download only diff file'
complete -c apt-get -l 'tar-only' -d 'Download only tar file'
complete -c apt-get -l 'arch-only' -d 'Only process arch-dependant build-dependencies'
complete -c apt-get -l 'allow-unauthenticated' -d 'Ignore non-authenticated packages'
complete -c apt-get -s 'v' -l 'version' -d 'Display version and exit'
complete -c apt-get -s 'c' -l 'config-file' -d 'Specify a config file'
complete -c apt-get -s 'o' -l 'option' -d 'Set a config option'
