complete -c apt-move -d 'Generate master file'
complete -c apt-move -d 'Alias for '"'"'get'"'"''
complete -c apt-move -d 'Move packages to local tree'
complete -c apt-move -d 'Delete obsolete package files'
complete -c apt-move -d 'Build new local files'
complete -c apt-move -d 'Rebuild index files'
complete -c apt-move -d 'Move packages from cache to local mirror'
complete -c apt-move -d 'Alias for '"'"'move delete packages'"'"''
complete -c apt-move -d 'Alias for '"'"'update'"'"''
complete -c apt-move -d 'Download package missing from mirror'
complete -c apt-move -d 'Sync packages installed'
complete -c apt-move -d 'test $LOCALDIR/.exclude file'
complete -c apt-move -d 'Move file specified on commandline'
complete -c apt-move -d 'List packages that may serve as input to mirrorbin or mirrorsource'
complete -c apt-move -d 'Fetch package from STDIN'
complete -c apt-move -d 'Fetch source package from STDIN'
complete -c apt-move -s 'a' -d 'Process all packages'
complete -c apt-move -s 'c' -d 'Use specific conffile'
complete -c apt-move -s 'f' -d 'Force deletion'
complete -c apt-move -s 'q' -d 'Suppresses normal output'
complete -c apt-move -s 't' -d 'Test run'
