complete -c apt-src -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-src -d 'Update list of source packages'
complete -c apt-src -d 'Install source packages'
complete -c apt-src -d 'Upgrade source packages'
complete -c apt-src -d 'Remove source packages'
complete -c apt-src -d 'Build source packages'
complete -c apt-src -d 'Clean source packages'
complete -c apt-src -d 'Detect known source tree'
complete -c apt-src -d 'List installed source package\(s\)'
complete -c apt-src -d 'Root source tree'
complete -c apt-src -d 'Version of source package'
complete -c apt-src -d 'Name of the source package'
complete -c apt-src -s 'b' -l 'build' -d 'Build source packages'
complete -c apt-src -s 'i' -l 'installdebs' -d 'Install after build'
complete -c apt-src -s 'p' -l 'patch' -d 'Patch local changes'
complete -c apt-src -s 'l' -l 'location' -d 'Specify a dir'
complete -c apt-src -s 'c' -l 'here' -d 'Run on current dir'
complete -c apt-src -l 'upstream-version' -d 'Omit debian version'
complete -c apt-src -s 'k' -l 'keep-built' -d 'Do not del built files'
complete -c apt-src -s 'n' -l 'no-delete-source' -d 'Do not del source files'
complete -c apt-src -l 'version' -d 'Source tree version'
complete -c apt-src -s 'q' -l 'quiet' -d 'Output to /dev/null'
complete -c apt-src -s 't' -l 'trace' -d 'Output trace'
