complete -c apt-build -l 'help' -d 'Display help and exit'
complete -c apt-build -d 'Update list of packages'
complete -c apt-build -d 'Upgrade packages'
complete -c apt-build -d 'Rebuild your system'
complete -c apt-build -d 'Build and install a new package'
complete -c apt-build -d 'Download and extract a source'
complete -c apt-build -d 'Info on a package'
complete -c apt-build -d 'Remove packages'
complete -c apt-build -d 'Erase built packages'
complete -c apt-build -d 'Build source without install'
complete -c apt-build -d 'Clean source directories'
complete -c apt-build -d 'Update source and rebuild'
complete -c apt-build -d 'Update the repository'
complete -c apt-build -l 'nowrapper' -d 'Do not use gcc wrapper'
complete -c apt-build -l 'remove-builddep' -d 'Remove build-dep'
complete -c apt-build -l 'no-source' -d 'Do not download source'
complete -c apt-build -l 'build-dir' -d 'Specify build-dir'
complete -c apt-build -l 'rebuild' -d 'Rebuild a package'
complete -c apt-build -l 'reinstall' -d 'Rebuild and install an installed package'
complete -c apt-build -l 'build-command' -d 'Use <command> to build'
complete -c apt-build -l 'patch' -d 'Apply <file> patch'
complete -c apt-build -s 'p' -l 'patch-strip' -d 'Prefix to strip on patch'
complete -c apt-build -s 'y' -l 'yes' -d 'Assume yes to all questions'
complete -c apt-build -l 'purge' -d 'Use purge instead of remove'
complete -c apt-build -l 'noupdate' -d 'Do not run update'
complete -c apt-build -l 'source-list' -d 'Specify sources.list file'
complete -c apt-build -s 'v' -l 'version' -d 'Display version and exit'
