complete -c apt-listbugs -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-listbugs -s 's' -l 'severity' -d 'Set severity'
complete -c apt-listbugs -s 'T' -l 'tag' -d 'Tags you want to see'
complete -c apt-listbugs -s 'S' -l 'stats' -d 'Bug-status you want to see'
complete -c apt-listbugs -s 'l' -l 'showless' -d 'Ignore bugs in your system'
complete -c apt-listbugs -s 'g' -l 'showgreater' -d 'Ignore newer bugs than upgrade packages'
complete -c apt-listbugs -s 'D' -l 'show-downgrade' -d 'Bugs for downgrade packages'
complete -c apt-listbugs -s 'H' -l 'hostname' -d 'Bug Tracking system'
complete -c apt-listbugs -s 'p' -l 'port' -d 'Specify port for web interface'
complete -c apt-listbugs -s 'R' -l 'release-critical' -d 'Use daily bug report'
complete -c apt-listbugs -s 'I' -l 'index' -d 'Use the raw index.db'
complete -c apt-listbugs -s 'X' -l 'indexdir' -d 'Specify index dir'
complete -c apt-listbugs -s 'P' -l 'pin-priority' -d 'Specify Pin-Priority value'
complete -c apt-listbugs -l 'title' -d 'Specify the title of rss'
complete -c apt-listbugs -s 'f' -l 'force-download' -d 'Retrieve fresh bugs'
complete -c apt-listbugs -s 'q' -l 'quiet' -d 'Do not display progress bar'
complete -c apt-listbugs -s 'c' -l 'cache-dir' -d 'Specify local cache dir'
complete -c apt-listbugs -s 't' -l 'timer' -d 'Specify the expire cache timer'
complete -c apt-listbugs -s 'C' -l 'aptconf' -d 'Specify apt config file'
complete -c apt-listbugs -s 'y' -l 'force-yes' -d 'Assume yes to all questions'
complete -c apt-listbugs -s 'n' -l 'force-no' -d 'Assume no to all questions'
complete -c apt-listbugs -d 'List bugs from packages'
complete -c apt-listbugs -d 'List bugs in rss format'
