complete -c apt-file -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-file -d 'Resync package contents from source'
complete -c apt-file -d 'Search package containing pattern'
complete -c apt-file -d 'List contents of a package matching pattern'
complete -c apt-file -d 'Remove all gz files from cache'
complete -c apt-file -s 'c' -l 'cache' -d 'Set cache dir'
complete -c apt-file -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c apt-file -s 'd' -l 'cdrom-mount' -d 'Use cdrom-mount-point'
complete -c apt-file -s 'i' -l 'ignore-case' -d 'Do not expand pattern'
complete -c apt-file -s 'x' -l 'regexp' -d 'Pattern is regexp'
complete -c apt-file -s 'V' -l 'version' -d 'Display version and exit'
complete -c apt-file -s 'a' -l 'architecture' -d 'Set arch'
complete -c apt-file -s 's' -l 'sources-list' -d 'Set sources.list file'
complete -c apt-file -s 'l' -l 'package-only' -d 'Only display package name'
complete -c apt-file -s 'F' -l 'fixed-string' -d 'Do not expand pattern'
complete -c apt-file -s 'y' -l 'dummy' -d 'Run in dummy mode'
