complete -c apt-spy -s 'h' -d 'Display help and exit'
complete -c apt-spy -s 'd' -d 'Debian distribution'
complete -c apt-spy -s 'a' -d 'Servers in the areas'
complete -c apt-spy -s 'c' -d 'Conf file'
complete -c apt-spy -s 'e' -d 'Finish after number of servers'
complete -c apt-spy -s 'f' -d 'File to grab servers'
complete -c apt-spy -s 'i' -d 'File as input'
complete -c apt-spy -s 'm' -d 'Mirror-list file'
complete -c apt-spy -s 'o' -d 'Output sources.list file'
complete -c apt-spy -s 'p' -d 'Use proxy server'
complete -c apt-spy -s 's' -d 'Comma separated country list'
complete -c apt-spy -s 't' -d 'How long in sec to download'
complete -c apt-spy -s 'u' -d 'Custom URL to get mirror list'
complete -c apt-spy -s 'w' -d 'Write top servers to file'
complete -c apt-spy -s 'n' -d 'Number of top servers'
complete -c apt-spy -d 'Update mirror list'
complete -c apt-spy -s 'v' -d 'Version number'
