complete -c apt-show-source -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-show-source -l 'status-file' -d 'Read package from file'
complete -c apt-show-source -d 'Read package from file'
complete -c apt-show-source -l 'list-dir' -d 'Specify APT list dir'
complete -c apt-show-source -d 'Specify APT list dir'
complete -c apt-show-source -s 'p' -l 'package' -d 'List PKG info'
complete -c apt-show-source -l 'version-only' -d 'Display version and exit'
complete -c apt-show-source -s 'a' -l 'all' -d 'Print all source packages with version'
complete -c apt-show-source -s 'v' -l 'verbose' -d 'Verbose mode'
