complete -c apt-show-versions -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-show-versions -s 'p' -l 'packages' -d 'Print PKG versions'
complete -c apt-show-versions -s 'r' -l 'regex' -d 'Using regex'
complete -c apt-show-versions -s 'u' -l 'upgradeable' -d 'Print only upgradeable packages'
complete -c apt-show-versions -s 'a' -l 'allversions' -d 'Print all versions'
complete -c apt-show-versions -s 'b' -l 'brief' -d 'Print package name/distro'
complete -c apt-show-versions -s 'v' -l 'verbose' -d 'Print verbose info'
complete -c apt-show-versions -s 'i' -l 'initialize' -d 'Init or update cache only'
complete -c apt-show-versions -l 'status-file' -d 'Read package from file'
complete -c apt-show-versions -d 'Read package from file'
complete -c apt-show-versions -l 'list-dir' -d 'Specify APT list dir'
complete -c apt-show-versions -d 'Specify APT list dir'
