complete -c apt-listchanges -l 'help' -d 'Display help and exit'
complete -c apt-listchanges -l 'apt' -d 'Read filenames from pipe'
complete -c apt-listchanges -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c apt-listchanges -s 'f' -l 'frontend' -d 'Select frontend interface'
complete -c apt-listchanges -l 'email-address' -d 'Specify email address'
complete -c apt-listchanges -s 'c' -l 'confirm' -d 'Ask confirmation'
complete -c apt-listchanges -s 'a' -l 'all' -d 'Display all changelogs'
complete -c apt-listchanges -l 'save-seen' -d 'Avoid changelogs from db in named file'
complete -c apt-listchanges -l 'which' -d 'Select display'
complete -c apt-listchanges -s 'h' -l 'headers' -d 'Insert header'
complete -c apt-listchanges -l 'debug' -d 'Display debug info'
complete -c apt-listchanges -l 'profile' -d 'Select an option profile'
