complete -c apt-cdrom -s 'h' -l 'help' -d 'Display help and exit'
complete -c apt-cdrom -d 'Add new disc to source list'
complete -c apt-cdrom -d 'Report identity of disc'
complete -c apt-cdrom -s 'd' -l 'cdrom' -d 'Mount point'
complete -c apt-cdrom -s 'r' -l 'rename' -d 'Rename a disc'
complete -c apt-cdrom -s 'm' -l 'no-mount' -d 'No mounting'
complete -c apt-cdrom -s 'f' -l 'fast' -d 'Fast copy'
complete -c apt-cdrom -s 'a' -l 'thorough' -d 'Thorough package scan'
complete -c apt-cdrom -s 'n' -l 'no-act' -d 'No changes'
complete -c apt-cdrom -s 'v' -l 'version' -d 'Display version and exit'
complete -c apt-cdrom -s 'c' -l 'config-file' -d 'Specify config file'
complete -c apt-cdrom -s 'o' -l 'option' -d 'Specify options'
