complete -c apt -l 'no-install-recommends' -d 'Do not install recommended packages'
complete -c apt -l 'no-install-suggests' -d 'Do not install suggested packages'
complete -c apt -s 'd' -l 'download-only' -d 'Download Only'
complete -c apt -s 'f' -l 'fix-broken' -d 'Correct broken dependencies'
complete -c apt -s 'm' -l 'fix-missing' -d 'Ignore missing packages'
complete -c apt -l 'no-download' -d 'Disable downloading packages'
complete -c apt -s 'q' -l 'quiet' -d 'Quiet mode'
complete -c apt -s 's' -l 'simulate' -l 'just-print' -l 'dry-run' -l 'recon' -l 'no-act' -d 'Perform a simulation'
complete -c apt -s 'y' -l 'yes' -l 'assume-yes' -d 'Automatic yes to prompts'
complete -c apt -l 'assume-no' -d 'Automatic no to prompts'
complete -c apt -l 'install-recommends' -d 'Install recommended packages'
complete -c apt -l 'install-suggests' -d 'Install suggested packages'
complete -c apt -l 'with-new-pkgs'
complete -c apt -s 'h' -l 'help' -d 'Display help'
complete -c apt -s 'v' -l 'version' -d 'Display version and exit'
complete -c apt -s 'o' -l 'option' -d 'Set a configuration option'
complete -c apt -s 'c' -l 'config-file' -d 'Configuration file'
complete -c apt -s 't' -d 'Install from specific repository'
