complete -c aptitude -d 'Package'
complete -c aptitude -s 'h' -l 'help' -d 'Display a brief help message. Identical to the help action'
complete -c aptitude -d 'Remove any cached packages which can no longer be downloaded'
complete -c aptitude -d 'Remove all downloaded .deb files from the package cache directory'
complete -c aptitude -d 'Cancel all scheduled actions on all packages'
complete -c aptitude -d 'Update the list of available packages from the apt sources'
complete -c aptitude -d 'Upgrade installed packages to their most recent version'
complete -c aptitude -d 'Download and displays the Debian changelog for the packages'
complete -c aptitude -d 'Upgrade, removing or installing packages as necessary'
complete -c aptitude -d 'Download the packages to the current directory'
complete -c aptitude -d 'Forbid the upgrade to a particular version'
complete -c aptitude -d 'Ignore the packages by future upgrade commands'
complete -c aptitude -d 'Install the packages'
complete -c aptitude -d 'Cancel any scheduled actions on the packages'
complete -c aptitude -d 'Mark packages as automatically installed'
complete -c aptitude -d 'Remove and delete all associated configuration and data files'
complete -c aptitude -d 'Reinstall the packages'
complete -c aptitude -d 'Remove the packages'
complete -c aptitude -d 'Display detailed information about the packages'
complete -c aptitude -d 'Consider the packages by future upgrade commands'
complete -c aptitude -d 'Mark packages as manually installed'
complete -c aptitude -d 'Search for packages matching one of the patterns'
complete -c aptitude -d 'Display brief summary of the available commands and options'
complete -c aptitude -s 'D' -l 'show-deps' -d 'Show explanations of automatic installations and removals'
complete -c aptitude -s 'd' -l 'download-only' -d 'Download Only'
complete -c aptitude -s 'f' -l 'fix-broken' -d 'Correct broken dependencies'
complete -c aptitude -l 'purge-unused' -d 'Purge packages that are not required by any installed package'
complete -c aptitude -s 'P' -l 'prompt' -d 'Always display a prompt'
complete -c aptitude -s 'R' -l 'without-recommends' -d 'Do not treat recommendations as dependencies'
complete -c aptitude -s 'r' -l 'with-recommends' -d 'Treat recommendations as dependencies'
complete -c aptitude -l 'schedule-only' -d 'Schedule operations to be performed in the future'
complete -c aptitude -s 'q' -l 'quiet' -d 'Suppress incremental progress indicators'
complete -c aptitude -s 'V' -l 'show-versions' -d 'Show which versions of packages will be installed'
complete -c aptitude -s 'v' -l 'verbose' -d 'Display extra information'
complete -c aptitude -l 'version' -d 'Display the version of aptitude and compile information'
complete -c aptitude -l 'visual-preview' -d 'Start up the visual interface and display its preview screen'
complete -c aptitude -s 'y' -l 'assume-yes' -d 'Assume the answer yes for all question prompts'
complete -c aptitude -s 'Z' -d 'Show how much disk space will be used or freed'
complete -c aptitude -s 'F' -l 'display-format' -d 'Specify the format to be used by the search command'
complete -c aptitude -s 't' -l 'target-release' -d 'Set the release from which packages should be installed'
complete -c aptitude -s 'O' -l 'sort' -d 'Specify the order for the output from the search command'
complete -c aptitude -s 'o' -d 'Set a configuration file option directly'
complete -c aptitude -s 'w' -l 'width' -d 'Specify the display width for the output from the search command'
