complete -c archlinux-java -d 'List installed Java environments and enabled one'
complete -c archlinux-java -d 'Force <JAVA_ENV> as default'
complete -c archlinux-java -d 'Unset current default Java environment'
complete -c archlinux-java -d 'Return the short name of the Java environment set as default'
complete -c archlinux-java -d 'Fix an invalid/broken default Java environment configuration'
complete -c archlinux-java -d 'Show help'
