complete -c arp -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c arp -s 'n' -l 'numeric' -d 'Numerical address'
complete -c arp -s 'H' -l 'tw-type' -d 'Class of hw type'
complete -c arp -s 'a' -l 'display' -d 'Show arp entries'
complete -c arp -s 'd' -l 'delete' -d 'Remove an entry for hostname'
complete -c arp -s 'D' -l 'use-device' -d 'Use hardware address'
complete -c arp -s 'i' -l 'device' -d 'Select interface'
complete -c arp -s 's' -l 'set' -d 'Manually create ARP address'
complete -c arp -s 'f' -l 'file' -d 'Take addr from filename, default /etc/ethers'
