complete -c asciinema -s 'h' -l 'help' -d 'Show this help message and exit'
complete -c asciinema -l 'version' -d 'Show program'"'"'s version number and exit'
complete -c asciinema -d 'Record terminal session'
complete -c asciinema -l 'stdin' -d 'Enable stdin recording'
complete -c asciinema -l 'append' -d 'Append to existing recording'
complete -c asciinema -l 'raw' -d 'Save only raw stdout output'
complete -c asciinema -l 'overwrite' -d 'Overwrite the file if it already exists'
complete -c asciinema -s 'c' -l 'command' -d 'Command to record'
complete -c asciinema -s 'e' -l 'env' -d 'List of environment variables to capture'
complete -c asciinema -s 't' -l 'title' -d 'Title of the asciicast'
complete -c asciinema -s 'i' -l 'idle-time-limit' -d 'Limit recorded idle time to given number of seconds'
complete -c asciinema -l 'cols' -d 'Override terminal columns for recorded process'
complete -c asciinema -l 'rows' -d 'Override terminal rows for recorded process'
complete -c asciinema -s 'y' -l 'yes' -d 'Answer "yes" to all prompts'
complete -c asciinema -s 'q' -l 'quiet' -d 'Be quiet, suppress all notices/warnings'
complete -c asciinema -d 'Replay terminal session'
complete -c asciinema -s 'i' -l 'idle-time-limit' -d 'Limit idle time during playback to given number of seconds'
complete -c asciinema -s 's' -l 'speed' -d 'Playback speedup'
complete -c asciinema -d 'Print full output of terminal session'
complete -c asciinema -d 'Upload locally saved terminal session to asciinema.org'
complete -c asciinema -d 'Manage recordings on asciinema.org account'
