complete -c asp -d 'Checkout package'
complete -c asp -d 'Show the full history of the target, with file diffs'
complete -c asp -d 'Put the source files in current directory'
complete -c asp -d 'Collect garbage'
complete -c asp -d 'Report approximate disk usage'
complete -c asp -d 'Display help and exit'
complete -c asp -d 'List all known packages'
complete -c asp -d 'List the architectures the targets are available for'
complete -c asp -d 'List locally tracked packages'
complete -c asp -d 'List repos the targets exist in'
complete -c asp -d 'Show revision history of the target'
complete -c asp -d 'Show condensed revision history'
complete -c asp -d 'Show the target'"'"'s PKGBUILD'
complete -c asp -d 'Update given targets'
complete -c asp -d 'Remove target from local repository'
