complete -c avifenc -s 'h' -l 'help' -d 'Show syntax help'
complete -c avifenc -s 'V' -l 'version' -d 'Show the version number'
complete -c avifenc -s 'j' -l 'jobs' -d 'Number of jobs'
complete -c avifenc -s 'o' -l 'output' -d 'Filename of the output file'
complete -c avifenc -s 'l' -l 'lossless' -d 'Set all defaults to encode losslessly'
complete -c avifenc -s 'd' -l 'depth' -d 'Output depth'
complete -c avifenc -s 'y' -l 'yuv' -d 'Output format'
complete -c avifenc -l 'stdin' -d 'Read y4m frames from stdin'
complete -c avifenc -l 'cicp' -l 'nclx' -d 'Set CICP values'
complete -c avifenc -s 'r' -l 'range' -d 'YUV range'
complete -c avifenc -l 'min' -d 'Set min quantizer for color'
complete -c avifenc -l 'max' -d 'Set max quantizer for color'
complete -c avifenc -l 'minalpha' -d 'Set min quantizer for alpha'
complete -c avifenc -l 'maxalpha' -d 'Set max quantizer for alpha'
complete -c avifenc -l 'tilerowslog2' -d 'Set log2 of number of tile rows'
complete -c avifenc -l 'tilecolslog2' -d 'Set log2 of number of tile columns'
complete -c avifenc -l 'exif' -d 'Filename of the associated Exif metadata'
complete -c avifenc -l 'xmp' -d 'Filename of the associated XMP metadata'
complete -c avifenc -l 'icc' -d 'Filename of the associated ICC profile'
complete -c avifenc -s 'a' -l 'advanced' -d 'Pass a codec-specific key/value pair to the codec'
complete -c avifenc -l 'duration' -d 'Set all following frame durations'
complete -c avifenc -l 'timescale' -l 'fps' -d 'Set the timescale'
complete -c avifenc -s 'k' -l 'keyframe' -d 'Set the forced keyframe interval'
complete -c avifenc -l 'ignore-icc' -d 'Ignore an embedded ICC profile'
complete -c avifenc -l 'pasp' -d 'Add pasp property'
complete -c avifenc -l 'clap' -d 'Add clap property'
complete -c avifenc -l 'irot' -d 'Add irot property'
complete -c avifenc -l 'imir' -d 'Add imir property'
