complete -c blender -l 'help' -d 'Show help'
complete -c blender -l 'version' -d 'Show version'
complete -c blender -l 'background' -d 'Hide UI'
complete -c blender -l 'render-anim' -d 'Render animation'
complete -c blender -l 'scene' -d 'Specify scene'
complete -c blender -l 'render-frame' -d 'Render specified frame(s)'
complete -c blender -l 'frame-start' -d 'Specify start frame'
complete -c blender -l 'frame-end' -d 'Specify end frame'
complete -c blender -l 'frame-jump' -d 'Skip frame count'
complete -c blender -l 'render-output' -d 'Specify render output'
complete -c blender -l 'engine' -d 'Render engine'
complete -c blender -l 'threads' -d 'Specify thread count'
complete -c blender -d 'Run as animation player'
complete -c blender -d 'Specify position and size'
complete -c blender -d 'Read from disk (do not buffer)'
complete -c blender -d 'Specify FPS to start with'
complete -c blender -d 'Specify frame step'
complete -c blender -d 'Specify start frame'
complete -c blender -d 'Specify end frame'
complete -c blender -d 'Memory in MB for cache'
complete -c blender -l 'window-border' -d 'Show window borders'
complete -c blender -l 'window-fullscreen' -d 'Show in fullscreen'
complete -c blender -l 'window-geometry' -d 'Specify position and size'
complete -c blender -l 'window-maximized' -d 'Maximize window'
complete -c blender -l 'start-console' -d 'Open console'
complete -c blender -l 'no-native-pixels' -d 'Do not use native pixel size'
complete -c blender -l 'no-window-focus' -d 'Open unfocused'
complete -c blender -l 'enable-autoexec' -d 'Enable Python scripts automatic execution'
complete -c blender -l 'disable-autoexec' -d 'Disable Python scripts automatic execution'
complete -c blender -l 'python' -d 'Specify Python script'
complete -c blender -l 'python-text' -d 'Specify Python text block'
complete -c blender -l 'python-expr' -d 'Specify Python expression'
complete -c blender -l 'python-console' -d 'Open interactive console'
complete -c blender -l 'python-exit-code' -d 'Specify Python exit code on exception'
complete -c blender -l 'python-use-system-env' -d 'Use system env vars and user site-packages'
complete -c blender -l 'addons' -d 'Specify addons'
complete -c blender -l 'log' -d 'Enable logging categories'
complete -c blender -l 'log-level' -d 'Specify log level'
complete -c blender -l 'log-show-basename' -d 'Hide file leading path'
complete -c blender -l 'log-show-backtrace' -d 'Show backtrace'
complete -c blender -l 'log-show-timestamp' -d 'Show timestamp'
complete -c blender -l 'log-file' -d 'Specify log file'
complete -c blender -l 'debug' -d 'Enable debugging'
complete -c blender -l 'debug-value' -d 'Specify debug value'
complete -c blender -l 'debug-events' -d 'Enable debug messages from the event system'
complete -c blender -l 'debug-ffmpeg' -d 'Enable debug messages from FFmpeg library'
complete -c blender -l 'debug-handlers' -d 'Enable debug messages for event handling'
complete -c blender -l 'debug-libmv' -d 'Enable debug messages for libmv library'
complete -c blender -l 'debug-cycles' -d 'Enable debug messages for Cycles'
complete -c blender -l 'debug-memory' -d 'Enable fully guarded memory allocation and debugging'
complete -c blender -l 'debug-jobs' -d 'Enable time profiling for background jobs'
complete -c blender -l 'debug-python' -d 'Enable debug messages for Python'
complete -c blender -l 'debug-depsgraph' -d 'Enable all debug messages for dependency graph'
complete -c blender -l 'debug-depsgraph-eval' -d 'Enable debug messages for dependency graph related on evalution'
complete -c blender -l 'debug-depsgraph-build' -d 'Enable debug messages for dependency graph related on its construction'
complete -c blender -l 'debug-depsgraph-tag' -d 'Enable debug messages for dependency graph related on tagging'
complete -c blender -l 'debug-depsgraph-no-threads' -d 'Enable single treaded evaluation for dependency graph'
complete -c blender -l 'debug-depsgraph-time' -d 'Enable debug messages for dependency graph related on timing'
complete -c blender -l 'debug-depsgraph-pretty' -d 'Enable colors for dependency graph debug messages'
complete -c blender -l 'debug-depsgraph-uuid' -d 'Enable virefication for dependency graph session-wide identifiers'
complete -c blender -l 'debug-ghost' -d 'Enable debug messages for Ghost'
complete -c blender -l 'debug-wintab' -d 'Enable debug messages for Wintab'
complete -c blender -l 'debug-gpu' -d 'Enable GPU debug context and infromation for OpenGL'
complete -c blender -l 'debug-gpu-force-workarounds' -d 'Enable workarounds for typical GPU issues'
complete -c blender -l 'debug-wm' -d 'Enable debug messages for window manager'
complete -c blender -l 'debug-xr' -d 'Enable debug messages for virtual reality contexts'
complete -c blender -l 'debug-xr-time' -d 'Enable debug messages for virtual reality frame rendering times'
complete -c blender -l 'debug-all' -d 'Enable all debug messages'
complete -c blender -l 'debug-io' -d 'Enable debug for I/O'
complete -c blender -l 'debug-fpe' -d 'Enable floating point exceptions'
complete -c blender -l 'debug-exit-on-error' -d 'Exit on internal error'
complete -c blender -l 'debug-freestyle' -d 'Enable debug messages for Freestyle'
complete -c blender -l 'disable-crash-handler' -d 'Disable crash handler'
complete -c blender -l 'disable-abort-handler' -d 'Disable abort handler'
complete -c blender -l 'verbose' -d 'Specify logging verbosity level'
complete -c blender -l 'gpu-backend' -d 'Specify GPU backend'
complete -c blender -l 'open-last' -d 'Open the most recent .blend file'
complete -c blender -l 'app-template' -d 'Specify app template'
complete -c blender -l 'factory-startup' -d 'Do not read startup.blend'
complete -c blender -l 'enable-event-simulate' -d 'Enable event simulation'
complete -c blender -l 'env-system-datafiles' -d 'Set BLENDER_SYSTEM_DATAFILES variable'
complete -c blender -l 'env-system-scripts' -d 'Set BLENDER_SYSTEM_SCRIPTS variable'
complete -c blender -l 'env-system-python' -d 'Set BLENDER_SYSTEM_PYTHON variable'
complete -c blender -d 'Disable sound'
complete -c blender -d 'Specify sound device'
complete -c blender -l 'register' -d 'Register .blend extension for current user'
complete -c blender -l 'register-allusers' -d 'Register .blend extension for all users'
complete -c blender -l 'unregister' -d 'Unregister .blend extension for current user'
complete -c blender -l 'unregister-allusers' -d 'Unregister .blend extension for all users'
complete -c blender -d 'End option processing, following arguments passed to python'
