complete -c bluetoothctl -d 'List available controllers'
complete -c bluetoothctl -d 'Controller information'
complete -c bluetoothctl -d 'Select default controller'
complete -c bluetoothctl -d 'List available devices'
complete -c bluetoothctl -d 'List paired devices'
complete -c bluetoothctl -d 'Set controller alias'
complete -c bluetoothctl -d 'Reset controller alias'
complete -c bluetoothctl -d 'Set controller power'
complete -c bluetoothctl -d 'Set controller pairable mode'
complete -c bluetoothctl -d 'Set controller discoverable mode'
complete -c bluetoothctl -d 'Set discoverable timeout'
complete -c bluetoothctl -d 'Enable/disable agent with given capability'
complete -c bluetoothctl -d 'Set agent as the default one'
complete -c bluetoothctl -d 'Enable/disable advertising with given type'
complete -c bluetoothctl -d 'Set device alias'
complete -c bluetoothctl -d 'Scan for devices'
complete -c bluetoothctl -d 'Device information'
complete -c bluetoothctl -d 'Pair with device'
complete -c bluetoothctl -d 'Cancel pairing with device'
complete -c bluetoothctl -d 'Trust device'
complete -c bluetoothctl -d 'Untrust device'
complete -c bluetoothctl -d 'Block device'
complete -c bluetoothctl -d 'Unblock device'
complete -c bluetoothctl -d 'Remove device'
complete -c bluetoothctl -d 'Connect device'
complete -c bluetoothctl -d 'Disconnect device'
complete -c bluetoothctl -d 'Set/Get advertise uuids'
complete -c bluetoothctl -d 'Set/Get advertise service data'
complete -c bluetoothctl -d 'Set/Get advertise manufacturer data'
complete -c bluetoothctl -d 'Set/Get advertise data'
complete -c bluetoothctl -d 'Set/Get advertise discoverable'
complete -c bluetoothctl -d 'Set/Get advertise discoverable timeout'
complete -c bluetoothctl -d 'Show/Enable/Disable TX power to be advertised'
complete -c bluetoothctl -d 'Configure local name to be advertised'
complete -c bluetoothctl -d 'Configure custom appearance to be advertised'
complete -c bluetoothctl -d 'Set/Get advertise duration'
complete -c bluetoothctl -d 'Set/Get advertise timeout'
complete -c bluetoothctl -d 'Set/Get advertise secondary channel'
complete -c bluetoothctl -d 'Clear advertise config'
complete -c bluetoothctl -d 'List attributes'
complete -c bluetoothctl -d 'Select attribute'
complete -c bluetoothctl -d 'Select attribute'
complete -c bluetoothctl -d 'Read attribute value'
complete -c bluetoothctl -d 'Write attribute value'
complete -c bluetoothctl -d 'Acquire Write file descriptor'
complete -c bluetoothctl -d 'Release Write file descriptor'
complete -c bluetoothctl -d 'Acquire Notify file descriptor'
complete -c bluetoothctl -d 'Release Notify file descriptor'
complete -c bluetoothctl -d 'Notify attribute value'
complete -c bluetoothctl -d 'Clone a device or attribute'
complete -c bluetoothctl -d 'Register profile to connect'
complete -c bluetoothctl -d 'Unregister profile'
complete -c bluetoothctl -d 'Register application service'
complete -c bluetoothctl -d 'Unregister application service'
complete -c bluetoothctl -d 'Register as Included service in'
complete -c bluetoothctl -d 'Unregister Included service'
complete -c bluetoothctl -d 'Register application characteristic'
complete -c bluetoothctl -d 'Unregister application characteristic'
complete -c bluetoothctl -d 'Register application descriptor'
complete -c bluetoothctl -d 'Unregister application descriptor'
complete -c bluetoothctl -d 'Set/Get advertise uuids'
complete -c bluetoothctl -d 'Set/Get advertise service data'
complete -c bluetoothctl -d 'Set/Get advertise manufacturer data'
complete -c bluetoothctl -d 'Set/Get advertise data'
complete -c bluetoothctl -d 'Set/Get advertise discoverable'
complete -c bluetoothctl -d 'Set/Get advertise discoverable timeout'
complete -c bluetoothctl -d 'Show/Enable/Disable TX power to be advertised'
complete -c bluetoothctl -d 'Configure local name to be advertised'
complete -c bluetoothctl -d 'Configure custom appearance to be advertised'
complete -c bluetoothctl -d 'Set/Get advertise duration'
complete -c bluetoothctl -d 'Set/Get advertise timeout'
complete -c bluetoothctl -d 'Set/Get advertise secondary channel'
complete -c bluetoothctl -d 'Clear advertise config'
