complete -c bootctl -d 'Show status of EFI variables'
complete -c bootctl -d 'Install systemd-boot'
complete -c bootctl -d 'Update systemd-boot'
complete -c bootctl -d 'Remove systemd-boot'
complete -c bootctl -d 'Test whether systemd-boot is installed'
complete -c bootctl -d 'Initialize random seed'
complete -c bootctl -d 'Query or set system options string'
complete -c bootctl -d 'Query or set reboot-to-firmware EFI flag'
complete -c bootctl -d 'List boot loader entries'
complete -c bootctl -d 'Set default boot loader entry'
complete -c bootctl -d 'Set default boot loader entry (Once)'
complete -c bootctl -d 'Set default boot loader timeout'
complete -c bootctl -d 'Set default boot loader timeout (Once)'
complete -c bootctl -s 'h' -l 'help' -d 'Show this help'
complete -c bootctl -l 'version' -d 'Print version'
complete -c bootctl -l 'esp-path' -d 'Path to the EFI System Partition (ESP)'
complete -c bootctl -l 'boot-path' -d 'Path to the $BOOT partition'
complete -c bootctl -s 'p' -l 'print-esp-path' -d 'Print path to the EFI System Partition'
complete -c bootctl -s 'x' -l 'print-boot-path' -d 'Print path to the $BOOT partition'
complete -c bootctl -l 'no-variables' -d 'Do not touch EFI variables'
complete -c bootctl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c bootctl -l 'graceful' -d 'Do not print fail'
