complete -c bosh -d 'Add blob'
complete -c bosh -d 'Alias environment to save URL and CA certificate'
complete -c bosh -d 'Attaches disk to an instance'
complete -c bosh -d 'List blobs'
complete -c bosh -d 'Cancel task at its next checkpoint'
complete -c bosh -d 'Clean up releases, stemcells, disks, etc.'
complete -c bosh -d 'Cloud consistency check and interactive repair'
complete -c bosh -d 'Show current cloud config'
complete -c bosh -d 'Show current config'
complete -c bosh -d 'List configs'
complete -c bosh -d 'Show current CPI config'
complete -c bosh -d 'Create or update BOSH environment'
complete -c bosh -d 'Create release'
complete -c bosh -d 'Delete config'
complete -c bosh -d 'Delete deployment'
complete -c bosh -d 'Delete disk'
complete -c bosh -d 'Delete BOSH environment'
complete -c bosh -d 'Delete release'
complete -c bosh -d 'Delete snapshot'
complete -c bosh -d 'Delete all snapshots in a deployment'
complete -c bosh -d 'Delete stemcell'
complete -c bosh -d 'Delete VM'
complete -c bosh -d 'Update deployment'
complete -c bosh -d 'Show deployment information'
complete -c bosh -d 'List deployments'
complete -c bosh -d 'Diff two configs by ID'
complete -c bosh -d 'List disks'
complete -c bosh -d 'Show environment'
complete -c bosh -d 'List environments'
complete -c bosh -d 'List errands'
complete -c bosh -d 'Show event details'
complete -c bosh -d 'List events'
complete -c bosh -d 'Export the compiled release to a tarball'
complete -c bosh -d 'Create final release from dev release tarball'
complete -c bosh -d 'Generate job'
complete -c bosh -d 'Generate package'
complete -c bosh -d 'Show this help message'
complete -c bosh -d 'Ignore an instance'
complete -c bosh -d 'Initialize release'
complete -c bosh -d 'List release contents such as jobs'
complete -c bosh -d 'List all instances in a deployment'
complete -c bosh -d 'Interpolates variables into a manifest'
complete -c bosh -d 'List current locks'
complete -c bosh -d 'Log in'
complete -c bosh -d 'Log out'
complete -c bosh -d 'Fetch logs from instance(s)'
complete -c bosh -d 'Show deployment manifest'
complete -c bosh -d 'Orphan disk'
complete -c bosh -d 'Recreate instance(s)'
complete -c bosh -d 'List releases'
complete -c bosh -d 'Remove blob'
complete -c bosh -d 'Repack stemcell'
complete -c bosh -d 'Reset release'
complete -c bosh -d 'Restart instance(s)'
complete -c bosh -d 'Run errand'
complete -c bosh -d 'Show current runtime config'
complete -c bosh -d 'SCP to/from instance(s)'
complete -c bosh -d 'List snapshots'
complete -c bosh -d 'SSH into instance(s)'
complete -c bosh -d 'Start instance(s)'
complete -c bosh -d 'List stemcells'
complete -c bosh -d 'Stop instance(s)'
complete -c bosh -d 'Sync blobs'
complete -c bosh -d 'Take snapshot'
complete -c bosh -d 'Show task status and start tracking its output'
complete -c bosh -d 'List running or recent tasks'
complete -c bosh -d 'Unignore an instance'
complete -c bosh -d 'Update current cloud config'
complete -c bosh -d 'Update config'
complete -c bosh -d 'Update current CPI config'
complete -c bosh -d 'Enable/disable resurrection'
complete -c bosh -d 'Update current runtime config'
complete -c bosh -d 'Upload blobs'
complete -c bosh -d 'Upload release'
complete -c bosh -d 'Upload stemcell'
complete -c bosh -d 'List variables'
complete -c bosh -d 'Vendor package'
complete -c bosh -d 'List all VMs in all deployments'
