complete -c brightnessctl -d 'Get device info'
complete -c brightnessctl -d 'Get current brightness of device'
complete -c brightnessctl -d 'Get maximum brightness of device'
complete -c brightnessctl -d 'Set brightness of device'
complete -c brightnessctl -s 'h' -l 'help' -d 'Print help and exit'
complete -c brightnessctl -s 'l' -l 'list' -d 'List devices with available brightness controls'
complete -c brightnessctl -s 'q' -l 'quiet' -d 'Supress output'
complete -c brightnessctl -s 'p' -l 'pretend' -d 'Do not perform write operations'
complete -c brightnessctl -s 'm' -l 'machine-readable' -d 'Produce machine-readable output'
complete -c brightnessctl -s 'n' -l 'min-value' -d 'Set minimum brightness when using delta values'
complete -c brightnessctl -s 'e' -l 'exponent' -d 'Set exponent for exponential scaling curve'
complete -c brightnessctl -s 's' -l 'save' -d 'Save state in a temporary file'
complete -c brightnessctl -s 'r' -l 'restore' -d 'Restore previously-saved state'
complete -c brightnessctl -s 'c' -l 'class' -d 'Specify device class'
complete -c brightnessctl -s 'v' -l 'version' -d 'Print version and exit'
