complete -c bru -s 'h' -l 'help' -d 'Show help'
complete -c bru -l 'version' -d 'Show version number'
complete -c bru -d 'Run a request'
complete -c bru -s 'r' -d 'Indicates a recursive run'
complete -c bru -l 'cacert' -d 'CA certificate to verify peer against'
complete -c bru -l 'env' -d 'Environment variables'
complete -c bru -l 'env-var' -d 'Overwrite a single environment variable, multiple usages possible'
complete -c bru -s 'o' -l 'output' -d 'Path to write file results to'
complete -c bru -s 'f' -l 'format' -d 'Format of the file results'
complete -c bru -l 'insecure' -d 'Allow insecure connections'
complete -c bru -l 'tests-only' -d 'Only run requests that have a test'
complete -c bru -l 'bail' -d 'Stop execution after a failure of a request, test or assertion'
