complete -c btrbk -l 'format' -d 'Change output format'
complete -c btrbk -l 'loglevel' -s 'l' -d 'Set logging level'
complete -c btrbk -l 'exclude' -d 'Exclude configured sections'
complete -c btrbk -l 'override' -d 'Globally override a configuration option'
complete -c btrbk -l 'config' -s 'c' -d 'Specify configuration file'
complete -c btrbk -l 'lockfile' -d 'Create and check lockfile'
complete -c btrbk -l 'help' -s 'h' -d 'Display this help message'
complete -c btrbk -l 'version' -d 'Display version information'
complete -c btrbk -l 'dry-run' -s 'n' -d 'Perform a trial run with no changes made'
complete -c btrbk -l 'preserve' -s 'p' -d 'Preserve all (do not delete anything)'
complete -c btrbk -l 'preserve-snapshots' -d 'Preserve snapshots (do not delete snapshots)'
complete -c btrbk -l 'preserve-backups' -d 'Preserve backups (do not delete backups)'
complete -c btrbk -l 'wipe' -d 'Delete all but latest snapshots'
complete -c btrbk -l 'verbose' -s 'v' -d 'Be more verbose (increase logging level)'
complete -c btrbk -l 'quiet' -s 'q' -d 'Be quiet (do not print backup summary)'
complete -c btrbk -l 'table' -s 't' -d 'Change output to table format'
complete -c btrbk -l 'long' -s 'L' -d 'Change output to long format'
complete -c btrbk -l 'print-schedule' -s 'S' -d 'Print scheduler details (for the "run" command)'
complete -c btrbk -l 'progress' -d 'Show progress bar on send-receive operation'
complete -c btrbk -l 'single-column' -s '1' -d 'Print output as a single column'
complete -c btrbk -l 'pretty' -d 'Print pretty table output with lowercase and underlined column headings'
complete -c btrbk -l 'raw' -d 'Create raw targets for archive command'
complete -c btrbk -d 'Run snapshot and backup operations'
complete -c btrbk -d 'Show what would be executed without running btrfs commands'
complete -c btrbk -d 'Run snapshot operations only'
complete -c btrbk -d 'Run backup operations and delete snapshots'
complete -c btrbk -d 'Only delete snapshots and backups'
complete -c btrbk -d 'Recursively copy all subvolumes (src -> dst)'
complete -c btrbk -d 'Delete incomplete (garbled) backups'
complete -c btrbk -d 'Print snapshot/backup statistics'
complete -c btrbk -d 'Print filesystem usage'
complete -c btrbk -d 'List all btrfs subvolumes below a given path'
complete -c btrbk -d 'Print origin information for a subvolume'
complete -c btrbk -d 'List file changes between related subvolumes'
complete -c btrbk -d 'Calculate accurate disk space usage for a path'
complete -c btrbk -d 'List snapshots and backups'
complete -c btrbk -d 'List all snapshots and backups'
complete -c btrbk -d 'List snapshots only'
complete -c btrbk -d 'List backups and correlated snapshots'
complete -c btrbk -d 'List most recent snapshots and backups'
complete -c btrbk -d 'List configured source/snapshot/target relations'
complete -c btrbk -d 'List configured source/snapshot relations'
complete -c btrbk -d 'List configured volume sections'
complete -c btrbk -d 'List configured targets'
