complete -c btrfs -l 'help' -d 'Display help information'
complete -c btrfs -d 'Check structural integrity of a filesystem (unmounted).'
complete -c btrfs -d 'Try to restore files from a damaged filesystem (unmounted)'
complete -c btrfs -d 'Send the subvolume(s) to stdout.'
complete -c btrfs -d 'Receive subvolumes from a stream'
complete -c btrfs -d 'Display help information'
complete -c btrfs -d 'Display btrfs-progs version'
complete -c btrfs -d 'manage subvolumes: create, delete, list, etc'
complete -c btrfs -d 'overall filesystem tasks and information'
complete -c btrfs -d 'balance data across devices, or change block groups using filters'
complete -c btrfs -d 'manage and query devices in the filesystem'
complete -c btrfs -d 'verify checksums of data and metadata'
complete -c btrfs -d 'toolbox for specific rescue operations'
complete -c btrfs -d 'query various internal information'
complete -c btrfs -d 'modify properties of filesystem objects'
complete -c btrfs -d 'manage filesystem quota settings'
complete -c btrfs -d 'manage quota groups'
complete -c btrfs -d 'replace a device in the filesystem'
complete -c btrfs -s 's' -l 'super' -d 'Use this SUPERBLOCK copy'
complete -c btrfs -s 'b' -l 'backup' -d 'Use the first valid BACKUP root copy'
complete -c btrfs -s 'r' -l 'tree-root' -d 'Use the given bytenr for the TREE root'
complete -c btrfs -l 'chunk-root' -d 'Use the given bytenr for the CHUNK-TREE root'
complete -c btrfs -l 'readonly' -d 'Run in read-only mode'
complete -c btrfs -l 'repair' -d 'Try to repair the filesystem'
complete -c btrfs -l 'force' -d 'Skip mount checks, repair is not possible'
complete -c btrfs -l 'mode' -d 'Allows choice of memory/IO trade-offs'
complete -c btrfs -l 'init-csum-tree' -d 'Create a new CRC tree (repair only)'
complete -c btrfs -l 'init-extent-tree' -d 'Create a new extent tree (repair only)'
complete -c btrfs -l 'clear-space-cache' -d 'clear space cache (repair only)'
complete -c btrfs -l 'check-data-csum' -d 'Verify checksums of data blocks'
complete -c btrfs -s 'Q' -l 'qgroup-report' -d 'Print a report on qgroup consistency'
complete -c btrfs -s 'E' -l 'subvol-extents' -d 'Print subvolume extents and sharing state'
complete -c btrfs -s 'p' -l 'progress' -d 'Indicate progress'
complete -c btrfs -s 's' -l 'snapshots' -d 'Get snapshots'
complete -c btrfs -s 'x' -l 'xattr' -d 'Restore extended attributes'
complete -c btrfs -s 'm' -l 'metadata' -d 'Restore owner, mode and times'
complete -c btrfs -s 'S' -l 'symlink' -d 'Restore symbolic links'
complete -c btrfs -s 'v' -l 'verbose' -d 'Verbose'
complete -c btrfs -s 'i' -l 'ignore-errors' -d 'Ignore errors'
complete -c btrfs -s 'o' -l 'overwrite' -d 'Overwrite'
complete -c btrfs -s 't' -d 'Tree location'
complete -c btrfs -s 'f' -d 'Filesystem location'
complete -c btrfs -s 'u' -l 'super' -d 'Super mirror'
complete -c btrfs -s 'r' -l 'root' -d 'Root objectid'
complete -c btrfs -s 'd' -d 'Find dir'
complete -c btrfs -s 'l' -l 'list-roots' -d 'List tree roots'
complete -c btrfs -s 'D' -l 'dry-run' -d 'Only list files that would be recovered'
complete -c btrfs -l 'path-regex' -d 'Restore only filenames matching regex'
complete -c btrfs -s 'c' -d 'Ignore case (--path-regex only)'
complete -c btrfs -s 'e' -d ''
complete -c btrfs -s 'p' -d 'Send an incremental stream from <parent> to <subvol>'
complete -c btrfs -s 'c' -d 'Use this snapshot as a clone source for an incremental send'
complete -c btrfs -s 'f' -d 'Output is normally written to stdout'
complete -c btrfs -l 'no-data' -d 'send in NO_FILE_DATA mode'
complete -c btrfs -s 'v' -l 'verbose' -d 'Enable verbose output to stderr'
complete -c btrfs -s 'q' -l 'quiet' -d 'Suppress all messages, except errors'
complete -c btrfs -l 'proto' -d 'Use send protocol version'
complete -c btrfs -l 'proto' -l 'compressed-data' -d 'Send compressed data directly'
complete -c btrfs -s 'v' -d 'Increase verbosity about performed actions'
complete -c btrfs -s 'q' -l 'quiet' -d 'Suppress all messages, except errors'
complete -c btrfs -s 'f' -d 'Read the stream from FILE instead of stdin'
complete -c btrfs -s 'e' -d 'Terminate after receiving an <end cmd> marker in the stream'
complete -c btrfs -s 'C' -l 'chroot' -d 'Confine the process to <mount> using chroot'
complete -c btrfs -s 'E' -l 'max-errors' -d 'Terminate when NUMBER errors occur'
complete -c btrfs -s 'm' -d 'The root mount point of the destination filesystem'
complete -c btrfs -l 'force-decompress' -d 'Always decompress data'
complete -c btrfs -l 'dump' -d 'Dump stream metadata'
complete -c btrfs -l 'full' -d 'Display detailed help on every command'
complete -c btrfs -l 'box' -d 'Show list of built-in tools (busybox style)'
complete -c btrfs -d 'Create a subvolume'
complete -c btrfs -d 'Delete subvolume(s)'
complete -c btrfs -d 'List subvolumes and snapshots in the filesystem.'
complete -c btrfs -d 'Create a snapshot of the subvolume'
complete -c btrfs -d 'Get the default subvolume of a filesystem'
complete -c btrfs -d 'Set the default subvolume of the filesystem mounted as default.'
complete -c btrfs -d 'List the recently modified files in a filesystem'
complete -c btrfs -d 'Show more information about the subvolume'
complete -c btrfs -d 'Wait until given subvolume(s) are completely removed from the filesystem.'
complete -c btrfs -s 'i' -d 'Add subvolume to a qgroup (can be given multiple times)'
complete -c btrfs -s 'p' -d 'Create any missing parent directories'
complete -c btrfs -s 'c' -l 'commit-after' -d 'Wait for transaction commit at the end of the operation'
complete -c btrfs -s 'C' -l 'commit-each' -d 'Wait for transaction commit after deleting each subvolume'
complete -c btrfs -s 'R' -l 'recursive' -d 'Delete subvolumes beneath each subvolume recursively'
complete -c btrfs -s 'v' -l 'verbose' -d 'Verbose output of operations'
complete -c btrfs -s 'o' -d 'Print only subvolumes below specified path'
complete -c btrfs -s 'a' -d 'Print all the subvolumes and absolute and relative path'
complete -c btrfs -s 'p' -d 'Print parent ID'
complete -c btrfs -s 'c' -d 'Print the ogeneration of the subvolume'
complete -c btrfs -s 'g' -d 'Print the generation of the subvolume'
complete -c btrfs -s 'u' -d 'Print the uuid of subvolumes (and snapshots)'
complete -c btrfs -s 'q' -d 'Print the parent uuid of the snapshots'
complete -c btrfs -s 'R' -d 'Print the uuid of the received snapshots'
complete -c btrfs -s 's' -d 'List only snapshots'
complete -c btrfs -s 'r' -d 'List readonly subvolumes (including snapshots)'
complete -c btrfs -s 'd' -d 'List deleted subvolumes that are not yet cleaned'
complete -c btrfs -s 't' -d 'Print the result as a table'
complete -c btrfs -s 'G' -d 'Filter the subvolumes by generation'
complete -c btrfs -s 'C' -d 'Filter the subvolumes by ogeneration'
complete -c btrfs -l 'sort' -d 'List the subvolume in order'
complete -c btrfs -s 'r' -d 'Create a readonly snapshot'
complete -c btrfs -s 'i' -d 'Add snapshot to a qgroup (can be given multiple times)'
complete -c btrfs -s 'r' -l 'rootid' -d 'Show rootid of the subvolume'
complete -c btrfs -s 'u' -l 'uuid' -d 'Show uuid of the subvolume'
complete -c btrfs -s 'b' -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -s 'h' -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -s 'H' -d 'Show human friendly numbers, base 1000'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -s 'k' -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -s 'm' -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -s 'g' -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -s 't' -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -s 's' -d 'Sleep NUMBER seconds between checks'
complete -c btrfs -d 'Show space usage information for a mount point'
complete -c btrfs -d 'Summarize disk usage of each file.'
complete -c btrfs -d 'Show the structure of a filesystem'
complete -c btrfs -d 'Force a sync on a filesystem'
complete -c btrfs -d 'Defragment a file or a directory'
complete -c btrfs -d 'Resize a filesystem'
complete -c btrfs -d 'Get or change the label of a filesystem'
complete -c btrfs -d 'Show detailed information about internal filesystem usage.'
complete -c btrfs -d 'Create a new swapfile'
complete -c btrfs -s 'b' -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -s 'h' -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -s 'H' -d 'Show human friendly numbers, base 1000'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -s 'k' -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -s 'm' -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -s 'g' -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -s 't' -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -s 's' -l 'summarize' -d 'Display only a total for each argument'
complete -c btrfs -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -s 'd' -l 'all-devices' -d 'Show only disks under /dev containing btrfs filesystem'
complete -c btrfs -s 'm' -l 'mounted' -d 'Show only mounted btrfs'
complete -c btrfs -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -s 'v' -d 'Be verbose'
complete -c btrfs -s 'r' -d 'Defragment files recursively'
complete -c btrfs -s 'c' -d 'Compress the file while defragmenting'
complete -c btrfs -s 'f' -d 'Flush data to disk immediately after defragmenting'
complete -c btrfs -s 's' -d 'Defragment only from NUMBER byte onward'
complete -c btrfs -s 'l' -d 'Defragment only up to LEN bytes'
complete -c btrfs -s 't' -d 'Target extent SIZE hint'
complete -c btrfs -l 'step' -d 'Defragment in steps of SIZE'
complete -c btrfs -s 'L' -l 'level' -d 'Specify compression levels'
complete -c btrfs -s 'b' -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -s 'h' -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -s 'H' -d 'Show human friendly numbers, base 1000'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -s 'k' -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -s 'm' -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -s 'g' -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -s 't' -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -s 'T' -d 'Show data in tabular format'
complete -c btrfs -s 's' -l 'size' -d 'Swapfile size'
complete -c btrfs -s 'U' -l 'uuid' -d 'UUID for the swapfile'
complete -c btrfs -l 'enqueue' -d 'Wait for other exclusive operations'
complete -c btrfs -d 'Balance chunks across the devices'
complete -c btrfs -d 'Pause running balance'
complete -c btrfs -d 'Cancel running or paused balance'
complete -c btrfs -d 'Resume interrupted balance'
complete -c btrfs -d 'Show status of running or paused balance'
complete -c btrfs -s 'd' -d 'Act on data chunks with FILTERS'
complete -c btrfs -s 'm' -d 'Act on metadata chunks with FILTERS'
complete -c btrfs -s 's' -d 'Act on system chunks with FILTERS (only under -f)'
complete -c btrfs -s 'v' -d 'Be verbose'
complete -c btrfs -s 'f' -d 'Force a reduction of metadata integrity'
complete -c btrfs -l 'full-balance' -d 'Do not print warning and do not delay start'
complete -c btrfs -l 'background' -l 'bg' -d 'Run the balance as a background process'
complete -c btrfs -l 'enqueue' -d 'Wait for other exclusive operations'
complete -c btrfs -s 'v' -d 'Be verbose'
complete -c btrfs -d 'Add one or more devices to a mounted filesystem.'
complete -c btrfs -d 'Remove a device from a filesystem'
complete -c btrfs -d 'Remove a device from a filesystem'
complete -c btrfs -d 'Scan or forget (unregister) devices of btrfs filesystems'
complete -c btrfs -d 'Check and wait until a group of devices of a filesystem is ready for mount'
complete -c btrfs -d 'Show device IO error statistics'
complete -c btrfs -d 'Show detailed information about internal allocations in devices.'
complete -c btrfs -s 'K' -l 'nodiscard' -d 'Do not perform TRIM on DEVICES'
complete -c btrfs -s 'f' -l 'force' -d 'Force overwrite existing filesystem on the disk'
complete -c btrfs -s 'd' -l 'all-devices' -d 'Enumerate and register all devices'
complete -c btrfs -s 'u' -l 'forget' -d 'Unregister a given device or all stale devices'
complete -c btrfs -s 'c' -l 'check' -d 'Return non-zero if any stat counter is not zero'
complete -c btrfs -s 'z' -l 'reset' -d 'Show current stats and reset values to zero'
complete -c btrfs -s 'T' -d 'Print stats in a tabular form'
complete -c btrfs -l 'enqueue' -d 'Wait for other exclusive operations'
complete -c btrfs -l 'force' -d 'Skip the safety timeout for removing multiple devices'
complete -c btrfs -s 'b' -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -s 'h' -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -s 'H' -d 'Show human friendly numbers, base 1000'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -s 'k' -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -s 'm' -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -s 'g' -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -s 't' -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -d 'Start a new scrub. If a scrub is already running, the new one fails.'
complete -c btrfs -d 'Cancel a running scrub'
complete -c btrfs -d 'Resume previously canceled or interrupted scrub'
complete -c btrfs -d 'Show status of running or finished scrub'
complete -c btrfs -d 'Show or set scrub limits on devices of the given filesystem'
complete -c btrfs -s 'd' -l 'devid' -d 'Select the device by DEVID to apply the limit'
complete -c btrfs -s 'l' -l 'limit' -d 'Set the limit of the device'
complete -c btrfs -s 'a' -l 'all' -d 'Apply the limit to all devices'
complete -c btrfs -s 'B' -d 'Do not background'
complete -c btrfs -s 'd' -d 'Stats per device (-B only)'
complete -c btrfs -s 'q' -d 'Be quiet'
complete -c btrfs -s 'r' -d 'Read only mode'
complete -c btrfs -s 'R' -d 'Raw print mode, print full data instead of summary'
complete -c btrfs -l 'limit' -d 'Set the scrub throughput limit'
complete -c btrfs -s 'c' -d 'Set ioprio class (see ionice(1) manpage)'
complete -c btrfs -s 'n' -d 'Set ioprio classdata (see ionice(1) manpage)'
complete -c btrfs -s 'f' -d 'Force starting new scrub'
complete -c btrfs -s 'B' -d 'Do not background'
complete -c btrfs -s 'd' -d 'Stats per device (-B only)'
complete -c btrfs -s 'q' -d 'Be quiet'
complete -c btrfs -s 'r' -d 'Read only mode'
complete -c btrfs -s 'R' -d 'Raw print mode, print full data instead of summary'
complete -c btrfs -s 'c' -d 'Set ioprio class (see ionice(1) manpage)'
complete -c btrfs -s 'n' -d 'Set ioprio classdata (see ionice(1) manpage)'
complete -c btrfs -s 'd' -d 'Stats per DEVICE'
complete -c btrfs -s 'R' -d 'Print raw stats'
complete -c btrfs -d 'Recover the chunk tree by scanning the devices one by one.'
complete -c btrfs -d 'Recover bad superblocks from good copies'
complete -c btrfs -d 'Re-align device and super block sizes'
complete -c btrfs -d 'Remove leftover items pertaining to the deprecated inode cache feature'
complete -c btrfs -d 'Completely remove the on-disk data of free space cache of given version'
complete -c btrfs -d 'Clear the UUID tree'
complete -c btrfs -s 'y' -d 'Assume an answer of YES to all questions'
complete -c btrfs -s 'v' -d 'Verbose mode'
complete -c btrfs -s 'y' -d 'Assume an answer of YES to all questions'
complete -c btrfs -s 'v' -d 'Verbose mode'
complete -c btrfs -d 'Get file system paths for the given inode'
complete -c btrfs -d 'Get file system paths for the given logical address'
complete -c btrfs -d 'Get file system paths for the given subvolume ID.'
complete -c btrfs -d 'Get tree ID of the containing subvolume of path.'
complete -c btrfs -d 'Get the minimum size the device can be shrunk to. (Default: 1)'
complete -c btrfs -d 'Dump tree structures from a given device'
complete -c btrfs -d 'Dump superblock from a device in a textual form'
complete -c btrfs -d 'Print various stats for trees'
complete -c btrfs -d 'Enumerate chunks on all devices'
complete -c btrfs -d 'Find device-specific physical offset of file that can be used for hibernation'
complete -c btrfs -s 'v' -d 'Verbose mode'
complete -c btrfs -s 'P' -d 'Skip the path resolving and print the inodes instead'
complete -c btrfs -s 'v' -d 'Verbose mode'
complete -c btrfs -l 'id' -d 'Specify the DEVICE-ID to query'
complete -c btrfs -s 'e' -l 'extents' -d 'Print only extent info: extent and device trees'
complete -c btrfs -s 'd' -l 'device' -d 'Print only device info: tree root, chunk and device trees'
complete -c btrfs -s 'r' -l 'roots' -d 'Print only short root node info'
complete -c btrfs -s 'R' -l 'backups' -d 'Print short root node info and backup root info'
complete -c btrfs -s 'u' -l 'uuid' -d 'Print only the uuid tree'
complete -c btrfs -s 'b' -l 'block' -d 'Print info from the specified BLOCK only'
complete -c btrfs -s 't' -l 'tree' -d 'Print only tree with the given ID'
complete -c btrfs -l 'follow' -d 'Use with -b, to show all children tree blocks of <block_num>'
complete -c btrfs -l 'noscan' -d 'Do not scan the devices from the filesystem'
complete -c btrfs -l 'bfs' -d 'Breadth-first traversal of the trees, print nodes, then leaves'
complete -c btrfs -l 'dfs' -d 'Depth-first traversal of the trees'
complete -c btrfs -l 'hide-names' -d 'Print placeholder instead of names'
complete -c btrfs -l 'csum-headers' -d 'Print b-tree node checksums in headers'
complete -c btrfs -l 'csum-items' -d 'Print checksums stored in checksum items'
complete -c btrfs -s 'f' -l 'full' -d 'Print full superblock information, backup roots etc.'
complete -c btrfs -s 'a' -l 'all' -d 'Print information about all superblocks'
complete -c btrfs -s 's' -l 'super' -d 'Specify which SUPER-BLOCK copy to print out'
complete -c btrfs -s 'F' -l 'force' -d 'Attempt to dump superblocks with bad magic'
complete -c btrfs -l 'bytenr' -d 'Specify alternate superblock OFFSET'
complete -c btrfs -s 'P' -d 'Print inodes instead of resolving paths'
complete -c btrfs -s 'o' -d 'Ignore offsets, find all references to an extent'
complete -c btrfs -s 's' -d 'Set internal buffer size for storing file names'
complete -c btrfs -s 'b' -d 'Show raw numbers in bytes'
complete -c btrfs -l 'sort' -d 'Sort by a column (ascending)'
complete -c btrfs -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -l 'resume-offset' -s 'r' -d 'Print the value suitable as resume offset for /sys/power/resume_offset.'
complete -c btrfs -s 't' -d 'Print stats only for the given treeid'
complete -c btrfs -l 'raw' -s 'b' -d 'Show raw numbers in bytes'
complete -c btrfs -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -d 'Get a property value of a btrfs object'
complete -c btrfs -d 'Set a property on a btrfs object'
complete -c btrfs -d 'Lists available properties with their descriptions for the given object'
complete -c btrfs -s 't' -d 'List properties for the given object type'
complete -c btrfs -s 't' -d 'List properties for the given object type'
complete -c btrfs -s 't' -d 'List properties for the given object type'
complete -c btrfs -d 'Enable subvolume quota support for a filesystem.'
complete -c btrfs -d 'Disable subvolume quota support for a filesystem.'
complete -c btrfs -d 'Trash all qgroup numbers and scan the metadata again with the current config.'
complete -c btrfs -s 's' -l 'simple' -d 'Use simple quotas'
complete -c btrfs -s 's' -l 'status' -d 'Show status of a running rescan operation'
complete -c btrfs -s 'w' -l 'wait' -d 'Wait for rescan operation to finish'
complete -c btrfs -s 'W' -l 'wait-norescan' -d 'Wait for rescan to finish without starting it'
complete -c btrfs -d 'Assign SRC as the child qgroup of DST'
complete -c btrfs -d 'Remove a child qgroup SRC from DST.'
complete -c btrfs -d 'Create a subvolume quota group.'
complete -c btrfs -d 'Destroy a quota group.'
complete -c btrfs -d 'Show subvolume quota groups.'
complete -c btrfs -d 'Clear all stale qgroups whose subvolume does not exist'
complete -c btrfs -d 'Set the limits a subvolume quota group.'
complete -c btrfs -l 'rescan' -d 'Schedule qutoa rescan if needed'
complete -c btrfs -s 'p' -d 'Print parent qgroup id'
complete -c btrfs -s 'c' -d 'Print child qgroup id'
complete -c btrfs -s 'r' -d 'Print limit of referenced size of qgroup'
complete -c btrfs -s 'e' -d 'Print limit of exclusive size of qgroup'
complete -c btrfs -s 'F' -d 'List all qgroups including ancestral qgroups'
complete -c btrfs -s 'f' -d 'List all qgroups excluding ancestral qgroups'
complete -c btrfs -l 'raw' -d 'Show raw numbers in bytes'
complete -c btrfs -l 'human-readable' -d 'Show human friendly numbers, base 1024'
complete -c btrfs -l 'iec' -d 'Use 1024 as a base (KiB, MiB, GiB, TiB)'
complete -c btrfs -l 'si' -d 'Use 1000 as a base (kB, MB, GB, TB)'
complete -c btrfs -l 'kbytes' -d 'Show sizes in KiB, or kB with --si'
complete -c btrfs -l 'mbytes' -d 'Show sizes in MiB, or MB with --si'
complete -c btrfs -l 'gbytes' -d 'Show sizes in GiB, or GB with --si'
complete -c btrfs -l 'tbytes' -d 'Show sizes in TiB, or TB with --si'
complete -c btrfs -l 'sort' -d 'List qgroups sorted by specified items'
complete -c btrfs -l 'sync' -d 'Force sync of the filesystem before getting info'
complete -c btrfs -s 'c' -d 'Limit amount of data after compression'
complete -c btrfs -s 'e' -d 'Limit space exclusively assigned to this qgroup'
complete -c btrfs -d 'Replace device of a btrfs filesystem.'
complete -c btrfs -d 'Print status and progress information of a running device replace'
complete -c btrfs -d 'Cancel a running device replace operation.'
complete -c btrfs -s 'r' -d 'Only read from <srcdev> if no other zero-defect mirror exists'
complete -c btrfs -s 'f' -d 'Force using and overwriting <targetdev>'
complete -c btrfs -s 'B' -d 'Do not background'
complete -c btrfs -l 'enqueue' -d 'Wait if there'"'"'s another exclusive operation running'
complete -c btrfs -s 'K' -l 'nodiscard' -d 'Do not perform TRIM on DEVICES'
complete -c btrfs -s '1' -d 'Only print once until the replace operation finishes'
