complete -c busctl -l 'quiet' -d 'Suppress message payload display'
complete -c busctl -l 'verbose'
complete -c busctl -l 'list' -d 'Show a flat list instead of a tree'
complete -c busctl -l 'expect-reply'
complete -c busctl -l 'auto-start' -d 'Activate the peer if necessary'
complete -c busctl -l 'allow-interactive-authorization'
complete -c busctl -l 'timeout'
complete -c busctl -l 'unique' -d 'Only show unique (:X.Y) names'
complete -c busctl -l 'acquired' -d 'Only show well-known names'
complete -c busctl -l 'activatable' -d 'Only show peers that have not been activated yet but can be'
complete -c busctl -l 'show-machine' -d 'Show the machine the peers belong to'
complete -c busctl -l 'augment-creds'
complete -c busctl -l 'user'
complete -c busctl -l 'system'
complete -c busctl -s 'H' -l 'host'
complete -c busctl -s 'M' -l 'machine'
complete -c busctl -l 'no-pager'
complete -c busctl -l 'no-legend'
complete -c busctl -s 'h' -l 'help'
complete -c busctl -l 'version'
