complete -c bzr -d 'Show help'
complete -c bzr -d 'List all help topics'
complete -c bzr -d 'List all commands'
complete -c bzr -d 'Help about supported formats'
complete -c bzr -d 'Help about current supported formats'
complete -c bzr -d 'How to specify revisions in bzr'
complete -c bzr -d 'Show bug tracker settings in bzr'
complete -c bzr -d 'Makes this directory a versioned branch'
complete -c bzr -l 'create-prefix' -d 'Create the path leading up to the branch if it does not already exists'
complete -c bzr -l 'no-tree' -d 'Create a branch without a working tree'
complete -c bzr -l 'append-revisions-only' -d 'Never change revnos or the existing log. Append revisions to it only'
complete -c bzr -d 'Make a copy of another branch'
complete -c bzr -l 'use-existing-dir' -d 'Proceed even if directory exits'
complete -c bzr -l 'stacked' -d 'Create a stacked branch referring to the source branch'
complete -c bzr -l 'standalone' -d 'Do not use a shared repository, even if available'
complete -c bzr -l 'switch' -d 'Switch the checkout in the current directory to the new branch'
complete -c bzr -l 'hardlink' -d 'Hard-link working tree files where possible'
complete -c bzr -l 'bind' -d 'Bind new branch to from location'
complete -c bzr -l 'no-tree' -d 'Create a branch without a working-tree'
complete -c bzr -d 'Make files or directories versioned'
complete -c bzr -d 'Ignore a file or pattern'
complete -c bzr -l 'default-rules' -d 'Display the default ignore rules that bzr uses'
complete -c bzr -d 'Move or rename a versioned file'
complete -c bzr -l 'auto' -d 'Automatically guess renames'
complete -c bzr -l 'after' -d 'Move only the bzr identifier of the file, because the file has already been moved'
complete -c bzr -d 'Summarize changes in working copy'
complete -c bzr -l 'short' -s 'S' -d 'Use short status indicators'
complete -c bzr -l 'versioned' -s 'V' -d 'Only show versioned files'
complete -c bzr -l 'no-classify' -d 'Do not mark object type using indicator'
complete -c bzr -l 'show-ids' -d 'Show internal object ids'
complete -c bzr -d 'Show detailed diffs'
complete -c bzr -d 'Pull in changes from another branch'
complete -c bzr -l 'pull' -d 'If destination is already merged, pull rather than merging'
complete -c bzr -l 'remember' -d 'Remember the specified location as a default'
complete -c bzr -l 'force' -d 'Merge even if the destination tree has uncommitted changes'
complete -c bzr -l 'reprocess' -d 'Reprocess to reduce spurious conflicts'
complete -c bzr -l 'uncommitted' -d 'Apply uncommitted changes from a working copy, instead of branch changes'
complete -c bzr -l 'show-base' -d 'Show base revision text in conflicts'
complete -c bzr -l 'preview' -d 'Instead of merging, show a diff of the merge'
complete -c bzr -l 'interactive' -s 'i' -d 'Select changes interactively'
complete -c bzr -l 'directory' -s 'd' -d 'Branch to merge into, rather than the one containing the working directory'
complete -c bzr -l 'change' -s 'c' -d 'Select changes introduced by the specified revision'
complete -c bzr -l 'revision' -s 'r' -d 'Select changes introduced by the specified revision'
complete -c bzr -d 'Save some or all changes'
complete -c bzr -l 'show-diff' -s 'p' -d 'When no message is supplied, show diff along with status summary in message editor'
complete -c bzr -l 'file' -s 'F' -d 'Take commit message from this file'
complete -c bzr -l 'exclude' -s 'x' -d 'Do not consider changes made to a given path'
complete -c bzr -l 'message' -s 'm' -d 'Description of the new revision'
complete -c bzr -l 'commit-time' -d 'Manually set a commit time using commit date format'
complete -c bzr -l 'unchanged' -d 'Commit even if nothing has changed'
complete -c bzr -l 'fixes' -d 'Mark a bug as being fixed by this revision'
complete -c bzr -l 'strict' -d 'Refuse to commit if there are unknown files in the working tree'
complete -c bzr -l 'lossy' -d 'When committing to a foreign vcs do not push data that can not be natively represented'
complete -c bzr -l 'local' -d 'Perform a local commit in a bound branch (pushed to master on normal commit)'
complete -c bzr -d 'Send changes via email'
complete -c bzr -l 'body' -d 'Body for the email'
complete -c bzr -l 'remember' -d 'Remember submit and public branch'
complete -c bzr -l 'mail-to' -d 'Mail the request to this address'
complete -c bzr -l 'format' -d 'Use the specified output format'
complete -c bzr -l 'no-bundle' -d 'Do not include a bundle in the merge directive'
complete -c bzr -l 'strict' -d 'Refuse to send if there are uncommitted changes in the working tree'
complete -c bzr -l 'no-patch' -d 'Do not include a preview patch in the merge directive'
complete -c bzr -d 'Show history of changes'
complete -c bzr -d 'Validate storage'
complete -c bzr -l 'tree' -d 'Check the working tree related to the current directory'
complete -c bzr -l 'repo' -d 'Check the repository related to the current directory'
complete -c bzr -l 'branch' -d 'Check the branch related to the current directory'
complete -c bzr -l 'usage' -d 'Show usage message and options'
complete -c bzr -s 'h' -l 'help' -d 'Show help message'
complete -c bzr -s 'q' -l 'quiet' -d 'Only displays errors and warnings'
complete -c bzr -s 'v' -l 'verbose' -d 'Display more information'
complete -c bzr -l 'dry-run' -d 'Show what would be done'
