complete -c caddy -d 'Agree to the CA'"'"'s Subscriber Agreement'
complete -c caddy -d 'URL to certificate authority'"'"'s ACME server directory'
complete -c caddy -d 'Default ACME CA HTTP timeout'
complete -c caddy -d 'Caddyfile to load'
complete -c caddy -d 'CPU cap'
complete -c caddy -d 'Disable the ACME HTTP challenge'
complete -c caddy -d 'Disable the ACME TLS-SNI challenge'
complete -c caddy -d 'Default ACME CA account email address'
complete -c caddy -d 'Maximum duration of graceful shutdown'
complete -c caddy -d 'Default host'
complete -c caddy -d 'Default port to use for HTTP'
complete -c caddy -d 'Use HTTP/2'
complete -c caddy -d 'Default port to use for HTTPS'
complete -c caddy -d 'Process log file'
complete -c caddy -d 'Path to write pid file'
complete -c caddy -d 'List installed plugins'
complete -c caddy -d 'Default port'
complete -c caddy -d 'Use experimental QUIC'
complete -c caddy -d 'Quiet mode (no initialization output)'
complete -c caddy -d 'Hostname for which to revoke the certificate'
complete -c caddy -d 'Root path of default site'
complete -c caddy -d 'Type of server to run'
complete -c caddy -d 'Parse the Caddyfile but do not start the server'
complete -c caddy -d 'Show version'
