complete -c canto -s 'h' -l 'help' -d 'Show Help'
complete -c canto -s 'v' -l 'version' -d 'Show version'
complete -c canto -s 'u' -l 'update' -d 'Update before running'
complete -c canto -s 'l' -l 'list' -d 'List feeds'
complete -c canto -s 'a' -l 'checkall' -d 'Show number of new items'
complete -c canto -s 'n' -l 'checknew' -d 'Show number of new items for feed'
complete -c canto -d 'Feed'
complete -c canto -s 'o' -l 'opml' -d 'Print conf as OPML'
complete -c canto -s 'i' -l 'import' -d 'Import from OPML'
complete -c canto -s 'r' -l 'url' -d 'Add feed'
complete -c canto -s 'D' -l 'dir' -d 'Set configuration directory'
complete -c canto -s 'C' -l 'conf' -d 'Set configuration file'
complete -c canto -s 'L' -l 'log' -d 'Set client log file'
complete -c canto -s 'F' -l 'fdir' -d 'Set feed directory'
complete -c canto -s 'S' -l 'sdir' -d 'Set script directory'
