complete -c castnow -l 'tomp4' -d 'Convert file to mp4 during playback'
complete -c castnow -l 'device' -d 'Specify name of Chromecast device to be used'
complete -c castnow -l 'address' -d 'Specify IP or hostname of Chromecast device'
complete -c castnow -l 'subtitles' -d 'Path or URL to SRT or VTT file'
complete -c castnow -l 'subtitles-scale' -d 'Set subtitles font scale'
complete -c castnow -l 'subtitles-color' -d 'Set subtitles font RGBA color'
complete -c castnow -l 'subtitles-port' -d 'Specify port to be used for serving subtitles'
complete -c castnow -l 'myip' -d 'Set local IP'
complete -c castnow -l 'quiet' -d 'No output'
complete -c castnow -l 'type' -d 'Explicitly set the mime-type'
complete -c castnow -l 'bypass-srt-encoding' -d 'Disable automatic UTF-8 encoding of SRT subtitles'
complete -c castnow -l 'seek' -d 'Seek to specified time (format: [hh:]mm:ss)'
complete -c castnow -l 'loop' -d 'Loop over playlist, or file'
complete -c castnow -l 'shuffle' -d 'Play in random order'
complete -c castnow -l 'recursive' -d 'List all files in directories recursively'
complete -c castnow -l 'volume-step' -d 'Set at which the volume changes'
complete -c castnow -l 'localfile-port' -d 'Specify port to be used for serving local file'
complete -c castnow -l 'transcode-port' -d 'Specify port to be used for serving transcoded file'
complete -c castnow -l 'torrent-port' -d 'Specify port to be used for serving torrented file'
complete -c castnow -l 'stdin-port' -d 'Specify port to be used for serving file read from stdin'
complete -c castnow -l 'command' -d 'Execute key command(s)'
complete -c castnow -l 'exit' -d 'Exit when playback begins or --command completes'
complete -c castnow -l 'help' -d 'Display help'
