complete -c cdrecord -d 'Display version'
complete -c cdrecord -s 'v' -d 'Increment the level of general verbosity by one'
complete -c cdrecord -s 'V' -d 'Increment the verbose level in respect of SCSI command transport by one'
complete -c cdrecord -d 'Set the misc debug value to #'
complete -c cdrecord -s 'd' -d 'Increment the misc debug level by one'
complete -c cdrecord -s 's' -d 'Do not print out a status report for failed SCSI commands'
complete -c cdrecord -d 'Force to continue on some errors'
complete -c cdrecord -d 'Set the SCSI IMMED flag in certain commands'
complete -c cdrecord -d 'Minimum drive buffer fill ratio for the ATAPI wait mode'
complete -c cdrecord -d 'Complete CD/DVD-Recorder recording process with the laser turned off'
complete -c cdrecord -d 'Handle images created by readcd -clone'
complete -c cdrecord -d 'Set SAO (Session At Once) mode, usually called Disk At Once mode'
complete -c cdrecord -d 'Set TAO (Track At Once) writing mode'
complete -c cdrecord -d 'Set RAW writing mode'
complete -c cdrecord -d 'Select Set RAW writing, the preferred raw writing mode'
complete -c cdrecord -d 'Select Set RAW writing, the less preferred raw writing mode'
complete -c cdrecord -d 'Select Set RAW writing, the preferred raw writing mode after raw96r'
complete -c cdrecord -d 'Allow multi session CDs to be made'
complete -c cdrecord -d 'Retrieve multi session info in a form suitable for mkisofs-1.10 or later'
complete -c cdrecord -d 'Retrieve and print out the table of content or PMA of a CD'
complete -c cdrecord -d 'Retrieve and print out the ATIP (absolute Time in Pre-groove) info'
complete -c cdrecord -d 'Only fixate disk '
complete -c cdrecord -d 'Do not fixate the disk after writing the tracks'
complete -c cdrecord -d 'Wait for standard input to become available before opening the SCSI driver'
complete -c cdrecord -d 'Load the media'
complete -c cdrecord -d 'Load the media, lock the door'
complete -c cdrecord -d 'Eject disk after doing the work'
complete -c cdrecord -d 'Set the speed factor of the writing process to #'
complete -c cdrecord -d 'Blank a CD-RW and exit or blank a CD-RW before writing'
complete -c cdrecord -d 'Format a CD-RW/DVD-RW/DVD+RW disc'
complete -c cdrecord -d 'Set the FIFO (ring buffer) size to #'
complete -c cdrecord -d 'Set the maximum transfer size for a single SCSI command to #'
complete -c cdrecord -d 'Sets the SCSI target for the CD/DVD-Recorder'
complete -c cdrecord -d 'Set the grace time before starting to write to ># seconds'
complete -c cdrecord -d 'Set the default SCSI command timeout value to # seconds'
complete -c cdrecord -d 'Allows the user to manually select a driver for the device'
complete -c cdrecord -d 'Set driver specific options'
complete -c cdrecord -d 'Set driver specific options'
complete -c cdrecord -d 'Checks if a driver for the current drive is present'
complete -c cdrecord -d 'Print the drive capabilities for SCSI-3/mmc compliant drives'
complete -c cdrecord -d 'Do an inquiry for the drive, print the inquiry info'
complete -c cdrecord -d 'Scan all SCSI devices on all SCSI busses and print the inquiry strings'
complete -c cdrecord -d 'Try to reset the SCSI bus where the CD recorder is located'
complete -c cdrecord -d 'Try to send an abort sequence to the drive'
complete -c cdrecord -d 'Allow writing more than the official size of a medium'
complete -c cdrecord -d 'Ignore the known size of the medium, use for debugging only'
complete -c cdrecord -d 'Use *.inf files to overwrite audio options'
complete -c cdrecord -d 'Set default pre-gap size for all tracks except track nr 1'
complete -c cdrecord -d 'Set Packet writing mode'
complete -c cdrecord -d 'Set the packet size to #, forces fixed packet mode'
complete -c cdrecord -d 'Don'"'"'t close the current track, only when in packet writing mode'
complete -c cdrecord -d 'Set the Media Catalog Number of the CD'
complete -c cdrecord -d 'Write CD-Text info based on file containing ascii info'
complete -c cdrecord -d 'Write CD-Text based on info found in the binary file filename'
complete -c cdrecord -d 'Take all recording related info from a CDRWIN compliant CUE sheet file'
complete -c cdrecord -d 'Set the International Standard Recording Number for the next track'
complete -c cdrecord -d 'Sets an index list for the next track'
complete -c cdrecord -d 'Subsequent tracks are written in CD-DA format'
complete -c cdrecord -d 'Audio data is assumed to be in byte-swapped order'
complete -c cdrecord -d 'Subsequent tracks are written in CD-ROM mode 1 format'
complete -c cdrecord -d 'Subsequent tracks are written in CD-ROM mode 2 format'
complete -c cdrecord -d 'Subsequent tracks are written in CD-ROM XA mode 2 form 1 format'
complete -c cdrecord -d 'Subsequent tracks are written in CD-ROM XA mode 2 form 1 format'
complete -c cdrecord -d 'Subsequent tracks are written in CD-ROM XA mode 2 form 2 format'
complete -c cdrecord -d 'Subsequent tracks allows a mix of CD-ROM XA mode 2 form 1/2 format'
complete -c cdrecord -d 'The TOC type for the disk is set to CDI, with XA only'
complete -c cdrecord -d 'Use the ISO-9660 file system size as the size of the next track'
complete -c cdrecord -d 'Add 15 sectors of zeroed data to the end of this and subsequent tracks'
complete -c cdrecord -d 'Set the amount of data to be appended as padding to the next track'
complete -c cdrecord -d 'Do not pad the following tracks - the default'
complete -c cdrecord -d 'Allow all subsequent tracks to violate the Red Book track length standard'
complete -c cdrecord -d 'Re-enforce the Red Book track length standard'
complete -c cdrecord -d 'Set the pre-gap size for the next track'
complete -c cdrecord -d 'TOC indicates that data has been sampled with 50/15 microsec pre-emphasis'
complete -c cdrecord -d 'TOC indicates that data has been mastered with linear data'
complete -c cdrecord -d 'TOC indicates that data has permission to be copied without limit'
complete -c cdrecord -d 'TOC indicates that data has permission to be copied only once'
complete -c cdrecord -d 'TOC indicates that data has no permission to be copied'
complete -c cdrecord -d 'Specify valid amount of data on raw disk for next track'"'"'s master image'
