complete -c cf -d 'Show help'
complete -c cf -d 'Print the version'
complete -c cf -d 'Log user in'
complete -c cf -d 'Log user out'
complete -c cf -d 'Change user password'
complete -c cf -d 'Set or view the targeted org or space'
complete -c cf -d 'Set or view target api url'
complete -c cf -d 'Authenticate user non-interactively'
complete -c cf -d 'List all apps in the target space'
complete -c cf -d 'Display health and status for an app'
complete -c cf -d 'Push a new app or sync changes to an existing app'
complete -c cf -d 'Change or view the instance count, disk space limit, and memory limit for an app'
complete -c cf -d 'Delete an app'
complete -c cf -d 'Rename an app'
complete -c cf -d 'Start an app'
complete -c cf -d 'Stop an app'
complete -c cf -d 'Stop all instances of the app, then start them again'
complete -c cf -d 'Recreate the app'"'"'s executable artifact using the latest pushed app files and environment'
complete -c cf -d 'Terminate, then restart an app instance'
complete -c cf -d 'Run a one-off task on an app'
complete -c cf -d 'List tasks of an app'
complete -c cf -d 'Terminate a running task of an app'
complete -c cf -d 'Show recent app events'
complete -c cf -d 'Print out a list of files or contents of a specific file of an app running on the DEA backend'
complete -c cf -d 'Tail or show recent logs for an app'
complete -c cf -d 'Show all env variables for an app'
complete -c cf -d 'Set an env variable for an app'
complete -c cf -d 'Remove an env variable'
complete -c cf -d 'List all stacks (stack is a pre-built file system, including an OS, to run apps)'
complete -c cf -d 'Show stack info (stack is a pre-built file system, including an OS, to run apps)'
complete -c cf -d 'Copy the source to another existing app (and restart that)'
complete -c cf -d 'Create an app manifest for an app that has been pushed successfully'
complete -c cf -d 'Show the type of health check performed on an app'
complete -c cf -d 'Change type of health check performed on an app'
complete -c cf -d 'Enable ssh for the application'
complete -c cf -d 'Disable ssh for the application'
complete -c cf -d 'Reports whether SSH is enabled on an application container instance'
complete -c cf -d 'SSH to an application container instance'
complete -c cf -d 'List available offerings in the marketplace'
complete -c cf -d 'List all service instances in the target space'
complete -c cf -d 'Show service instance info'
complete -c cf -d 'Create a service instance'
complete -c cf -d 'Update a service instance'
complete -c cf -d 'Delete a service instance'
complete -c cf -d 'Rename a service instance'
complete -c cf -d 'Create key for a service instance'
complete -c cf -d 'List keys for a service instance'
complete -c cf -d 'Show service key info'
complete -c cf -d 'Delete a service key'
complete -c cf -d 'Bind a service instance to an app'
complete -c cf -d 'Unbind a service instance from an app'
complete -c cf -d 'Bind a service instance to an HTTP route'
complete -c cf -d 'Unbind a service instance from an HTTP route'
complete -c cf -d 'Make a user-provided service instance available to CF apps'
complete -c cf -d 'Update user-provided service instance'
complete -c cf -d 'List all orgs'
complete -c cf -d 'Show org info'
complete -c cf -d 'Create an org'
complete -c cf -d 'Delete an org'
complete -c cf -d 'Rename an org'
complete -c cf -d 'List all spaces in an org'
complete -c cf -d 'Show space info'
complete -c cf -d 'Create a space'
complete -c cf -d 'Delete a space'
complete -c cf -d 'Rename a space'
complete -c cf -d 'Allow SSH access for the space'
complete -c cf -d 'Disallow SSH access for the space'
complete -c cf -d 'Reports whether SSH is allowed in a space'
complete -c cf -d 'List domains in the target org'
complete -c cf -d 'Create a domain in an org for later use'
complete -c cf -d 'Delete a domain'
complete -c cf -d 'Create a domain that can be used by all orgs (admin-only)'
complete -c cf -d 'Delete a shared domain'
complete -c cf -d 'List router groups'
complete -c cf -d 'List all routes in the current space or the current organization'
complete -c cf -d 'Create a url route in a space for later use'
complete -c cf -d 'Perform a simple check to determine whether a route currently exists or not'
complete -c cf -d 'Add a url route to an app'
complete -c cf -d 'Remove a url route from an app'
complete -c cf -d 'Delete a route'
complete -c cf -d 'Delete all orphaned routes (i.e. those that are not mapped to an app)'
complete -c cf -d 'List direct network traffic policies'
complete -c cf -d 'Create policy to allow direct network traffic from one app to another'
complete -c cf -d 'Remove network traffic policy of an app'
complete -c cf -d 'List all buildpacks'
complete -c cf -d 'Create a buildpack'
complete -c cf -d 'Update a buildpack'
complete -c cf -d 'Rename a buildpack'
complete -c cf -d 'Delete a buildpack'
complete -c cf -d 'Create a new user'
complete -c cf -d 'Delete a user'
complete -c cf -d 'Show org users by role'
complete -c cf -d 'Assign an org role to a user'
complete -c cf -d 'Remove an org role from a user'
complete -c cf -d 'Show space users by role'
complete -c cf -d 'Assign a space role to a user'
complete -c cf -d 'Remove a space role from a user'
complete -c cf -d 'List available usage quotas'
complete -c cf -d 'Show quota info'
complete -c cf -d 'Assign a quota to an org'
complete -c cf -d 'Define a new resource quota'
complete -c cf -d 'Delete a quota'
complete -c cf -d 'Update an existing resource quota'
complete -c cf -d 'Share a private domain with an org'
complete -c cf -d 'Unshare a private domain with an org'
complete -c cf -d 'List available space resource quotas'
complete -c cf -d 'Show space quota info'
complete -c cf -d 'Define a new space resource quota'
complete -c cf -d 'Update an existing space quota'
complete -c cf -d 'Delete a space quota definition and unassign the space quota from all spaces'
complete -c cf -d 'Assign a space quota definition to a space'
complete -c cf -d 'Unassign a quota from a space'
complete -c cf -d 'List service auth tokens'
complete -c cf -d 'Create a service auth token'
complete -c cf -d 'Update a service auth token'
complete -c cf -d 'Delete a service auth token'
complete -c cf -d 'List service brokers'
complete -c cf -d 'Create a service broker'
complete -c cf -d 'Update a service broker'
complete -c cf -d 'Delete a service broker'
complete -c cf -d 'Rename a service broker'
complete -c cf -d 'Migrate service instances from one service plan to another'
complete -c cf -d 'Recursively remove service from CF database without requests to service broker'
complete -c cf -d 'Recursively remove service instance from CF database without requests to service broker'
complete -c cf -d 'List service access settings'
complete -c cf -d 'Enable access to a service or service plan'
complete -c cf -d 'Disable access to a service or service plan'
complete -c cf -d 'Show a single security group'
complete -c cf -d 'List all security groups'
complete -c cf -d 'Create a security group'
complete -c cf -d 'Update a security group'
complete -c cf -d 'Deletes a security group'
complete -c cf -d 'Bind a security group to a particular space, or all existing spaces of an org'
complete -c cf -d 'Unbind a security group from a space'
complete -c cf -d 'Bind a security group to the list of security groups to be used for staging applications'
complete -c cf -d 'List security groups in the staging set for applications'
complete -c cf -d 'Unbind a security group from the set of security groups for staging applications'
complete -c cf -d 'Bind a security group to the list of security groups to be used for running applications'
complete -c cf -d 'List security groups in the set of security groups for running applications'
complete -c cf -d 'Unbind a security group from the set of security groups for running applications'
complete -c cf -d 'Retrieve the contents of the running environment variable group'
complete -c cf -d 'Retrieve the contents of the staging environment variable group'
complete -c cf -d 'Pass parameters as JSON to create a staging environment variable group'
complete -c cf -d 'Pass parameters as JSON to create a running environment variable group'
complete -c cf -d 'List all isolation segments'
complete -c cf -d 'Create an isolation segment'
complete -c cf -d 'Delete an isolation segment'
complete -c cf -d 'Entitle an organization to an isolation segment'
complete -c cf -d 'Revoke an organization'"'"'s entitlement to an isolation segment'
complete -c cf -d 'Set the default isolation segment used for apps in spaces in an org'
complete -c cf -d 'Reset the default isolation segment used for apps in spaces of an org'
complete -c cf -d 'Assign the isolation segment for a space'
complete -c cf -d 'Reset the space'"'"'s isolation segment to the org default'
complete -c cf -d 'Retrieve list of feature flags with status'
complete -c cf -d 'Retrieve an individual feature flag with status'
complete -c cf -d 'Allow use of a feature'
complete -c cf -d 'Prevent use of a feature'
complete -c cf -d 'Executes a request to the targeted API endpoint'
complete -c cf -d 'Write default values to the config'
complete -c cf -d 'Retrieve and display the OAuth token for the current session'
complete -c cf -d 'Get a one time password for ssh clients'
complete -c cf -d 'Add a new plugin repository'
complete -c cf -d 'Remove a plugin repository'
complete -c cf -d 'List all the added plugin repositories'
complete -c cf -d 'List all available plugins in specified repository or in all added repositories'
complete -c cf -d 'List commands of installed plugins'
complete -c cf -d 'Install CLI plugin'
complete -c cf -d 'Uninstall CLI plugin'
