complete -c checkinstall -l 'type' -d 'Choose packaging system'
complete -c checkinstall -d 'Build a Slackware package'
complete -c checkinstall -d 'Build an RPM package'
complete -c checkinstall -d 'Build a Debian package'
complete -c checkinstall -l 'install' -d 'Toggle created package installation'
complete -c checkinstall -l 'fstrans' -d 'Enable/disable the filesystem translation code'
complete -c checkinstall -l 'default' -d 'Accept default answers to all questions'
complete -c checkinstall -l 'pkgname' -d 'Set name'
complete -c checkinstall -l 'pkgversion' -d 'Set version'
complete -c checkinstall -l 'arch' -l 'pkgarch' -d 'Set architecture'
complete -c checkinstall -l 'pkgrelease' -d 'Set release'
complete -c checkinstall -l 'pkglicense' -d 'Set license'
complete -c checkinstall -l 'pkggroup' -d 'Set software group'
complete -c checkinstall -l 'pkgsource' -d 'Set source location'
complete -c checkinstall -l 'pkgalitsource' -d 'Set alternate source location'
complete -c checkinstall -l 'pakdir' -d 'The new package will be saved here'
complete -c checkinstall -l 'maintainer' -d 'The package maintainer (.deb)'
complete -c checkinstall -l 'provides' -d 'Features provided by this package'
complete -c checkinstall -l 'requires' -d 'Features required by this package'
complete -c checkinstall -l 'recommends' -d 'Features recommended by this package'
complete -c checkinstall -l 'sggests' -d 'Featues suggested by this package'
complete -c checkinstall -l 'conflicts' -d 'Packages that this package cannot be installed with (.deb)'
complete -c checkinstall -l 'replaces' -d 'Packages that this package replaces (.deb)'
complete -c checkinstall -l 'rpmflags' -d 'Pass these flags to the rpm installer'
complete -c checkinstall -l 'rpmi' -d 'Use the -i flag for rpm when installing a .rpm'
complete -c checkinstall -l 'rpmu' -d 'Use the -U flag for rpm when installing a .rpm'
complete -c checkinstall -l 'dpkgflags' -d 'Pass these flags to the dpkg installer'
complete -c checkinstall -l 'spec' -d '.spec file location'
complete -c checkinstall -l 'nodoc' -d 'Do not include documentation files'
complete -c checkinstall -d 'Set debug level'
complete -c checkinstall -d 'Run an interactive install command'
complete -c checkinstall -l 'showinstall' -d 'Toggle interactive install command'
complete -c checkinstall -d 'Run an interactive Slackware installation script'
complete -c checkinstall -l 'showslack' -d 'Toggle interactive Slackware installation script'
complete -c checkinstall -l 'autodoinst' -d 'Toggle the creation of a doinst.sh script'
complete -c checkinstall -l 'strip' -d 'Strip any ELF binaries found inside the package'
complete -c checkinstall -l 'stripso' -d 'Strop any ELF binary libraries (.so files)'
complete -c checkinstall -l 'addso' -d 'Search for ant shared libs and add them to /etc/ld.so.conf'
complete -c checkinstall -l 'reset-uids' -d 'Reset perms for all files'
complete -c checkinstall -l 'gzman' -d 'Compress any man pages found inside the package'
complete -c checkinstall -l 'docdir' -d 'Where to put documentation files'
complete -c checkinstall -l 'umask' -d 'Set the umask value'
complete -c checkinstall -l 'exclude' -d 'Excluse these files/directories from the package'
complete -c checkinstall -l 'include' -d 'Include file/directories in this file in the package'
complete -c checkinstall -l 'inspect' -d 'Inspect the package'"'"'s file list'
complete -c checkinstall -l 'review-spec' -d 'Review the dpec file before creating a .rpm'
complete -c checkinstall -l 'review-control' -d 'Review the control file before creating a .deb'
complete -c checkinstall -l 'newslack' -d 'Use the new (8.1+) Slackware description format'
complete -c checkinstall -l 'with-tar' -d 'Manually set the path to the tar binary'
complete -c checkinstall -l 'deldoc' -d 'Delete doc-pak upon termination'
complete -c checkinstall -l 'deldesc' -d 'Delete description-pak upon termination'
complete -c checkinstall -l 'delspec' -d 'Delete spec file upon termination'
complete -c checkinstall -l 'bk' -d 'Backup any overwritten files'
complete -c checkinstall -l 'backup' -d 'Toggle backup'
complete -c checkinstall -l 'help' -d 'Show help'
complete -c checkinstall -l 'copyright' -d 'Show Copyright information'
complete -c checkinstall -l 'version' -d 'Show version information'
