complete -c chronyc -s '4' -d 'Use only IPv4 address for hostname resolution'
complete -c chronyc -s '6' -d 'Use only IPv6 address for hostname resolution'
complete -c chronyc -s 'n' -d 'Disable resolving of IP address to hostname'
complete -c chronyc -s 'c' -d 'Print the report in CSV format'
complete -c chronyc -s 'd' -d 'Enable print of debugging message'
complete -c chronyc -s 'm' -d 'Allow multiple commands to be specified'
complete -c chronyc -s 'h' -d 'Specify the host to connect'
complete -c chronyc -s 'p' -d 'Specify the UDP port number used by the target to monitor connections'
complete -c chronyc -s 'f' -d 'Option for compatibility'
complete -c chronyc -s 'a' -d 'Option for compatibility'
complete -c chronyc -s 'v' -d 'Show version number'
complete -c chronyc -d 'Show system time info'
complete -c chronyc -d 'Correct the clock by stepping'
complete -c chronyc -d 'Modify max valid skew to update frequency'
complete -c chronyc -d 'Wait until synced in specified limits'
complete -c chronyc -d 'Show info about current sources'
complete -c chronyc -s 'v' -d 'Be verbose'
complete -c chronyc -d 'Show statistics about collected measurements'
complete -c chronyc -s 'v' -d 'Be verbose'
complete -c chronyc -d 'Force reselecting sync source'
complete -c chronyc -d 'Modify reselection distance'
complete -c chronyc -d 'Check how many NTP sources are online/offline'
complete -c chronyc -d 'Show info about last valid measurement'
complete -c chronyc -d 'Add new NTP peer'
complete -c chronyc -d 'Add new NTP server'
complete -c chronyc -d 'Remove server/peer'
complete -c chronyc -d 'Start rapid set of measurements'
complete -c chronyc -d 'Modify max valid sample delay'
complete -c chronyc -d 'Modify max valid delay/deviation ratio'
complete -c chronyc -d 'Modify max valid delay/min ratio'
complete -c chronyc -d 'Modify max polling interval'
complete -c chronyc -d 'Modify min polling interval'
complete -c chronyc -d 'Modify min stratum'
complete -c chronyc -d 'Set sources in subnet to offline status'
complete -c chronyc -d 'Set sources in subnet to online status'
complete -c chronyc -d 'Set all sources to online/offline status according to network config'
complete -c chronyc -d 'Modify poll target'
complete -c chronyc -d 'Refresh IP address'
complete -c chronyc -d 'Enable settime command'
complete -c chronyc -d 'Disable settime command'
complete -c chronyc -d 'Delete previous settime entry'
complete -c chronyc -d 'Show previous settime entries'
complete -c chronyc -d 'Reset settime command'
complete -c chronyc -d 'Set daemon time'
complete -c chronyc -d 'Check whether address is allowed'
complete -c chronyc -d 'Report on clients that have accessed the server'
complete -c chronyc -d 'Show statistics of the server'
complete -c chronyc -d 'Allow access to subnet as a default'
complete -c chronyc -d 'Allow access to subnet and all children'
complete -c chronyc -d 'Deny access to subnet as a default'
complete -c chronyc -d 'Deny access to subnet and all children'
complete -c chronyc -d 'Serve time even when not synced'
complete -c chronyc -d 'Don'"'"'t serve time when not synced'
complete -c chronyc -d 'Show current time smoothing state'
complete -c chronyc -d 'Activate time smoothing'
complete -c chronyc -d 'Reset time smoothing'
complete -c chronyc -d 'Check whether address is allowed'
complete -c chronyc -d 'Allow access to subnet as a default'
complete -c chronyc -d 'Allow access to subnet and all children'
complete -c chronyc -d 'Deny access to subnet as a default'
complete -c chronyc -d 'Deny access to subnet and all children'
complete -c chronyc -d 'Print current RTC performance parameters'
complete -c chronyc -d 'Correct RTC relative to system clock'
complete -c chronyc -d 'Save RTC performance parameters to file'
complete -c chronyc -d 'Close and reopen log files'
complete -c chronyc -d 'Dump all measurements to save files'
complete -c chronyc -d 'Reread keys from key file'
complete -c chronyc -d 'Stop daemon'
complete -c chronyc -d 'Configure how hostname and IP address are resolved'
complete -c chronyc -d 'Set initial response timeout'
complete -c chronyc -d 'Set max number of retries'
complete -c chronyc -d 'Generate key for key file'
complete -c chronyc -d 'Leave the program'
complete -c chronyc -d 'Show help message'
