complete -c cjxl -s 'V' -l 'version' -d 'Print version number'
complete -c cjxl -l 'quiet' -d 'Be more silent'
complete -c cjxl -l 'container' -d 'Encode using container format'
complete -c cjxl -l 'print_profile' -d 'Print timing information'
complete -c cjxl -l 'target_size' -d 'Target file size (based on bytes)'
complete -c cjxl -l 'target_bpp' -d 'Target file size (based on BPP)'
complete -c cjxl -s 'p' -l 'progressive' -d 'Enable progressive decoding'
complete -c cjxl -l 'middleout' -d 'Put center groups first in the file'
complete -c cjxl -l 'progressive_ac' -d 'Use the progressive mode for AC'
complete -c cjxl -l 'qprogressive_ac' -d 'Use the progressive mode for AC'
complete -c cjxl -l 'progressive_dc' -d 'Use progressive mode for DC'
complete -c cjxl -s 'm' -l 'modular' -d 'Use the modular mode'
complete -c cjxl -l 'use_new_heuristics' -d 'Use new encoder heuristics'
complete -c cjxl -s 'j' -l 'jpeg_transcode' -d 'Do lossy transcode of input JPEG file'
complete -c cjxl -l 'num_threads' -d 'Number of worker threads'
complete -c cjxl -l 'num_reps' -d 'How many times to compress'
complete -c cjxl -l 'resampling' -d 'Subsample all color channels'
complete -c cjxl -l 'epf' -d 'Edge preserving filter level'
complete -c cjxl -l 'gaborish' -d 'Force disable gaborish'
complete -c cjxl -l 'intensity_target' -d 'Intensity target of monitor in nits'
complete -c cjxl -l 'saliency_num_progressive_steps'
complete -c cjxl -l 'saliency_map_filename'
complete -c cjxl -l 'saliency_threshold'
complete -c cjxl -s 'x' -l 'dec-hints'
complete -c cjxl -s 'Q' -l 'mquality' -d 'Lossy quality'
complete -c cjxl -s 'I' -l 'iterations' -d 'Fraction of pixels used to learn MA trees'
complete -c cjxl -s 'g' -l 'group-size' -d 'Set group size'
complete -c cjxl -s 'E' -l 'extra-properties' -d 'Number of extra MA tree properties'
complete -c cjxl -s 'N' -l 'near-lossless' -d 'Apply near-lossless preprocessing'
complete -c cjxl -l 'palette' -d 'Use a palette'
complete -c cjxl -l 'lossy-palette' -d 'Quantize to a lossy palette'
complete -c cjxl -s 'X' -l 'pre-compact' -d 'Compact channels (globally)'
complete -c cjxl -s 'Y' -l 'post-compact' -d 'Compact channels (per-group)'
complete -c cjxl -s 'v' -l 'verbose' -d 'Verbose output'
complete -c cjxl -s 'h' -l 'help' -d 'Print help message'
