complete -c clasp -s 'h' -l 'help' -d 'Show [h]elp'
complete -c clasp -s 'v' -l 'version' -d 'Show [v]ersion'
complete -c clasp -s 'A' -l 'auth' -d 'Path to a '"'"'.clasprc.json'"'"' or to a directory with it'
complete -c clasp -s 'I' -l 'ignore' -d 'Path to a '"'"'.claspignore.json'"'"' or to a directory with it'
complete -c clasp -s 'P' -l 'project' -d 'Path to a '"'"'.clasp.json'"'"' or to a directory with it'
complete -c clasp -s 'W' -l 'why' -d 'Display some debugging info upon exit'
complete -c clasp -d 'Log in to script.google.com'
complete -c clasp -d 'Log out'
complete -c clasp -d 'Create a script'
complete -c clasp -d 'Clone a project'
complete -c clasp -d 'Fetch a remote project'
complete -c clasp -d 'Update the remote project'
complete -c clasp -d 'Lists files that will be pushed by '"'"'push'"'"' subcommand'
complete -c clasp -d 'Open a script'
complete -c clasp -d 'List deployment IDs of a script'
complete -c clasp -d 'Deploy a project'
complete -c clasp -d 'Undeploy a project'
complete -c clasp -d 'Create an immutable version of a script'
complete -c clasp -d 'List versions of a script'
complete -c clasp -d 'List projects'
complete -c clasp -d 'Show StackDriver logs'
complete -c clasp -d 'Run a function in your Apps Scripts project'
complete -c clasp -d 'List, enable, or disable APIs'
complete -c clasp -d 'Show help for a command'
complete -c clasp -l 'no-localhost' -d 'Do not run a local server, manually enter code instead'
complete -c clasp -l 'creds' -d 'Specify a relative path to credentials'
complete -c clasp -l 'status' -d 'Show who is logged in'
complete -c clasp -l 'type' -d 'A project type'
complete -c clasp -l 'title' -d 'A project title'
complete -c clasp -l 'parentId' -d 'A project container ID'
complete -c clasp -l 'rootDir' -d 'Path to a directory with project files'
complete -c clasp -l 'rootDir' -d 'Path to a directory project files'
complete -c clasp -l 'versionNumber' -d 'A project version to pull'
complete -c clasp -s 'f' -l 'force' -d 'Forcibly overwrite a remote manifest'
complete -c clasp -s 'w' -l 'watch' -d 'Watch for local changes in non-ignored files and push when they occur'
complete -c clasp -l 'json' -d 'Show in JSON format'
complete -c clasp -l 'webapp' -d 'Open a web application in a browser'
complete -c clasp -l 'creds' -d 'Open the URL to create credentials'
complete -c clasp -l 'addon' -d 'List parent IDs and open the URL of the first one'
complete -c clasp -l 'deploymentId' -d 'Use a custom deployment ID with a web application'
complete -c clasp -s 'V' -l 'versionNumber' -d 'A project version'
complete -c clasp -s 'd' -l 'description' -d 'A deployment description'
complete -c clasp -s 'i' -l 'deploymentId' -d 'A deployment ID to redeploy'
complete -c clasp -l 'all' -d 'Undeploy all deployments'
complete -c clasp -l 'noShorten' -d 'Do not shorten long names'
complete -c clasp -l 'json' -d 'Show logs in JSON form'
complete -c clasp -l 'open' -d 'Open the StackDriver logs in a browser'
complete -c clasp -l 'setup' -d 'Setup StackDriver logs'
complete -c clasp -l 'watch' -d 'Watch and list new logs'
complete -c clasp -l 'simplified' -d 'Hide timestamps with logs'
complete -c clasp -l 'nondev' -d 'Run a function in non-development mode'
complete -c clasp -s 'p' -l 'params' -d 'Specify parameters for a function as a JSON array'
complete -c clasp -d 'List APIs'
complete -c clasp -d 'Enable APIs'
complete -c clasp -d 'Disable APIs'
complete -c clasp -l 'open' -d 'Open API Console in a browser'
