complete -c climate -d 'Show help'
complete -c climate -d 'Update your climate install'
complete -c climate -d 'uninstall climate'
complete -c climate -d 'Show climate version'
complete -c climate -d 'Get the weather'
complete -c climate -d 'Display remaining battery'
complete -c climate -d 'Display remaining battery'
complete -c climate -d 'Lock computer'
complete -c climate -d 'Shutdown the computer'
complete -c climate -d 'Restart the computer'
complete -c climate -d 'Show the time'
complete -c climate -d 'Put a console clock in the top right corner'
complete -c climate -d 'A countdown timer'
complete -c climate -d 'A stopwatch'
complete -c climate -d 'Pipe output to ix.io'
complete -c climate -d 'Find the biggest files recursively'
complete -c climate -d 'Find the biggest directories'
complete -c climate -d 'Find directory size'
complete -c climate -d 'Remove empty directories'
complete -c climate -d 'Extract any given archive'
complete -c climate -d 'Report duplicate files in a directory'
complete -c climate -d 'Count the number of occurences'
complete -c climate -d 'Monitor file for changes'
complete -c climate -d 'Search for the given pattern recursively'
complete -c climate -d 'Replace all occurences'
complete -c climate -d 'Create a ramfs of size (in MB) at path'
complete -c climate -d 'Test your network speed'
complete -c climate -d 'Retrieve your local ip address'
complete -c climate -d 'Retrieve your public ip address'
complete -c climate -d 'List open ports'
complete -c climate -d 'Edit the hosts file'
complete -c climate -d 'http-server serving the current directory'
complete -c climate -d 'Determine if server is up'
complete -c climate -d 'Download file from server'
complete -c climate -d 'Download dir from server'
complete -c climate -d 'Upload to server'
complete -c climate -d 'Mount a remote path'
complete -c climate -d 'Unmount a ssh mount'
complete -c climate -d 'Undo the latest commit'
complete -c climate -d 'Reset local repo to match remote'
complete -c climate -d 'Seset local repo to match remote'
complete -c climate -d 'List all branches'
complete -c climate -d 'Calculate the repo size'
complete -c climate -d 'Calculate total contribution for a user'
complete -c climate -d 'Display a performance overview'
complete -c climate -d 'Find memory used'
complete -c climate -d 'Find disk used'
complete -c climate -d 'Get all PIDs for a process name'
complete -c climate -d 'Find the trash size'
complete -c climate -d 'Empty the trash'
