complete -c clj -s 'X' -d 'Use concatenated aliases to modify classpath or supply exec fn/args'
complete -c clj -s 'A' -d 'Use concatenated aliases to modify classpath'
complete -c clj -s 'M' -d 'Use concatenated aliases to modify classpath or supply main opts'
complete -c clj -s 'T' -d 'Invoke tool by name or via aliases ala -X'
complete -c clj -d 'Deps data to use as the last deps file to be merged'
complete -c clj -d 'Compute classpath and echo to stdout only'
complete -c clj -d 'Generate (or update) pom.xml with deps and paths'
complete -c clj -d 'Print dependency tree'
complete -c clj -d 'Do NOT compute or cache classpath, use this one instead'
complete -c clj -d 'Ignore the ~/.clojure/deps.edn config file'
complete -c clj -d 'Force recomputation of the classpath (don'"'"'t use the cache)'
complete -c clj -d 'Print important path info to console'
complete -c clj -d 'Print environment and command parsing info as data'
complete -c clj -d 'Set specific number of download threads'
complete -c clj -d 'Write a trace.edn file that traces deps expansion'
complete -c clj -s 'h' -l 'help' -d 'Show help'
complete -c clj -s 'P' -d 'Prepare deps - download libs, cache classpath, but don'"'"'t exec'
complete -c clj -s 'J' -d 'Pass opt through in java_opts, ex: -J-Xmx512m'
complete -c clj -s 'i' -l 'init' -d 'Load a file or resource'
complete -c clj -s 'e' -l 'eval' -d 'Eval exprs in string; print non-nil values'
complete -c clj -l 'report' -d 'Report uncaught exception to "file" (default), "stderr", or "none"'
complete -c clj -l 'version' -d 'Print the version to stdout and exit'
complete -c clj -s 'm' -l 'main' -d 'Call the -main function from namespace w/args'
complete -c clj -s 'r' -l 'repl' -d 'Run a repl'
complete -c clj -d 'Run a script from a file or resource'
