complete -c code -s 'd' -l 'diff' -d 'Compare two files with each other'
complete -c code -s 'm' -l 'merge' -d 'Perform a three-way merge'
complete -c code -s 'a' -l 'add' -d 'Add folder(s) to the last active window'
complete -c code -s 'g' -l 'goto' -d 'line and character position'
complete -c code -s 'n' -l 'new-window' -d 'Force to open a new window'
complete -c code -s 'r' -l 'reuse-window' -d 'Force to open a file or folder in an already opened window'
complete -c code -s 'w' -l 'wait' -d 'Wait for the files to be closed before returning'
complete -c code -l 'locale' -d 'The locale to use (e.g. en-US or zh-TW)'
complete -c code -l 'user-data-dir' -d 'Specifies the directory that user data is kept in'
complete -c code -l 'profile' -d 'Opens the provided folder or workspace with the given profile'
complete -c code -s 'v' -l 'version' -d 'Print version'
complete -c code -s 'h' -l 'help' -d 'Print usage'
complete -c code -l 'extensions-dir' -d 'Set the root path for extensions'
complete -c code -l 'list-extensions' -d 'List the installed extensions'
complete -c code -l 'show-versions' -d 'Show versions of installed extensions'
complete -c code -l 'category' -d 'Filters installed extensions by provided category'
complete -c code -l 'install-extension' -d 'Installs or updates the extension'
complete -c code -l 'force' -d 'Updates to the latest version'
complete -c code -l 'pre-release' -d 'Installs the pre-release version'
complete -c code -l 'update-extensions' -d 'Update the installed extensions'
complete -c code -l 'enable-proposed-api' -d 'Enables proposed API features for extensions'
complete -c code -l 'uninstall-extension' -d 'Uninstall extension'
complete -c code -l 'disable-extension' -d 'Disable extension(s)'
complete -c code -l 'disable-extensions' -d 'Disable all installed extensions'
complete -c code -l 'verbose' -d 'Print verbose output (implies --wait)'
complete -c code -l 'log' -d 'Log level to use (default: info)'
complete -c code -s 's' -l 'status' -d 'Print process usage and diagnostics information'
complete -c code -l 'prof-startup' -d 'Run CPU profiler during startup'
complete -c code -l 'sync' -d 'Turn sync on or off'
complete -c code -l 'inspect-extensions' -d 'Allow debugging and profiling of extensions'
complete -c code -l 'inspect-brk-extensions' -d 'Allow debugging and profiling of extensions'
complete -c code -l 'disable-lcd-text' -d 'Disable LCD font rendering'
complete -c code -l 'disable-gpu' -d 'Disable GPU hardware acceleration'
complete -c code -l 'disable-chromium-sandbox' -d 'Disable the Chromium sandbox environment'
complete -c code -l 'telemetry' -d 'Shows all telemetry events which VS code collects'
