complete -c combine -d 'Combine sets of lines from two files using boolean operations'
complete -c combine -d 'Output lines that are in both files'
complete -c combine -d 'Output lines that are inf file1 but not in file2'
complete -c combine -d 'Output lines that are in file1 or in file2'
complete -c combine -d 'Output lines that are in either file1 or file2, but not in both files'
complete -c combine -d 'Read file from stdin'
