complete -c composite -d 'Affine transform matrix [matrix]'
complete -c composite -d 'Control alpha/matte channel of an image [option]'
complete -c composite -d 'Decipher image with this password [password]'
complete -c composite -d 'Chromaticity blue primary point [point]'
complete -c composite -d 'Apply option to select image channels [type]'
complete -c composite -d 'Alternate image colorspace [type]'
complete -c composite -d 'Annotate image with comment [string]'
complete -c composite -d 'Composite operator [operator]'
complete -c composite -d 'Type of pixel compression when writing the image [type]'
complete -c composite -d 'Define one or more image format options [format:option]'
complete -c composite -d 'Image depth [value]'
complete -c composite -d 'Horizontal and vertical density of the image [geometry]'
complete -c composite -d 'Get image or font from this X server [server]'
complete -c composite -d 'Layer disposal method [method]'
complete -c composite -d 'Apply error diffusion to image [method]'
complete -c composite -d 'Encoding type [type text]'
complete -c composite -d 'Endianness (MSB or LSB) of the image [type]'
complete -c composite -d 'Use this filter when resizing an image [type]'
complete -c composite -d 'Render text with this font [name]'
complete -c composite -d 'Output formatted image characteristics ["string"]'
complete -c composite -d 'Which direction to gravitate towards [type]'
complete -c composite -d 'Chromaticity green primary point [point]'
complete -c composite -d 'Type of image interlacing scheme [type]'
complete -c composite -d 'Pixel color interpolation method [method]'
complete -c composite -d 'Assign a label to an image [string]'
complete -c composite -d 'Pixel cache resource limit [type value]'
complete -c composite -d 'Monitor progress'
complete -c composite -d 'Size and location of an image canvas (setting) [geometry]'
complete -c composite -d 'Font point size [value]'
complete -c composite -d 'JPEG/MIFF/PNG compression level [value]'
complete -c composite -d 'Suppress all warning messages'
complete -c composite -d 'Chromaticity red primary point [point]'
complete -c composite -d 'Pay attention to warning messages'
complete -c composite -d 'Settings remain in effect until parenthesis boundary'
complete -c composite -d 'Horizontal and vertical sampling factor [geometry]'
complete -c composite -d 'Image scene number [value]'
complete -c composite -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c composite -d 'Width and height of image [geometry]'
complete -c composite -d 'Synchronize image to storage device'
complete -c composite -d 'Declare the image as modified'
complete -c composite -d 'Transparent color [color]'
complete -c composite -d 'Color tree depth [value]'
complete -c composite -d 'Repeat composite operation across and down image'
complete -c composite -d 'The units of image resolution [type]'
complete -c composite -d 'Print detailed information about the image'
complete -c composite -d 'Virtual pixel access method [method]'
complete -c composite -d 'Chromaticity white point [point]'
complete -c composite -d 'Blend images [geometry]'
complete -c composite -d 'Surround image with a border of color [geometry]'
complete -c composite -d 'Border color [color]'
complete -c composite -d 'Preferred number of colors in the image [value]'
complete -c composite -d 'Convert cipher pixels to plain pixels [filename]'
complete -c composite -d 'Shift image pixels defined by a displacement map [geometry]'
complete -c composite -d 'Dissolve the two images a given percent [value]'
complete -c composite -d 'Shift lookup based on a absolute distortion map [geometry]'
complete -c composite -d 'Convert plain pixels to cipher pixels [filename]'
complete -c composite -d 'Extract area from image [geometry]'
complete -c composite -d 'Location of the composite image [geometry]'
complete -c composite -d 'Identify the format and characteristics of the image'
complete -c composite -d 'Transform image to black and white'
complete -c composite -d 'Replace every pixel with its complementary color '
complete -c composite -d 'Add ICM or IPTC information profile to image [filename]'
complete -c composite -d 'Reduce colors in this colorspace [colorspace]'
complete -c composite -d 'Size and location of an image canvas (operator) [geometry]'
complete -c composite -d 'Apply Paeth rotation to the image [degrees]'
complete -c composite -d 'Resize the image [geometry]'
complete -c composite -d 'Sharpen the image [geometry]'
complete -c composite -d 'Shave pixels from the image edges [geometry]'
complete -c composite -d 'Offset hide watermark within an image'
complete -c composite -d 'Combine two image to create a stereo anaglyph [geometry]'
complete -c composite -d 'Strip image of all profiles and comments'
complete -c composite -d 'Create a thumbnail of the image [geometry]'
complete -c composite -d 'Affine transform image'
complete -c composite -d 'Image type [type]'
complete -c composite -d 'Sharpen the image [geometry]'
complete -c composite -d 'Percent brightness and saturation of a watermark [geometry]'
complete -c composite -d 'Write images to this file [filename]'
complete -c composite -d 'Swap two images in the image sequence [indexes]'
complete -c composite -d 'Display copious debugging information [events]'
complete -c composite -d 'Print program options'
complete -c composite -d 'Print a list of supported option arguments [type]'
complete -c composite -d 'Format of debugging information [format]'
complete -c composite -d 'Print version information'
complete -c composite -d 'Store matte channel if the image has one'
complete -c composite -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
