complete -c compare -d 'Control alpha/matte channel of an image [option]'
complete -c compare -d 'Decipher image with this password [password]'
complete -c compare -d 'Apply option to select image channels [type]'
complete -c compare -d 'Alternate image colorspace [type]'
complete -c compare -d 'Set image composite operator [operator]'
complete -c compare -d 'Type of pixel compression when writing the image [type]'
complete -c compare -d 'Convert cipher pixels to plain pixels [filename]'
complete -c compare -d 'Define one or more image format options [format:option]'
complete -c compare -d 'Horizontal and vertical density of the image [geometry]'
complete -c compare -d 'Image depth [value]'
complete -c compare -d 'Maximum distortion for (sub)image match [value]'
complete -c compare -d 'Convert plain pixels to cipher pixels [filename]'
complete -c compare -d 'Extract area from image [geometry]'
complete -c compare -d 'Output formatted image characteristics ["string"]'
complete -c compare -d 'Colors within this distance are considered equal [distance]'
complete -c compare -d 'Emphasize pixel differences with this color [color]'
complete -c compare -d 'Identify the format and characteristics of the image'
complete -c compare -d 'Type of image interlacing scheme [type]'
complete -c compare -d 'Pixel cache resource limit [type value]'
complete -c compare -d 'De-emphasize pixel differences with this color [color]'
complete -c compare -d 'Measure differences between images with this metric [type]'
complete -c compare -d 'Monitor progress'
complete -c compare -d 'Get the passphrase from this file [filename]'
complete -c compare -d 'Add, delete, or apply an image profile [filename]'
complete -c compare -d 'JPEG/MIFF/PNG compression level [value]'
complete -c compare -d 'Suppress all warning messages'
complete -c compare -d 'Reduce colors in this colorspace [colorspace]'
complete -c compare -d 'Pay attention to warning messages'
complete -c compare -d 'Settings remain in effect until parenthesis boundary'
complete -c compare -d 'Horizontal and vertical sampling factor [geometry]'
complete -c compare -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c compare -d 'Attribute set an image attribute [value]'
complete -c compare -d 'Width and height of image [geometry]'
complete -c compare -d 'Search for subimage'
complete -c compare -d 'Transparent color [color]'
complete -c compare -d 'Image type [type]'
complete -c compare -d 'Print detailed information about the image'
complete -c compare -d 'Print version information'
complete -c compare -d 'Virtual pixel access method [method]'
complete -c compare -d 'Display copious debugging information [events]'
complete -c compare -d 'Print program options'
complete -c compare -d 'Print a list of supported option arguments [type]'
complete -c compare -d 'Format of debugging information [format]'
complete -c compare -d 'Synchronize image to storage device'
complete -c compare -d 'Declare the image as modified'
