complete -c connmanctl -d 'Shows if the system is online or offline'
complete -c connmanctl -d 'Display technologies'
complete -c connmanctl -d 'Get System Clock Properties'
complete -c connmanctl -d 'Enables given technology or offline mode'
complete -c connmanctl -d 'Disables given technology or offline mode'
complete -c connmanctl -d 'Enable, disable tethering, set SSID and passphrase for wifi'
complete -c connmanctl -d 'Display services'
complete -c connmanctl -d 'Display peers'
complete -c connmanctl -d 'Scans for new services for given technology'
complete -c connmanctl -d 'Connect a given service or peer'
complete -c connmanctl -d 'Disconnect a given service or peer'
complete -c connmanctl -d 'Set service configuration options'
complete -c connmanctl -d 'Monitor signals from interfaces'
complete -c connmanctl -d 'Display VPN connections'
complete -c connmanctl -d 'Enable or disable a session'
complete -c connmanctl -d '(Un)Register a Peer Service'
complete -c connmanctl -d 'Show help'
