complete -c cp -s 'H' -d '-R: Follow symlink arguments'
complete -c cp -s 'L' -d '-R: Follow all symlinks'
complete -c cp -s 'P' -d '-R: Don'"'"'t follow symlinks (default)'
complete -c cp -s 'f' -d 'Don'"'"'t confirm to overwrite'
complete -c cp -s 'i' -d 'Prompt before overwrite'
complete -c cp -s 'p' -d 'Preserve attributes of source'
complete -c cp -s 'v' -d 'Print filenames as they'"'"'re copied'
complete -c cp -s 'a' -d 'Archive mode (-pPR)'
complete -c cp -s 'l' -d 'Hard link instead of copying'
complete -c cp -s 'x' -d 'Don'"'"'t traverse mount points'
