complete -c cpupower -s 'h' -l 'help' -d 'Show supported commands and general usage'
complete -c cpupower -s 'c' -l 'cpu' -d 'Only show or set values for specific cores'
complete -c cpupower -d 'Show manpage for subcommands'
complete -c cpupower -d 'Retrieve cpufreq kernel information'
complete -c cpupower -d 'Modify cpufreq settings'
complete -c cpupower -d 'Retrieve cpu idle kernel information'
complete -c cpupower -d 'Set cpu idle state specific kernel options'
complete -c cpupower -d 'Set processor power related kernel or hardware config'
complete -c cpupower -d 'Show processor power related kernel or hardware config'
complete -c cpupower -d 'Report processor frequency and idle statistics'
complete -c cpupower -s 'e' -l 'debug' -d 'Prints out debug information'
complete -c cpupower -s 'f' -l 'freq' -d 'Get frequency the CPU currently runs at, according to the cpufreq core'
complete -c cpupower -s 'w' -l 'hwfreq' -d 'Get frequency the CPU currently runs at, by reading it from hardware'
complete -c cpupower -s 'l' -l 'hwlimits' -d 'Determine the minimum and maximum CPU frequency allowed'
complete -c cpupower -s 'd' -l 'driver' -d 'Determines the used cpufreq kernel driver'
complete -c cpupower -s 'p' -l 'policy' -d 'Gets the currently used cpufreq policy'
complete -c cpupower -s 'g' -l 'governors' -d 'Determines available cpufreq governors'
complete -c cpupower -s 's' -l 'stats' -d 'Shows cpufreq statistics if available'
complete -c cpupower -s 'y' -l 'latency' -d 'Determines the maximum latency on CPU frequency changes'
complete -c cpupower -s 'o' -l 'proc' -d 'Prints out information like the old /proc/cpufreq'
complete -c cpupower -s 'm' -l 'human' -d 'human-readable output for the -f, -w, -s and -y parameters'
complete -c cpupower -s 'n' -l 'no-rounding' -d 'Output frequencies and latencies without rounding off values'
complete -c cpupower -l 'related-cpus'
complete -c cpupower -s 'a' -l 'affected-cpus'
complete -c cpupower -s 'd' -l 'min' -d 'new minimum CPU frequency the governor may select'
complete -c cpupower -s 'u' -l 'max' -d 'new maximum CPU frequency the governor may select'
complete -c cpupower -s 'g' -l 'governor' -d 'new cpufreq governor'
complete -c cpupower -s 'f' -l 'freq' -d 'specific frequency to be set. Requires userspace governor to be available and loaded'
complete -c cpupower -s 'r' -l 'related' -d 'modify all hardware-related CPUs at the same time'
complete -c cpupower -s 'f' -l 'silent' -d 'Only print a summary of all available C-states in the system'
complete -c cpupower -s 'd' -l 'disable' -d 'Disable a specific processor sleep state'
complete -c cpupower -s 'e' -l 'enable' -d 'Enable a specific processor sleep state'
complete -c cpupower -s 'D' -l 'disable-by-latency' -d 'Disable all idle states with a equal or higher latency than <LATENCY>'
complete -c cpupower -s 'E' -l 'enable-all' -d 'Enable all idle states if not enabled already'
complete -c cpupower -s 'b' -l 'perf-bias' -d 'Set relative importance of performance vs energy savings'
complete -c cpupower -s 'b' -l 'perf-bias' -d 'Get relative importance of performance vs energy savings'
complete -c cpupower -s 'm' -d 'Only display this monitor'
complete -c cpupower -s 'v' -d 'Increase verbosity if the binary was compiled with the DEBUG option set'
complete -c cpupower -s 'c' -d 'Schedule the processs on every core before starting and ending measuring'
complete -c cpupower -s 'i' -d 'Measure interval'
complete -c cpupower -s 'l' -d 'List available monitors on your system'
