complete -c createdb -s 'D' -l 'tablespace' -d 'Default tablespace for the database'
complete -c createdb -s 'e' -l 'echo' -d 'Show the commands being sent to the server'
complete -c createdb -s 'E' -l 'encoding' -d 'Encoding for the database'
complete -c createdb -s 'l' -l 'locale' -d 'Locale settings for the database'
complete -c createdb -l 'lc-collate' -d 'LC_COLLATE setting for the database'
complete -c createdb -l 'lc-ctype' -d 'LC_CTYPE setting for the database'
complete -c createdb -s 'O' -l 'owner' -d 'Database user to own the new database'
complete -c createdb -s 'T' -l 'template' -d 'Template database to copy'
complete -c createdb -s 'V' -l 'version' -d 'Output version information, then exit'
complete -c createdb -s '?' -l 'help' -d 'Show help, then exit'
complete -c createdb -s 'h' -l 'host' -d 'Database server host or socket directory'
complete -c createdb -s 'p' -l 'port' -d 'Database server port'
complete -c createdb -s 'U' -l 'username' -d 'User name to connect as'
complete -c createdb -s 'w' -l 'no-password' -d 'Never prompt for password'
complete -c createdb -s 'W' -l 'password' -d 'Force password prompt'
complete -c createdb -l 'maintenance-db' -d 'Alternate maintenance database'
