complete -c csc -s 'o' -d 'Enable optimizations'
complete -c csc -d 'Disable optimizations'
complete -c csc -d 'Make output identical across compilations if inputs are identical'
complete -c csc -d 'Specifies an XML file where processed documentation comments are to be written'
complete -c csc -d 'Specifies the output file'
complete -c csc -d 'Specify a mapping for source path names output by the compiler'
complete -c csc -d 'Specifies the file name and location of the .pdb file'
complete -c csc -d 'Specify any platform as the output platform (default)'
complete -c csc -d 'Specify any platform as the output platform'
complete -c csc -d 'Specify ARM as the output platform'
complete -c csc -d 'Specify ARM64 as the output platform'
complete -c csc -d 'Specify AMD64 or EM64T as the output platform'
complete -c csc -d 'Specify x86 as the output platform'
complete -c csc -d 'Specify Itanium as the output platform'
complete -c csc -d 'Specify a language for compiler output'
complete -c csc -d 'Generate a reference assembly in addition to the primary assembly'
complete -c csc -d 'Generate a reference assembly instead of a primary assembly'
complete -c csc -d 'Specify .exe file for Windows 8.x Store apps as the format of the output file'
complete -c csc -d 'Specify .exe file as the format of the output file (default)'
complete -c csc -d 'Specify code library as the format of the output file'
complete -c csc -d 'Specify module as the format of the output file'
complete -c csc -d 'Specify Windows program as the format of the output file'
complete -c csc -d 'Specify intermediate .winmdobj file as the format of the output file'
complete -c csc -d 'Specify the name of the source module'
complete -c csc -d 'Specifies one or more modules to be part of this assembly'
complete -c csc -d 'Instructs the compiler to add the public key but to leave the assembly unsigned'
complete -c csc -d 'Disable -delaysign'
complete -c csc -d 'Specifies the name of the cryptographic key container'
complete -c csc -d 'Specifies the filename containing the cryptographic key'
complete -c csc -d 'Specifies the location of assemblies referenced by means of -reference'
complete -c csc -d 'Instructs the compiler not to import the standard library (mscorlib.dll)'
complete -c csc -d 'Disable -nostdlib'
complete -c csc -d 'Apply a public key without signing the assembly'
complete -c csc -d 'Imports metadata from a file that contains an assembly'
complete -c csc -d 'Run the analyzers from this assembly'
complete -c csc -d 'Names additional files that don'"'"'t directly affect code generation but may be used by analyzers for producing errors or warnings'
complete -c csc -d 'Embed all source files in the PDB'
complete -c csc -d 'Embed specific files in the PDB'
complete -c csc -d 'Creates a file that contains information that makes it easy to report a bug'
complete -c csc -d 'Generate overflow checks'
complete -c csc -d 'Disable overflow checks'
complete -c csc -d 'Instruct the compiler to emit debugging information'
complete -c csc -d 'Disable -debug'
complete -c csc -d 'Specifies the absolute path to the file in compiler output'
complete -c csc -d 'Suppresses the compiler'"'"'s generation of specified warnings'
complete -c csc -d 'Promotes warnings to errors'
complete -c csc -d 'Disable -warnaserror'
complete -c csc -d 'Specify a ruleset file that disables specific diagnostics'
complete -c csc -d 'Defines preprocessor symbols'
complete -c csc -d 'Makes COM type information in specified assemblies available to the project'
complete -c csc -d 'Creates a link to a managed resource'
complete -c csc -d 'Embeds a .NET Framework resource into the output file'
complete -c csc -d 'Specifies an .ico file to insert into the output file'
complete -c csc -d 'Specifies a Win32 resource to insert into the output file'
complete -c csc -s '?' -d 'Lists compiler options to stdout'
complete -c csc -d 'Specifies the preferred base address at which to load a DLL'
complete -c csc -d 'Specifies the code page to use for all source code files in the compilation'
complete -c csc -d 'Specifies that the executable file supports address space layout randomization (ASLR)'
complete -c csc -d 'Disable -highentropyva'
complete -c csc -d 'Display the allowed values for language version'
complete -c csc -d 'Specify latest major version as language version'
complete -c csc -d 'Specify latest version (including minor releases) as language version'
complete -c csc -d 'Specify latest major version as language version'
complete -c csc -d 'Specify latest preview version as language version'
complete -c csc -d 'Specify ISO/IEC 23270:2003 C# (1.0/1.2) as language version'
complete -c csc -d 'Specify ISO/IEC 23270:2006 C# (2.0) as language version'
complete -c csc -d 'Specifies the location of the Main method'
complete -c csc -d 'Instructs the compiler not to compile with csc.rsp'
complete -c csc -d 'Suppresses compiler banner information'
complete -c csc -d 'Searches subdirectories for source files to compile'
complete -c csc -d 'Specifies the minimum version of the subsystem that the executable file can use'
complete -c csc -d 'Enables compilation of code that uses the unsafe keyword'
complete -c csc -d 'Displays compiler output using UTF-8 encoding'
complete -c csc -d 'Specifies whether to use concurrent build'
complete -c csc -d 'Disable -parallel'
complete -c csc -d 'Specify SHA1 as the algorithm for calculating the source file checksum stored in PDB (default)'
complete -c csc -d 'Specify SHA256 as the algorithm for calculating the source file checksum stored in PDB'
