complete -c cvs -s 'H' -d 'Displays usage information for command.'
complete -c cvs -s 'Q' -d 'Cause CVS to be really quiet.'
complete -c cvs -s 'q' -d 'Cause CVS to be somewhat quiet.'
complete -c cvs -s 'r' -d 'Make checked-out files read-only.'
complete -c cvs -s 'w' -d 'Make checked-out files read-write (default).'
complete -c cvs -s 'n' -d 'Do not execute anything that will change the disk.'
complete -c cvs -s 't' -d 'Show trace of program execution -- try with -n.'
complete -c cvs -s 'R' -d 'Assume repository is read-only, such as CDROM'
complete -c cvs -s 'v' -d 'CVS version and copyright.'
complete -c cvs -s 'd' -d 'Overrides $CVSROOT as the root of the CVS tree.'
complete -c cvs -s 'f' -d 'Do not use the ~/.cvsrc file.'
complete -c cvs -s 'x' -d 'Encrypt all net traffic.'
complete -c cvs -s 'a' -d 'Authenticate all net traffic.'
complete -c cvs -s '4' -d 'Use IPv4 addresses only.'
complete -c cvs -s '6' -d 'Use IPv6 addresses only.'
complete -c cvs -s 's' -d 'Set CVS user variable.'
complete -c cvs -d 'Add a new file/directory to the repository'
complete -c cvs -d 'Administration front end for rcs'
complete -c cvs -d 'Show last revision where each line was modified'
complete -c cvs -d 'Checkout sources for editing'
complete -c cvs -d 'Check files into the repository'
complete -c cvs -d 'Show differences between revisions'
complete -c cvs -d 'Get ready to edit a watched file'
complete -c cvs -d 'See who is editing a watched file'
complete -c cvs -d 'Export sources from CVS, similar to checkout'
complete -c cvs -d 'Show repository access history'
complete -c cvs -d 'Import sources into CVS, using vendor branches'
complete -c cvs -d 'Kerberos server mode'
complete -c cvs -d 'Print out history information for files'
complete -c cvs -d 'Prompt for password for authenticating server'
complete -c cvs -d 'Removes entry in .cvspass for remote repository'
complete -c cvs -d 'List files available from CVS'
complete -c cvs -d 'Password server mode'
complete -c cvs -d 'Show last revision where each line of module was modified'
complete -c cvs -d 'Indicate that a Module is no longer in use'
complete -c cvs -d 'Remove an entry from the repository'
complete -c cvs -d 'Print out history information for a module'
complete -c cvs -d 'List files in a module'
complete -c cvs -d 'Add a symbolic tag to a module'
complete -c cvs -d 'Server mode'
complete -c cvs -d 'Display status information on checked out files'
complete -c cvs -d 'Add a symbolic tag to checked out version of files'
complete -c cvs -d 'Undo an edit command'
complete -c cvs -d 'Bring work tree in sync with repository'
complete -c cvs -d 'Show current CVS version(s)'
complete -c cvs -d 'Set watches'
complete -c cvs -d 'See who is watching a file'
