complete -c cwebp -d 'Help (short)'
complete -c cwebp -l 'help' -d 'Help (long)'
complete -c cwebp -d 'Quality (float; 0…100; default: 75)'
complete -c cwebp -d 'Transparency-compression quality (integer 0…100; default: 100)'
complete -c cwebp -d 'Preset setting'
complete -c cwebp -d 'Lossless preset of level'
complete -c cwebp -d 'Compression method'
complete -c cwebp -d 'Number of segments to use'
complete -c cwebp -d 'Target size (in bytes)'
complete -c cwebp -d 'Target PSNR (in dB; typically: 42)'
complete -c cwebp -d 'Input size (width x height) for YUV'
complete -c cwebp -d 'Spatial noise shaping (integer 0…100; default: 50)'
complete -c cwebp -d 'Filter strength (integer 0…100; default: 60)'
complete -c cwebp -d 'Filter sharpness'
complete -c cwebp -d 'Use strong filter'
complete -c cwebp -d 'Use simple filter'
complete -c cwebp -d 'Use sharper (and slower) RGB->YUV conversion'
complete -c cwebp -d 'Limit quality to fit 512k limit on first partition (0:no degradation…100:full degradation)'
complete -c cwebp -d 'Analysis pass number'
complete -c cwebp -d 'Crop picture with <x> <y> <v> <h> rectangle'
complete -c cwebp -d 'Resize picture to <w> <h> after any cropping'
complete -c cwebp -d 'Use multi-threading if available'
complete -c cwebp -d 'Reduce memory usage (slows encoding)'
complete -c cwebp -d 'Print map of extra info'
complete -c cwebp -d 'Print averaged PSNR distortion'
complete -c cwebp -d 'Print averaged SSIM distortion'
complete -c cwebp -d 'Print local-similarity distortion'
complete -c cwebp -d 'Dump compressed output to given PGM file'
complete -c cwebp -d 'Transparency-compression method'
complete -c cwebp -d 'Predictive filtering for alpha plane'
complete -c cwebp -d 'Preserve RGB values in transparent area'
complete -c cwebp -d 'Blend colors against background color (e.g. 0xc0e0d0)'
complete -c cwebp -d 'Discard any transparency information'
complete -c cwebp -d 'Encode image losslessly'
complete -c cwebp -d 'Use near-lossless image preprocessing (integer 0…100:off; default: 100)'
complete -c cwebp -d 'Specify image-characteristics hint'
complete -c cwebp -d 'Comma-separated list of metadata to copy, if present'
complete -c cwebp -d 'Condense printed messages'
complete -c cwebp -d 'Print version number and exit'
complete -c cwebp -d 'Disable all assembly optimizations'
complete -c cwebp -d 'Be verbose (print encoding/decoding times)'
complete -c cwebp -d 'Report encoding progress'
complete -c cwebp -d 'Roughly match expected JPEG size'
complete -c cwebp -d 'Auto-adjust filter strength'
complete -c cwebp -d 'Pre-processing filter (integer)'
complete -c cwebp -d 'Output to file'
