complete -c cygpath -s 'd' -l 'dos' -d 'Print DOS/short form (C:PROGRA~1)'
complete -c cygpath -s 'm' -l 'mixed' -d 'Print Windows form with regular slashes (C:/WINNT)'
complete -c cygpath -s 'M' -l 'mode' -d 'Report on mode of file'
complete -c cygpath -s 'u' -l 'unix' -d 'Print Unix form (/cygdrive/c/winnt)'
complete -c cygpath -s 'w' -l 'windows' -d 'Print Windows form (C:\\WINNT)'
complete -c cygpath -s 't' -l 'type' -d 'Print TYPE form'
complete -c cygpath -s 'a' -l 'absolute' -d 'Output absolute path'
complete -c cygpath -s 'l' -l 'long-name' -d 'Print Windows long form'
complete -c cygpath -s 'p' -l 'path' -d 'NAME is a colon-separated list'
complete -c cygpath -s 'U' -l 'proc-cygdrive' -d 'Emit /proc/cygdrive instead of /cygdrive prefix'
complete -c cygpath -s 's' -l 'short-name' -d 'Print DOS/short form'
complete -c cygpath -s 'C' -l 'codepage' -d 'Print pathname in CODEPAGE'
complete -c cygpath -s 'A' -l 'allusers' -d 'Use "All Users" instead of current user'
complete -c cygpath -s 'D' -l 'desktop' -d 'Output "Desktop" directory'
complete -c cygpath -s 'H' -l 'homeroot' -d 'Output "Profiles" directory'
complete -c cygpath -s 'O' -l 'mydocs' -d 'Output "My Documents" directory'
complete -c cygpath -s 'P' -l 'smprograms' -d 'Output Start Menu "Programs" directory'
complete -c cygpath -s 'S' -l 'sysdir' -d 'Output system directory'
complete -c cygpath -s 'W' -l 'windir' -d 'Output "Windows" directory'
complete -c cygpath -s 'F' -l 'folder' -d 'Output special folder with numeric ID'
complete -c cygpath -s 'f' -l 'file' -d 'Read FILE for input'
complete -c cygpath -s 'o' -l 'option' -d 'Read options from FILE as well'
complete -c cygpath -s 'c' -l 'close' -d 'Close HANDLE'
complete -c cygpath -s 'i' -l 'ignore' -d 'Ignore missing argument'
complete -c cygpath -s 'h' -l 'help' -d 'Output usage information'
complete -c cygpath -s 'V' -l 'version' -d 'Output version information'
