complete -c cygport -s '4' -l '32' -d 'Build for 32-bit Cygwin'
complete -c cygport -s '8' -l '64' -d 'Build for 64-bit Cygwin'
complete -c cygport -l 'debug' -d 'Enable debugging messages'
complete -c cygport -d 'Cygport file'
complete -c cygport -d 'Download all sources'
complete -c cygport -d 'Download missing sources'
complete -c cygport -d 'Prepare source directory'
complete -c cygport -d 'Build software'
complete -c cygport -d 'Run test suite'
complete -c cygport -d 'Install into DESTDIR and run post-installation steps'
complete -c cygport -d 'Run post-installation steps'
complete -c cygport -d 'List package files'
complete -c cygport -d 'List debug package files'
complete -c cygport -d 'Show dependencies'
complete -c cygport -d 'Show packaging info'
complete -c cygport -d 'Show project homepage URL'
complete -c cygport -d 'Create packages, marked as test'
complete -c cygport -d 'Create packages'
complete -c cygport -d 'Create source patches'
complete -c cygport -d 'Upload finished packages'
complete -c cygport -d 'Upload packages without marking !ready'
complete -c cygport -d 'Send announcement email'
complete -c cygport -d 'Delete working directory'
complete -c cygport -d 'Same as prep build inst pkg'
complete -c cygport -d 'Show help'
complete -c cygport -d 'Show version'
