complete -c darcs -d 'Darcs repo'
complete -c darcs -d 'Set the specified option'
complete -c darcs -d 'Display help about darcs and darcs commands'
complete -c darcs -d 'Add new files to version control'
complete -c darcs -d 'Remove files from version control'
complete -c darcs -d 'Move or rename files'
complete -c darcs -d 'Substitute one word for another'
complete -c darcs -d 'Discard unrecorded changes'
complete -c darcs -d 'Undo the last revert'
complete -c darcs -d 'List unrecorded changes in the working tree'
complete -c darcs -d 'Create a patch from unrecorded changes'
complete -c darcs -d 'Remove recorded patches without changing the working tree'
complete -c darcs -d 'Improve a patch before it leaves your repository'
complete -c darcs -d 'Mark unresolved conflicts in working tree, for manual resolution'
complete -c darcs -d 'Name the current repository state for future reference'
complete -c darcs -d 'Set a preference (test, predist, boringfile or binariesfile)'
complete -c darcs -d 'Create a diff between two versions of the repository'
complete -c darcs -d 'List patches in the repository'
complete -c darcs -d 'Annotate lines of a file with the last patch that modified it'
complete -c darcs -d 'Create a distribution archive'
complete -c darcs -d 'Show information about the given repository'
complete -c darcs -d 'Copy and apply patches from another repository to this one'
complete -c darcs -d 'Delete selected patches from the repository'
complete -c darcs -d 'Apply the inverse of recorded changes to the working tree'
complete -c darcs -d 'Copy and apply patches from this repository to another one'
complete -c darcs -d 'Prepare a bundle of patches to be applied to some target repository'
complete -c darcs -d 'Make a copy of an existing repository'
complete -c darcs -d 'Create an empty repository'
complete -c darcs -d 'Optimize the repository'
complete -c darcs -d 'Repair a corrupted repository'
complete -c darcs -d 'Convert repositories between various formats'
complete -c darcs -d 'Outputs a specific version of a file'
complete -c darcs -d 'Generate the graph of dependencies'
complete -c darcs -d 'Show version-controlled files in the working tree'
complete -c darcs -d 'Dump contents of working tree index'
complete -c darcs -d 'Dump contents of pristine cache'
complete -c darcs -d 'Show repository summary information'
complete -c darcs -d 'List authors by patch count'
complete -c darcs -d 'Show all tags in the repository'
complete -c darcs -d 'Check integrity of patch index'
complete -c darcs -d 'Garbage collect pristine, inventories and patches'
complete -c darcs -d 'Optimize repository for getting over network'
complete -c darcs -d 'Reorder the patches in the repository'
complete -c darcs -d 'Enable patch index'
complete -c darcs -d 'Disable patch index'
complete -c darcs -d 'Compress patches and inventories'
complete -c darcs -d 'Uncompress patches and inventories'
complete -c darcs -d 'Relink random internal data to a sibling'
complete -c darcs -d 'Optimize hashed pristine layout'
complete -c darcs -d 'Upgrade repository to latest compatible format'
complete -c darcs -d 'Garbage collect global cache'
complete -c darcs -l 'help' -d 'Show a brief description of the command and its options'
complete -c darcs -l 'list-options' -d 'Show plain list of available options and commands, for auto-completion'
complete -c darcs -l 'run-posthook' -d 'Run posthook command without prompting [DEFAULT]'
complete -c darcs -l 'prompt-posthook' -d 'Prompt before running posthook'
complete -c darcs -l 'posthook' -d 'Specify command to run after this darcs command'
complete -c darcs -l 'run-prehook' -d 'Run prehook command without prompting [DEFAULT]'
complete -c darcs -l 'prompt-prehook' -d 'Prompt before running prehook'
complete -c darcs -l 'prehook' -d 'Specify command to run before this darcs command'
complete -c darcs -l 'disable' -d 'Disable this command'
complete -c darcs -l 'debug' -d 'Give only debug output'
complete -c darcs -l 'debug-http' -d 'Debug output from libcurl'
complete -c darcs -l 'quiet' -s 'q' -d 'Suppress informational output'
complete -c darcs -l 'standard-verbosity' -d 'Neither verbose nor quiet output [DEFAULT]'
complete -c darcs -l 'verbose' -s 'v' -d 'Give verbose output'
complete -c darcs -l 'timings' -d 'Provide debugging timings information'
