complete -c dconf -d 'Read the value of a key'
complete -c dconf -d 'List the sub-keys and sub-directories of a directory'
complete -c dconf -d 'Write a new value to a key'
complete -c dconf -d 'Delete a key or an entire directory'
complete -c dconf -d 'Compile a binary database from keyfiles'
complete -c dconf -d 'Update the system dconf databases'
complete -c dconf -d 'Watch a key or directory for changes'
complete -c dconf -d 'Dump an entire subpath to stdout'
complete -c dconf -d 'Populate a subpath from stdin'
complete -c dconf -d 'Display help and exit'
