complete -c defaults -d 'Restricts preferences operations to the current logged-in host'
complete -c defaults -d 'Restricts preferences operations to hostname'
complete -c defaults -d 'Shows defaults entire given domain'
complete -c defaults -d 'Writes domain or or a key in the domain'
complete -c defaults -d 'String as the value for the given key'
complete -c defaults -d 'Raw data bytes for given key'
complete -c defaults -d 'Integer as the value for the given key'
complete -c defaults -d 'Floating point number as the value for the given key'
complete -c defaults -d 'Boolean as the value for the given key'
complete -c defaults -d 'Date as the value for the given key'
complete -c defaults -d 'Array as the value for the given key'
complete -c defaults -d 'Add new elements to the end of an array'
complete -c defaults -d 'Add a dictionary to domain'
complete -c defaults -d 'Add new key/value pairs to a dictionary'
complete -c defaults -d 'Shows the type for the given domain, key'
complete -c defaults -d 'Renames old_key to new_key'
complete -c defaults -d 'Deletes domain or a key in the domain'
complete -c defaults -d 'Prints the names of all domains in the users defaults system'
complete -c defaults -d 'Searches for word in domain names, keys, and values'
complete -c defaults -d 'Prints a list of possible command formats'
