complete -c dig -s '4' -d 'Use IPv4 query transport only'
complete -c dig -s '6' -d 'Use IPv6 query transport only'
complete -c dig -s 'm' -d 'Enable memory usage debugging'
complete -c dig -s 'b' -d 'Bind to source address/port'
complete -c dig -s 'f' -d 'Specify batch mode file'
complete -c dig -s 'c' -d 'Specify query class'
complete -c dig -s 'k' -d 'Specify TSIG key file'
complete -c dig -s 'y' -d 'specify named base64 TSIG key'
complete -c dig -s 'p' -d 'Specify port number'
complete -c dig -s 'q' -d 'Specify query name'
complete -c dig -s 't' -d 'Specify query type'
complete -c dig -s 'x' -d 'Reverse lookup'
complete -c dig -s 'h' -d 'Print help and exit'
complete -c dig -s 'v' -d 'Print version and exit'
complete -c dig -d 'TCP mode'
complete -c dig -d 'TCP mode, alternate syntax'
complete -c dig -d 'Set whether to use searchlist'
complete -c dig -d 'Search with intermediate results'
complete -c dig -d 'Deprecated, treated as a synonym for +[no]search'
complete -c dig -d 'Recursive mode'
complete -c dig -d 'Dont revert to TCP for TC responses.'
complete -c dig -d 'Dont try next server on SERVFAIL'
complete -c dig -d 'Try to parse even illegal messages'
complete -c dig -d 'Set AA flag in query (+[no]aaflag)'
complete -c dig -d 'Set AD flag in query'
complete -c dig -d 'Set CD flag in query'
complete -c dig -d 'Control display of class in records'
complete -c dig -d 'Control display of command line'
complete -c dig -d 'Control display of comment lines'
complete -c dig -d 'Control display of question'
complete -c dig -d 'Control display of answer'
complete -c dig -d 'Control display of authority'
complete -c dig -d 'Control display of additional'
complete -c dig -d 'Control display of statistics'
complete -c dig -d 'Disable everything except short form of answer'
complete -c dig -d 'Control display of ttls in records'
complete -c dig -d 'Set or clear all display flags'
complete -c dig -d 'Print question before sending'
complete -c dig -d 'Search all authoritative nameservers'
complete -c dig -d 'ID responders in short answers'
complete -c dig -d 'Trace delegation down from root'
complete -c dig -d 'Request DNSSEC records'
complete -c dig -d 'Request Name Server ID'
complete -c dig -d 'Print records in an expanded format'
complete -c dig -d 'AXFR prints only one soa record'
complete -c dig -d 'Set number of UDP attempts'
complete -c dig -d 'Set number of UDP retries'
complete -c dig -d 'Set query timeout'
complete -c dig -d 'Set EDNS0 Max UDP packet size'
complete -c dig -d 'Set NDOTS value'
complete -c dig -d 'Set EDNS version'
