complete -c diskutil -d 'List disks'
complete -c diskutil -d 'Return a property list'
complete -c diskutil -d 'Get detailed information about a specific whole disk or partition'
complete -c diskutil -d 'Return a property list'
complete -c diskutil -d 'Process all disks'
complete -c diskutil -d 'Continuously display system-wide disk manipulation activity'
complete -c diskutil -d 'Show the file system personalities available'
complete -c diskutil -d 'Return a property list'
complete -c diskutil -d 'Unmount a single volume'
complete -c diskutil -d 'Unmount an entire disk (all volumes)'
complete -c diskutil -d 'Eject a volume or disk'
complete -c diskutil -d 'Mount a single volume'
complete -c diskutil -d 'Specify mount point'
complete -c diskutil -d 'Mount an entire disk (all mountable volumes)'
complete -c diskutil -d 'Rename a volume'
complete -c diskutil -d 'Enable journaling on an HFS+ volume'
complete -c diskutil -d 'Disable journaling on an HFS+ volume'
complete -c diskutil -d 'Create a 512MB Apple_Journal partition'
complete -c diskutil -d 'Enable ownership of a volume'
complete -c diskutil -d 'Disable ownership of a volume'
complete -c diskutil -d 'Verify the file system data structures of a volume'
complete -c diskutil -d 'Repair the file system data structures of a volume'
complete -c diskutil -d 'Verify the partition map layout of a whole disk'
complete -c diskutil -d 'Repair the partition map layout of a whole disk'
complete -c diskutil -d 'Erase an existing disk'
complete -c diskutil -d 'Write out a new empty file system volume'
complete -c diskutil -d 'Erase an existing volume by writing out a new empty file system'
complete -c diskutil -d 'Erase optical media (CD/RW, DVD/RW, etc.)'
complete -c diskutil -d 'Erase a device, writing zeros to the media'
complete -c diskutil -d 'Erase a whole disk, writing random data to the media'
complete -c diskutil -d 'Erase, using a secure method'
complete -c diskutil -d '(re)Partition a disk, removing all volumes'
complete -c diskutil -d 'Non-destructively resize a volume (partition)'
complete -c diskutil -d 'Destructively split a volume into multiple partitions'
complete -c diskutil -d 'Merge two or more partitions on a disk'
complete -c diskutil -d 'Merge two or more partitions on a disk'
complete -c diskutil -d 'Show status of all current APFS Containers'
complete -c diskutil -d 'Nondestructively convert from HFS to APFS'
complete -c diskutil -d 'Create a new APFS Container with one APFS Volume'
complete -c diskutil -d 'Create a new empty APFS Container'
complete -c diskutil -d 'Delete an APFS Container and reformat disks to HFS'
complete -c diskutil -d 'Resize an APFS Container and its disk space usage'
complete -c diskutil -d 'Export a new APFS Volume from an APFS Container'
complete -c diskutil -d 'Remove an APFS Volume from its APFS Container'
complete -c diskutil -d 'Erase contents of, but keep, an APFS Volume'
complete -c diskutil -d 'Change the Role metadata bits of an APFS Volume'
complete -c diskutil -d 'Unlock an encrypted APFS Volume which is locked'
complete -c diskutil -d 'Lock an encrypted APFS Volume (diskutil unmount)'
complete -c diskutil -d 'List cryptographic users of encrypted APFS Volume'
complete -c diskutil -d 'Change the passphrase of a cryptographic user'
complete -c diskutil -d 'Set or clear passphrase hint of a cryptographic user'
complete -c diskutil -d 'Start async encryption of an unencrypted APFS Volume'
complete -c diskutil -d 'Start async decryption of an encrypted APFS Volume'
complete -c diskutil -d 'Create, manipulate and destroy AppleRAID volumes'
complete -c diskutil -d 'Display the current status of RAID sets'
complete -c diskutil -d 'Create a RAID set on multiple disks'
complete -c diskutil -d 'Delete an existing RAID set'
complete -c diskutil -d 'Repair a damaged RAID mirror set'
complete -c diskutil -d 'Add a spare or member disk to an existing RAID'
complete -c diskutil -d 'Remove a spare or member disk from an existing RAID'
complete -c diskutil -d 'Convert a volume into a single disk RAID set'
complete -c diskutil -d 'Update the settings of an existing RAID'
complete -c diskutil -d 'Create, manipulate and destroy CoreStorage volumes'
complete -c diskutil -d 'Show status of CoreStorage volumes'
complete -c diskutil -d 'Get CoreStorage information by UUID or disk'
complete -c diskutil -d 'Convert a volume into a CoreStorage volume'
complete -c diskutil -d 'Revert a CoreStorage volume to its native type'
complete -c diskutil -d 'Create a new CoreStorage logical volume group'
complete -c diskutil -d 'Delete a CoreStorage logical volume group'
complete -c diskutil -d 'Rename a CoreStorage logical volume group'
complete -c diskutil -d 'Create a new CoreStorage logical volume'
complete -c diskutil -d 'Delete a volume from a logical volume group'
complete -c diskutil -d 'Start encrypting a CoreStorage logical volume'
complete -c diskutil -d 'Start decrypting a CoreStorage logical volume'
complete -c diskutil -d 'Attach/mount a locked CoreStorage logical volume'
complete -c diskutil -d 'Resize a CoreStorage volume'
complete -c diskutil -d 'Resize a CoreStorage physical volume disk'
complete -c diskutil -d 'Resize a CoreStorage logical/physical volume set'
