complete -c display -d 'Control alpha/matte channel of an image [option]'
complete -c display -d 'Remove pixel-aliasing'
complete -c display -d 'Decipher image with this password [password]'
complete -c display -d 'Display image centered on a backdrop'
complete -c display -d 'Apply option to select image channels [type]'
complete -c display -d 'Shared or Private [type]'
complete -c display -d 'Alternate image colorspace [type]'
complete -c display -d 'Annotate image with comment [string]'
complete -c display -d 'Type of pixel compression when writing the image [type]'
complete -c display -d 'Define one or more image format options [format:option]'
complete -c display -d 'Display the next image after pausing [value]'
complete -c display -d 'Horizontal and vertical density of the image [geometry]'
complete -c display -d 'Image depth [value]'
complete -c display -d 'Display image to this X server [server]'
complete -c display -d 'Layer disposal method [method]'
complete -c display -d 'Apply error diffusion to image [method]'
complete -c display -d 'Endianness (MSB or LSB) of the image [type]'
complete -c display -d 'Use this filter when resizing an image [type]'
complete -c display -d 'Output formatted image characteristics [string]'
complete -c display -d 'Preferred size and location of the Image window [geometry]'
complete -c display -d 'Horizontal and vertical backdrop placement [type]'
complete -c display -d 'Identify the format and characteristics of the image'
complete -c display -d 'Displayed image cannot be modified'
complete -c display -d 'Type of image interlacing scheme [type]'
complete -c display -d 'Pixel color interpolation method [method]'
complete -c display -d 'Assign a label to an image [string]'
complete -c display -d 'Pixel cache resource limit [type value]'
complete -c display -d 'Loop images then exit [iterations]'
complete -c display -d 'Display image using this Standard Colormap [type]'
complete -c display -d 'Monitor progress'
complete -c display -d 'Size and location of an image canvas [geometry]'
complete -c display -d 'Add, delete, or apply an image profile [filename]'
complete -c display -d 'JPEG/MIFF/PNG compression level [value]'
complete -c display -d 'Reduce colors in this colorspace [colorspace]'
complete -c display -d 'Suppress all warning messages'
complete -c display -d 'Pay attention to warning messages'
complete -c display -d 'Command execute a command in an remote display process'
complete -c display -d 'Size and location of an image canvas (operator) [geometry]'
complete -c display -d 'Settings remain in effect until parenthesis boundary'
complete -c display -d 'Horizontal and vertical sampling factor [geometry]'
complete -c display -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c display -d 'Set an image property [property value]'
complete -c display -d 'Width and height of image [geometry]'
complete -c display -d 'Texture name to tile onto the image background [filename]'
complete -c display -d 'Transparent color [color]'
complete -c display -d 'Color tree depth [value]'
complete -c display -d 'Seconds detect when image file is modified and redisplay'
complete -c display -d 'Print detailed information about the image'
complete -c display -d 'Display image using this visual type [type]'
complete -c display -d 'Virtual pixel access method [method]'
complete -c display -d 'Display image to background of this window [id]'
complete -c display -d 'Exit program when this window id is destroyed [id]'
complete -c display -d 'Write image to a file [filename]'
complete -c display -d 'Automagically orient (rotate) image'
complete -c display -d 'Surround image with a border of color [geometry]'
complete -c display -d 'Clip along the first path from the 8BIM profile'
complete -c display -d 'Clip along a named path from the 8BIM profile [id]'
complete -c display -d 'Preferred number of colors in the image [value]'
complete -c display -d 'Enhance or reduce the image contrast'
complete -c display -d 'Preferred size and location of the cropped image [geometry]'
complete -c display -d 'Convert cipher pixels to plain pixels [filename]'
complete -c display -d 'Straighten an image [threshold]'
complete -c display -d 'Reduce the speckles within an image'
complete -c display -d 'Apply a filter to detect edges in the image [factor]'
complete -c display -d 'Apply a digital filter to enhance a noisy image'
complete -c display -d 'Perform histogram equalization to an image'
complete -c display -d 'Extract area from image [geometry]'
complete -c display -d 'Flip image in the vertical direction'
complete -c display -d 'Flop image in the horizontal direction'
complete -c display -d 'Surround image with an ornamental border [geometry]'
complete -c display -d 'Colors within this distance are considered equal [distance]'
complete -c display -d 'Level of gamma correction [value]'
complete -c display -d 'Transform image to black and white'
complete -c display -d 'Replace every pixel with its complementary color'
complete -c display -d 'Transform image to span the full range of colors'
complete -c display -d 'Lighten/darken image edges to create a 3-D effect [value]'
complete -c display -d 'Change the resolution of an image [geometry]'
complete -c display -d 'Resize the image [geometry]'
complete -c display -d 'Roll an image vertically or horizontally [geometry]'
complete -c display -d 'Apply Paeth rotation to the image [degrees]'
complete -c display -d 'Scale image with pixel sampling [geometry]'
complete -c display -d 'Segment an image [value]'
complete -c display -d 'Sharpen the image [geometry]'
complete -c display -d 'Strip image of all profiles and comments'
complete -c display -d 'Threshold the image [value]'
complete -c display -d 'Create a thumbnail of the image [geometry]'
complete -c display -d 'Trim image edges'
complete -c display -d 'Merge a sequence of images'
complete -c display -d 'Flatten a sequence of images'
complete -c display -d 'Display copious debugging information [events]'
complete -c display -d 'Print program options'
complete -c display -d 'Print a list of supported option arguments [type]'
complete -c display -d 'Format of debugging information [format]'
complete -c display -d 'Print version information'
complete -c display -d 'Store matte channel if the image has one'
complete -c display -d 'Range image scene range'
complete -c display -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
