complete -c djxl -s 'V' -l 'version' -d 'Print version number'
complete -c djxl -l 'num_reps'
complete -c djxl -l 'use_sjpeg' -d 'Use sjpeg instead of libjpeg'
complete -c djxl -l 'jpeg_quality' -d 'JPEG output quality'
complete -c djxl -l 'num_threads' -d 'The number of threads to use'
complete -c djxl -l 'print_profile' -d 'Print timing information'
complete -c djxl -l 'print_info' -d 'Print AuxOut'
complete -c djxl -l 'bits_per_sample'
complete -c djxl -l 'color_space'
complete -c djxl -s 's' -l 'downsampling' -d 'Maximum permissible downsampling factor'
complete -c djxl -l 'allow_partial_files' -d 'Allow decoding of truncated files'
complete -c djxl -l 'allow_more_progressive_steps' -d 'Allow decoding more progressive steps'
complete -c djxl -s 'j' -l 'jpeg' -d 'Decode directly to JPEG'
complete -c djxl -l 'print_read_bytes' -d 'Print total number of decoded bytes'
complete -c djxl -s 'h' -l 'help' -d 'Print help message'
