complete -c dmesg -d 'Display system message buffer'
complete -c dmesg -s 'C' -l 'clear'
complete -c dmesg -s 'c' -l 'read-clear'
complete -c dmesg -s 'D' -l 'console-off'
complete -c dmesg -s 'd' -l 'show-delta'
complete -c dmesg -s 'E' -l 'console-on'
complete -c dmesg -s 'F' -l 'file'
complete -c dmesg -s 'f' -l 'facility'
complete -c dmesg -s 'h' -l 'help'
complete -c dmesg -s 'k' -l 'kernel'
complete -c dmesg -s 'l' -l 'level'
complete -c dmesg -s 'n' -l 'console-level'
complete -c dmesg -s 'r' -l 'raw'
complete -c dmesg -s 's' -l 'buffer-size'
complete -c dmesg -s 'T' -l 'ctime'
complete -c dmesg -s 'u' -l 'userspace'
complete -c dmesg -s 'V' -l 'version'
complete -c dmesg -s 'w' -l 'follow'
complete -c dmesg -s 'W' -l 'follow-new'
complete -c dmesg -s 'x' -l 'decode'
complete -c dmesg -s 'd'
complete -c dmesg -s 'T'
complete -c dmesg -s 'S'
complete -c dmesg -s 'a'
complete -c dmesg -s 'c'
complete -c dmesg -s 'M'
complete -c dmesg -s 'N'
