complete -c dmidecode -s 'd' -l 'dev-mem' -d 'Memory device file'
complete -c dmidecode -s 'q' -l 'quiet' -d 'Be less verbose'
complete -c dmidecode -l 'no-quirks' -d 'Decode everything exactly as it is'
complete -c dmidecode -s 's' -l 'string' -d 'Only display specified value'
complete -c dmidecode -s 't' -l 'type' -d 'Only display entries of specified type'
complete -c dmidecode -s 'H' -l 'handle' -d 'Only display specified handle'
complete -c dmidecode -s 'u' -l 'dump' -d 'Do not decode the entries'
complete -c dmidecode -l 'dump-bin' -d 'Dump DMI data to a file'
complete -c dmidecode -l 'from-dump' -d 'Read DMI data generated using --dump-bin'
complete -c dmidecode -l 'no-sysfs' -d 'Do not attempt to read DMI data from sysfs files'
complete -c dmidecode -l 'oem-string' -d 'Only display the value of the OEM string number N'
complete -c dmidecode -s 'h' -l 'help' -d 'Display usage information and exit'
complete -c dmidecode -s 'V' -l 'version' -d 'Display the version and exit'
