complete -c dnf -d 'Manage aliases'
complete -c dnf -d 'Add a new alias'
complete -c dnf -d 'Lists all defined aliases'
complete -c dnf -d 'Delete an alias'
complete -c dnf -d 'Removes unneeded packages'
complete -c dnf -d 'Check for problems in packagedb'
complete -c dnf -l 'dependencies' -d 'Checks dependencies'
complete -c dnf -l 'duplicates' -d 'Checks duplicates'
complete -c dnf -l 'obsoleted' -d 'Checks obsoleted'
complete -c dnf -l 'provides' -d 'Checks provides'
complete -c dnf -d 'Checks for updates'
complete -c dnf -l 'changelogs'
complete -c dnf -d 'Clean up cache directory'
complete -c dnf -d 'Removes the database cache'
complete -c dnf -d 'Marks the repository metadata expired'
complete -c dnf -d 'Removes repository metadata'
complete -c dnf -d 'Removes any cached packages'
complete -c dnf -d 'Removes all cache'
complete -c dnf -d 'Synchronizes packages to match the latest'
complete -c dnf -d 'Downgrades the specified package'
complete -c dnf -d 'Manage groups'
complete -c dnf -d 'Display overview of installed and available groups'
complete -c dnf -d 'Display package list of a group'
complete -c dnf -d 'Install group'
complete -c dnf -l 'with-optional' -d 'Include optional packages'
complete -c dnf -d 'List groups'
complete -c dnf -l 'installed' -d 'List installed groups'
complete -c dnf -l 'available' -d 'List available groups'
complete -c dnf -l 'hidden' -d 'List hidden groups'
complete -c dnf -d 'Remove group'
complete -c dnf -l 'with-optional' -d 'Include optional packages'
complete -c dnf -d 'Upgrade group'
complete -c dnf -d 'Marks group without manipulating packages'
complete -c dnf -d 'Mark group installed without installing packages'
complete -c dnf -d 'Mark group removed without removing packages'
complete -c dnf -d 'Display help and exit'
complete -c dnf -d 'View and manage past transactions'
complete -c dnf -d 'Lists all transactions'
complete -c dnf -d 'Describe the given transactions'
complete -c dnf -d 'Redoes the specified transaction'
complete -c dnf -d 'Undo all transactions performed after the specified transaction'
complete -c dnf -d 'Undoes the specified transaction'
complete -c dnf -d 'Lists all user installed packages'
complete -c dnf -d 'Describes the given package'
complete -c dnf -d 'Install package'
complete -c dnf -d 'Lists all packages'
complete -c dnf -l 'all' -d 'Lists all packages'
complete -c dnf -l 'installed' -d 'Lists installed packages'
complete -c dnf -l 'available' -d 'Lists available packages'
complete -c dnf -l 'extras' -d 'Lists installed packages that are not in any known repository'
complete -c dnf -l 'obsoletes' -d 'List installed obsoleted packages'
complete -c dnf -l 'recent' -d 'List recently added packages'
complete -c dnf -l 'upgrades' -d 'List available upgrades'
complete -c dnf -l 'autoremove' -d 'List packages which will be removed by autoremove'
complete -c dnf -d 'Downloads and caches metadata for all known repos'
complete -c dnf -l 'timer' -d 'Instructs DNF to be more resource-aware'
complete -c dnf -d 'Mark packages'
complete -c dnf -d 'Mark package installed'
complete -c dnf -d 'Unmarks installed package'
complete -c dnf -d 'Mark installed by group'
complete -c dnf -d 'Manage modules'
complete -c dnf -d 'Install module'
complete -c dnf -d 'Update modules'
complete -c dnf -d 'Remove module'
complete -c dnf -d 'Enable a module'
complete -c dnf -d 'Disable a module'
complete -c dnf -d 'Reset module state'
complete -c dnf -d 'List modules'
complete -c dnf -l 'all' -d 'Lists all module '
complete -c dnf -l 'enabled' -d 'Lists enabled module'
complete -c dnf -l 'disabled' -d 'Lists disabled module'
complete -c dnf -l 'installed' -d 'List  installed modules'
complete -c dnf -d 'Print module information'
complete -c dnf -l 'profile' -d 'Print module profiles information'
complete -c dnf -d 'Synchronizes packages to match the latest'
complete -c dnf -d 'Download updates for offline upgrade'
complete -c dnf -d 'Remove cached packages'
complete -c dnf -d 'Reboot and install packages'
complete -c dnf -d 'Install cached packages without reboot'
complete -c dnf -d 'Show logs of upgrade attempts'
complete -c dnf -d 'Prepare offline upgrade of the system'
complete -c dnf -d 'Download updates for offline upgrade'
complete -c dnf -d 'Remove cached packages'
complete -c dnf -d 'Reboot and install packages'
complete -c dnf -d 'Show logs of upgrade attempts'
complete -c dnf -d 'Finds packages providing the given command'
complete -c dnf -d 'Reinstalls a package'
complete -c dnf -d 'Remove packages'
complete -c dnf -d 'Removes the specified packages'
complete -c dnf -l 'duplicates' -d 'Removes older version of duplicated packages'
complete -c dnf -l 'oldinstallonly' -d 'Removes old installonly packages'
complete -c dnf -d 'Verbose repolist'
complete -c dnf -d 'Lists all enabled repositories'
complete -c dnf -d 'Queries DNF repositories'
complete -c dnf -l 'querytags' -d 'Provides the list of tags'
complete -c dnf -s 'a' -l 'all'
complete -c dnf -l 'enabled'
complete -c dnf -l 'arch' -l 'archlist'
complete -c dnf -l 'duplicates'
complete -c dnf -l 'unneeded'
complete -c dnf -l 'available'
complete -c dnf -l 'extras'
complete -c dnf -s 'f' -l 'file'
complete -c dnf -l 'installed'
complete -c dnf -l 'installonly'
complete -c dnf -l 'latest-limit'
complete -c dnf -l 'recent'
complete -c dnf -l 'repo'
complete -c dnf -l 'unsatisfied'
complete -c dnf -l 'upgrades'
complete -c dnf -l 'userinstalled'
complete -c dnf -l 'whatdepends'
complete -c dnf -l 'whatconflicts'
complete -c dnf -l 'whatenhances'
complete -c dnf -l 'whatobsoletes'
complete -c dnf -l 'whatprovides'
complete -c dnf -l 'whatrecommends'
complete -c dnf -l 'whatrequires'
complete -c dnf -l 'whatsuggests'
complete -c dnf -l 'whatsupplements'
complete -c dnf -l 'alldeps'
complete -c dnf -l 'exactdeps'
complete -c dnf -l 'srpm'
complete -c dnf -d 'Prepare major version upgrade of the system'
complete -c dnf -d 'Download updates for offline upgrade'
complete -c dnf -d 'Remove cached packages'
complete -c dnf -d 'Reboot and install packages'
complete -c dnf -d 'Install cached packages without reboot'
complete -c dnf -d 'Show logs of upgrade attempts'
complete -c dnf -s 'i' -l 'info' -d 'Show detailed information about the package'
complete -c dnf -s 'l' -l 'list' -d 'Show the list of files in the package'
complete -c dnf -s 's' -l 'source' -d 'Show the package source RPM name'
complete -c dnf -l 'changelogs' -d 'Print the package changelogs'
complete -c dnf -l 'conflicts' -d 'Display capabilities that the package conflicts with'
complete -c dnf -l 'depends' -d 'Display capabilities that the package depends on'
complete -c dnf -l 'enhances' -d 'Display capabilities enhanced by the package'
complete -c dnf -l 'location' -d 'Show a location where the package could be downloaded from'
complete -c dnf -l 'obsoletes' -d 'Display capabilities that the package obsoletes'
complete -c dnf -l 'provides' -d 'Display capabilities provided by the package'
complete -c dnf -l 'recommends' -d 'Display capabilities recommended by the package'
complete -c dnf -l 'requires' -d 'Display capabilities that the package depends on'
complete -c dnf -l 'requires-pre' -d 'Display capabilities that the package depends on'
complete -c dnf -l 'suggests' -d 'Display capabilities suggested by the package'
complete -c dnf -l 'supplements' -d 'Display capabilities supplemented by the package'
complete -c dnf -l 'tree' -d 'Display a recursive tree of packages'
complete -c dnf -l 'deplist' -d 'Produce a list of all dependencies'
complete -c dnf -l 'nvr' -d 'Format like name-version-release'
complete -c dnf -l 'nevra' -d 'Format like name-epoch:version-release.architecture'
complete -c dnf -l 'envra' -d 'Format like epoch:name-version-release.architecture'
complete -c dnf -l 'qf' -l 'queryformat' -d 'Custom display format'
complete -c dnf -l 'recursive' -d 'Query packages recursively'
complete -c dnf -l 'resolve' -d 'Resolve capabilities to originating packages'
complete -c dnf -d 'Run commands on all packages in the repository'
complete -c dnf -d 'Search package metadata for keywords'
complete -c dnf -l 'all' -d 'Lists packages that match at least one of the keys'
complete -c dnf -d 'Opens an interactive shell'
complete -c dnf -d 'Remove spec and install spec in one transaction'
complete -c dnf -d 'Display information about update advisories'
complete -c dnf -l 'summary' -d 'Displays the summary'
complete -c dnf -l 'list' -d 'List of advisories'
complete -c dnf -l 'info' -d 'Detailed information'
complete -c dnf -l 'all'
complete -c dnf -l 'available'
complete -c dnf -l 'installed'
complete -c dnf -l 'updates'
complete -c dnf -d 'Updates packages'
complete -c dnf -d 'Updates packages'
complete -c dnf -d 'DNF versionlock plugin'
complete -c dnf -d 'Add  a versionlock for all available packages matching the spec'
complete -c dnf -d 'Add an exclude (within  versionlock) for the available packages matching the spec'
complete -c dnf -d 'Remove any matching versionlock entries'
complete -c dnf -d 'List the current versionlock entries'
complete -c dnf -d 'Remove all versionlock entries'
complete -c dnf -s '4' -d 'Use IPv4 only'
complete -c dnf -s '6' -d 'Use IPv6 only'
complete -c dnf -l 'advisory' -l 'advisories' -d 'Include packages corresponding to the advisory ID'
complete -c dnf -l 'allowerasing' -d 'Allow erasing of installed packages to resolve dependencies'
complete -c dnf -l 'assumeno' -d 'Answer no for all questions'
complete -c dnf -s 'b' -l 'best' -d 'Try the best available package versions in transactions'
complete -c dnf -l 'bugfix' -d 'Include packages that fix a bugfix issue'
complete -c dnf -l 'bz' -l 'bzs' -d 'Include packages that fix a Bugzilla ID'
complete -c dnf -s 'C' -l 'cacheonly' -d 'Run entirely from system cache'
complete -c dnf -l 'color' -d 'Control whether color is used'
complete -c dnf -s 'c' -l 'config' -d 'Configuration file location'
complete -c dnf -l 'cve' -l 'cves' -d 'Include packages that fix a CVE'
complete -c dnf -s 'd' -l 'debuglevel' -d 'Debugging output level'
complete -c dnf -l 'debugsolver' -d 'Dump dependency solver debugging info'
complete -c dnf -l 'disableexcludes' -l 'disableexcludepkgs' -d 'Disable excludes'
complete -c dnf -l 'disable' -l 'set-disabled' -d 'Disable specified repositories'
complete -c dnf -l 'disableplugin' -d 'Disable the listed plugins specified'
complete -c dnf -l 'disablerepo' -d 'Disable specified repositories'
complete -c dnf -l 'downloaddir' -l 'destdir' -d 'Change downloaded packages to provided directory'
complete -c dnf -l 'downloadonly' -d 'Download packages without performing any transaction'
complete -c dnf -l 'enable' -l 'set-enabled' -d 'Enable specified repositories'
complete -c dnf -l 'enableplugin' -d 'Enable the listed plugins'
complete -c dnf -l 'enablerepo' -d 'Enable additional repositories'
complete -c dnf -l 'enhancement' -d 'Include enhancement relevant packages'
complete -c dnf -s 'x' -l 'exclude' -d 'Exclude packages specified'
complete -c dnf -l 'forcearch' -d 'Force the use of the specified architecture'
complete -c dnf -s 'h' -l 'help' -l 'help-i' -d 'Show the help'
complete -c dnf -l 'installroot' -d 'Specifies an alternative installroot'
complete -c dnf -l 'newpackage' -d 'Include newpackage relevant packages'
complete -c dnf -l 'noautoremove' -d 'Disable autoremove'
complete -c dnf -l 'nobest' -d 'Set best option to False'
complete -c dnf -l 'nodocs' -d 'Do not install documentation'
complete -c dnf -l 'nogpgcheck' -d 'Skip checking GPG signatures on packages'
complete -c dnf -l 'noplugins' -d 'Disable all plugins'
complete -c dnf -l 'obsoletes' -d 'Enables obsoletes processing logic'
complete -c dnf -s 'q' -l 'quiet' -d 'Quiet mode'
complete -c dnf -s 'R' -l 'randomwait' -d 'Maximum command wait time'
complete -c dnf -l 'refresh' -d 'Set metadata as expired before running the command'
complete -c dnf -l 'releasever' -d 'Configure the distribution release'
complete -c dnf -l 'repofrompath' -d 'Specify repository to add to the repositories for this query'
complete -c dnf -l 'repo' -l 'repoid' -d 'Enable just specific repositories by an id or a glob'
complete -c dnf -l 'rpmverbosity' -d 'RPM debug scriptlet output level'
complete -c dnf -l 'sec-severity' -l 'secseverity' -d 'Includes packages that provide a fix for an issue of the specified severity'
complete -c dnf -l 'security' -d 'Includes packages that provide a fix for a security issue'
complete -c dnf -l 'setopt' -d 'Override a configuration option'
complete -c dnf -l 'skip-broken' -d 'Skips broken packages'
complete -c dnf -l 'showduplicates' -d 'Shows duplicate packages'
complete -c dnf -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c dnf -l 'version' -d 'Shows DNF version and exit'
complete -c dnf -s 'y' -l 'assumeyes' -d 'Answer yes for all questions'
