complete -c dropdb -s 'e' -l 'echo' -d 'Show the commands being sent to the server'
complete -c dropdb -s 'i' -l 'interactive' -d 'Prompt before deleting anything'
complete -c dropdb -s 'V' -l 'version' -d 'Output version information, then exit'
complete -c dropdb -l 'if-exists' -d 'Don'"'"'t report error if database doesn'"'"'t exist'
complete -c dropdb -s '?' -l 'help' -d 'Show help, then exit'
complete -c dropdb -s 'h' -l 'host' -d 'Database server host or socket directory'
complete -c dropdb -s 'p' -l 'port' -d 'Database server port'
complete -c dropdb -s 'U' -l 'username' -d 'User name to connect as'
complete -c dropdb -s 'w' -l 'no-password' -d 'Never prompt for password'
complete -c dropdb -s 'W' -l 'password' -d 'Force password prompt'
complete -c dropdb -l 'maintenance-db' -d 'Alternate maintenance database'
