complete -c dua -s 'A' -l 'apparent-size' -d 'Display apparent size instead of disk usage'
complete -c dua -s 'h' -l 'help' -d 'Print help information'
complete -c dua -s 'i' -l 'ignore-dirs' -d 'One or more absolute directories to ignore'
complete -c dua -s 'l' -l 'count-hard-links' -d 'Count hard-linked files each time they are seen'
complete -c dua -s 't' -l 'threads' -d 'The amount of threads to use'
complete -c dua -s 'V' -l 'version' -d 'Print version information'
complete -c dua -s 'x' -l 'stay-on-filesystem' -d 'If set, we will not cross filesystems or traverse mount points'
complete -c dua -d 'Aggregrate the consumed space of one or more directories or files'
complete -c dua -d 'Aggregrate the consumed space of one or more directories or files'
complete -c dua -l 'no-sort' -d 'Do not sort paths by their size in bytes'
complete -c dua -l 'no-total' -d 'Do not compute total column for multiple inputs'
complete -c dua -l 'stats' -d 'Print additional statistics about the file traversal to stderr'
complete -c dua -d 'Print help message or the help of the given subcommand(s)'
complete -c dua -d 'Launch the terminal user interface'
complete -c dua -d 'Launch the terminal user interface'
