complete -c duf -l 'all' -d 'include pseudo, duplicate, inaccessible file systems'
complete -c duf -l 'avail-threshold' -d 'specifies the coloring threshold (yellow, red) of the avail column, must be integer with optional SI prefixes (default '"'"'10G,1G'"'"')'
complete -c duf -l 'hide' -d 'hide specific devices, separated with commas'
complete -c duf -l 'hide-fs' -d 'hide specific filesystems, separated with commas'
complete -c duf -l 'hide-mp' -d 'hide specific mount points, separated with commas (supports wildcards)'
complete -c duf -l 'inodes' -d 'list inode information instead of block usage'
complete -c duf -l 'json' -d 'output all devices in JSON format'
complete -c duf -l 'only' -d 'show only specific devices, separated with commas'
complete -c duf -l 'only-fs' -d 'only specific filesystems, separated with commas'
complete -c duf -l 'only-mp' -d 'only specific mount points, separated with commas (supports wildcards)'
complete -c duf -l 'output' -d 'output fields, separated with commas'
complete -c duf -l 'sort' -d 'sort output (default '"'"'mountpoint'"'"')'
complete -c duf -l 'style' -d 'style (default '"'"'unicode'"'"')'
complete -c duf -l 'theme' -d 'color themes (default '"'"'light'"'"')'
complete -c duf -l 'usage-threshold' -d 'specifies the coloring threshold (yellow, red) of the usage bars as a floating point number from 0 to 1 (default '"'"'0.5,0.9'"'"')'
complete -c duf -l 'version' -d 'display version'
complete -c duf -l 'warnings' -d 'output all warnings to STDERR'
complete -c duf -l 'width' -d 'max output width'
