complete -c dupload -s 'h' -l 'help' -d '(_'
complete -c dupload -s 'f' -l 'force' -d '(_'
complete -c dupload -s 'k' -l 'keep' -d '(_'
complete -c dupload -s 'c' -l 'configfile' -d '(_'
complete -c dupload -l 'no' -d '(_'
complete -c dupload -l 'nomail' -d '(_'
complete -c dupload -l 'mailonly' -d '(_'
complete -c dupload -l 'noarchive' -d '(_'
complete -c dupload -s 'p' -l 'print' -d '(_'
complete -c dupload -s 'q' -l 'quiet' -d '(_'
complete -c dupload -s 't' -l 'to' -d '(_'
complete -c dupload -s 'V' -l 'version' -d '(_'
