complete -c ebuild -l 'debug' -d 'Run bash with the -x option'
complete -c ebuild -l 'force' -d 'Force regeneration of digests'
complete -c ebuild -l 'ignore-default-opts' -d 'Ignore EBUILD_DEFAULT_OPTS'
complete -c ebuild -l 'skip-manifest' -d 'Skip all manifest checks'
complete -c ebuild -d 'Show help'
complete -c ebuild -d 'Run pkg_pretend()'
complete -c ebuild -d 'Run setup and system checks'
complete -c ebuild -d 'Clean build dir'
complete -c ebuild -d 'Fetches all files from SRC_URI'
complete -c ebuild -d 'Update pkg manifest'
complete -c ebuild -d 'Extracts sources'
complete -c ebuild -d 'Run src_prepare()'
complete -c ebuild -d 'Run src_configure()'
complete -c ebuild -d 'Run src_compile()'
complete -c ebuild -d 'Run tests'
complete -c ebuild -d 'Run pkg_preinst()'
complete -c ebuild -d 'Run src_install()'
complete -c ebuild -d 'Run pkg_postinst()'
complete -c ebuild -d 'Install files to live filesystem'
complete -c ebuild -d 'Run fetch, unpack, compile, install and qmerge'
complete -c ebuild -d 'Uninstall files from live filesystem'
complete -c ebuild -d 'Run pkg_prerm()'
complete -c ebuild -d 'Run pkg_postrm()'
complete -c ebuild -d 'Run post-install configuration'
complete -c ebuild -d 'Create a binpkg in PKGDIR'
complete -c ebuild -d 'Builds a RedHat RPM pkg'
