complete -c elm -d 'Open up an interactive programming session'
complete -c elm -l 'no-colors' -d 'Turn off the colors in REPL'
complete -c elm -l 'interpreter' -d 'Path to an alternative JS interpreter'
complete -c elm -d 'Compile code with a click'
complete -c elm -l 'port' -d 'Compile code with a click'
complete -c elm -d 'Compiles Elm code in JS or HTML'
complete -c elm -l 'output' -d 'Specify the name of resulting JS file'
complete -c elm -l 'debug' -d 'Turn on the time-travelling debugger'
complete -c elm -l 'optimize' -d 'Turn on optimizations to make code smaller and faster'
complete -c elm -l 'docs' -d 'Generate a JSON file of documentation for a package'
complete -c elm -d 'Start an Elm project'
complete -c elm -d 'Fetches packages from Elm repository'
complete -c elm -d 'Figures out the next version number based on API changes'
complete -c elm -d 'See what changed in a package between different versions'
complete -c elm -d 'Publishes your package on package.elm-lang.org so anyone in the community can use it'
complete -c elm -l 'help' -d 'Show a more detailed description'
