complete -c elvish -d 'Show help and exit'
complete -c elvish -d 'Show version and exit'
complete -c elvish -d 'Show build info and exit'
complete -c elvish -s 'c' -d 'Compile'
complete -c elvish -d 'Write cpu profile'
complete -c elvish -d 'Warn about deprecated features'
complete -c elvish -s 'i' -d 'Show output in JSON'
complete -c elvish -d 'Use log file'
complete -c elvish -d 'Use startup file'
