complete -c emaint -s 'h' -l 'help' -d 'Show this help message and exit'
complete -c emaint -s 'c' -l 'check' -d 'Check for problems'
complete -c emaint -l 'version' -d 'Show program'"'"'s version number and exit'
complete -c emaint -s 'f' -l 'fix' -d 'Attempt to fix problems'
complete -c emaint -s 'P' -l 'purge' -d 'Remove the list of failed merges'
complete -c emaint -d 'Perform all supported commands'
complete -c emaint -d 'Scan and generate metadata indexes for binary pkgs'
complete -c emaint -d 'Check and clean the config tracker list for uninstalled pkgs'
complete -c emaint -d 'Discard emerge --resume merge lists'
complete -c emaint -d 'Check and clean old logs in the PORT_LOGDIR'
complete -c emaint -d 'Scan for failed merges and fix them'
complete -c emaint -d 'Perform pkg move updates for binary pkgs'
complete -c emaint -d 'Perform pkg move updates for installed and binary pkgs'
complete -c emaint -d 'Check repos.conf settings and sync repositories'
complete -c emaint -d 'Check and fix problems in the world file'
complete -c emaint -s 'p' -l 'pretend' -d 'Output logs that would be deleted'
complete -c emaint -s 'C' -l 'clean' -d 'Cleans out logs more than 7 days old'
complete -c emaint -s 'a' -l 'auto' -d 'Sync auto-sync enabled repos only'
complete -c emaint -s 'A' -l 'allrepos' -d 'Sync all repos that have a sync-url defined'
