complete -c emerge -l 'check-news'
complete -c emerge -l 'clean'
complete -c emerge -l 'config'
complete -c emerge -s 'c' -l 'depclean'
complete -c emerge -l 'deselect'
complete -c emerge -s 'h' -l 'help'
complete -c emerge -l 'info'
complete -c emerge -l 'list-sets'
complete -c emerge -l 'metadata'
complete -c emerge -s 'P' -l 'prune'
complete -c emerge -l 'regen'
complete -c emerge -s 'r' -l 'resume'
complete -c emerge -s 's' -l 'search'
complete -c emerge -s 'S' -l 'searchdesc'
complete -c emerge -l 'sync'
complete -c emerge -s 'C' -l 'unmerge'
complete -c emerge -s 'V' -l 'version'
complete -c emerge -s 'A' -l 'alert' -d 'Add a terminal bell character ('"'"'\a'"'"') to all interactive prompts'
complete -c emerge -s 'a' -l 'ask' -d 'Prompt the user before peforming the merge'
complete -c emerge -l 'backtrack'
complete -c emerge -s 'b' -l 'buildpkg' -d 'Build a binary pkg additionally'
complete -c emerge -s 'B' -l 'buildpkgonly' -d 'Only build a binary pkg'
complete -c emerge -s 'U' -l 'changed-use'
complete -c emerge -s 'l' -l 'changelog' -d 'Show changelog of pkg. Use with --pretend'
complete -c emerge -l 'columns' -d 'Align output. Use with --pretend'
complete -c emerge -l 'complete-graph'
complete -c emerge -s 'd' -l 'debug' -d 'Run in debug mode'
complete -c emerge -s 'D' -l 'deep' -d 'Consider the whole dependency tree'
complete -c emerge -s 'e' -l 'emptytree' -d 'Reinstall all world pkgs'
complete -c emerge -l 'exclude'
complete -c emerge -s 'f' -l 'fetchonly' -d 'Only download the pkgs but don'"'"'t install them'
complete -c emerge -s 'F' -l 'fetch-all-uri' -d 'Same as --fetchonly and grab all potential files'
complete -c emerge -s 'g' -l 'getbinpkg' -d 'Download infos from each binary pkg. Implies -k'
complete -c emerge -s 'G' -l 'getbinpkgonly' -d 'As -g but don'"'"'t use local infos'
complete -c emerge -l 'ignore-default-opts' -d 'Ignore EMERGE_DEFAULT_OPTS'
complete -c emerge -l 'jobs'
complete -c emerge -l 'keep-going'
complete -c emerge -s 'N' -l 'newuse' -d 'Include installed pkgs with changed USE flags'
complete -c emerge -l 'noconfmem' -d 'Disregard merge records'
complete -c emerge -s 'O' -l 'nodeps' -d 'Don'"'"'t merge dependencies'
complete -c emerge -s 'n' -l 'noreplace' -d 'Skip already installed pkgs'
complete -c emerge -l 'nospinner' -d 'Disable the spinner'
complete -c emerge -s '1' -l 'oneshot' -d 'Don'"'"'t add pkgs to world'
complete -c emerge -s 'o' -l 'onlydeps' -d 'Only merge dependencies'
complete -c emerge -s 'p' -l 'pretend' -d 'Display what would be done without doing it'
complete -c emerge -s 'q' -l 'quiet' -d 'Use a condensed output'
complete -c emerge -s 'w' -l 'select'
complete -c emerge -l 'skipfirst' -d 'Remove first pkg in resume list. Use with --resume'
complete -c emerge -s 't' -l 'tree' -d 'Show the dependency tree'
complete -c emerge -s 'u' -l 'update'
complete -c emerge -s 'k' -l 'usepkg' -d 'Use binary pkg if available'
complete -c emerge -s 'K' -l 'usepkgonly' -d 'Only use binary pkgs'
complete -c emerge -s 'v' -l 'verbose' -d 'Run in verbose mode'
complete -c emerge -l 'verbose-conflicts' -d 'Verbose slot conflicts'
