complete -c eopkg -d 'Repository'
complete -c eopkg -d 'Available Package'
complete -c eopkg -d 'Installed package'
complete -c eopkg -s 'c' -l 'component' -d 'Component'
complete -c eopkg -s 'r' -l 'repository' -d 'Repository'
complete -c eopkg -l 'version' -d 'Show program'"'"'s version number and exit'
complete -c eopkg -s 'd' -l 'debug' -d 'Show debugging information'
complete -c eopkg -s 'D' -l 'destdir' -d 'Change the system root for eopkg commands'
complete -c eopkg -s 'h' -l 'help' -d 'Show help message and exit'
complete -c eopkg -s 'L' -l 'bandwidth-limit' -d 'Keep bandwidth usage under specified KB'"'"'s'
complete -c eopkg -s 'p' -l 'password'
complete -c eopkg -s 'u' -l 'username'
complete -c eopkg -s 'v' -l 'verbose' -d 'Detailed output'
complete -c eopkg -s 'y' -l 'yes-all' -d 'Assume yes for all yes/no queries'
