complete -c equery -s 'h' -l 'help' -d 'Displays a help message'
complete -c equery -s 'q' -l 'quiet' -d 'Minimal output'
complete -c equery -s 'C' -l 'no-color' -d 'Turns off colors'
complete -c equery -s 'N' -l 'no-pipe' -d 'Turns off pipe detection'
complete -c equery -s 'V' -l 'version' -d 'Display version information'
complete -c equery -d 'List all pkgs owning file(s)'
complete -c equery -d 'List changelog entries for ATOM'
complete -c equery -d 'Check pkg'"'"'s MD5sums and timestamps'
complete -c equery -d 'List all pkgs depending on specified pkg'
complete -c equery -d 'Display pkg'"'"'s dependency tree'
complete -c equery -d 'List files owned by pkg'
complete -c equery -d 'List pkgs for matching ENVIRONMENT data'
complete -c equery -d 'List pkgs with specified useflag'
complete -c equery -d 'Display pkg'"'"'s keywords'
complete -c equery -d 'List all pkgs matching pattern'
complete -c equery -d 'Display pkg'"'"'s metadata'
complete -c equery -d 'Print size of files contained in pkg'
complete -c equery -d 'Display pkg'"'"'s USE flags'
complete -c equery -d 'Print full path to ebuild for pkg'
complete -c equery -s 'f' -l 'full-regex' -d 'Query is a regex'
complete -c equery -s 'e' -l 'early-out' -d 'Stop after first match'
complete -c equery -s 'n' -l 'name-only' -d 'Omit version'
complete -c equery -s 'l' -l 'latest' -d 'Display only latest ChangeLog entry'
complete -c equery -s 'f' -l 'full' -d 'Display full ChangeLog'
complete -c equery -s 'f' -l 'full-regex' -d 'Query is a regex'
complete -c equery -s 'o' -l 'only-failures' -d 'Only display pkgs that do not pass'
complete -c equery -s 'a' -l 'all-packages' -d 'Include dependencies that are not installed (slow)'
complete -c equery -s 'D' -l 'indirect' -d 'Search both direct and indirect dependencies'
complete -c equery -s 'A' -l 'no-atom' -d 'Don'"'"'t show dependency atom'
complete -c equery -s 'M' -l 'no-mask' -d 'Don'"'"'t show masking status'
complete -c equery -s 'U' -l 'no-useflags' -d 'Don'"'"'t show USE flags'
complete -c equery -s 'l' -l 'linear' -d 'Don'"'"'t indent dependencies'
complete -c equery -s 'm' -l 'md5sum' -d 'Include MD5 sum in output'
complete -c equery -s 's' -l 'timestamp' -d 'Include timestamp in output'
complete -c equery -s 't' -l 'type' -d 'Include file type in output'
complete -c equery -l 'tree' -d 'Display results in a tree'
complete -c equery -s 'I' -l 'exclude-installed' -d 'Exclude installed pkgs from search path'
complete -c equery -s 'o' -l 'overlay-tree' -d 'Include overlays in search path'
complete -c equery -s 'p' -l 'portage-tree' -d 'Include entire portage tree in search path'
complete -c equery -s 'd' -l 'duplicates' -d 'List only installed duplicate pkgs'
complete -c equery -s 'b' -l 'binpkgs-missing' -d 'List only installed pkgs without a corresponding binary pkg'
complete -c equery -s 'f' -l 'full-regex' -d 'Query is a regex'
complete -c equery -s 'm' -l 'mask-reason' -d 'Include reason for pkg mask'
complete -c equery -s 'I' -l 'exclude-installed' -d 'Exclude installed pkgs from output'
complete -c equery -s 'o' -l 'overlay-tree' -d 'List pkgs in overlays'
complete -c equery -s 'p' -l 'portage-tree' -d 'List pkgs in the main portage tree'
complete -c equery -s 'd' -l 'description' -d 'Show extended pkg description'
complete -c equery -s 'H' -l 'herd' -d 'Show pkg'"'"'s herd(s)'
complete -c equery -s 'k' -l 'keywords' -d 'Show keywords for all matching pkg versions'
complete -c equery -s 'l' -l 'license' -d 'Show licenses for the best matching version'
complete -c equery -s 'm' -l 'maintainer' -d 'Show the maintainer(s) for the pkg'
complete -c equery -s 'S' -l 'stablreq' -d 'Show STABLEREQ arches (cc'"'"'s) for all matching pkg versions'
complete -c equery -s 'u' -l 'useflags' -d 'Show per-pkg USE flag descriptions'
complete -c equery -s 'U' -l 'upstream' -d 'Show pkg'"'"'s upstream information'
complete -c equery -s 'x' -l 'xml' -d 'Show the plain metadata.xml file'
complete -c equery -s 'b' -l 'bytes' -d 'Report size in bytes'
complete -c equery -s 'f' -l 'full-regex' -d 'Query is a regex'
complete -c equery -s 'a' -l 'all' -d 'Include all pkg versions'
complete -c equery -s 'i' -l 'ignore-l10n' -d 'Don'"'"'t show l10n USE flags'
complete -c equery -s 'm' -l 'include-masked' -d 'Return highest version ebuild available'
complete -c equery -s 'e' -l 'ebuild' -d 'Print the ebuild'
