complete -c expect -s 'c' -d 'execute command'
complete -c expect -s 'd' -d 'diagnostic output'
complete -c expect -s 'D' -d 'debug value'
complete -c expect -s 'f' -d 'script path'
complete -c expect -s 'i' -d 'interactive mode'
complete -c expect -s 'v' -d 'print version'
complete -c expect -s 'N' -d 'skip global rc'
complete -c expect -s 'n' -d 'skip user rc'
complete -c expect -s 'b' -d 'read line by line'
