complete -c fail2ban-client -s 'c' -l 'conf' -d 'Configuration dir'
complete -c fail2ban-client -s 's' -l 'socket' -d 'Socket path'
complete -c fail2ban-client -s 'p' -l 'pidfile' -d 'Pidfile path'
complete -c fail2ban-client -l 'pname' -d 'Name of the process'
complete -c fail2ban-client -l 'loglevel' -d 'loglevel of client'
complete -c fail2ban-client -l 'logtarget' -d 'Logging target'
complete -c fail2ban-client -l 'logtarget' -d 'Syslogsocket'
complete -c fail2ban-client -s 'd' -d 'Dump configuration'
complete -c fail2ban-client -l 'dp' -l 'dump-pretty' -d 'Dump configuration (pretty)'
complete -c fail2ban-client -s 't' -l 'test' -d 'Test configuration'
complete -c fail2ban-client -s 'i' -d 'Run in interactive mode'
complete -c fail2ban-client -s 'v' -d 'Increase verbosity'
complete -c fail2ban-client -s 'q' -d 'Decrease verbosity'
complete -c fail2ban-client -s 'x' -d 'Force execution of server'
complete -c fail2ban-client -s 'b' -d 'Start server in background (default)'
complete -c fail2ban-client -s 'f' -d 'Start server in foreground'
complete -c fail2ban-client -l 'str2sec' -d 'Convert time abbr format to secs'
complete -c fail2ban-client -s 'h' -l 'help' -d 'Display help message'
complete -c fail2ban-client -s 'V' -l 'version' -d 'Display client version'
complete -c fail2ban-client -d 'Start fail2ban server or jail'
complete -c fail2ban-client -d 'Restart server or jail'
complete -c fail2ban-client -d 'Reload server configuration'
complete -c fail2ban-client -d 'Stop fail2ban server or jail'
complete -c fail2ban-client -d 'Unban ip address(es)'
complete -c fail2ban-client -d 'List jails w/ their banned IPs'
complete -c fail2ban-client -d 'Get server or jail status'
complete -c fail2ban-client -d 'Check if server is alive'
complete -c fail2ban-client -d 'Prints usage synopsis'
complete -c fail2ban-client -d 'Prints server version'
complete -c fail2ban-client -d 'Flushes log files and reopens'
complete -c fail2ban-client -l 'unban'
complete -c fail2ban-client -l 'if-exists'
complete -c fail2ban-client -l 'restart'
complete -c fail2ban-client -l 'unban'
complete -c fail2ban-client -l 'all'
complete -c fail2ban-client -l 'if-exists'
complete -c fail2ban-client -l 'all'
complete -c fail2ban-client -d 'Get server log level'
complete -c fail2ban-client -d 'Change server log level'
complete -c fail2ban-client -d 'Get server log output'
complete -c fail2ban-client -d 'Change server log output'
complete -c fail2ban-client -d 'Get server syslog socket'
complete -c fail2ban-client -d 'Change server syslog socket'
complete -c fail2ban-client -d 'Get server db path'
complete -c fail2ban-client -d 'Change server db path'
complete -c fail2ban-client -d 'Get max matches stored per ticket'
complete -c fail2ban-client -d 'Set max matches stored per ticket'
complete -c fail2ban-client -d 'Get secs ban history will be kept'
complete -c fail2ban-client -d 'Set secs ban history will be kept'
