complete -c fastboot -s 'h' -l 'help' -d 'Show this message'
complete -c fastboot -s 'v' -l 'verbose' -d 'Verbose output'
complete -c fastboot -l 'version' -d 'Display version'
complete -c fastboot -s 'w' -d 'Wipe userdata'
complete -c fastboot -s 's' -d 'Specify a device'
complete -c fastboot -s 'S' -d 'Break into sparse files no larger than SIZE'
complete -c fastboot -l 'set-active' -d 'Sets the active slot before rebooting'
complete -c fastboot -d 'Flash all partitions from $ANDROID_PRODUCT_OUT'
complete -c fastboot -d 'Display given bootloader variable'
complete -c fastboot -d 'Execute OEM-specific command'
complete -c fastboot -d 'Lock/unlock'
complete -c fastboot -d 'Reboot device'
complete -c fastboot -d 'Flash all partitions from an update.zip package'
complete -c fastboot -d 'Erase a flash partition'
complete -c fastboot -d 'Format a flash partition'
complete -c fastboot -d 'List devices in bootloader'
complete -c fastboot -d 'Flash given partition'
complete -c fastboot -d 'Show help message'
complete -c fastboot -d 'Sends given file to stage for the next command'
complete -c fastboot -d 'Writes data staged by the last command to a file'
complete -c fastboot -d 'Fetch a partition image from the device'
complete -c fastboot -d 'Download and boot kernel from RAM'
complete -c fastboot -l 'disable-verity' -d 'Sets disable-verity when flashing vbmeta'
complete -c fastboot -l 'disable-verification' -d 'Sets disable-verification when flashing vbmeta'
complete -c fastboot -l 'force' -d 'Force a flash operation that may be unsafe'
complete -c fastboot -s 'l' -d 'device paths'
