complete -c ffmpeg -s 'i' -d 'Specify input file'
complete -c ffmpeg -s 'L' -d 'Show license'
complete -c ffmpeg -s 'h' -s '?' -l 'help' -d 'Show help'
complete -c ffmpeg -d 'Show version'
complete -c ffmpeg -d 'Show build configuration'
complete -c ffmpeg -d 'Show available formats'
complete -c ffmpeg -d 'Show available muxers'
complete -c ffmpeg -d 'Show available demuxers'
complete -c ffmpeg -d 'Show available devices'
complete -c ffmpeg -d 'Show available codecs'
complete -c ffmpeg -d 'Show available decoders'
complete -c ffmpeg -d 'Show available encoders'
complete -c ffmpeg -d 'Show available bit stream filters'
complete -c ffmpeg -d 'Show available protocols'
complete -c ffmpeg -d 'Show available filters'
complete -c ffmpeg -d 'Show available pixel formats'
complete -c ffmpeg -d 'Show standard channel layouts'
complete -c ffmpeg -d 'Show available audio sample formats'
complete -c ffmpeg -d 'Show available color names'
complete -c ffmpeg -d 'List sources of the input device'
complete -c ffmpeg -d 'List sinks of the output device'
complete -c ffmpeg -d 'Show available HW acceleration methods'
complete -c ffmpeg -d 'Generate a report'
complete -c ffmpeg -d 'Set maximum size of a single allocated block'
complete -c ffmpeg -s 'y' -d 'Overwrite output files'
complete -c ffmpeg -s 'n' -d 'Never overwrite output files'
complete -c ffmpeg -d 'Ignore unknown stream types'
complete -c ffmpeg -d 'Number of non-complex filter threads'
complete -c ffmpeg -d 'Number of threads for -filter_complex'
complete -c ffmpeg -d 'Print progress report during encoding'
complete -c ffmpeg -d 'Ratio of errors'
complete -c ffmpeg -d 'Set the number of bits per raw sample'
complete -c ffmpeg -d 'Change audio volume'
complete -c ffmpeg -s 'f' -d 'Force format'
complete -c ffmpeg -s 'c' -d 'Codec name'
complete -c ffmpeg -d 'Set metadata information of outfile from infile'
complete -c ffmpeg -s 't' -d 'Record or transcode "duration" seconds of audio/video'
complete -c ffmpeg -d 'Record or transcode stop time'
complete -c ffmpeg -d 'Set the limit file size in bytes'
complete -c ffmpeg -d 'Set the start time offset'
complete -c ffmpeg -d 'Enable/disable seeking by timestamp with -ss'
complete -c ffmpeg -d 'Set the recording timestamp'
complete -c ffmpeg -d 'Add metadata'
complete -c ffmpeg -d 'Add program with specified streams'
complete -c ffmpeg -d 'Audio pad'
complete -c ffmpeg -d 'Set the number of frames to output'
complete -c ffmpeg -d 'Set stream filtergraph'
complete -c ffmpeg -d 'Read stream filtergraph description from a file'
complete -c ffmpeg -d 'Reinit filtergraph on input parameter changes'
complete -c ffmpeg -d 'Discard'
complete -c ffmpeg -d 'Disposition'
complete -c ffmpeg -d 'Set the number of video frames to output'
complete -c ffmpeg -s 'r' -d 'Set frame rate'
complete -c ffmpeg -s 's' -d 'Set frame size'
complete -c ffmpeg -d 'Set aspect ratio'
complete -c ffmpeg -d 'Set the number of bits per raw sample'
complete -c ffmpeg -d 'Disable video'
complete -c ffmpeg -d 'Set initial TimeCode value'
complete -c ffmpeg -d 'Select the pass number'
complete -c ffmpeg -d 'Set video filters'
complete -c ffmpeg -d 'Audio bitrate'
complete -c ffmpeg -s 'b' -d 'Video bitrate'
complete -c ffmpeg -d 'Disable data'
complete -c ffmpeg -d 'Set the number of audio frames to output'
complete -c ffmpeg -d 'Set audio quality'
complete -c ffmpeg -d 'Set audio sampling rate'
complete -c ffmpeg -d 'Set number of audio channels'
complete -c ffmpeg -d 'Disable audio'
complete -c ffmpeg -d 'Change audio volume'
complete -c ffmpeg -d 'Set audio filters'
complete -c ffmpeg -s 's' -d 'Set frame size'
complete -c ffmpeg -d 'Disable subtitle'
complete -c ffmpeg -d 'Force subtitle tag/fourcc'
complete -c ffmpeg -d 'Fix subtitles duration'
complete -c ffmpeg -d 'Set canvas size'
complete -c ffmpeg -d 'Set the subtitle options to the indicated preset'
complete -c ffmpeg -d 'Preset name'
