complete -c ffplay -s 'L' -d 'Show license'
complete -c ffplay -s 'h' -s '?' -l 'help' -d 'Show help'
complete -c ffplay -d 'Show version'
complete -c ffplay -d 'Show build configuration'
complete -c ffplay -d 'Show available formats'
complete -c ffplay -d 'Show available muxers'
complete -c ffplay -d 'Show available demuxers'
complete -c ffplay -d 'Show available devices'
complete -c ffplay -d 'Show available codecs'
complete -c ffplay -d 'Show available decoders'
complete -c ffplay -d 'Show available encoders'
complete -c ffplay -d 'Show available bit stream filters'
complete -c ffplay -d 'Show available protocols'
complete -c ffplay -d 'Show available filters'
complete -c ffplay -d 'Show available pixel formats'
complete -c ffplay -d 'Show standard channel layouts'
complete -c ffplay -d 'Show available audio sample formats'
complete -c ffplay -d 'Show available color names'
complete -c ffplay -s 'v' -d 'Set logging level'
complete -c ffplay -d 'Generate a report'
complete -c ffplay -d 'Set maximum size of a single allocated block'
complete -c ffplay -d 'List sources of the input device'
complete -c ffplay -d 'List sinks of the output device'
complete -c ffplay -s 'x' -d 'Force displayed width'
complete -c ffplay -s 'y' -d 'Force displayed height'
complete -c ffplay -s 's' -d 'Set frame size'
complete -c ffplay -d 'Force full screen'
complete -c ffplay -d 'Disable audio'
complete -c ffplay -d 'Disable video'
complete -c ffplay -d 'Disable subtitle'
complete -c ffplay -d 'Seek to a given position in seconds'
complete -c ffplay -s 't' -d 'Play duration seconds of audio/video'
complete -c ffplay -d 'Seek by bytes'
complete -c ffplay -d 'Disable graphical display'
complete -c ffplay -d 'Borderless window'
complete -c ffplay -d 'Set startup volume'
complete -c ffplay -s 'f' -d 'Force format'
complete -c ffplay -d 'Set window title'
complete -c ffplay -d 'Set audio filters'
complete -c ffplay -d 'Select show mode'
complete -c ffplay -s 'i' -d 'Read specified file'
complete -c ffplay -d 'Force decoder'
complete -c ffplay -d 'Automatically rotate video'
