complete -c ffprobe -s 'L' -d 'Show license'
complete -c ffprobe -s 'h' -s '?' -l 'help' -d 'Show help'
complete -c ffprobe -d 'Show version'
complete -c ffprobe -d 'Show build configuration'
complete -c ffprobe -d 'Show available formats'
complete -c ffprobe -d 'Show available muxers'
complete -c ffprobe -d 'Show available demuxers'
complete -c ffprobe -d 'Show available devices'
complete -c ffprobe -d 'Show available codecs'
complete -c ffprobe -d 'Show available decoders'
complete -c ffprobe -d 'Show available encoders'
complete -c ffprobe -d 'Show available bit stream filters'
complete -c ffprobe -d 'Show available protocols'
complete -c ffprobe -d 'Show available filters'
complete -c ffprobe -d 'Show available pixel formats'
complete -c ffprobe -d 'Show standard channel layouts'
complete -c ffprobe -d 'Show available audio sample formats'
complete -c ffprobe -d 'Show available color names'
complete -c ffprobe -s 'v' -d 'Set logging level'
complete -c ffprobe -d 'Generate a report'
complete -c ffprobe -d 'Set maximum size of a single allocated block'
complete -c ffprobe -d 'Force specific cpu flags'
complete -c ffprobe -d 'Do not show program banner'
complete -c ffprobe -d 'List sources of the input device'
complete -c ffprobe -d 'List sinks of the output device'
complete -c ffprobe -s 'f' -d 'Force format'
complete -c ffprobe -d 'Show unit of the displayed values'
complete -c ffprobe -d 'Use SI prefixes for the displayed values'
complete -c ffprobe -d 'Use binary prefixes for byte units'
complete -c ffprobe -d 'Use sexagesimal format HOURS:MM:SS.MICROSECONDS for time units'
complete -c ffprobe -d 'Prettify the format of displayed values, make it more human readable'
complete -c ffprobe -d 'Set the output printing format'
complete -c ffprobe -d 'Alias for -print_format'
complete -c ffprobe -d 'Select the specified streams'
complete -c ffprobe -d 'Print sections structure and section information, and exit'
complete -c ffprobe -d 'Show packets data'
complete -c ffprobe -d 'Show packets data hash'
complete -c ffprobe -d 'Show probing error'
complete -c ffprobe -d 'Show format/container info'
complete -c ffprobe -d 'Show frames info'
complete -c ffprobe -d 'Show a particular entry from the format/container info'
complete -c ffprobe -d 'Show a set of specified entries'
complete -c ffprobe -d 'Show log'
complete -c ffprobe -d 'Show packets info'
complete -c ffprobe -d 'Show programs info'
complete -c ffprobe -d 'Show streams info'
complete -c ffprobe -d 'Show chapters info'
complete -c ffprobe -d 'Count the number of frames per stream'
complete -c ffprobe -d 'Count the number of packets per stream'
complete -c ffprobe -d 'Show ffprobe version'
complete -c ffprobe -d 'Show library versions'
complete -c ffprobe -d 'Show program and library versions'
complete -c ffprobe -d 'Show pixel format descriptions'
complete -c ffprobe -d 'Show private data'
complete -c ffprobe -d 'Same as show_private_data'
complete -c ffprobe -d 'Force bitexact output'
complete -c ffprobe -d 'Set read intervals'
complete -c ffprobe -d 'Generic catch all option'
complete -c ffprobe -s 'i' -d 'Read specified file'
complete -c ffprobe -d 'Read and decode the streams to fill missing information with heuristics'
