complete -c find -s 'P' -d 'Never follow symlinks'
complete -c find -s 'L' -d 'Follow symlinks'
complete -c find -s 'H' -d 'Don'"'"'t follow symlinks (except for command line arguments)'
complete -c find -d 'Measure from the beginning of today rather than from 24 hours ago'
complete -c find -s 'd' -d 'Process subdirectories before the directory itself'
complete -c find -l 'help' -d 'Display help and exit'
complete -c find -d 'Do not print error messages for files that are deleted while running find'
complete -c find -d 'Maximum recursion depth'
complete -c find -d 'Do not apply any tests or actions at levels less than specified level'
complete -c find -d 'Don'"'"'t descend directories on other filesystems'
complete -c find -d 'Print error messages for files that are deleted while running find'
complete -c find -d 'Don'"'"'t assume directories contain 2 fewer subdirs than their hard link count'
complete -c find -d 'Specify regular expression type'
complete -c find -l 'version' -d 'Display version and exit'
complete -c find -d 'Turn warnings on'
complete -c find -d 'Turn warnings off'
complete -c find -d 'Equivalent to optimisation level 1.'
complete -c find -d 'Default optimisation level and corresponds to the traditional behaviour.'
complete -c find -d 'Any -type or -xtype tests are performed after any tests based only on the names of files.'
complete -c find -d 'The full cost-based query optimiser is enabled.'
complete -c find -s 'D' -d 'Print diagnostic information.'
complete -c find -d 'File last accessed specified number of minutes ago'
complete -c find -d 'File last accessed more recently than file was modified'
complete -c find -d 'File last accessed specified number of days ago'
complete -c find -d 'File status last changed specified number of minutes ago'
complete -c find -d 'File status last changed more recently than file was modified'
complete -c find -d 'File status last changed specified number of days ago'
complete -c find -d 'File is empty and is either a regular file or a directory'
complete -c find -d 'File is executable'
complete -c find -d 'Always false'
complete -c find -d 'File is on filesystem of specified type'
complete -c find -d 'Numeric group id of file'
complete -c find -d 'Group name of file'
complete -c find -d 'File is symlink matching specified case insensitive pattern'
complete -c find -d 'File name matches case insensitive pattern'
complete -c find -d 'File has specified inode number'
complete -c find -d 'File path matches case insensitive pattern'
complete -c find -d 'File name matches case insensitive regex'
complete -c find -d 'File has specified number of links'
complete -c find -d 'File is symlink matching specified pattern'
complete -c find -d 'File last modified specified number of minutes ago'
complete -c find -d 'File last modified more recently than file was modified'
complete -c find -d 'File last modified specified number of days ago'
complete -c find -d 'File name matches pattern'
complete -c find -d 'No user corresponds to file'"'"'s numeric user ID'
complete -c find -d 'No group corresponds to file'"'"'s numeric group ID'
complete -c find -d 'File path matches pattern'
complete -c find -d 'Files has specified permissions set'
complete -c find -d 'File name matches regex'
complete -c find -d 'File refers to the same inode as specified file'
complete -c find -d 'File uses specified units of space'
complete -c find -d 'Always true'
complete -c find -d 'File is of specified type'
complete -c find -d 'File'"'"'s owner has specified numeric user ID'
complete -c find -d 'File was last used X number of days after its status was last changed'
complete -c find -d 'File'"'"'s owner'
complete -c find -d 'Check type of file - in case of symlink, check the file that is not checked by -type'
complete -c find -d 'File'"'"'s security context matches specified pattern'
complete -c find -d 'Delete selected files'
complete -c find -d 'Execute specified command for each located file'
complete -c find -d 'Execute specified command for each located file, in the files directory'
complete -c find -d 'List file in ls -dils format, write to specified file'
complete -c find -d 'Print full file names into specified file'
complete -c find -d 'Print null separated full file names into specified file'
complete -c find -d 'Print formated data into specified file'
complete -c find -d 'Execute specified command for each located file after asking user'
complete -c find -d 'Print full file names'
complete -c find -d 'Execute a command for each located file, in its directory, after asking'
complete -c find -d 'Print null separated full file names'
complete -c find -d 'Print formated data'
complete -c find -d 'Do not recurse unless -depth is specified'
complete -c find -d 'Exit at once'
complete -c find -d 'List file in ls -dils format'
complete -c find -d 'Negate result of action'
complete -c find -s 'a' -d 'Result is only true if both previous and next action are true'
complete -c find -s 'o' -d 'Result is true if either previous or next action are true'
