complete -c firejail -l 'help' -d 'Show help and exit'
complete -c firejail -l 'version' -d 'Show version and exit'
complete -c firejail -l 'debug' -d 'Print debug info'
complete -c firejail -l 'debug-blacklists' -d 'Debug blacklisting'
complete -c firejail -l 'debug-whitelists' -d 'Debug whitelisting'
complete -c firejail -l 'debug-caps' -d 'Print known capabilities and exit'
complete -c firejail -l 'debug-errnos' -d 'Print known error numbers and exit'
complete -c firejail -l 'debug-private-lib' -d 'Debug --private-lib'
complete -c firejail -l 'debug-protocols' -d 'Print known protocols and exit'
complete -c firejail -l 'debug-syscalls' -d 'Print known syscalls and exit'
complete -c firejail -l 'debug-syscalls32' -d 'Print known 32-bit syscalls and exit'
complete -c firejail -l 'list' -d 'List all sandboxes'
complete -c firejail -l 'tree' -d 'Print a tree of all sandboxes'
complete -c firejail -l 'top' -d 'Monitor sandboxes (like `top`)'
complete -c firejail -l 'shutdown' -d 'Show help and exit'
complete -c firejail -l 'profiles' -d 'Load a custom security profile'
complete -c firejail -l 'join' -d 'Join existing sandbox'
complete -c firejail -l 'hosts-file' -d 'Show help and exit'
complete -c firejail -l 'chroot' -d 'Chroot into this directory'
complete -c firejail -l 'tmpfs' -d 'Mount tmpfs into sandbox'
complete -c firejail -l 'blacklist' -d 'Blacklist dir or file'
complete -c firejail -l 'noblacklist' -d 'Disable blacklist for dir or file'
complete -c firejail -l 'whitelist' -d 'Whitelist dir or file'
complete -c firejail -l 'nowhitelist' -d 'Disable whitelist for dir or file'
complete -c firejail -l 'read-only' -d 'Set dir or file read-only'
complete -c firejail -l 'read-write' -d 'Set dir or file read-write'
complete -c firejail -l 'bind' -d 'Bind-mount file on top of another'
complete -c firejail -l 'private' -d 'Mount temporary home directories and delete on exit'
complete -c firejail -l 'netfilter' -d 'Enable firewall given by this file'
complete -c firejail -l 'net' -d 'Enable network namespace connected to this interface'
