complete -c firewall-cmd -s 'h' -l 'help' -d 'Prints a short help text and exits'
complete -c firewall-cmd -s 'V' -l 'version' -d 'Print the version string of firewalld'
complete -c firewall-cmd -s 'q' -l 'quiet' -d 'Do not print status messages'
complete -c firewall-cmd -l 'state' -d 'Check whether the firewalld daemon is active'
complete -c firewall-cmd -l 'reload' -d 'Reload firewall rules and keep state information'
complete -c firewall-cmd -l 'complete-reload' -d 'Reload firewall completely, even netfilter kernel modules'
complete -c firewall-cmd -l 'runtime-to-permanent' -d 'Save active runtime configuration and overwrite permanent configuration'
complete -c firewall-cmd -l 'check-config' -d 'Run checks on the permanent configuration'
complete -c firewall-cmd -l 'get-log-denied' -d 'Print the log denied setting'
complete -c firewall-cmd -l 'set-log-denied' -d 'Add logging rules right before reject and drop rules'
complete -c firewall-cmd -l 'permanent' -d 'Set options permanently'
complete -c firewall-cmd -l 'get-default-zone' -d 'Print default zone for connections and interfaces'
complete -c firewall-cmd -l 'set-default-zone' -d 'Set default zone for connections and interfaces'
complete -c firewall-cmd -l 'get-active-zones' -d 'Print currently active zones altogether with interfaces and sources'
complete -c firewall-cmd -l 'get-zones' -d 'Print predefined zones'
complete -c firewall-cmd -l 'get-services' -d 'Print predefined services'
complete -c firewall-cmd -l 'get-icmptypes' -d 'Print predefined icmptypes'
complete -c firewall-cmd -l 'get-zone-of-interface' -d 'Print the name of the zone the interface is bound to'
complete -c firewall-cmd -l 'get-zone-of-source' -d 'Print the name of the zone the source is bound to'
complete -c firewall-cmd -l 'info-zone' -d 'Print information about the zone'
complete -c firewall-cmd -l 'list-all-zones' -d 'List everything added for or enabled in all zones'
complete -c firewall-cmd -l 'new-zone' -d 'Add a new permanent and empty zone'
complete -c firewall-cmd -l 'new-zone-from-file' -d 'Add a new permanent zone from a prepared zone file'
complete -c firewall-cmd -l 'delete-zone' -d 'Delete an existing permanent zone'
complete -c firewall-cmd -l 'load-zone-defaults' -d 'Load zone default settings'
complete -c firewall-cmd -l 'path-zone' -d 'Print path of the zone configuration file'
complete -c firewall-cmd -l 'get-policies' -d 'Print predefined policies'
complete -c firewall-cmd -l 'info-policy' -d 'Print information about the policy'
complete -c firewall-cmd -l 'list-all-policies' -d 'List everything added for or enabled in all policies'
complete -c firewall-cmd -l 'new-policy' -d 'Add a new permanent policy'
complete -c firewall-cmd -l 'new-policy-from-file' -d 'Add a new permanent policy from a prepared policy file'
complete -c firewall-cmd -l 'path-policy' -d 'Print path of the policy configuration file'
complete -c firewall-cmd -l 'delete-policy' -d 'Delete an existing permanent policy'
complete -c firewall-cmd -l 'load-policy-defaults' -d 'Load the shipped defaults for a policy'
complete -c firewall-cmd -l 'zone' -d 'Apply option to this zone'
complete -c firewall-cmd -l 'policy' -d 'Apply option to this policy'
complete -c firewall-cmd -l 'get-target' -d 'Get the target'
complete -c firewall-cmd -l 'set-target' -d 'Set the target'
complete -c firewall-cmd -l 'list-all' -d 'List everything added for or enabled'
complete -c firewall-cmd -l 'list-services' -d 'List services added'
complete -c firewall-cmd -l 'add-service' -d 'Add a service'
complete -c firewall-cmd -l 'remove-service' -d 'Remove a service'
complete -c firewall-cmd -l 'query-service' -d 'Return whether service has been added'
complete -c firewall-cmd -l 'list-ports' -d 'List ports added'
complete -c firewall-cmd -l 'list-protocols' -d 'List protocols added'
complete -c firewall-cmd -l 'list-source-ports' -d 'List source ports added'
complete -c firewall-cmd -l 'list-icmp-blocks' -d 'List ICMPs type blocks added'
complete -c firewall-cmd -l 'add-icmp-block' -d 'Add an ICMP block for icmptype'
complete -c firewall-cmd -l 'remove-icmp-block' -d 'Remove the ICMP block for icmptype'
complete -c firewall-cmd -l 'query-icmp-block' -d 'Return whether an ICMP block for icmptype has been added'
complete -c firewall-cmd -l 'list-forward-ports' -d 'List IPv4 forward ports added'
complete -c firewall-cmd -l 'add-forward-port' -d 'Add the IPv4 forward port'
complete -c firewall-cmd -l 'remove-forward-port' -d 'Remove the IPv4 forward port'
complete -c firewall-cmd -l 'query-forward-port' -d 'Return whether the IPv4 forward port has been added'
complete -c firewall-cmd -l 'add-masquerade' -d 'Enable IPv4 masquerade'
complete -c firewall-cmd -l 'remove-masquerade' -d 'Disable IPv4 masquerade'
complete -c firewall-cmd -l 'query-masquerade' -d 'Return whether IPv4 masquerading has been enabled'
complete -c firewall-cmd -l 'list-rich-rules' -d 'List rich language rules added'
complete -c firewall-cmd -l 'add-rich-rule' -d 'Add rich language rule'
complete -c firewall-cmd -l 'remove-rich-rule' -d 'Remove rich language rule'
complete -c firewall-cmd -l 'query-rich-rule' -d 'Return whether the rich language rule has been added'
complete -c firewall-cmd -l 'timeout' -d 'The rule will be active for the specified amount of time'
complete -c firewall-cmd -l 'add-icmp-block-inversion' -d 'Enable ICMP block inversion'
complete -c firewall-cmd -l 'remove-icmp-block-inversion' -d 'Disable ICMP block inversion'
complete -c firewall-cmd -l 'query-icmp-block-inversion' -d 'Return whether ICMP block inversion is enabled'
complete -c firewall-cmd -l 'add-forward' -d 'Enable intra zone forwarding'
complete -c firewall-cmd -l 'remove-forward' -d 'Disable intra zone forwarding'
complete -c firewall-cmd -l 'query-forward' -d 'Return whether intra zone forwarding is enabled'
complete -c firewall-cmd -l 'get-priority' -d 'Get the priority'
complete -c firewall-cmd -l 'set-priority' -d 'Set the priority'
complete -c firewall-cmd -l 'list-ingress-zones' -d 'List ingress zones added'
complete -c firewall-cmd -l 'add-ingress-zone' -d 'Add an ingress zone'
complete -c firewall-cmd -l 'remove-ingress-zone' -d 'Remove an ingress zone'
complete -c firewall-cmd -l 'query-ingress-zone' -d 'Return whether zone has been added'
complete -c firewall-cmd -l 'list-egress-zones' -d 'List egress zones added'
complete -c firewall-cmd -l 'add-egress-zone' -d 'Add an egress zone'
complete -c firewall-cmd -l 'remove-egress-zone' -d 'Remove an egress zone'
complete -c firewall-cmd -l 'query-egress-zone' -d 'Return whether zone has been added'
complete -c firewall-cmd -l 'list-interfaces' -d 'List interfaces that are bound to zone'
complete -c firewall-cmd -l 'add-interface' -d 'Bind interface to zone'
complete -c firewall-cmd -l 'change-interface' -d 'Change to which zone interface is bound'
complete -c firewall-cmd -l 'query-interface' -d 'Query whether interface is bound to zone'
complete -c firewall-cmd -l 'remove-interface' -d 'Remove binding of interface from zone'
complete -c firewall-cmd -l 'list-sources' -d 'List sources that are bound to zone'
complete -c firewall-cmd -l 'add-source' -d 'Bind the source to zone'
complete -c firewall-cmd -l 'change-source' -d 'Change zone the source is bound to'
complete -c firewall-cmd -l 'query-source' -d 'Query whether the source is bound to the zone'
complete -c firewall-cmd -l 'remove-source' -d 'Remove binding of the source from zone'
complete -c firewall-cmd -l 'get-ipset-types' -d 'Print the supported ipset types'
complete -c firewall-cmd -l 'new-ipset' -d 'Add a new permanent and empty ipset'
complete -c firewall-cmd -l 'type' -d 'Specify ipset type'
complete -c firewall-cmd -l 'option' -d 'Options for new ipset'
complete -c firewall-cmd -l 'new-ipset-from-file' -d 'Add a new permanent ipset from a prepared ipset file'
complete -c firewall-cmd -l 'delete-ipset' -d 'Delete an existing permanent ipset'
complete -c firewall-cmd -l 'load-ipset-defaults' -d 'Load ipset default settings'
complete -c firewall-cmd -l 'info-ipset' -d 'Print information about the ipset'
complete -c firewall-cmd -l 'get-ipsets' -d 'Print predefined ipsets'
complete -c firewall-cmd -l 'ipset' -d 'Apply settings to this ipset'
complete -c firewall-cmd -l 'add-entry' -d 'Add a new entry to the ipset'
complete -c firewall-cmd -l 'remove-entry' -d 'Remove an entry from the ipset'
complete -c firewall-cmd -l 'query-entry' -d 'Return whether the entry has been added to an ipset'
complete -c firewall-cmd -l 'get-entries' -d 'List all entries of the ipset'
complete -c firewall-cmd -l 'add-entries-from-file' -d 'Add new entries to the ipset from the file'
complete -c firewall-cmd -l 'remove-entries-from-file' -d 'Remove existing entries from the ipset from the file'
complete -c firewall-cmd -l 'path-ipset' -d 'Print path of the ipset configuration file'
complete -c firewall-cmd -l 'info-service' -d 'Print information about the service'
complete -c firewall-cmd -l 'new-service' -d 'Add a new permanent and empty service'
complete -c firewall-cmd -l 'new-service-from-file' -d 'Add a new permanent service from a prepared service file'
complete -c firewall-cmd -l 'delete-service' -d 'Delete an existing permanent service'
complete -c firewall-cmd -l 'load-service-defaults' -d 'Load service default settings'
complete -c firewall-cmd -l 'path-service' -d 'Print path of the service configuration file'
complete -c firewall-cmd -l 'service' -d 'Apply settings to this service'
complete -c firewall-cmd -l 'get-protocols' -d 'List protocols added to the permanent service'
complete -c firewall-cmd -l 'get-source-ports' -d 'List source ports added to the permanent service'
complete -c firewall-cmd -l 'add-helper' -d 'Add a new helper to the permanent service'
complete -c firewall-cmd -l 'remove-helper' -d 'Remove a helper from the permanent service'
complete -c firewall-cmd -l 'query-helper' -d 'Return wether the helper has been added to the permanent service'
complete -c firewall-cmd -l 'get-service-helpers' -d 'List helpers added to the permanent service'
complete -c firewall-cmd -l 'set-destination' -d 'Set destination for ipv to address[/mask] in the permanent service'
complete -c firewall-cmd -l 'add-include' -d 'Add a new include to the permanent service'
complete -c firewall-cmd -l 'remove-include' -d 'Remove a include from the permanent service'
complete -c firewall-cmd -l 'query-include' -d 'Return wether the include has been added to the permanent service'
complete -c firewall-cmd -l 'get-includes' -d 'List includes added to the permanent service'
complete -c firewall-cmd -l 'info-helper' -d 'Print information about the helper'
complete -c firewall-cmd -l 'new-helper' -d 'Add a new permanent helper'
complete -c firewall-cmd -l 'module' -d 'Specify module for new helper'
complete -c firewall-cmd -l 'new-helper-from-file' -d 'Add a new permanent helper from a prepared helper file'
complete -c firewall-cmd -l 'delete-helper' -d 'Delete an existing permanent helper'
complete -c firewall-cmd -l 'load-helper-defaults' -d 'Load helper default settings'
complete -c firewall-cmd -l 'path-helper' -d 'Print path of the helper configuration file'
complete -c firewall-cmd -l 'get-helpers' -d 'Print predefined helpers as a space separated list'
complete -c firewall-cmd -l 'helper' -d 'Apply settings to this helper'
complete -c firewall-cmd -l 'set-module' -d 'Set module description for helper'
complete -c firewall-cmd -l 'get-module' -d 'Print module description for helper'
complete -c firewall-cmd -l 'set-family' -d 'Set family description for helper'
complete -c firewall-cmd -l 'get-family' -d 'Print family description of helper'
complete -c firewall-cmd -l 'info-icmptype' -d 'Print information about the icmptype'
complete -c firewall-cmd -l 'new-icmptype' -d 'Add a new permanent and empty icmptype'
complete -c firewall-cmd -l 'new-icmptype-from-file' -d 'Add a new permanent icmptype from a prepared icmptype file'
complete -c firewall-cmd -l 'delete-icmptype' -d 'Delete an existing permanent icmptype'
complete -c firewall-cmd -l 'load-icmptype-defaults' -d 'Load icmptype default settings'
complete -c firewall-cmd -l 'icmptype' -d 'Apply settings to this icmptype'
complete -c firewall-cmd -l 'add-destination' -d 'Enable destination for ipv in permanent icmptype'
complete -c firewall-cmd -l 'path-icmptype' -d 'Print path of the icmptype configuration file'
complete -c firewall-cmd -l 'direct' -d 'Give a more direct access to the firewall'
complete -c firewall-cmd -l 'get-all-chains' -d 'Get all chains added to all tables'
complete -c firewall-cmd -l 'get-chains' -d 'Get all chains added to table'
complete -c firewall-cmd -l 'add-chain' -d 'Add a new chain to table'
complete -c firewall-cmd -l 'remove-chain' -d 'Remove chain from table'
complete -c firewall-cmd -l 'query-chain' -d 'Return whether the chain with given name exists in table'
complete -c firewall-cmd -l 'get-all-rules' -d 'Get all rules added to all chains in all tables'
complete -c firewall-cmd -l 'get-rules' -d 'Get all rules added to chain in table'
complete -c firewall-cmd -l 'add-rule' -d 'Add a rule to chain in table'
complete -c firewall-cmd -l 'remove-rule' -d 'Remove a rule from chain in table'
complete -c firewall-cmd -l 'remove-rules' -d 'Remove all rules in the chain in table'
complete -c firewall-cmd -l 'query-rule' -d 'Return whether the rule exists in chain in table'
complete -c firewall-cmd -l 'passthrough' -d 'Pass a command through to the firewall'
complete -c firewall-cmd -l 'get-all-passthroughs' -d 'Get all passthrough rules'
complete -c firewall-cmd -l 'get-passthroughs' -d 'Get all passthrough rules for the ipv value'
complete -c firewall-cmd -l 'add-passthrough' -d 'Add a passthrough rule'
complete -c firewall-cmd -l 'remove-passthrough' -d 'Remove a passthrough rule'
complete -c firewall-cmd -l 'query-passthrough' -d 'Return whether the passthrough rule exists'
complete -c firewall-cmd -l 'lockdown-on' -d 'Enable lockdown'
complete -c firewall-cmd -l 'lockdown-off' -d 'Disable lockdown'
complete -c firewall-cmd -l 'query-lockdown' -d 'Query whether lockdown is enabled'
complete -c firewall-cmd -l 'list-lockdown-whitelist-commands' -d 'List all command lines that are on the whitelist'
complete -c firewall-cmd -l 'add-lockdown-whitelist-command' -d 'Add the command to the whitelist'
complete -c firewall-cmd -l 'remove-lockdown-whitelist-command' -d 'Remove the command from the whitelist'
complete -c firewall-cmd -l 'query-lockdown-whitelist-command' -d 'Query whether the command is on the whitelist'
complete -c firewall-cmd -l 'list-lockdown-whitelist-contexts' -d 'List all contexts that are on the whitelist'
complete -c firewall-cmd -l 'add-lockdown-whitelist-context' -d 'Add the context to the whitelist'
complete -c firewall-cmd -l 'remove-lockdown-whitelist-context' -d 'Remove the context from the whitelist'
complete -c firewall-cmd -l 'query-lockdown-whitelist-context' -d 'Query whether the context is on the whitelist'
complete -c firewall-cmd -l 'list-lockdown-whitelist-uids' -d 'List all user ids that are on the whitelist'
complete -c firewall-cmd -l 'add-lockdown-whitelist-uid' -d 'Add the user id to the whitelist'
complete -c firewall-cmd -l 'remove-lockdown-whitelist-uid' -d 'Remove the user id from the whitelist'
complete -c firewall-cmd -l 'query-lockdown-whitelist-uid' -d 'Query whether the user id is on the whitelist'
complete -c firewall-cmd -l 'list-lockdown-whitelist-users' -d 'List all user names that are on the whitelist'
complete -c firewall-cmd -l 'add-lockdown-whitelist-user' -d 'Add the user to the whitelist'
complete -c firewall-cmd -l 'remove-lockdown-whitelist-user' -d 'Remove the user from the whitelist'
complete -c firewall-cmd -l 'query-lockdown-whitelist-user' -d 'Query whether the user is on the whitelist'
complete -c firewall-cmd -l 'panic-on' -d 'Enable panic mode'
complete -c firewall-cmd -l 'panic-off' -d 'Disable panic mode'
complete -c firewall-cmd -l 'query-panic' -d 'Returns 0 if panic mode is enabled, 1 otherwise'
complete -c firewall-cmd -l 'set-description' -d 'Set new description for zone|policy|ipset|service|helper|icmptype'
complete -c firewall-cmd -l 'get-description' -d 'Print description of zone|policy|ipset|service|helper|icmptype'
complete -c firewall-cmd -l 'set-short' -d 'Set short description for zone|policy|ipset|service|helper|icmptype'
complete -c firewall-cmd -l 'get-short' -d 'Print short description of zone|policy|ipset|service|helper|icmptype'
complete -c firewall-cmd -l 'name' -d 'Name for new zone|policy|ipset|service|helper|icmptype'
complete -c firewall-cmd -l 'add-port' -d 'Add the port to zone|policy|service|helper'
complete -c firewall-cmd -l 'remove-port' -d 'Remove the port from zone|policy|service|helper'
complete -c firewall-cmd -l 'query-port' -d 'Return whether the port has been added for zone|policy|service|helper'
complete -c firewall-cmd -l 'add-protocol' -d 'Add the protocol to zone|policy|service'
complete -c firewall-cmd -l 'remove-protocol' -d 'Remove the protocol from zone|policy|service'
complete -c firewall-cmd -l 'query-protocol' -d 'Return whether the protocol has been added to zone|policy|service'
complete -c firewall-cmd -l 'add-source-port' -d 'Add the source port to zone|policy|service'
complete -c firewall-cmd -l 'remove-source-port' -d 'Remove the source port from zone|policy|service'
complete -c firewall-cmd -l 'query-source-port' -d 'Return whether the source port has been added for zone|policy|service'
complete -c firewall-cmd -l 'get-ports' -d 'List ports added to the permanent service|helper'
complete -c firewall-cmd -l 'remove-destination' -d 'Disable destination for ipv in permanent service|icmptype'
complete -c firewall-cmd -l 'query-destination' -d 'Return whether destination for ipv is enabled in permanent service|icmptype'
complete -c firewall-cmd -l 'get-destinations' -d 'List destinations in permanent service|icmptype'
complete -c firewall-cmd -l 'family' -d 'Inet family'
