complete -c fish -s 'c' -l 'command' -d 'Run specified command instead of interactive session'
complete -c fish -s 'C' -l 'init-command' -d 'Run specified command before session'
complete -c fish -s 'h' -l 'help' -d 'Display help and exit'
complete -c fish -s 'v' -l 'version' -d 'Display version and exit'
complete -c fish -s 'N' -l 'no-config' -d 'Do not read configuration files'
complete -c fish -s 'n' -l 'no-execute' -d 'Only parse input, do not execute'
complete -c fish -s 'i' -l 'interactive' -d 'Run in interactive mode'
complete -c fish -s 'l' -l 'login' -d 'Run as a login shell'
complete -c fish -s 'p' -l 'profile' -d 'Output profiling information (excluding startup) to a file'
complete -c fish -l 'profile-startup' -d 'Output startup profiling information to a file'
complete -c fish -s 'd' -l 'debug' -d 'Specify debug categories'
complete -c fish -s 'o' -l 'debug-output' -d 'Where to direct debug output to'
complete -c fish -s 'P' -l 'private' -d 'Do not persist history'
complete -c fish -s 'f' -l 'features' -d 'Run with comma-separated feature flags enabled'
complete -c fish -l 'print-rusage-self' -d 'Print stats from getrusage at exit'
complete -c fish -l 'print-debug-categories' -d 'Print the debug categories fish knows'
