complete -c fortune -s 'a' -d 'Include offensive fortunes'
complete -c fortune -s 'e' -d 'Equal category weighting'
complete -c fortune -s 'f' -d 'Print fortune categories'
complete -c fortune -s 'i' -d 'Ignore case for regex patterns'
complete -c fortune -s 'l' -d 'Long fortunes only'
complete -c fortune -s 'm' -d 'Print all fortunes that match regex pattern'
complete -c fortune -s 'n' -d 'Set short/long fortune threshold'
complete -c fortune -s 'o' -d 'Offensive fortunes only'
complete -c fortune -s 's' -d 'Short fortunes only'
complete -c fortune -s 'w' -d 'Add a wait time for reading'
