complete -c fossil -d 'Add files to checkout'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -l 'dotfiles' -d 'Include dotfiles'
complete -c fossil -l 'ignore' -d 'Files to ignore'
complete -c fossil -l 'clean' -d 'Files to ignore'
complete -c fossil -d 'File'
complete -c fossil -d 'Remove and add files to checkout'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -l 'dotfiles' -d 'Include dotfiles'
complete -c fossil -l 'ignore' -d 'Files to ignore'
complete -c fossil -l 'clean' -d 'Files to ignore'
complete -c fossil -s 'n' -l 'dry-run' -d 'Display actions without running'
complete -c fossil -d 'Check all repositories'
complete -c fossil -d 'List changes'
complete -c fossil -d 'Ignore repository'
complete -c fossil -d 'Ignore repository'
complete -c fossil -d 'Display locations'
complete -c fossil -d 'Pull repositories'
complete -c fossil -d 'Push repositories'
complete -c fossil -d 'Rebuild repositories'
complete -c fossil -d 'Sync repositories'
complete -c fossil -d 'Shows file modifications'
complete -c fossil -l 'filevers' -d 'Show file versions'
complete -c fossil -s 'l' -l 'log' -d 'List all analyzed versions'
complete -c fossil -s 'n' -l 'limit' -d 'Limit analyzed versions'
complete -c fossil -d 'Find regressions'
complete -c fossil -d 'Identify version as not working'
complete -c fossil -d 'Identify version as working'
complete -c fossil -d 'Show log of bisects in test order'
complete -c fossil -d 'Show log of bisects in check-in order'
complete -c fossil -d 'Skip version'
complete -c fossil -d 'Show bisect options'
complete -c fossil -d 'Automatically run bisect next'
complete -c fossil -d 'Follow only primary parent-child links'
complete -c fossil -d 'Command to show after bisect next'
complete -c fossil -d 'Automatically run bisect next'
complete -c fossil -d 'Follow only primary parent-child links'
complete -c fossil -d 'Show log of bisects in check-in order'
complete -c fossil -d 'Show log of bisects in test order'
complete -c fossil -d 'List versions between bad and good'
complete -c fossil -d 'Reinitialize bisect'
complete -c fossil -d 'List versions between bad and good'
complete -c fossil -s 'a' -l 'all' -d 'Show all versions'
complete -c fossil -s 'a' -l 'all' -d 'Show all versions'
complete -c fossil -s 'a' -l 'all' -d 'Show all versions'
complete -c fossil -d 'Undo latest bad/good command.'
complete -c fossil -d 'Create a new branch'
complete -c fossil -d 'Create new branch'
complete -c fossil -l 'private' -d 'Make branch local'
complete -c fossil -l 'bgcolor' -d 'Set background color'
complete -c fossil -l 'date-override' -d 'Override date'
complete -c fossil -l 'user-override' -d 'Override user'
complete -c fossil -d 'List branches'
complete -c fossil -s 'a' -l 'all' -d 'Show all branches'
complete -c fossil -s 'a' -l 'all' -d 'Show all branches'
complete -c fossil -s 'c' -l 'closed' -d 'Show closed branches'
complete -c fossil -s 'c' -l 'closed' -d 'Show closed branches'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -d 'Print a file'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -s 'r' -d 'Print specific revision'
complete -c fossil -d 'List local changes'
complete -c fossil -l 'abs-paths' -d 'Display absolute paths'
complete -c fossil -l 'rel-paths' -d 'Display relative paths'
complete -c fossil -l 'sha1sum' -d 'Verify file status using SHA1'
complete -c fossil -l 'header' -d 'Identify the repository if there are changes'
complete -c fossil -s 'v' -l 'verbose' -d 'Say (none) if there are no changes'
complete -c fossil -d 'Checkout version'
complete -c fossil -d 'Version to check out'
complete -c fossil -l 'force' -d 'Ignore edited files'
complete -c fossil -l 'force-missing' -d 'Ignore missing content'
complete -c fossil -l 'keep' -d 'Only update the manifest'
complete -c fossil -l 'latest' -d 'Update to latest version'
complete -c fossil -d 'Delete all extra files'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -l 'dotfiles' -d 'Include dotfiles'
complete -c fossil -l 'ignore' -d 'Files to ignore'
complete -c fossil -l 'clean' -d 'Files to clean without prompting'
complete -c fossil -s 'f' -l 'force' -d 'Remove without prompting'
complete -c fossil -s 'n' -l 'dry-run' -d 'Display actions without running'
complete -c fossil -l 'temp' -d 'Only remove Fossil temporary files'
complete -c fossil -s 'v' -l 'verbose' -d 'Show removed files'
complete -c fossil -d 'Clone repository'
complete -c fossil -s 'A' -l 'admin-user' -d 'Make username an administrator'
complete -c fossil -l 'private' -d 'Clone private branches'
complete -c fossil -l 'ssl-identity' -d 'Use SSL identity'
complete -c fossil -d 'Create new revision'
complete -c fossil -d 'File'
complete -c fossil -l 'allow-conflict' -d 'Allow unresolved merge conflicts'
complete -c fossil -l 'allow-empty' -d 'Allow empty check-ins'
complete -c fossil -l 'allow-fork' -d 'Allow forking'
complete -c fossil -l 'allow-older' -d 'Allow commit older than ancestor'
complete -c fossil -l 'baseline' -d 'Use a baseline manifest'
complete -c fossil -l 'bgcolor' -d 'Apply color to check-in'
complete -c fossil -l 'branch' -d 'Check-in to new branch'
complete -c fossil -l 'branchcolor' -d 'Apply color to branch'
complete -c fossil -l 'close' -d 'Close the branch'
complete -c fossil -l 'delta' -d 'Use a delta manifest'
complete -c fossil -s 'm' -l 'comment' -d 'Commit comment'
complete -c fossil -s 'M' -l 'message-file' -d 'Read commit comment from a file'
complete -c fossil -l 'mimetype' -d 'Mimetype of commit comment'
complete -c fossil -s 'n' -l 'dry-run' -d 'Display actions without running'
complete -c fossil -l 'no-warnings' -d 'Omit all warnings'
complete -c fossil -l 'tag' -d 'Assign a tag to the checkin'
complete -c fossil -d 'Show differences'
complete -c fossil -l 'binary' -d 'Binary files glob pattern'
complete -c fossil -l 'branch' -d 'Show diff of branch'
complete -c fossil -l 'brief' -d 'Show file names only'
complete -c fossil -s 'c' -l 'context' -d 'Context lines'
complete -c fossil -l 'diff-binary' -d 'Include binary files'
complete -c fossil -s 'r' -l 'from' -d 'Select revision to compare with'
complete -c fossil -s 'i' -l 'internal' -d 'Use internal diff logic'
complete -c fossil -s 'y' -l 'side-by-side' -d 'Side-by-side diff'
complete -c fossil -l 'tk' -d 'Launch GUI'
complete -c fossil -l 'to' -d 'Select revision to compare to'
complete -c fossil -l 'unified' -d 'Unified diff'
complete -c fossil -s 'v' -l 'verbose' -d 'Output complete text'
complete -c fossil -s 'W' -l 'width' -d 'Line width in side-by-side diff'
complete -c fossil -d 'Export repository to git'
complete -c fossil -l 'export-marks' -d 'Export rids of exported data to file'
complete -c fossil -l 'import-marks' -d 'Read rids of data to ignore from file'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -l 'abs-paths' -d 'Display absolute paths'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -l 'dotfiles' -d 'Include dotfiles'
complete -c fossil -l 'ignore' -d 'Files to ignore'
complete -c fossil -l 'rel-paths' -d 'Display relative paths'
complete -c fossil -d 'Print complete file history'
complete -c fossil -s 'b' -l 'brief' -d 'Display one-line summary'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -s 'l' -l 'log' -d 'Select log mode (default)'
complete -c fossil -s 'n' -l 'limit' -d 'Limit analyzed versions'
complete -c fossil -l 'offset' -d 'Skip changes'
complete -c fossil -s 'p' -l 'print' -d 'Select print mode'
complete -c fossil -s 'r' -l 'revision' -d 'Print specific revision'
complete -c fossil -s 's' -l 'status' -d 'Select status mode'
complete -c fossil -d 'Display help'
complete -c fossil -s 'a' -l 'all' -d 'Show main and auxiliary commands'
complete -c fossil -s 't' -l 'test' -d 'Show test commands only'
complete -c fossil -s 'x' -l 'aux' -d 'Show auxiliary commands only'
complete -c fossil -s 'w' -l 'www' -d 'Show list of web UI pages'
complete -c fossil -d 'Import repository from git'
complete -c fossil -l 'incremental' -d 'Allow importing into existing repository'
complete -c fossil -d 'Provide information about object'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -s 'v' -l 'verbose' -d 'Show extra information'
complete -c fossil -d 'Create a repository'
complete -c fossil -l 'template' -d 'Copy settings from repository'
complete -c fossil -s 'A' -l 'admin-user' -d 'Make username an administrator'
complete -c fossil -l 'date-override' -d 'Override date'
complete -c fossil -d 'Make JSON request'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -d 'List files'
complete -c fossil -s 'r' -d 'Tag'
complete -c fossil -l 'age' -d 'Show commit time'
complete -c fossil -s 'v' -l 'verbose' -d 'Provide extra information'
complete -c fossil -d 'Merge commits'
complete -c fossil -d 'Tag'
complete -c fossil -l 'baseline' -d 'Use baseline'
complete -c fossil -l 'binary' -d 'Binary files glob pattern'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -s 'f' -l 'force' -d 'Allow empty merge'
complete -c fossil -l 'integrate' -d 'Close merged branch'
complete -c fossil -s 'n' -l 'dry-run' -d 'Display actions without running'
complete -c fossil -s 'v' -l 'verbose' -d 'Show extra information'
complete -c fossil -d 'Move file'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -d 'Open repository'
complete -c fossil -l 'keep' -d 'Only modify manifest'
complete -c fossil -l 'nested' -d 'Allow opening inside an opened repository'
complete -c fossil -d 'Pull from a repository'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -l 'private' -d 'Pull private branches'
complete -c fossil -d 'Push into a repository'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -l 'private' -d 'Pull private branches'
complete -c fossil -d 'Rebuild a repository'
complete -c fossil -l 'cluster' -d 'Compute clusters'
complete -c fossil -l 'compress' -d 'Compress database'
complete -c fossil -l 'force' -d 'Force rebuild even with errors'
complete -c fossil -l 'noverify' -d 'Skip BLOB table verification'
complete -c fossil -l 'pagesize' -d 'Set the database pagesize'
complete -c fossil -l 'randomize' -d 'Scan in random order'
complete -c fossil -l 'vacuum' -d 'Run VACUUM'
complete -c fossil -l 'deanalyze' -d 'Remove ANALYZE tables'
complete -c fossil -l 'analyze' -d 'Run ANALYZE'
complete -c fossil -l 'wal' -d 'Set Write-Ahead-Log journalling'
complete -c fossil -l 'stats' -d 'Show statistics'
complete -c fossil -d 'Default server URL'
complete -c fossil -d 'Revert a commit'
complete -c fossil -d 'Tag'
complete -c fossil -s 'r' -d 'Revert back to given revision'
complete -c fossil -d 'Remove a file from repository'
complete -c fossil -l 'hard' -d 'Remove files from this checkout'
complete -c fossil -l 'soft' -d 'Skip removing files from this checkout'
complete -c fossil -s 'n' -l 'dry-run' -d 'Display actions without runing'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -d 'Manage settings'
complete -c fossil -d 'Log accesses'
complete -c fossil -d 'Allow symbolic links'
complete -c fossil -d 'Allow automatically filling CAPTCHA'
complete -c fossil -d 'Use JavaScript to enable hyperlinks'
complete -c fossil -d 'Pull list of shunned references from server'
complete -c fossil -d 'Automatically sync the repository'
complete -c fossil -d 'Binary files glob pattern'
complete -c fossil -d 'Case insensitive file matching'
complete -c fossil -d 'Files to clean without prompting'
complete -c fossil -d 'Sign commits using GPG'
complete -c fossil -d 'Non-standard line endings allowed glob pattern'
complete -c fossil -d 'Permissions given to new users'
complete -c fossil -d 'Allow binary files to be diffed'
complete -c fossil -d 'External diff command'
complete -c fossil -d 'Disallow pushing to the repository'
complete -c fossil -d 'Text editor for writing check-in comments'
complete -c fossil -d 'List of empty directories'
complete -c fossil -d 'Non-UTF-8 files glob pattern'
complete -c fossil -d 'Command to use for graphical diff'
complete -c fossil -d 'Command to use for graphical merge'
complete -c fossil -d 'HTTP port for fossil ui'
complete -c fossil -d 'Send login credentials using HTTPS'
complete -c fossil -d 'Files to ignore glob pattern'
complete -c fossil -d 'Files to keep when cleaning'
complete -c fossil -d 'Require authentication for localhost logins'
complete -c fossil -d 'Primary branch'
complete -c fossil -d 'Automatically create manifest files'
complete -c fossil -d 'HTTP request size limit'
complete -c fossil -d 'Use modification times'
complete -c fossil -d 'PGP command'
complete -c fossil -d 'HTTP proxy URL'
complete -c fossil -d 'Report relative paths'
complete -c fossil -d 'Compute checksums over all files'
complete -c fossil -d 'Allow users to register themselves'
complete -c fossil -d 'Command to use for SSH protocol'
complete -c fossil -d 'Location of SSL CA root certificates'
complete -c fossil -d 'SSL private certificate path'
complete -c fossil -d 'Allow Tcl scripting'
complete -c fossil -d 'Tcl initialization script'
complete -c fossil -d 'TH1 initialization script'
complete -c fossil -d 'Web browser name'
complete -c fossil -l 'global' -d 'Set globally'
complete -c fossil -d 'Run SQL commands'
complete -c fossil -d 'Manage stashes'
complete -c fossil -d 'Save current changes'
complete -c fossil -s 'm' -l 'comment' -d 'Stash comment'
complete -c fossil -s 'm' -l 'comment' -d 'Stash comment'
complete -c fossil -d 'List all stashes'
complete -c fossil -s 'v' -l 'verbose' -d 'Show information about files'
complete -c fossil -s 'v' -l 'verbose' -d 'Show information about files'
complete -c fossil -d 'Show stash contents'
complete -c fossil -d 'Pop last stash'
complete -c fossil -d 'Apply stash'
complete -c fossil -d 'Updates to stash state'
complete -c fossil -d 'Forget about stash'
complete -c fossil -s 'a' -l 'all' -d 'Forget ALL stashes'
complete -c fossil -s 'a' -l 'all' -d 'Forget ALL stashes'
complete -c fossil -d 'Compare stash'
complete -c fossil -d 'Show status'
complete -c fossil -l 'abs-paths' -d 'Display absolute paths'
complete -c fossil -l 'rel-paths' -d 'Display relative paths'
complete -c fossil -l 'sha1sum' -d 'Verify file status using SHA1'
complete -c fossil -d 'Sync with a repository'
complete -c fossil -s 'R' -l 'repository' -d 'Run command on repository'
complete -c fossil -l 'private' -d 'Sync private branches'
complete -c fossil -d 'Manage tags'
complete -c fossil -d 'Add tag to check-in'
complete -c fossil -l 'raw' -d 'Add raw tag'
complete -c fossil -l 'propagate' -d 'Propagate tag'
complete -c fossil -d 'Remove tag from check-in'
complete -c fossil -d 'Tag'
complete -c fossil -l 'raw' -d 'Remove raw tag'
complete -c fossil -d 'Find tag'
complete -c fossil -l 'raw' -d 'Find raw tag'
complete -c fossil -s 't' -l 'type' -d 'Find tag type'
complete -c fossil -s 'n' -l 'limit' -d 'Limit number of tags'
complete -c fossil -d 'Tag'
complete -c fossil -d 'List tags'
complete -c fossil -l 'raw' -d 'List raw tags'
complete -c fossil -d 'Show timeline'
complete -c fossil -s 'n' -l 'limit' -d 'Limit timeline entries'
complete -c fossil -s 't' -l 'type' -d 'Output only event type'
complete -c fossil -s 'v' -l 'verbose' -d 'Output list of files changed'
complete -c fossil -d 'Open web UI'
complete -c fossil -d 'Start web server'
complete -c fossil -l 'localauth' -d 'Enable automatic login for localhost'
complete -c fossil -l 'localhost' -d 'Only listen on localhost'
complete -c fossil -s 'P' -l 'port' -d 'Port to listen on'
complete -c fossil -l 'th-trace' -d 'Trace TH1 execution'
complete -c fossil -l 'baseurl' -d 'Use base URL'
complete -c fossil -l 'notfound' -d 'Redirect'
complete -c fossil -l 'files' -d 'Static files glob'
complete -c fossil -l 'scgi' -d 'Use SCGI rather than HTTP'
complete -c fossil -d 'Undo the changes'
complete -c fossil -s 'n' -l 'dry-run' -d 'Display actions without running'
complete -c fossil -d 'Update version'
complete -c fossil -l 'case-sensitive' -d 'Case insensitive file matching'
complete -c fossil -l 'debug' -d 'Print debug information'
complete -c fossil -l 'latest' -d 'Update to latest version'
complete -c fossil -s 'n' -l 'dry-run' -d 'Display actions without running'
complete -c fossil -s 'v' -l 'verbose' -d 'Print information about all files'
complete -c fossil -d 'Print fossil version'
complete -c fossil -s 'v' -l 'verbose' -d 'Print version of optional features'
complete -c fossil -l 'help' -d 'Print help'
