complete -c function -s 'd' -l 'description' -d 'Set function description'
complete -c function -d 'Function'
complete -c function -d 'Builtin'
complete -c function -s 'j' -l 'on-job-exit' -d 'Make the function a job exit event handler'
complete -c function -s 'p' -l 'on-process-exit' -d 'Make the function a process exit event handler'
complete -c function -s 's' -l 'on-signal' -d 'Make the function a signal event handler'
complete -c function -s 'v' -l 'on-variable' -d 'Make the function a variable update event handler'
complete -c function -s 'e' -l 'on-event' -d 'Make the function a generic event handler'
complete -c function -s 'a' -l 'argument-names' -d 'Specify named arguments'
complete -c function -s 'S' -l 'no-scope-shadowing' -d 'Do not shadow variable scope of calling function'
complete -c function -s 'w' -l 'wraps' -d 'Inherit completions from the given command'
complete -c function -s 'V' -l 'inherit-variable' -d 'Snapshot and define local variable'
