complete -c fzf -l 'no-extended' -d 'no-extended'
complete -c fzf -d 'no-extended'
complete -c fzf -s 'e' -l 'exact' -d 'Enable exact-match'
complete -c fzf -d 'case-sensitive match'
complete -c fzf -s 'i' -d 'Case-insensitive match'
complete -c fzf -l 'literal' -d 'Do not normalize latin script letters for matching'
complete -c fzf -l 'algo' -d 'Fuzzy matching algorithm'
complete -c fzf -s 'n' -l 'nth' -d 'Limit search scope using field index expressions'
complete -c fzf -l 'with-nth' -d 'Transform each line using field index expressions'
complete -c fzf -s 'd' -l 'delimiter' -d 'Field delimiter regex for --nth and --with-nth'
complete -c fzf -l 'no-sort' -d 'Do not sort the result'
complete -c fzf -d 'Do not sort the result'
complete -c fzf -l 'tac' -d 'Reverse the order of the input'
complete -c fzf -l 'disabled' -d 'Do not perform search'
complete -c fzf -l 'tiebreak' -d 'Sort criteria when breaking ties'
complete -c fzf -s 'm' -l 'multi' -d 'Enable multi-select with tab/shift-tab'
complete -c fzf -l 'no-multi' -d 'Disable multi-select'
complete -c fzf -d 'Disable multi-select'
complete -c fzf -l 'no-mouse' -d 'Disable mouse'
complete -c fzf -l 'bind' -d 'Custom key bindings'
complete -c fzf -l 'cycle' -d 'Enable cyclic scroll'
complete -c fzf -l 'keep-right' -d 'Keep the right end of the line visible on overflow'
complete -c fzf -l 'no-hscroll' -d 'Disable horizontal scroll'
complete -c fzf -l 'hscroll-off' -d 'Number of columns to keep right of highlighted substring'
complete -c fzf -l 'filepath-word' -d 'Make word-wise movements respect path separators'
complete -c fzf -l 'jump-labels' -d 'Label characters for jump and jump-accept'
complete -c fzf -l 'height' -d 'Display fzf window with the given height'
complete -c fzf -l 'min-height' -d 'Minimum height when --height is given in percent'
complete -c fzf -l 'layout' -d 'Choose the layout'
complete -c fzf -l 'reverse' -d 'A synonym for --layout=reverse'
complete -c fzf -l 'border' -d 'Draw border around the finder'
complete -c fzf -l 'no-unicode' -d 'Draw border with ASCII characters'
complete -c fzf -l 'margin' -d 'Expression for margins around the finder'
complete -c fzf -l 'info' -d 'Finder info style'
complete -c fzf -l 'inline-info' -d 'Display finder info inline with the query'
complete -c fzf -l 'prompt' -d 'Input prompt'
complete -c fzf -l 'pointer' -d 'Pointer to the current line'
complete -c fzf -l 'marker' -d 'Multi-select marker'
complete -c fzf -l 'header' -d 'String to print as header'
complete -c fzf -l 'header-lines' -d 'Treat the first N lines of input as header'
complete -c fzf -l 'ansi' -d 'Enable processing of ANSI color codes'
complete -c fzf -l 'tabstop' -d 'Number of spaces for a tab character'
complete -c fzf -l 'color' -d 'Color configuration'
complete -c fzf -l 'no-bold' -d 'Do not use bold text'
complete -c fzf -l 'black' -d 'Use black background'
complete -c fzf -l 'history' -d 'History file'
complete -c fzf -l 'history-size' -d 'Maximum number of history entries'
complete -c fzf -l 'preview' -d 'Command to preview highlighted line'
complete -c fzf -l 'preview-window' -d 'Preview window layout'
complete -c fzf -s 'q' -l 'query' -d 'Start the finder with the given query'
complete -c fzf -s '1' -l 'select-1' -d 'Automatically select the only match'
complete -c fzf -s 'f' -l 'filter' -d 'Filter mode. Do not start interactive finder'
complete -c fzf -l 'print-query' -d 'Print query as the first line'
complete -c fzf -l 'expect' -d 'List of keys to complete fzf'
complete -c fzf -l 'read0' -d 'Read input delimited by ASCII NUL characters'
complete -c fzf -l 'print0' -d 'Print output delimited by ASCII NUL characters'
complete -c fzf -l 'no-clear' -d 'Do not clear finder interface on exit'
complete -c fzf -l 'sync' -d 'Synchronous search for multi-staged filtering'
complete -c fzf -l 'version' -d 'Display version information and exit'
