complete -c gdb -s 'h' -d 'List all options, with brief explanations'
complete -c gdb -s 's' -d 'Read symbol table from <file>'
complete -c gdb -d 'Enable writing into executable and core files'
complete -c gdb -s 'e' -d 'Set executable'
complete -c gdb -d 'Read symbol table from <file> and execute it'
complete -c gdb -s 'c' -d 'Use <file> as a core dump to examine'
complete -c gdb -s 'x' -d 'Execute GDB commands from <file>'
complete -c gdb -s 'd' -d 'Add directory with source files'
complete -c gdb -s 'n' -d 'Do not execute commands from any .gdbinit files'
complete -c gdb -s 'q' -d 'Quiet'
complete -c gdb -d 'Run in batch mode'
complete -c gdb -s 'f' -d 'Used by Emacs'
complete -c gdb -s 'b' -d 'Set throughput in bps for remote debugging'
complete -c gdb -l 'args' -d 'Pass arguments to the program after its name'
complete -c gdb -d 'Run GDB using a text (console) user interface'
