complete -c gdbus -d 'Introspect a remote object'
complete -c gdbus -d 'Monitor a remote object'
complete -c gdbus -d 'Invoke a method on a remote object'
complete -c gdbus -d 'Emit a signal'
complete -c gdbus -d 'Wait for a bus name to appear'
complete -c gdbus -d 'Prints help'
complete -c gdbus -s 'y' -l 'system' -d 'Connect to the system bus'
complete -c gdbus -s 'e' -l 'session' -d 'Connect to the session bus'
complete -c gdbus -s 'a' -l 'address' -d 'Connect to given D-Bus address'
complete -c gdbus -s 'd' -l 'dest' -d 'Destination name'
complete -c gdbus -s 'o' -l 'object-path' -d 'Object path'
complete -c gdbus -s 'h' -l 'help' -d 'Prints help'
complete -c gdbus -s 'x' -l 'xml' -d 'Print XML'
complete -c gdbus -s 'r' -l 'recurse' -d 'Introspect children'
complete -c gdbus -s 'p' -l 'only-properties' -d 'Only print properties'
complete -c gdbus -s 'm' -l 'method' -d 'Method and interface name'
complete -c gdbus -s 't' -l 'timeout' -d 'Timeout in seconds'
complete -c gdbus -s 's' -l 'signal' -d 'Signal and interface name'
complete -c gdbus -s 'a' -l 'activate' -d 'Service to activate'
complete -c gdbus -s 't' -l 'timeout' -d 'Timeout to wait'
