complete -c gem -s 'h' -l 'help' -d 'Print usage informations and quit'
complete -c gem -s 'v' -l 'version' -d 'Print the version and quit'
complete -c gem -d 'Build a gem from a gemspec'
complete -c gem -d 'Adjust RubyGems certificate settings'
complete -c gem -d 'Check installed gems'
complete -c gem -d 'Cleanup old versions of installed gems in the local repository'
complete -c gem -d 'Display the contents of the installed gems'
complete -c gem -d 'Show the dependencies of an installed gem'
complete -c gem -d 'Display RubyGems environmental information'
complete -c gem -d 'Download a gem into current directory'
complete -c gem -d 'Provide help on the '"'"'gem'"'"' command'
complete -c gem -d 'Install a gem into the local repository'
complete -c gem -d 'Display all gems whose name starts with STRING'
complete -c gem -d 'Query gem information in local or remote repositories'
complete -c gem -d 'Generates RDoc for pre-installed gems'
complete -c gem -d 'Display all gems whose name contains STRING'
complete -c gem -d 'Display gem specification (in YAML)'
complete -c gem -d 'Uninstall a gem from the local repository'
complete -c gem -d 'Unpack an installed gem to the current directory'
complete -c gem -d 'Update the named gem or all installed gems in the local repository'
