complete -c gendarme -l 'version' -d 'Show version'
complete -c gendarme -l 'config' -d 'Use config file'
complete -c gendarme -l 'set' -d 'Use rule set from config file'
complete -c gendarme -l 'xml' -d 'Convert stdout to XML and redirect to file'
complete -c gendarme -l 'html' -d 'Convert stdout to HTML and redirect to file'
complete -c gendarme -l 'console' -d 'Show the defects on stdout'
complete -c gendarme -l 'ignore' -d 'Exclude the defects from file'
complete -c gendarme -l 'limit' -d 'Specify defect limit'
complete -c gendarme -l 'quiet' -d 'Discard stdout'
complete -c gendarme -s 'v' -l 'verbose' -d 'Show more messages'
