complete -c gio -d 'Print help'
complete -c gio -d 'Print version'
complete -c gio -d 'Concatenate files to stdout'
complete -c gio -d 'Copy files'
complete -c gio -d 'Show information about locations'
complete -c gio -d 'List the contents of locations'
complete -c gio -d 'Get or set the handler'
complete -c gio -d 'Create directories'
complete -c gio -d 'Monitor files'
complete -c gio -d 'Mount or unmount the locations'
complete -c gio -d 'Move files'
complete -c gio -d 'Open files'
complete -c gio -d 'Rename a file'
complete -c gio -d 'Delete files'
complete -c gio -d 'Read from stdin and save'
complete -c gio -d 'Set a file attribute'
complete -c gio -d 'Move files to the trash'
complete -c gio -d 'Lists the contents of locations in a tree'
complete -c gio -d 'Command'
complete -c gio -d 'MIME type'
complete -c gio -s 'T' -l 'no-target-directory' -d 'No target directory'
complete -c gio -s 'p' -l 'progress' -d 'Show progress'
complete -c gio -s 'i' -l 'interactive' -d 'Prompt before overwrite'
complete -c gio -s 'b' -l 'backup' -d 'Backup existing destination files'
complete -c gio -s 'a' -l 'attributes' -d 'The attributes to get'
complete -c gio -s 'n' -l 'nofollow-symlinks' -d 'Don'"'"'t follow symbolic links'
complete -c gio -s 'h' -l 'hidden' -d 'Show hidden files'
complete -c gio -s 'f' -l 'force' -d 'Ignore nonexistent files'
complete -c gio -l 'preserve' -d 'Preserve all attributes'
complete -c gio -s 'P' -l 'no-dereference' -d 'Never follow symbolic links'
complete -c gio -l 'default-permissions' -d 'Use default permissions'
complete -c gio -s 'w' -l 'query-writable' -d 'List writable attributes'
complete -c gio -s 'f' -l 'filesystem' -d 'Get file system info'
complete -c gio -s 'l' -l 'long' -d 'Use a long listing format'
complete -c gio -s 'd' -l 'print-display-names' -d 'Print display names'
complete -c gio -s 'u' -l 'print-uris' -d 'Print full URIs'
complete -c gio -s 'p' -l 'parent' -d 'Create parent directories'
complete -c gio -s 'd' -l 'dir' -d 'Monitor a directory'
complete -c gio -s 'f' -l 'file' -d 'Monitor a file'
complete -c gio -s 'D' -l 'direct' -d 'Monitor a file directly'
complete -c gio -s 's' -l 'silent' -d 'Monitors a file directly without reporting changes'
complete -c gio -s 'n' -l 'no-moves' -d 'Don'"'"'t report move events'
complete -c gio -s 'm' -l 'mounts' -d 'Watch for mount events'
complete -c gio -s 'm' -l 'mountable' -d 'Mount as mountable'
complete -c gio -s 'd' -l 'device' -d 'Mount volume'
complete -c gio -s 'u' -l 'unmount' -d 'Unmount'
complete -c gio -s 'e' -l 'eject' -d 'Eject'
complete -c gio -s 't' -l 'stop' -d 'Stop drive'
complete -c gio -s 's' -l 'unmount-scheme' -d 'Unmount all mounts with the given scheme'
complete -c gio -s 'f' -l 'force' -d 'Ignore outstanding file operations'
complete -c gio -s 'a' -l 'anonymous' -d 'Use an anonymous user'
complete -c gio -s 'l' -l 'list' -d 'List'
complete -c gio -s 'o' -l 'monitor' -d 'Monitor events'
complete -c gio -s 'i' -l 'detail' -d 'Show extra information'
complete -c gio -l 'tcrypt-pim' -d 'The numeric PIM when unlocking a VeraCrypt volume'
complete -c gio -l 'tcrypt-hidden' -d 'Mount a TCRYPT hidden volume'
complete -c gio -l 'tcrypt-system' -d 'Mount a TCRYPT system volume'
complete -c gio -s 'C' -l 'no-copy-fallback' -d 'Don'"'"'t use copy and delete fallback'
complete -c gio -s 'c' -l 'create' -d 'Only create if not existing'
complete -c gio -s 'a' -l 'append' -d 'Append to end of file'
complete -c gio -s 'p' -l 'private' -d 'Restrict access to the current user'
complete -c gio -s 'u' -l 'unlink' -d 'Replace as if the destination didn'"'"'t exist'
complete -c gio -s 'v' -l 'print-etag' -d 'Print new etag at end'
complete -c gio -s 'e' -l 'etag' -d 'The etag of the file being overwritten'
complete -c gio -s 't' -l 'type' -d 'Type of the attribute'
complete -c gio -l 'empty' -d 'Empty the trash'
complete -c gio -s 'l' -l 'follow-symlinks' -d 'Follow symbolic links'
