complete -c git -d 'Manage git subtrees'
complete -c git -s 'q' -l 'quiet' -d 'Suppress output'
complete -c git -s 'd' -l 'debug' -d 'Debug output'
complete -c git -s 'P' -l 'path' -d 'Path to the subtree'
complete -c git -d 'Add a new subtree to the repository'
complete -c git -d 'Merge changes from a subtree into the repository'
complete -c git -d 'Extract a subtree from the repository'
complete -c git -d 'Fetch and integrate changes from a remote subtree'
complete -c git -d 'Push changes to a remote subtree'
complete -c git -l 'annotate' -d 'Annotate the commit'
complete -c git -s 'b' -l 'branch' -d 'Branch to split'
complete -c git -l 'ignore-joins' -d 'Ignore joins during history reconstruction'
complete -c git -l 'onto' -d 'Specify the commit ID to start history reconstruction'
complete -c git -l 'rejoin' -d 'Merge the synthetic history back into the main project'
complete -c git -l 'squash' -d 'Merge subtree changes as a single commit'
complete -c git -l 'no-squash' -d 'Do not merge subtree changes as a single commit'
complete -c git -s 'm' -l 'message' -d 'Use the given message as the commit message for the merge commit'
complete -c git -l 'squash' -d 'Merge subtree changes as a single commit'
complete -c git -l 'no-squash' -d 'Do not merge subtree changes as a single commit'
complete -c git -s 'm' -l 'message' -d 'Use the given message as the commit message for the merge commit'
