complete -c gnome-extensions -d 'Print help'
complete -c gnome-extensions -d 'Print version'
complete -c gnome-extensions -d 'Enable extension'
complete -c gnome-extensions -d 'Disable extension'
complete -c gnome-extensions -d 'Reset extension'
complete -c gnome-extensions -d 'Uninstall extension'
complete -c gnome-extensions -d 'List extensions'
complete -c gnome-extensions -d 'Show extension info'
complete -c gnome-extensions -d 'Open extension preferences'
complete -c gnome-extensions -d 'Create extension'
complete -c gnome-extensions -d 'Package extension'
complete -c gnome-extensions -d 'Install extension bundle'
complete -c gnome-extensions -l 'user' -d 'Show user-installed extensions'
complete -c gnome-extensions -l 'system' -d 'Show system-installed extensions'
complete -c gnome-extensions -l 'enabled' -d 'Show enabled extensions'
complete -c gnome-extensions -l 'disabled' -d 'Show disabled extensions'
complete -c gnome-extensions -l 'prefs' -d 'Show extensions with preferences'
complete -c gnome-extensions -l 'updates' -d 'Show extensions with updates'
complete -c gnome-extensions -s 'd' -l 'details' -d 'Print extension details'
complete -c gnome-extensions -d 'Enabled'
complete -c gnome-extensions -d 'Disabled'
complete -c gnome-extensions -d 'Disabled'
complete -c gnome-extensions -d 'Enabled'
complete -c gnome-extensions -l 'uuid' -d 'The unique identifier of the new extension'
complete -c gnome-extensions -l 'name' -d 'The user-visible name of the new extension'
complete -c gnome-extensions -l 'description' -d 'A short description of what the extension does'
complete -c gnome-extensions -l 'template' -d 'The template to use for the new extension'
complete -c gnome-extensions -s 'i' -l 'interactive' -d 'Enter extension information interactively'
complete -c gnome-extensions -l 'extra-source' -d 'Additional source to include in the bundle'
complete -c gnome-extensions -l 'schema' -d 'A GSettings schema that should be included'
complete -c gnome-extensions -l 'podir' -d 'The directory where translations are found'
complete -c gnome-extensions -l 'gettext-domain' -d 'The gettext domain to use for translations'
complete -c gnome-extensions -s 'f' -l 'force' -d 'Overwrite an existing pack'
complete -c gnome-extensions -s 'o' -l 'out-dir' -d 'The directory where the pack should be created'
complete -c gnome-extensions -d 'Source directory'
complete -c gnome-extensions -s 'f' -l 'force' -d 'Overwrite an existing extension'
complete -c gnome-extensions -d 'Extension bundle'
complete -c gnome-extensions -s 'q' -l 'quiet' -d 'Do not print error messages'
