complete -c godoc -l 'analysis' -d 'Comma-separated list of analyses to perform'
complete -c godoc -l 'ex' -d 'Show examples in command line mode'
complete -c godoc -l 'goroot' -d 'Go root directory'
complete -c godoc -l 'html' -d 'Print HTML in command-line mode'
complete -c godoc -l 'http' -d 'HTTP service address'
complete -c godoc -l 'httptest.serve' -d 'httptest.NewServer serves on this address and blocks'
complete -c godoc -l 'index' -d 'Enable search index'
complete -c godoc -l 'index_files' -d 'Glob pattern specifying index files'
complete -c godoc -l 'index_interval' -d 'Interval of indexing'
complete -c godoc -l 'index_throttle' -d 'Index throttle value'
complete -c godoc -l 'links' -d 'Link identifiers to their declarations'
complete -c godoc -l 'maxresults' -d 'Maximum number of full text search results shown'
complete -c godoc -l 'notes' -d 'Regular expression matching note markers to show'
complete -c godoc -l 'play' -d 'Enable playground in web interface'
complete -c godoc -s 'q' -d 'Arguments are considered search queries'
complete -c godoc -l 'server' -d 'Webserver address for command line searches'
complete -c godoc -l 'src' -d 'Print (exported) source in command-line mode'
complete -c godoc -l 'tabwidth' -d 'Tab width'
complete -c godoc -l 'templates' -d 'Directory containing alternate template files'
complete -c godoc -l 'timestamps' -d 'Show timestamps with directory listings'
complete -c godoc -l 'url' -d 'Print HTML for named URL'
complete -c godoc -s 'v' -d 'Verbose mode'
complete -c godoc -l 'write_index' -d 'Write index to a file'
complete -c godoc -l 'zip' -d 'Zip file providing the file system to serve'
complete -c godoc -l 'help' -s 'h' -d 'Show help'
