complete -c gorename -s 'd' -d 'Display diffs instead of rewriting files'
complete -c gorename -l 'diffcmd' -d 'Diff command invoked when using -d'
complete -c gorename -l 'force' -d 'Proceed, even if conflicts were reported'
complete -c gorename -l 'from' -d 'Identifier to be renamed'
complete -c gorename -l 'help' -d 'Show usage message'
complete -c gorename -l 'offset' -d 'File and byte offset of identifier to be renamed'
complete -c gorename -l 'tags' -d 'Build tag'
complete -c gorename -l 'to' -d 'New name for identifier'
complete -c gorename -s 'v' -d 'Print verbose information'
complete -c gorename -l 'help' -s 'h' -d 'Show help'
