complete -c gprof -s 'A' -l 'annotated-source' -d 'Print annotated source'
complete -c gprof -s 'b' -l 'brief' -d 'Do not print explanations'
complete -c gprof -s 'C' -l 'exec-counts' -d 'Print tally'
complete -c gprof -s 'i' -l 'file-info' -d 'Display summary'
complete -c gprof -s 'I' -l 'directory-path' -d 'Search directories for source'
complete -c gprof -s 'J' -l 'no-annotated-source' -d 'No annotated source'
complete -c gprof -s 'L' -l 'print-path' -d 'Print full path of source'
complete -c gprof -s 'p' -l 'flat-profile' -d 'Print flat profile'
complete -c gprof -s 'P' -l 'no-flat-profile' -d 'No flat profile'
complete -c gprof -s 'q' -l 'graph' -d 'Print call graph'
complete -c gprof -s 'Q' -l 'no-graph' -d 'No call graph'
complete -c gprof -s 'y' -l 'separate-files' -d 'Annotate to file'
complete -c gprof -s 'Z' -l 'no-exec-counts' -d 'No tally'
complete -c gprof -l 'function-ordering' -d 'Suggest function ordering'
complete -c gprof -s 'T' -l 'traditional' -d 'Traditional mode'
complete -c gprof -s 'x' -l 'all-lines' -d 'Annotate every line'
complete -c gprof -l 'no-demangle' -d 'Turn of demangling'
