complete -c grub-install -l 'compress' -d 'Compress GRUB files'
complete -c grub-install -l 'directory' -s 'd' -d 'Use image and modules under given directory'
complete -c grub-install -l 'fonts' -d 'Install given fonts'
complete -c grub-install -l 'install-modules' -d 'Install only given modules and their dependencies'
complete -c grub-install -l 'pubkey' -s 'k' -d 'Embed given file as public key for signature checking'
complete -c grub-install -l 'locale-directory' -d 'Use translations under given directory'
complete -c grub-install -l 'locales' -d 'Install only given locales'
complete -c grub-install -l 'modules' -d 'Preload specfied modules'
complete -c grub-install -l 'themes' -d 'Install given theme'
complete -c grub-install -l 'verbose' -s 'v' -d 'Verbose mode'
complete -c grub-install -l 'allow-floppy' -d 'Make drive also bootable as floppy'
complete -c grub-install -l 'boot-directory' -d 'Install GRUB images under DIR/grub'
complete -c grub-install -l 'bootloader-id' -d 'Set bootloader ID'
complete -c grub-install -l 'core-compress' -d 'Choose compression to use for core image'
complete -c grub-install -l 'disk-module' -d 'Set disk module to use'
complete -c grub-install -l 'efi-directory' -d 'Use given directory as the EFI System Partition root'
complete -c grub-install -l 'force' -d 'Install even if problems are detected'
complete -c grub-install -l 'force-file-id' -d 'Use identifier file even if UUID is available'
complete -c grub-install -l 'label-bgcolor' -d 'Use given color for label background'
complete -c grub-install -l 'label-color' -d 'Use given color for label'
complete -c grub-install -l 'label-font' -d 'Use given file for label'
complete -c grub-install -l 'macppc-directory' -d 'Use given directory for PPC Mac install'
complete -c grub-install -l 'no-bootsector' -d 'Do not install bootsector'
complete -c grub-install -l 'product-version' -d 'Set product version'
complete -c grub-install -l 'recheck' -d 'Delete device map if it already exists'
complete -c grub-install -l 'removable' -d 'The installation is removable'
complete -c grub-install -l 'skip-fs-probe' -s 's' -d 'Do not probe for filesystems'
complete -c grub-install -l 'target' -d 'Install GRUB for given platform'
complete -c grub-install -l 'help' -s '?' -d 'Show help'
complete -c grub-install -l 'usage' -d 'Show usage'
complete -c grub-install -l 'version' -d 'Show version'
