complete -c grub-mkrescue -l 'compress' -d 'Compress GRUB files'
complete -c grub-mkrescue -l 'dtb' -d 'Embed a specific DTB'
complete -c grub-mkrescue -l 'directory' -s 'd' -d 'Use images and modules under given directory'
complete -c grub-mkrescue -l 'fonts' -d 'Install given fonts'
complete -c grub-mkrescue -l 'install-modules' -d 'Install only the given modules'
complete -c grub-mkrescue -l 'pubkey' -s 'k' -d 'Embed given file as public key for signature checking'
complete -c grub-mkrescue -l 'locale-directory' -d 'Use translation under given directory'
complete -c grub-mkrescue -l 'locales' -d 'Install only given locales'
complete -c grub-mkrescue -l 'modules' -d 'Pre-load specified modules'
complete -c grub-mkrescue -l 'theme' -d 'Install given theme'
complete -c grub-mkrescue -l 'verbose' -s 'v' -d 'Print verbose messages'
complete -c grub-mkrescue -l 'arcs-boot' -d 'Enable ARCS boot'
complete -c grub-mkrescue -l 'core-compress' -d 'Choose compression to use for core image'
complete -c grub-mkrescue -l 'label-gbcolor' -d 'Use given color for label background'
complete -c grub-mkrescue -l 'label-color' -d 'Use given color for label'
complete -c grub-mkrescue -l 'label-font' -d 'Use given file font for label'
complete -c grub-mkrescue -l 'output' -s 'o' -d 'Save output in given file'
complete -c grub-mkrescue -l 'product-name' -d 'Use given string as product name'
complete -c grub-mkrescue -l 'product-version' -d 'Use given string as product version'
complete -c grub-mkrescue -l 'rom-directory' -d 'Save ROM image in given directory'
complete -c grub-mkrescue -l 'sparc-boot' -d 'Enable sparc boot'
complete -c grub-mkrescue -l 'xorriso' -d 'Use given file as xorriso'
complete -c grub-mkrescue -l 'help' -s '?' -d 'Show help'
complete -c grub-mkrescue -l 'usage' -d 'Show short usage message'
complete -c grub-mkrescue -l 'version' -s 'V' -d 'Show program version'
