complete -c grunt -s 'h' -l 'help' -d 'Display help text'
complete -c grunt -l 'base' -d 'Specify an alternate base path'
complete -c grunt -l 'no-color' -d 'Disable colored output'
complete -c grunt -l 'gruntfile'
complete -c grunt -s 'd' -l 'debug' -d 'Enable debugging mode for tasks that support it'
complete -c grunt -l 'stack' -d 'Print a stack trace when exiting with a warning or fatal error'
complete -c grunt -s 'f' -l 'force' -d 'A way to force your way past warnings.'
complete -c grunt -l 'tasks'
complete -c grunt -l 'npm' -d 'Npm-installed grunt plugins to scan for task and extra files'
complete -c grunt -l 'no-write' -d 'Disable writing files (dry run)'
complete -c grunt -s 'v' -l 'verbose' -d 'Verbose mode. A lot more information output'
complete -c grunt -s 'V' -l 'version' -d 'Print the grunt version. Combine with --verbose for more info'
complete -c grunt -l 'completion' -d 'Output shell auto-completion rules.'
