complete -c gsettings -l 'version' -d 'Print the version information'
complete -c gsettings -l 'schemadir' -d 'Specify a custom schemas directory'
complete -c gsettings -d 'Get the value of a key'
complete -c gsettings -d 'Determine if a key is writable'
complete -c gsettings -d 'Determine the valid value range of a key'
complete -c gsettings -d 'Print the description of a key'
complete -c gsettings -d 'Set the value of a key'
complete -c gsettings -d 'Reset a key to its default value'
complete -c gsettings -d 'Reset all keys under the given schema'
complete -c gsettings -d 'List all installed, non-relocatable schemas'
complete -c gsettings -d 'List all installed, relocatable schemas'
complete -c gsettings -d 'List all keys in a schema'
complete -c gsettings -d 'List all children of a schema'
complete -c gsettings -d 'List keys and values, recursively'
complete -c gsettings -d 'Print help'
