complete -c help -d 'Autosuggestions'
complete -c help -d 'Builtin commands'
complete -c help -d 'Cartesian Products'
complete -c help -d 'Setting syntax highlighting colors'
complete -c help -d 'Combining different expansions'
complete -c help -d 'Debugging fish scripts'
complete -c help -d 'Command line editor'
complete -c help -d 'Emacs mode commands'
complete -c help -d 'Escaping characters'
complete -c help -d 'Event handlers'
complete -c help -d 'Parameter expansion (Globbing)'
complete -c help -d 'Brace expansion {a,b,c}'
complete -c help -d 'Command substitution'
complete -c help -d 'Command substitution (SUBCOMMAND)'
complete -c help -d 'Home directory expansion ~USER'
complete -c help -d 'Index range expansion'
complete -c help -d 'Variable expansion $VARNAME'
complete -c help -d 'Wildcard expansion *.*'
complete -c help -d 'Parameter expansion (Globbing)'
complete -c help -d 'Configurable greeting'
complete -c help -d 'Help on how to reuse previously entered commands'
complete -c help -d 'Searchable history'
complete -c help -d 'Shell variable and function names'
complete -c help -d 'Initialization files'
complete -c help -d 'Introduction'
complete -c help -d 'Running multiple programs'
complete -c help -d 'Copy and paste (Kill Ring)'
complete -c help -d 'Further help and development'
complete -c help -d 'Multiline editing'
complete -c help -d 'Other features'
complete -c help -d 'Piping'
complete -c help -d 'Programmable prompt'
complete -c help -d 'Quotes'
complete -c help -d 'Input/Output (IO) redirection'
complete -c help -d 'Shared bindings'
complete -c help -d 'Introduction to the fish syntax'
complete -c help -d 'Background jobs'
complete -c help -d 'Conditional execution of code and flow control'
complete -c help -d 'Functions'
complete -c help -d 'Autoloading functions'
complete -c help -d 'Defining aliases'
complete -c help -d 'Job control'
complete -c help -d 'Some common words'
complete -c help -d 'How tab-completion works'
complete -c help -d 'Programmable title'
complete -c help -d 'Shell variables'
complete -c help -d 'Lists'
complete -c help -d 'Variables for changing highlighting colors'
complete -c help -d 'Exporting variables'
complete -c help -d 'Variable scope for functions'
complete -c help -d 'Locale variables'
complete -c help -d 'Variable scope'
complete -c help -d 'Special variables'
complete -c help -d 'The status variable'
complete -c help -d 'More on universal variables'
complete -c help -d 'Vi mode commands'
complete -c help -d 'Command mode'
complete -c help -d 'Insert mode'
complete -c help -d 'Visual mode'
complete -c help -d 'Writing your own completions'
complete -c help -d 'Useful functions for writing completions'
complete -c help -d 'Where to put completions'
complete -c help -d 'Tutorial'
complete -c help -d 'Autoloading Functions'
complete -c help -d 'Autosuggestions'
complete -c help -d 'Combiners (And, Or, Not)'
complete -c help -d 'Command Substitutions'
complete -c help -d 'Conditionals (If, Else, Switch)'
complete -c help -d 'Exit Status'
complete -c help -d 'Exports (Shell Variables)'
complete -c help -d 'Functions'
complete -c help -d 'Getting Help'
complete -c help -d 'Learning fish'
complete -c help -d 'Lists'
complete -c help -d 'Loops'
complete -c help -d 'Ready for more?'
complete -c help -d '$PATH'
complete -c help -d 'Pipes and Redirections'
complete -c help -d 'Prompt'
complete -c help -d 'Running Commands'
complete -c help -d 'Separating Commands (Semicolon)'
complete -c help -d 'Startup (Where'"'"'s .bashrc?)'
complete -c help -d 'Syntax Highlighting'
complete -c help -d 'Tab Completions'
complete -c help -d 'Universal Variables'
complete -c help -d 'Variables'
complete -c help -d 'Why fish?'
complete -c help -d 'Wildcards'
complete -c help -d 'Fish'"'"'s release notes'
complete -c help -d 'How to write completions'
complete -c help -d 'Frequently Asked Questions'
complete -c help -d 'Differences from bash'
complete -c help -d 'How to handle arguments'
complete -c help -d 'How functions are loaded'
complete -c help -d '{a,b} brace expansion'
complete -c help -d 'An overview of fish'"'"'s builtins'
complete -c help -d 'How different expansions work together'
complete -c help -d 'How lists combine'
complete -c help -d '(command) command substitution'
complete -c help -d '# comments'
complete -c help -d 'ifs and elses'
complete -c help -d 'How to define an alias'
complete -c help -d 'How \\ escaping works'
complete -c help -d 'What set -x does'
complete -c help -d 'How to define functions'
complete -c help -d '~ expansion'
complete -c help -d 'var[x..y] slices'
complete -c help -d '< and > redirectoins'
complete -c help -d 'Variables with multiple elements'
complete -c help -d 'while, for and begin'
complete -c help -d 'foo=bar variable overrides'
complete -c help -d 'How to color the pager'
complete -c help -d 'Why $PATH is special'
complete -c help -d 'What characters are allowed in names'
complete -c help -d '$status, the return code'
complete -c help -d '$variable'
complete -c help -d 'Local, global and universal scope'
complete -c help -d 'How to write your own prompt'
complete -c help -d 'How to make your own prompt'
