complete -c heroku -s 'o' -l 'org' -l 'ORG' -d 'the org to list the apps for'
complete -c heroku -s 'A' -l 'all' -d 'list all apps in the org. Not just joined apps'
complete -c heroku -s 'p' -l 'personal' -d 'list apps in personal account when a default org is set'
complete -c heroku -l 'app' -s 'a'
complete -c heroku -l 'app' -s 'a'
complete -c heroku -l 'app' -s 'a'
complete -c heroku -l 'app' -s 'a'
complete -c heroku -l 'app' -s 'a'
complete -c heroku -l 'app' -s 'a'
complete -c heroku -l 'app' -s 'a'
complete -c heroku -s 's' -l 'shell' -d 'output config vars in shell format'
complete -c heroku -d 'display a config value for an app'
complete -c heroku -d 'set one or more config vars (KEY=VALUE)'
complete -c heroku -d 'unset one or more config vars'
complete -c heroku -d 'remove a custom domain from an app'
complete -c heroku -s 'n' -l 'num' -l 'NUM' -d 'the number of lines to display'
complete -c heroku -s 'p' -l 'ps' -l 'PS' -d 'only display logs from the given process'
complete -c heroku -s 's' -l 'source' -l 'SOURCE' -d 'only display logs from the given source'
complete -c heroku -s 't' -l 'tail' -d 'continually stream logs'
complete -c heroku -d 'resize dynos to the given size (DYNO1=1X|2X|PX)'
complete -c heroku -d 'restart an app dyno'
complete -c heroku -d 'scale dynos by the given amount (DYNO1=AMOUNT1)'
complete -c heroku -d 'stop an app dyno'
complete -c heroku -s 'n' -l 'num' -l 'NUM' -d 'number of releases to show, maximum 50'
complete -c heroku -d 'view detailed information for a release'
complete -c heroku -d 'roll back to an older release'
complete -c heroku -s 's' -l 'size' -l 'SIZE' -d 'specify dyno size'
complete -c heroku -s 't' -l 'tail' -d 'stream logs for the dyno'
