complete -c hg -s 'R' -l 'repository' -d 'repository root directory or name of overlay bundle file'
complete -c hg -l 'cwd' -d 'change working directory'
complete -c hg -s 'y' -l 'noninteractive' -d 'do not prompt, automatically pick the first choice for all prompts'
complete -c hg -s 'q' -l 'quiet' -d 'suppress output'
complete -c hg -s 'v' -l 'verbose' -d 'enable additional output'
complete -c hg -l 'config' -d 'set/override config option'
complete -c hg -l 'debug' -d 'enable debugging output'
complete -c hg -l 'debugger' -d 'start debugger'
complete -c hg -l 'encoding' -d 'set the charset encoding'
complete -c hg -l 'encodingmode' -d 'set the charset encoding mode'
complete -c hg -l 'traceback' -d 'always print a traceback on exception'
complete -c hg -l 'time' -d 'time how long the command takes'
complete -c hg -l 'profile' -d 'print command execution profile'
complete -c hg -l 'version' -d 'output version information and exit'
complete -c hg -s 'h' -l 'help' -d 'display help and exit'
complete -c hg -l 'hidden' -d 'consider hidden changesets'
complete -c hg -l 'color' -d 'when to colorize'
complete -c hg -l 'pager' -d 'when to paginate'
complete -c hg -s 'I' -l 'include' -d 'include names matching the given patterns'
complete -c hg -s 'X' -l 'exclude' -d 'exclude names matching the given patterns'
complete -c hg -s 'S' -l 'subrepos' -d 'recurse into subrepositories'
complete -c hg -s 'n' -l 'dry-run' -d 'do not perform actions, just print output'
complete -c hg -l 'mq' -d 'operate on patch repository'
complete -c hg -s 'f' -l 'force' -d 'set branch name even if it shadows an existing branch'
complete -c hg -s 'C' -l 'clean' -d 'reset branch name to parent branch name'
complete -c hg -l 'mq' -d 'operate on patch repository'
complete -c hg -s 'e' -l 'edit' -d 'invoke editor on commit messages'
complete -c hg -s 'g' -l 'git' -d 'use git extended diff format'
complete -c hg -s 'U' -l 'currentuser' -d 'add "From: <current user>" to patch'
complete -c hg -s 'u' -l 'user' -d 'add "From: <USER>" to patch'
complete -c hg -s 'D' -l 'currentdate' -d 'add "Date: <current date>" to patch'
complete -c hg -s 'd' -l 'date' -d 'add "Date: <DATE>" to patch'
complete -c hg -s 'I' -l 'include' -d 'include names matching the given patterns'
complete -c hg -s 'X' -l 'exclude' -d 'exclude names matching the given patterns'
complete -c hg -s 'm' -l 'message' -d 'use text as commit message'
complete -c hg -s 'l' -l 'logfile' -d 'read commit message from file'
complete -c hg -s 'i' -l 'interactive' -d 'interactively record a new patch'
complete -c hg -s 'f' -l 'force' -d 'force tag'
complete -c hg -s 'l' -l 'local' -d 'make the tag local'
complete -c hg -s 'r' -l 'rev' -d 'revision to tag'
complete -c hg -l 'remove' -d 'remove a tag'
complete -c hg -s 'e' -l 'edit' -d 'invoke editor on commit messages'
complete -c hg -s 'm' -l 'message' -d 'use <text> as commit message'
complete -c hg -s 'd' -l 'date' -d 'record the specified date as commit date'
complete -c hg -s 'u' -l 'user' -d 'record the specified user as committer'
complete -c hg -l 'mq' -d 'operate on patch repository'
complete -c hg -l 'mq' -d 'operate on patch repository'
