complete -c hjson -s 'j' -l 'json' -d 'output formatted json'
complete -c hjson -s 'c' -l 'compact' -d 'output condensed json'
complete -c hjson -d 'output the opening brace on the same line'
complete -c hjson -d 'quote all strings'
complete -c hjson -d 'quote all strings and keys'
complete -c hjson -d 'output in JSON-compatible format'
complete -c hjson -d 'round trip comments'
complete -c hjson -d 'disable color output'
complete -c hjson -d 'set condense option [default 60]'
