complete -c homectl -d 'List home areas'
complete -c homectl -d 'Activate a home area'
complete -c homectl -d 'Deactivate a home area'
complete -c homectl -d 'Inspect a home area'
complete -c homectl -d 'Authenticate a home area'
complete -c homectl -d 'Create a home area'
complete -c homectl -d 'Remove a home area'
complete -c homectl -d 'Update a home area'
complete -c homectl -d 'Change password of a home area'
complete -c homectl -d 'Resize a home area'
complete -c homectl -d 'Temporarily lock an active home area'
complete -c homectl -d 'Unlock a temporarily locked home area'
complete -c homectl -d 'Lock all suitable home areas'
complete -c homectl -d 'Run shell or command with access to a home area'
complete -c homectl -s 'h' -l 'help' -d 'Show this help'
complete -c homectl -l 'version' -d 'Show package version'
complete -c homectl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c homectl -l 'no-legend' -d 'Do not show the headers and footers'
complete -c homectl -l 'no-ask-password' -d 'Do not ask for system passwords'
complete -c homectl -s 'H' -l 'host' -d 'Operate on remote host'
complete -c homectl -s 'M' -l 'machine' -d 'Operate on local container'
complete -c homectl -l 'identity' -d 'Read JSON identity from file'
complete -c homectl -l 'json' -d 'Output inspection data in JSON'
complete -c homectl -s 'j' -d 'Equivalent to --json (on TTY) or short (otherwise)'
complete -c homectl -l 'export-format' -d 'Strip JSON inspection data'
complete -c homectl -s 'E' -d 'Equals -j --export-format (twice to minimal)'
complete -c homectl -d 'Equals -j --export-format=minimal'
complete -c homectl -s 'c' -l 'real-name' -d 'Real name for user'
complete -c homectl -l 'realm' -d 'Realm to create user in'
complete -c homectl -l 'email-address' -d 'Email address for user'
complete -c homectl -l 'location' -d 'Set location of user on earth'
complete -c homectl -l 'icon-name' -d 'Icon name for user'
complete -c homectl -s 'd' -l 'home-dir' -d 'Home directory'
complete -c homectl -s 'u' -l 'uid' -d 'Numeric UID for user'
complete -c homectl -s 'G' -l 'member-of' -d 'Add user to group'
complete -c homectl -l 'skel' -d 'Skeleton directory to use'
complete -c homectl -l 'shell' -d 'Shell for account'
complete -c homectl -l 'setenv' -d 'Set an environment variable at log-in'
complete -c homectl -l 'timezone' -d 'Set a time-zone'
complete -c homectl -l 'language' -d 'Set preferred language'
complete -c homectl -l 'ssh-authorized-keys' -d 'Specify SSH public keys'
complete -c homectl -l 'pkcs11-token-uri' -d 'URI to PKCS#11 security token'
complete -c homectl -l 'fido2-device' -d 'Path to FIDO2 hidraw device'
complete -c homectl -l 'locked' -d 'Set locked account state'
complete -c homectl -l 'not-before' -d 'Do not allow logins before'
complete -c homectl -l 'not-after' -d 'Do not allow logins after'
complete -c homectl -l 'rate-limit-interval' -d 'Login rate-limit interval in seconds'
complete -c homectl -l 'rate-limit-burst' -d 'Login rate-limit attempts per interval'
complete -c homectl -l 'password-hint' -d 'Set Password hint'
complete -c homectl -l 'enforce-password-policy' -d 'Control enforce password policy'
complete -c homectl -s 'P' -d 'Equivalent to --enforce-password-password=no'
complete -c homectl -l 'password-change-now' -d 'Require the password to be changed on next login'
complete -c homectl -l 'password-change-min' -d 'Require minimum time between password changes'
complete -c homectl -l 'password-change-max' -d 'Require maximum time between password changes'
complete -c homectl -l 'password-change-warn' -d 'How much time to warn before password expiry'
complete -c homectl -l 'password-change-inactive' -d 'How much time to block password after expiry'
complete -c homectl -l 'disk-size' -d 'Size to assign the user on disk'
complete -c homectl -l 'access-mode' -d 'User home directory access mode'
complete -c homectl -l 'umask' -d 'Umask for user when logging in'
complete -c homectl -l 'nice' -d 'Nice level for user'
complete -c homectl -l 'rlimit' -d 'Set resource limits'
complete -c homectl -l 'tasks-max' -d 'Set maximum number of per-user tasks'
complete -c homectl -l 'memory-high' -d 'Set high memory threshold in bytes'
complete -c homectl -l 'memory-max' -d 'Set maximum memory limit'
complete -c homectl -l 'cpu-weight' -d 'Set CPU weight'
complete -c homectl -l 'io-weight' -d 'Set IO weight'
complete -c homectl -l 'storage' -d 'Storage type to use'
complete -c homectl -l 'image-path' -d 'Path to image file/directory'
complete -c homectl -l 'fs-type' -d 'File system type to use in case of luks storage'
complete -c homectl -l 'luks-discard' -d 'Whether to use discard feature'
complete -c homectl -l 'luks-offline-discard' -d 'Whether to trim file on logout'
complete -c homectl -l 'luks-cipher' -d 'Cipher to use for LUKS encryption'
complete -c homectl -l 'luks-cipher-mode' -d 'Cipher mode to use for LUKS encryption'
complete -c homectl -l 'luks-volume-key-size' -d 'Volume key size to use for LUKS encryption'
complete -c homectl -l 'luks-pbkdf-type' -d 'Password-based Key Derivation Function to use'
complete -c homectl -l 'luks-pbkdf-hash-algorithm' -d 'PBKDF hash algorithm to use'
complete -c homectl -l 'luks-pbkdf-time-cost' -d 'Time cost for PBKDF in seconds'
complete -c homectl -l 'luks-pbkdf-memory-cost' -d 'Memory cost for PBKDF in bytes'
complete -c homectl -l 'luks-pbkdf-parallel-threads' -d 'Number of parallel threads for PKBDF'
complete -c homectl -l 'nosuid' -d 'Control the nosuid flag of the home mount'
complete -c homectl -l 'nodev' -d 'Control the nodev flag of the home mount'
complete -c homectl -l 'noexec' -d 'Control the noexec flag of the home mount'
complete -c homectl -l 'cifs-domain' -d 'CIFS (Windows) domain'
complete -c homectl -l 'cifs-user-name' -d 'CIFS (Windows) user name'
complete -c homectl -l 'cifs-service' -d 'CIFS (Windows) service to mount as home area'
complete -c homectl -l 'stop-delay' -d 'How long to leave user services running after logout'
complete -c homectl -l 'kill-processes' -d 'Whether to kill user processes when sessions terminate'
complete -c homectl -l 'auto-login' -d 'Try to log this user in automatically'
