complete -c hostnamectl -l 'no-ask-password' -d 'Don'"'"'t query for authentication for privileged operations'
complete -c hostnamectl -l 'static' -d 'Get or set static hostname'
complete -c hostnamectl -l 'transient' -d 'Get or set transient hostname'
complete -c hostnamectl -l 'pretty' -d 'Get or set pretty hostname'
complete -c hostnamectl -s 'H' -l 'host' -d 'Execute operation on remote host'
complete -c hostnamectl -s 'M' -l 'machine' -d 'Execute operation on local container'
complete -c hostnamectl -s 'h' -l 'help' -d 'Print short help'
complete -c hostnamectl -l 'version' -d 'Print version'
complete -c hostnamectl -l 'json' -d 'Show output as JSON'
