complete -c htop -l 'delay' -s 'd' -d 'Update interval'
complete -c htop -l 'no-color' -s 'C' -d 'Start htop in monochrome mode'
complete -c htop -l 'no-colour' -d 'Start htop in monochrome mode'
complete -c htop -l 'filter' -s 'F' -d 'Filter processes by terms matching the commands'
complete -c htop -l 'help' -s 'h' -d 'Show help and exit'
complete -c htop -l 'pid' -s 'p' -d 'Show only given PIDs'
complete -c htop -l 'sort-key' -s 's' -d 'Sort column'
complete -c htop -l 'user' -s 'u' -d 'Monitor given user'
complete -c htop -l 'no-unicode' -s 'U' -d 'Do not use unicode but ASCII characters for graph meters'
complete -c htop -l 'no-mouse' -s 'M' -d 'Disable support of mouse control'
complete -c htop -l 'readonly' -d 'Disable all system and process changing features'
complete -c htop -l 'version' -s 'V' -d 'Show version and exit'
complete -c htop -l 'tree' -s 't' -d 'Show processes in tree view'
complete -c htop -l 'highlight-changes' -s 'H' -d 'Highlight new and old processes'
