complete -c hugo -l 'config' -d 'Configuration file'
complete -c hugo -l 'debug' -d 'Debug output'
complete -c hugo -l 'log' -d 'Enable logging'
complete -c hugo -l 'logFile' -d 'Log file'
complete -c hugo -l 'quiet' -d 'Quiet mode'
complete -c hugo -s 'v' -l 'verbose' -d 'Verbose output'
complete -c hugo -l 'verboseLog' -d 'Verbose logging'
complete -c hugo -s 'b' -l 'baseURL' -d 'Hostname and path to the root'
complete -c hugo -s 'B' -l 'buildDrafts' -d 'Include content marked as draft'
complete -c hugo -s 'E' -l 'buildExpired' -d 'Include expired content'
complete -c hugo -s 'F' -l 'buildFuture' -d 'Include content with publishdate in the future'
complete -c hugo -l 'cacheDir' -d 'Cache directory'
complete -c hugo -l 'canonifyURLs' -d 'Canonicalize all relative URLs using baseurl'
complete -c hugo -l 'cleanDestinationDir' -d 'Remove files from destination not found in static directories'
complete -c hugo -s 'c' -l 'contentDir' -d 'Content directory'
complete -c hugo -s 'd' -l 'destination' -d 'Destination directory'
complete -c hugo -l 'disable404' -d 'Do not build 404 page'
complete -c hugo -l 'disableKinds' -d 'Disable different kinds of pages'
complete -c hugo -l 'disableRSS' -d 'Do not build RSS files'
complete -c hugo -l 'disableSitemap' -d 'Do not build sitemap files'
complete -c hugo -l 'enableGitInfo' -d 'Add Git revision, date and author info to the pages'
complete -c hugo -l 'forceSyncStatic' -d 'Copy all files when static is changed'
complete -c hugo -s 'h' -l 'help' -d 'Help for hugo'
complete -c hugo -l 'i18n-warnings' -d 'Print missing translations'
complete -c hugo -l 'ignoreCache' -d 'Ignore the cache directory'
complete -c hugo -s 'l' -l 'layoutDir' -d 'Layout directory'
complete -c hugo -l 'noChmod' -d 'Do not sync permission mode of files'
complete -c hugo -l 'noTimes' -d 'Do not sync modification time of files'
complete -c hugo -l 'pluralizeListTitles' -d 'Pluralize titles in lists using inflect'
complete -c hugo -l 'preserveTaxonomyNames' -d 'Preserve taxonomy names as written'
complete -c hugo -l 'renderToMemory' -d 'Render to memory'
complete -c hugo -s 's' -l 'source' -d 'Source directory'
complete -c hugo -l 'stepAnalysis' -d 'Display memory and timing of different steps of the program'
complete -c hugo -l 'templateMetrics' -d 'Display metrics about template executions'
complete -c hugo -l 'templateMetricsHints' -d 'Calculate some improvement hints when combined with --templateMetrics'
complete -c hugo -s 't' -l 'theme' -d 'Theme to use'
complete -c hugo -l 'themesDir' -d 'Themes directory'
complete -c hugo -l 'uglyURLs' -d 'Use /filename.html instead of /filename/'
complete -c hugo -s 'w' -l 'watch' -d 'Watch filesystem for changes and recreate as needed'
complete -c hugo -d 'Benchmark Hugo by building the site a number of times'
complete -c hugo -s 'n' -l 'count' -d 'Number of times to build the site'
complete -c hugo -l 'cpuprofile' -d 'CPU profile file'
complete -c hugo -s 'h' -l 'help' -d 'Help for benchmark'
complete -c hugo -l 'memprofile' -d 'Memory profile file'
complete -c hugo -l 'renderToMemory' -d 'Render to memory'
complete -c hugo -l 'stepAnalysis' -d 'Display memory and timing of different steps of the program'
complete -c hugo -l 'templateMetrics' -d 'Display metrics about template executions'
complete -c hugo -l 'templateMetricsHints' -d 'Calculate some improvement hints when combined with --templateMetrics'
complete -c hugo -d 'Perform some verification checks'
complete -c hugo -s 'h' -l 'help' -d 'Help for check'
complete -c hugo -d 'Check system ulimit settings'
complete -c hugo -s 'h' -l 'help' -d 'Help for ulimit'
complete -c hugo -d 'Print the site configuration'
complete -c hugo -s 'h' -l 'help' -d 'Help for config'
complete -c hugo -d 'Convert the content to different formats'
complete -c hugo -s 'h' -l 'help' -d 'Help for convert'
complete -c hugo -s 'o' -l 'output' -d 'Output directory'
complete -c hugo -s 's' -l 'source' -d 'Source directory'
complete -c hugo -l 'unsafe' -d 'Enable less safe operations'
complete -c hugo -d 'Convert front matter to JSON'
complete -c hugo -s 'h' -l 'help' -d 'Help for toJSON'
complete -c hugo -d 'Convert front matter to TOML'
complete -c hugo -s 'h' -l 'help' -d 'Help for toTOML'
complete -c hugo -d 'Convert front matter to YAML'
complete -c hugo -s 'h' -l 'help' -d 'Help for toYAML'
complete -c hugo -d 'Print Hugo version and environment info'
complete -c hugo -s 'h' -l 'help' -d 'Help for env'
complete -c hugo -d 'Collection of several useful generators'
complete -c hugo -s 'h' -l 'help' -d 'Help for gen'
complete -c hugo -d 'Generate shell autocompletion script for Hugo'
complete -c hugo -l 'completionfile' -d 'Autocompletion file'
complete -c hugo -s 'h' -l 'help' -d 'Help for autocomplete'
complete -c hugo -l 'type' -d 'Autocompletion type'
complete -c hugo -d 'Generate CSS stylesheet for the Chroma code highlighter'
complete -c hugo -s 'h' -l 'help' -d 'Help for chromastyles'
complete -c hugo -l 'highlightStyle' -d 'Style used for highlighting lines'
complete -c hugo -l 'lineStyle' -d 'Style used for line numbers'
complete -c hugo -l 'style' -d 'Highlighter style'
complete -c hugo -d 'Generate Markdown documentation for the Hugo CLI'
complete -c hugo -l 'dir' -d 'Doc directory'
complete -c hugo -s 'h' -l 'help' -d 'Help for doc'
complete -c hugo -d 'Generate man pages for the Hugo CLI'
complete -c hugo -l 'dir' -d 'Man pages directory'
complete -c hugo -s 'h' -l 'help' -d 'Help for man'
complete -c hugo -d 'Import your site from others'
complete -c hugo -s 'h' -l 'help' -d 'Help for import'
complete -c hugo -d 'Import from Jekyll'
complete -c hugo -l 'force' -d 'Allow import into non-empty target directory'
complete -c hugo -s 'h' -l 'help' -d 'Help for jekyll'
complete -c hugo -d 'List various types of content'
complete -c hugo -s 'h' -l 'help' -d 'Help for list'
complete -c hugo -s 's' -l 'source' -d 'Source directory'
complete -c hugo -d 'List all drafts'
complete -c hugo -s 'h' -l 'help' -d 'Help for drafts'
complete -c hugo -d 'List all expired posts'
complete -c hugo -s 'h' -l 'help' -d 'Help for expired'
complete -c hugo -d 'List all posts dated in the future'
complete -c hugo -s 'h' -l 'help' -d 'Help for future'
complete -c hugo -d 'Create new content'
complete -c hugo -l 'editor' -d 'Editor to use'
complete -c hugo -s 'h' -l 'help' -d 'Help for new'
complete -c hugo -s 'k' -l 'kind' -d 'Content type to create'
complete -c hugo -s 's' -l 'source' -d 'Source directory'
complete -c hugo -d 'Create a new site'
complete -c hugo -l 'force' -d 'Create site inside non-empty directory'
complete -c hugo -s 'f' -l 'format' -d 'Config and front matter format'
complete -c hugo -s 'h' -l 'help' -d 'Help for site'
complete -c hugo -d 'Create a new theme'
complete -c hugo -s 'h' -l 'help' -d 'Help for theme'
complete -c hugo -d 'Start high performance web server'
complete -c hugo -l 'appendPort' -d 'Append port to baseurl'
complete -c hugo -l 'bind' -d 'Interface to which the server will bind'
complete -c hugo -l 'disableFastRender' -d 'Enable full re-renders on changes'
complete -c hugo -l 'disableLiveReload' -d 'Watch without enabling live browser reload on rebuild'
complete -c hugo -s 'h' -l 'help' -d 'Help for server'
complete -c hugo -l 'liveReloadPort' -d 'Port for live reloading'
complete -c hugo -l 'meminterval' -d 'Interval to poll memory usage'
complete -c hugo -l 'memstats' -d 'Memory usage log file'
complete -c hugo -l 'navigateToChanged' -d 'Navigate to changed content file on live browser reload'
complete -c hugo -l 'noHTTPCache' -d 'Prevent HTTP caching'
complete -c hugo -s 'p' -l 'port' -d 'Port on which the server will listen'
complete -c hugo -l 'renderToDisk' -d 'Render to destination directory'
complete -c hugo -d 'Reset the content draft status'
complete -c hugo -s 'h' -l 'help' -d 'Help for undraft'
complete -c hugo -d 'Print the version number of Hugo'
complete -c hugo -s 'h' -l 'help' -d 'Help for version'
