complete -c hwinfo -l 'short' -d 'Show only a summary'
complete -c hwinfo -l 'listmd' -d 'Report RAID devices'
complete -c hwinfo -l 'only' -d 'Show only entries in the device list matching DEVNAME'
complete -c hwinfo -l 'save-config' -d 'Store config for a particular device'
complete -c hwinfo -l 'show-config' -d 'Show saved config data'
complete -c hwinfo -l 'map' -d 'Prints a list of disk name mappings'
complete -c hwinfo -l 'debug' -d 'Set debug level'
complete -c hwinfo -l 'verbose' -d 'Increase verbosity'
complete -c hwinfo -l 'log' -d 'Write log'
complete -c hwinfo -l 'dump-db' -d 'Dump hardware database'
complete -c hwinfo -l 'version' -d 'Show libhd version'
complete -c hwinfo -l 'help' -d 'Show help message'
