complete -c ibus -d 'Set or get engine'
complete -c ibus -d 'Exit ibus-daemon'
complete -c ibus -d 'Show available engines'
complete -c ibus -d 'Restart ibus-daemon'
complete -c ibus -d 'Show version'
complete -c ibus -d 'Show the content of registry cache'
complete -c ibus -d 'Create registry cache'
complete -c ibus -d 'Print the D-Bus address of ibus-daemon'
complete -c ibus -d 'Show the configuration values'
complete -c ibus -d 'Reset the configuration values'
complete -c ibus -d 'Save emoji on dialog to clipboard'
