complete -c identify -d 'Remove pixel-aliasing'
complete -c identify -d 'Decrypt image with this password [value]'
complete -c identify -d 'Apply option to select image channels [type]'
complete -c identify -d 'Cut out a rectangular region of the image [geometry]'
complete -c identify -d 'Define one or more image format options [format:option]'
complete -c identify -d 'Horizontal and vertical density of the image [geometry]'
complete -c identify -d 'Image depth [value]'
complete -c identify -d 'Extract area from image [geometry]'
complete -c identify -d 'Display image features [distance]'
complete -c identify -d 'Output formatted image characteristics ["string"]'
complete -c identify -d 'Colors within this distance are considered equal [distance]'
complete -c identify -d 'Type of image interlacing scheme [type]'
complete -c identify -d 'Pixel color interpolation method [method]'
complete -c identify -d 'Pixel cache resource limit [type value]'
complete -c identify -d 'Print a list of supported option arguments [type]'
complete -c identify -d 'Store matte channel if the image has one'
complete -c identify -d 'Monitor progress'
complete -c identify -d 'Efficiently determine image attributes'
complete -c identify -d 'Suppress all warning messages'
complete -c identify -d 'Pay attention to warning messages'
complete -c identify -d 'Horizontal and vertical sampling factor [geometry]'
complete -c identify -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c identify -d 'Attribute set an image attribute [value]'
complete -c identify -d 'Width and height of image [geometry]'
complete -c identify -d 'Strip image of all profiles and comments'
complete -c identify -d 'Display the number of unique colors in the image'
complete -c identify -d 'The units of image resolution [type]'
complete -c identify -d 'Print detailed information about the image'
complete -c identify -d 'Virtual pixel access method [method]'
complete -c identify -d 'Replace each pixel with its complementary color'
complete -c identify -d 'Display copious debugging information [events]'
complete -c identify -d 'Print program options'
complete -c identify -d 'Format of debugging information [format]'
