complete -c ifdata -d 'Reports interface existence via return code'
complete -c ifdata -d 'Print out the whole config of iface'
complete -c ifdata -d 'Print out yes or no according to existence'
complete -c ifdata -d 'Print out the address'
complete -c ifdata -d 'Print netmask'
complete -c ifdata -d 'Print network address'
complete -c ifdata -d 'Print broadcast'
complete -c ifdata -d 'Print mtu'
complete -c ifdata -d 'Print out the hardware address'
complete -c ifdata -d 'Print flags'
complete -c ifdata -d 'Print all statistics on input'
complete -c ifdata -d 'Print # of in packets'
complete -c ifdata -d 'Print # of in bytes'
complete -c ifdata -d 'Print # of in errors'
complete -c ifdata -d 'Print # of in drops'
complete -c ifdata -d 'Print # of in fifo overruns'
complete -c ifdata -d 'Print # of in compress'
complete -c ifdata -d 'Print # of in multicast'
complete -c ifdata -d 'Print all statistics on output'
complete -c ifdata -d 'Print # of out packets'
complete -c ifdata -d 'Print # of out bytes'
complete -c ifdata -d 'Print # of out errors'
complete -c ifdata -d 'Print # of out drops'
complete -c ifdata -d 'Print # of out fifo overruns'
complete -c ifdata -d 'Print # of out collisions'
complete -c ifdata -d 'Print # of out carrier loss'
complete -c ifdata -d 'Print # of out multicast'
complete -c ifdata -d 'Print # of incoming bytes per second'
complete -c ifdata -d 'Print # of outgoing bytes per second'
