complete -c iftop -s 'h' -d 'Print a summary of usage'
complete -c iftop -s 'n' -d 'Don'"'"'t do hostname lookups'
complete -c iftop -s 'N' -d 'Don'"'"'t resolve port number to service names'
complete -c iftop -s 'p' -d 'Run in promiscuous mode'
complete -c iftop -s 'P' -d 'Turn on port display'
complete -c iftop -s 'l' -d 'Include link-local IPv6 addresses'
complete -c iftop -s 'b' -d 'Don'"'"'t display bar graphs of traffic'
complete -c iftop -s 'm' -d 'Set the upper limit for the bandwidth scale'
complete -c iftop -s 'B' -d 'Show bandwidth rates in bytes/s rather than bits/s'
complete -c iftop -s 'i' -d 'Listen to packets on interface'
complete -c iftop -s 'f' -d 'Use filter code to select the packets to count'
complete -c iftop -s 'F' -d 'Filter to only specified IPv4 network'
complete -c iftop -s 'G' -d 'Filter to only specified IPv6 network'
complete -c iftop -s 'c' -d 'Use specified config file'
complete -c iftop -s 'o' -d 'Sort by specified column'
complete -c iftop -s 't' -d 'Use text interface without ncurses'
complete -c iftop -s 'L' -d 'Number of lines to print with -t'
complete -c iftop -s 's' -d 'With -t, print single output after specific number of seconds'
