complete -c ilasm -l 'help' -d 'Show help and exit'
complete -c ilasm -l 'version' -d 'Show version and exit'
complete -c ilasm -d 'Specify the output file name'
complete -c ilasm -d 'Generate an exe'
complete -c ilasm -d 'Just scan the IL code and display tokens'
complete -c ilasm -d 'Show tokens as they are parsed'
complete -c ilasm -d 'Display method information when a method is defined'
complete -c ilasm -d 'Display method information when a method is referenced'
complete -c ilasm -d 'Strongname (sign) the output assembly using the key pair'
