complete -c import -d 'Join images into a single multi-image file'
complete -c import -d 'Include window border in the output image'
complete -c import -d 'Apply option to select image channels [type]'
complete -c import -d 'Alternate image colorspace [type]'
complete -c import -d 'Annotate image with comment [string]'
complete -c import -d 'Type of pixel compression when writing the image [type]'
complete -c import -d 'Define one or more image format options [format:option]'
complete -c import -d 'Horizontal and vertical density of the image [geometry]'
complete -c import -d 'Image depth [value]'
complete -c import -d 'Obtain image by descending window hierarchy'
complete -c import -d 'X server to contact [server]'
complete -c import -d 'Layer disposal method [method]'
complete -c import -d 'Apply error diffusion to image [method]'
complete -c import -d 'Display the next image after pausing [value]'
complete -c import -d 'Convert plain pixels to cipher pixels [filename]'
complete -c import -d 'Endianness (MSB or LSB) of the image [type]'
complete -c import -d 'Encoding type [type text]'
complete -c import -d 'Use this filter when resizing an image [type]'
complete -c import -d 'Output formatted image characteristics ["string"]'
complete -c import -d 'Include window manager frame'
complete -c import -d 'Direction which direction to gravitate towards'
complete -c import -d 'Identify the format and characteristics of the image'
complete -c import -d 'None, Line, Plane, or Partition [type]'
complete -c import -d 'Pixel color interpolation method [method]'
complete -c import -d 'Assign a label to an image [string]'
complete -c import -d 'Area, Disk, Map, or Memory resource limit [type value]'
complete -c import -d 'Monitor progress'
complete -c import -d 'Size and location of an image canvas [geometry]'
complete -c import -d 'Seconds delay between snapshots [value]'
complete -c import -d 'Font point size [value]'
complete -c import -d 'JPEG/MIFF/PNG compression level [value]'
complete -c import -d 'Suppress all warning messages'
complete -c import -d 'Pay attention to warning messages'
complete -c import -d 'Settings remain in effect until parenthesis boundary'
complete -c import -d 'Horizontal and vertical sampling factor [geometry]'
complete -c import -d 'Image scene number [value]'
complete -c import -d 'Select image from root window'
complete -c import -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c import -d 'Set an image property [property value]'
complete -c import -d 'Number of screen snapshots [value]'
complete -c import -d 'Synchronize image to storage device'
complete -c import -d 'Declare the image as modified'
complete -c import -d 'Transparent color [color]'
complete -c import -d 'Color tree depth [value]'
complete -c import -d 'Print detailed information about the image'
complete -c import -d 'Constant, Edge, Mirror, or Tile [method]'
complete -c import -d 'Select window with this id or name [id]'
complete -c import -d 'Annotate the image with text [geometry text]'
complete -c import -d 'Preferred number of colors in the image [value]'
complete -c import -d 'Preferred size and location of the cropped image [geometry]'
complete -c import -d 'Preferred size or location of the image [geometry]'
complete -c import -d 'Print program options'
complete -c import -d 'Transform image to black and white'
complete -c import -d 'Replace every pixel with its complementary color '
complete -c import -d 'Size and location of an image canvas [geometry]'
complete -c import -d 'Reduce colors in this colorspace [colorspace]'
complete -c import -d 'Resize the image [geometry]'
complete -c import -d 'Apply Paeth rotation to the image [degrees]'
complete -c import -d 'Strip image of all profiles and comments'
complete -c import -d 'Create a thumbnail of the image [geometry]'
complete -c import -d 'Make this color transparent within the image [color]'
complete -c import -d 'Trim image edges'
complete -c import -d 'Image type [type]'
complete -c import -d 'Display copious debugging information [events]'
complete -c import -d 'Print a list of supported option arguments [type]'
complete -c import -d 'Format of debugging information [format]'
complete -c import -d 'Print version information'
complete -c import -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
