complete -c ip -s 'h' -l 'human' -d 'Output statistics with human readable values'
complete -c ip -s 'b' -l 'batch' -d 'Read commands from file or stdin'
complete -c ip -l 'force' -d 'Don'"'"'t terminate on errors in batch mode'
complete -c ip -s 'V' -l 'Version' -d 'Print the version'
complete -c ip -s 's' -l 'stats' -d 'Output more information'
complete -c ip -s 'd' -l 'details' -d 'Output more detailed information'
complete -c ip -s 'l' -l 'loops' -d 'Specify maximum number of loops for '"'"'ip addr flush'"'"''
complete -c ip -s 'f' -l 'family' -d 'The protocol family to use'
complete -c ip -s '4' -d 'Short for --family inet'
complete -c ip -s '6' -d 'Short for --family inet6'
complete -c ip -s 'B' -d 'Short for --family bridge'
complete -c ip -s 'M' -d 'Short for --family mpls'
complete -c ip -s '0' -d 'Short for --family link'
complete -c ip -s 'o' -l 'oneline' -d 'Output on one line'
complete -c ip -s 'r' -l 'resolve' -d 'Resolve names and print them instead of addresses'
complete -c ip -s 'n' -l 'netns' -d 'Use specified network namespace'
complete -c ip -s 'a' -l 'all' -d 'Execute command for all objects'
complete -c ip -s 'c' -l 'color' -d 'Configure color output'
complete -c ip -s 't' -l 'timestamp' -d 'Display current time when using monitor'
complete -c ip -l 'tshort' -d 'Like -timestamp, but shorter format'
complete -c ip -l 'rcvbuf' -d 'Set the netlink socket receive buffer size'
complete -c ip -d 'Print human readable rates in IEC units'
complete -c ip -l 'brief' -d 'Print only basic information in a tabular format'
complete -c ip -s 'j' -l 'json' -d 'Output results in JSON'
complete -c ip -s 'p' -l 'pretty' -d 'Output results in pretty JSON'
