complete -c ipset -d 'Create a set identified with SETNAME'
complete -c ipset -d 'Add a given entry to a SET'
complete -c ipset -d 'Delete an entry from a SET'
complete -c ipset -d 'Test whether an entry is in a set'
complete -c ipset -d 'Destroy the specified set or all sets'
complete -c ipset -d 'Destroy the specified set or all sets'
complete -c ipset -d 'a'
complete -c ipset -s '!' -d 'Ignore errors'
complete -c ipset -s 'o' -d 'Output format to the list command'
complete -c ipset -s 'q' -d 'Suppress any output'
complete -c ipset -s 'r' -d 'Enforce name lookup'
complete -c ipset -s 'n' -d 'List just the names of the sets'
complete -c ipset -s 't' -d 'List the set names and headers'
complete -c ipset -s 'f' -d 'Filename instead of stdout'
