complete -c iptables -s 'A' -l 'append' -d 'Append rules to the end of a chain'
complete -c iptables -s 'C' -l 'check' -d 'Check whether a matching rule exists in a chain'
complete -c iptables -s 'D' -l 'delete' -d 'Delete rules from a chain'
complete -c iptables -s 'm' -l 'match' -d 'Specify a match to use'
complete -c iptables -s 'I' -l 'insert' -d 'Insert rules in the beginning of a chain'
complete -c iptables -s 'R' -l 'replace' -d 'Replace a rule in a chain'
complete -c iptables -s 'L' -l 'list' -d 'List all rules in a chain'
complete -c iptables -s 'S' -l 'list-rules' -d 'Print all rules in a chain.'
complete -c iptables -s 'F' -l 'flush' -d 'Delete ALL rules in a chain'
complete -c iptables -s 'Z' -l 'zero' -d 'Zero the packet and byte counters in chains'
complete -c iptables -s 'N' -l 'new-chain' -d 'Create a new user-defined chain by the given name'
complete -c iptables -s 'X' -l 'delete-chain' -d 'Delete the optional user-defined chain specified'
complete -c iptables -s 'P' -l 'policy' -d 'Set the policy for the chain to the given target'
complete -c iptables -s 'E' -l 'rename-chain' -d 'Rename the user specified chain to the user supplied name'
complete -c iptables -s 'h' -d 'Help'
complete -c iptables -s 'p' -l 'protocol' -d 'The protocol of the rule or of the packet to check'
complete -c iptables -s 's' -l 'source' -d 'Source specification'
complete -c iptables -s 'd' -l 'destination' -d 'Destination specification'
complete -c iptables -s 'j' -l 'jump' -d 'Specify the target of a rule'
complete -c iptables -s 'i' -l 'in-interface' -d 'Interface via which a packet was received'
complete -c iptables -s 'o' -l 'out-interface' -d 'Interface via which packet is to be sent'
complete -c iptables -s 'f' -l 'fragment' -d 'Rule only refers to second and further ipv4 fragments'
complete -c iptables -s 'c' -l 'set-counters' -d 'Initialize packet and byte counters of a rule'
complete -c iptables -s 'v' -l 'verbose' -d 'Verbose output'
complete -c iptables -s 'w' -l 'wait' -d 'Wait for the xtables lock'
complete -c iptables -s 'n' -l 'numeric' -d 'Numeric output'
complete -c iptables -s 'x' -l 'exact' -d 'Expand numbers'
complete -c iptables -l 'line-numbers' -d 'When listing rules, add line numbers'
complete -c iptables -s 't' -l 'table' -d 'The table to operate on'
complete -c iptables -l 'modprobe' -d 'Use this command to load modules'
