complete -c iwctl -s 'h' -l 'help'
complete -c iwctl -s 'p' -l 'password'
complete -c iwctl -s 'u' -l 'username'
complete -c iwctl -s 'P' -l 'passphrase'
complete -c iwctl -s 'v' -l 'dont-ask' -d 'Don'"'"'t ask for missing credentials'
complete -c iwctl -d 'List devices in Ad-Hoc mode'
complete -c iwctl -d 'Start or join an Ad-Hoc network'
complete -c iwctl -d 'Start of join an open Ad-Hoc network'
complete -c iwctl -d 'Leave an Ad-Hoc network'
complete -c iwctl -d 'List adapters'
complete -c iwctl -d 'Show adapter info'
complete -c iwctl -d 'Set property'
complete -c iwctl -d 'List devices in AP mode'
complete -c iwctl -d 'Start an access point'
complete -c iwctl -d 'Start an access point based on a disk profile'
complete -c iwctl -d 'Stop a started access point'
complete -c iwctl -d 'Show AP info'
complete -c iwctl -d 'Get network list after scanning'
complete -c iwctl -d 'Connect to a specific BSS'
complete -c iwctl -d 'Roam to a BSS'
complete -c iwctl -d 'Get networks'
complete -c iwctl -d 'Set autoconnect property'
complete -c iwctl -d 'Set autoconnect property'
complete -c iwctl -d 'List devices'
complete -c iwctl -d 'Show device info'
complete -c iwctl -d 'Set property'
complete -c iwctl -d 'List DPP-capable devices'
complete -c iwctl -d 'Starts a DPP Enrollee'
complete -c iwctl -d 'Starts a DPP Configurator'
complete -c iwctl -d 'Aborts a DPP operations'
complete -c iwctl -d 'Show the DPP state'
complete -c iwctl -d 'List known networks'
complete -c iwctl -d 'Forget a known network'
complete -c iwctl -d 'Show nown network'
complete -c iwctl -d 'Set property'
complete -c iwctl -d 'List devices in Station mode'
complete -c iwctl -d 'Connect to network'
complete -c iwctl -d 'Connect to network'
complete -c iwctl -d 'Connect to hidden network'
complete -c iwctl -d 'Disconnect'
complete -c iwctl -d 'Get networks'
complete -c iwctl -d 'Get hidden APs'
complete -c iwctl -d 'Scan for networks'
complete -c iwctl -d 'Show station info'
complete -c iwctl -d 'List WSC-capable devices'
complete -c iwctl -d 'PushButton Mode'
complete -c iwctl -d 'PIN mode'
complete -c iwctl -d 'PIN mode with generated PIN'
complete -c iwctl -d 'Aborts WSC operations'
