complete -c jbake -l 'bake' -d 'Perform a bake'
complete -c jbake -l 'help' -d 'Print the help message'
complete -c jbake -l 'init' -d 'Initialise the required directory structure with default templates'
complete -c jbake -l 'server' -d 'Run the HTTP server to serve out the baked site'
complete -c jbake -l 'template' -d 'Use the specified template engine for default templates'
