complete -c jhipster -s 'd' -l 'debug' -d 'Enable debugger'
complete -c jhipster -s 'h' -l 'help' -d 'Output usage information'
complete -c jhipster -s 'V' -l 'version' -d 'Output version number'
complete -c jhipster -d 'Create a new JHipster application'
complete -c jhipster -d 'Deploy the current application to AWS'
complete -c jhipster -d 'Create pipeline scripts for popular CI tools'
complete -c jhipster -d 'Create a new JHipster client-side application'
complete -c jhipster -d 'Prepare Cloud Foundry deployment'
complete -c jhipster -d 'Create required Docker deployment configs for applications'
complete -c jhipster -d 'Create a new JHipster entity: JPA, Spring & Angular components'
complete -c jhipster -d 'Create a JDL file from the existing entities'
complete -c jhipster -d 'Deploy the current application to Heroku'
complete -c jhipster -d 'Create entities from the JDL file passed in argument'
complete -c jhipster -d 'Display information about your current project and system'
complete -c jhipster -d 'Deploy the current application to Kubernetes'
complete -c jhipster -d 'Copy i18n files for selected languages to /webapp/i18n'
complete -c jhipster -d 'Deploy the current application to OpenShift'
complete -c jhipster -d 'Deploy the current application to Rancher'
complete -c jhipster -d 'Create a new JHipster server-side application'
complete -c jhipster -d 'Create a new Spring service bean'
complete -c jhipster -d 'Upgrade the JHipster and the generated application'
complete -c jhipster -d 'Print command completion script'
