complete -c john -l 'help' -d 'print usage summary'
complete -c john -l 'single' -d 'single crack mode'
complete -c john -l 'single-seed' -d 'add static seed word(s) for all salts in single mode'
complete -c john -l 'single-wordlist' -d 'short wordlist with static seed words/morphemes'
complete -c john -l 'single-user-seed' -d 'wordlist with seeds per username'
complete -c john -l 'single-retest-guess' -d 'enable SingleRetestGuess'
complete -c john -l 'no-single-retest-guess' -d 'disable SingleRetestGuess'
complete -c john -l 'single-pair-max' -d 'max. number of word pairs generated'
complete -c john -l 'no-single-pair' -d 'disable single word pair generation'
complete -c john -l 'wordlist' -d 'read wordlist from file'
complete -c john -l 'stdin' -d 'read wordlist from stdin'
complete -c john -l 'pipe' -d 'read wordlist from stdin but with bulk reads and allows rules'
complete -c john -l 'mem-file-size' -d 'size threshold for wordlist preload'
complete -c john -l 'loopback' -d 'parse .pot file as a wordlist'
complete -c john -l 'dupe-suppression' -d 'suppress all dupes in wordlist'
complete -c john -l 'prince' -d 'PRINCE mode, read words from file'
complete -c john -l 'prince-loopback' -d 'PRINCE mode, fetch words from a .pot file'
complete -c john -l 'prince-elem-cnt-min' -d 'minimum number of elements per chain'
complete -c john -l 'prince-elem-cnt-max' -d 'maximum number of elements per chain'
complete -c john -l 'prince-skip' -d 'initial skip'
complete -c john -l 'prince-limit' -d 'limit number of candidates generated'
complete -c john -l 'prince-wl-dist-len' -d 'calculate length distribution from wordlist'
complete -c john -l 'prince-wl-max' -d 'load only N words from input wordlist'
complete -c john -l 'prince-case-permute' -d 'permute case of first letter'
complete -c john -l 'prince-mmap' -d 'memory-map infile'
complete -c john -l 'prince-keyspace' -d 'just show total keyspace that would be produced'
complete -c john -l 'encoding' -l 'input-encoding' -d 'input encoding'
complete -c john -l 'rules' -d 'enable word mangling rules'
complete -c john -l 'rules-stack' -d 'stacked rules'
complete -c john -l 'rules-skip-nop' -d 'skip any NOP rules'
complete -c john -l 'incremental' -d 'incremental mode'
complete -c john -l 'incremental-charcount' -d 'override CharCount for incremental mode'
complete -c john -l 'mask' -d 'mask mode'
complete -c john -l 'markov' -d 'Markov mode'
complete -c john -l 'mkv-stats' -d 'markov stats file'
complete -c john -l 'external' -d 'external mode or word filter'
complete -c john -l 'subsets' -d 'subsets mode'
complete -c john -l 'subsets-required' -d 'The N first characters of subsets charset are the required set'
complete -c john -l 'subsets-min-diff' -d 'Minimum unique characters in subset'
complete -c john -l 'subsets-max-diff' -d 'Maximum unique characters in subset'
complete -c john -l 'stdout' -d 'just output candidate passwords'
complete -c john -l 'restore' -d 'restore an interrupted session'
complete -c john -l 'session' -d 'give a new session a name'
complete -c john -l 'status' -d 'print status of a session'
complete -c john -l 'make-charset' -d 'make a charset file'
complete -c john -l 'reject-printable' -d 'reject printable binaries'
complete -c john -l 'test' -d 'run tests and benchmarks for TIME seconds each'
complete -c john -l 'stress-test' -d 'loop self tests forever'
complete -c john -l 'no-mask' -d 'used with --test for alternate benchmark w/o mask'
complete -c john -l 'skip-self-tests' -d 'skip self tests'
complete -c john -l 'test-full' -d 'run more thorough self-tests'
complete -c john -l 'users' -d 'load or don'"'"'t load these users only'
complete -c john -l 'groups' -d 'load users in or not in these groups only'
complete -c john -l 'shells' -d 'load users with or without these shells only'
complete -c john -l 'salts' -d 'load salts'
complete -c john -l 'costs' -d 'load salts with or without cost value'
complete -c john -l 'save-memory' -d 'enable memory saving'
complete -c john -l 'node' -d 'this node'"'"'s number range out of TOTAL count'
complete -c john -l 'subformat' -d 'pick a benchmark format for --format=crypt'
complete -c john -l 'mkpc' -d 'request a lower max. keys per crypt'
complete -c john -l 'min-length' -d 'request a minimum candidate length in bytes'
complete -c john -l 'max-length' -d 'request a maximum candidate length in bytes'
complete -c john -l 'length' -d 'shortcut for --min-len=N --max-len=N'
complete -c john -l 'field-separator-char' -d 'use custom character instead of '"'"':'"'"' in input and pot files'
complete -c john -l 'config' -d 'use custom file instead of john.conf or john.ini'
complete -c john -l 'log-stderr' -d 'log to screen instead of file'
complete -c john -l 'no-loader-dupecheck' -d 'disable the dupe checking when loading hashes'
complete -c john -l 'verbosity' -d 'change verbosity'
complete -c john -l 'no-log' -d 'disables creation and writing to john.log file'
complete -c john -l 'bare-always-valid' -d 'treat bare hashes as valid'
complete -c john -l 'progress-every' -d 'emit a status line every N seconds'
complete -c john -l 'crack-status' -d 'emit a status line whenever a password is cracked'
complete -c john -l 'no-crack-status' -d 'don'"'"'t emit a status line whenever a password is cracked'
complete -c john -l 'keep-guessing' -d 'try finding plaintext collisions'
complete -c john -l 'no-keep-guessing' -d 'don'"'"'t try finding plaintext collisions'
complete -c john -l 'max-candidates' -d 'gracefully exit after this many candidates tried'
complete -c john -l 'max-run-time' -d 'gracefully exit after this many seconds'
complete -c john -l 'regen-lost-salts' -d 'brute force unknown salts'
complete -c john -l 'fork' -d 'fork N processes'
complete -c john -l 'pot' -d 'pot file to use'
complete -c john -l 'list' -d 'list capabilities'
complete -c john -l 'internal-codepage' -d 'codepage used in rules/masks'
complete -c john -l 'target-encoding' -d 'output encoding'
complete -c john -l 'tune' -d 'tuning options'
complete -c john -l 'force-tty' -d 'set up terminal for reading keystrokes'
complete -c john -l 'format' -d 'force hash type'
