complete -c journalctl -d 'Journal field'
complete -c journalctl -d 'Executable'
complete -c journalctl -d 'OR'
complete -c journalctl -s 'h' -l 'help' -d 'Prints a short help text and exits'
complete -c journalctl -l 'version' -d 'Prints a short version string and exits'
complete -c journalctl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c journalctl -s 'a' -l 'all' -d 'Show all fields in full'
complete -c journalctl -s 'f' -l 'follow' -d 'Show live tail of entries'
complete -c journalctl -s 'n' -l 'lines' -d 'Controls the number of journal lines'
complete -c journalctl -l 'no-tail' -d 'Show all lines, even in follow mode'
complete -c journalctl -s 'o' -l 'output' -d 'Controls the formatting'
complete -c journalctl -s 'q' -l 'quiet' -d 'Suppress warning about normal user'
complete -c journalctl -s 'm' -l 'merge' -d 'Show entries interleaved from all journals'
complete -c journalctl -l 'this-boot' -d 'Show data only from the current boot'
complete -c journalctl -s 'b' -l 'boot' -d 'Show data only from a certain boot'
complete -c journalctl -s 'u' -l 'unit' -d 'Show data only of the specified unit'
complete -c journalctl -s 'p' -l 'priority' -d 'Filter by priority'
complete -c journalctl -s 'c' -l 'cursor' -d 'Start from the passing cursor'
complete -c journalctl -l 'since' -d 'Entries on or newer than DATE'
complete -c journalctl -l 'until' -d 'Entries on or older than DATE'
complete -c journalctl -s 'F' -l 'field' -d 'Print all possible data values of FIELD'
complete -c journalctl -s 'D' -l 'directory' -d 'Specify journal directory'
complete -c journalctl -l 'new-id128' -d 'Generate a new 128 bit ID'
complete -c journalctl -l 'header' -d 'Show internal header information'
complete -c journalctl -l 'disk-usage' -d 'Shows the current disk usage'
complete -c journalctl -l 'setup-keys' -d 'Generate Forward Secure Sealing key pair'
complete -c journalctl -l 'interval' -d 'Change interval for the sealing'
complete -c journalctl -l 'verify' -d 'Check journal for internal consistency'
complete -c journalctl -l 'verify-key' -d 'Specifies FSS key for --verify'
complete -c journalctl -s 'r' -l 'reverse' -d 'Reverse output to show newest entries first'
complete -c journalctl -l 'utc' -d 'Express time in Coordinated Universal Time (UTC)'
complete -c journalctl -l 'no-hostname' -d 'Don'"'"'t show the hostname field'
complete -c journalctl -s 'x' -l 'catalog' -d 'Augment log lines with explanation texts from the message catalog'
complete -c journalctl -l 'list-boots' -d 'Show a list of boot numbers, their IDs and timestamps'
complete -c journalctl -s 'k' -l 'dmesg' -d 'Show only kernel messages'
complete -c journalctl -s 'N' -l 'fields' -d 'Print all field names used in all entries of the journal'
complete -c journalctl -l 'update-catalog' -d 'Update the message catalog index'
complete -c journalctl -l 'sync' -d 'Write all unwritten journal data and sync journals'
complete -c journalctl -l 'flush' -d 'Flush log data from /run/log/journal/ into /var/log/journal/'
complete -c journalctl -l 'relinquish-var' -d 'Write to /run/log/journal/ instead of /var/log/journal/'
complete -c journalctl -l 'smart-relinquish-var' -d 'Similar to --relinquish-var'
complete -c journalctl -l 'rotate' -d 'Mark active journal files as archived and create new empty ones'
complete -c journalctl -l 'output-fields' -d 'List of fields to be included in the output'
complete -c journalctl -s 't' -l 'identifier' -d 'Show messages for specified syslog identifier'
complete -c journalctl -l 'user-unit' -d 'Show messages for the specified user session unit'
complete -c journalctl -l 'facility' -d 'Filter output by syslog facility'
complete -c journalctl -s 'g' -l 'grep' -d 'Show entries where MESSAGE field matches regex'
complete -c journalctl -l 'case-sensitive' -d 'Toggle pattern matching case sensitivity'
complete -c journalctl -l 'cursor-file' -d 'Load cursor from file or save to file, if missing'
complete -c journalctl -l 'after-cursor' -d 'Show entries after the passed cursor'
complete -c journalctl -l 'show-cursor' -d 'Show cursor after the last entry'
complete -c journalctl -l 'user' -d 'Show messages from service of current user'
complete -c journalctl -l 'system' -d 'Show messages from system services and the kernel'
complete -c journalctl -s 'M' -l 'machine' -d 'Show messages from a running, local container'
complete -c journalctl -l 'file' -d 'Operate only on journal files matching glob'
complete -c journalctl -l 'root' -d 'Use specified directory instead of the root directory'
complete -c journalctl -l 'namespace' -d 'Show log data of specified namespace'
complete -c journalctl -l 'vacuum-size' -d 'Reduce disk usage below specified SIZE'
complete -c journalctl -l 'vacuum-time' -d 'Remove journal files older than TIME'
complete -c journalctl -l 'vacuum-files' -d 'Leave only INT number of journal files'
complete -c journalctl -l 'list-catalog' -d 'Show message catalog entries as a table'
complete -c journalctl -l 'dump-catalog' -d 'Show message catalog entries'
