complete -c k3d -s 'h' -l 'help' -d 'More information about a command'
complete -c k3d -l 'version' -d 'Show k3d and default k3s version'
complete -c k3d -d 'Manage cluster(s)'
complete -c k3d -d 'Show k3d and default k3s version'
complete -c k3d -d 'Handle container images'
complete -c k3d -d 'Manage kubeconfig(s)'
complete -c k3d -d 'Manage node(s)'
complete -c k3d -d 'Create a new cluster'
complete -c k3d -d 'List cluster(s)'
complete -c k3d -d 'Delete cluster(s)'
complete -c k3d -d 'Start existing k3d cluster(s)'
complete -c k3d -d 'Stop existing k3d cluster(s)'
complete -c k3d -d 'Cluster'
complete -c k3d -s 'h' -l 'help' -d 'Print usage'
complete -c k3d -d 'Import image(s) from docker into k3d cluster(s)'
complete -c k3d -d 'Print usage'
complete -c k3d -s 'h' -l 'help' -d 'Print usage'
complete -c k3d -d 'Get kubeconfig from cluster(s)'
complete -c k3d -d 'Merge/write kubeconfig(s) from cluster(s) into existing kubeconfig/file'
complete -c k3d -d 'Cluster'
complete -c k3d -s 'a' -l 'all' -d 'Get kubeconfig from all existing clusters'
complete -c k3d -s 'h' -l 'help' -d 'Print usage'
complete -c k3d -d 'Create a new k3s node in docker'
complete -c k3d -d 'Delete node(s)'
complete -c k3d -d 'List node(s)'
complete -c k3d -d 'Start an existing k3d node'
complete -c k3d -d 'Stop an existing k3d node'
complete -c k3d -d 'Node'
complete -c k3d -s 'h' -l 'help' -d 'Print usage'
