complete -c kak -d 'connect to given session'
complete -c kak -d 'execute argument on client initialisation'
complete -c kak -d 'execute argument on server initialisation'
complete -c kak -d 'do not source kakrc files on startup'
complete -c kak -d 'set session name'
complete -c kak -d 'run as a headless session (requires -s)'
complete -c kak -d 'just send stdin as commands to the given session'
complete -c kak -d 'filter: for each file, select the entire buffer and execute the given keys'
complete -c kak -d 'backup the files on which a filter is applied using the given suffix'
complete -c kak -d 'in filter mode be quiet about errors applying keys'
complete -c kak -d 'set the type of user interface to use'
complete -c kak -d 'list existing sessions'
complete -c kak -d 'clear dead sessions'
complete -c kak -d 'initial debug option value'
complete -c kak -d 'display kakoune version and exit'
complete -c kak -d 'readonly mode'
complete -c kak -d 'display a help message and quit'
