complete -c kcmshell5 -l 'list' -d 'List available modules'
complete -c kcmshell5 -l 'author' -d 'Show author information'
complete -c kcmshell5 -l 'license' -d 'Show license information'
complete -c kcmshell5 -l 'lang' -d 'Set a language'
complete -c kcmshell5 -l 'silent' -d 'Don'"'"'t show main window'
complete -c kcmshell5 -l 'args' -d 'Arguments to the module'
complete -c kcmshell5 -l 'icon' -d 'Icon for the module'
complete -c kcmshell5 -l 'caption' -d 'Title for the window'
complete -c kcmshell5 -l 'version' -s 'v' -d 'Show version information and exit'
complete -c kcmshell5 -l 'help' -s 'h' -d 'Show help information and exit'
