complete -c keepassxc-cli -l 'debug-info' -d 'Show debug info'
complete -c keepassxc-cli -s 'k' -l 'key-file' -d 'Specify a key file'
complete -c keepassxc-cli -l 'no-password' -d 'Deactivate the password key'
complete -c keepassxc-cli -s 'y' -l 'yubikey' -d 'Specify a yubikey slot'
complete -c keepassxc-cli -s 'q' -l 'quiet' -d 'Be quiet'
complete -c keepassxc-cli -s 'h' -l 'help' -d 'Show help info'
complete -c keepassxc-cli -s 'v' -l 'version' -d 'Show version info'
complete -c keepassxc-cli -d 'Add a new entry'
complete -c keepassxc-cli -d 'Analyze password for weakness and problem'
complete -c keepassxc-cli -d 'Copy an entry'"'"'s password to the clipboard'
complete -c keepassxc-cli -d 'Close the currently opened database'
complete -c keepassxc-cli -d 'Create new database'
complete -c keepassxc-cli -d 'Generate a new random diceware passphrase'
complete -c keepassxc-cli -d 'Edit an entry'
complete -c keepassxc-cli -d 'Estimate the entropy of a password'
complete -c keepassxc-cli -d 'Exit interactive mode'
complete -c keepassxc-cli -d 'Export the contents to stdout'
complete -c keepassxc-cli -d 'Generate a new password'
complete -c keepassxc-cli -d 'Show command help'
complete -c keepassxc-cli -d 'Import the contents'
complete -c keepassxc-cli -d 'Find entries quickly'
complete -c keepassxc-cli -d 'List database entries'
complete -c keepassxc-cli -d 'Merge two databases'
complete -c keepassxc-cli -d 'Add a new group'
complete -c keepassxc-cli -d 'Move an entry'
complete -c keepassxc-cli -d 'Open a database'
complete -c keepassxc-cli -d 'Exit interactive mode'
complete -c keepassxc-cli -d 'Remove an entry'
complete -c keepassxc-cli -d 'Remove a group'
complete -c keepassxc-cli -d 'Show an entry'"'"'s info'
complete -c keepassxc-cli -s 'd' -l 'dry-run' -d 'Dry run'
complete -c keepassxc-cli -l 'key-file-from' -d 'Key file to merge from'
complete -c keepassxc-cli -l 'no-password-from' -d 'Deactivate the password key to merge from'
complete -c keepassxc-cli -l 'yubikey-from' -d 'Yubikey slot for the second database'
complete -c keepassxc-cli -s 's' -l 'same-credentials' -d 'Use the same credentials for both databases'
complete -c keepassxc-cli -s 'u' -l 'username' -d 'Username for the entry'
complete -c keepassxc-cli -l 'url' -d 'URL for the entry'
complete -c keepassxc-cli -l 'password-prompt' -d 'Prompt for the entry'"'"'s password'
complete -c keepassxc-cli -s 'g' -l 'generate' -d 'Generate a password for the entry'
complete -c keepassxc-cli -s 't' -l 'title' -d 'Title for the entry'
complete -c keepassxc-cli -s 'a' -l 'advanced' -d 'Perform advanced analysis on the password'
complete -c keepassxc-cli -s 'H' -l 'hibp' -d 'Check if any passwords have been publicly leaked'
complete -c keepassxc-cli -s 't' -l 'totp' -d 'Copy the current TOTP to the clipboard'
complete -c keepassxc-cli -s 'a' -l 'attributes' -d 'Names of the attributes to show'
complete -c keepassxc-cli -s 's' -l 'show-protected' -d 'Show the protected attributes in clear text'
complete -c keepassxc-cli -s 't' -l 'totp' -d 'Show the entry'"'"'s current TOTP'
complete -c keepassxc-cli -s 'W' -l 'words' -d 'Word count for the diceware passphrase'
complete -c keepassxc-cli -s 'w' -l 'word-list' -d 'Wordlist for the diceware generator'
complete -c keepassxc-cli -s 'f' -l 'format' -d 'Format to use when exporting'
complete -c keepassxc-cli -s 'R' -l 'recursive' -d 'Recursively list the elements of the group'
complete -c keepassxc-cli -s 'f' -l 'flatten' -d 'Flattens the output to single line'
complete -c keepassxc-cli -s 'L' -l 'length' -d 'Length of the generated password'
complete -c keepassxc-cli -s 'l' -l 'lower' -d 'Use lowercase chars'
complete -c keepassxc-cli -s 'U' -l 'upper' -d 'Use uppercase chars'
complete -c keepassxc-cli -s 'n' -l 'numeric' -d 'Use numbers'
complete -c keepassxc-cli -s 's' -l 'special' -d 'Use special chars'
complete -c keepassxc-cli -s 'e' -l 'extended' -d 'Use extended ASCII'
complete -c keepassxc-cli -s 'x' -l 'exclude' -d 'Exclude char set'
complete -c keepassxc-cli -l 'exclude-similar' -d 'Exclude similar looking chars'
complete -c keepassxc-cli -l 'every-group' -d 'Include chars from every selected group'
