complete -c kitchen -d 'Describe available commands or one specific command'
complete -c kitchen -d 'Describe available commands or one specific command'
complete -c kitchen -d 'Lists one or more instances'
complete -c kitchen -s 'b' -l 'bare' -d 'List the name of each instance only, one per line'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -d 'Lists one or more instances'
complete -c kitchen -d 'Show computed diagnostic configuration'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -l 'loader' -d 'Include data loader diagnostics'
complete -c kitchen -l 'instances' -d 'Include instances diagnostics'
complete -c kitchen -l 'all' -d 'Include all diagnostics'
complete -c kitchen -d 'Show computed diagnostic configuration'
complete -c kitchen -d 'Change instance state to create. Start one or more instances'
complete -c kitchen -s 'c' -l 'concurrency' -d 'Run concurrently, give number for max instances'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -d 'Change instance state to create. Start one or more instances'
complete -c kitchen -d 'Change instance state to converge. Use a provisioner to configure one or more instances'
complete -c kitchen -s 'c' -l 'concurrency' -d 'Run converge concurrently, give number for max instances'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -d 'Change instance state to converge. Use a provisioner to configure one or more instances'
complete -c kitchen -d 'Change instance state to setup. Prepare to run automated tests. Install busser'
complete -c kitchen -s 'c' -l 'concurrency' -d 'Run concurrently, give number for max instances'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -d 'Change instance state to setup. Prepare to run automated tests. Install busser'
complete -c kitchen -d 'Change instance state to verify. Run automated tests'
complete -c kitchen -s 'c' -l 'concurrency' -d 'Run concurrently, give number for max instances'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -d 'Change instance state to verify. Run automated tests'
complete -c kitchen -d 'Change instance state to destroy. Delete all information for one or more instances'
complete -c kitchen -s 'c' -l 'concurrency' -d 'Run concurrently, give number for max instances'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -d 'Change instance state to destroy. Delete all information for one or more instances'
complete -c kitchen -d 'Test (destroy, create, converge, setup, verify and destroy) one or more instances'
complete -c kitchen -s 'c' -l 'concurrency' -d 'Run concurrently, give number for max instances'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -s 'd' -l 'destroy' -d 'Destroy strategy to use after testing (passing, always, never).'
complete -c kitchen -l 'auto_init' -d 'Invoke init command if .kitchen.yml is missing'
complete -c kitchen -d 'Test (destroy, create, converge, setup, verify and destroy) one or more instances'
complete -c kitchen -d 'Log in to one instance'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -d 'Log in to one instance'
complete -c kitchen -d 'Execute command on one or more instance'
complete -c kitchen -s 'l' -l 'log_level' -d 'Set the log level (debug, info, warn, error, fatal)'
complete -c kitchen -s 'c' -l 'command' -d 'execute via ssh'
complete -c kitchen -d 'Execute command on one or more instance'
complete -c kitchen -d 'Print Kitchen'"'"'s version information'
complete -c kitchen -d 'Print Kitchen'"'"'s version information'
complete -c kitchen -d 'Show the Kitchen sink!'
complete -c kitchen -d 'Show the Kitchen sink!'
complete -c kitchen -d 'Kitchen Console!'
complete -c kitchen -d 'Kitchen Console!'
complete -c kitchen -d 'Adds some configuration to your cookbook so Kitchen can rock'
complete -c kitchen -s 'D' -l 'driver' -d 'One or more Kitchen Driver gems to be installed or added to a Gemfile '
complete -c kitchen -s 'P' -l 'provisioner' -d 'The default Kitchen Provisioner to use '
complete -c kitchen -l 'create_gemfile' -d 'Whether or not to create a Gemfile if one does not exist. Default: false '
complete -c kitchen -d 'Add some configuration to your cookbook'
complete -c kitchen -d 'Driver subcommands'
complete -c kitchen -d 'Driver subcommands'
