complete -c latexmk -d 'use bibtex when needed (default)'
complete -c latexmk -d 'never use bibtex'
complete -c latexmk -d 'use bibtex when needed, but only if the bib files exist'
complete -c latexmk -d 'Print message across the page when converting to postscript'
complete -c latexmk -d 'Set contrast or intensity of banner'
complete -c latexmk -d 'Set scale for banner'
complete -c latexmk -d 'list commands used by latexmk for processing files'
complete -c latexmk -d 'Delete all nonessential files, except dvi, ps and pdf files'
complete -c latexmk -d 'Delete all nonessential files'
complete -c latexmk -d 'Delete database file information file before other actions'
complete -c latexmk -d 'Change to directory of source file when processing it'
complete -c latexmk -d 'Don'"'"'t change to directory of source file when processing it'
complete -c latexmk -d 'Show list of dependent files after processing'
complete -c latexmk -d 'Do not show list of dependent files'
complete -c latexmk -d 'Set dependency list file name, show dependency list'
complete -c latexmk -d 'Filter to apply to dvi file'
complete -c latexmk -d 'generate dvi'
complete -c latexmk -d 'turn off required dvi'
complete -c latexmk -d 'Execute specified Perl code on start-up'
complete -c latexmk -d 'force continued processing past errors'
complete -c latexmk -d 'turn off forced continuing processing past errors'
complete -c latexmk -d 'Super go mode: clean out generated files before processing'
complete -c latexmk -d 'process regardless of file timestamps'
complete -c latexmk -d 'Turn off -g'
complete -c latexmk -d 'print help'
complete -c latexmk -d 'set basename of output files to STRING'
complete -c latexmk -d 'force landscape mode'
complete -c latexmk -d 'turn off -l'
complete -c latexmk -d 'set program used for latex'
complete -c latexmk -d 'in -pvc mode, always start a new viewer'
complete -c latexmk -d 'in -pvc mode, start a new viewer only if needed'
complete -c latexmk -d 'never use bibtex'
complete -c latexmk -d 'Do not show list of dependent files after processing'
complete -c latexmk -d 'omit automatic reading of system, user and project rc files'
complete -c latexmk -d 'set name of directory for output files'
complete -c latexmk -d 'generate pdf by pdflatex'
complete -c latexmk -d 'generate pdf by dvipdf'
complete -c latexmk -d 'set program used for pdflatex'
complete -c latexmk -d 'generate pdf by ps2pdf'
complete -c latexmk -d 'turn off pdf'
complete -c latexmk -d 'generate postscript'
complete -c latexmk -d 'turn off postscript'
complete -c latexmk -d 'Filter to apply to postscript file'
complete -c latexmk -d 'print document after generating postscript'
complete -c latexmk -d 'when file is to be printed, print the dvi file'
complete -c latexmk -d 'when file is to be printed, print the ps file (default)'
complete -c latexmk -d 'when file is to be printed, print the pdf file'
complete -c latexmk -d 'preview document'
complete -c latexmk -d 'turn off preview mode'
complete -c latexmk -d 'preview document and continuously update'
complete -c latexmk -d 'turn off -pvc'
complete -c latexmk -d 'silence progress messages from called programs'
complete -c latexmk -d 'Read custom RC file'
complete -c latexmk -d 'Use -recorder option for (pdf)latex'
complete -c latexmk -d 'Do not use -recorder option for (pdf)latex'
complete -c latexmk -d 'Show list of rules after processing'
complete -c latexmk -d 'Do not show list of rules after processing'
complete -c latexmk -d 'silence progress messages from called programs'
complete -c latexmk -d 'show CPU time used'
complete -c latexmk -d 'use the make program to try to make missing files'
complete -c latexmk -d 'display program version'
complete -c latexmk -d 'display usual progress messages from called programs'
complete -c latexmk -d 'display program version'
complete -c latexmk -d 'viewer is default (dvi, ps, pdf)'
complete -c latexmk -d 'viewer is for dvi'
complete -c latexmk -d 'no viewer is used'
complete -c latexmk -d 'viewer is for ps'
complete -c latexmk -d 'viewer is for pdf'
