complete -c lein -d 'Check syntax and warn on reflection.'
complete -c lein -d 'Write the classpath of the current project to output-file.'
complete -c lein -d 'Remove all files from project'"'"'s target-path.'
complete -c lein -d 'Compile Clojure source into .class files.'
complete -c lein -d 'Build jar and deploy to remote repository.'
complete -c lein -d 'Show details about dependencies.'
complete -c lein -d 'Higher-order task to perform other tasks in succession.'
complete -c lein -d 'Display a list of tasks or help for a given task or subtask.'
complete -c lein -d 'Install current project to the local repository.'
complete -c lein -d 'Package up all the project'"'"'s files into a jar file.'
complete -c lein -d 'Compile Java source files.'
complete -c lein -d 'Start a Light Table client for this project'
complete -c lein -d 'Generate scaffolding for a new project based on a template.'
complete -c lein -d 'DEPRECATED. Please use the :user profile instead.'
complete -c lein -d 'Write a pom.xml file to disk for Maven interoperability.'
complete -c lein -d 'Start a repl session either with the current project or standalone.'
complete -c lein -d 'Run only the test namespaces which failed last time around.'
complete -c lein -d 'Run the project'"'"'s -main function.'
complete -c lein -d 'Search remote maven repositories for matching jars.'
complete -c lein -d 'List all available profiles or display one if given an argument.'
complete -c lein -d 'Run the project'"'"'s tests.'
complete -c lein -d 'Run a task without nesting the project'"'"'s JVM inside Leiningen'"'"'s.'
complete -c lein -d 'Package up the project files and all dependencies into a jar file.'
complete -c lein -d 'Perform arbitrary transformations on your project map.'
complete -c lein -d 'Upgrade Leiningen to specified version or latest stable.'
complete -c lein -d 'Print version for Leiningen and the current JVM.'
complete -c lein -d 'Apply the given task with the profile(s) specified.'
