complete -c light -s 'h' -d 'Print help and exit'
complete -c light -s 'V' -d 'Print version info and exit'
complete -c light -s 'G' -d 'Get value (default)'
complete -c light -s 'S' -d 'Set value'
complete -c light -s 'A' -d 'Add value'
complete -c light -s 'U' -d 'Subtract value'
complete -c light -s 'L' -d 'List controllers'
complete -c light -s 'I' -d 'Restore brightness'
complete -c light -s 'O' -d 'Save brightness'
complete -c light -s 'b' -d 'Brightness (default)'
complete -c light -s 'm' -d 'Maximum brightness'
complete -c light -s 'c' -d 'Minimum cap'
complete -c light -s 'a' -d 'Selects controller automatically (default)'
complete -c light -s 's' -d 'Specify controller to use'
complete -c light -s 'p' -d 'Interpret & output values in percent'
complete -c light -s 'r' -d 'Interpret & output values in raw mode'
complete -c light -s 'v' -d 'Sets the verbosity level'
