complete -c llm -l 'version' -d 'Show version info'
complete -c llm -l 'help' -d 'Show usage info'
complete -c llm -s 's' -l 'system' -d 'System prompt to use'
complete -c llm -s 'm' -l 'model' -d 'Model to use'
complete -c llm -s 'a' -l 'attachment' -d 'Attachment to use'
complete -c llm -l 'at' -d 'Attachment type'
complete -c llm -l 'attachment-type' -d 'Attachment type'
complete -c llm -s 'n' -l 'no-log' -d 'Don'"'"'t log to db'
complete -c llm -s 'l' -l 'log' -d 'Log prompt/reply to db'
complete -c llm -s 'c' -l 'continue' -d 'Continue most recent conversation'
complete -c llm -l 'key' -d 'API key to use'
complete -c llm -l 'save' -d 'Save prompt as template with name'
