complete -c loadkeys -s 'C' -l 'console' -d 'Console device to use'
complete -c loadkeys -s 'a' -l 'ascii' -d 'Force conversion to ASCII'
complete -c loadkeys -s 'b' -l 'bkeymap' -d 'Output binary keymap'
complete -c loadkeys -s 'c' -l 'clearcompose' -d 'Clear kernel compose table'
complete -c loadkeys -s 'd' -l 'default' -d 'Load default keymap'
complete -c loadkeys -s 'm' -l 'mktable' -d 'Output a '"'"'defkeymap.c'"'"''
complete -c loadkeys -s 'p' -l 'parse' -d 'Only search and parse keymap'
complete -c loadkeys -s 's' -l 'clearstrings' -d 'Clear kernel string table'
complete -c loadkeys -s 'u' -l 'unicode' -d 'Force conversion to Unicode'
complete -c loadkeys -s 'q' -l 'quiet' -d 'Supress all normal output'
complete -c loadkeys -s 'v' -l 'verbose' -d 'Be more verbose'
complete -c loadkeys -s 'V' -l 'version' -d 'Print version number'
complete -c loadkeys -s 'h' -l 'help' -d 'Print help'
