complete -c loginctl -l 'all' -s 'a' -d 'Show all properties, including empty ones'
complete -c loginctl -l 'full' -s 'l' -d 'Do not ellipsize output'
complete -c loginctl -l 'help' -s 'h' -d 'Show this help'
complete -c loginctl -l 'host' -s 'H' -d 'Operate on remote host'
complete -c loginctl -l 'kill-who' -d 'Who to send signal to'
complete -c loginctl -l 'lines' -s 'n' -d 'Number of journal entries to show'
complete -c loginctl -l 'machine' -s 'M' -d 'Operate on local container'
complete -c loginctl -l 'no-ask-password' -d 'Don'"'"'t prompt for password'
complete -c loginctl -l 'no-legend' -d 'Do not show the headers and footers'
complete -c loginctl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c loginctl -l 'output' -s 'o' -d 'Change journal output mode'
complete -c loginctl -l 'property' -s 'p' -d 'Show only properties by this name'
complete -c loginctl -s 'P' -d 'Equivalent to --value --property'
complete -c loginctl -l 'signal' -s 's' -d 'Which signal to send'
complete -c loginctl -l 'value' -d 'When showing properties, only print the value'
complete -c loginctl -l 'version' -d 'Show package version'
