complete -c losetup -s 'a' -l 'all' -d 'List all used devices'
complete -c losetup -s 'd' -l 'detach' -d 'Detach one or more devices'
complete -c losetup -s 'D' -l 'detach-all' -d 'Detach all used devices'
complete -c losetup -s 'f' -l 'find' -d 'Find first unused device'
complete -c losetup -s 'c' -l 'set-capacity' -d 'Resize the device'
complete -c losetup -s 'j' -l 'associated' -d 'List all devices associated with given file'
complete -c losetup -s 'L' -l 'nooverlap' -d 'Avoid possible conflict between devices'
complete -c losetup -s 'o' -l 'offset' -d 'Start at given offset into file'
complete -c losetup -l 'sizelimit' -d 'Device is limited to give bytes of the file'
complete -c losetup -s 'b' -l 'sector-size' -d 'Set the logical sector size'
complete -c losetup -s 'P' -l 'partscan' -d 'Create a partitioned loop device'
complete -c losetup -s 'r' -l 'read-only' -d 'Set up a read-only loop device'
complete -c losetup -l 'direct-io' -d 'open backing file with O_DIRECT'
complete -c losetup -l 'show' -d 'Print device name after setup'
complete -c losetup -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c losetup -s 'J' -l 'json' -d 'Use JSON --list output format'
complete -c losetup -s 'l' -l 'list' -d 'List info about all or specified'
complete -c losetup -s 'n' -l 'noheadings' -d 'Don'"'"'t print headings for --list output'
complete -c losetup -s 'O' -l 'output' -d 'Specify columns to output for --list'
complete -c losetup -l 'output-all' -d 'Output all columns'
complete -c losetup -l 'raw' -d 'Use raw --list output format'
complete -c losetup -s 'h' -l 'help' -d 'Display help'
complete -c losetup -s 'V' -l 'version' -d 'Display version'
