complete -c lpadmin -s 'c' -d 'Adds the named printer to class'
complete -c lpadmin -s 'i' -d 'Sets a  SysV style interface script for printer'
complete -c lpadmin -s 'm' -d 'Sets a standard SysV interface script or PPD file '
complete -c lpadmin -s 'R' -d 'Deletes the named option from printer'
complete -c lpadmin -s 'r' -d 'Removes the named printer from class'
complete -c lpadmin -s 'v' -d 'Sets the device-uri attribute of the printer queue'
complete -c lpadmin -s 'D' -d 'Provides a textual description of the destination'
complete -c lpadmin -s 'E' -d 'Enables the destination and accepts jobs'
complete -c lpadmin -s 'L' -d 'Provides a textual location of the destination'
complete -c lpadmin -s 'P' -d 'Specify a PDD file to use with the printer'
complete -c lpadmin -s 'o' -d 'Specify if IPP supply level values should be reported'
complete -c lpadmin -s 'o' -d 'Specify if IPP supply level values should be reported'
complete -c lpadmin -s 'o' -d 'Specify if SNMP supply level values should be reported'
complete -c lpadmin -s 'o' -d 'Specify if SNMP supply level values should be reported'
complete -c lpadmin -s 'o' -d 'Sets the kilobyte limit for per-user quotas'
complete -c lpadmin -s 'o' -d 'Sets the page limit for per-user quotas (int) '
complete -c lpadmin -s 'o' -d 'Sets the accounting period for per-user quotas (sec)'
complete -c lpadmin -s 'o' -d 'Sets the default banner page(s) to use for print jobs'
complete -c lpadmin -s 'o' -d 'Sets a  PPD option for the printer'
complete -c lpadmin -s 'o' -d 'Set the binary communications program to use'
complete -c lpadmin -s 'o' -d 'Set error policy if printer backend can'"'"'t send job'
complete -c lpadmin -s 'o' -d 'Sets dest to shared/published or unshared/unpublished'
complete -c lpadmin -s 'o' -d 'Sets dest to shared/published or unshared/unpublished'
complete -c lpadmin -s 'o' -d 'Set IPP operation policy associated with dest'
complete -c lpadmin -s 'u' -d 'Sets user-level access control on a destination'
complete -c lpadmin -s 'u' -d 'Sets user-level access control on a destination'
complete -c lpadmin -s 'u' -d 'Sets user-level access control on a destination'
complete -c lpadmin -s 'u' -d 'Sets user-level access control on a destination'
