complete -c ls -s '1' -d 'List one entry per line'
complete -c ls -s 'c' -d 'Sort by changed time, (-l) show ctime'
complete -c ls -s 'C' -d 'Force multi-column output'
complete -c ls -s 'f' -d 'Unsorted output, enables -a'
complete -c ls -s 'l' -d 'Long listing format'
complete -c ls -s 'm' -d 'Comma-separated format, fills across screen'
complete -c ls -s 't' -d 'Sort by modified time, most recent first'
complete -c ls -s 'u' -d 'Sort by access time, (-l) show atime'
complete -c ls -s 'x' -d 'Multi-column output, horizontally listed'
complete -c ls -s 'T' -d 'for -l: Show complete date and time'
complete -c ls -s 'B' -d 'Octal escapes for non-graphic characters'
complete -c ls -s 'W' -d 'Display whiteouts when scanning directories'
complete -c ls -s 'w' -d 'Force raw printing of non-printable characters'
complete -c ls -s 'P' -d 'Don'"'"'t follow symlinks'
complete -c ls -s 'X' -d 'Don'"'"'t cross mount points when recursing'
complete -c ls -s 'M' -d 'for -l, -s: Format size/count with commas'
complete -c ls -s 'O' -d 'Show only leaf files (not dirs), eliding other output'
complete -c ls -s 'O' -d 'for -l: Show file flags'
complete -c ls -s 'e' -d 'for -l: Print ACL associated with file, if present'
complete -c ls -s '@' -d 'for -l: Display extended attributes'
complete -c ls -s 'Z' -d 'Display each file'"'"'s MAC label'
complete -c ls -s 'y' -d 'for -t: Sort A-Z output in same order as time output'
complete -c ls -s 'I' -d 'Prevent -A from being automatically set for root'
complete -c ls -s ',' -d 'for -l: Format size/count number groups with ,/locale'
complete -c ls -s 'D' -d 'for -l: Format date with strptime string'
complete -c ls -l 'color' -d 'Enable color output'
complete -c ls -s 'U' -d 'Sort (-t) by creation time and show time (-l)'
complete -c ls -s 'G' -d 'Enable colorized output'
