complete -c lscpu -l 'all' -s 'a' -d 'Print both online and offline CPUs'
complete -c lscpu -l 'online' -s 'b' -d 'Print online CPUs only'
complete -c lscpu -l 'offline' -s 'c' -d 'Print offline CPUs only'
complete -c lscpu -l 'extended' -s 'e' -d 'Print out an extended readable format'
complete -c lscpu -l 'parse' -s 'p' -d 'Print out a parseble format'
complete -c lscpu -l 'sysroot' -s 's' -d 'Use specified directory as system root'
complete -c lscpu -l 'hex' -s 'x' -d 'Print hexadecimal masks rather thans lists of CPUs'
complete -c lscpu -l 'help' -s 'h' -d 'Display help'
complete -c lscpu -l 'version' -s 'V' -d 'Display version'
