complete -c lsof -s '?' -s 'h' -d 'Print help and exit'
complete -c lsof -s 'a' -d 'Causes list selections to be ANDed'
complete -c lsof -s 'A' -d 'Use alternative name list file'
complete -c lsof -s 'b' -d 'Avoid kernel functions that might block: lstat, readlink, stat'
complete -c lsof -s 'c' -d 'Select the listing for processes, whose command begins with string (^ - negate)'
complete -c lsof -s 'd' -d 'specifies a list of file descriptors to exclude or include in the output listing'
complete -c lsof -s 'g' -d 'select by group (^ - negates)'
complete -c lsof -s 'l' -d 'Convert UIDs to login names'
complete -c lsof -s 'p' -d 'Select or exclude processes by pid'
complete -c lsof -s 'R' -d 'Print PPID'
complete -c lsof -s 't' -d 'Produce terse output (pids only, no header)'
complete -c lsof -s 'u' -d 'select by user (^ - negates)'
