complete -c lunchy -s 'v' -l 'verbose' -d 'Show command executions'
complete -c lunchy -d 'Installs [file] to ~/Library/LaunchAgents or /Library/LaunchAgents'
complete -c lunchy -d 'Show the list of installed agents'
complete -c lunchy -d 'Start the first matching agent'
complete -c lunchy -d 'Stop the first matching agent'
complete -c lunchy -d 'Stop and start the first matching agent'
complete -c lunchy -d 'Show the PID and label for all agents'
complete -c lunchy -d 'Opens the launchctl daemon file in the default editor'
complete -c lunchy -d 'Service'
complete -c lunchy -s 'w' -l 'write' -d 'Persist command'
complete -c lunchy -s 'F' -l 'force' -d 'Force start (disabled) agents'
complete -c lunchy -s 'w' -l 'write' -d 'Persist command'
