complete -c machinectl -s 'H' -l 'host' -d 'Execute the operation on a remote host'
complete -c machinectl -s 'M' -l 'machine' -d 'Execute operation on a VM or container'
complete -c machinectl -s 'h' -l 'help' -d 'Print a short help and exit'
complete -c machinectl -l 'version' -d 'Print a short version and exit'
complete -c machinectl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c machinectl -l 'no-legend' -d 'Do not print header and footer'
complete -c machinectl -l 'no-ask-password' -d 'Don'"'"'t ask for password for privileged operations'
complete -c machinectl -d 'List running machines'
complete -c machinectl -d 'List startable machine images'
complete -c machinectl -s 'a' -l 'all' -d 'Also show machines starting with a '"'"'.'"'"''
complete -c machinectl -d 'Show information about machine'
complete -c machinectl -s 'l' -l 'full' -d 'Do not ellipsize process tree entries'
complete -c machinectl -s 'n' -l 'lines' -d 'How many journal lines to show'
complete -c machinectl -d 'Show properties of machines'
complete -c machinectl -s 'p' -l 'property' -d 'Limit to certain properties'
complete -c machinectl -s 'a' -l 'all' -d 'Show all properties, even if not set'
complete -c machinectl -d 'Start machine'
complete -c machinectl -d 'Login to a machine'
complete -c machinectl -d 'Enable machine to start at boot'
complete -c machinectl -d 'Disable machine from starting at boot'
complete -c machinectl -d 'Poweroff machine'
complete -c machinectl -d 'Reboot machine'
complete -c machinectl -d 'Terminate machine (without shutting down)'
complete -c machinectl -d 'Send signal to process in a machine'
complete -c machinectl -l 'kill-who' -d 'Choose who to send the signal to'
complete -c machinectl -s 's' -l 'signal' -d 'Signal to send'
complete -c machinectl -d 'Bind-mount a directory to a machine'
complete -c machinectl -l 'mkdir' -d 'Create destination directory'
complete -c machinectl -l 'read-only' -d 'Apply read-only mount'
complete -c machinectl -d 'Copy file or directory to a machine'
complete -c machinectl -d 'Copy file or directory from a machine'
complete -c machinectl -d 'Open a shell on a machine'
complete -c machinectl -d 'Show a list of locally installed machines'
complete -c machinectl -d 'Show information about machine images (human-readable)'
complete -c machinectl -d 'Show properties of machine images (machine-readable)'
complete -c machinectl -d 'Clone a machine image'
complete -c machinectl -d 'Rename a machine image'
complete -c machinectl -d 'Mark or unmark machine image as read-only'
complete -c machinectl -d 'Remove machine images'
complete -c machinectl -d 'Set size limit for machine image'
complete -c machinectl -d 'Download a .tar container image'
complete -c machinectl -d 'Download a .raw container image'
complete -c machinectl -d 'Download a .dkr container image'
complete -c machinectl -d 'Import a .tar container image'
complete -c machinectl -d 'Import a .raw container image'
complete -c machinectl -d 'Export a .tar container image'
complete -c machinectl -d 'Export a .raw container image'
complete -c machinectl -l 'format' -d 'Specify compression format'
complete -c machinectl -d 'Show running downloads, imports and exports'
complete -c machinectl -d 'Abort running downloads, imports or exports'
complete -c machinectl -l 'verify' -d 'Verify image with specified method'
complete -c machinectl -l 'verify' -d 'Verify image (not available for dkr)'
complete -c machinectl -l 'dkr-index-url' -d 'Specify index server'
complete -c machinectl -l 'force' -d 'Overwrite existing machine image'
