complete -c magento -s 'h' -l 'help' -d 'Show help for a command'
complete -c magento -s 'q' -l 'quiet' -d 'Do not output any message'
complete -c magento -s 'v' -l 'verbose' -d 'Increase verbosity: 1 for normal, 2 for verbose and 3 for debug'
complete -c magento -s 'V' -l 'version' -d 'Show version'
complete -c magento -l 'ansi' -d 'Force colored output'
complete -c magento -l 'no-ansi' -d 'Disable colored output'
complete -c magento -s 'n' -l 'no-interaction' -d 'Don'"'"'t ask any interactive question'
