complete -c makensis -d 'Prints out help for a specific command, or lists all commands'
complete -c makensis -d 'Specifies input charset'
complete -c makensis -d 'Specifies output charset'
complete -c makensis -d 'Prints the makensis software license'
complete -c makensis -d 'Disables the current directory change to that of the .nsi file'
complete -c makensis -d 'Disables inclusion of <path to makensis.exe>/nsisconf.nsh'
complete -c makensis -d 'Sets the compiler process priority to idle'
complete -c makensis -d 'Sets the compiler process priority to below normal'
complete -c makensis -d 'Sets the compiler process priority to normal'
complete -c makensis -d 'Sets the compiler process priority to above normal'
complete -c makensis -d 'Sets the compiler process priority to high'
complete -c makensis -d 'Sets the compiler process priority to realtime'
complete -c makensis -d 'Pauses after execution'
complete -c makensis -d 'Preprocess to stdout/file'
complete -c makensis -d 'Preprocess to stdout/file'
complete -c makensis -d 'Verbosity: none'
complete -c makensis -d 'Verbosity: no warnings'
complete -c makensis -d 'Verbosity: no info'
complete -c makensis -d 'Verbosity: no script'
complete -c makensis -d 'Verbosity: all'
complete -c makensis -d 'Prints the makensis version and exits'
complete -c makensis -d 'Treat warnings as errors'
