complete -c makedepend -s 'D' -d 'Define'
complete -c makedepend -s 'I' -d 'Include directory'
complete -c makedepend -s 'Y' -d 'Replace include directories'
complete -c makedepend -s 'a' -d 'Append dependencies to makefile'
complete -c makedepend -s 'f' -d 'Specify makefile'
complete -c makedepend -d 'Prepend file to input'
complete -c makedepend -s 'o' -d 'Object file suffix'
complete -c makedepend -s 'p' -d 'Object file prefix'
complete -c makedepend -s 's' -d 'Starting string delimiter'
complete -c makedepend -s 'w' -d 'Line width'
complete -c makedepend -s 'v' -d 'Verbose mode'
complete -c makedepend -s 'm' -d 'Warn about multiple inclusion'
