complete -c man -s 'a' -d 'Display all matches'
complete -c man -s 'c' -d 'Always reformat'
complete -c man -s 'd' -d 'Debug'
complete -c man -s 'D' -d 'Debug and run'
complete -c man -s 'f' -d 'Show whatis information'
complete -c man -s 'F' -l 'preformat' -d 'Format only'
complete -c man -s 'h' -d 'Display help and exit'
complete -c man -s 'k' -d 'Show apropos information'
complete -c man -s 'K' -d 'Search in all man pages'
complete -c man -s 't' -d 'Format for printing'
complete -c man -s 'w' -l 'path' -d 'Only print locations'
complete -c man -s 'W' -d 'Only print locations'
