complete -c mariner -d 'Print bash completion command'
complete -c mariner -d 'Show or update configuration'
complete -c mariner -d 'Show details about torrent with given ID'
complete -c mariner -d 'Download torrent with given ID'
complete -c mariner -d 'Print detailed help for another command'
complete -c mariner -d 'Copy magnet link with given ID to clipboard'
complete -c mariner -d 'Open torrent in the default torrent application'
complete -c mariner -d 'Search for torrents'
complete -c mariner -l 'version' -d 'Show program'"'"'s version number and exit'
complete -c mariner -s 'v' -l 'verbose' -d 'Increase verbosity of output. Can be repeated'
complete -c mariner -s 'q' -l 'quiet' -d 'Suppress output except warnings and errors'
complete -c mariner -s 'h' -l 'help' -d 'Show help message and exit'
complete -c mariner -l 'debug' -d 'Show tracebacks on errors'
complete -c mariner -l 'log-file' -d 'Specify a file to log output. Default ~/.local/share/mariner/mariner.log'
complete -c mariner -l 'config-file' -d 'Path to config file. Default ~/.config/mariner/config.yaml'
complete -c mariner -s 's' -l 'show' -d 'Show the configuration'
complete -c mariner -s 'p' -l 'path' -d 'Path to download torrent files to'
complete -c mariner -s 'a' -l 'all' -d 'Search all available trackers'
complete -c mariner -s 'A' -l 'anime' -d 'Search trackers with anime content only'
complete -c mariner -s 'f' -l 'filter' -d 'Filter trackers that should be searched'
complete -c mariner -s 'L' -l 'legal' -d 'Search trackers with legal content only'
complete -c mariner -s 'l' -l 'limit' -d 'Limit the number of results shown. Default is 50'
complete -c mariner -s 'n' -l 'newest' -d 'Sort results by newest'
complete -c mariner -s 't' -l 'trackers' -d 'Trackers that should be searched'
