complete -c matlab -s 'h' -l 'help' -d 'Show help'
complete -c matlab -d 'Start without a controlling terminal'
complete -c matlab -d 'Run the JVM software without opening the desktop'
complete -c matlab -d 'Start without the JVM software'
complete -c matlab -d 'Disable the display of figure windows'
complete -c matlab -d 'Start the JVM software without starting desktop'
complete -c matlab -d 'Send X commands to X Window Server display xDisp'
complete -c matlab -d 'Set the folder'
complete -c matlab -d 'Change the folder to the Initial working folder preference'
complete -c matlab -d 'Copy Command Window output into filename'
complete -c matlab -s 'n' -d 'Display the environment variables/arguments passed to the executable'
complete -c matlab -s 'e' -d 'Display all environment variables and their values to standard output'
complete -c matlab -s 'Dgdb' -d 'Start in debug mode'
complete -c matlab -s 'Dlldb' -d 'Start in debug mode'
complete -c matlab -s 'Ddbx' -d 'Start in debug mode'
complete -c matlab -d 'Enable use of the Java debugger'
complete -c matlab -d 'Display information for debugging X-based problems'
complete -c matlab -d 'Execute script, statement, or function non-interactively'
complete -c matlab -s 'r' -d 'Execute the statement'
complete -c matlab -d 'Limit to a single computational thread'
complete -c matlab -d 'Disable use of javaclasspath.txt and javalibrarypath.txt files'
complete -c matlab -d 'Force to start with software OpenGL libraries'
complete -c matlab -d 'Disable auto-selection of OpenGL software'
complete -c matlab -s 'c' -d 'Use the specified license file'
