complete -c mdbook -s 'l' -l 'help' -d 'Prints help'
complete -c mdbook -s 'V' -l 'version' -d 'Prints version'
complete -c mdbook -d 'Build book from markdown files'
complete -c mdbook -d 'Prints help'
complete -c mdbook -d 'Create boilerplate structure and files in directory'
complete -c mdbook -l 'force' -d 'Skip confirmation prompts'
complete -c mdbook -l 'theme' -d 'Copy default theme into source folder'
complete -c mdbook -d 'Serve book at http://localhost:3000'
complete -c mdbook -l 'port' -s 'p' -d 'Use another port (default 3000)'
complete -c mdbook -l 'websocket-port' -s 'w' -d 'Use another port for websocket (default 3001)'
complete -c mdbook -d 'Test that code samples compile'
complete -c mdbook -d 'Watch file changes'
