complete -c mddiagnose -s 'h' -d 'Display help'
complete -c mddiagnose -s 'd' -d 'Ignore unknown options'
complete -c mddiagnose -s 'n' -d 'Do not reveal the resulting package in the Finder'
complete -c mddiagnose -s 'r' -d 'Avoid restricted operations such as heap'
complete -c mddiagnose -s 's' -d 'Skip gathering system.log'
complete -c mddiagnose -s 'v' -d 'Prints version of mddiagnose'
complete -c mddiagnose -s 'm' -d 'Minimal report'
complete -c mddiagnose -s 'e' -d 'Evaluate indexing information for path'
complete -c mddiagnose -s 'p' -d 'Evaluate permissions information for path'
complete -c mddiagnose -s 'f' -d 'Write the diagnostic to the specified path'
