complete -c mdimport -s 'g' -d 'Import files using the listed plugin'
complete -c mdimport -s 'V' -d 'Print timing information for this run'
complete -c mdimport -s 'A' -d 'Print out the list of all of the attributes and exit'
complete -c mdimport -s 'X' -d 'Print out the schema file and exit'
complete -c mdimport -s 'r' -d 'Ask the server to reimport files for UTIs claimed by the listed plugin'
complete -c mdimport -s 'p' -d 'Print out performance information gathered during the run'
complete -c mdimport -s 'L' -d 'Print the list of installed importers and exit'
complete -c mdimport -s 'd' -d 'Print debugging information'
complete -c mdimport -s 'n' -d 'Dont send the imported attributes to the data store'
complete -c mdimport -s 'w' -d 'Wait for the specified interval between scanning files'
complete -c mdimport -s 'o' -d 'Write the imported attributes to a file'
