complete -c mdutil -s 'p' -d 'Publish metadata'
complete -c mdutil -s 'i' -d 'Turn indexing on or off'
complete -c mdutil -s 'd' -d 'Disable Spotlight activity for volume'
complete -c mdutil -s 'E' -d 'Erase and rebuild index'
complete -c mdutil -s 's' -d 'Print indexing status'
complete -c mdutil -s 't' -d 'Resolve files from file id with an optional volume path or device id'
complete -c mdutil -s 'a' -d 'Apply command to all volumes'
complete -c mdutil -s 'V' -d 'Apply command to all stores on the specified volume'
complete -c mdutil -s 'v' -d 'Display verbose information'
