complete -c mix -d 'Starts all registered apps'
complete -c mix -d 'Lists all archives'
complete -c mix -d 'Archives this project into a .ez file'
complete -c mix -d 'Installs an archive locally'
complete -c mix -d 'Uninstalls archives'
complete -c mix -d 'Deletes generated application files'
complete -c mix -d 'Executes the given command'
complete -c mix -d 'Compiles source files'
complete -c mix -d 'Compiles Phoenix source files that support code reloading'
complete -c mix -d 'Lists dependencies and their status'
complete -c mix -d 'Deletes the given dependencies'"'"' files'
complete -c mix -d 'Compiles dependencies'
complete -c mix -d 'Gets all out of date dependencies'
complete -c mix -d 'Unlocks the given dependencies'
complete -c mix -d 'Updates the given dependencies'
complete -c mix -d 'Executes the tasks separated by comma'
complete -c mix -d 'Builds an escript for the project'
complete -c mix -d 'Prints help information for tasks'
complete -c mix -d 'Loads and persists the given configuration'
complete -c mix -d 'Lists local tasks'
complete -c mix -d 'Installs Hex locally'
complete -c mix -d 'Manages public keys'
complete -c mix -d 'Installs rebar locally'
complete -c mix -d 'Updates the Phoenix project generator locally'
complete -c mix -d 'Creates a new Elixir project'
complete -c mix -d 'Profiles the given file or expression with fprof'
complete -c mix -d 'Prints Phoenix tasks and their information.'
complete -c mix -d 'Digests and compresses static files'
complete -c mix -d 'Removes old versions of static assets.'
complete -c mix -d 'Lists all available Phoenix generators'
complete -c mix -d 'Generates authentication logic for a resource'
complete -c mix -d 'Generates a self-signed certificate for HTTPS testing'
complete -c mix -d 'Generates a Phoenix channel'
complete -c mix -d 'Generates a context with functions around an Ecto schema'
complete -c mix -d 'Generates an embedded Ecto schema file'
complete -c mix -d 'Generates context and controller for an HTML resource'
complete -c mix -d 'Generates context and controller for a JSON resource'
complete -c mix -d 'Generates LiveView, templates, and context for a resource'
complete -c mix -d 'Generates a notifier that delivers emails by default'
complete -c mix -d 'Generates a Presence tracker'
complete -c mix -d 'Generates release files and optional Dockerfile for release-based deployments'
complete -c mix -d 'Generates an Ecto schema and migration file'
complete -c mix -d 'Generates a secret'
complete -c mix -d 'Generates a Phoenix socket handler'
complete -c mix -d 'Creates a new Phoenix application'
complete -c mix -d 'Creates a new Ecto project within an umbrella project'
complete -c mix -d 'Creates a new Phoenix web project within an umbrella project'
complete -c mix -d 'Prints all routes'
complete -c mix -d 'Starts applications and their servers'
complete -c mix -d 'Runs the given file or expression'
complete -c mix -d 'Runs a project'"'"'s tests'
complete -c mix -s 'i' -d 'Specify input directory'
complete -c mix -s 'o' -d 'Specify output file name'
complete -c mix -l 'no-compile' -d 'Skip compilation'
complete -c mix -l 'all' -d 'Clean everything, including dependencies'
complete -c mix -l 'force' -d 'Forces compilation regardless of modification times'
complete -c mix -l 'no-compile' -d 'Skips compilation to .beam files'
complete -c mix -l 'sup' -d 'Generate an OTP application skeleton with a supervision tree'
complete -c mix -l 'umbrella' -d 'Can be given to generate an umbrella project'
complete -c mix -l 'app' -d 'Can be given in order to name the OTP application'
complete -c mix -l 'module' -d 'Can be given in order to name the modules in the generated code skeleton'
complete -c mix -l 'config' -s 'c' -d 'Loads the given configuration file'
complete -c mix -l 'eval' -s 'e' -d 'Evaluates the given code'
complete -c mix -l 'require' -s 'r' -d 'Requires pattern before running the command'
complete -c mix -l 'parallel-require' -s 'pr' -d 'Requires pattern in parallel'
complete -c mix -l 'no-compile' -d 'Does not compile even if files require compilation'
complete -c mix -l 'no-deps-check' -d 'Does not check dependencies'
complete -c mix -l 'no-halt' -d 'Does not halt the system after running the command'
complete -c mix -l 'no-start' -d 'Does not start applications after compilation'
complete -c mix -l 'trace' -d 'Run tests with detailed reporting; automatically sets `--max-cases` to 1'
complete -c mix -l 'max-cases' -d 'Set the maximum number of cases running async'
complete -c mix -l 'cover' -d 'The directory to include coverage results'
complete -c mix -l 'force' -d 'Forces compilation regardless of modification times'
complete -c mix -l 'no-compile' -d 'Do not compile, even if files require compilation'
complete -c mix -l 'no-start' -d 'Do not start applications after compilation'
complete -c mix -l 'no-color' -d 'Disable color in the output'
complete -c mix -l 'color' -d 'Enable color in the output'
complete -c mix -l 'include' -d 'Include tests that match the filter'
complete -c mix -l 'exclude' -d 'Exclude tests that match the filter'
complete -c mix -l 'only' -d 'Run only tests that match the filter'
complete -c mix -l 'seed' -d 'Seeds the random number generator used to randomize test order'
complete -c mix -l 'timeout' -d 'Set the timeout for the tests'
complete -c mix -l 'version' -d 'Prints the Phoenix version'
complete -c mix -s 'o' -d 'Specify output file name'
complete -c mix -l 'no-vsn' -d 'digest the stylesheet asset references without the query string `?vsn=d`'
complete -c mix -s 'o' -l 'output' -d 'The path to your compiled assets directory. Defaults to priv/static'
complete -c mix -l 'age' -d 'Maximum age (in seconds) for assets'
complete -c mix -l 'keep' -d 'How many previous versions of assets to keep'
complete -c mix -l 'all' -d 'Specifies that all compiled assets (including the manifest) will be removed'
complete -c mix -l 'web' -d 'Customize the web module namespace'
complete -c mix -l 'binary-id' -d 'Uses `binary_id` for schema'"'"'s primary key and its references'
complete -c mix -l 'table' -d 'Specify the the table name for the migration and schema'
complete -c mix -s 'o' -l 'output' -d 'The path and base filename for the certificate and key'
complete -c mix -s 'n' -l 'name' -d 'The Common Name value in certificate'"'"'s subject'
complete -c mix -l 'binary-id' -d 'Uses `binary_id` for schema'"'"'s primary key and its references'
complete -c mix -l 'table' -d 'Specify the the table name for the migration and schema'
complete -c mix -l 'merge-with-existing-context' -d 'Skips prompt and automatically merge the new schema access functions and tests'
complete -c mix -l 'no-merge-with-existing-context' -d 'Skips prompt and prevents changes to an existing context'
complete -c mix -l 'context-app' -d 'Specifies the context app'
complete -c mix -l 'web' -d 'Customize the web module namespace'
complete -c mix -l 'no-context' -d 'Omits context internal implementation'
complete -c mix -l 'no-schema' -d 'Omits schema internal implementation'
complete -c mix -l 'binary-id' -d 'Uses `binary_id` for schema'"'"'s primary key and its references'
complete -c mix -l 'table' -d 'Specify the the table name for the migration and schema'
complete -c mix -l 'context-app' -d 'Specifies the context app'
complete -c mix -l 'web' -d 'Customize the web module namespace'
complete -c mix -l 'no-context' -d 'Omits context internal implementation'
complete -c mix -l 'no-schema' -d 'Omits schema internal implementation'
complete -c mix -l 'binary-id' -d 'Uses `binary_id` for schema'"'"'s primary key and its references'
complete -c mix -l 'table' -d 'Specify the the table name for the migration and schema'
complete -c mix -l 'context-app' -d 'Specifies the context app'
complete -c mix -l 'web' -d 'Customize the web module namespace'
complete -c mix -l 'no-context' -d 'Omits context internal implementation'
complete -c mix -l 'no-schema' -d 'Omits schema internal implementation'
complete -c mix -l 'binary-id' -d 'Uses `binary_id` for schema'"'"'s primary key and its references'
complete -c mix -l 'table' -d 'Specify the the table name for the migration and schema'
complete -c mix -l 'context-app' -d 'Specifies the context app'
complete -c mix -l 'docker' -d 'Generates a Docker and .dockerignore file'
complete -c mix -l 'no-ecto' -d 'Skip migration-related file generation'
complete -c mix -l 'ecto' -d 'Force migration-related file generation'
complete -c mix -l 'no-migration' -d 'Omits migration file'
complete -c mix -l 'context-app' -d 'Specifies the context app'
complete -c mix -l 'table' -d 'Specify the the table name for the migration and schema'
complete -c mix -l 'binary-id' -d 'Uses `binary_id` for schema'"'"'s primary key and its references'
complete -c mix -l 'no-binary-id' -d 'Use normal ids despite the default configuration'
complete -c mix -l 'prefix' -d 'Specifies a prefix'
complete -c mix -l 'migration' -d 'Force generation of the migration'
complete -c mix -l 'umbrella' -d 'Generate an umbrella project (one app for your domain, a second app for web interface)'
complete -c mix -l 'app' -d 'The name of the OTP application'
complete -c mix -l 'module' -d 'The name of the base module in the generated skeleton'
complete -c mix -l 'database' -d 'Specify the database adapter for Ecto'
complete -c mix -l 'no-assets' -d 'Do not generate the assets folder'
complete -c mix -l 'no-ecto' -d 'Do not generate Ecto files'
complete -c mix -l 'no-html' -d 'Do not generate HTML views'
complete -c mix -l 'no-gettext' -d 'Do not generate gettext files'
complete -c mix -l 'no-dashboard' -d 'Do not include Phoenix.LiveDashboard'
complete -c mix -l 'no-live' -d 'Comment out LiveView socket setup in assets/js/app.js'
complete -c mix -l 'no-mailer' -d 'Do not generate Swoosh mailer files'
complete -c mix -l 'no-esbuild' -d 'Do not include esbuild dependencies and assets'
complete -c mix -l 'no-tailwind' -d 'Do not include tailwind dependencies and assets'
complete -c mix -l 'binary-id' -d 'Use binary_id as primary key type in Ecto schemas'
complete -c mix -l 'verbose' -d 'Use verbose output'
complete -c mix -s 'v' -l 'version' -d 'Prints the Phoenix installer version'
complete -c mix -l 'no-context' -d 'Omits context internal implementation'
complete -c mix -l 'no-install' -d 'Disable prompt to install dependencies'
complete -c mix -l 'install' -d 'Force prompt to install dependencies'
complete -c mix -l 'app' -d 'The name of the OTP application'
complete -c mix -l 'module' -d 'The name of the base module in the generated skeleton'
complete -c mix -l 'database' -d 'Specify the database adapter for Ecto'
complete -c mix -l 'binary-id' -d 'Use binary_id as primary key type in Ecto schemas'
complete -c mix -l 'app' -d 'The name of the OTP application'
complete -c mix -l 'module' -d 'The name of the base module in the generated skeleton'
complete -c mix -l 'info' -d 'Locate the controller function definition called by the given url'
complete -c mix -l 'open' -d 'Open browser window for each started endpoint'
complete -c mix -l 'config' -s 'c' -d 'Loads the given configuration file'
complete -c mix -l 'eval' -s 'e' -d 'Evaluates the given code'
complete -c mix -l 'require' -s 'r' -d 'Requires pattern before running the command'
complete -c mix -l 'parallel-require' -s 'pr' -d 'Requires pattern in parallel'
complete -c mix -l 'no-compile' -d 'Does not compile even if files require compilation'
complete -c mix -l 'no-deps-check' -d 'Does not check dependencies'
complete -c mix -l 'no-halt' -d 'Does not halt the system after running the command'
complete -c mix -l 'no-start' -d 'Does not start applications after compilation'
complete -c mix -d 'Starts all registered apps'
complete -c mix -d 'Lists all archives'
complete -c mix -d 'Archives this project into a .ez file'
complete -c mix -d 'Installs an archive locally'
complete -c mix -d 'Uninstalls archives'
complete -c mix -d 'Deletes generated application files'
complete -c mix -d 'Executes the given command'
complete -c mix -d 'Compiles source files'
complete -c mix -d 'Compiles Phoenix source files that support code reloading'
complete -c mix -d 'Lists dependencies and their status'
complete -c mix -d 'Deletes the given dependencies'"'"' files'
complete -c mix -d 'Compiles dependencies'
complete -c mix -d 'Gets all out of date dependencies'
complete -c mix -d 'Unlocks the given dependencies'
complete -c mix -d 'Updates the given dependencies'
complete -c mix -d 'Executes the tasks separated by comma'
complete -c mix -d 'Builds an escript for the project'
complete -c mix -d 'Prints help information for tasks'
complete -c mix -d 'Loads and persists the given configuration'
complete -c mix -d 'Lists local tasks'
complete -c mix -d 'Installs Hex locally'
complete -c mix -d 'Manages public keys'
complete -c mix -d 'Installs rebar locally'
complete -c mix -d 'Creates a new Elixir project'
complete -c mix -d 'Profiles the given file or expression with fprof'
complete -c mix -d 'Prints Phoenix tasks and their information.'
complete -c mix -d 'Digests and compresses static files'
complete -c mix -d 'Removes old versions of static assets.'
complete -c mix -d 'Lists all available Phoenix generators'
complete -c mix -d 'Generates authentication logic for a resource'
complete -c mix -d 'Generates a self-signed certificate for HTTPS testing'
complete -c mix -d 'Generates a Phoenix channel'
complete -c mix -d 'Generates a context with functions around an Ecto schema'
complete -c mix -d 'Generates an embedded Ecto schema file'
complete -c mix -d 'Generates context and controller for an HTML resource'
complete -c mix -d 'Generates context and controller for a JSON resource'
complete -c mix -d 'Generates LiveView, templates, and context for a resource'
complete -c mix -d 'Generates a notifier that delivers emails by default'
complete -c mix -d 'Generates a Presence tracker'
complete -c mix -d 'Generates release files and optional Dockerfile for release-based deployments'
complete -c mix -d 'Generates an Ecto schema and migration file'
complete -c mix -d 'Generates a secret'
complete -c mix -d 'Generates a Phoenix socket handler'
complete -c mix -d 'Creates a new Phoenix application'
complete -c mix -d 'Creates a new Ecto project within an umbrella project'
complete -c mix -d 'Creates a new Phoenix web project within an umbrella project'
complete -c mix -d 'Prints all routes'
complete -c mix -d 'Starts applications and their servers'
complete -c mix -d 'Runs the given file or expression'
complete -c mix -d 'Runs a project'"'"'s tests'
