complete -c mkbundle -l 'config' -d 'Bundle DLLMAP Mono config file'
complete -c mkbundle -l 'config-dir' -d 'Use MONO_CFG_DIR environment variable as config dir'
complete -c mkbundle -l 'env' -d 'Specify value for the environment variable'
complete -c mkbundle -l 'i18n' -d 'Use encoding tables to ship with the executable'
complete -c mkbundle -s 'L' -d 'Use path for look for assemblies'
complete -c mkbundle -l 'library' -d 'Embed the dynamic library file'
complete -c mkbundle -l 'lists-targets' -d 'Show all of the available remote cross compilation targets'
complete -c mkbundle -l 'local-targets' -d 'Show all of the available local cross compilation targets'
complete -c mkbundle -l 'cil-strip' -d 'Use a CIL stripper that mkbundle will use if able to'
complete -c mkbundle -s 'o' -d 'Use output file name'
complete -c mkbundle -l 'options' -d 'Specify configuration options to the Mono runtime'
complete -c mkbundle -l 'target-server' -d 'Use a different server to provide cross-compiled runtimes'
complete -c mkbundle -s 'c' -d 'Produce the stub file, do not compile the resulting stub'
complete -c mkbundle -l 'nomain' -d 'Generate the host stub without a main() function'
complete -c mkbundle -l 'static' -d 'Statically link to mono and glib'
complete -c mkbundle -s 'z' -d 'Compress the assemblies before embedding'
