complete -c mkdosfs -s 'a' -d 'Disable alignment'
complete -c mkdosfs -s 'A' -d 'Use Atari variation'
complete -c mkdosfs -s 'b' -d 'Select location of backup sector'
complete -c mkdosfs -s 'c' -d 'Check for bad blocks'
complete -c mkdosfs -s 'C' -d 'Create file given as device'
complete -c mkdosfs -s 'D' -d 'Specify drive number'
complete -c mkdosfs -s 'f' -d 'Specify number of FATs'
complete -c mkdosfs -s 'F' -d 'Specify FAT size'
complete -c mkdosfs -s 'h' -d 'Specify number of hidden sectors'
complete -c mkdosfs -s 'i' -d 'Specify volume ID'
complete -c mkdosfs -s 'I' -d 'Force to use entire disk'
complete -c mkdosfs -s 'l' -d 'Read bad blocks list from given file'
complete -c mkdosfs -s 'm' -d 'Specify file containing non bootable message'
complete -c mkdosfs -s 'n' -d 'Specify volume name'
complete -c mkdosfs -s 'r' -d 'Specify number of entries available in root directory'
complete -c mkdosfs -s 'R' -d 'Specify number of reserved sectors'
complete -c mkdosfs -s 's' -d 'Specify number of sector per cluster'
complete -c mkdosfs -s 'S' -d 'Specify number of bytes per logical sector'
complete -c mkdosfs -s 'v' -d 'Verbose mode'
complete -c mkdosfs -l 'invariant' -d 'Use constants for randomly generated data'
complete -c mkdosfs -l 'help' -d 'Show help and exit'
