complete -c mkdocs -s 'h' -l 'help' -d 'Show help and exit'
complete -c mkdocs -s 'v' -l 'verbose' -d 'Enable verbose output'
complete -c mkdocs -s 'q' -l 'quiet' -d 'Silence warnings'
complete -c mkdocs -s 'V' -l 'version' -d 'Show the version and exit'
complete -c mkdocs -d 'Build the MkDocs documentation'
complete -c mkdocs -s 'c' -l 'clean' -d 'Remove old site_dir before building (the default)'
complete -c mkdocs -s 'f' -l 'config-file' -d 'Provide a specific MkDocs config'
complete -c mkdocs -s 's' -l 'strict' -d 'Enable strict mode. This will cause MkDocs to abort the build on any warnings'
complete -c mkdocs -s 't' -l 'theme' -d 'The theme to use when building your documentation'
complete -c mkdocs -s 'e' -l 'theme-dir' -d 'The theme directory to use when building your documentation'
complete -c mkdocs -s 'd' -l 'site-dir' -d 'The directory to output the result of the documentation build'
complete -c mkdocs -d 'Deploy your documentation to GitHub Pages'
complete -c mkdocs -s 'c' -l 'clean' -d 'Remove old site_dir before building (the default)'
complete -c mkdocs -s 'f' -l 'config-file' -d 'Provide a specific MkDocs config'
complete -c mkdocs -s 'm' -l 'message' -d 'A commit message to use when committing to the GitHub Pages remote branch'
complete -c mkdocs -s 'b' -l 'remote-branch' -d 'The remote branch to commit to for GitHub Pages'
complete -c mkdocs -s 'r' -l 'remote-name' -d 'The remote name to commit to for GitHub Pages'
complete -c mkdocs -l 'force' -d 'Force the push to the repository'
complete -c mkdocs -d 'Create a new MkDocs project'
complete -c mkdocs -d 'Run the builtin development server'
complete -c mkdocs -s 'f' -l 'config-file' -d 'Provide a specific MkDocs config'
complete -c mkdocs -s 'a' -l 'dev-addr' -d 'IP address and port to serve documentation locally (default: localhost:8000)'
complete -c mkdocs -s 's' -l 'strict' -d 'Enable strict mode. This will cause MkDocs to abort the build on any warnings'
complete -c mkdocs -s 't' -l 'theme' -d 'The theme to use when building your documentation'
complete -c mkdocs -s 'e' -l 'theme-dir' -d 'The theme directory to use when building your documentation'
complete -c mkdocs -l 'livereload' -d 'Enable the live reloading in the development server (this is the default)'
complete -c mkdocs -l 'no-livereload' -d 'Disable the live reloading in the development server'
complete -c mkdocs -l 'dirtyreload' -d 'Enable the live reloading in the development server, but only re-build files that have changed'
