complete -c mksquashfs -d 'Data block size'
complete -c mksquashfs -d 'Selects the compression scheme'
complete -c mksquashfs -d 'Do not compress inode table'
complete -c mksquashfs -d 'Do not compress the uid/gid table'
complete -c mksquashfs -d 'Do not compress data blocks'
complete -c mksquashfs -d 'Do not compress fragment blocks'
complete -c mksquashfs -d 'Do not compress extended attributes'
complete -c mksquashfs -d 'Do not compress any of the data or metadata'
complete -c mksquashfs -d 'Read uncompressed tar file from standard in (stdin)'
complete -c mksquashfs -d 'Act like tar, and do not strip leading directories from source files'
complete -c mksquashfs -d 'Act like cpio, and read file pathnames from standard in (stdin)'
complete -c mksquashfs -d 'Like -cpiostyle, but filenames are null terminated'
complete -c mksquashfs -d 'Build filesystems that are reproducible'
complete -c mksquashfs -d 'Build filesystems that are not reproducible'
complete -c mksquashfs -d 'Set root directory owner'
complete -c mksquashfs -d 'Set root directory group'
complete -c mksquashfs -d 'Make all files owned by root'
complete -c mksquashfs -d 'Set all file uids'
complete -c mksquashfs -d 'Set all file gids'
complete -c mksquashfs -d 'Make pseudo file uids and gids override -all-root, -force-uid and -force-gid options'
complete -c mksquashfs -d 'Do not make filesystem exportable via NFS'
complete -c mksquashfs -d 'Make filesystem exportable via NFS'
complete -c mksquashfs -d 'Do not detect sparse files'
complete -c mksquashfs -d 'Do not pack tail ends into fragments'
complete -c mksquashfs -d 'Pack tail ends into fragments'
complete -c mksquashfs -d 'Do not use fragments'
complete -c mksquashfs -d 'Do not perform duplicate checking'
complete -c mksquashfs -d 'Do not hardlink files, instead store duplicates'
complete -c mksquashfs -d 'If one source directory is specified, create a root directory containing that directory, rather than the contents of the directory'
complete -c mksquashfs -d 'Allow extended shell wildcards (globbing) to be used in exclude dirs/files'
complete -c mksquashfs -d 'Allow POSIX regular expressions to be used in exclude dirs/files'
complete -c mksquashfs -d 'Do not cross filesystem boundaries'
complete -c mksquashfs -d 'Do not cross filesystem boundaries'
complete -c mksquashfs -d 'Do not store extended attributes'
complete -c mksquashfs -d 'Store extended attributes'
complete -c mksquashfs -d 'Print version, licence and copyright message'
complete -c mksquashfs -d 'Treat normally ignored errors as fatal'
complete -c mksquashfs -d 'No verbose output'
complete -c mksquashfs -d 'Print files written to filesystem'
complete -c mksquashfs -d 'Do not display the progress bar'
complete -c mksquashfs -d 'Display progress bar when using the -info option'
complete -c mksquashfs -d 'Display a percentage rather than the full progress bar'
complete -c mksquashfs -d 'Print default memory usage in Mbytes'
complete -c mksquashfs -d 'Do not append to existing filesystem'
complete -c mksquashfs -d 'Do not generate a recovery file'
complete -c mksquashfs -d 'Sets the default directory user'
complete -c mksquashfs -d 'Sets the default directory group'
complete -c mksquashfs -d 'Allow tar files to be concatenated together and fed to Mksquashfs'
complete -c mksquashfs -d 'Do not pad filesystem to a multiple of 4K'
complete -c mksquashfs -d 'Print help and exit'
complete -c mksquashfs -d 'Print compressor options for selected compressor'
complete -c mksquashfs -d 'Strategy to use (gzip only)'
complete -c mksquashfs -d 'Algorithm to use (lzo only)'
complete -c mksquashfs -d 'Compress using LZ4 High Compression (lz4 only)'
complete -c mksquashfs -d 'Compress using filters in turn and choose the best compression (xz only)'
