complete -c mkvextract -s 'V' -l 'version' -d 'Show version information'
complete -c mkvextract -s 'h' -l 'help' -d 'Show help'
complete -c mkvextract -l 'check-for-updates' -d 'Check online for updates'
complete -c mkvextract -d 'Extract tracks to external files'
complete -c mkvextract -d 'Extract tags as XML'
complete -c mkvextract -d 'Extract attachments'
complete -c mkvextract -d 'Extract chapters as XML'
complete -c mkvextract -d 'Extract chapters and tags as CUE sheet'
complete -c mkvextract -d 'Extract timecodes of a track as timecode v2 file'
complete -c mkvextract -d 'Extract cue information as text file'
complete -c mkvextract -s 'f' -l 'parse-fully' -d 'Parse the whole file instead of relying on the index'
complete -c mkvextract -s 'v' -l 'verbose' -d 'Increase verbosity'
complete -c mkvextract -s 'q' -l 'quiet' -d 'Suppress status output'
complete -c mkvextract -l 'ui-language' -d 'Force a locale'
complete -c mkvextract -l 'command-line-charset' -d 'Charset for strings on the command line'
complete -c mkvextract -l 'output-charset' -d 'Outputs messages in specified charset'
complete -c mkvextract -s 'r' -l 'redirect-output' -d 'Redirect all messages into a file'
complete -c mkvextract -l 'debug' -d 'Turn on debugging for a specific feature'
complete -c mkvextract -l 'engage' -d 'Turn on an experimental feature'
complete -c mkvextract -l 'gui-mode' -d 'Enable GUI mode'
complete -c mkvextract -s 'c' -d 'Convert text subtitles to a charset'
complete -c mkvextract -l 'cuesheet' -d 'Also try to extract the CUE sheet'
complete -c mkvextract -l 'blockadd' -d 'Keep only the BlockAdditions up to the specified level'
complete -c mkvextract -l 'raw' -d 'Extract the data to a raw file'
complete -c mkvextract -l 'fullraw' -d 'Extract the data to a raw file including the CodecPrivate as header'
complete -c mkvextract -s 's' -l 'simple' -d 'Exports the chapter information in a simple format'
complete -c mkvextract -l 'simple-language' -d 'Uses the chapter names of the specified language'
