complete -c modinfo -l 'author' -s 'a' -d 'Print only '"'"'author'"'"''
complete -c modinfo -l 'description' -s 'd' -d 'Print only '"'"'description'"'"''
complete -c modinfo -l 'license' -s 'l' -d 'Print only '"'"'license'"'"''
complete -c modinfo -l 'parameters' -s 'p' -d 'Print only '"'"'parm'"'"''
complete -c modinfo -l 'filename' -s 'n' -d 'Print only '"'"'filename'"'"''
complete -c modinfo -l 'null' -s '0' -d 'Use \0 instead of \n'
complete -c modinfo -l 'field' -s 'F' -d 'Print only provided FIELD'
complete -c modinfo -l 'set-version' -s 'k' -d 'Use VERSION instead of `uname -r`'
complete -c modinfo -l 'basedir' -s 'b' -d 'Use DIR as filesystem root for /lib/modules'
complete -c modinfo -l 'version' -s 'V' -d 'Show version'
complete -c modinfo -l 'help' -s 'h' -d 'Show help'
