complete -c mogrify -d 'Join images into a single multi-image file'
complete -c mogrify -d 'Affine transform matrix [matrix]'
complete -c mogrify -d 'Remove pixel-aliasing'
complete -c mogrify -d 'Decrypt image with this password [value]'
complete -c mogrify -d 'Background color [color]'
complete -c mogrify -d 'Add bias when convolving an image [value]'
complete -c mogrify -d 'Use black point compensation'
complete -c mogrify -d 'Chromaticity blue primary point [point]'
complete -c mogrify -d 'Border color [color]'
complete -c mogrify -d 'Assign a caption to an image [string]'
complete -c mogrify -d 'Color correct with a color decision list [filename]'
complete -c mogrify -d 'Apply option to select image channels [type]'
complete -c mogrify -d 'Preferred number of colors in the image [value]'
complete -c mogrify -d 'Alternate image colorspace [type]'
complete -c mogrify -d 'Annotate image with comment [string]'
complete -c mogrify -d 'Set image composite operator [operator]'
complete -c mogrify -d 'Type of pixel compression when writing the image [type]'
complete -c mogrify -d 'Convert cipher pixels to plain pixels [filename]'
complete -c mogrify -d 'Define one or more image format options [format:option]'
complete -c mogrify -d 'Display the next image after pausing [value]'
complete -c mogrify -d 'Horizontal and vertical density of the image [geometry]'
complete -c mogrify -d 'Image depth [value]'
complete -c mogrify -d 'Render text right-to-left or left-to-right [type]'
complete -c mogrify -d 'Get image or font from this X server [server]'
complete -c mogrify -d 'Layer disposal method [method]'
complete -c mogrify -d 'Apply error diffusion to image [method]'
complete -c mogrify -d 'Convert plain pixels to cipher pixels [filename]'
complete -c mogrify -d 'Encoding type [type text]'
complete -c mogrify -d 'Endianness (MSB or LSB) of the image [type]'
complete -c mogrify -d 'Render text with this font family [name]'
complete -c mogrify -d 'Color to use when filling a graphic primitive [color]'
complete -c mogrify -d 'Use this filter when resizing an image [type]'
complete -c mogrify -d 'Flatten a sequence of images'
complete -c mogrify -d 'Render text with this font [name]'
complete -c mogrify -d 'Image format type [type]'
complete -c mogrify -d 'Apply a function to the image [name]'
complete -c mogrify -d 'Colors within this distance are considered equal [distance]'
complete -c mogrify -d 'Horizontal and vertical text placement [type]'
complete -c mogrify -d 'Chromaticity green primary point [point]'
complete -c mogrify -d 'Type of rendering intent when managing the image color [type]'
complete -c mogrify -d 'Type of image interlacing scheme [type]'
complete -c mogrify -d 'Pixel color interpolation method [method]'
complete -c mogrify -d 'Set the space between two letters [value]'
complete -c mogrify -d 'Assign a label to an image [string]'
complete -c mogrify -d 'Pixel cache resource limit [type value]'
complete -c mogrify -d 'Add Netscape loop extension to your GIF animation [iterations]'
complete -c mogrify -d 'Associate a mask with the image [filename]'
complete -c mogrify -d 'Store matte channel if the image has one'
complete -c mogrify -d 'Frame color [color]'
complete -c mogrify -d 'Monitor progress'
complete -c mogrify -d 'Apply a morphology method to the image [method kernel]'
complete -c mogrify -d 'Image orientation [type]'
complete -c mogrify -d 'Image origin [geometry]'
complete -c mogrify -d 'Size and location of an image canvas (setting) [geometry]'
complete -c mogrify -d 'Path write images to this path on disk'
complete -c mogrify -d 'Efficiently determine image attributes'
complete -c mogrify -d 'Font point size [value]'
complete -c mogrify -d 'Image preview type [type]'
complete -c mogrify -d 'JPEG/MIFF/PNG compression level [value]'
complete -c mogrify -d 'Suppress all warning messages'
complete -c mogrify -d 'Chromaticity red primary point [point]'
complete -c mogrify -d 'Pay attention to warning messages'
complete -c mogrify -d 'Horizontal and vertical sampling factor [geometry]'
complete -c mogrify -d 'Image scene number [value]'
complete -c mogrify -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c mogrify -d 'Width and height of image [geometry]'
complete -c mogrify -d 'Render text with this font stretch [type]'
complete -c mogrify -d 'Graphic primitive stroke color [color]'
complete -c mogrify -d 'Graphic primitive stroke width [value]'
complete -c mogrify -d 'Render text with this font style [type]'
complete -c mogrify -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
complete -c mogrify -d 'Synchronize image to storage device'
complete -c mogrify -d 'Declare the image as modified'
complete -c mogrify -d 'Name of texture to tile onto the image background [filename]'
complete -c mogrify -d 'Tile offset [geometry]'
complete -c mogrify -d 'Color tree depth [value]'
complete -c mogrify -d 'Transparent color [color]'
complete -c mogrify -d 'Annotation bounding box color [color]'
complete -c mogrify -d 'The units of image resolution [type]'
complete -c mogrify -d 'Print detailed information about the image'
complete -c mogrify -d 'FlashPix viewing transforms'
complete -c mogrify -d 'Virtual pixel access method [method]'
complete -c mogrify -d 'Render text with this font weight [type]'
complete -c mogrify -d 'Chromaticity white point [point]'
complete -c mogrify -d 'Adaptively blur pixels; decrease effect near edges [geometry]'
complete -c mogrify -d 'Adaptively resize image using '"'"'mesh'"'"' interpolation [geometry]'
complete -c mogrify -d 'Adaptively sharpen pixels; increase effect near edges [geometry]'
complete -c mogrify -d 'Annotate the image with text [geometry text]'
complete -c mogrify -d 'Automatically orient (rotate) image'
complete -c mogrify -d 'Force all pixels below the threshold into black [value]'
complete -c mogrify -d 'Reduce image noise and reduce detail levels [geometry]'
complete -c mogrify -d 'Surround image with a border of color [geometry]'
complete -c mogrify -d 'Simulate a charcoal drawing [radius]'
complete -c mogrify -d 'Remove pixels from the image interior [geometry]'
complete -c mogrify -d 'Clip along the first path from the 8BIM profile'
complete -c mogrify -d 'Associate a clip mask with the image [filename]'
complete -c mogrify -d 'Clip along a named path from the 8BIM profile [id]'
complete -c mogrify -d 'Colorize the image with the fill color [value]'
complete -c mogrify -d 'Apply color correction to the image [matrix]'
complete -c mogrify -d 'Enhance or reduce the image contrast'
complete -c mogrify -d 'Apply a convolution kernel to the image [coefficients]'
complete -c mogrify -d 'Cycle the image colormap [amount]'
complete -c mogrify -d 'Reduce the speckles within an image'
complete -c mogrify -d 'Annotate the image with a graphic primitive [string]'
complete -c mogrify -d 'Apply a filter to detect edges in the image [radius]'
complete -c mogrify -d 'Emboss an image [radius]'
complete -c mogrify -d 'Apply a digital filter to enhance a noisy image'
complete -c mogrify -d 'Perform histogram equalization to an image'
complete -c mogrify -d 'Alter channel pixels based on expression [operator]'
complete -c mogrify -d 'Set the image size [geometry]'
complete -c mogrify -d 'Extract area from image [geometry]'
complete -c mogrify -d 'Implements the discrete Fourier transform (DFT)'
complete -c mogrify -d 'Flip image vertically'
complete -c mogrify -d 'Color floodfill the image with color [geometry]'
complete -c mogrify -d 'Flop image horizontally'
complete -c mogrify -d 'Surround image with an ornamental border [geometry]'
complete -c mogrify -d 'Level of gamma correction [value]'
complete -c mogrify -d 'Reduce image noise and reduce detail levels [geometry]'
complete -c mogrify -d 'Preferred size or location of the image [geometry]'
complete -c mogrify -d 'Implements the inverse discrete Fourier transform (DFT)'
complete -c mogrify -d 'Print program options'
complete -c mogrify -d 'Identify the format and characteristics of the image'
complete -c mogrify -d 'Implode image pixels about the center [amount]'
complete -c mogrify -d 'Local adaptive thresholding [geometry]'
complete -c mogrify -d 'Optimize or compare image layers [method]'
complete -c mogrify -d 'Adjust the level of image contrast [value]'
complete -c mogrify -d 'Apply a median filter to the image [geometry]'
complete -c mogrify -d 'Vary the brightness, saturation, and hue [value]'
complete -c mogrify -d 'Transform image to black and white'
complete -c mogrify -d 'Simulate motion blur [geometry]'
complete -c mogrify -d 'Replace each pixel with its complementary color'
complete -c mogrify -d 'Add or reduce noise in an image [geometry]'
complete -c mogrify -d 'Transform image to span the full range of colors'
complete -c mogrify -d 'Change this color to the fill color [color]'
complete -c mogrify -d 'Add a noise pattern to the image with specific amplitudes [NxN]'
complete -c mogrify -d 'Simulate an oil painting [radius]'
complete -c mogrify -d 'Simulate a Polaroid picture [angle]'
complete -c mogrify -d 'Reduce the image to a limited number of color levels [levels]'
complete -c mogrify -d 'Interpret string and print to console [string]'
complete -c mogrify -d 'Add, delete, or apply an image profile [filename]'
complete -c mogrify -d 'Reduce colors in this colorspace [colorspace]'
complete -c mogrify -d 'Radial blur the image [angle]'
complete -c mogrify -d 'Lighten/darken image edges to create a 3-D effect [value]'
complete -c mogrify -d 'Random threshold the image [low,high]'
complete -c mogrify -d 'Apply options to a portion of the image [geometry]'
complete -c mogrify -d 'Render vector graphics'
complete -c mogrify -d 'Size and location of an image canvas [geometry]'
complete -c mogrify -d 'Change the resolution of an image [geometry]'
complete -c mogrify -d 'Resize the image [geometry]'
complete -c mogrify -d 'Roll an image vertically or horizontally [geometry]'
complete -c mogrify -d 'Apply Paeth rotation to the image [degrees]'
complete -c mogrify -d 'Scale image with pixel sampling [geometry]'
complete -c mogrify -d 'Scale the image [geometry]'
complete -c mogrify -d 'Segment an image [values]'
complete -c mogrify -d 'Selectively blur pixels within a contrast threshold [geometry]'
complete -c mogrify -d 'Simulate a sepia-toned photo [threshold]'
complete -c mogrify -d 'Set an image property [property value]'
complete -c mogrify -d 'Shade the image using a distant light source [degrees]'
complete -c mogrify -d 'Simulate an image shadow [geometry]'
complete -c mogrify -d 'Sharpen the image [geometry]'
complete -c mogrify -d 'Shave pixels from the image edges [geometry]'
complete -c mogrify -d 'Slide one edge of the image along the X or Y axis [geometry]'
complete -c mogrify -d 'Lightness rescaling using sigmoidal contrast enhancement [geometry]'
complete -c mogrify -d 'Simulate a pencil sketch [geometry]'
complete -c mogrify -d 'Negate all pixels above the threshold level [threshold]'
complete -c mogrify -d 'Splice the background color into the image [geometry]'
complete -c mogrify -d 'Displace image pixels by a random amount [amount]'
complete -c mogrify -d 'Replace pixels with statistic from the neighborhood [type geometry]'
complete -c mogrify -d 'Strip image of all profiles and comments'
complete -c mogrify -d 'Swirl image pixels about the center [degrees]'
complete -c mogrify -d 'Threshold the image [value]'
complete -c mogrify -d 'Create a thumbnail of the image [geometry]'
complete -c mogrify -d 'Tile image when filling a graphic primitive [filename]'
complete -c mogrify -d 'Tint the image with the fill color [value]'
complete -c mogrify -d 'Affine transform image'
complete -c mogrify -d 'Make this color transparent within the image [color]'
complete -c mogrify -d 'Flip image vertically and rotate 90 degrees'
complete -c mogrify -d 'Flop image horizontally and rotate 270 degrees'
complete -c mogrify -d 'Trim image edges'
complete -c mogrify -d 'Image type [type]'
complete -c mogrify -d 'Discard all but one of any pixel color'
complete -c mogrify -d 'Sharpen the image [geometry]'
complete -c mogrify -d 'Soften the edges of the image in vignette style [geometry]'
complete -c mogrify -d 'Alter an image along a sine wave [geometry]'
complete -c mogrify -d 'Force all pixels above the threshold into white [value]'
complete -c mogrify -d 'Transform image colors to match this set of colors [filename]'
complete -c mogrify -d 'Append an image sequence'
complete -c mogrify -d 'Apply a color lookup table to the image'
complete -c mogrify -d 'Merge a sequence of images'
complete -c mogrify -d 'Combine a sequence of images'
complete -c mogrify -d 'Composite image'
complete -c mogrify -d 'Cut out a rectangular region of the image [geometry]'
complete -c mogrify -d 'Break down an image sequence into constituent parts'
complete -c mogrify -d 'Alter channel pixels based on expression [operator]'
complete -c mogrify -d 'Apply mathematical expression to an image channel(s) [expression]'
complete -c mogrify -d 'Apply a Hald color lookup table to the image'
complete -c mogrify -d 'Morph an image sequence [value]'
complete -c mogrify -d 'Create a mosaic from an image sequence'
complete -c mogrify -d 'Process the image with a custom image filter [arguments]'
complete -c mogrify -d 'Separate an image channel into a grayscale image'
complete -c mogrify -d 'Smush an image sequence together [geometry]'
complete -c mogrify -d 'Write images to this file [filename]'
complete -c mogrify -d 'Delete the image from the image sequence [indexes]'
complete -c mogrify -d 'Duplicate an image one or more times [count,indexes]'
complete -c mogrify -d 'Insert last image into the image sequence [index]'
complete -c mogrify -d 'Swap two images in the image sequence [indexes]'
complete -c mogrify -d 'Display copious debugging information [events]'
complete -c mogrify -d 'Format of debugging information [format]'
complete -c mogrify -d 'Print a list of supported option arguments [type]'
