complete -c montage -d 'Join images into a single multi-image file'
complete -c montage -d 'Affine transform matrix [matrix]'
complete -c montage -d 'Control alpha/matte channel of an image [option]'
complete -c montage -d 'Decipher image with this password [password]'
complete -c montage -d 'Chromaticity blue primary point [point]'
complete -c montage -d 'Border color [color]'
complete -c montage -d 'Assign a caption to an image [string]'
complete -c montage -d 'Apply option to select image channels [type]'
complete -c montage -d 'Preferred number of colors in the image [value]'
complete -c montage -d 'Alternate image colorsapce [type]'
complete -c montage -d 'Annotate image with comment [string]'
complete -c montage -d 'Composite operator [operator]'
complete -c montage -d 'Type of pixel compression when writing the image [type]'
complete -c montage -d 'Define one or more image format options [format:option]'
complete -c montage -d 'Horizontal and vertical density of the image [geometry]'
complete -c montage -d 'Image depth [value]'
complete -c montage -d 'Query font from this X server [server]'
complete -c montage -d 'Layer disposal method [method]'
complete -c montage -d 'Apply error diffusion to image [method]'
complete -c montage -d 'Annotate the image with a graphic primitive [string]'
complete -c montage -d 'Encoding type [type text]'
complete -c montage -d 'Endianness (MSB or LSB) of the image [type]'
complete -c montage -d 'Extract area from image [geometry]'
complete -c montage -d 'Color to use when filling a graphic primitive [color]'
complete -c montage -d 'Use this filter when resizing an image [type]'
complete -c montage -d 'Render text with this font [name]'
complete -c montage -d 'Output formatted image characteristics ["string"]'
complete -c montage -d 'Level of gamma correction [value]'
complete -c montage -d 'Preferred tile and border sizes [geometry]'
complete -c montage -d 'Direction which direction to gravitate towards'
complete -c montage -d 'Chromaticity green primary point [point]'
complete -c montage -d 'Identify the format and characteristics of the image'
complete -c montage -d 'Type of image interlacing scheme [type]'
complete -c montage -d 'Pixel color interpolation method [method]'
complete -c montage -d 'Set the space between two letters [value]'
complete -c montage -d 'Assign a label to an image [string]'
complete -c montage -d 'Pixel cache resource limit [type value]'
complete -c montage -d 'Frame color [color]'
complete -c montage -d 'Framing style [type]'
complete -c montage -d 'Monitor progress'
complete -c montage -d 'Image origin [geometry]'
complete -c montage -d 'Size and location of an image canvas (setting) [geometry]'
complete -c montage -d 'Font point size [value]'
complete -c montage -d 'Add, delete, or apply an image profile [filename]'
complete -c montage -d 'JPEG/MIFF/PNG compression level [value]'
complete -c montage -d 'Reduce colors in this colorspace [colorspace]'
complete -c montage -d 'Suppress all warning messages'
complete -c montage -d 'Chromaticity red primary point [point]'
complete -c montage -d 'Pay attention to warning messages'
complete -c montage -d 'Settings remain in effect until parenthesis boundary'
complete -c montage -d 'Horizontal and vertical sampling factor [geometry]'
complete -c montage -d 'Range image scene range'
complete -c montage -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c montage -d 'Attribute set an image attribute [value]'
complete -c montage -d 'Add a shadow beneath a tile to simulate depth'
complete -c montage -d 'Width and height of image [geometry]'
complete -c montage -d 'Color to use when stroking a graphic primitive [color]'
complete -c montage -d 'Synchronize image to storage device'
complete -c montage -d 'Declare the image as modified'
complete -c montage -d 'Texture name to tile onto the image background [filename]'
complete -c montage -d 'Create a thumbnail of the image [geometry]'
complete -c montage -d 'Number of tiles per row and column [geometry]'
complete -c montage -d 'Decorate the montage image with a title [string]'
complete -c montage -d 'Transparent color [color]'
complete -c montage -d 'Color tree depth [value]'
complete -c montage -d 'Trim image edges'
complete -c montage -d 'The units of image resolution [type]'
complete -c montage -d 'Print detailed information about the image'
complete -c montage -d 'Virtual pixel access method [method]'
complete -c montage -d 'Chromaticity white point [point]'
complete -c montage -d 'Adaptively sharpen pixels; increase effect near edges [geometry]'
complete -c montage -d 'Automagically orient (rotate) image'
complete -c montage -d 'Reduce image noise and reduce detail levels [geometry]'
complete -c montage -d 'Surround image with a border of color [geometry]'
complete -c montage -d 'Preferred size and location of the cropped image [geometry]'
complete -c montage -d 'Set the image size [geometry]'
complete -c montage -d 'Flatten a sequence of images'
complete -c montage -d 'Flip image in the vertical direction'
complete -c montage -d 'Flop image in the horizontal direction'
complete -c montage -d 'Surround image with an ornamental border [geometry]'
complete -c montage -d 'Transform image to black and white'
complete -c montage -d 'Simulate a Polaroid picture [angle]'
complete -c montage -d 'Size and location of an image canvas (operator) [geometry]'
complete -c montage -d 'Resize the image [geometry]'
complete -c montage -d 'Apply Paeth rotation to the image [degrees]'
complete -c montage -d 'Strip image of all profiles and comments'
complete -c montage -d 'Affine transform image'
complete -c montage -d 'Flip image vertically and rotate 90 degrees'
complete -c montage -d 'Make this color transparent within the image [color]'
complete -c montage -d 'Image type [type]'
complete -c montage -d 'Sharpen the image [geometry]'
complete -c montage -d 'Merge a sequence of images'
complete -c montage -d 'Composite image'
complete -c montage -d 'Clone an image [indexes]'
complete -c montage -d 'Delete the image from the image sequence [indexes]'
complete -c montage -d 'Duplicate an image one or more times [count,indexes]'
complete -c montage -d 'Insert last image into the image sequence [index]'
complete -c montage -d 'Reverse image sequence'
complete -c montage -d 'Swap two images in the image sequence [indexes]'
complete -c montage -d 'Display copious debugging information [events]'
complete -c montage -d 'Print program options'
complete -c montage -d 'Print a list of supported option arguments [type]'
complete -c montage -d 'Format of debugging information [format]'
complete -c montage -d 'Print version information'
complete -c montage -d 'Store matte channel if the image has one'
complete -c montage -d 'Resize support: > 1.0 is blurry, < 1.0 is sharp [factor]'
complete -c montage -d 'Annotate the image with text [geometry text]'
