complete -c mosh -d 'Hostname'
complete -c mosh -d 'Command to run'
complete -c mosh -l 'client' -d 'Path to client helper on local machine (default: "mosh-client")'
complete -c mosh -l 'server' -d 'Command to run server helper on remote machine (default: "mosh-server")'
complete -c mosh -l 'ssh' -d 'SSH command to run when setting up session (example: "ssh -p 2222") (default: "ssh")'
complete -c mosh -l 'predict' -d 'Controls use of speculative local echo'
complete -c mosh -s 'a' -d 'Synonym for --predict=always'
complete -c mosh -s 'n' -d 'Synonym for --predict=never'
complete -c mosh -s 'p' -l 'port' -d 'Use a particular server-side UDP port or port range'
