complete -c mount -s 'V' -d 'Display version and exit'
complete -c mount -s 'h' -d 'Display help and exit'
complete -c mount -s 'v' -d 'Verbose mode'
complete -c mount -s 'a' -d 'Mount file systems in fstab'
complete -c mount -s 'F' -d 'Fork process for each mount'
complete -c mount -s 'f' -d 'Fake mounting'
complete -c mount -s 'l' -d 'Add label to output'
complete -c mount -s 'n' -d 'Do not write mtab'
complete -c mount -s 's' -d 'Tolerate sloppy mount options'
complete -c mount -s 'r' -d 'Read only'
complete -c mount -s 'w' -d 'Read/Write mode'
complete -c mount -s 'L' -d 'Mount partition with specified label'
complete -c mount -s 'U' -d 'Mount partition with specified UID'
complete -c mount -s 'O' -d 'Exclude file systems'
complete -c mount -l 'bind' -d 'Remount a subtree to a second position'
complete -c mount -l 'move' -d 'Move a subtree to a new position'
complete -c mount -s 't' -d 'File system'
complete -c mount -s 'o' -d 'Mount option'
