complete -c mpc -s 'f' -l 'format' -d 'Configure the format used to display songs'
complete -c mpc -l 'wait' -d 'Wait for operation to finish (e. g.  database update)'
complete -c mpc -l 'range' -d 'Operate on a range'
complete -c mpc -s 'q' -l 'quiet' -l 'no-status' -d 'Prevents the current song status from being printed'
complete -c mpc -l 'verbose' -d 'Verbose output'
complete -c mpc -l 'host'
complete -c mpc -s 'p' -l 'port'
complete -c mpc -d 'Toggle consume mode if state is not specified'
complete -c mpc -d 'Get and set current amount of crossfading'
complete -c mpc -d 'Show currently queued (next) song'
complete -c mpc -d 'Get/set volume level at which songs with MixRamp tags will be overlapped'
complete -c mpc -d 'Get/set extra delay added computed from MixRamp tags'
complete -c mpc -d 'Start playing next song on queue'
complete -c mpc -d 'Pause playing'
complete -c mpc -d 'Start playing song-number specified'
complete -c mpc -d 'Start playing previous song'
complete -c mpc -d 'Toggle random mode if state (on or off) is not specified'
complete -c mpc -d 'Toggle repeat mode if state (on or off) is not specified'
complete -c mpc -d 'Set replay gain mode'
complete -c mpc -d 'Toggle single mode if state (on or off) is not specified'
complete -c mpc -d 'Seek by hour, minute or seconds'
complete -c mpc -d 'Seek relative to current position'
complete -c mpc -d 'Stop playing'
complete -c mpc -d 'Toggle between play and pause'
complete -c mpc -d 'Add a song from music database to queue'
complete -c mpc -d 'Add a song from music database to queue after current song'
complete -c mpc -d 'Empty queue'
complete -c mpc -d 'Remove all songs except for currently playing song'
complete -c mpc -d 'Remove a queue number from queue'
complete -c mpc -l 'move' -d 'Change position of song in queue'
complete -c mpc -d 'Search queue for a matching song and play it'
complete -c mpc -d 'Shuffle all songs on queue'
complete -c mpc -d 'Load a file as queue'
complete -c mpc -d 'List available playlists'
complete -c mpc -d 'List all songs in playlist'
complete -c mpc -d 'Delete a specific playlist'
complete -c mpc -d 'Save playlist as file'
complete -c mpc -d 'List file from database'
complete -c mpc -d 'List all files/folders in directory'
complete -c mpc -d 'Search for substrings in song tags'
complete -c mpc -d ' Search with a filter expression'
complete -c mpc -d 'Exact search with a filter expression'
complete -c mpc -d 'Find and add results to current queue'
complete -c mpc -d 'Return a list of all tags of given tag type'
complete -c mpc -d 'Display statistics about MPD'
complete -c mpc -d 'List all mounts'
complete -c mpc -d 'Create a new mount'
complete -c mpc -d 'Remove a mount'
complete -c mpc -d 'List all available outputs'
complete -c mpc -d 'Disable output(s)'
complete -c mpc -d 'Enable output(s)'
complete -c mpc -d 'Change status for given output(s)'
complete -c mpc -d 'List channels that other clients have subscribed to'
complete -c mpc -d 'Send a message to specified channel'
complete -c mpc -d 'Wait for at least one message on specified channel'
complete -c mpc -d 'Subscribe to specified channel and continuously receive messages'
complete -c mpc -d 'Wait until an event occurs'
complete -c mpc -d 'Keep waiting and printing events as they occur'
complete -c mpc -d 'Report version of MPD'
complete -c mpc -d 'Set volume'
complete -c mpc -d 'Scan for updated files in music directory'
complete -c mpc -d 'Like update, but also rescans unmodified files'
complete -c mpc -d 'Show currently playing song'
