complete -c mplayer -d 'Dynamically change postprocessing'
complete -c mplayer -d 'A/V sync speed'
complete -c mplayer -d 'Skip frames to maintain A/V sync'
complete -c mplayer -s 'h' -d 'Display help and exit'
complete -c mplayer -d 'Skip frames to maintain A/V sync'
complete -c mplayer -d 'Loop playback'
complete -c mplayer -d 'Play in random order'
complete -c mplayer -s 'h' -d 'Display help and exit'
complete -c mplayer -d 'Full screen'
complete -c mplayer -d 'Set playlist-r'
complete -c mplayer -d 'Audio language'
complete -c mplayer -d 'Play audio from file'
complete -c mplayer -d 'Set default CD-ROM drive'
complete -c mplayer -d 'Set number of audio channels'
complete -c mplayer -d 'Set start chapter'
complete -c mplayer -d 'Set default DVD-ROM drive'
complete -c mplayer -d 'Set dvd viewing angle'
complete -c mplayer -d 'Force rebuilding index'
complete -c mplayer -d 'Override framerate'
complete -c mplayer -d 'Build index if unavailable'
complete -c mplayer -d 'Load index from file'
complete -c mplayer -d 'Force non-interleaved AVI parser'
complete -c mplayer -d 'Rebuild index and save to file'
complete -c mplayer -d 'Seek to given time position'
complete -c mplayer -d 'TV capture mode'
complete -c mplayer -d 'Subtitle language'
complete -c mplayer -d 'Subtitle file'
complete -c mplayer -d 'Handle subtitlefile as unicode'
complete -c mplayer -d 'Handle subtitlefile as utf8'
complete -c mplayer -l 'help' -d 'Display help and exit'
complete -c mplayer -l 'version' -d 'Display version and exit'
