complete -c msfconsole -s 'E' -l 'environment' -d 'Set Rails environment'
complete -c msfconsole -s 'M' -l 'migration-path' -d 'Directory containing additional DB migrations'
complete -c msfconsole -s 'n' -l 'no-database' -d 'Disable database support'
complete -c msfconsole -s 'y' -l 'yaml' -d 'YAML file containing database settings'
complete -c msfconsole -s 'c' -d 'Load the specified configuration file'
complete -c msfconsole -s 'v' -s 'V' -l 'version' -d 'Show version'
complete -c msfconsole -l 'defer-module-loads' -d 'Defer module loading'
complete -c msfconsole -s 'm' -l 'module-path' -d 'Load an additional module path'
complete -c msfconsole -s 'a' -l 'ask' -d 'Ask before exiting Metasploit'
complete -c msfconsole -s 'H' -l 'history-file' -d 'Save command history to the specified file'
complete -c msfconsole -s 'l' -l 'logger' -d 'Specify a logger to use'
complete -c msfconsole -s 'L' -l 'real-readline' -d 'Use the system Readline library'
complete -c msfconsole -s 'o' -l 'output' -d 'Output to the specified file'
complete -c msfconsole -s 'p' -l 'plugin' -d 'Load a plugin on startup'
complete -c msfconsole -s 'q' -l 'quiet' -d 'Do not print the banner on startup'
complete -c msfconsole -s 'r' -l 'resource' -d 'Execute the specified resource file'
complete -c msfconsole -s 'x' -l 'execute-command' -d 'Execute the specified console commands'
complete -c msfconsole -s 'h' -l 'help' -d 'Show help message'
