complete -c msfdb -d 'Initialize the component'
complete -c msfdb -d 'Delete and reinitialize the component'
complete -c msfdb -d 'Delete and stop the component'
complete -c msfdb -d 'Check component status'
complete -c msfdb -d 'Start the component'
complete -c msfdb -d 'Stop the component'
complete -c msfdb -d 'Restart the component'
complete -c msfdb -l 'component' -d 'Component used with provided command'
complete -c msfdb -s 'd' -l 'debug' -d 'Enable debug output'
complete -c msfdb -s 'h' -l 'help' -d 'Show help message'
complete -c msfdb -l 'use-defaults' -d 'Accept all defaults and do not prompt for options'
complete -c msfdb -l 'msf-db-name' -d 'Database name'
complete -c msfdb -l 'msf-db-user-name' -d 'Database username'
complete -c msfdb -l 'msf-test-db-name' -d 'Test database name'
complete -c msfdb -l 'msf-test-db-user-name' -d 'Test database username'
complete -c msfdb -l 'db-port' -d 'Database port'
complete -c msfdb -l 'db-pool' -d 'Database connection pool size'
complete -c msfdb -s 'a' -l 'address' -d 'Bind to host address'
complete -c msfdb -s 'p' -l 'port' -d 'Web service port'
complete -c msfdb -l 'ssl' -d 'Enable SSL'
complete -c msfdb -l 'no-ssl' -d 'Disable SSL'
complete -c msfdb -l 'ssl-key-file' -d 'Path to private key'
complete -c msfdb -l 'ssl-cert-file' -d 'Path to certificate'
complete -c msfdb -l 'ssl-disable-verify' -d 'Disables (optional) client cert requests'
complete -c msfdb -l 'no-ssl-disable-verify' -d 'Enables (optional) client cert requests'
complete -c msfdb -l 'environment' -d 'Web service framework environment'
complete -c msfdb -l 'retry-max' -d 'Maximum number of web service connect attempts'
complete -c msfdb -l 'retry-delay' -d 'Delay (seconds) between web service connect attempts'
complete -c msfdb -l 'user' -d 'Initial web service admin username'
complete -c msfdb -l 'pass' -d 'Initial web service admin password'
complete -c msfdb -l 'msf-data-service' -d 'Local msfconsole data service connection name'
complete -c msfdb -l 'no-msf-data-service' -d 'Disable local msfconsole data service connection'
