complete -c msfvenom -s 'l' -l 'list' -d 'List all modules for type'
complete -c msfvenom -s 'p' -l 'payload' -d 'Payload to use'
complete -c msfvenom -l 'list-options' -d 'List options for payload'
complete -c msfvenom -s 'f' -l 'format' -d 'Output format'
complete -c msfvenom -s 'e' -l 'encoder' -d 'The encoder to use'
complete -c msfvenom -l 'service-name' -d 'Service name to use when generating a service binary'
complete -c msfvenom -l 'sec-name' -d 'Section name when generating Windows binaries'
complete -c msfvenom -l 'smallest' -d 'Generate the smallest possible payload'
complete -c msfvenom -l 'encrypt' -d 'Type of encryption to apply to the shellcode'
complete -c msfvenom -l 'encrypt-key' -d 'A key to be used for --encrypt'
complete -c msfvenom -l 'encrypt-iv' -d 'An initialization vector for --encrypt'
complete -c msfvenom -s 'a' -l 'arch' -d 'The architecture to use'
complete -c msfvenom -l 'platform' -d 'The platform to use'
complete -c msfvenom -s 'o' -l 'out' -d 'Save the payload to a file'
complete -c msfvenom -s 'b' -l 'bad-chars' -d 'Characters to avoid'
complete -c msfvenom -s 'n' -l 'nopsled' -d 'Prepend a nopsled'
complete -c msfvenom -l 'pad-nops' -d 'Use nopsled size as total payload size'
complete -c msfvenom -s 's' -l 'space' -d 'Maximum size of the resulting payload'
complete -c msfvenom -l 'encoder-space' -d 'Maximum size of the encoded payload'
complete -c msfvenom -s 'i' -l 'iterations' -d 'Number of times to encode the payload'
complete -c msfvenom -s 'c' -l 'add-code' -d 'Additional win32 shellcode file to include'
complete -c msfvenom -s 'x' -l 'template' -d 'Custom executable file to use as a template'
complete -c msfvenom -s 'k' -l 'keep' -d 'Inject the payload as a new thread (for template)'
complete -c msfvenom -s 'v' -l 'var-name' -d 'Custom variable name for certain output formats'
complete -c msfvenom -s 't' -l 'timeout' -d 'Number of seconds to wait when reading the payload'
complete -c msfvenom -s 'h' -l 'help' -d 'Show help message'
