complete -c mupdf -s 'p' -d 'Description'
complete -c mupdf -s 'r' -d 'Resolution'
complete -c mupdf -s 'A' -d 'Set anti-aliasing quality in bits'
complete -c mupdf -s 'C' -d 'Tint color in RRGGBB'
complete -c mupdf -s 'I' -d 'Invert colors'
complete -c mupdf -s 'W' -d 'Page width for EPUB layout'
complete -c mupdf -s 'H' -d 'Page height for EPUB layout'
complete -c mupdf -s 'S' -d 'Font size for EPUB layout'
complete -c mupdf -s 'U' -d 'User style sheet for EPUB layout'
complete -c mupdf -s 'X' -d 'Disable document styles for EPUB layout'
