complete -c ncat -s '4' -d 'IPv4 only'
complete -c ncat -s '6' -d 'IPv6 only'
complete -c ncat -s 'U' -l 'unixsock' -d 'Use Unix domain sockets'
complete -c ncat -s 'u' -l 'udp' -d 'Use UDP'
complete -c ncat -l 'sctp' -d 'Use SCTP'
complete -c ncat -l 'vsock' -d 'Use AF_VSOCK sockets'
complete -c ncat -s 'g' -d 'Loose source routing'
complete -c ncat -s 'G' -d 'Set source routing pointer'
complete -c ncat -s 'p' -l 'source-port' -d 'Specify source port'
complete -c ncat -s 's' -l 'source' -d 'Specify source address'
complete -c ncat -s 'l' -l 'listen' -d 'Listen for connections'
complete -c ncat -s 'm' -l 'max-conns' -d 'Specify maximum number of connections'
complete -c ncat -s 'k' -l 'keep-open' -d 'Accept multiple connections'
complete -c ncat -l 'broker' -d 'Connection brokering'
complete -c ncat -l 'chat' -d 'Ad-hoc "chat server"'
complete -c ncat -l 'ssl' -d 'Use SSL'
complete -c ncat -l 'ssl-verify' -d 'Verify server certificates'
complete -c ncat -l 'ssl-cert' -d 'Specify SSL certificate'
complete -c ncat -l 'ssl-key' -d 'Specify SSL private key'
complete -c ncat -l 'ssl-trustfile' -d 'List trusted certificates'
complete -c ncat -l 'ssl-ciphers' -d 'Specify SSL ciphersuites'
complete -c ncat -l 'ssl-servername' -d 'Request distinct server name'
complete -c ncat -l 'ssl-alpn' -d 'Specify ALPN protocol list'
complete -c ncat -l 'proxy' -d 'Specify proxy address'
complete -c ncat -l 'proxy-type' -d 'Specify proxy protocol'
complete -c ncat -l 'proxy-auth' -d 'Specify proxy credentials'
complete -c ncat -l 'proxy-dns' -d 'Specify where to resolve proxy destination'
complete -c ncat -s 'e' -l 'exec' -d 'Execute command'
complete -c ncat -s 'c' -l 'sh-exec' -d 'Execute command via sh'
complete -c ncat -l 'lua-exec' -d 'Execute a .lua script'
complete -c ncat -l 'allow' -d 'Allow connections'
complete -c ncat -l 'allowfile' -d 'Allow connections from file'
complete -c ncat -l 'deny' -d 'Deny connections'
complete -c ncat -l 'denyfile' -d 'Deny connections from file'
complete -c ncat -s 'd' -l 'delay' -d 'Specify line delay'
complete -c ncat -s 'i' -l 'idle-timeout' -d 'Specify idle timeout'
complete -c ncat -s 'w' -l 'wait' -d 'Specify connect timeout'
complete -c ncat -s 'o' -l 'output' -d 'Save session data'
complete -c ncat -s 'x' -l 'hex-dump' -d 'Save session data in hex'
complete -c ncat -l 'append-output' -d 'Append output'
complete -c ncat -s 'v' -l 'verbose' -d 'Be verbose'
complete -c ncat -s 'C' -l 'crlf' -d 'Use CRLF as EOL'
complete -c ncat -s 'h' -l 'help' -d 'Help screen'
complete -c ncat -l 'recv-only' -d 'Only receive data'
complete -c ncat -l 'send-only' -d 'Only send data'
complete -c ncat -l 'no-shutdown' -d 'Do not shutdown into half-duplex mode'
complete -c ncat -s 'n' -l 'nodns' -d 'Do not resolve hostnames'
complete -c ncat -s 't' -l 'telnet' -d 'Answer Telnet negotiations'
complete -c ncat -l 'version' -d 'Display version'
complete -c ncat -s 'z' -d 'Report connection status only'
