complete -c netctl-auto -l 'help' -d 'Show help'
complete -c netctl-auto -l 'version' -d 'Show version'
complete -c netctl-auto -d 'List all available profiles for automatic selection'
complete -c netctl-auto -d 'Start automatic profile selection on interface'
complete -c netctl-auto -d 'Stop automatic profile selection on interface'
complete -c netctl-auto -d 'Switch to the given network profile'
complete -c netctl-auto -d 'Enable network profile for automatic selection'
complete -c netctl-auto -d 'Disable network profile for automatic selection'
complete -c netctl-auto -d 'Enable all profiles for automatic selection'
complete -c netctl-auto -d 'Disable all profiles for automatic selection'
complete -c netctl-auto -d 'Check whether specified profile is active'
complete -c netctl-auto -d 'Check whether specified profile is enabled'
complete -c netctl-auto -d 'Profile'
complete -c netctl-auto -d 'Profile'
complete -c netctl-auto -d 'Profile'
