complete -c netctl -l 'help' -d 'Display help'
complete -c netctl -l 'version' -d 'Display version'
complete -c netctl -d 'List available profiles'
complete -c netctl -d 'Save which profiles are active'
complete -c netctl -d 'Load saved profiles'
complete -c netctl -d 'Stops all profiles'
complete -c netctl -d 'Start a profile'
complete -c netctl -d 'Stop a profile'
complete -c netctl -d 'Restart a profile'
complete -c netctl -d 'Switch to a profile'
complete -c netctl -d 'Show runtime status of a profile'
complete -c netctl -d 'Enable the systemd unit for a profile'
complete -c netctl -d 'Disable the systemd unit for a profile'
complete -c netctl -d 'Reenable the systemd unit for a profile'
complete -c netctl -d 'Check whether the unit is enabled'
complete -c netctl -d 'Open the specified profile in an editor'
complete -c netctl -d 'Profile'
