complete -c nethack -s 'd' -d 'Specify a playground directory'
complete -c nethack -s 'n' -d 'Suppress printing any news from the game administrator'
complete -c nethack -s 'p' -d 'Specify profession'
complete -c nethack -s 'r' -d 'Specify race'
complete -c nethack -s 'D' -d 'Start in debugging (wizard) mode'
complete -c nethack -s 'X' -d 'Start in discovery mode'
complete -c nethack -s 'u' -d 'Specify player name'
complete -c nethack -d 'Use DEC graphics'
complete -c nethack -d 'Use IBM graphics'
complete -c nethack -l 'version' -d 'Show version information'
complete -c nethack -l 'version:paste' -d 'Show version information & copy it to paste buffer'
complete -c nethack -s 's' -d 'Print the list of your scores'
complete -c nethack -s 'v' -d 'Print all versions present in the score file'
