complete -c networkctl -d 'List links'
complete -c networkctl -d 'Show link status'
complete -c networkctl -d 'Show LLDP neighbors'
complete -c networkctl -d 'Show current address label'
complete -c networkctl -d 'Delete virtual netdevs'
complete -c networkctl -d 'Bring devices up'
complete -c networkctl -d 'Bring devices down'
complete -c networkctl -d 'Renew dynamic configurations'
complete -c networkctl -d 'Trigger DHCP reconfiguration of all connected clients'
complete -c networkctl -d 'Reconfigure interfaces'
complete -c networkctl -d 'Reload .network and .netdev files'
complete -c networkctl -s 'h' -l 'help' -d 'Show help'
complete -c networkctl -l 'version' -d 'Show version'
complete -c networkctl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c networkctl -l 'no-legend' -d 'Do not show the headers and footers'
complete -c networkctl -s 'a' -l 'all' -d 'Show status for all links'
complete -c networkctl -s 's' -l 'stats' -d 'Show detailed link statics'
complete -c networkctl -s 'l' -l 'full' -d 'Do not ellipsize output'
complete -c networkctl -s 'n' -l 'lines' -d 'Number of journal entries to show'
