complete -c ng -d 'The Angular CLI'
complete -c ng -d 'Add dependency'
complete -c ng -d 'Configure analytics'
complete -c ng -d 'Compile Angular app'
complete -c ng -d 'get/set config vars'
complete -c ng -d 'Deploy builder'
complete -c ng -d 'Search documentation'
complete -c ng -d 'Run e2e tests'
complete -c ng -d 'Extracts i18n'
complete -c ng -d ''
complete -c ng -d 'Create <schematic>'
complete -c ng -d 'Display help'
complete -c ng -d 'Run linter'
complete -c ng -d 'New workspace'
complete -c ng -d 'Run Architect'
complete -c ng -d 'Start dev server'
complete -c ng -d 'Run unit tests'
complete -c ng -d 'Update deps'
complete -c ng -d 'Display version'
