complete -c ngrok -d 'Save authtoken to configuration file'
complete -c ngrok -d 'Prints author and licensing information'
complete -c ngrok -d 'Start an HTTP tunnel'
complete -c ngrok -d 'Start tunnels by name from the configuration file'
complete -c ngrok -d 'Start a TCP tunnel'
complete -c ngrok -d 'Start a TLS tunnel'
complete -c ngrok -d 'Update ngrok to the latest version'
complete -c ngrok -d 'Print the version string'
complete -c ngrok -d 'Shows a list of commands or help for one command'
complete -c ngrok -l 'help'
complete -c ngrok -l 'authtoken' -d 'ngrok.com authtoken identifying a user'
complete -c ngrok -l 'config' -d 'path to config files; they are merged if multiple'
complete -c ngrok -l 'log' -d 'path to log file, '"'"'stdout'"'"', '"'"'stderr'"'"' or '"'"'false'"'"''
complete -c ngrok -l 'log-format' -d 'log record format: '"'"'term'"'"', '"'"'logfmt'"'"', '"'"'json'"'"''
complete -c ngrok -l 'log-level' -d 'logging level'
complete -c ngrok -l 'region' -d 'ngrok server region [us , eu, au, ap] (default: us)'
complete -c ngrok -l 'hostname' -d 'host tunnel on custom hostname (requires DNS CNAME)'
complete -c ngrok -l 'subdomain' -d 'host tunnel on a custom subdomain'
complete -c ngrok -l 'auth' -d 'enforce basic auth on tunnel endpoint, '"'"'user:password'"'"''
complete -c ngrok -l 'bind-tls' -d 'listen for http, https or both: true/false/both'
complete -c ngrok -l 'host-header' -d 'set Host header; if '"'"'rewrite'"'"' use local address hostname'
complete -c ngrok -l 'inspect' -d 'enable/disable http introspection'
complete -c ngrok -l 'client-cas' -d 'path to TLS certificate authority to verify client certs'
complete -c ngrok -l 'crt' -d 'path to a TLS certificate for TLS termination'
complete -c ngrok -l 'key' -d 'path to a TLS key for TLS termination'
complete -c ngrok -l 'all' -d 'start all tunnels in the configuration file'
complete -c ngrok -l 'none' -d 'start running no tunnels'
complete -c ngrok -l 'remote-addr' -d 'bind remote address (requires you reserve an address)'
complete -c ngrok -l 'channel' -d 'update channel (stable, beta)'
