complete -c ninja -d 'target'
complete -c ninja -s 't' -d 'subtool'
complete -c ninja -s 'C' -d 'change to specified directory'
complete -c ninja -s 'f' -d 'specify build file [default=build.ninja]'
complete -c ninja -s 'n' -d 'dry run'
complete -c ninja -s 'v' -d 'show all command lines while building'
complete -c ninja -s 'j' -d 'number of jobs to run in parallel [default derived from CPUs]'
complete -c ninja -s 'l' -d 'do not start if load average > N'
complete -c ninja -s 'k' -d 'keep going until N jobs fail [default=1]'
complete -c ninja -s 'h' -d 'show help'
complete -c ninja -s 'd' -d 'enable debugging, specify debug mode'
complete -c ninja -s 'w' -d 'adjust warnings, specify flags'
complete -c ninja -s 'v' -l 'verbose' -d 'show all command lines while building'
complete -c ninja -l 'version' -d 'print ninja version'
