complete -c nmap -d 'Input target from file'
complete -c nmap -d 'Choose random targets'
complete -c nmap -l 'exclude' -d 'Exclude hosts/networks'
complete -c nmap -l 'excludefile' -d 'Exclude list from file'
complete -c nmap -d 'Scan: List Scan'
complete -c nmap -d 'Scan: No port scan'
complete -c nmap -d 'Probe: No Ping'
complete -c nmap -d 'Probe: TCP Syn Ping'
complete -c nmap -d 'Probe: TCP ACK Ping'
complete -c nmap -d 'Probe: UDP Ping'
complete -c nmap -d 'Probe: SCTP INIT Ping'
complete -c nmap -d 'Probe: ICMP Echo Ping'
complete -c nmap -d 'Probe: ICMP timestamp request'
complete -c nmap -d 'Probe: ICMP netmask Ping'
complete -c nmap -d 'Probe: IP Protocol Ping'
complete -c nmap -d 'Probe: ARP Ping'
complete -c nmap -l 'disable-arp-ping' -d 'No ARP or ND Ping'
complete -c nmap -l 'traceroute' -d 'Trace path to host'
complete -c nmap -s 'n' -d 'No DNS resolution'
complete -c nmap -s 'R' -d 'DNS resolution for all targets'
complete -c nmap -l 'system-dns' -d 'Use system DNS resolver'
complete -c nmap -l 'dns-servers' -d 'Servers to use for reverse DNS queries'
complete -c nmap -d 'Scan: TCP SYN'
complete -c nmap -d 'Scan: TCP connect'
complete -c nmap -d 'Scan: UDP'
complete -c nmap -d 'Scan: SCTP INIT'
complete -c nmap -d 'Scan: TCP NULL'
complete -c nmap -d 'Scan: FIN'
complete -c nmap -d 'Scan: Xmas'
complete -c nmap -d 'Scan: ACK'
complete -c nmap -d 'Scan: Window'
complete -c nmap -d 'Scan: Mainmon'
complete -c nmap -l 'scanflags' -d 'Custom TCP scan flags'
complete -c nmap -d 'Scan: SCTP COOKIE ECHO'
complete -c nmap -d 'Scan: Idle Scan'
complete -c nmap -d 'Scan: IP protocol'
complete -c nmap -s 'b' -d 'FTP bounce scan'
complete -c nmap -s 'p' -d 'Only scan specified ports'
complete -c nmap -l 'exclude-ports' -d 'Exclude the specified ports from scanning'
complete -c nmap -s 'F' -d 'Fast (limited port) scan'
complete -c nmap -s 'r' -d 'Don'"'"'t randomize ports'
complete -c nmap -l 'port-ratio' -d 'Scan ports with ratio greater then'
complete -c nmap -l 'top-ports' -d 'Scan the n highest-ratio ports'
complete -c nmap -d 'Scan: Version'
complete -c nmap -l 'allports' -d 'Don'"'"'t exclude any ports from version detection'
complete -c nmap -l 'version-intensity' -d 'Set version scan intensity'
complete -c nmap -l 'version-light' -d 'Enable light mode'
complete -c nmap -l 'version-all' -d 'Try every single probe'
complete -c nmap -l 'version-trace' -d 'Trace version scan activity'
complete -c nmap -s 'O' -d 'Enable OS detection'
complete -c nmap -l 'osscan-limit' -d 'Limit OS detection to promising targets'
complete -c nmap -l 'osscan-guess' -d 'Guess OS detection results'
complete -c nmap -l 'fuzzy' -d 'Guess OS detection results'
complete -c nmap -l 'max-os-tries' -d 'Set the maximum number of OS detection tries against a target'
complete -c nmap -d 'Scan: Scripts (default)'
complete -c nmap -l 'script'
complete -c nmap -l 'script' -d 'Runs a script scan'
complete -c nmap -l 'script-args' -d 'provide arguments to NSE scripts'
complete -c nmap -l 'script-args-file' -d 'load arguments to NSE scripts from a file'
complete -c nmap -l 'script-help'
complete -c nmap -l 'script-help' -d 'Shows help about scripts'
complete -c nmap -l 'script-trace'
complete -c nmap -l 'script-updatedb'
complete -c nmap -l 'min-hostgroup' -l 'max-hostgroup' -d 'Adjust paralel scan group size'
complete -c nmap -l 'min-parallelism' -l 'max-parallelism' -d 'Adjust probe parallelization'
complete -c nmap -l 'min-rtt-timeout' -l 'max-rtt-timeout' -l 'initial-rtt-timeout' -d 'Adjust probe timeouts'
complete -c nmap -l 'max-retries' -d 'Specify the maximum number of port scan probe retransmissions'
complete -c nmap -l 'host-timeout' -d 'to skip slow hosts'
complete -c nmap -l 'script-timeout'
complete -c nmap -l 'scan-delay' -l 'max-scan-delay' -d 'Adjust delay between probes'
complete -c nmap -l 'min-rate' -l 'max-rate' -d 'Directly control the scanning rate'
complete -c nmap -l 'defeat-rst-ratelimit' -d 'ignore ICMP-RST rate limits'
complete -c nmap -l 'defeat-icmp-ratelimit' -d 'ignore ICMP unreachable in UDP'
complete -c nmap -l 'nsock-engine' -d 'Enforce use of a given nsock IO multiplexing engine'
complete -c nmap -s 'T' -d 'Set a timing template'
complete -c nmap -s 'f' -d 'fragment packets'
complete -c nmap -s 'f' -d 'use 16 bytes per fragment'
complete -c nmap -l 'mtu' -d 'use specified mtu'
complete -c nmap -s 'D' -d 'Cloak a scan with decoys'
complete -c nmap -s 'S' -d 'Spoof source address'
complete -c nmap -s 'e' -d 'Use specified interface'
complete -c nmap -l 'source-port' -s 'g' -d 'Spoof source port number'
complete -c nmap -l 'data' -d 'Append custom binary data to sent packets'
complete -c nmap -l 'data-string' -d 'Append custom string to sent packets'
complete -c nmap -l 'data-length' -d 'Append random data to sent packets'
complete -c nmap -l 'ip-options' -d 'Send packets with specified ip options'
complete -c nmap -l 'ttl' -d 'Set IP time-to-live field'
complete -c nmap -l 'randomize-hosts' -d 'Randomize target host order'
complete -c nmap -l 'spoof-mac' -d 'Spoof MAC address'
complete -c nmap -l 'proxies' -d 'Relay TCP connections through a chain of proxies'
complete -c nmap -l 'badsum' -d 'Send packets with bogus TCP/UDP checksums'
complete -c nmap -l 'adler32' -d 'Use deprecated Adler32 instead of CRC32C for SCTP checksums'
complete -c nmap -d 'normal output'
complete -c nmap -d 'XML output'
complete -c nmap -d 'ScRipT KIdd|3 oUTpuT'
complete -c nmap -d 'grepable output'
complete -c nmap -d 'Output in the three major formats'
complete -c nmap -s 'v' -d 'Increase/Set verbosity level'
complete -c nmap -s 'd' -d 'Increase/Set debugging level'
complete -c nmap -l 'reason' -d 'Host and port state reasons'
complete -c nmap -l 'stats-every' -d 'Print periodic timing stats'
complete -c nmap -l 'packet-trace' -d 'Trace packets and data sent and received'
complete -c nmap -l 'open' -d 'Show only open (or possibly open) ports'
complete -c nmap -l 'iflist' -d 'List interfaces and routes'
complete -c nmap -l 'append-output' -d 'Append to rather than clobber output files'
complete -c nmap -l 'resume' -d 'Resume aborted scan'
complete -c nmap -l 'stylesheet' -d 'Set XSL stylesheet to transform XML output'
complete -c nmap -l 'webxml' -d 'Load stylesheet from Nmap.Org'
complete -c nmap -l 'no-stylesheet' -d 'Omit XSL stylesheet declaration from XML'
complete -c nmap -s '6' -d 'Enable IPv6 scanning'
complete -c nmap -s 'A' -d 'Aggressive scan options'
complete -c nmap -l 'datadir' -d 'Specify custom Nmap data file location'
complete -c nmap -l 'servicedb' -d 'Specify custom services file'
complete -c nmap -l 'versiondb' -d 'Specify custom service probes file'
complete -c nmap -l 'send-eth' -d 'Use raw ethernet sending'
complete -c nmap -l 'send-ip' -d 'Send at raw IP level'
complete -c nmap -l 'privileged' -d 'Assume that the user is fully privileged'
complete -c nmap -l 'unprivileged' -d 'Assume that the user lacks raw socket privileges'
complete -c nmap -l 'release-memory' -d 'Release memory before quitting'
complete -c nmap -s 'V' -l 'version' -d 'Print version number'
complete -c nmap -s 'h' -l 'help' -d 'Print help summary page'
