complete -c nmcli -s 't' -l 'terse' -d 'Output is terse'
complete -c nmcli -s 'p' -l 'pretty' -d 'Output is pretty'
complete -c nmcli -s 'm' -l 'mode' -d 'Switch between tabular and multiline mode'
complete -c nmcli -s 'c' -l 'color' -d 'Whether to use colors in output'
complete -c nmcli -s 'f' -l 'fields' -d 'Specify the output fields'
complete -c nmcli -s 'e' -l 'escape' -d 'Whether to escape ":" and "\\" characters'
complete -c nmcli -s 'a' -l 'ask' -d 'Ask for missing parameters'
complete -c nmcli -s 's' -l 'show-secrets' -d 'Allow displaying passwords'
complete -c nmcli -s 'w' -l 'wait' -d 'Set timeout (seconds) waiting for finishing operations'
complete -c nmcli -s 'v' -l 'version' -d 'Show nmcli version'
complete -c nmcli -s 'h' -l 'help' -d 'Print help information'
complete -c nmcli -d 'Command-line tool to control NetworkManager'
complete -c nmcli -d 'Show overall status of NetworkManager'
complete -c nmcli -d 'Get or change persistent system hostname'
complete -c nmcli -d 'Show caller permissions for authenticated operations'
complete -c nmcli -d 'Get or change NetworkManager logging level and domains'
complete -c nmcli -d 'Switch networking on'
complete -c nmcli -d 'Switch networking off'
complete -c nmcli -d 'Get network connectivity state'
complete -c nmcli -d 'Re-check the connectivity'
complete -c nmcli -d 'Get status of all radio switches; turn them on/off'
complete -c nmcli -d 'Get status of Wi-Fi radio switch; turn it on/off'
complete -c nmcli -d 'Get status of mobile broadband radio switch; turn it on/off'
complete -c nmcli -d 'Modify one or more properties'
complete -c nmcli -d 'Interactive edit'
complete -c nmcli -l 'active' -d 'List only active profiles'
complete -c nmcli -l 'order' -d 'Custom connection ordering'
complete -c nmcli -d 'Specify NSP to connect to (only for WiMAX)'
complete -c nmcli -d 'password file to activate the connection'
complete -c nmcli -l 'temporary'
complete -c nmcli -l 'temporary'
complete -c nmcli -l 'temporary'
complete -c nmcli -d 'Register nmcli as NM secret agent'
complete -c nmcli -d 'Register nmcli as a polkit agent for user session'
complete -c nmcli -d 'Run nmcli as secret and polkit agent'
