complete -c npm -d 'Run arbitrary package scripts'
complete -c npm -d 'Set access level on published packages'
complete -c npm -d 'List access info'
complete -c npm -d 'Get access level'
complete -c npm -d 'Grant access to users'
complete -c npm -d 'Revoke access from users'
complete -c npm -d 'Set access level'
complete -c npm -d 'Set package status'
complete -c npm -d 'Set package MFA'
complete -c npm -d 'Set package MFA'
complete -c npm -l 'json' -d 'Output JSON'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Add a registry user account'
complete -c npm -d 'Login to a registry user account'
complete -c npm -d 'Run a security audit'
complete -c npm -d 'Verify registry signatures'
complete -c npm -d 'Install compatible updates to vulnerable deps'
complete -c npm -l 'audit-level' -d 'Audit level'
complete -c npm -l 'dry-run' -d 'Do not make any changes'
complete -c npm -s 'f' -l 'force' -d 'Removes various protections'
complete -c npm -l 'json' -d 'Output JSON'
complete -c npm -l 'package-lock-only' -d 'Only use package-lock.json, ignore node_modules'
complete -c npm -l 'omit' -d 'Omit dependency type'
complete -c npm -l 'foreground-scripts' -d 'Run all build scripts in the foreground'
complete -c npm -l 'ignore-scripts' -d 'Don'"'"'t run pre-, post- and life-cycle scripts'
complete -c npm -l 'install-links' -d 'Install file: protocol deps as regular deps'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Manipulates package'"'"'s cache'
complete -c npm -d 'Add the specified package to the local cache'
complete -c npm -d 'Delete data out of the cache folder'
complete -c npm -d 'Show the data in the cache'
complete -c npm -d 'Verify the contents of the cache folder'
complete -c npm -l 'cache' -d 'Cache location'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Clean install a project'
complete -c npm -d 'Install a project with a clean slate and run tests'
complete -c npm -d 'Tab Completion for npm'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Manage the npm configuration files'
complete -c npm -d 'Get a value from the npm configuration'
complete -c npm -s 'l' -l 'long' -d 'Show extended information'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Set a value in the npm configuration'
complete -c npm -s 'L' -l 'location' -d 'Which config file'
complete -c npm -s 'g' -l 'global' -d 'Edit global config'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Reduce duplication'
complete -c npm -d 'Find duplication'
complete -c npm -d 'Deprecate a version of a package'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'The registry diff command'
complete -c npm -l 'diff' -d 'Arguments to compare'
complete -c npm -l 'diff-name-only' -d 'Prints only filenames'
complete -c npm -l 'diff-unified' -d 'The number of lines to print'
complete -c npm -l 'diff-ignore-all-space' -d 'Ignore whitespace'
complete -c npm -l 'diff-no-prefix' -d 'Do not show any prefix'
complete -c npm -l 'diff-src-prefix' -d 'Source prefix'
complete -c npm -l 'diff-dst-prefix' -d 'Destination prefix'
complete -c npm -l 'diff-text' -d 'Treat all files as text'
complete -c npm -s 'g' -l 'global' -d 'Operates in "global" mode'
complete -c npm -l 'tag' -d 'The tag used to fetch the tarball'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Modify package distribution tags'
complete -c npm -d 'Open docs for a package in a web browser'
complete -c npm -d 'Check your npm environment'
complete -c npm -d 'Check npm ping'
complete -c npm -d 'Check registry'
complete -c npm -d 'Check installed versions'
complete -c npm -d 'Check PATH'
complete -c npm -d 'Check file permissions'
complete -c npm -d 'Verify cache'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Edit an installed package'
complete -c npm -l 'editor' -d 'Specify the editor'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Run a command from a local or remote npm package'
complete -c npm -d 'Browse an installed package'
complete -c npm -d 'The shell to open'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Retrieve funding information'
complete -c npm -l 'json' -d 'Output JSON'
complete -c npm -l 'browser' -d 'Set browser'
complete -c npm -l 'no-browser' -d 'Print to stdout'
complete -c npm -l 'unicode' -d 'Use unicode characters in the output'
complete -c npm -l 'no-unicode' -d 'Use ascii characters over unicode glyphs'
complete -c npm -l 'which' -d 'Which source URL to open (1-indexed)'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Get help on npm'
complete -c npm -d 'Search npm help documentation'
complete -c npm -s 'l' -l 'long' -d 'Show extended information'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Manage registry hooks'
complete -c npm -d 'Add a hook'
complete -c npm -d 'List all active hooks'
complete -c npm -d 'Update an existing hook'
complete -c npm -d 'Remove a hook'
complete -c npm -l 'type' -d 'Hook type'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Create a package.json file'
complete -c npm -d 'Install a package'
complete -c npm -d 'Install package(s) and run tests'
complete -c npm -d 'Symlink a package folder'
complete -c npm -d 'Log out of the registry'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -l 'scope' -d 'Log out of private repository'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'List installed packages'
complete -c npm -d 'Check for outdated packages'
complete -c npm -s 'a' -l 'all' -d 'Also show indirect dependencies'
complete -c npm -l 'json' -d 'Output JSON'
complete -c npm -s 'l' -l 'long' -d 'Show extended information'
complete -c npm -l 'parseable' -d 'Output parseable results'
complete -c npm -s 'g' -l 'global' -d 'Check global packages'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Manage orgs'
complete -c npm -d 'Create a tarball from a package'
complete -c npm -l 'dry-run' -d 'Do not make any changes'
complete -c npm -l 'json' -d 'Output JSON'
complete -c npm -l 'pack-destination' -d 'Tarball destination directory'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Ping npm registry'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Manages your package.json'
complete -c npm -d 'Sets a value'
complete -c npm -d 'Retrieves a value'
complete -c npm -d 'Deletes a key'
complete -c npm -s 'f' -l 'force' -d 'Removes various protections'
complete -c npm -l 'json' -d 'Parse values with JSON.parse()'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Display npm prefix'
complete -c npm -s 'g' -l 'global' -d 'Display global prefix'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Change settings on your registry profile'
complete -c npm -d 'Enables two-factor authentication'
complete -c npm -d 'Disables two-factor authentication'
complete -c npm -d 'Display profile properties'
complete -c npm -d 'Set the value of a profile property'
complete -c npm -d 'Requiere an OTP on profile changes'
complete -c npm -d 'Also requiere an OTP on package changes'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Remove extraneous packages'
complete -c npm -l 'omit' -d 'Omit dependency type'
complete -c npm -l 'dry-run' -d 'Do not make any changes'
complete -c npm -l 'json' -d 'Output JSON'
complete -c npm -l 'foreground-scripts' -d 'Run all build scripts in the foreground'
complete -c npm -l 'ignore-scripts' -d 'Don'"'"'t run pre-, post- and life-cycle scripts'
complete -c npm -l 'install-links' -d 'Install file: protocol deps as regular deps'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Publish a package'
complete -c npm -l 'tag' -d 'Upload to tag'
complete -c npm -l 'access' -d 'Restrict access'
complete -c npm -l 'dry-run' -d 'Do not make any changes'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -l 'provenance' -d 'Link to build location when publishing from CI/CD'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Dependency selector query'
complete -c npm -s 'g' -l 'global' -d 'Query global packages'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Rebuild a package'
complete -c npm -d 'Open package repository page in the browser'
complete -c npm -s 'g' -l 'global' -d 'Display global root'
complete -c npm -l 'browser' -d 'Set browser'
complete -c npm -l 'no-browser' -d 'Print to stdout'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Restart a package'
complete -c npm -d 'Start a package'
complete -c npm -d 'Stop a package'
complete -c npm -d 'Test a package'
complete -c npm -d 'Display npm root'
complete -c npm -s 'g' -l 'global' -d 'Display global root'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Search for packages'
complete -c npm -d 'Lock down dependency versions'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Mark your favorite packages'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -l 'unicode' -d 'Use unicode characters in the output'
complete -c npm -l 'no-unicode' -d 'Use ascii characters over unicode glyphs'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'View packages marked as favorites'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Manage organization teams and team memberships'
complete -c npm -d 'Create a new team'
complete -c npm -d 'Destroy an existing team'
complete -c npm -d 'Add a user to an existing team'
complete -c npm -d 'Remove users from a team'
complete -c npm -d 'List teams or team members'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -s 'p' -l 'parseable' -d 'Output parseable results'
complete -c npm -l 'json' -d 'Output JSON'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Manage your authentication tokens'
complete -c npm -d 'Shows active authentication tokens'
complete -c npm -d 'Revokes an authentication token'
complete -c npm -d 'Create a new authentication token'
complete -c npm -l 'read-only' -d 'Mark a token as unable to publish'
complete -c npm -l 'cidr' -d 'List of CIDR address'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Update package(s)'
complete -c npm -d 'Remove a package'
complete -c npm -d 'Remove a package from the registry'
complete -c npm -l 'dry-run' -d 'Do not make any changes'
complete -c npm -s 'f' -l 'force' -d 'Removes various protections'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Remove star from a package'
complete -c npm -l 'registry' -d 'Registry base URL'
complete -c npm -l 'unicode' -d 'Use unicode characters in the output'
complete -c npm -l 'no-unicode' -d 'Use ascii characters over unicode glyphs'
complete -c npm -l 'otp' -d '2FA one-time password'
complete -c npm -s 'h' -l 'help' -d 'Display help'
complete -c npm -d 'Bump a package version'
complete -c npm -d 'View registry info'
complete -c npm -d 'Display npm username'
complete -c npm -d 'Check registry'
complete -c npm -s 'h' -l 'help' -d 'Display help'
