complete -c nvim -s 'c' -d 'Execute Ex command after the first file has been read'
complete -c nvim -s 'S' -d 'Source file after the first file has been read'
complete -c nvim -l 'cmd' -d 'Execute Ex command before loading any vimrc'
complete -c nvim -s 'i' -d 'Set the shada file location'
complete -c nvim -s 'o' -d 'Open horizontally split windows for each file'
complete -c nvim -d 'Open two horizontally split windows'
complete -c nvim -s 'O' -d 'Open vertically split windows for each file'
complete -c nvim -d 'Open two vertically split windows'
complete -c nvim -s 'p' -d 'Open tab pages for each file'
complete -c nvim -d 'Open two tab pages'
complete -c nvim -s 'q' -d 'Start in quickFix mode'
complete -c nvim -s 'r' -d 'Use swap files for recovery'
complete -c nvim -s 't' -d 'Set the cursor to tag'
complete -c nvim -s 'u' -d 'Use alternative vimrc'
complete -c nvim -s 'w' -d 'Record all typed characters'
complete -c nvim -s 'W' -d 'Record all typed characters (overwrite file)'
complete -c nvim -s 'A' -d 'Start in Arabic mode'
complete -c nvim -s 'b' -d 'Start in binary mode'
complete -c nvim -s 'd' -d 'Start in diff mode'
complete -c nvim -s 'D' -d 'Debugging mode'
complete -c nvim -s 'e' -d 'Start in Ex mode, execute stdin as Ex commands'
complete -c nvim -s 'E' -d 'Start in Ex mode, read stdin as text into buffer 1'
complete -c nvim -s 'h' -d 'Print help message and exit'
complete -c nvim -s 'H' -d 'Start in Hebrew mode'
complete -c nvim -s 'L' -d 'List swap files'
complete -c nvim -s 'm' -d 'Disable file modification'
complete -c nvim -s 'M' -d 'Disable buffer modification'
complete -c nvim -s 'R' -d 'Read-only mode'
complete -c nvim -s 'r' -d 'List swap files'
complete -c nvim -s 'V' -d 'Start in verbose mode'
complete -c nvim -s 'h' -l 'help' -d 'Print help message and exit'
complete -c nvim -l 'noplugin' -d 'Skip loading plugins'
complete -c nvim -s 'v' -l 'version' -d 'Print version information and exit'
complete -c nvim -l 'clean' -d 'Factory defaults: skip vimrc, plugins, shada'
complete -c nvim -l 'startuptime' -d 'Write startup timing messages to <file>'
complete -c nvim -s 'l' -d 'Execute Lua script'
complete -c nvim -s 'll' -d 'Execute Lua script in uninitialized editor'
complete -c nvim -s 'es' -d 'Start in Ex script mode, execute stdin as Ex commands'
complete -c nvim -s 'Es' -d 'Start in Ex script mode, read stdin as text into buffer 1'
complete -c nvim -s 's' -d 'Execute script file as normal-mode input'
complete -c nvim -l 'api-info' -d 'Write msgpack-encoded API metadata to stdout'
complete -c nvim -l 'embed' -d 'Use stdin/stdout as a msgpack-rpc channel'
complete -c nvim -l 'headless' -d 'Don'"'"'t start a user interface'
complete -c nvim -l 'listen' -d 'Serve RPC API from this address (e.g. 127.0.0.1:6000)'
complete -c nvim -l 'server' -d 'Specify RPC server to send commands to'
complete -c nvim -l 'remote' -d 'Edit files on nvim server specified with --server'
complete -c nvim -l 'remote-expr' -d 'Evaluate expr on nvim server specified with --server'
complete -c nvim -l 'remote-send' -d 'Send keys to nvim server specified with --server'
complete -c nvim -l 'remote-silent' -d 'Edit files on nvim server specified with --server'
