complete -c nvme -d 'List all NVMe devices and namespaces on machine'
complete -c nvme -s 'v' -l 'verbose' -d 'Increase verbosity'
complete -c nvme -d 'List nvme subsystems'
complete -c nvme -d 'Send NVMe Identify Controller'
complete -c nvme -d 'Send NVMe Identify Namespace'
complete -c nvme -d 'Send NVMe Identify Namespace Granularity List'
complete -c nvme -d 'Send NVMe Identify Namespace for the specified LBA Format index'
complete -c nvme -d 'Send NVMe Identify List'
complete -c nvme -d 'Send NVMe Identify Controller List'
complete -c nvme -d 'Send NVMe Identify Controller NVM Command Set'
complete -c nvme -d 'Send NVMe Identify Namespace NVM Command Set'
complete -c nvme -d 'Send NVMe Identify Namespace NVM Command Set for the specified LBA Format index'
complete -c nvme -d 'Send NVMe Identify Primary Controller Capabilities'
complete -c nvme -d 'List Secondary Controllers associated with a Primary Controller'
complete -c nvme -d 'I/O Command Set Independent Identify Namespace'
complete -c nvme -d 'Send NVMe Namespace Descriptor List'
complete -c nvme -d 'Send NVMe Identify NVM Set List'
complete -c nvme -d 'Send NVMe Identify UUID List'
complete -c nvme -d 'Send NVMe Identify I/O Command Set'
complete -c nvme -d 'Send NVMe Identify Domain List'
complete -c nvme -d 'Send NVMe Identify Endurance Group List'
complete -c nvme -d 'Creates a namespace with the provided parameters'
complete -c nvme -d 'Deletes a namespace from the controller'
complete -c nvme -d 'Attaches a namespace to requested controller(s)'
complete -c nvme -d 'Detaches a namespace from requested controller(s)'
complete -c nvme -d 'Retrieve the namespace ID of opened block device'
complete -c nvme -d 'Generic NVMe get log, returns log in raw format'
complete -c nvme -d 'Retrieve FW Telemetry log write to file'
complete -c nvme -d 'Retrieve FW Log'
complete -c nvme -d 'Retrieve Changed Namespace List'
complete -c nvme -d 'Retrieve SMART Log'
complete -c nvme -d 'Retrieve ANA Log'
complete -c nvme -d 'Retrieve Error Log'
complete -c nvme -d 'Retrieve Command Effects Log'
complete -c nvme -d 'Retrieve Endurance Group Log'
complete -c nvme -d 'Retrieve Predictable Latency per Nvmset Log'
complete -c nvme -d 'Retrieve Predictable Latency Event Aggregate Log'
complete -c nvme -d 'Retrieve Presistent Event Log'
complete -c nvme -d 'Retrieve Endurance Group Event Aggregate Log'
complete -c nvme -d 'Retrieve LBA Status Information Log'
complete -c nvme -d 'Retrieve Reservation Notification Log'
complete -c nvme -d 'Retrieve Boot Partition Log'
complete -c nvme -d 'Get feature and show the resulting value'
complete -c nvme -d 'Perform the necessary tests to observe the performance'
complete -c nvme -d 'Retrieve the SELF-TEST Log'
complete -c nvme -d 'Retrieve the Supported Log pages details'
complete -c nvme -d 'Retrieve FID Support and Effects log'
complete -c nvme -d 'Retrieve MI Command Support and Effects log'
complete -c nvme -d 'Retrieve the configuration and wear of media units'
complete -c nvme -d 'Retrieve the list of Supported Capacity Configuration Descriptors'
complete -c nvme -d 'Set a feature and show the resulting value'
complete -c nvme -d 'Set a property and show the resulting value'
complete -c nvme -d 'Get a property and show the resulting value'
complete -c nvme -d 'Format namespace with new block format'
complete -c nvme -d 'Verify and commit firmware to a specific slot'
complete -c nvme -d 'Download new firmware'
complete -c nvme -d 'Submit an arbitrary admin command'
complete -c nvme -d 'Submit an arbitrary IO command'
complete -c nvme -d 'Submit a Security Send command'
complete -c nvme -d 'Submit a Security Receive command'
complete -c nvme -d 'Submit a Get LBA Status command'
complete -c nvme -d 'Submit Capacity Management Command'
complete -c nvme -d 'Submit a Reservation Acquire'
complete -c nvme -d 'Submit a Reservation Register'
complete -c nvme -d 'Submit a Reservation Release'
complete -c nvme -d 'Submit a Reservation Report'
complete -c nvme -d 'Submit a Data Set Management command'
complete -c nvme -d 'Submit a Simple Copy command'
complete -c nvme -d 'Submit a Flush command'
complete -c nvme -d 'Submit a Compare command'
complete -c nvme -d 'Submit a read command'
complete -c nvme -d 'Submit a write command'
complete -c nvme -d 'Submit a write zeroes command'
complete -c nvme -d 'Submit a write uncorrectable command'
complete -c nvme -d 'Submit a verify command'
complete -c nvme -d 'Submit a sanitize command'
complete -c nvme -d 'Retrieve sanitize log'
complete -c nvme -d 'Resets the controller'
complete -c nvme -d 'Resets the subsystem'
complete -c nvme -d 'Rescans the NVME namespaces'
complete -c nvme -d 'Shows the controller registers or properties'
complete -c nvme -d 'Discover NVMeoF subsystems'
complete -c nvme -d 'Discover and Connect to NVMeoF subsystems'
complete -c nvme -d 'Connect to NVMeoF subsystem'
complete -c nvme -d 'Disconnect from NVMeoF subsystem'
complete -c nvme -d 'Disconnect from all connected NVMeoF subsystems'
complete -c nvme -d 'Configuration of NVMeoF subsystems'
complete -c nvme -d 'Generate NVMeoF host NQN'
complete -c nvme -d 'Show NVMeoF host NQN'
complete -c nvme -d 'Generate NVMeoF DH-HMAC-CHAP host key'
complete -c nvme -d 'Validate NVMeoF DH-HMAC-CHAP host key'
complete -c nvme -d 'Generate NVMeoF TLS PSK'
complete -c nvme -d 'Validate NVMeoF TLS PSK'
complete -c nvme -d 'Submit a Directive Receive command'
complete -c nvme -d 'Submit a Directive Send command'
complete -c nvme -d 'Manage Flexible Resources between Primary and Secondary Controller '
complete -c nvme -d 'Replay Protection Memory Block commands'
complete -c nvme -d 'Submit Lockdown command'
complete -c nvme -d 'Send Discovery Information Management command to a Discovery Controller'
complete -c nvme -d 'Show  version'
complete -c nvme -d 'Display help'
complete -c nvme -s 'f' -l 'output-format' -d 'Output format'
complete -c nvme -s 'f' -l 'output-format' -d 'Output format'
complete -c nvme -s 'h' -l 'help' -d 'Display help'
complete -c nvme -d 'NVME device'
