complete -c obnam -d 'Add a key to the repository'
complete -c obnam -d 'Backup data to repository'
complete -c obnam -d 'List clients and their keys in the repository'
complete -c obnam -d 'List clients using the repository'
complete -c obnam -d 'Show difference between two generations'
complete -c obnam -d 'Dump (some) data structures from a repository'
complete -c obnam -d 'Force a locked repository to be open'
complete -c obnam -d 'Forget (remove) specified backup generations'
complete -c obnam -d 'Verify internal consistency of backup repository'
complete -c obnam -d 'List backup generations for client'
complete -c obnam -d 'List generation ids for client'
complete -c obnam -d 'Print help'
complete -c obnam -d 'Print help, including hidden subcommands'
complete -c obnam -d 'List contents of a generation in kdirstat cache format'
complete -c obnam -d 'List error codes and explanations'
complete -c obnam -d 'List available repository formats'
complete -c obnam -d 'List keys and repository toplevels they are used in'
complete -c obnam -d 'List repository toplevel directories and their keys'
complete -c obnam -d 'List contents of a generation'
complete -c obnam -d 'Mount a backup repository as a FUSE filesystem'
complete -c obnam -d 'Check if the most recent generation is recent enough'
complete -c obnam -d 'Remove client and its key from repository'
complete -c obnam -d 'Remove a key from the repository'
complete -c obnam -d 'Restore some or all files from a generation'
complete -c obnam -d 'Verify that live data and backed up data match'
complete -c obnam -l 'always-restore-setuid' -d 'Restore setuid/setgid bits in restored files'
complete -c obnam -l 'no-always-restore-setuid' -d 'Do not restore setuid/setgid bits in restored files'
complete -c obnam -l 'checksum-algorithm' -d 'Use CHECKSUM algorithm'
complete -c obnam -l 'client-name' -d 'Name of client'
complete -c obnam -l 'compress-with' -d 'Compress repository with'
complete -c obnam -l 'critical-age' -d 'For --nagios-last-backup-age: maximum age'
complete -c obnam -l 'dump-repo-file-metadata' -d 'Dump metadata about files'
complete -c obnam -l 'no-dump-repo-file-metadata' -d 'Do not dump metadata about files'
complete -c obnam -l 'generate-manpage' -d 'Generate man page'
complete -c obnam -l 'generation' -d 'Which generation to restore'
complete -c obnam -s 'h' -l 'help' -d 'Show this help message and exit'
complete -c obnam -l 'keep' -d 'Policy for what generations to keep when forgetting.'
complete -c obnam -l 'lock-timeout' -d 'Wait TIMEOUT seconds for an existing lock'
complete -c obnam -l 'output' -d 'Write output to FILE instead of STDOUT'
complete -c obnam -l 'pretend' -l 'dry-run' -l 'no-act' -d 'Do not actually change anything'
complete -c obnam -l 'no-pretend' -l 'no-dry-run' -l 'no-no-act' -d 'Actually commit changes'
complete -c obnam -l 'quiet' -d 'Show only errors, no progress updates'
complete -c obnam -l 'no-quiet' -d 'Show errors and progress updates'
complete -c obnam -s 'r' -l 'repository' -d 'Name of backup repository'
complete -c obnam -l 'repository-format' -d 'Use FORMAT for new repositories'
complete -c obnam -l 'to' -d 'Where to restore / mount to'
complete -c obnam -l 'verbose' -d 'Be more verbose'
complete -c obnam -l 'no-verbose' -d 'Do not be verbose'
complete -c obnam -l 'verify-randomly' -d 'Verify N files randomly from the backup'
complete -c obnam -l 'version' -d 'Show version number and exit'
complete -c obnam -l 'warn-age' -d 'For nagios-last-backup-age: maximum age'
complete -c obnam -l 'checkpoint' -d 'Make a checkpoint after a given SIZE'
complete -c obnam -l 'deduplicate' -d 'Deduplicate mode'
complete -c obnam -l 'exclude' -d 'REGEXP for pathnames to exclude'
complete -c obnam -l 'exclude-caches' -d 'Exclude directories tagged as cache'
complete -c obnam -l 'no-exclude-caches' -d 'Include directories tagged as cache'
complete -c obnam -l 'exclude-from' -d 'Read exclude patterns from FILE'
complete -c obnam -l 'include' -d 'REGEXP for pathnames to include, even if matches --exclude'
complete -c obnam -l 'leave-checkpoints' -d 'Leave checkpoint generations at the end of backup'
complete -c obnam -l 'no-leave-checkpoints' -d 'Omit checkpoint generations at the end of backup'
complete -c obnam -l 'one-file-system' -d 'Do not follow mount points'
complete -c obnam -l 'no-one-file-system' -d 'Follow mount points'
complete -c obnam -l 'root' -d 'What to backup'
complete -c obnam -l 'small-files-in-btree' -d 'Put small files directly into the B-tree'
complete -c obnam -l 'no-small-files-in-btree' -d 'No not put small files into the B-tree'
complete -c obnam -l 'config' -d 'Add FILE to config files'
complete -c obnam -l 'dump-config' -d 'Write out the current configuration'
complete -c obnam -l 'dump-setting-names' -d 'Write out setting names'
complete -c obnam -l 'help-all' -d 'Show all options'
complete -c obnam -l 'list-config-files' -d 'List config files'
complete -c obnam -l 'no-default-configs' -d 'Clear list of configuration files to read'
complete -c obnam -l 'crash-limit' -d 'Artificially crash the program after COUNTER files'
complete -c obnam -l 'pretend-time' -d 'Pretend it is TIMESTAMP'
complete -c obnam -l 'testing-fail-matching' -d 'Simulate failures for files that match REGEXP'
complete -c obnam -l 'trace' -d 'FILENAME pattern for trace debugging'
complete -c obnam -l 'encrypt-with' -d 'PGP key with which to encrypt'
complete -c obnam -l 'gnupghome' -d 'Home directory for GPG'
complete -c obnam -l 'key-details' -d 'Show additional user IDs'
complete -c obnam -l 'no-key-details' -d 'Do not show additional user IDs'
complete -c obnam -l 'keyid' -d 'PGP key id'
complete -c obnam -l 'symmetric-key-bits' -d 'Size of symmetric key'
complete -c obnam -l 'weak-random' -d 'Use /dev/urandom instead of /dev/random'
complete -c obnam -l 'no-weak-random' -d 'Use default /dev/random'
complete -c obnam -l 'fsck-fix' -d 'fsck should try to fix problems'
complete -c obnam -l 'no-fsck-fix' -d 'fsck should not try to fix problems'
complete -c obnam -l 'fsck-ignore-chunks' -d 'Ignore chunks when checking integrity'
complete -c obnam -l 'no-fsck-ignore-chunks' -d 'Check chunks when checking integrity'
complete -c obnam -l 'fsck-ignore-client' -d 'Do not check data for cient NAME'
complete -c obnam -l 'fsck-last-generation-only' -d 'Check only the last generation'
complete -c obnam -l 'no-fsck-last-generation-only' -d 'Check all generations'
complete -c obnam -l 'fsck-rm-unused' -d 'fsck should remove unused chunks'
complete -c obnam -l 'no-fsck-rm-unused' -d 'fsck should remove unused chunks'
complete -c obnam -l 'fsck-skip-checksums' -d 'Do not check checksums of files'
complete -c obnam -l 'no-fsck-skip-checksums' -d 'Check checksums of files'
complete -c obnam -l 'fsck-skip-dirs' -d 'Do not check directories'
complete -c obnam -l 'no-fsck-skip-dirs' -d 'Check directories'
complete -c obnam -l 'fsck-skip-files' -d 'Do not check files'
complete -c obnam -l 'no-fsck-skip-files' -d 'Check files'
complete -c obnam -l 'fsck-skip-generations' -d 'Do not check any generations'
complete -c obnam -l 'no-fsck-skip-generations' -d 'Check all generations'
complete -c obnam -l 'fsck-skip-per-client-b-trees' -d 'Do not check per-client B-trees'
complete -c obnam -l 'no-fsck-skip-per-client-b-trees' -d 'Check per-client B-trees'
complete -c obnam -l 'fsck-skip-shared-b-trees' -d 'Do not check shared B-trees'
complete -c obnam -l 'no-fsck-skip-shared-b-trees' -d 'Check shared B-trees'
complete -c obnam -l 'log' -d 'Write log to FILE or syslog'
complete -c obnam -l 'log-keep' -d 'Keep last N logs (10)'
complete -c obnam -l 'log-level' -d 'Log at LEVEL'
complete -c obnam -l 'log-max' -d 'Rotate logs larger than SIZE'
complete -c obnam -l 'log-mode' -d 'Set permissions of logfiles to MODE'
complete -c obnam -l 'fuse-opt' -d 'Options to pass to FUSE'
complete -c obnam -l 'dump-memory-profile' -d 'Make memory profiling dumps using METHOD'
complete -c obnam -l 'memory-dump-interval' -d 'Make memory profiling dumps at SECONDS'
complete -c obnam -l 'chunk-size' -d 'Size of chunks of file data'
complete -c obnam -l 'chunkids-per-group' -d 'Encode NUM chunk ids per group'
complete -c obnam -l 'idpath-bits' -d 'Chunk id level size'
complete -c obnam -l 'idpath-depth' -d 'Depth of chunk id mapping'
complete -c obnam -l 'idpath-skip' -d 'Chunk id mapping lowest bits skip'
complete -c obnam -l 'lru-size' -d 'Size of LRU cache for B-tree nodes'
complete -c obnam -l 'node-size' -d 'Size of B-tree nodes on disk'
complete -c obnam -l 'upload-queue-size' -d 'Length of upload queue for B-tree nodes'
complete -c obnam -l 'chunk-bag-size' -d 'Approx max SIZE of bag combining chunk objects'
complete -c obnam -l 'chunk-cache-size' -d 'In-memory cache SIZE for chunk objects'
complete -c obnam -l 'dir-bag-size' -d 'Approx max SIZE of bags combining dir objects'
complete -c obnam -l 'dir-cache-size' -d 'In-memory cache SIZE for dir objects'
complete -c obnam -l 'pure-paramiko' -d 'Use only paramiko, no openssh'
complete -c obnam -l 'no-pure-paramiko' -d 'Use openssh if available'
complete -c obnam -l 'ssh-command' -d 'Executable to be used instead of "ssh"'
complete -c obnam -l 'ssh-host-keys-check' -d 'ssh host key check'
complete -c obnam -l 'ssh-key' -d 'Use FILENAME as the ssh RSA key'
complete -c obnam -l 'ssh-known-hosts' -d 'FILENAME of the known_hosts file'
