complete -c octave -s 'h' -l 'help' -d 'Show help'
complete -c octave -s 'v' -l 'version' -d 'Show version'
complete -c octave -l 'built-in-docstrings-file' -d 'Use docs for built-ins'
complete -c octave -s 'd' -l 'debug' -d 'Enter parser debugging mode'
complete -c octave -l 'debug-jit' -d 'Enable JIT compiler debugging/tracing'
complete -c octave -l 'doc-cache-file' -d 'Use doc cache file'
complete -c octave -s 'x' -l 'echo-commands' -d 'Echo commands as they are executed'
complete -c octave -l 'eval' -d 'Evaluate code'
complete -c octave -l 'exec-path' -d 'Set path for executing subprograms'
complete -c octave -l 'gui' -d 'Start the graphical user interface'
complete -c octave -l 'image-path' -d 'Add path to head of image search path'
complete -c octave -l 'info-file' -d 'Use top-level info file'
complete -c octave -l 'info-program' -d 'Specify program for reading info files'
complete -c octave -s 'i' -l 'interactive' -d 'Force interactive behavior'
complete -c octave -l 'jit-compiler' -d 'Enable the JIT compiler'
complete -c octave -l 'line-editing' -d 'Force readline use for command-line editing'
complete -c octave -l 'no-gui' -d 'Disable the graphical user interface'
complete -c octave -s 'W' -l 'no-window-system' -d 'Disable window system, including graphics'
complete -c octave -s 'p' -l 'path' -d 'Add path to head of function search path'
complete -c octave -l 'persist' -d 'Go interactive after --eval or reading'
complete -c octave -l 'texi-macros-file' -d 'Use Texinfo macros for makeinfo command'
complete -c octave -l 'traditional' -d 'Set variables for closer MATLAB compatibility'
complete -c octave -s 'V' -l 'verbose' -d 'Enable verbose output in some cases'
