complete -c oggenc -s 'Q' -l 'quiet' -d 'Produce no output to stderr'
complete -c oggenc -s 'h' -l 'help' -d 'Print this help text'
complete -c oggenc -s 'v' -l 'version' -d 'Print the version number'
complete -c oggenc -s 'r' -l 'raw' -d 'Raw mode. Input files are read directly as PCM data'
complete -c oggenc -s 'B' -l 'raw-bits' -d 'Set bits/sample for raw input (default 16)'
complete -c oggenc -s 'C' -l 'raw-chan' -d 'Set number of channels for raw input'
complete -c oggenc -s 'R' -l 'raw-rate' -d 'Set samples/sec for raw input'
complete -c oggenc -l 'raw-endianness' -d '1 for bigendian, 0 for little (default 0)'
complete -c oggenc -s 'b' -l 'bitrate' -d 'Choose a nominal bitrate to encode at'
complete -c oggenc -l 'managed' -d 'Enable the bitrate management engine'
complete -c oggenc -s 'm' -l 'min-bitrate' -d 'Specify a minimum bitrate in kbps'
complete -c oggenc -s 'M' -l 'max-bitrate' -d 'Specify a maximum bitrate in kbps'
complete -c oggenc -l 'advanced-encode-option' -d 'option=value Set an advanced encoder option to the given value'
complete -c oggenc -s 'q' -l 'quality' -d 'Specify quality'
complete -c oggenc -l 'resample' -d 'Resample input data to sampling rate n (Hz)'
complete -c oggenc -l 'downmix' -d 'Downmix stereo to mono'
complete -c oggenc -s 's' -l 'serial' -d 'Specify a serial number for the stream'
complete -c oggenc -l 'discard-comments' -d 'Don'"'"'t copy comments to the output file'
complete -c oggenc -s 'o' -l 'output' -d 'Write file to fn (only valid in single-file mode)'
complete -c oggenc -s 'n' -l 'names' -d 'Produce filenames as this string'
complete -c oggenc -s 'X' -l 'name-remove=' -d 'Remove the specified characters from parameters'
complete -c oggenc -s 'P' -l 'name-replace=' -d 'Replace characters removed by --name-remove'
complete -c oggenc -s 'c' -l 'comment' -d 'Add the given string as an extra comment'
complete -c oggenc -s 'd' -l 'date' -d 'Date for track'
complete -c oggenc -s 'N' -l 'tracknum' -d 'Track number'
complete -c oggenc -s 't' -l 'title' -d 'Title of track'
complete -c oggenc -s 'l' -l 'album' -d 'Name of album'
complete -c oggenc -s 'a' -l 'artist' -d 'Name of artist'
complete -c oggenc -s 'G' -l 'genre' -d 'Genre of track'
