complete -c ollama -d 'Start ollama'
complete -c ollama -d 'Create a model from a Modelfile'
complete -c ollama -d 'Show information for a model'
complete -c ollama -d 'Run a model'
complete -c ollama -d 'Pull a model from a registry'
complete -c ollama -d 'Push a model to a registry'
complete -c ollama -d 'List models'
complete -c ollama -d 'Copy a model'
complete -c ollama -d 'Remove a model'
complete -c ollama -d 'Help about any command'
complete -c ollama -s 'h' -l 'help' -d 'help for ollama'
complete -c ollama -s 'v' -l 'version' -d 'Show version information'
