complete -c opam -l 'help' -d 'Display the manual for an OPAM command'
complete -c opam -l 'version' -d 'Show version information'
complete -c opam -l 'color' -d 'Colorize the output'
complete -c opam -l 'compat-mode-1.0' -d 'Compatibility mode with OPAM 1.0'
complete -c opam -l 'debug' -d 'Print debug message on stdout'
complete -c opam -l 'git-version' -d 'Print the git version if it exists and exit'
complete -c opam -l 'no-aspcud' -d 'Do not use the external aspcud solver, even if available'
complete -c opam -l 'no-base-packages' -d 'Do not install base packages'
complete -c opam -s 'q' -l 'quiet' -d 'Be quiet when installing a new compiler'
complete -c opam -s 'r' -l 'root' -d 'Use ROOT as the current root path'
complete -c opam -l 'strict' -d 'Fail whenever an error is found in a package definition or a configuration file'
complete -c opam -l 'switch' -d 'Use SWITCH as the current compiler switch'
complete -c opam -s 'v' -l 'verbose' -d 'Be more verbose'
complete -c opam -s 'y' -l 'yes' -d 'Disable interactive mode and answer yes to all questions'
complete -c opam -d 'Display configuration options for packages'
complete -c opam -s 'a' -l 'all' -d 'Enable all the global and user configuration options'
complete -c opam -l 'csh' -d 'Use csh-compatible mode for configuring OPAM'
complete -c opam -l 'dot-profile' -d 'Name of the configuration file to update instead of ~/'
complete -c opam -s 'e' -d 'Backward-compatible option, equivalent to opam config env'
complete -c opam -l 'fish' -d 'Use fish-compatible mode for configuring OPAM'
complete -c opam -s 'g' -l 'global' -d 'Enable all the global configuration options'
complete -c opam -s 'l' -l 'list' -d 'List the current configuration'
complete -c opam -l 'no-complete' -d 'Do not load the auto-completion scripts in the environment'
complete -c opam -l 'no-switch-eval' -d 'Do not install `opam-switch-eval`'
complete -c opam -l 'ocamlinit' -d 'Modify ~/'
complete -c opam -l 'profile' -d 'Modify ~/. profile'
complete -c opam -s 'R' -l 'rec' -d 'Recursive query'
complete -c opam -l 'sexp' -d 'Display environment variables as an s-expression'
complete -c opam -l 'sh' -d 'Use sh-compatible mode for configuring OPAM'
complete -c opam -s 'u' -l 'user' -d 'Enable all the user configuration options'
complete -c opam -l 'zsh' -d 'Use zsh-compatible mode for configuring OPAM.  DOMAINS'
complete -c opam -d 'Return PATH, MANPATH, OCAML_TOPLEVEL_PATH and CAML_LD_LIBRARY_PATH for compiler'
complete -c opam -d 'Configure global and user parameters for OPAM'
complete -c opam -d 'Execute the shell script given in parameter with the correct environment variables'
complete -c opam -d 'Return the value associated with the given variable'
complete -c opam -d 'Return the list of all variables defined in the listed packages'
complete -c opam -d 'Substitute %{var}% variables'
complete -c opam -d 'returns include options'
complete -c opam -d 'returns bytecode compile options'
complete -c opam -d 'returns assembly compile options'
complete -c opam -d 'returns bytecode linking options'
complete -c opam -d 'Prints a summary of your setup, useful for bug-reports'
complete -c opam -d 'Display help about OPAM and OPAM commands'
complete -c opam -d 'Initialize OPAM state'
complete -c opam -d 'Install a list of packages'
complete -c opam -d 'Display the list of available packages'
complete -c opam -d 'Pin a given package to a specific version'
complete -c opam -d 'Reinstall a list of packages'
complete -c opam -d 'Remove a list of packages'
complete -c opam -d 'Manage OPAM repositories'
complete -c opam -d 'Search into the package list'
complete -c opam -d 'Display information about specific packages'
complete -c opam -d 'Manage multiple installation of compilers'
complete -c opam -d 'Update the list of available packages'
complete -c opam -d 'Upgrade the installed package to latest version'
complete -c opam -d 'Administration tool for local repositories'
complete -c opam -l 'help' -d 'Show this help in format FMT (pager, plain or groff)'
complete -c opam -l 'version' -d 'Show version information'
complete -c opam -d 'Check a local repo for errors'
complete -c opam -d 'Add external dependencies'
complete -c opam -d 'Initialize a repo for serving files'
complete -c opam -d 'Compute statistics'
complete -c opam -d 'Create a new switch, and install the given compiler there'
complete -c opam -d 'Set the currently active switch'
complete -c opam -d 'Remove the given switch from disk'
complete -c opam -d 'Save the current switch state to a file'
complete -c opam -d 'Import a saved switch state'
complete -c opam -d 'Reinstall the given compiler switch and all its packages'
complete -c opam -d 'Lists installed switches'
complete -c opam -d 'Lists base packages that can be used to create a new switch'
complete -c opam -d 'Prints the name of the current switch'
complete -c opam -d 'Sets the packages forming the immutable base for the selected switch'
complete -c opam -d 'Sets a local alias for a given switch'
