complete -c opkg -d 'Package'
complete -c opkg -d 'Package'
complete -c opkg -d 'Update list of available packages'
complete -c opkg -d 'Upgrade packages'
complete -c opkg -d 'Install package(s)'
complete -c opkg -d 'Configure unpacked package(s)'
complete -c opkg -d 'Remove package(s)'
complete -c opkg -d 'Flag package(s)'
complete -c opkg -d 'List available packages'
complete -c opkg -d 'List installed packages'
complete -c opkg -d 'List installed and upgradable packages'
complete -c opkg -d 'List user modified configuration files'
complete -c opkg -d 'List files belonging to <pkg>'
complete -c opkg -d 'List package providing <file>'
complete -c opkg -d 'List packages whose name or description matches <regexp>'
complete -c opkg -d 'Display all info for <pkg>'
complete -c opkg -d 'Display all status for <pkg>'
complete -c opkg -d 'Download <pkg> to current directory'
complete -c opkg -d 'compare versions using <= < > >= = << >>'
complete -c opkg -d 'List installable package architectures'
complete -c opkg -d 'list depends'
complete -c opkg -d 'list whatdepends'
complete -c opkg -d 'list whatdepends recursively'
complete -c opkg -d 'list whatrecommends'
complete -c opkg -d 'list whatsuggests'
complete -c opkg -d 'list whatprovides'
complete -c opkg -d 'list whatconflicts'
complete -c opkg -d 'list whatreplaces'
complete -c opkg -s 'A' -d 'Query all packages not just those installed'
complete -c opkg -s 'V' -l 'verbosity' -d 'Set verbosity level to <level>'
complete -c opkg -s 'f' -l 'conf' -d 'Use <conf_file> as the opkg configuration file'
complete -c opkg -l 'cache' -d 'Use a package cache'
complete -c opkg -s 'd' -l 'dest' -d 'Use <dest_name> as the root directory'
complete -c opkg -s 'o' -l 'offline-root' -d 'Use <dir> as the root directory for offline'
complete -c opkg -l 'add-arch' -d 'Register architecture with given priority'
complete -c opkg -l 'add-dest' -d 'Register destination with given path'
complete -c opkg -l 'force-depends' -d 'Install/remove despite failed dependencies'
complete -c opkg -l 'force-maintainer' -d 'Overwrite preexisting config files'
complete -c opkg -l 'force-reinstall' -d 'Reinstall package(s)'
complete -c opkg -l 'force-overwrite' -d 'Overwrite files from other package(s)'
complete -c opkg -l 'force-downgrade' -d 'Allow opkg to downgrade packages'
complete -c opkg -l 'force-space' -d 'Disable free space checks'
complete -c opkg -l 'force-postinstall' -d 'Run postinstall scripts even in offline mode'
complete -c opkg -l 'force-remove' -d 'Remove package even if prerm script fails'
complete -c opkg -l 'noaction' -d 'No action -- test only'
complete -c opkg -l 'download-only' -d 'No action -- download only'
complete -c opkg -l 'nodeps' -d 'Do not follow dependencies'
complete -c opkg -l 'nocase' -d 'Perform case insensitive pattern matching'
complete -c opkg -l 'size' -d 'Print package size when listing available packages'
complete -c opkg -l 'force-removal-of-dependent-packages' -d 'Remove package and all dependencies'
complete -c opkg -l 'autoremove' -d 'Remove automatically installed packages'
complete -c opkg -s 't' -l 'tmp-dir' -d 'Specify tmp-dir.'
complete -c opkg -s 'l' -l 'lists-dir' -d 'Specify lists-dir.'
