complete -c ouch -s 'y' -l 'yes' -d 'Skip [Y/n] questions positively'
complete -c ouch -s 'n' -l 'no' -d 'Skip [Y/n] questions negatively'
complete -c ouch -s 'A' -l 'accessible' -d 'Activate accessibility mode, reducing visual noise [env: ACCESSIBLE=]'
complete -c ouch -s 'H' -l 'hidden' -d 'Ignores hidden files'
complete -c ouch -s 'g' -l 'gitignore' -d 'Ignores files matched by git'"'"'s ignore files'
complete -c ouch -s 'h' -l 'help' -d 'Print help information (use `--help` for more detail)'
complete -c ouch -s 'V' -l 'version' -d 'Print version information'
