complete -c p4 -s 'b' -d 'Number of arguments when using -x flag'
complete -c p4 -s 'c' -d 'Overrides P4CLIENT settings'
complete -c p4 -s 'd' -d 'Overrides PWD settings'
complete -c p4 -s 'I' -d 'Show process indicators'
complete -c p4 -s 'G' -d 'python dict in/output'
complete -c p4 -s 'H' -d 'Overrides P4HOST settings'
complete -c p4 -s 'p' -d 'Overrides P4PORT settings'
complete -c p4 -s 'P' -d 'Overrides P4PASSWD settings'
complete -c p4 -s 'r' -d 'Number of retry attempts'
complete -c p4 -s 's' -d 'Prefix for each line'
complete -c p4 -s 'u' -d 'Overrides P4USER/USER/USERNAME settings'
complete -c p4 -s 'x' -d 'Read arguments from file'
complete -c p4 -s 'C' -d 'Overrides P4CHARSET settings'
complete -c p4 -s 'Q' -d 'Overrides P4COMMANDCHARSET settings'
complete -c p4 -s 'L' -d 'Feature reserved for system integrators'
complete -c p4 -s 'z' -d 'fstat output'
complete -c p4 -s 'q' -d 'Quiet mode'
complete -c p4 -s 'V' -d 'Display version'
complete -c p4 -s 'h' -d 'Display help'
