complete -c pacaur -d 'Modify the package database'
complete -c pacaur -d 'Query the package database'
complete -c pacaur -d 'Manage .pac* files'
complete -c pacaur -s 'D' -l 'database' -d 'Modify the package database'
complete -c pacaur -s 'Q' -l 'query' -d 'Query the package database'
complete -c pacaur -s 'R' -l 'remove' -d 'Remove packages from the system'
complete -c pacaur -s 'S' -l 'sync' -d 'Synchronize packages'
complete -c pacaur -s 'T' -l 'deptest' -d 'Check dependencies'
complete -c pacaur -s 'U' -l 'upgrade' -d 'Upgrade or add a local package'
complete -c pacaur -s 'F' -l 'files' -d 'Query the files database'
complete -c pacaur -s 'V' -l 'version' -d 'Display version and exit'
complete -c pacaur -s 'h' -l 'help' -d 'Display help'
complete -c pacaur -s 's' -l 'search' -d '(AUR) Search for packages'
complete -c pacaur -s 'i' -l 'info' -d '(AUR) Show info for packages'
complete -c pacaur -s 'm' -l 'makepkg' -d '(AUR) Clone the packages'"'"' build files and build them'
complete -c pacaur -s 'y' -l 'sync' -d '(AUR) Clone build files, build and install packages'
complete -c pacaur -s 'k' -l 'check' -d '(AUR) Check foreign packages for updates'
complete -c pacaur -s 'u' -l 'update' -d '(AUR) Update foreign packages'
complete -c pacaur -s 'd' -l 'download' -d '(AUR) Clone the packages'"'"' build files'
complete -c pacaur -s 'd' -l 'download' -d 'Download dependencies recursively'
complete -c pacaur -s 'b' -l 'dbpath' -d 'Alternative database location'
complete -c pacaur -s 'r' -l 'root' -d 'Alternative installation root'
complete -c pacaur -s 'v' -l 'verbose' -d 'Output more status messages'
complete -c pacaur -l 'arch' -d 'Alternate architecture'
complete -c pacaur -l 'cachedir' -d 'Alternative package cache location'
complete -c pacaur -l 'config' -d 'Alternate config file'
complete -c pacaur -l 'debug' -d 'Display debug messages'
complete -c pacaur -l 'gpgdir' -d 'GPG directory to verify signatures'
complete -c pacaur -l 'hookdir' -d 'Hook file directory'
complete -c pacaur -l 'logfile' -d 'Specify alternative log file'
complete -c pacaur -l 'noconfirm' -d 'Bypass any question'
complete -c pacaur -s 'a' -l 'aur' -d 'Apply only for AUR targets'
complete -c pacaur -s 'r' -l 'repo' -d 'Apply only for specified repo'
complete -c pacaur -s 'r' -l 'edit' -d 'Edit build files'
complete -c pacaur -l 'noedit' -d 'Do not edit build files'
complete -c pacaur -l 'rebuild' -d 'Always rebuild packages'
complete -c pacaur -l 'silent' -d 'Redirect output to the log in the clone directory'
complete -c pacaur -l 'domain' -d 'Point at a domain other than the default aur.archlinux.org'
complete -c pacaur -l 'devel' -d 'Use devel packages'
complete -c pacaur -l 'ignore-ood' -d 'Ignore all results marked as out of date'
complete -c pacaur -l 'no-ignore-ood' -d 'Do not ignore all results marked as out of date'
complete -c pacaur -l 'sort' -d 'Sort ascending by key'
complete -c pacaur -l 'rsort' -d 'Sort descending by key'
complete -c pacaur -l 'by' -d 'Search by field'
complete -c pacaur -s 'c' -l 'changelog' -d 'View the change log of PACKAGE'
complete -c pacaur -s 'd' -l 'deps' -d 'List only non-explicit packages (dependencies)'
complete -c pacaur -s 'e' -l 'explicit' -d 'List only explicitly installed packages'
complete -c pacaur -s 'k' -l 'check' -d 'Check if all files owned by PACKAGE are present'
complete -c pacaur -s 'l' -l 'list' -d 'List all files owned by PACKAGE'
complete -c pacaur -s 'm' -l 'foreign' -d 'List all packages not in the database'
complete -c pacaur -s 'o' -l 'owns' -d 'Search for the package that owns FILE'
complete -c pacaur -s 'p' -l 'file' -d 'Apply the query to a package file, not package'
complete -c pacaur -s 't' -l 'unrequired' -d 'List only unrequired packages'
complete -c pacaur -s 'u' -l 'upgrades' -d 'List only out-of-date packages'
complete -c pacaur -d 'Installed package'
complete -c pacaur -s 'c' -l 'cascade' -d 'Also remove packages depending on PACKAGE'
complete -c pacaur -s 'n' -l 'nosave' -d 'Ignore file backup designations'
complete -c pacaur -s 's' -l 'recursive' -d 'Also remove dependencies of PACKAGE'
complete -c pacaur -s 'u' -l 'unneeded' -d 'Only remove targets not required by PACKAGE'
complete -c pacaur -d 'Installed package'
complete -c pacaur -s 'c' -l 'clean' -d 'Remove [all] packages from cache'
complete -c pacaur -s 'l' -l 'list' -d 'List all packages in REPOSITORY'
complete -c pacaur -s 'u' -l 'sysupgrade' -d 'Upgrade all packages that are out of date'
complete -c pacaur -s 'u' -l 'sysupgrade' -d 'Also downgrade packages'
complete -c pacaur -s 'w' -l 'downloadonly' -d 'Only download the target packages'
complete -c pacaur -s 'y' -l 'refresh' -d 'Download fresh copy of the package list'
complete -c pacaur -d 'Mark PACKAGE as dependency'
complete -c pacaur -d 'Mark PACKAGE as explicitly installed'
complete -c pacaur -s 'k' -l 'check' -d 'Check database validity'
complete -c pacaur -d 'List files owned by given packages'
complete -c pacaur -l '-d'
complete -c pacaur -d 'Search packages for matching files'
complete -c pacaur -s '-d'
complete -c pacaur -s 'y' -l 'refresh' -d 'Refresh the files database'
complete -c pacaur -s 'l' -l 'list' -d 'List files owned by given packages'
complete -c pacaur -s 's' -l 'search' -d 'Search packages for matching files'
complete -c pacaur -s 'o' -l 'owns' -d 'Search for packages that include the given files'
complete -c pacaur -s 'q' -l 'quiet' -d 'Show less information'
complete -c pacaur -l 'machinereadable' -d 'Show in machine readable format'
complete -c pacaur -d 'Package file'
