complete -c pacman -d 'Modify the package database'
complete -c pacman -d 'Query the package database'
complete -c pacman -s 'D' -l 'database' -d 'Modify the package database'
complete -c pacman -s 'Q' -l 'query' -d 'Query the package database'
complete -c pacman -s 'R' -l 'remove' -d 'Remove packages from the system'
complete -c pacman -s 'S' -l 'sync' -d 'Synchronize packages'
complete -c pacman -s 'T' -l 'deptest' -d 'Check dependencies'
complete -c pacman -s 'U' -l 'upgrade' -d 'Upgrade or add a local package'
complete -c pacman -s 'F' -l 'files' -d 'Query the files database'
complete -c pacman -s 'V' -l 'version' -d 'Display version and exit'
complete -c pacman -s 'h' -l 'help' -d 'Display help'
complete -c pacman -s 'b' -l 'dbpath' -d 'Alternate database location'
complete -c pacman -s 'r' -l 'root' -d 'Alternate installation root'
complete -c pacman -s 'v' -l 'verbose' -d 'Output more status messages'
complete -c pacman -l 'arch' -d 'Alternate architecture'
complete -c pacman -l 'cachedir' -d 'Alternate package cache location'
complete -c pacman -l 'color' -d 'Colorize the output'
complete -c pacman -l 'config' -d 'Alternate config file'
complete -c pacman -l 'confirm' -d 'Always ask for confirmation'
complete -c pacman -l 'debug' -d 'Display debug messages'
complete -c pacman -l 'disable-download-timeout' -d 'Use relaxed timeouts for download'
complete -c pacman -l 'gpgdir' -d 'Alternate home directory for GnuPG'
complete -c pacman -l 'hookdir' -d 'Alternate hook location'
complete -c pacman -l 'logfile' -d 'Alternate log file'
complete -c pacman -l 'noconfirm' -d 'Bypass any confirmation'
complete -c pacman -l 'sysroot' -d 'Operate on a mounted guest system (root-only)'
complete -c pacman -s 'k' -l 'check' -d 'Check database validity'
complete -c pacman -s 'q' -l 'quiet' -d 'Suppress output of success messages'
complete -c pacman -l 'asdeps' -d 'Mark PACKAGE as dependency'
complete -c pacman -l 'asexplicit' -d 'Mark PACKAGE as explicitly installed'
complete -c pacman -s 'x' -l 'regex' -d 'Interpret each query as a regular expression'
complete -c pacman -l 'machinereadable' -d 'Print each match in a machine readable output format'
complete -c pacman -d 'Package'
complete -c pacman -s 'c' -l 'changelog' -d 'View the change log of PACKAGE'
complete -c pacman -s 'd' -l 'deps' -d 'List only non-explicit packages (dependencies)'
complete -c pacman -s 'e' -l 'explicit' -d 'List only explicitly installed packages'
complete -c pacman -s 'i' -l 'info' -d 'View PACKAGE [backup files] information'
complete -c pacman -s 'k' -l 'check' -d 'Check that PACKAGE files exist'
complete -c pacman -s 'm' -l 'foreign' -d 'List installed packages not found in sync database'
complete -c pacman -s 'n' -l 'native' -d 'list installed packages only found in sync database'
complete -c pacman -s 'o' -l 'owns' -d 'Query the package that owns FILE'
complete -c pacman -s 'p' -l 'file' -d 'Query a package file instead of the database'
complete -c pacman -s 's' -l 'search' -d 'Search locally-installed packages for regexp'
complete -c pacman -s 't' -l 'unrequired' -d 'List only unrequired packages [and optdepends]'
complete -c pacman -s 'u' -l 'upgrades' -d 'List only out-of-date packages'
complete -c pacman -d 'Installed package'
complete -c pacman -d 'Package file'
complete -c pacman -s 'c' -l 'cascade' -d 'Also remove packages depending on PACKAGE'
complete -c pacman -s 'n' -l 'nosave' -d 'Ignore file backup designations'
complete -c pacman -s 's' -l 'recursive' -d 'Also remove dependencies of PACKAGE'
complete -c pacman -s 'u' -l 'unneeded' -d 'Only remove targets not required by PACKAGE'
complete -c pacman -d 'Installed package'
complete -c pacman -s 'c' -l 'clean' -d 'Remove [all] packages from cache'
complete -c pacman -s 'i' -l 'info' -d 'View PACKAGE [extended] information'
complete -c pacman -s 'l' -l 'list' -d 'List all packages in REPOSITORY'
complete -c pacman -s 's' -l 'search' -d 'Search remote repositories for regexp'
complete -c pacman -s 'u' -l 'sysupgrade' -d 'Upgrade all packages that are out of date'
complete -c pacman -s 'w' -l 'downloadonly' -d 'Only download the target packages'
complete -c pacman -d 'Package file'
