complete -c pactl -d 'Show statistics about memory usage'
complete -c pactl -d 'Show info about the daemon'
complete -c pactl -d 'Show all loaded things of the specified type'
complete -c pactl -d 'Show shorter output'
complete -c pactl -d 'Ask the daemon to exit'
complete -c pactl -d 'Upload a file to the sample cache'
complete -c pactl -d 'Play a sample from the cache'
complete -c pactl -d 'Remove a sample from the cache'
complete -c pactl -l 'version' -d 'Print a short version and exit'
complete -c pactl -s 'h' -l 'help' -d 'Print help text and exit'
