complete -c pandoc -s 'p' -l 'preserve-tabs'
complete -c pandoc -l 'file-scope'
complete -c pandoc -s 's' -l 'standalone'
complete -c pandoc -l 'strip-comments'
complete -c pandoc -l 'toc' -l 'table-of-contents'
complete -c pandoc -l 'no-highlight'
complete -c pandoc -l 'self-contained'
complete -c pandoc -l 'html-q-tags'
complete -c pandoc -l 'ascii'
complete -c pandoc -l 'reference-links'
complete -c pandoc -l 'atx-headers'
complete -c pandoc -s 'N' -l 'number-sections'
complete -c pandoc -l 'listings'
complete -c pandoc -s 'i' -l 'incremental'
complete -c pandoc -l 'section-divs'
complete -c pandoc -l 'natbib' -l 'biblatex'
complete -c pandoc -l 'dump-args'
complete -c pandoc -l 'ignore-args'
complete -c pandoc -l 'verbose'
complete -c pandoc -l 'quiet'
complete -c pandoc -l 'fail-if-warnings'
complete -c pandoc -l 'bash-completion'
complete -c pandoc -l 'list-input-formats'
complete -c pandoc -l 'list-output-formats'
complete -c pandoc -l 'list-extensions'
complete -c pandoc -l 'list-highlight-languages'
complete -c pandoc -l 'list-highlight-styles'
complete -c pandoc -s 'v' -l 'version'
complete -c pandoc -s 'h' -l 'help'
complete -c pandoc -l 'mathml' -l 'webtex' -l 'mathjax' -l 'katex'
complete -c pandoc -l 'katex-stylesheet' -s 'm' -l 'latexmathml'
complete -c pandoc -l 'asciimathml' -l 'mimetex' -l 'jsmath' -l 'gladtex'
complete -c pandoc -s 'c' -l 'css'
complete -c pandoc -s 'f' -s 'r' -l 'from' -l 'read'
complete -c pandoc -s 't' -s 'w' -l 'to' -l 'write'
complete -c pandoc -s 'D' -l 'print-default-template'
complete -c pandoc -l 'data-dir'
complete -c pandoc -l 'extract-media'
complete -c pandoc -s 'o' -l 'output'
complete -c pandoc -s 'F' -l 'filter'
complete -c pandoc -l 'template'
complete -c pandoc -l 'syntax-definition'
complete -c pandoc -s 'H' -l 'include-in-header'
complete -c pandoc -s 'B' -l 'include-before-body'
complete -c pandoc -s 'A' -l 'include-after-body'
complete -c pandoc -l 'abbreviations'
complete -c pandoc -l 'log'
complete -c pandoc -l 'epub-cover-image'
complete -c pandoc -l 'epub-metadata'
complete -c pandoc -l 'epub-embed-font'
complete -c pandoc -l 'citation-abbreviations'
complete -c pandoc -l 'print-highlight-style'
complete -c pandoc -l 'highlight_style'
complete -c pandoc -l 'csl'
complete -c pandoc -l 'reference-file'
complete -c pandoc -l 'bibliography'
complete -c pandoc -l 'lua-filter'
complete -c pandoc -s 'F' -l 'filter'
complete -c pandoc -l 'template'
complete -c pandoc -l 'lua-filter'
complete -c pandoc -l 'indented-code-classes'
complete -c pandoc -s 'M' -l 'metadata'
complete -c pandoc -s 'V' -l 'variable'
complete -c pandoc -l 'dpi'
complete -c pandoc -l 'columns'
complete -c pandoc -l 'resource-path'
complete -c pandoc -l 'request-header'
complete -c pandoc -l 'number-offset'
complete -c pandoc -l 'id-prefix'
complete -c pandoc -s 'T' -l 'title-prefix'
complete -c pandoc -l 'epub-subdirectory'
complete -c pandoc -l 'pdf-engine-opt'
complete -c pandoc -l 'default-image-extension'
complete -c pandoc -l 'base-header-level'
complete -c pandoc -l 'toc-depth' -l 'slide-level' -l 'epub-chapter-level'
complete -c pandoc -l 'tab-stop'
complete -c pandoc -l 'track-changes'
complete -c pandoc -l 'print-default-data-file'
complete -c pandoc -l 'print-highlight-style' -l 'highlight-style'
complete -c pandoc -l 'eol'
complete -c pandoc -l 'wrap'
complete -c pandoc -l 'reference-location'
complete -c pandoc -l 'top-level-division'
complete -c pandoc -l 'email-obfuscation'
complete -c pandoc -l 'pdf-engine'
