complete -c path -s 'h' -l 'help' -d 'Display help and exit'
complete -c path -d 'Give basename for given paths'
complete -c path -d 'Give dirname for given paths'
complete -c path -d 'Give extension for given paths'
complete -c path -d 'Change extension for given paths'
complete -c path -d 'Show modification time'
complete -c path -d 'Normalize given paths (remove ./, resolve ../ against other components..)'
complete -c path -d 'Normalize given paths and resolve symlinks'
complete -c path -d 'Print paths that match a filter'
complete -c path -d 'Return true if any path matched a filter'
complete -c path -d 'Sort paths'
complete -c path -s 'q' -l 'quiet' -d 'Only return status, no output'
complete -c path -s 'z' -l 'null-in' -d 'Handle NULL-delimited input'
complete -c path -s 'Z' -l 'null-out' -d 'Print NULL-delimited output'
complete -c path -s 'E' -l 'no-extension' -d 'Remove the extension'
complete -c path -s 'v' -l 'invert' -d 'Invert meaning of filters'
complete -c path -s 't' -l 'type' -d 'Filter by type'
complete -c path -s 'f' -d 'Filter files'
complete -c path -s 'd' -d 'Filter directories'
complete -c path -s 'l' -d 'Filter symlinks'
complete -c path -s 'p' -l 'perm' -d 'Filter by permission'
complete -c path -s 'r' -d 'Filter readable paths'
complete -c path -s 'w' -d 'Filter writable paths'
complete -c path -s 'x' -d 'Filter executable paths'
complete -c path -s 'R' -l 'relative' -d 'Show seconds since the modification time'
complete -c path -s 'u' -l 'unique' -d 'Only leave the first of each run with the same key'
complete -c path -s 'r' -l 'reverse' -d 'Reverse the order'
