complete -c patool -s 'h' -l 'help' -d 'Show help message'
complete -c patool -s 'v' -l 'verbose' -d 'Be verbose'
complete -c patool -l 'non-interactive' -d 'Run in batch mode'
complete -c patool -d 'Extract archive(s)'
complete -c patool -d 'List files in archive(s)'
complete -c patool -d 'Create archive'
complete -c patool -d 'Test archive(s)'
complete -c patool -d 'Repackage archive to different format'
complete -c patool -d 'Recompress archive to smaller'
complete -c patool -d 'Differences between two archives'
complete -c patool -d 'Search contents of archive'
complete -c patool -d 'Show supported formats'
complete -c patool -l 'outdir' -d 'Specify output directory'
