complete -c perl -s '0' -d 'Specify record separator'
complete -c perl -s 'a' -d 'Turn on autosplit mode'
complete -c perl -s 'c' -d 'Check syntax'
complete -c perl -s 'C' -d 'Control Unicode features'
complete -c perl -s 'Ca' -d 'Debug UTF-8 cache'
complete -c perl -s 'CA' -d 'ARGV uses UTF-8'
complete -c perl -s 'CD' -d 'Opened filehandles are UTF-8'
complete -c perl -s 'CE' -d 'STDERR is UTF-8'
complete -c perl -s 'Ci' -d 'Filehandles that are read are UTF-8'
complete -c perl -s 'CI' -d 'STDIN is UTF-8'
complete -c perl -s 'CL' -d 'Enable Unicode conditionally'
complete -c perl -s 'Co' -d 'Filehandles written to are UTF-8'
complete -c perl -s 'CO' -d 'STDOUT is UTF-8'
complete -c perl -s 'CS' -d 'STDOUT, STDIN, and STDERR are UTF-8'
complete -c perl -s 'd' -d 'Debugger'
complete -c perl -s 'dt' -d 'Debugger, with threads'
complete -c perl -s 'D' -d 'Debug option'
complete -c perl -s 'e' -d 'Execute command'
complete -c perl -s 'E' -d 'Execute command, enable optional features'
complete -c perl -s 'f' -d 'Disable sitecustomize.pl'
complete -c perl -s 'F' -d 'Set regexp used to split input'
complete -c perl -s 'h' -d 'Show help and exit'
complete -c perl -s 'i' -d 'Edit files in-place'
complete -c perl -s 'I' -d 'Include path'
complete -c perl -s 'l' -d 'Automatic line ending processing'
complete -c perl -s 'm' -d 'Require module'
complete -c perl -s 'M' -d 'Use module'
complete -c perl -s 'n' -d 'Loop script'
complete -c perl -s 'p' -d 'Loop script, print $_'
complete -c perl -s 's' -d 'Define custom switches'
complete -c perl -s 'S' -d 'Search $PATH for script'
complete -c perl -s 't' -d 'Taint checking, but only with warnings'
complete -c perl -s 'T' -d 'Taint checking'
complete -c perl -s 'u' -d 'Dump core'
complete -c perl -s 'U' -d 'Unsafe mode'
complete -c perl -s 'v' -d 'Display version and exit'
complete -c perl -s 'V' -d 'Display configuration and exit'
complete -c perl -s 'w' -d 'Show warnings'
complete -c perl -s 'W' -d 'Force warnings'
complete -c perl -s 'X' -d 'Disable warnings'
complete -c perl -s 'x' -d 'Extract script'
