complete -c pkg-config -l 'modversion' -d 'Print versions of the specified libraries'
complete -c pkg-config -l 'version' -d 'Display the version of pkg-config and quit'
complete -c pkg-config -l 'help' -d 'Displays a help message and quit'
complete -c pkg-config -l 'print-errors' -d 'Print message when errors occur'
complete -c pkg-config -l 'silence-errors' -d 'Stay quiet when errors occur'
complete -c pkg-config -l 'errors-to-stdout' -d 'Print errors to stdout instead of stderr'
complete -c pkg-config -l 'debug' -d 'Print debugging information'
complete -c pkg-config -l 'cflags' -d 'Print pre-processor and compile flags for the specified libraries'
complete -c pkg-config -l 'cflags-only-I' -d 'This prints the -I part of "--cflags".'
complete -c pkg-config -l 'libs' -d 'Print link flags'
complete -c pkg-config -l 'libs-only-L' -d 'This prints the -L/-R part of "--libs".'
complete -c pkg-config -l 'libs-only-l' -d 'This prints the -l part of "--libs"'
complete -c pkg-config -l 'define-variable' -d 'This sets a global value for a variable'
complete -c pkg-config -l 'print-variables' -d 'Returns a list of all variables defined in the package'
complete -c pkg-config -l 'uninstalled' -d 'Return success if any -uninstalled packages are used'
complete -c pkg-config -l 'max-version' -d 'Test if a package has at most the specified version'
complete -c pkg-config -l 'atleast-version' -d 'Test if a package has at least this version'
complete -c pkg-config -l 'exact-version' -d 'Test if a package has exactly this version'
complete -c pkg-config -l 'exists' -d 'Test if a package exists'
complete -c pkg-config -l 'static' -d 'Output libraries suitable for static linking'
complete -c pkg-config -l 'list-all' -d 'List all modules found in the pkg-config path'
complete -c pkg-config -l 'print-provides' -d 'List all modules the given packages provides'
complete -c pkg-config -l 'print-requires' -d 'List all modules the given packages requires'
complete -c pkg-config -l 'print-requires-private' -d 'List all modules the given packages requires for static linking'
