complete -c pkg -s 'v' -l 'version' -d 'Display version and exit'
complete -c pkg -s 'd' -l 'debug' -d 'Show debug information'
complete -c pkg -s 'l' -l 'list' -d 'List subcommands'
complete -c pkg -s 'o' -l 'option' -d 'Set configuration option'
complete -c pkg -s 'N' -d 'Run sanity test'
complete -c pkg -s 'j' -l 'jail' -d 'Run package manager within jail'
complete -c pkg -s 'c' -l 'chroot' -d 'Run package manager within chroot'
complete -c pkg -s 'r' -l 'rootdir' -d 'Install packages in specified root'
complete -c pkg -s 'C' -l 'config' -d 'Use configuration file'
complete -c pkg -s 'R' -l 'repo-conf-dir' -d 'Set repository configuration directory'
complete -c pkg -s '4' -d 'Use IPv4'
complete -c pkg -s '6' -d 'Use IPv6'
complete -c pkg -d 'Install package file'
complete -c pkg -d 'List the command line aliases'
complete -c pkg -d 'Modify annotations on packages'
complete -c pkg -d 'Audit installed packages'
complete -c pkg -d 'Delete unneeded packages'
complete -c pkg -d 'Dump package database'
complete -c pkg -d 'Install pkg(8) from remote repository'
complete -c pkg -d 'Check installed packages'
complete -c pkg -d 'Clean local cache'
complete -c pkg -d 'Convert package from pkg_add format'
complete -c pkg -d 'Create a package'
complete -c pkg -d 'Remove a package'
complete -c pkg -d 'Download a remote package'
complete -c pkg -d 'Display help for command'
complete -c pkg -d 'List installed packages'
complete -c pkg -d 'Install packages'
complete -c pkg -d 'List files belonging to package(s)'
complete -c pkg -d 'Prevent package modification'
complete -c pkg -d 'List package manager plugins'
complete -c pkg -d 'Query installed packages'
complete -c pkg -d 'Register a package in a database'
complete -c pkg -d 'Remove a package'
complete -c pkg -d 'Create package repository'
complete -c pkg -d 'Query information for remote repositories'
complete -c pkg -d 'Find packages'
complete -c pkg -d 'Modify package information in database'
complete -c pkg -d 'Open a SQLite shell'
complete -c pkg -d 'Display packages linking to shared library'
complete -c pkg -d 'Show information about package(s)'
complete -c pkg -d 'Display package statistics'
complete -c pkg -d 'Stop preventing package modification'
complete -c pkg -d 'Update remote repositories'
complete -c pkg -d 'Display UPDATING entries'
complete -c pkg -d 'Upgrade packages'
complete -c pkg -d 'Show package versions'
complete -c pkg -d 'Check which package provides a file'
complete -c pkg -s 'A' -l 'automatic' -d 'Mark packages as automatic'
complete -c pkg -s 'f' -l 'force' -d 'Force installation even when installed'
complete -c pkg -s 'I' -l 'no-scripts' -d 'Disable installation scripts'
complete -c pkg -s 'M' -l 'accept-missing' -d 'Force installation with missing dependencies'
complete -c pkg -s 'q' -l 'quiet' -d 'Force quiet output'
complete -c pkg -s 'l' -l 'list' -d 'Print all aliases without their pkg(8) arguments'
complete -c pkg -s 'n' -l 'dry-run' -d 'Do not make changes'
complete -c pkg -s 'y' -l 'yes' -d 'Assume yes when asked for confirmation'
complete -c pkg -s 'B' -l 'shlibs' -d 'Regenerate library dependency metadata'
complete -c pkg -s 'd' -l 'dependencies' -d 'Check for and install missing dependencies'
complete -c pkg -s 'r' -l 'recompute' -d 'Recalculate and set the checksums of installed packages'
complete -c pkg -s 's' -l 'checksums' -d 'Detect installed packages with invalid checksums'
complete -c pkg -s 'n' -l 'dry-run' -d 'Do not make changes'
complete -c pkg -s 'q' -l 'quiet' -d 'Force quiet output'
complete -c pkg -s 'v' -l 'verbose' -d 'Provide verbose output'
complete -c pkg -s 'y' -l 'yes' -d 'Assume yes when asked for confirmation'
complete -c pkg -s 'a' -l 'all' -d 'Process all packages'
complete -c pkg -s 'C' -l 'case-sensitive' -d 'Case sensitive packages'
complete -c pkg -s 'g' -l 'glob' -d 'Treat the package name as shell glob'
complete -c pkg -s 'i' -l 'case-insensitive' -d 'Case insensitive packages'
complete -c pkg -s 'x' -l 'regex' -d 'Treat the package name as regular expression'
complete -c pkg -s 'a' -l 'all' -d 'Delete all cached packages'
complete -c pkg -s 'a' -l 'all' -d 'Delete all installed packages'
complete -c pkg -s 'C' -l 'case-sensitive' -d 'Case sensitive packages'
complete -c pkg -s 'D' -l 'no-deinstall-script' -d 'Disable deinstallation scripts'
complete -c pkg -s 'f' -l 'force' -d 'Force package removal'
complete -c pkg -s 'g' -l 'glob' -d 'Treat the package name as shell glob'
complete -c pkg -s 'i' -l 'case-insensitive' -d 'Case insensitive packages'
complete -c pkg -s 'R' -l 'recursive' -d 'Remove recursively'
complete -c pkg -s 'x' -l 'regex' -d 'Treat the package name as regular expression'
complete -c pkg -s 'I' -l 'no-install-scripts' -d 'Disable installation scripts'
complete -c pkg -s 'M' -l 'ignore-missing' -d 'Force installation with missing dependencies'
complete -c pkg -s 'F' -l 'fetch-only' -d 'Do not perform actual installation'
complete -c pkg -s 'R' -l 'from-root' -d 'Reinstall packages required by this package'
complete -c pkg -s 'r' -l 'repository' -d 'Use only a given repository'
complete -c pkg -s 'U' -l 'no-repo-update' -d 'Do not automatically update database'
complete -c pkg -s 'f' -l 'force' -d 'Force a full download of a repository'
