complete -c pkgmk -l 'install' -d 'Install with pkgadd after build'
complete -c pkgmk -l 'upgrade' -d 'Upgrade with pkgadd after build'
complete -c pkgmk -l 'recursive' -d 'Search and build packages recursively'
complete -c pkgmk -l 'download' -d 'Download the sources'
complete -c pkgmk -l 'download-only' -d 'Only download the sources'
complete -c pkgmk -l 'up-to-date' -d 'Check if the package is uptodate'
complete -c pkgmk -l 'update-footprint' -d 'Update footprint'
complete -c pkgmk -l 'ignore-footprint' -d 'Ignore footprint'
complete -c pkgmk -l 'update-md5sum' -d 'Update md5sum'
complete -c pkgmk -l 'ignore-md5sum' -d 'Ignore md5sum'
complete -c pkgmk -l 'no-strip' -d 'Do not strip executables'
complete -c pkgmk -l 'force' -d 'Force rebuild'
complete -c pkgmk -l 'clean' -d 'Remove package and sources'
complete -c pkgmk -l 'keep-work' -d 'Keep working dir'
complete -c pkgmk -l 'config-file' -d 'Use another config'
complete -c pkgmk -l 'version' -d 'Print version'
complete -c pkgmk -l 'help' -d 'Print help'
