complete -c plutil -d 'Show usage information and exit'
complete -c plutil -d 'Check plist files for syntax errors'
complete -c plutil -d 'Rewrite file in FORMAT'
complete -c plutil -s 'r' -d 'Pretty-print JSON'
complete -c plutil -s 'o' -d 'Alternate path for conversion result'
complete -c plutil -s 'e' -d 'Alternate extension for converted files'
complete -c plutil -d 'Convert FILE to Obj-C literal and create a .h file'
complete -c plutil -d 'Insert VALUE into the plist'
complete -c plutil -d 'Overwrite existing VALUE in the plist'
complete -c plutil -d 'Removes the value at KEYPATH'
complete -c plutil -d 'Outputs the value at KEYPATH as a new plist'
complete -c plutil -s 'p' -d 'Print the plist in a human-readable fashion'
complete -c plutil -s 's' -d 'Be silent on success'
