complete -c port -s 'v' -d 'Verbose mode, generates verbose messages'
complete -c port -s 'd' -d 'Debug mode, implies -v'
complete -c port -s 'q' -d 'Quiet mode, implies -N'
complete -c port -s 'N' -d 'Non-interactive mode'
complete -c port -s 'n' -d 'Don'"'"'t follow dependencies in upgrade'
complete -c port -s 'R' -d 'Also upgrade dependents (only for upgrade)'
complete -c port -s 'u' -d 'Uninstall inactive ports'
complete -c port -s 'y' -d 'Perform a dry run'
complete -c port -s 's' -d 'Source-only mode'
complete -c port -s 'b' -d 'Binary-only mode, abort if no archive available'
complete -c port -s 'c' -d 'Autoclean mode, execute clean after install'
complete -c port -s 'k' -d 'Keep mode, do not autoclean after install'
complete -c port -s 'p' -d 'Proceed to process despite any errors'
complete -c port -s 'o' -d 'Honor state files even if Portfile was modified'
complete -c port -s 't' -d 'Enable trace mode debug facilities'
complete -c port -s 'f' -d 'Force mode, ignore state file'
complete -c port -s 'D' -d 'Specify portdir'
complete -c port -s 'F' -d 'Read and process file of commands'
