complete -c prt-get -d 'Package'
complete -c prt-get -d 'Port'
complete -c prt-get -d 'Install listed ports'
complete -c prt-get -d 'Install listed ports and their deps'
complete -c prt-get -d 'Install listed ports, stop if one fails'
complete -c prt-get -d 'Update listed packages'
complete -c prt-get -d 'Remove listed packages'
complete -c prt-get -d 'Update all outdated installed packages'
complete -c prt-get -d 'Do not update this in sysup'
complete -c prt-get -d 'Remove this from lock'
complete -c prt-get -d 'Print differences between installed packages and ports in the port tree'
complete -c prt-get -d 'Search for an expr in port names'
complete -c prt-get -d 'Search for an expr in port names and descriptions'
complete -c prt-get -d 'Print info on a port'
complete -c prt-get -d 'Search for a pattern in the footprints in the ports tree'
complete -c prt-get -d 'Print the path of a port'
complete -c prt-get -d 'Print the eventual README of a port'
complete -c prt-get -d 'Print a list of deps for the listed ports'
complete -c prt-get -d 'Print a simple list of deps for the listed ports'
complete -c prt-get -d 'Print a deptree for the port'
complete -c prt-get -d 'List ports in multiple directories'
complete -c prt-get -d 'List all the ports'
complete -c prt-get -d 'Print formatted list of ports'
complete -c prt-get -d 'List installed packages'
complete -c prt-get -d 'List installed packages which have no dependent packages'
complete -c prt-get -d 'Check if a port is installed'
complete -c prt-get -d 'Print the version of an installed package'
complete -c prt-get -d 'Print the listing of the directory of a port'
complete -c prt-get -d 'Print a file in a port to stdout'
complete -c prt-get -d 'Edit a file in a port'
complete -c prt-get -d 'Shows a help screen'
complete -c prt-get -d 'Print the configuration of prt-get'
complete -c prt-get -d 'Show the current version of prt-get'
complete -c prt-get -d 'Create a cache for prt-get'
complete -c prt-get -d 'Force install'
complete -c prt-get -d 'Force rebuild'
complete -c prt-get -d 'Update md5sum'
complete -c prt-get -d 'Ignore md5sum'
complete -c prt-get -d 'Update footprint'
complete -c prt-get -d 'Ignore footprint'
complete -c prt-get -d 'No stripping'
complete -c prt-get -d 'Keep work directory'
complete -c prt-get -l 'ignore' -d 'Ignore the listed ports'
complete -c prt-get -l 'cache' -d 'Use cache'
complete -c prt-get -l 'test' -d 'Dry run'
complete -c prt-get -l 'pre-install' -d 'Exec eventual pre-install script'
complete -c prt-get -l 'post-install' -d 'Exec eventual post-install script'
complete -c prt-get -l 'install-scripts' -d 'Exec eventual pre-post-install scripts'
complete -c prt-get -l 'no-std-config' -d 'Ignore default config file'
complete -c prt-get -l 'config-prepend' -d 'Prepend string to config file'
complete -c prt-get -l 'config-append' -d 'Append string to config file'
complete -c prt-get -l 'config-set' -d 'Overrirde config file with string'
complete -c prt-get -d 'Be verbose'
complete -c prt-get -l 'margs' -d 'Arguments for pkgmk'
complete -c prt-get -l 'aargs' -d 'Arguments for pkgadd'
complete -c prt-get -l 'rargs' -d 'Arguments for pkgrm'
complete -c prt-get -l 'prefer-higher' -d 'Prefer higher version'
complete -c prt-get -l 'strict-diff' -d 'Override prefer-higher'
complete -c prt-get -l 'config' -d 'Use alternative config file'
complete -c prt-get -l 'install-root' -d 'Use this alternative root for installation'
complete -c prt-get -l 'log' -d 'Write output to log file'
complete -c prt-cache -d 'Port'
complete -c prt-cache -d 'Package'
complete -c prt-cache -d 'Install listed ports'
complete -c prt-cache -d 'Install listed ports and their deps'
complete -c prt-cache -d 'Install listed ports, stop if one fails'
complete -c prt-cache -d 'Update listed packages'
complete -c prt-cache -d 'Remove listed packages'
complete -c prt-cache -d 'Update all outdated installed packages'
complete -c prt-cache -d 'Do not update this in sysup'
complete -c prt-cache -d 'Remove this from lock'
complete -c prt-cache -d 'Print differences between installed packages and ports in the port tree'
complete -c prt-cache -d 'Search for an expr in port names'
complete -c prt-cache -d 'Search for an expr in port names and descriptions'
complete -c prt-cache -d 'Print info on a port'
complete -c prt-cache -d 'Search for a pattern in the footprints in the ports tree'
complete -c prt-cache -d 'Print the path of a port'
complete -c prt-cache -d 'Print the eventual README of a port'
complete -c prt-cache -d 'Print a list of deps for the listed ports'
complete -c prt-cache -d 'Print a simple list of deps for the listed ports'
complete -c prt-cache -d 'Print a deptree for the port'
complete -c prt-cache -d 'List all the ports'
complete -c prt-cache -d 'Print formatted list of ports'
complete -c prt-cache -d 'List installed packages'
complete -c prt-cache -d 'List installed packages which have no dependent packages'
complete -c prt-cache -d 'Print the version of an installed package'
complete -c prt-cache -d 'Print the listing of the directory of a port'
complete -c prt-cache -d 'Print a file in a port to stdout'
complete -c prt-cache -d 'Edit a file in a port'
complete -c prt-cache -d 'Shows a help screen'
complete -c prt-cache -d 'Print the configuration of prt-get'
complete -c prt-cache -d 'Show the current version of prt-get'
complete -c prt-cache -d 'Create a cache for prt-get'
complete -c prt-cache -d 'Force install'
complete -c prt-cache -d 'Force rebuild'
complete -c prt-cache -d 'Update md5sum'
complete -c prt-cache -d 'Ignore md5sum'
complete -c prt-cache -d 'Update footprint'
complete -c prt-cache -d 'Ignore footprint'
complete -c prt-cache -d 'No stripping'
complete -c prt-cache -d 'Keep work directory'
complete -c prt-cache -l 'ignore' -d 'Ignore the listed ports'
complete -c prt-cache -l 'test' -d 'Dry run'
complete -c prt-cache -l 'pre-install' -d 'Exec eventual pre-install script'
complete -c prt-cache -l 'post-install' -d 'Exec eventual post-install script'
complete -c prt-cache -l 'install-scripts' -d 'Exec eventual pre-post-install scripts'
complete -c prt-cache -l 'no-std-config' -d 'Ignore default config file'
complete -c prt-cache -l 'config-prepend' -d 'Prepend string to config file'
complete -c prt-cache -l 'config-append' -d 'Append string to config file'
complete -c prt-cache -l 'config-set' -d 'Overrirde config file with string'
complete -c prt-cache -d 'Be verbose'
complete -c prt-cache -l 'margs' -d 'Arguments for pkgmk'
complete -c prt-cache -l 'aargs' -d 'Arguments for pkgadd'
complete -c prt-cache -l 'rargs' -d 'Arguments for pkgrm'
complete -c prt-cache -l 'prefer-higher' -d 'Prefer higher version'
complete -c prt-cache -l 'strict-diff' -d 'Override prefer-higher'
complete -c prt-cache -l 'config' -d 'Use alternative config file'
complete -c prt-cache -l 'install-root' -d 'Use this alternative root for installation'
complete -c prt-cache -l 'log' -d 'Write output to log file'
