complete -c pyenv -d 'List all available pyenv commands'
complete -c pyenv -d 'Set or show the global Python version'
complete -c pyenv -d 'List hook scripts for a given pyenv command'
complete -c pyenv -d 'Configure the shell environment for pyenv'
complete -c pyenv -d 'Install a Python version'
complete -c pyenv -d 'Set or show the local application-specific Python version'
complete -c pyenv -d 'Display the directory where a Python version is installed'
complete -c pyenv -d 'Rehash pyenv shims (run this after installing executables)'
complete -c pyenv -d 'Display the root directory where versions and shims are kept'
complete -c pyenv -d 'Set or show the shell-specific Python version'
complete -c pyenv -d 'List existing pyenv shims'
complete -c pyenv -d 'Show the current Python version & how it was selected'
complete -c pyenv -d 'Detect the file that sets the current pyenv version'
complete -c pyenv -d 'Show the current Python version'
complete -c pyenv -d 'Explain how the current Python version is set'
complete -c pyenv -d 'List all Python versions known by pyenv'
complete -c pyenv -d 'List all Python versions that contain the given executable'
complete -c pyenv -d 'Show the full path for the given Python executable'
