complete -c pygmentize -s 'o' -d 'Set output file'
complete -c pygmentize -s 's' -d 'Read one line at a time'
complete -c pygmentize -s 'l' -d 'Set lexer'
complete -c pygmentize -s 'g' -d 'Guess lexer'
complete -c pygmentize -s 'f' -d 'Set formatter'
complete -c pygmentize -s 'O' -d 'Set coma-separated options'
complete -c pygmentize -s 'P' -d 'Set one option'
complete -c pygmentize -s 'F' -d 'Set filter'
complete -c pygmentize -s 'S' -d 'Print style definition for given style'
complete -c pygmentize -s 'L' -d 'List lexers, formatters, styles or filters'
complete -c pygmentize -s 'N' -d 'Guess and print lexer name based on given file'
complete -c pygmentize -s 'H' -d 'Print detailed help'
complete -c pygmentize -s 'v' -d 'Print detailed traceback on unhandled exceptions'
complete -c pygmentize -s 'h' -d 'Print help'
complete -c pygmentize -s 'V' -d 'Print package version'
