complete -c python3 -s 'c' -d 'Execute argument as command'
complete -c python3 -s 'd' -d 'Debug on'
complete -c python3 -s 'E' -d 'Ignore environment variables'
complete -c python3 -s 'h' -s '?' -l 'help' -d 'Display help and exit'
complete -c python3 -s 'i' -d 'Interactive mode after executing commands'
complete -c python3 -s 'O' -d 'Enable optimizations'
complete -c python3 -d 'Remove doc-strings in addition to the -O optimizations'
complete -c python3 -s 'S' -d 'Disable import of site module'
complete -c python3 -s 'u' -d 'Unbuffered input and output'
complete -c python3 -s 'v' -d 'Verbose mode'
complete -c python3 -s 'V' -l 'version' -d 'Display version and exit'
complete -c python3 -s 'W' -d 'Warning control'
complete -c python3 -s 'x' -d 'Skip first line of source, allowing use of non-Unix forms of #!cmd'
complete -c python3 -d 'Read program from stdin'
complete -c python3 -s 'X' -d 'Set implementation-specific option'
complete -c python3 -s 'b' -d 'Issue warnings for possible misuse of `bytes` with `str`'
complete -c python3 -d 'Issue errors for possible misuse of `bytes` with `str`'
complete -c python3 -l 'check-hash-based-pycs' -d 'Set pyc hash check mode'
complete -c python3 -s 'I' -d 'Run in isolated mode'
