complete -c python2 -s 'c' -d 'Execute argument as command'
complete -c python2 -s 'd' -d 'Debug on'
complete -c python2 -s 'E' -d 'Ignore environment variables'
complete -c python2 -s 'h' -l 'help' -d 'Display help and exit'
complete -c python2 -s 'i' -d 'Interactive mode after executing commands'
complete -c python2 -s 'O' -d 'Enable optimizations'
complete -c python2 -d 'Remove doc-strings in addition to the -O optimizations'
complete -c python2 -s 'S' -d 'Disable import of site module'
complete -c python2 -s 'u' -d 'Unbuffered input and output'
complete -c python2 -s 'v' -d 'Verbose mode'
complete -c python2 -s 'V' -d 'Display version and exit'
complete -c python2 -s 'W' -d 'Warning control'
complete -c python2 -s 'x' -d 'Skip first line of source, allowing use of non-Unix forms of #!cmd'
complete -c python2 -d 'Read program from stdin'
complete -c python2 -s '3' -d 'Warn about Python 3.x incompatibilities that 2to3 cannot trivially fix'
complete -c python2 -s 't' -d 'Warn on mixed tabs and spaces'
complete -c python2 -s 'Q' -d 'Division control'
