complete -c python -s 'c' -d 'Execute argument as command'
complete -c python -l 'check-hash-based-pycs' -d 'Control validation behaviour of pyc files'
complete -c python -s 'd' -d 'Debug on'
complete -c python -s 'E' -d 'Ignore all PYTHON* env vars'
complete -c python -s 'h' -s '?' -l 'help' -d 'Display help and exit'
complete -c python -s 'i' -d 'Interactive mode after executing commands'
complete -c python -s 'O' -d 'Enable optimizations'
complete -c python -d 'Remove doc-strings in addition to the -O optimizations'
complete -c python -s 'S' -d 'Disable import of site module'
complete -c python -s 'u' -d 'Unbuffered input and output'
complete -c python -s 'v' -d 'Verbose mode'
complete -c python -d 'Even more verbose mode'
complete -c python -s 'V' -l 'version' -d 'Display version and exit'
complete -c python -s 'W' -d 'Warning control'
complete -c python -s 'x' -d 'Skip first line of source, allowing use of non-Unix forms of #!cmd'
complete -c python -d 'Read program from stdin'
complete -c python -s '3' -d 'Warn about Python 3.x incompatibilities that 2to3 cannot trivially fix'
complete -c python -s 't' -d 'Warn on mixed tabs and spaces'
complete -c python -s 'Q' -d 'Division control'
complete -c python -s 'X' -d 'Set implementation-specific option'
complete -c python -s 'b' -d 'Warn when comparing bytes with str or int'
complete -c python -d 'Error when comparing bytes with str or int'
complete -c python -s 'R' -d 'Turn on hash randomization'
complete -c python -s 'I' -d 'Run in isolated mode'
complete -c python -d 'Print further version info'
