complete -c qjsc -s 'c' -d 'Only output bytecode in a C file'
complete -c qjsc -s 'e' -d 'Output main() and bytecode in a C file (default = executable output)'
complete -c qjsc -s 'o' -d 'Set the output filename'
complete -c qjsc -s 'N' -d 'Set the C name of the generated data'
complete -c qjsc -s 'm' -d 'Compile as Javascript module (default=autodetect)'
complete -c qjsc -s 'D' -d 'Compile a dynamically loaded module or worker'
complete -c qjsc -s 'M' -d 'Add initialization code for an external C module'
complete -c qjsc -s 'x' -d 'Byte swapped output'
complete -c qjsc -s 'p' -d 'Set the prefix of the generated C names'
complete -c qjsc -s 'S' -d 'Set the maximum stack size to n bytes (default=262144)'
complete -c qjsc -d 'Use link time optimization'
complete -c qjsc -d 'Enable bignum extensions'
complete -c qjsc -d 'Disable the date extension'
complete -c qjsc -d 'Disable the eval extension'
complete -c qjsc -d 'Disable the string normalize extension'
complete -c qjsc -d 'Disable the regexp extension'
complete -c qjsc -d 'Disable the JSON extension'
complete -c qjsc -d 'Disable the proxy extension'
complete -c qjsc -d 'Disable the Map extension'
complete -c qjsc -d 'Disable the Typed Array extension'
complete -c qjsc -d 'Disable the Promise extension'
complete -c qjsc -d 'Disable the module loader extension'
complete -c qjsc -d 'Disable the BigInt extension'
