complete -c quilt -s 'h' -d 'Show help'
complete -c quilt -l 'version' -d 'Show version'
complete -c quilt -l 'quiltrc' -d 'Give the config file to use'
complete -c quilt -l 'trace' -d 'Runs the command in bash trace mode (-x). For internal debugging'
complete -c quilt -d 'Add file(s) to the topmost/named patch'
complete -c quilt -d 'Print an annotated listing of the given file'
complete -c quilt -d 'Print a list of applied patches'
complete -c quilt -d 'Remove the topmost/given patch from the series file'
complete -c quilt -d 'Produces a diff of the given file(s) in the topmost/given patch'
complete -c quilt -d 'Edit the given file(s) in $EDITOR'
complete -c quilt -d 'Lists files that the topmost/given patch changes'
complete -c quilt -d 'Integrate the patch read from standard input into the topmost patch'
complete -c quilt -d 'Fork the topmost patch'
complete -c quilt -d 'Generates a dot directed graph of patch dependencies'
complete -c quilt -d 'Grep through source files recursively'
complete -c quilt -d 'Print/change the header of the topmost/given patch'
complete -c quilt -d 'Import external patches'
complete -c quilt -d 'Create mail messages from patches in the series file, stores/sends them'
complete -c quilt -d 'Creates new patch with the given name, inserts it after topmost patch'
complete -c quilt -d 'Prints name of patch after the topmost/given patch in the series file'
complete -c quilt -d 'Print the list of patches that modify the given file'
complete -c quilt -d 'Remove patch(es) from the stack of applied patches'
complete -c quilt -d 'Prints name of patch before the topmost/given patch in the series file'
complete -c quilt -d 'Apply patch(es) from the series file'
complete -c quilt -d 'Refresh the given patch, or the topmost patch by default'
complete -c quilt -d 'Remove one or more files from the topmost/named patch'
complete -c quilt -d 'Rename the topmost/named patch'
complete -c quilt -d 'Print the names of all patches in the series file'
complete -c quilt -d 'Initializes a source tree from an rpm spec or a quilt series file'
complete -c quilt -d 'Take a snapshot of the current working state'
complete -c quilt -d 'Prints name of the topmost patch in the current stack of applied patches'
complete -c quilt -d 'List patches not applied or patches that follow the patch in the series file'
complete -c quilt -d 'Upgrade meta-data in a working tree to the current version of quilt'
