complete -c rakudo -d 'Read program source from STDIN or start REPL if a TTY'
complete -c rakudo -s 'c' -d 'Check syntax only. Runs BEGIN and CHECK blocks'
complete -c rakudo -l 'doc' -d 'Extract documentation and print it as text'
complete -c rakudo -s 'e' -d 'One line of program, strict is enabled by default'
complete -c rakudo -s 'h' -l 'help' -d 'Display help text'
complete -c rakudo -s 'n' -d 'Run program once for each line of input'
complete -c rakudo -s 'p' -d 'Same as -n, but also print $_ at the end of lines'
complete -c rakudo -s 'I' -d 'Add the path to the module search path'
complete -c rakudo -s 'M' -d 'Load the module prior to running the program'
complete -c rakudo -l 'target' -d 'Specify compilation stage to emit'
complete -c rakudo -l 'optimize' -d 'use the given level of optimization, pass 0..3'
complete -c rakudo -s 'o' -l 'output' -d 'Specify name of output file'
complete -c rakudo -s 'v' -l 'version' -d 'Display version information'
complete -c rakudo -s 'V' -d 'Print configuration summary'
complete -c rakudo -l 'rakudo-home' -d 'Override the path of the Rakudo runtime files'
complete -c rakudo -l 'stagestats' -d 'Display time spent in the compilation stages'
complete -c rakudo -l 'repl-mode' -d 'Specify the REPL mode'
complete -c rakudo -l 'profile' -d 'Write profile information to a file. Extension controls format'
complete -c rakudo -l 'profile-compile' -d 'Write compile-time profile information to a file. Extension controls format'
complete -c rakudo -l 'profile-kind' -d 'Choose the type of profile to generate'
complete -c rakudo -l 'profile-stage' -d 'Write profile information for the given compilation stage to a file'
complete -c rakudo -l 'debug-port' -d 'Listen for incoming debugger connections'
complete -c rakudo -l 'tracing' -d 'Output a line to stderr on every interpreter instr, if enabled in MoarVM'
