complete -c rbenv -d 'List all available rbenv commands'
complete -c rbenv -d 'Set or show the global Ruby version'
complete -c rbenv -d 'List hook scripts for a given rbenv command'
complete -c rbenv -d 'Configure the shell environment for rbenv'
complete -c rbenv -d 'Install a Ruby version'
complete -c rbenv -d 'Uninstall a Ruby version'
complete -c rbenv -d 'Set or show the local application-specific Ruby version'
complete -c rbenv -d 'Display the directory where a Ruby version is installed'
complete -c rbenv -d 'Rehash rbenv shims (run this after installing executables)'
complete -c rbenv -d 'Display the root directory where versions and shims are kept'
complete -c rbenv -d 'Set or show the shell-specific Ruby version'
complete -c rbenv -d 'List existing rbenv shims'
complete -c rbenv -d 'Show the current Ruby version & how it was selected'
complete -c rbenv -d 'Detect the file that sets the current rbenv version'
complete -c rbenv -d 'Show the current Ruby version'
complete -c rbenv -d 'Explain how the current Ruby version is set'
complete -c rbenv -d 'List all Ruby versions known by rbenv'
complete -c rbenv -d 'List all Ruby versions that contain the given executable'
complete -c rbenv -d 'Show the full path for the given Ruby executable'
