complete -c resolvectl -s '4' -d 'Resolve only IPv4'
complete -c resolvectl -s '6' -d 'Resolve only IPv6'
complete -c resolvectl -l 'interface' -s 'i' -d 'Interface to execute the query on'
complete -c resolvectl -l 'protocol' -s 'p' -d 'Network protocol for the query'
complete -c resolvectl -l 'type' -s 't' -d 'DNS RR type for query'
complete -c resolvectl -l 'class' -s 'c' -d 'DNS class for query'
complete -c resolvectl -l 'service-address' -d 'Resolve address for SRV record'
complete -c resolvectl -l 'service-txt' -d 'Resolve TXT records for services'
complete -c resolvectl -l 'cname' -d 'Follow CNAME redirects'
complete -c resolvectl -l 'validate' -d 'Allow DNSSEC validation'
complete -c resolvectl -l 'synthesize' -d 'Allow synthetic response'
complete -c resolvectl -l 'cache' -d 'Allow response from cache'
complete -c resolvectl -l 'zone' -d 'Allow response from locally registered mDNS/LLMNR records'
complete -c resolvectl -l 'trust-anchor' -d 'Use local trust anchors'
complete -c resolvectl -l 'network' -d 'Allow response from network'
complete -c resolvectl -l 'search' -d 'Use search domains for single-label names'
complete -c resolvectl -l 'raw' -d 'Dump answer as binary data'
complete -c resolvectl -l 'legend' -d 'Print headers and meta info'
complete -c resolvectl -l 'help' -s 'h' -d 'Show help'
complete -c resolvectl -l 'version' -d 'Show version'
complete -c resolvectl -l 'no-pager' -d 'Do not pipe output into a pager'
