complete -c reuse -s 'h' -l 'help' -d 'show help message'
complete -c reuse -l 'debug' -d 'enable debug logging'
complete -c reuse -l 'suppress-deprecation' -d 'hide deprecation warnings'
complete -c reuse -l 'include-submodules' -d 'do not ignore Git submodules'
complete -c reuse -l 'include-meson-subprojects' -d 'do not ignore Meson subprojects'
complete -c reuse -l 'no-multiprocessing' -d 'disable multiprocessing'
complete -c reuse -l 'root' -d 'set root of project'
complete -c reuse -l 'version' -d 'show version number'
complete -c reuse -d 'add REUSE information to files'
complete -c reuse -d 'download license files'
complete -c reuse -d 'initialize REUSE project'
complete -c reuse -d 'list all non-compliant files'
complete -c reuse -d 'generate SPDX bill of materials'
complete -c reuse -d 'list all supported licenses'
complete -c reuse -s 'c' -l 'copyright' -d 'copyright statement'
complete -c reuse -s 'l' -l 'license' -d 'SPDX Identifier'
complete -c reuse -l 'contributor' -d 'file contributor'
complete -c reuse -s 'y' -l 'year' -d 'year of copyright statement'
complete -c reuse -s 's' -l 'style' -d 'comment style to use'
complete -c reuse -l 'copyright-style' -d 'copyright style to use'
complete -c reuse -s 't' -l 'template' -d 'name of template to use'
complete -c reuse -l 'exclude-year' -d 'do not include year in statement'
complete -c reuse -l 'merge-copyrights' -d 'merge copyright lines if copyright statements are identical'
complete -c reuse -l 'single-line' -d 'force single-line comment style'
complete -c reuse -l 'multi-line' -d 'force multi-line comment style'
complete -c reuse -s 'r' -l 'recursive' -d 'annotate all files recursively'
complete -c reuse -l 'no-replace' -d 'do not replace the first header in the file'
complete -c reuse -l 'force-dot-license' -d 'always write a .license file'
complete -c reuse -l 'fallback-dot-license' -d 'write a .license file to files with unrecognised comment styles'
complete -c reuse -l 'skip-unrecognised' -d 'skip files with unrecognised comment styles'
complete -c reuse -l 'skip-existing' -d 'skip files that already contain REUSE information'
complete -c reuse -l 'all' -d 'download all missing licenses'
complete -c reuse -s 'o' -l 'output' -d 'output license to specified file'
complete -c reuse -l 'source' -d 'source from which to copy custom `LicenseRef-` licenses'
complete -c reuse -s 'q' -l 'quiet' -d 'prevents output'
complete -c reuse -s 'j' -l 'json' -d 'formats output as JSON'
complete -c reuse -s 'p' -l 'plain' -d 'formats output as plain text'
complete -c reuse -s 'o' -l 'output' -d 'write the bill of materials to specified file'
complete -c reuse -l 'add-license-concluded' -d 'populate the LicenseConcluded field'
complete -c reuse -l 'creator-person' -d 'name of the person signing off on the SPDX report'
complete -c reuse -l 'creator-organization' -d 'name of the organization signing off on the SPDX report'
