complete -c ros -d 'Run repl'
complete -c ros -d 'Install a given implementation or a system for roswell environment'
complete -c ros -d 'Update installed systems.'
complete -c ros -d 'Make executable from script.'
complete -c ros -d 'Change default implementation.'
complete -c ros -d 'Creates a new ros script, optionally based on a template.'
complete -c ros -d 'Indent lisp source.'
complete -c ros -d 'List Information'
complete -c ros -d 'Manage templates'
complete -c ros -d 'Delete installed implementations'
complete -c ros -d 'Get and set options'
complete -c ros -d 'Show the roswell version information'
complete -c ros -d 'Use "ros help [command]" for more information about a command.'
complete -c ros -s 'l' -d 'load lisp FILE while building'
complete -c ros -l 'load' -d 'load lisp FILE while building'
complete -c ros -s 'l' -d 'load lisp FILE while building'
complete -c ros -l 'load' -d 'load lisp FILE while building'
complete -c ros -s 'S' -d 'override source registry of asdf systems'
complete -c ros -l 'source-registry' -d 'override source registry of asdf systems'
complete -c ros -s 's' -d 'load asdf SYSTEM while building'
complete -c ros -l 'system' -d 'load asdf SYSTEM while building'
complete -c ros -l 'load-system' -d 'same as above (buildapp compatibility)'
complete -c ros -s 'p' -d 'change current package to PACKAGE'
complete -c ros -l 'package' -d 'change current package to PACKAGE'
complete -c ros -d 'combination of -s SP and -p SP'
complete -c ros -l 'system-package' -d ' combination of -s SP and -p SP'
complete -c ros -s 'e' -d 'evaluate FORM while building'
complete -c ros -l 'eval' -d 'evaluate FORM while building'
complete -c ros -l 'require' -d 'require MODULE while building'
complete -c ros -s 'q' -d 'quit lisp here'
complete -c ros -l 'quit' -d 'quit lisp here'
complete -c ros -s 'r' -d 'restart from build by calling (FUNC)'
complete -c ros -l 'restart' -d 'restart from build by calling (FUNC)'
complete -c ros -s 'E' -d 'restart from build by calling (FUNC argv)'
complete -c ros -l 'entry' -d 'restart from build by calling (FUNC argv)'
complete -c ros -s 'i' -d 'evaluate FORM after restart'
complete -c ros -l 'init' -d 'evaluate FORM after restart'
complete -c ros -d 'evaluate and princ FORM after restart'
complete -c ros -l 'print' -d 'evaluate and princ FORM after restart'
complete -c ros -d 'evaluate and write FORM after restart'
complete -c ros -l 'write' -d 'evaluate and write FORM after restart'
complete -c ros -s 'F' -d 'evaluate FORM before dumping IMAGE'
complete -c ros -l 'final' -d 'evaluate FORM before dumping IMAGE'
complete -c ros -d 'skip /etc/rosrc, ~/.roswell/init.lisp'
complete -c ros -l 'no-rc' -d 'skip /etc/rosrc, ~/.roswell/init.lisp'
complete -c ros -s 'A' -d 'use new asdf'
complete -c ros -l 'asdf' -d 'use new asdf'
complete -c ros -d 'do not use quicklisp'
complete -c ros -l 'noquicklisp' -d 'do not use quicklisp'
complete -c ros -s 'v' -d 'be quite noisy while building'
complete -c ros -l 'verbose' -d 'be quite noisy while building'
complete -c ros -l 'quiet' -d 'be quite quiet while building (default)'
complete -c ros -l 'test' -d 'for test purpose'
complete -c ros -d 'Create new template'
complete -c ros -d 'Remove a template'
complete -c ros -d 'List the installed templates'
complete -c ros -d 'Checkout default template to edit.'
complete -c ros -d 'Add files to template.'
complete -c ros -d 'Show file contents'
complete -c ros -d 'Edit file contents'
complete -c ros -d 'Remove (delete) files from template.'
complete -c ros -d 'Remove (delete) files from template.'
complete -c ros -d 'Set template type for a file.'
complete -c ros -d 'Set mode for a file.'
complete -c ros -d 'Set path rewrite rule for a file'
complete -c ros -d 'Export template to directory'
complete -c ros -d 'Import template'
complete -c ros -d 'Print usage and subcommands description'
complete -c ros -d 'show TARGET.'
complete -c ros -d 'set TARGET VALUE.'
