complete -c rpm-ostree -l 'help' -d 'Show help options'
complete -c rpm-ostree -l 'quiet' -s 'q' -d 'Print minimal informational messages'
complete -c rpm-ostree -l 'version' -d 'Print version info and exit'
complete -c rpm-ostree -d 'Apply pending changes to booted deployment'
complete -c rpm-ostree -d 'Cancel an active transaction'
complete -c rpm-ostree -d 'Clear cached/pending data'
complete -c rpm-ostree -d 'Commands to compose a tree'
complete -c rpm-ostree -d 'Commands to query the RPM database'
complete -c rpm-ostree -d 'Deploy a specific commit'
complete -c rpm-ostree -d 'Toggle local initramfs regeneration'
complete -c rpm-ostree -d 'Add files to the initramfs'
complete -c rpm-ostree -d 'Overlay additional packages'
complete -c rpm-ostree -d 'Query or modify kernel arguments'
complete -c rpm-ostree -d 'Manage base package overrides'
complete -c rpm-ostree -d 'Switch to a different tree'
complete -c rpm-ostree -d 'Generate rpm repo metadata'
complete -c rpm-ostree -d 'Reload configuration'
complete -c rpm-ostree -d 'Remove all mutations'
complete -c rpm-ostree -d 'Revert to previously booted tree'
complete -c rpm-ostree -d 'Get booted system version'
complete -c rpm-ostree -d 'Remove overlayed additional packages'
complete -c rpm-ostree -d 'Remove overlayed additional packages'
complete -c rpm-ostree -d 'Perform system upgrade'
complete -c rpm-ostree -d 'Alias for upgrade'
complete -c rpm-ostree -d 'Apply transient overlayfs to /usr'
complete -c rpm-ostree -l 'target' -d 'Target provided commit'
complete -c rpm-ostree -l 'reset' -d 'Reset back to booted commit'
complete -c rpm-ostree -l 'allow-replacement' -d 'Allow replacement of packages/files'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'base' -s 'b' -d 'Clear temporary files; will not change deployments'
complete -c rpm-ostree -l 'pending' -s 'p' -d 'Remove pending deployment'
complete -c rpm-ostree -l 'rollback' -s 'r' -d 'Remove rollback deployment'
complete -c rpm-ostree -l 'repomd' -s 'm' -d 'Delete cached rpm repo metadata'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -d 'Commit target path to an OSTree repo'
complete -c rpm-ostree -d 'Create Chunked Container image from OSTree Commit'
complete -c rpm-ostree -d 'Download Depsolved RPMs for Base OSTree'
complete -c rpm-ostree -d 'Create reproducible Chunked Image from Treefile'
complete -c rpm-ostree -d 'Install packages into a target path'
complete -c rpm-ostree -d 'Final postprocessing on an installation root'
complete -c rpm-ostree -d 'Process a treefile'
complete -c rpm-ostree -l 'unified-core' -d 'Use new unified core codepath'
complete -c rpm-ostree -l 'repo' -s 'r' -d '=REPO Path to OSTree repo'
complete -c rpm-ostree -l 'layer-repo' -d '=REPO Path to OSTree repo for ostree-layers & ostree-override-layers'
complete -c rpm-ostree -l 'add-metadata-string' -d '=KEY=VALUE Append given key=value to metadata'
complete -c rpm-ostree -l 'add-metadata-from-json' -d '=JSON Append given JSON file to ostree commit'
complete -c rpm-ostree -l 'write-commitid-to' -d '=FILE Write composed CommitID to file'
complete -c rpm-ostree -l 'write-composejson-to' -d '=FIlE Write compose run info to JSON file'
complete -c rpm-ostree -l 'no-parent' -d 'Always commit without a parent'
complete -c rpm-ostree -l 'parent' -d '=REV Commit with specific parent revision'
complete -c rpm-ostree -l 'repo' -d '=REPO Path to repo'
complete -c rpm-ostree -l 'label' -d 'Additional labels for container'
complete -c rpm-ostree -l 'copymeta' -d 'Propagate OSTree key to container label'
complete -c rpm-ostree -l 'copymeta-opt' -d 'Propagate opt OSTree key to container label'
complete -c rpm-ostree -l 'cmd' -d 'Matches dockerfile CMD instruction'
complete -c rpm-ostree -l 'max-layers' -d 'Maximum number of container image layers'
complete -c rpm-ostree -l 'format-version' -d '0 or 1; encapsulated container format version'
complete -c rpm-ostree -l 'write-contentmeta-json' -d 'Output content metadata as JSON'
complete -c rpm-ostree -l 'compare-with-build' -d 'Compare current OCI layers with another imgref'
complete -c rpm-ostree -l 'previous-build-manifest' -d 'Preserve pack structure with prior metadata'
complete -c rpm-ostree -l 'unified-core' -d 'Use new unified core codepath'
complete -c rpm-ostree -l 'repo' -s 'r' -d '=REPO Path to OSTree repo'
complete -c rpm-ostree -l 'layer-repo' -d '=REPO Repo for ostree-layers & ostree-override-layers'
complete -c rpm-ostree -l 'output-dir' -d '=PATH Path to extensions output dir'
complete -c rpm-ostree -l 'base-rev' -d '=REV Base OSTree revision'
complete -c rpm-ostree -l 'cachedir' -d '=CACHEDIR Cached state dir'
complete -c rpm-ostree -l 'rootfs' -d '=ROOTFS Path to existing rootfs'
complete -c rpm-ostree -l 'touch-if-changed' -d '=FILE Update mod time on file'
complete -c rpm-ostree -l 'cachedir' -d 'Set cache directory for packages and data'
complete -c rpm-ostree -l 'authfile' -d 'Container authentication file'
complete -c rpm-ostree -l 'layer-repo' -d 'Specify repository for ostree layers and ostree-override-layers'
complete -c rpm-ostree -l 'initialize' -s 'i' -d 'Skip previous image query for first build'
complete -c rpm-ostree -l 'format' -d 'Choose format (ociarchive oci registry)'
complete -c rpm-ostree -l 'force-nocache' -d 'Force a build'
complete -c rpm-ostree -l 'offline' -d 'Operate on cached data, no network repo access'
complete -c rpm-ostree -l 'lockfile' -d 'Specify JSON-formatted lockfile'
complete -c rpm-ostree -l 'label' -d 'Add labels (KEY=VALUE) to the container image'
complete -c rpm-ostree -l 'touch-if-changed' -d 'Update file timestamp on changes'
complete -c rpm-ostree -l 'copy-retry-times' -d 'Set number of copy retries to remote destination'
complete -c rpm-ostree -l 'unified-core' -d 'Use new unified core codepath'
complete -c rpm-ostree -l 'repo' -s 'r' -d '=REPO Path to OSTree repo'
complete -c rpm-ostree -l 'layer-repo' -d '=REPO Repo for ostree-layers & ostree-override-layers'
complete -c rpm-ostree -l 'force-nocache' -d 'Always create new OSTree commit'
complete -c rpm-ostree -l 'cache-only' -d 'Assume cache present, no updates'
complete -c rpm-ostree -l 'cachedir' -d '=CACHEDIR Cached state dir'
complete -c rpm-ostree -l 'download-only' -d 'Dry-run but download & import RPMs'
complete -c rpm-ostree -l 'download-only-rpms' -d 'Dry-run but download RPMs; need --cachedir'
complete -c rpm-ostree -l 'proxy' -d '=PROXY HTTP proxy'
complete -c rpm-ostree -l 'dry-run' -d 'Print transaction and exit'
complete -c rpm-ostree -l 'print-only' -d 'Expand includes and print treefile'
complete -c rpm-ostree -l 'touch-if-changed' -d '=FILE Update FILE'"'"'s mod time if new commit'
complete -c rpm-ostree -l 'previous-commit' -d '=COMMIT for change detection'
complete -c rpm-ostree -l 'previous-inputhash' -d '=DIGEST Use input hash for change detect'
complete -c rpm-ostree -l 'previous-version' -d '=VERSION for auto version numbering'
complete -c rpm-ostree -l 'workdir' -d '=WORKDIR Working directory'
complete -c rpm-ostree -l 'ex-write-lockfile-to' -d '=FILE Write lockfile to FILE'
complete -c rpm-ostree -l 'ex-lockfile' -d '=FILE Read lockfile from FILE'
complete -c rpm-ostree -l 'ex-lockfile-strict' -d 'Only allow installing locked packages with --ex-lockfile'
complete -c rpm-ostree -l 'unified-core' -d 'Use new unified core codepath'
complete -c rpm-ostree -l 'unified-core' -d 'Use new unified core codepath'
complete -c rpm-ostree -l 'repo' -s 'r' -d '=REPO Path to OSTree repos'
complete -c rpm-ostree -l 'layer-repo' -d '=REPO Repo for ostree-layers & ostree-override-layers'
complete -c rpm-ostree -l 'force-nocache' -d 'Always create new OSTree commit'
complete -c rpm-ostree -l 'cache-only' -d 'Assume cache present, no updates'
complete -c rpm-ostree -l 'cachedir' -d '=CACHEDIR Specify cached state dir'
complete -c rpm-ostree -l 'download-only' -d 'Dry-run but download & import RPMs'
complete -c rpm-ostree -l 'download-only-rpms' -d 'Dry-run but download RPMs; need --cachedir'
complete -c rpm-ostree -l 'proxy' -d '=PROXY HTTP proxy'
complete -c rpm-ostree -l 'dry-run' -d 'Print transaction and exit'
complete -c rpm-ostree -l 'print-only' -d 'Expand includes and print treefile'
complete -c rpm-ostree -l 'touch-if-changed' -d '=FILE Update FILE'"'"'s mod time if new commit'
complete -c rpm-ostree -l 'previous-commit' -d '=COMMIT for change detection'
complete -c rpm-ostree -l 'previous-inputhash' -d '=DIGEST Use input hash for change detect'
complete -c rpm-ostree -l 'previous-version' -d '=VERSION for auto version numbering'
complete -c rpm-ostree -l 'workdir' -d '=WORKDIR Working directory'
complete -c rpm-ostree -l 'ex-write-lockfile-to' -d '=FILE Write lockfile to FILE'
complete -c rpm-ostree -l 'ex-lockfile' -d '=FILE Read lockfile from FILE'
complete -c rpm-ostree -l 'ex-lockfile-strict' -d 'Only allow installing locked packages with --ex-lockfile'
complete -c rpm-ostree -l 'add-metadata-string' -d '=KEY=VALUE Append key=value to metadata'
complete -c rpm-ostree -l 'add-metadata-from-json' -d '=JSON Append JSON to OSTree commit'
complete -c rpm-ostree -l 'write-commitid-to' -d '=FILE Write commitid to FILE, not ref'
complete -c rpm-ostree -l 'write-composejson-to' -d '=FILE Write compose run info json to FILE'
complete -c rpm-ostree -l 'no-parent' -d 'Always Commit without a parent'
complete -c rpm-ostree -l 'parent' -d '=REV Commit with specific parent revision'
complete -c rpm-ostree -d 'Show package changes between two commits'
complete -c rpm-ostree -d 'List packages within commits'
complete -c rpm-ostree -d 'Show rpmdb version of packages within the commits'
complete -c rpm-ostree -l 'repo' -s 'r' -d '=REPO Path to OSTree repo'
complete -c rpm-ostree -l 'format' -d '=FORMAT Choose output format (block diff json)'
complete -c rpm-ostree -l 'changelogs' -s 'c' -d 'Include RPM changelogs'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'base' -d 'Diff against deployments'"'"' base'
complete -c rpm-ostree -l 'advisories' -s 'a' -d 'Include new advisories'
complete -c rpm-ostree -l 'repo' -s 'r' -d '=PATH Path to OSTree repo'
complete -c rpm-ostree -l 'advisories' -s 'a' -d 'Include new advisories'
complete -c rpm-ostree -l 'repo' -s 'r' -d '=REPO Path to OSTree repo'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Reboot after operation complete'
complete -c rpm-ostree -l 'preview' -d 'Preview package differences'
complete -c rpm-ostree -l 'cache-only' -s 'C' -d 'No latest ostree and RPM download'
complete -c rpm-ostree -l 'download-only' -d 'Download latest ostree and RPM data, don'"'"'t deploy'
complete -c rpm-ostree -l 'skip-branch-check' -d 'Don'"'"'t check if commit belongs on the same branch'
complete -c rpm-ostree -l 'disallow-downgrade' -d 'Forbid deployment of older trees'
complete -c rpm-ostree -l 'unchanged-exit-77' -d 'If no new deployment made, exit 77'
complete -c rpm-ostree -l 'register-driver' -d '=DRIVERNAME Register agent as driver for updates'
complete -c rpm-ostree -l 'bypass-driver' -d 'Force deploy even if updates driver is registered'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed additional package'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'enable' -d 'Enable regenerating initramfs locally using dracut'
complete -c rpm-ostree -l 'arg' -d '=ARG Append ARG to the dracut arguments'
complete -c rpm-ostree -l 'disable' -d 'Disable regenerating initramfs locally'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Reboot after operation complete'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'force-sync' -d 'Deploy a new tree with the latest tracked /etc files'
complete -c rpm-ostree -l 'track' -d '=FILE Track root /etc file'
complete -c rpm-ostree -l 'untrack' -d '=FILE Untrack root /etc file'
complete -c rpm-ostree -l 'untrack-all' -d 'Untrack all root /etc files'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Reboot after operation complete'
complete -c rpm-ostree -l 'unchanged-exit-77' -d 'Exit with 77 if no new deployment made'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed additional package'
complete -c rpm-ostree -l 'cache-only' -s 'C' -d 'Skip downloading latest ostree/RPM data'
complete -c rpm-ostree -l 'download-only' -d 'Download latest ostree & RPM data, skip deploy'
complete -c rpm-ostree -l 'apply-live' -s 'A' -d 'Apply changes to pending & live filesystem'
complete -c rpm-ostree -l 'force-replacefiles' -d 'Allow package to replace files from others'"'"' pkgs'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Initiate a reboot post-operation'
complete -c rpm-ostree -l 'dry-run' -s 'n' -d 'Exit after printing the transaction'
complete -c rpm-ostree -l 'assumeyes' -s 'y' -d 'Auto-confirm non-security prompts'
complete -c rpm-ostree -l 'allow-inactive' -d 'Allow inactive package requests'
complete -c rpm-ostree -l 'idempotent' -d 'No action if pkg already (un)installed'
complete -c rpm-ostree -l 'unchanged-exit-77' -d 'If no overlays were changed, exit 77'
complete -c rpm-ostree -l 'enablerepo' -d 'Enable repo based on its ID'
complete -c rpm-ostree -l 'disablerepo' -d 'Only disabling all (*) repo is supported'
complete -c rpm-ostree -l 'releasever' -d 'Set the releasever'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operation on provided OSNAME'
complete -c rpm-ostree -l 'deploy-index' -d '=INDEX Modify kernel args of a deployment by index'
complete -c rpm-ostree -l 'reboot' -d 'Initiate a reboot after operation'
complete -c rpm-ostree -l 'append' -d '=KEY=VALUE Append kernel argument'
complete -c rpm-ostree -l 'replace' -d '=KEY=VALUE=NEWVALUE Replace kernel argument'
complete -c rpm-ostree -l 'delete' -d '=KEY=VALUE Delete kernel argument pair'
complete -c rpm-ostree -l 'append-if-missing' -d '=KEY=VALUE Append kernel arg if missing'
complete -c rpm-ostree -l 'delete-if-present' -d '=KEY=VALUE Delete kernel arg if present'
complete -c rpm-ostree -l 'unchanged-exit-77' -d 'Exit 77 if no kernel args changed'
complete -c rpm-ostree -l 'import-proc-cmdline' -d 'Modify args from the booted deployment'
complete -c rpm-ostree -l 'editor' -d 'Use editor to modify kernel arguments'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -d 'Remove packages from the base layer'
complete -c rpm-ostree -d 'Replace packages in the base layer'
complete -c rpm-ostree -d 'Reset active package overrides'
complete -c rpm-ostree -l 'replace' -d '=RPM Replace a package'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Initiate a reboot after operation'
complete -c rpm-ostree -l 'dry-run' -s 'n' -d 'Exit after printing transaction'
complete -c rpm-ostree -l 'cache-only' -s 'C' -d 'Only operate on cached data'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed package'
complete -c rpm-ostree -l 'remove' -d '=PKG Remove a package'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -d 'Initiate a reboot after operation'
complete -c rpm-ostree -l 'dry-run' -s 'n' -d 'Exit after printing transaction'
complete -c rpm-ostree -l 'cache-only' -s 'C' -d 'Only operate on cached data'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed package'
complete -c rpm-ostree -l 'all' -s 'a' -d 'Reset all active overrides'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Initiate a reboot after operation'
complete -c rpm-ostree -l 'dry-run' -s 'n' -d 'Exit after printing transaction'
complete -c rpm-ostree -l 'cache-only' -s 'C' -d 'Only operate on cached data'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root '
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed package'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'branch' -s 'b' -d '=BRANCH Rebase to branch BRANCH'
complete -c rpm-ostree -l 'remote' -s 'm' -d '=REMOTE Rebase to current branch name using REMOTE'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Initiate a reboot after operation'
complete -c rpm-ostree -l 'skip-purge' -d 'Keep previous refspec after rebase'
complete -c rpm-ostree -l 'cache-only' -s 'C' -d 'Don'"'"'t download latest ostree/RPM data'
complete -c rpm-ostree -l 'download-only' -d 'Download ostree & RPM data, don'"'"'t deploy'
complete -c rpm-ostree -l 'custom-origin-description' -d 'Human-readable description of custom origin'
complete -c rpm-ostree -l 'custom-origin-url' -d 'Machine-readable description of custom origin'
complete -c rpm-ostree -l 'experimental' -d 'Enable experimental features'
complete -c rpm-ostree -l 'disallow-downgrade' -d 'Forbid older trees deployment'
complete -c rpm-ostree -l 'bypass-driver' -d 'Force rebase despite updates driver is registered'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed package'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'force' -d 'Expire current cache'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Reboot after transaction'
complete -c rpm-ostree -l 'overlays' -s 'l' -d 'Remove all overlayed packages'
complete -c rpm-ostree -l 'overrides' -s 'o' -d 'Remove all overrides'
complete -c rpm-ostree -l 'initramfs' -s 'i' -d 'Stop regenerating initramfs'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed package'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Reboot after transaction'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'verbose' -s 'v' -d 'Print additional fields'
complete -c rpm-ostree -l 'advisories' -s 'a' -d 'Expand advisories listing'
complete -c rpm-ostree -l 'json' -d 'Output JSON'
complete -c rpm-ostree -l 'jsonpath' -s 'J' -d '=EXPRESSION Filter JSONPath expression'
complete -c rpm-ostree -l 'booted' -s 'b' -d 'Only print booted deployment'
complete -c rpm-ostree -l 'pending-exit-77' -d 'If pending deployment available, exit 77'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'all' -d 'Remove all overlayed packages'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Reboot after operation'
complete -c rpm-ostree -l 'dry-run' -s 'n' -d 'Print transaction, don'"'"'t execute'
complete -c rpm-ostree -l 'assumeyes' -s 'y' -d 'Auto-confirm non-security prompts'
complete -c rpm-ostree -l 'allow-inactive' -d 'Allow inactive package requests'
complete -c rpm-ostree -l 'idempotent' -d 'Skip if pkg already (un)installed'
complete -c rpm-ostree -l 'unchanged-exit-77' -d 'Exit 77 if no overlays changed'
complete -c rpm-ostree -l 'enablerepo' -d 'Enable repo by id'
complete -c rpm-ostree -l 'disablerepo' -d 'Disable all (*) repositories'
complete -c rpm-ostree -l 'releasever' -d 'Set the release version'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'os' -d '=OSNAME Operate on provided OSNAME'
complete -c rpm-ostree -l 'reboot' -s 'r' -d 'Reboot after operation'
complete -c rpm-ostree -l 'allow-downgrade' -d 'Allow older trees deployment'
complete -c rpm-ostree -l 'preview' -d 'Preview pkg differences'
complete -c rpm-ostree -l 'check' -d 'Check upgrade availability'
complete -c rpm-ostree -l 'cache-only' -s 'C' -d 'Don'"'"'t download OSTree & RPM data'
complete -c rpm-ostree -l 'download-only' -d 'Download OSTree & RPM data, don'"'"'t deploy'
complete -c rpm-ostree -l 'unchanged-exit-77' -d 'Exit 77 if no deployment'
complete -c rpm-ostree -l 'bypass-driver' -d 'Force upgrade even if updates driver is registered'
complete -c rpm-ostree -l 'sysroot' -d '=SYSROOT Use system root'
complete -c rpm-ostree -l 'peer' -d 'Force peer-to-peer connection'
complete -c rpm-ostree -l 'install' -d '=PKG Overlay additional package'
complete -c rpm-ostree -l 'uninstall' -d '=PKG Remove overlayed package'
