complete -c run0 -s 'h' -l 'help' -d 'Show help'
complete -c run0 -s 'V' -l 'version' -d 'Show version'
complete -c run0 -s 'u' -l 'user' -d 'Switches to the specified user instead of root'
complete -c run0 -s 'g' -l 'group' -d 'Switches to the specified group instead of root'
complete -c run0 -l 'no-ask-password' -d 'Do not query the user for authentication for privileged operations'
complete -c run0 -l 'machine' -d 'Execute operation on a local container'
complete -c run0 -l 'property' -d 'Sets a property on the service unit that is created'
complete -c run0 -l 'description' -d 'Description for unit'
complete -c run0 -l 'slice' -d 'Make the new .service unit part of the specified slice, instead of user.slice.'
complete -c run0 -l 'slice-inherit' -d 'Make the new .service unit part of the slice the run0 itself has been invoked in'
complete -c run0 -l 'nice' -d 'Runs the invoked session with the specified nice level'
complete -c run0 -s 'D' -l 'chdir' -d 'Set working directory'
complete -c run0 -l 'setenv' -d 'Runs the invoked session with the specified environment variable set'
complete -c run0 -l 'background' -d 'Change the terminal background color to the specified ANSI color'
complete -c run0 -l 'pty' -d 'Request allocation of a pseudo TTY for stdio'
complete -c run0 -l 'pipe' -d 'Request redirect pipe for stdio'
complete -c run0 -l 'shell-prompt-prefix' -d 'Set a shell prompt prefix string'
