complete -c rustc -s 'h' -l 'help'
complete -c rustc -l 'cfg'
complete -c rustc -l 'check-cfg' -d 'Provide list of expected cfgs for checking'
complete -c rustc -s 'L'
complete -c rustc -s 'l'
complete -c rustc -l 'crate-type'
complete -c rustc -l 'crate-name'
complete -c rustc -l 'edition' -d 'Specify compiler edition'
complete -c rustc -l 'emit'
complete -c rustc -l 'print' -d 'Print compiler information'
complete -c rustc -s 'g' -d 'Equivalent to -C debuginfo=2'
complete -c rustc -s 'O' -d 'Equivalent to -C opt-level=2'
complete -c rustc -s 'o' -d 'Write output to <filename>'
complete -c rustc -l 'out-dir'
complete -c rustc -l 'explain'
complete -c rustc -l 'test'
complete -c rustc -l 'target'
complete -c rustc -l 'cap-lints'
complete -c rustc -s 'V' -l 'version' -d 'Print version info and exit'
complete -c rustc -s 'v' -l 'verbose' -d 'Use verbose output'
complete -c rustc -l 'extern'
complete -c rustc -l 'sysroot'
complete -c rustc -l 'color'
complete -c rustc -s 'C' -l 'codegen'
complete -c rustc -s 'Z'
complete -c rustc -s 'W' -l 'warn' -d 'Warn on lint'
complete -c rustc -s 'A' -l 'allow' -d 'Allow lint'
complete -c rustc -s 'D' -l 'deny' -d 'Deny lint'
complete -c rustc -s 'F' -l 'forbid' -d 'Forbid lint'
