complete -c sass-convert -s 'F' -l 'from' -d 'The format to convert from'
complete -c sass-convert -s 'T' -l 'to' -d 'The format to convert to'
complete -c sass-convert -s 'i' -l 'in-place' -d 'Convert a file to its own syntax'
complete -c sass-convert -s 'R' -l 'recursive' -d 'Convert all the files in a directory'
complete -c sass-convert -s '?' -s 'h' -l 'help' -d 'Show help message'
complete -c sass-convert -s 'v' -l 'version' -d 'Print the Sass version'
complete -c sass-convert -l 'dasherize' -d 'Convert underscores to dashes'
complete -c sass-convert -l 'indent' -d 'How many spaces to use for each level of indentation'
complete -c sass-convert -l 'old' -d 'Output the old-style '"'"':prop val'"'"' property syntax'
complete -c sass-convert -s 's' -l 'stdin' -d 'Read input from standard input instead of an input file'
complete -c sass-convert -s 'E' -l 'default-encoding' -d 'Specify the default encoding for input files'
complete -c sass-convert -l 'unix-newlines' -d 'Use Unix-style newlines in written files'
complete -c sass-convert -l 'cache-location' -d 'The path to save parsed Sass files'
complete -c sass-convert -s 'C' -l 'no-cache' -d 'Don'"'"'t cache to sassc files'
complete -c sass-convert -l 'trace' -d 'Show a full Ruby stack trace on error'
