complete -c sbt -d 'Create a new sbt project from the given template'
complete -c sbt -d 'Connect to a server with an interactive sbt prompt'
complete -c sbt -s 'h' -d 'Print options help message'
complete -c sbt -s 'v' -d 'Print more details'
complete -c sbt -s 'd' -d 'Set log level to debug'
complete -c sbt -d 'Disable ANSI color codes'
complete -c sbt -d 'Launch even if there'"'"'s no sbt project'
complete -c sbt -d 'Use all local caches'
complete -c sbt -d 'Use global caches, but not global ~/.sbt directory'
complete -c sbt -d 'Disable interactive mode'
complete -c sbt -d 'Specify path to global settings/plugins'
complete -c sbt -d 'Specify path to shared boot directory'
complete -c sbt -d 'Specify path to local Ivy repository'
complete -c sbt -d 'Set memory options'
complete -c sbt -d 'Turn on JVM debugging, open at the given port'
complete -c sbt -d 'Use specified version of sbt'
complete -c sbt -d 'Use specified jar as the sbt launcher'
complete -c sbt -d 'Use an RC version of sbt'
complete -c sbt -d 'Use a snapshot version of sbt'
complete -c sbt -d 'Alternate JAVA_HOME'
complete -c sbt -d 'Pass -D option directly to the Java runtime'
complete -c sbt -d 'Pass -X option directly to the Java runtime'
complete -c sbt -d 'Pass -X option to sbt'"'"'s scalacOptions'
