complete -c scanimage -s 'l' -d 'Top-left x position of scan area [0..480pel]/[0..218mm]'
complete -c scanimage -s 't' -d 'Top-left y position of scan area [0..360pel]'
complete -c scanimage -s 'x' -d 'Width of scan area [160..640pel]'
complete -c scanimage -s 'y' -d 'Height of scan area [120..480pel]'
complete -c scanimage -l 'brightness' -d 'Controls the brightness of the acquired image [0..255: 128]'
complete -c scanimage -l 'hue' -d 'Controls the "hue" (blue-level) of the acquired image [0..255]: 128'
complete -c scanimage -l 'contrast' -d 'Controls the contrast of the acquired image [0..255]: 128'
complete -c scanimage -l 'white-level' -d 'Selects what radiance level should be considered "white" [0..255]: 124'
complete -c scanimage -l 'custom-gamma' -d 'Use custom gamma gable'
complete -c scanimage -l 'gamma-table' -d 'Gamma-correction table [0..255, …]'
complete -c scanimage -l 'mode' -d 'Scan mode'
complete -c scanimage -s 'd' -l 'device-name' -d 'Device name to use'
complete -c scanimage -s 'L' -l 'list-devices' -d 'List devices'
complete -c scanimage -s 'f' -l 'formatted-device-list' -d 'Print formatted device list [%d, %v, %m, %t, %i, %n]'
complete -c scanimage -l 'channel' -d 'Selects the channel of the v4l device (e.g. television or video-in.)'
complete -c scanimage -l 'filename' -d 'The filename of the image to be loaded'
complete -c scanimage -l 'format' -d 'Output image format'
complete -c scanimage -s 'i' -l 'icc-profile' -d 'Include this ICC profile into TIFF file'
complete -c scanimage -l 'batch-start' -d 'Page number to start naming files with'
complete -c scanimage -l 'batch-count' -d 'How many pages to scan in batch mode'
complete -c scanimage -l 'batch-increment' -d 'Increase page number in filename by #'
complete -c scanimage -l 'batch-double' -d 'Increment page number by two'
complete -c scanimage -l 'batch-prompt' -d 'Ask for pressing a key before scanning a page'
complete -c scanimage -l 'accept-md5-only' -d 'Only accept authorization requests using md5'
complete -c scanimage -s 'p' -l 'progress' -d 'Print progress messages'
complete -c scanimage -s 'T' -l 'test' -d 'Test backend thoroughly'
complete -c scanimage -s 'A' -l 'all-options' -d 'List all available backend options'
complete -c scanimage -s 'h' -l 'help' -d 'Display this help message and exit'
complete -c scanimage -s 'v' -l 'verbose' -d 'Give even more status messages'
complete -c scanimage -s 'B' -l 'buffer-size' -d 'Change input buffer size (in kB, default 32)'
complete -c scanimage -s 'V' -l 'version' -d 'Print version information'
