complete -c scp -d 'Remote'
complete -c scp -d 'Local Path'
complete -c scp -s '3' -d 'Copies between two remote hosts are transferred through the local host'
complete -c scp -s 'B' -d 'Batch mode'
complete -c scp -s 'D' -d 'Connect directly to a local SFTP server'
complete -c scp -s 'l' -d 'Bandwidth limit'
complete -c scp -s 'O' -d 'Use original SCP protocol instead of SFTP'
complete -c scp -s 'P' -d 'Port'
complete -c scp -s 'p' -d 'Preserves modification times, access times, and modes from the original file'
complete -c scp -s 'R' -d 'Copies between two remote hosts are performed by executing scp on the origin host'
complete -c scp -s 'r' -d 'Recursively copy'
complete -c scp -s 'S' -d 'Encryption program'
complete -c scp -s 'T' -d 'Disable strict filename checking'
