complete -c screen -s 'a' -d 'Include all capabilitys'
complete -c screen -s 'A' -d 'Adapt window size'
complete -c screen -s 'c' -d 'Specify init file'
complete -c screen -d 'Detach screen'
complete -c screen -d 'Detach screen'
complete -c screen -d 'Reattach session'
complete -c screen -d 'Reattach/create session'
complete -c screen -d 'Reattach/create any session'
complete -c screen -s 'e' -d 'Escape character'
complete -c screen -s 'f' -d 'Flow control on'
complete -c screen -d 'Flow control off'
complete -c screen -d 'Flow control automatic'
complete -c screen -d 'History length'
complete -c screen -s 'i' -d 'Interrupt display on C-c'
complete -c screen -s 'l' -d 'Login on'
complete -c screen -d 'Login off'
complete -c screen -d 'List sessions'
complete -c screen -d 'List sessions'
complete -c screen -s 'L' -d 'Log on'
complete -c screen -s 'm' -d 'Ignore $STY'
complete -c screen -s 'O' -d 'Optimal output'
complete -c screen -s 'p' -d 'Preselect window'
complete -c screen -s 'q' -d 'Quiet mode'
complete -c screen -d 'Set shell'
complete -c screen -d 'Session name'
complete -c screen -d 'Session title'
complete -c screen -d 'Value to use for $TERM (default "screen")'
complete -c screen -s 'U' -d 'UTF-8 mode'
complete -c screen -s 'v' -d 'Display version and exit'
complete -c screen -d 'Wipe dead sessions'
complete -c screen -d 'Multi attach'
complete -c screen -d 'Send command'
