complete -c scrypt -d 'Encrypt file'
complete -c scrypt -d 'Decrypt file'
complete -c scrypt -d 'Print information about the encryption parameters'
complete -c scrypt -s 'f' -d 'Force the operation to proceed'
complete -c scrypt -l 'logN' -d 'Set the work parameter N'
complete -c scrypt -s 'M' -d 'Use at most the specified bytes of RAM'
complete -c scrypt -s 'm' -d 'Use at most the specified fraction of the available RAM'
complete -c scrypt -s 'P' -d 'Deprecated synonym for `--passphrase dev:stdin-once`'
complete -c scrypt -s 'p' -d 'Set the work parameter p'
complete -c scrypt -s 'r' -d 'Set the work parameter r'
complete -c scrypt -s 't' -d 'Use at most the specified seconds of CPU time'
complete -c scrypt -s 'v' -d 'Print encryption parameters and memory/CPU limits'
complete -c scrypt -l 'version' -d 'Print version'
