complete -c scss -s 'I' -l 'load-path' -d 'Specify a Sass import path'
complete -c scss -s 'r' -l 'require' -d 'Require a Ruby library before running Sass'
complete -c scss -l 'compass' -d 'Enable Compass imports and load project configuration'
complete -c scss -s 't' -l 'style' -d 'Output style'
complete -c scss -s '?' -s 'h' -l 'help' -d 'Show help message'
complete -c scss -s 'v' -l 'version' -d 'Print the Sass version'
complete -c scss -l 'watch' -d 'Watch files or directories for changes'
complete -c scss -l 'poll' -d 'Check for file changes manually, don'"'"'t rely on OS'
complete -c scss -l 'update' -d 'Compile files or directories to CSS'
complete -c scss -s 'f' -l 'force' -d 'Recompile every Sass file, even if the CSS file is newer'
complete -c scss -l 'stop-on-error' -d 'If a file fails to compile, exit immediately'
complete -c scss -l 'sass' -d 'Use the indented Sass syntax'
complete -c scss -s 's' -l 'stdin' -d 'Read input from standard input instead of an input file'
complete -c scss -s 'E' -l 'default-encoding' -d 'Specify the default encoding for input files'
complete -c scss -l 'unix-newlines' -d 'Use Unix-style newlines in written files'
complete -c scss -s 'g' -l 'debug-info' -d 'Emit output that can be used by the FireSass Firebug plugin'
complete -c scss -s 'l' -l 'line-numbers' -l 'line-comments' -d 'Indicate corresponding source line with comments'
complete -c scss -s 'i' -l 'interactive' -d 'Run an interactive SassScript shell'
complete -c scss -s 'c' -l 'check' -d 'Just check syntax, don'"'"'t evaluate'
complete -c scss -l 'precision' -d 'Set precision when outputting decimal numbers'
complete -c scss -l 'cache-location' -d 'The path to save parsed Sass files'
complete -c scss -s 'C' -l 'no-cache' -d 'Don'"'"'t cache parsed Sass files'
complete -c scss -l 'trace' -d 'Show a full Ruby stack trace on error'
complete -c scss -s 'q' -l 'quiet' -d 'Silence warnings and status messages during compilation'
