complete -c set -s 'e' -l 'erase' -d 'Erase variable'
complete -c set -s 'x' -l 'export' -d 'Export variable to subprocess'
complete -c set -s 'u' -l 'unexport' -d 'Do not export variable to subprocess'
complete -c set -s 'f' -l 'function' -d 'Make variable function-scoped'
complete -c set -s 'g' -l 'global' -d 'Make variable scope global'
complete -c set -s 'l' -l 'local' -d 'Make variable scope local'
complete -c set -s 'L' -l 'long' -d 'Do not truncate long lines'
complete -c set -s 'U' -l 'universal' -d 'Share variable persistently across sessions'
complete -c set -s 'q' -l 'query' -d 'Test if variable is defined'
complete -c set -s 'h' -l 'help' -d 'Display help and exit'
complete -c set -s 'n' -l 'names' -d 'List the names of the variables, but not their value'
complete -c set -s 'a' -l 'append' -d 'Append value to a list'
complete -c set -s 'p' -l 'prepend' -d 'Prepend value to a list'
complete -c set -s 'S' -l 'show' -d 'Show variable'
complete -c set -l 'path' -d 'Make variable as a path variable'
complete -c set -l 'unpath' -d 'Make variable not as a path variable'
complete -c set -d 'text color'
complete -c set -d 'Locale'
