complete -c setxkbmap -d 'Print this message'
complete -c setxkbmap -d 'Specifies compatibility map component name'
complete -c setxkbmap -d 'Specifies configuration file to use'
complete -c setxkbmap -d 'Specifies the device ID to use'
complete -c setxkbmap -d 'Specifies display to use'
complete -c setxkbmap -d 'Specifies geometry component name'
complete -c setxkbmap -d 'Add <dir> to list of directories to be used'
complete -c setxkbmap -d 'Specifies keycodes component name'
complete -c setxkbmap -d 'Specifies name of keymap to load'
complete -c setxkbmap -d 'Specifies layout used to choose component names'
complete -c setxkbmap -d 'Specifies model used to choose component names'
complete -c setxkbmap -d 'Adds an option used to choose component names'
complete -c setxkbmap -d 'Print a complete xkb_keymap description and exit'
complete -c setxkbmap -d 'Print the current layout settings and exit'
complete -c setxkbmap -d 'Name of rules file to use'
complete -c setxkbmap -d 'Specifies symbols component name'
complete -c setxkbmap -d 'Synchronize request w/X server'
complete -c setxkbmap -d 'Specifies types component name'
complete -c setxkbmap -d 'Sets verbosity (1..10).  Higher values yield more messages'
complete -c setxkbmap -d 'Specifies layout variant used to choose component names'
