complete -c sftp -s 'a' -d 'Attempt to continue interrupted transfers'
complete -c sftp -s 'B' -d 'Size of the buffer when transferring files'
complete -c sftp -s 'b' -d 'Reads a series of commands from an input batchfile'
complete -c sftp -s 'D' -d 'Connect directly to a local SFTP server'
complete -c sftp -s 'f' -d 'Flush files to disk after transfer'
complete -c sftp -s 'l' -d 'Limits the used bandwidth (Kbit/s)'
complete -c sftp -s 'N' -d 'Disables quiet mode'
complete -c sftp -s 'P' -d 'Port to connect to on the remote host'
complete -c sftp -s 'p' -d 'Preserve timestamps from the original files transferred'
complete -c sftp -s 'R' -d 'How many requests may be outstanding'
complete -c sftp -s 'r' -d 'Recursively copy entire directories'
complete -c sftp -s 'S' -d 'Program to use for the encrypted connection'
complete -c sftp -s 's' -d 'The SSH2 subsystem or the path for an sftp server'
