complete -c sops -d 'Execute a command with decrypted values inserted into the environment'
complete -c sops -d 'Execute a command with decrypted contents as a temporary file'
complete -c sops -d 'Publish sops file or directory to a configured destination'
complete -c sops -d 'Start a SOPS key kervice server'
complete -c sops -d 'Modify the groups on a SOPS file'
complete -c sops -d 'Update the keys of a SOPS file using the config file'
complete -c sops -d 'Shows a list of commands or help for one command'
complete -c sops -d 'Shows a list of commands or help for one command'
complete -c sops -s 'd' -l 'decrypt' -d 'Decrypt a file and output the result to stdout'
complete -c sops -s 'e' -l 'encrypt' -d 'Encrypt a file and output the result to stdout'
complete -c sops -s 'r' -l 'rotate' -d 'Generate new encryption key & reencrypt with the new key'
complete -c sops -s 'i' -l 'in-place' -d 'Write output back to the same file instead of stdout'
complete -c sops -s 's' -l 'show-master-keys' -d 'Display master encryption keys in the file during editing'
complete -c sops -l 'extract' -d 'Extract a specific key or branch from decrypted input document'
complete -c sops -l 'ignore-mac' -d 'Ignore Message Authentication Code during decryption'
complete -c sops -l 'verbose' -d 'Enable verbose logging output'
complete -c sops -l 'enable-local-keyservice' -d 'Use local key service'
complete -c sops -s 'v' -l 'version' -d 'Print the version'
complete -c sops -s 'k' -l 'kms' -d 'Comma separated list of KMS ARNs'
complete -c sops -s 'p' -l 'pgp' -d 'Comma separated list of PGP fingerprints'
complete -c sops -s 'a' -l 'age' -d 'Comma separated list of age recipients'
complete -c sops -l 'gcp-kms' -d 'Comma separated list of GCP KMS resource IDs'
complete -c sops -l 'aws-profile' -d 'The AWS profile to use for requests to AWS'
complete -c sops -l 'azure-kv' -d 'Comma separated list of Azure Key Vault URLs'
complete -c sops -l 'hc-vault-transit' -d 'Comma separated list of Vault'"'"'s key URI'
complete -c sops -l 'input-type' -d 'Currently json, yaml, dotenv and binary are supported.'
complete -c sops -l 'output-type' -d 'Currently json, yaml, dotenv and binary are supported.'
complete -c sops -l 'add-gcp-kms' -d 'Comma-separated list of GCP KMS key resource IDs'
complete -c sops -l 'rm-gcp-kms' -d 'Remove comma-separated list of GCP KMS key resource IDs'
complete -c sops -l 'add-azure-kv' -d 'Add comma-separated list of Azure Key Vault key URLs'
complete -c sops -l 'rm-azure-kv' -d 'Remove comma-separated list of Azure Key Vault key URLs'
complete -c sops -l 'add-kms' -d 'Add comma-separated list of KMS ARNs'
complete -c sops -l 'rm-kms' -d 'Remove comma-separated list of KMS ARNs'
complete -c sops -l 'add-hc-vault-transit' -d 'Add comma-separated list of Vault'"'"'s URI key'
complete -c sops -l 'rm-hc-vault-transit' -d 'Remove comma-separated list of Vault'"'"'s URI key'
complete -c sops -l 'add-age' -d 'Add comma-separated list of age recipients fingerprints'
complete -c sops -l 'rm-age' -d 'Remove comma-separated list of age recipients fingerprints'
complete -c sops -l 'add-pgp' -d 'Add comma-separated list of PGP fingerprints'
complete -c sops -l 'rm-pgp' -d 'Remove comma-separated list of PGP fingerprints'
complete -c sops -l 'unencrypted-suffix' -d 'Override the unencrypted key suffix'
complete -c sops -l 'encrypted-suffix' -d 'Override the encrypted key suffix'
complete -c sops -l 'unencrypted-regex' -d 'Set the unencrypted key suffix'
complete -c sops -l 'encrypted-regex' -d 'Set the encrypted key suffix'
complete -c sops -l 'config' -d 'Path to sops'"'"' config file'
complete -c sops -l 'encryption-context' -d 'Comma separated list of KMS encryption context key:value pairs'
complete -c sops -l 'set' -d 'Set a specific key or branch in the input document (edit mode)'
complete -c sops -l 'shamir-secret-sharing-threshold' -d 'Number of master keys required to retrieve the data key with shamir'
complete -c sops -l 'output' -d 'Save the output after encryption or decryption to file'
complete -c sops -l 'keyservice' -d 'Specify key services to use in addition to the local one'
complete -c sops -s 'h' -l 'help' -d 'Show help'
complete -c sops -l 'background' -d 'Background the process and don\'"'"'t wait for it to complete'
complete -c sops -l 'user' -d 'The user to run the command as'
complete -c sops -l 'enable-local-keyservice' -d 'Use local key service'
complete -c sops -l 'keyservice' -d 'Specify key services to use in addition to the local one'
complete -c sops -l 'background' -d 'Background the process and don\'"'"'t wait for it to complete'
complete -c sops -l 'no-fifo' -d 'Use a regular file instead of a fifo to temporarily hold the decrypted contents'
complete -c sops -l 'user' -d 'The user to run the command as'
complete -c sops -l 'input-type' -d 'Currently json, yaml, dotenv and binary are supported'
complete -c sops -l 'output-type' -d 'Currently json, yaml, dotenv and binary are supported'
complete -c sops -l 'filename' -d 'Filename for the temporarily file (default: tmp-file)'
complete -c sops -l 'enable-local-keyservice' -d 'Use local key service'
complete -c sops -l 'keyservice' -d 'Specify key services to use in addition to the local one'
complete -c sops -s 'y' -l 'yes' -d 'Pre-approve all changes and run non-interactively'
complete -c sops -l 'omit-extensions' -d 'Omit file extensions in destination path when publishing sops file'
complete -c sops -l 'recursive' -d 'If source path is a directory, publish all its content recursively'
complete -c sops -l 'verbose' -d 'Enable verbose logging output'
complete -c sops -l 'enable-local-keyservice' -d 'use local key service'
complete -c sops -l 'keyservice' -d 'Specify key services to use in addition to the local one'
complete -c sops -l 'network' -l 'net' -d 'Network to listen on (default: "tcp")'
complete -c sops -l 'address' -l 'addr' -d 'Address to listen on (default: "127.0.0.1:5000")'
complete -c sops -l 'prompt' -d 'Prompt user to confirm every incoming request'
complete -c sops -l 'verbose' -d 'Enable verbose logging output'
complete -c sops -d 'Add a new group to a SOPS file'
complete -c sops -d 'Delete a key group from a SOPS file'
complete -c sops -s 'f' -l 'file' -d 'The file to add the group to'
complete -c sops -s 'i' -l 'in-place' -d 'Write output back to the same file instead of stdout'
complete -c sops -l 'pgp' -d 'The PGP fingerprints the new group should contain'
complete -c sops -l 'kms' -d 'The KMS ARNs the new group should contain'
complete -c sops -l 'aws-profile' -d 'The AWS profile to use for requests to AWS'
complete -c sops -l 'gcp-kms' -d 'The GCP KMS Resource ID the new group should contain'
complete -c sops -l 'azure-kv' -d 'The Azure Key Vault key URL the new group should contain'
complete -c sops -l 'hc-vault-transit' -d 'The full vault path to the key used to encrypt/decrypt'
complete -c sops -l 'age' -d 'The age recipient the new group should contain. Can be specified more than once'
complete -c sops -l 'shamir-secret-sharing-threshold' -d 'Number of master keys required to retrieve data key with shamir'
complete -c sops -l 'encryption-context' -d 'Comma separated list of KMS encryption context key:value pairs'
complete -c sops -l 'enable-local-keyservice' -d 'Use local key service'
complete -c sops -l 'keyservice' -d 'Specify key services to use in addition to the local one'
complete -c sops -s 'f' -l 'file' -d 'The file to add the group to'
complete -c sops -s 'i' -l 'in-place' -d 'Write output back to the same file instead of stdout'
complete -c sops -l 'shamir-secret-sharing-threshold' -d 'Number of master keys required to retrieve data key with shamir'
complete -c sops -l 'enable-local-keyservice' -d 'Use local key service'
complete -c sops -l 'keyservice' -d 'Specify key services to use in addition to the local one'
complete -c sops -s 'y' -l 'yes' -d 'Pre-approve all changes and run non-interactively'
complete -c sops -l 'enable-local-keyservice' -d 'Use local key service'
complete -c sops -l 'keyservice' -d 'Specify key services to use in addition to the local one'
complete -c sops -d 'Execute a command with decrypted values inserted into the environment'
complete -c sops -d 'Execute a command with decrypted contents as a temporary file'
complete -c sops -d 'Publish sops file or directory to a configured destination'
complete -c sops -d 'Start a SOPS key kervice server'
complete -c sops -d 'Modify the groups on a SOPS file'
complete -c sops -d 'Update the keys of a SOPS file using the config file'
