complete -c src -d 'Displays help for commands'
complete -c src -d 'Enters a commit for the specified files'
complete -c src -s 'm' -d 'Enter commit message as a string'
complete -c src -s 'f' -d 'Enter file containing commit message'
complete -c src -s 'e' -d 'Further edit commit message'
complete -c src -d 'Amends the stored comment for a specified revision'
complete -c src -s 'm' -d 'Enter commit message as a string'
complete -c src -s 'f' -d 'Enter file containing commit message'
complete -c src -s 'e' -d 'Further edit commit message'
complete -c src -d 'Refresh working copy from history'
complete -c src -d 'Send the specified revision of the files to standard output'
complete -c src -d 'Show status of files'
complete -c src -s 'a' -d 'Show all files'
complete -c src -d 'List/create/delete tags'
complete -c src -d 'List tags'
complete -c src -s 'l' -d 'List tags'
complete -c src -d 'Create tag'
complete -c src -s 'c' -d 'Create tag'
complete -c src -d 'Delete tag'
complete -c src -s 'd' -d 'Delete tag'
complete -c src -d 'List/create/delete branches'
complete -c src -d 'List branches'
complete -c src -s 'l' -d 'List branches'
complete -c src -d 'Create branch'
complete -c src -s 'c' -d 'Create branch'
complete -c src -d 'Delete branch'
complete -c src -s 'd' -d 'Delete branch'
complete -c src -d 'Rename tag/branch'
complete -c src -d 'List information about commits'
complete -c src -s 'l' -d 'Limit per-file commit count'
complete -c src -s 'f' -d 'Specify format string'
complete -c src -d 'List information about commits'
complete -c src -s 'v' -d 'Be more verbose'
complete -c src -s 'l' -d 'Limit per-file log entries'
complete -c src -s 'p' -l 'patch' -s 'u' -d 'Print unified-format diff'
complete -c src -s 'c' -d 'Print context diff'
complete -c src -d 'Ignore whitespace changes'
complete -c src -d 'Ignore all whitespace'
complete -c src -d 'Ignore whitespace changes'
complete -c src -d 'Ignore all whitespace'
complete -c src -d 'Print diff'
complete -c src -s 'u' -d 'Print unified-format diff'
complete -c src -s 'c' -d 'Print context diff'
complete -c src -d 'Ignore whitespace changes'
complete -c src -d 'Ignore all whitespace'
complete -c src -d 'List all registered files'
complete -c src -d 'Emit DOT visualization'
complete -c src -d 'Rename a workfile and its history'
complete -c src -d 'Copy a file and its master'
complete -c src -d 'Export as a Git fast-import stream'
complete -c src -d 'Parse a git-fast-import stream from stdin'
complete -c src -s 'p' -d 'Discards metadata'
complete -c src -d 'Release locks on files'
complete -c src -s 'd' -d 'Enable debugging output'
complete -c src -s 'S' -d 'Set repository directory'
complete -c src -s 'T' -d 'Set up for fast-export tests'
