complete -c ssh-keygen -s 'a' -d 'number of KDF rounds used [default 16]'
complete -c ssh-keygen -s 'b' -d 'number of bits in the key'
complete -c ssh-keygen -s 'c' -d 'change the comment in the private and public key files'
complete -c ssh-keygen -s 'N' -d 'provide the new passphrase'
complete -c ssh-keygen -s 'P' -d 'provide the (old) passphrase'
complete -c ssh-keygen -s 'p' -d 'request changing the passphrase of a private key file'
complete -c ssh-keygen -s 'L' -d 'print the contents of one or more certificates'
complete -c ssh-keygen -s 'l' -d 'show fingerprint of public key file'
complete -c ssh-keygen -s 'v' -d 'verbose mode: print debugging messages about its progress'
complete -c ssh-keygen -s 'f' -d 'filename of key file'
complete -c ssh-keygen -s 'C' -d 'comment of the generated key'
complete -c ssh-keygen -s 't' -d 'type of key to create'
complete -c ssh-keygen -s 'A' -d 'generate host keys of all default key types (rsa, ecdsa, and ed25519)'
complete -c ssh-keygen -s 'B' -d 'show the bubblebabble digest of specified key file'
complete -c ssh-keygen -s 'D' -d 'download the public keys provided by shared library pkcs11'
complete -c ssh-keygen -s 'E' -d 'hash algorithm used when displaying key fingerprints'
complete -c ssh-keygen -s 'e' -d 'print public key of a OpenSSH key file in a format specified by the -m option'
complete -c ssh-keygen -s 'F' -d 'find hashed host names or addresses in a known_hosts file'
complete -c ssh-keygen -s 'g' -d 'use generic DNS format when printing fingerprint resource records using -r command'
complete -c ssh-keygen -s 'H' -d 'hash a known_hosts file'
complete -c ssh-keygen -s 'h' -d 'create a host certificate when signing a key'
complete -c ssh-keygen -s 'I' -d 'specify the key identity when signing a public key'
complete -c ssh-keygen -s 'i' -d 'print an OpenSSH compatible private (or public) key'
complete -c ssh-keygen -s 'K' -d 'download resident keys from a FIDO authenticator'
complete -c ssh-keygen -s 'k' -d 'generate a KRL file'
complete -c ssh-keygen -s 'M' -d 'candidate Diffie-Hellman Group Exchange (DH-GEX) parameters'
complete -c ssh-keygen -s 'm' -d 'key format for key generation, for -i, -e and -p flag'
complete -c ssh-keygen -s 'n' -d 'specify principals (user or host names) to be included in a certificate when signing a key'
complete -c ssh-keygen -s 'O' -d 'specify a key/value option'
complete -c ssh-keygen -s 'Q' -d 'whether keys have been revoked in a KRL'
complete -c ssh-keygen -s 'q' -d 'silence ssh-keygen'
complete -c ssh-keygen -s 'R' -d 'removes all keys belonging to the specified hostname from a known_hosts file'
complete -c ssh-keygen -s 'r' -d 'print the SSHFP fingerprint resource record named hostname'
complete -c ssh-keygen -s 's' -d 'sign a public key using the specified CA key'
complete -c ssh-keygen -s 'U' -d 'indicates that a CA key resides in a ssh-agent'
complete -c ssh-keygen -s 'u' -d 'update a KRL'
complete -c ssh-keygen -s 'V' -d 'specify a validity interval when signing a certificate'
complete -c ssh-keygen -s 'w' -d 'path to a needed library when creating FIDO authenticator-hosted keys'
complete -c ssh-keygen -s 'y' -d 'print an OpenSSH public key from a private OpenSSH format file'
complete -c ssh-keygen -s 'Z' -d 'cipher kind used for encryption an OpenSSH-format private key file'
complete -c ssh-keygen -s 'z' -d 'serial number embedded in the certificate'
