complete -c ssh-copy-id -d 'Remote'
complete -c ssh-copy-id -d 'Remote'
complete -c ssh-copy-id -s 'i' -d 'IdentityFile'
complete -c ssh-copy-id -s 'p' -d 'Port'
complete -c ssh-copy-id -s 'F' -d 'Alternate ssh config file'
complete -c ssh-copy-id -s 'f' -d 'Force mode'
complete -c ssh-copy-id -s 'n' -d 'Dry run'
complete -c ssh-copy-id -s 's' -d 'Use sftp'
complete -c ssh-copy-id -s 'h' -s '?' -d 'Show help'
