complete -c status -s 'h' -l 'help' -d 'Display help and exit'
complete -c status -d 'Test if this is a login shell'
complete -c status -d 'Test if this is an interactive shell'
complete -c status -d 'Test if inside an interactive read builtin'
complete -c status -d 'Test if a command substitution is currently evaluated'
complete -c status -d 'Test if a code block is currently evaluated'
complete -c status -d 'Test if a breakpoint is currently in effect'
complete -c status -d 'Test if new jobs are never put under job control'
complete -c status -d 'Test if only interactive new jobs are put under job control'
complete -c status -d 'Test if all new jobs are put under job control'
complete -c status -d 'Print the name of the currently running command or function'
complete -c status -d 'Print the currently running command with its arguments'
complete -c status -d 'Print the filename of the currently running script'
complete -c status -d 'Print the filename of the currently running script'
complete -c status -d 'Print the file name (without the path) of the currently running script'
complete -c status -d 'Print the path (without the file name) of the currently running script'
complete -c status -d 'Print the name of the current function'
complete -c status -d 'Print the name of the current function'
complete -c status -d 'Print the line number of the currently running script'
complete -c status -d 'Print the line number of the currently running script'
complete -c status -d 'Print a list of all function calls leading up to running the current command'
complete -c status -d 'Print a list of all function calls leading up to running the current command'
complete -c status -d 'List all feature flags'
complete -c status -d 'Test if a feature flag is enabled'
complete -c status -d 'Print the path to the current instance of fish'
complete -c status -d 'Set which jobs are under job control'
complete -c status -d 'Set all jobs under job control'
complete -c status -d 'Set only interactive jobs under job control'
complete -c status -d 'Set no jobs under job control'
