complete -c stream -d 'Decipher image with this password [password]'
complete -c stream -d 'Apply option to select image channels [type]'
complete -c stream -d 'Alternate image colorspace [type]'
complete -c stream -d 'Type of pixel compression when writing the image [type]'
complete -c stream -d 'Define one or more image format options [format:option]'
complete -c stream -d 'Horizontal and vertical density of the image [geometry]'
complete -c stream -d 'Image depth [value]'
complete -c stream -d 'Extract area from image [geometry]'
complete -c stream -d 'Identify the format and characteristics of the image'
complete -c stream -d 'Type of image interlacing scheme [type]'
complete -c stream -d 'Pixel color interpolation method [method]'
complete -c stream -d 'Pixel cache resource limit [type value]'
complete -c stream -d 'Components one or more pixel components'
complete -c stream -d 'Monitor progress'
complete -c stream -d 'Reduce colors in this colorspace [colorspace]'
complete -c stream -d 'Suppress all warning messages'
complete -c stream -d 'Pay attention to warning messages'
complete -c stream -d 'Settings remain in effect until parenthesis boundary'
complete -c stream -d 'Horizontal and vertical sampling factor [geometry]'
complete -c stream -d 'Seed a new sequence of pseudo-random numbers [value]'
complete -c stream -d 'Attribute set an image attribute [value]'
complete -c stream -d 'Width and height of image [geometry]'
complete -c stream -d 'Pixel storage type [type]'
complete -c stream -d 'Synchronize image to storage device'
complete -c stream -d 'Declare the image as modified'
complete -c stream -d 'Transparent color [color]'
complete -c stream -d 'Print detailed information about the image'
complete -c stream -d 'Virtual pixel access method [method]'
complete -c stream -d 'Display copious debugging information [events]'
complete -c stream -d 'Print program options'
complete -c stream -d 'Print a list of supported option arguments [type]'
complete -c stream -d 'Format of debugging information [format]'
complete -c stream -d 'Print version information'
