complete -c string -s 'h' -l 'help' -d 'Display help and exit'
complete -c string -s 'q' -l 'quiet' -d 'Do not print output'
complete -c string -s 'V' -l 'visible' -d 'Use the visible width, excluding escape sequences'
complete -c string -s 's' -l 'start' -d 'Sepcify start index'
complete -c string -s 'e' -l 'end' -d 'Sepcify end index'
complete -c string -s 'l' -l 'length' -d 'Sepcify substring length'
complete -c string -s 'm' -l 'max' -d 'Specify maximum number of splits'
complete -c string -s 'f' -l 'fields' -d 'Specify fields'
complete -c string -s 'r' -l 'right' -d 'Split right-to-left'
complete -c string -s 'n' -l 'no-empty' -d 'Empty results excluded'
complete -c string -s 'N' -l 'no-trim-newlines' -d 'Don'"'"'t trim trailing newlines'
complete -c string -s 'a' -l 'allow-empty' -d 'Always print empty argument'
complete -c string -s 'n' -l 'no-empty' -d 'Empty strings excluded'
complete -c string -s 'l' -l 'left' -d 'Trim only leading chars'
complete -c string -s 'r' -l 'right' -d 'Trim only trailing chars'
complete -c string -s 'c' -l 'chars' -d 'Specify the chars to trim (default: whitespace)'
complete -c string -s 'n' -l 'no-quoted' -d 'Escape with \ instead of quotes'
complete -c string -s 'n' -l 'index' -d 'Report index, length of match'
complete -c string -s 'v' -l 'invert' -d 'Report only non-matches'
complete -c string -s 'e' -l 'entire' -d 'Show entire matching lines'
complete -c string -s 'g' -l 'groups-only' -d 'Only report capturing groups'
complete -c string -s 'f' -l 'filter' -d 'Report only actual replacements'
complete -c string -s 'a' -l 'all' -d 'Report every match'
complete -c string -s 'i' -l 'ignore-case' -d 'Case insensitive'
complete -c string -s 'r' -l 'regex' -d 'Use regex instead of globs'
complete -c string -s 'n' -l 'count' -d 'Repetition count'
complete -c string -s 'm' -l 'max' -d 'Maximum number of printed chars'
complete -c string -s 'N' -l 'no-newline' -d 'Remove newline'
complete -c string -s 'r' -l 'right' -d 'Pad right instead of left'
complete -c string -s 'c' -l 'char' -d 'Character to use for padding'
complete -c string -s 'w' -l 'width' -d 'Integer width of the result, default is maximum width of inputs'
complete -c string -s 'l' -l 'left' -d 'Remove from the left on'
complete -c string -s 'c' -l 'char' -d 'Characters to use as ellipsis'
complete -c string -s 'm' -l 'max' -d 'Integer width of the result, default is minimum non-zero width of inputs'
complete -c string -s 'N' -l 'no-newline' -d 'Only keep one line of each input'
