complete -c subl -d 'Load the given project'
complete -c subl -d 'Run the given command'
complete -c subl -d 'Open a new window'
complete -c subl -d 'Add folders to the current window'
complete -c subl -d 'Wait for the files to be closed before returning'
complete -c subl -d 'Don'"'"'t activate the application'
complete -c subl -d 'Keep the application activated after closing the file'
complete -c subl -d 'Show help and exit'
complete -c subl -d 'Show version and exit'
