complete -c sudo -s 'h' -d 'Display help and exit'
complete -c sudo -s 'V' -d 'Display version information and exit'
complete -c sudo -s 'A' -d 'Ask for password via the askpass or \$SSH_ASKPASS program'
complete -c sudo -s 'C' -d 'Close all file descriptors greater or equal to the given number'
complete -c sudo -s 'E' -d 'Preserve environment'
complete -c sudo -s 'H' -d 'Set home'
complete -c sudo -s 'K' -d 'Remove the credential timestamp entirely'
complete -c sudo -s 'P' -d 'Preserve group vector'
complete -c sudo -s 'S' -d 'Read password from stdin'
complete -c sudo -s 'b' -d 'Run command in the background'
complete -c sudo -s 'e' -d 'Edit'
complete -c sudo -s 'g' -d 'Run command as group'
complete -c sudo -s 'i' -d 'Run a login shell'
complete -c sudo -s 'k' -d 'Reset or ignore the credential timestamp'
complete -c sudo -s 'l' -d 'List the allowed and forbidden commands for the given user'
complete -c sudo -s 'n' -d 'Do not prompt for a password - if one is needed, fail'
complete -c sudo -s 'p' -d 'Specify a custom password prompt'
complete -c sudo -s 's' -d 'Run the given command in a shell'
complete -c sudo -s 'u' -d 'Run command as user'
complete -c sudo -s 'v' -d 'Validate the credentials, extending timeout'
