complete -c svn -d 'Put files under version control, scheduling them for addition in the next commit'
complete -c svn -d 'Output the content of specified files or URLs with revision and author information in-line'
complete -c svn -d 'Output the content of specified files or URLs'
complete -c svn -d 'Output the content of specified files or URLs with revision and author information in-line'
complete -c svn -d 'Check out a working copy from a repository'
complete -c svn -d 'Recursively clean up the working copy, removing locks, resuming unfinished operations, etc'
complete -c svn -d 'Send changes from your working copy to the repository'
complete -c svn -d 'Duplicate something in working copy or repository, remembering history'
complete -c svn -d 'Display the differences between two revisions or paths'
complete -c svn -d 'Create an unversioned copy of a tree'
complete -c svn -d 'Describe the usage of this program or its subcommands'
complete -c svn -d 'Commit an unversioned file or tree into the repository'
complete -c svn -d 'Display information about a local or remote item'
complete -c svn -d 'List directory entries in the repository'
complete -c svn -d 'Lock working copy paths/URLs in the repo, so that no other user can commit changes to them'
complete -c svn -d 'Show the log messages for a set of revision(s) and/or file(s)'
complete -c svn -d 'Apply the differences between two sources to a working copy path'
complete -c svn -d 'Display information related to merges'
complete -c svn -d 'Create a new directory under version control'
complete -c svn -d 'Move and/or rename something in working copy or repository'
complete -c svn -d 'Apply a unidiff patch to the working copy'
complete -c svn -d 'Remove a property from files, dirs, or revisions'
complete -c svn -d 'Edit a property with an external editor'
complete -c svn -d 'Print the value of a property on files, dirs, or revisions'
complete -c svn -d 'List all properties on files, dirs, or revisions'
complete -c svn -d 'Set the value of a property on files, dirs, or revisions'
complete -c svn -d 'Rewrite working copy url metadata'
complete -c svn -d 'Remove files and directories from version control'
complete -c svn -d 'Remove conflicts on working copy files or directories'
complete -c svn -d 'Restore pristine working copy file (undo most local edits)'
complete -c svn -d 'Print the status of working copy files and directories'
complete -c svn -d 'Update the working copy to a different URL'
complete -c svn -d 'Unlock working copy paths or URLs'
complete -c svn -d 'Bring changes from the repository into the working copy'
complete -c svn -d 'Upgrade the metadata storage format for a working copy'
complete -c svn -l 'username' -d 'Specify a username ARG'
complete -c svn -l 'password' -d 'Specify a password ARG'
complete -c svn -l 'no-auth-cache' -d 'Do not cache authentication tokens'
complete -c svn -l 'non-interactive' -d 'Do no interactive prompting'
complete -c svn -l 'trust-server-cert' -d 'Accept SSL server certificates from unknown authorities (ony with --non-interactive)'
complete -c svn -l 'config-dir' -d 'Read user configuration files from directory ARG'
complete -c svn -l 'config-option' -d 'Set user configuration option in the format: FILE:SECTION:OPTION=[VALUE]'
