complete -c sysbench -l 'num-threads' -d 'The total number of worker threads to create (default: 1)'
complete -c sysbench -l 'max-requests' -d 'Limit for total number of requests. 0 means unlimited (default: 10000)'
complete -c sysbench -l 'max-time' -d 'Limit for total execution time in seconds. 0 means unlimited (default: 0)'
complete -c sysbench -l 'thread-stack-size' -d 'Size of stack for each thread (defaut: 32K)'
complete -c sysbench -l 'init-rng' -d 'Specifies if random numbers generator should be initialized from timer (defaut: off)'
complete -c sysbench -l 'debug' -d 'Print more debug info (default: off)'
complete -c sysbench -l 'validate' -d 'Perform validation of test results where possible (default: off)'
complete -c sysbench -l 'help' -d 'Print help on general syntax'
complete -c sysbench -l 'version' -d 'Show version of program'
complete -c sysbench -l 'percentile' -d 'A percentile rank of query execution times to count (default: 95)'
complete -c sysbench -l 'batch' -d 'Dump current results periodically (default: off)'
complete -c sysbench -l 'batch-delay' -d 'Delay between batch dumps in secods (default: 300)'
complete -c sysbench -l 'cpu-max-prime' -d 'Calculation of prime numbers up to the specified value'
complete -c sysbench -l 'thread-yields' -d 'Number of lock/yield/unlock loops to execute per each request (default: 1000)'
complete -c sysbench -l 'thread-locks' -d 'Number of mutexes to create (default: 8)'
complete -c sysbench -l 'mutex-num' -d 'Number of mutexes to create (default: 4096)'
complete -c sysbench -l 'memory-total-size' -d 'Total size of data to transfer (default: 100G)'
complete -c sysbench -l 'memory-oper' -d 'Type of memory operations'
complete -c sysbench -l 'file-num' -d 'Number of files to create (default: 128)'
complete -c sysbench -l 'file-block-size' -d 'Block size to use in all I/O operations (default: 16K)'
complete -c sysbench -l 'file-total-size' -d 'Total size of files (default: 2G)'
complete -c sysbench -l 'file-io-mode' -d 'I/O mode (default: sync)'
complete -c sysbench -l 'file-async-backlog' -d 'Number of asynchronous operations to queue per thread (default: 128)'
complete -c sysbench -l 'file-extra-flags' -d 'Additional flags to use with open(2)'
complete -c sysbench -l 'file-fsync-freq' -d 'Do fsync() after this number of requests (default: 0)'
complete -c sysbench -l 'file-fsync-all' -d 'Do fsync() after each write operation (default: no)'
complete -c sysbench -l 'file-fsync-end' -d 'Do fsync() at the end of the test (default: yes)'
complete -c sysbench -l 'file-fsync-mode' -d 'Method used for synchronization: fsync, fdatasync (default: fsync)'
complete -c sysbench -l 'file-merged-requests' -d 'Upper limit of I/O requests merge (default: 0)'
complete -c sysbench -l 'file-rw-ratio' -d 'reads/writes ratio for combined random read/write test (default: 1.5)'
complete -c sysbench -l 'oltp-read-only' -d 'Read-only mode. No UPDATE, DELETE or INSERT queries will be performed. (default: off)'
complete -c sysbench -l 'oltp-range-size' -d 'Range size for range queries (default: 100)'
complete -c sysbench -l 'oltp-point-selects' -d 'Number of point select queries in a single transaction (default: 10)'
complete -c sysbench -l 'oltp-simple-ranges' -d 'Number of simple range queries in a single transaction (default: 1)'
complete -c sysbench -l 'oltp-sum-ranges' -d 'Number of SUM range queries in a single transaction (default: 1)'
complete -c sysbench -l 'oltp-order-ranges' -d 'Number of ORDER range queries in a single transaction (default: 1)'
complete -c sysbench -l 'oltp-distinct-ranges' -d 'Number of DISTINCT range queries in a single transaction (default: 1)'
complete -c sysbench -l 'oltp-index-updates' -d 'Number of index UPDATE queries in a single transaction (default: 1)'
complete -c sysbench -l 'oltp-non-index-updates' -d 'Number of non-index UPDATE queries in a single transaction (default: 1)'
complete -c sysbench -l 'oltp-nontrx-mode' -d 'Type of queries for non-transactional execution mode (default: select)'
complete -c sysbench -l 'oltp-connect-delay' -d 'Time to sleep(in microseconds) after each connection to database (default: 10000)'
complete -c sysbench -l 'oltp-user-delay-min' -d 'Minimum time to sleep(in microseconds) after each request (default: 0)'
complete -c sysbench -l 'oltp-user-delay-max' -d 'Maximum time to sleep(in microseconds) after each request (default: 0)'
complete -c sysbench -l 'oltp-table-name' -d 'Name of the test table (default: sbtest)'
complete -c sysbench -l 'oltp-table-size' -d 'Number of rows in the test table (default: 10000)'
complete -c sysbench -l 'db-ps-mode' -d 'Use "Prepared Statements" API if supported, otherwise - use clientside statements: disable, auto (default: auto)'
complete -c sysbench -l 'mysql-host' -d 'MySQL server host (default: localhost)'
complete -c sysbench -l 'mysql-port' -d 'MySQL server port (default: 3306)'
complete -c sysbench -l 'mysql-socket' -d 'Unix socket file to communicate with the MySQL server'
complete -c sysbench -l 'mysql-user' -d 'MySQL user (default: sbtest)'
complete -c sysbench -l 'mysql-password' -d 'MySQL password'
complete -c sysbench -l 'mysql-db' -d 'MySQL database name (default: sbtest)'
complete -c sysbench -l 'mysql-table-engine' -d 'Type of the test table to use'
complete -c sysbench -l 'mysql-ssl' -d 'Use SSL connections. (default: no)'
complete -c sysbench -l 'myisam-max-rows' -d 'MAX_ROWS option for MyISAM tables (required for big tables) (default: 1000000)'
complete -c sysbench -l 'mysql-create-options' -d 'Additional options passed to CREATE TABLE.'
