complete -c systemctl -d 'Start one or more units'
complete -c systemctl -d 'Stop one or more units'
complete -c systemctl -d 'Restart one or more units'
complete -c systemctl -d 'Reload units if supported or restart them'
complete -c systemctl -d 'Reload units if supported or restart them, if running'
complete -c systemctl -d 'Runtime status about one or more units'
complete -c systemctl -d 'Enable one or more units'
complete -c systemctl -d 'Disable one or more units'
complete -c systemctl -d 'Start a unit and dependencies and disable all others'
complete -c systemctl -d 'Set the default target to boot into'
complete -c systemctl -d 'Show the default target to boot into'
complete -c systemctl -d 'Sets one or more properties of a unit'
complete -c systemctl -d 'List automount units'
complete -c systemctl -d 'Return if system is running/starting/degraded'
complete -c systemctl -d 'Freeze units with the cgroup freezer'
complete -c systemctl -d 'Unfreeze frozen units'
complete -c systemctl -d 'Remove config/state/logs for the given units'
complete -c systemctl -s 't' -l 'type' -d 'List of unit types'
complete -c systemctl -l 'state' -d 'List of unit states'
complete -c systemctl -s 'p' -l 'property'
complete -c systemctl -s 'a' -l 'all' -d 'Show all units or properties'
complete -c systemctl -s 'r' -l 'recursive' -d 'Show also units of local containers'
complete -c systemctl -l 'reverse' -d 'Show reverse dependencies between units'
complete -c systemctl -l 'after' -d 'Show units ordered before specified unit'
complete -c systemctl -l 'before' -d 'Show units ordered after specified unit'
complete -c systemctl -s 'l' -l 'full' -d 'Do not ellipsize anything'
complete -c systemctl -l 'show-types' -d 'Show the type of the socket'
complete -c systemctl -l 'job-mode' -d 'How to deal with queued jobs'
complete -c systemctl -s 'i' -l 'ignore-inhibitors' -d 'Ignore inhibitor locks on shutdown or sleep'
complete -c systemctl -s 'q' -l 'quiet' -d 'Suppress output to STDOUT'
complete -c systemctl -l 'no-block' -d 'Do not wait for the requested operation to finish'
complete -c systemctl -l 'no-legend' -d 'Do not print header and footer'
complete -c systemctl -l 'user' -d 'Talk to the service manager of the calling user'
complete -c systemctl -l 'system' -d 'Talk to the service manager of the system.'
complete -c systemctl -l 'failed' -d 'List units in failed state'
complete -c systemctl -l 'global' -d 'Enable or disable for all users'
complete -c systemctl -l 'no-wall' -d 'Do not send wall message before halt'
complete -c systemctl -l 'no-reload' -d 'Do not reload daemon configuration'
complete -c systemctl -l 'no-ask-password' -d 'Disable asking for password'
complete -c systemctl -l 'kill-who' -d 'Send signal to which process'
complete -c systemctl -s 's' -l 'signal' -d 'Which signal to send'
complete -c systemctl -s 'f' -l 'force' -d 'Overwrite conflicting existing symlinks'
complete -c systemctl -l 'root' -d 'Use alternative root path'
complete -c systemctl -l 'runtime' -d 'Make changes only temporarily'
complete -c systemctl -s 'n' -l 'lines' -d 'Number of journal lines to show'
complete -c systemctl -s 'o' -l 'output' -d 'Control journal formatting'
complete -c systemctl -l 'plain' -d 'list-dependencies flat, not as tree'
complete -c systemctl -s 'H' -l 'host' -d 'Execute the operation on a remote host'
complete -c systemctl -s 'M' -l 'machine' -d 'Execute operation on a VM or container'
complete -c systemctl -s 'h' -l 'help' -d 'Print a short help and exit'
complete -c systemctl -l 'version' -d 'Print a short version and exit'
complete -c systemctl -l 'no-pager' -d 'Do not pipe output into a pager'
