complete -c systemd-cryptenroll -l 'password' -d 'Enroll a regular password'
complete -c systemd-cryptenroll -l 'recovery-key' -d 'Enroll an auto-generated recovery key'
complete -c systemd-cryptenroll -l 'pkcs11-token-uri' -d 'Enroll a PKCS#11 security token or smartcard'
complete -c systemd-cryptenroll -l 'fido2-device' -d 'Enroll a FIDO2 security token'
complete -c systemd-cryptenroll -l 'fido2-with-client-pin' -d 'Require to enter a PIN when unlocking the volume'
complete -c systemd-cryptenroll -l 'fido2-with-user-presence' -d 'Require to verify presence when unlocking the volume'
complete -c systemd-cryptenroll -l 'fido2-with-user-verification' -d 'Require user verification when unlocking the volume'
complete -c systemd-cryptenroll -l 'tpm2-device' -d 'Enroll a TPM2 security chip'
complete -c systemd-cryptenroll -l 'tpm2-pcrs' -d 'Bind the enrollment of TPM2 device to speficied PCRs'
complete -c systemd-cryptenroll -l 'wipe-slot' -d 'Wipes one or more LUKS2 key slots'
complete -c systemd-cryptenroll -l 'help' -s 'h' -d 'Print a short help'
complete -c systemd-cryptenroll -l 'version' -d 'Print a short version string'
