complete -c test -d 'condition evaluation utility'
complete -c test -d 'Negate expression'
complete -c test -s 'a' -d 'Logical AND'
complete -c test -s 'o' -d 'Logical OR'
complete -c test -s 'n' -d 'String length is non-zero'
complete -c test -s 'z' -d 'String length is zero'
complete -c test -d 'Strings are identical'
complete -c test -d 'Strings are not identical'
complete -c test -d 'Numbers are equal'
complete -c test -d 'Left number >= right number'
complete -c test -d 'Left number > right number'
complete -c test -d 'Left number <= right number'
complete -c test -d 'Left number < right number'
complete -c test -d 'Left number != right number'
complete -c test -d 'Left file equal to right file'
complete -c test -d 'Left file newer than right file'
complete -c test -d 'Left file older than right file'
complete -c test -s 'b' -d 'Path is a block device'
complete -c test -s 'c' -d 'Path is a character device'
complete -c test -s 'd' -d 'Path is a directory'
complete -c test -s 'e' -d 'Path exists'
complete -c test -s 'f' -d 'Path is a regular file'
complete -c test -s 'g' -d 'File has the set-group-ID bit'
complete -c test -s 'G' -d 'File owned by our effective group ID'
complete -c test -s 'L' -d 'Path is a symlink'
complete -c test -s 'O' -d 'File owned by our effective user ID'
complete -c test -s 'p' -d 'Path is a named pipe'
complete -c test -s 'r' -d 'File is readable'
complete -c test -s 's' -d 'File size is non-zero'
complete -c test -s 'S' -d 'File is a socket'
complete -c test -s 't' -d 'FD is a terminal'
complete -c test -s 'u' -d 'File has the set-user-ID bit'
complete -c test -s 'w' -d 'File is writable'
complete -c test -s 'x' -d 'File is executable'
