complete -c tex -d 'Display help and exit'
complete -c tex -d 'Display version and exit'
complete -c tex -d 'Show errors in style file:line'
complete -c tex -d 'Show errors not in style file:line'
complete -c tex -d 'Stop processing at the first error'
complete -c tex -d 'Set interaction mode'
complete -c tex -d 'Set interaction mode'
complete -c tex -d 'Set interaction mode'
complete -c tex -d 'Set interaction mode'
complete -c tex -d 'Output directory'
complete -c tex -d 'Enable \write18{SHELL COMMAND}'
complete -c tex -d 'Disable \write18{SHELL COMMAND}'
complete -c tex -d 'Insert source specials into the DVI file'
