complete -c timeout -l 'foreground' -d 'Run COMMAND in the foreground'
complete -c timeout -s 'k' -l 'kill-after' -d 'Send a KILL signal after DURATION'
complete -c timeout -s 's' -l 'signal' -d 'Specify the signal to be sent'
complete -c timeout -l 'preserve-status' -d 'Exit with same status as COMMAND'
complete -c timeout -d 'Specify which command to run'
