complete -c timedatectl -d 'Show current time settings'
complete -c timedatectl -d 'Show properties of systemd-timedated'
complete -c timedatectl -d 'Set system time'
complete -c timedatectl -d 'Set system time zone'
complete -c timedatectl -d 'Show known time zones'
complete -c timedatectl -d 'Control whether RTC is in local time'
complete -c timedatectl -d 'Control network time sync'
complete -c timedatectl -d 'Show status of systemd-timesyncd'
complete -c timedatectl -d 'Show properties of systemd-timesyncd'
complete -c timedatectl -s 'h' -l 'help' -d 'Show this help message'
complete -c timedatectl -l 'version' -d 'Show package version'
complete -c timedatectl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c timedatectl -l 'no-ask-password' -d 'Do not prompt for password'
complete -c timedatectl -s 'H' -l 'host' -d 'Operate on remote HOST'
complete -c timedatectl -s 'M' -l 'machine' -d 'Operate on local CONTAINER'
complete -c timedatectl -l 'adjust-system-clock' -d 'Adjust system clock when changing local RTC mode'
complete -c timedatectl -l 'monitor' -d 'Monitor status of systemd-timesyncd'
complete -c timedatectl -s 'p' -l 'property' -d 'Show only properties by this NAME'
complete -c timedatectl -s 'a' -l 'all' -d 'Show all properties'
complete -c timedatectl -l 'value' -d 'Only show properties with values'
