complete -c tmutil -d 'Add an exclusion not to back up a file'
complete -c tmutil -s 'v' -d 'Volume exclusion'
complete -c tmutil -s 'p' -d 'Path exclusion'
complete -c tmutil -d 'Bind a snapshot volume directory to the specified local disk'
complete -c tmutil -d 'Determine the amount of change between snapshots'
complete -c tmutil -d 'Perform a backup diff'
complete -c tmutil -s 'a' -d 'Compare all supported metadata'
complete -c tmutil -s 'n' -d 'No metadata comparison'
complete -c tmutil -s '@' -d 'Compare extended attributes'
complete -c tmutil -s 'c' -d 'Compare creation times'
complete -c tmutil -s 'd' -d 'Compare file data forks'
complete -c tmutil -s 'e' -d 'Compare ACLs'
complete -c tmutil -s 'f' -d 'Compare file flags'
complete -c tmutil -s 'g' -d 'Compare GIDs'
complete -c tmutil -s 'm' -d 'Compare file modes'
complete -c tmutil -s 's' -d 'Compare sizes'
complete -c tmutil -s 't' -d 'Compare modification times'
complete -c tmutil -s 'u' -d 'Compare UIDs'
complete -c tmutil -s 'D' -d 'Limit traversal depth to depth levels from the beginning of iteration'
complete -c tmutil -s 'E' -d 'Dont take exclusions into account'
complete -c tmutil -s 'I' -d 'Ignore path'
complete -c tmutil -s 'U' -d 'Ignore logical volume identity'
complete -c tmutil -d 'Delete one or more snapshots'
complete -c tmutil -d 'Delete all local Time Machine snapshots for the specified date (formatted YYYY-MM-DD-HHMMSS)'
complete -c tmutil -d 'Print information about destinations'
complete -c tmutil -d 'Turn off automatic backups'
complete -c tmutil -d 'Turn off local Time Machine snapshots'
complete -c tmutil -d 'Turn on automatic backups'
complete -c tmutil -d 'Turn on local Time Machine snapshots'
complete -c tmutil -d 'Claim a machine directory or sparsebundle for use by the current machine'
complete -c tmutil -d 'Determine if a file, directory, or volume are excluded from backups'
complete -c tmutil -d 'Print the path to the latest snapshot'
complete -c tmutil -d 'List the creation dates of all local Time Machine snapshots'
complete -c tmutil -d 'List local Time Machine snapshots of the specified volume'
complete -c tmutil -d 'Print paths for all snapshots'
complete -c tmutil -d 'Create new local Time Machine snapshot of APFS volume in TM backup'
complete -c tmutil -d 'Print the path to the current machine directory'
complete -c tmutil -d 'Removes a backup destination'
complete -c tmutil -d 'Remove an exclusion'
complete -c tmutil -s 'v' -d 'Volume exclusion'
complete -c tmutil -s 'p' -d 'Path exclusion'
complete -c tmutil -d 'Restore an item'
complete -c tmutil -s 'v'
complete -c tmutil -d 'Set a backup destination'
complete -c tmutil -s 'a' -d 'Add to the list of destinations'
complete -c tmutil -s 'p' -d 'Enter the password at a non-echoing interactive prompt'
complete -c tmutil -d 'Create new local Time Machine snapshot'
complete -c tmutil -d 'Begin a backup if one is not already running'
complete -c tmutil -s 'a' -l 'auto' -d 'Automatic mode'
complete -c tmutil -s 'b' -l 'block' -d 'Block until finished'
complete -c tmutil -s 'r' -l 'rotation' -d 'Automatic rotation'
complete -c tmutil -s 'd' -l 'destination' -d 'Backup destination'
complete -c tmutil -d 'Cancel a backup currently in progress'
complete -c tmutil -d 'Thin local Time Machine snapshots for the specified volume'
complete -c tmutil -d 'Analyze the specified path and determine its unique size'
complete -c tmutil -d 'Verify snapshot'
complete -c tmutil -d 'Print version'
complete -c tmutil -s 'X' -d 'Print as XML'
