complete -c tokei -s 'f' -l 'files' -d 'Print out statistics for individual files'
complete -c tokei -s 'h' -l 'help' -d 'Print help information'
complete -c tokei -l 'hidden' -d 'Count hidden files, too'
complete -c tokei -s 'l' -l 'languages' -d 'Print out supported languages'
complete -c tokei -l 'no-ignore' -d 'Don’t respect ignore files'
complete -c tokei -l 'no-ignore-parent' -d 'Don’t respect ignore files in parent directories'
complete -c tokei -l 'no-ignore-vcs' -d 'Don’t respect version-control ignore files'
complete -c tokei -s 'V' -l 'version' -d 'Print version information'
complete -c tokei -s 'v' -l 'verbose' -d 'Increase log output level'
complete -c tokei -s 'c' -l 'columns' -d 'Set column width for terminal output'
complete -c tokei -s 'e' -l 'exclude' -d 'Ignore all files and directories containing this word'
complete -c tokei -s 'i' -l 'input' -d 'Gives statistics from a previous Tokei run'
complete -c tokei -s 'o' -l 'output' -d 'Choose output format'
complete -c tokei -s 's' -l 'sort' -d 'Sort languages based on column'
complete -c tokei -s 't' -l 'type' -d 'Filters output by language type, comma-separated'
