complete -c toot -d 'Switch between accounts.'
complete -c toot -d 'Show logged in accounts and instances'
complete -c toot -d 'Display instance details'
complete -c toot -d 'Log in using your browser'
complete -c toot -d 'Log in from the console'
complete -c toot -d 'Log out'
complete -c toot -d 'Show notifications'
complete -c toot -d 'Post a status text'
complete -c toot -d 'Search for users or hashtags'
complete -c toot -d 'Show toot thread items'
complete -c toot -d 'Show recent items'
complete -c toot -d 'Toot terminal user interface'
complete -c toot -d 'Upload a file'
complete -c toot -d 'Display user details'
complete -c toot -d 'Display account details'
complete -c toot -d 'Delete a status'
complete -c toot -d 'Favourite a status'
complete -c toot -d 'Pin a status'
complete -c toot -d 'Reblog a status'
complete -c toot -d 'Show rebloggers of status'
complete -c toot -d 'Unfavourite a status'
complete -c toot -d 'Unpin a status'
complete -c toot -d 'Unreblog a status'
complete -c toot -d 'Follow an account'
complete -c toot -d 'Unfollow an account'
complete -c toot -d 'Mute an account'
complete -c toot -d 'Unmute an account'
complete -c toot -d 'Block an account'
complete -c toot -d 'Unblock an account'
complete -c toot -l 'debug' -d 'show debug log'
complete -c toot -l 'no-color' -d 'no colors in output'
complete -c toot -l 'quiet' -d 'don'"'"'t write to stdout on success'
complete -c toot -s 'h' -l 'help' -d 'show help message'
complete -c toot -l 'disable-https' -d 'disable HTTPS'
complete -c toot -s 'i' -l 'instance' -d 'mastodon instance'
complete -c toot -s 'u' -l 'using' -d 'account to use'
complete -c toot -s 'r' -l 'reverse' -d 'reverse order of output'
complete -c toot -s 'd' -l 'description' -d 'alt text for media file'
complete -c toot -s 'e' -l 'email' -d 'email address'
complete -c toot -l 'clear' -d 'delete all notifications'
complete -c toot -s 'm' -l 'mentions' -d 'only print mentions'
complete -c toot -s 'r' -l 'resolve' -d 'resolve non-local accounts'
complete -c toot -s 'p' -l 'public' -d 'show public timeline'
complete -c toot -s 't' -l 'tag' -d 'show hastag timeline'
complete -c toot -s 'l' -l 'local' -d 'show only statuses from local instance'
complete -c toot -l 'list' -d 'show timeline for given list'
complete -c toot -s 'c' -l 'count' -d 'number of toots per page'
complete -c toot -s '1' -l 'once' -d 'do not prompt to continue'
complete -c toot -s 'm' -l 'media' -d 'path to the media file'
complete -c toot -s 'v' -l 'visibility' -d 'post visibility'
complete -c toot -s 's' -l 'sensitive' -d 'mark as NSFW'
complete -c toot -s 'p' -l 'spoiler-text' -d 'warning text before content'
complete -c toot -s 'r' -l 'reply-to' -d 'ID of the status to reply to'
complete -c toot -s 'l' -l 'language' -d 'language code of the toot'
complete -c toot -s 'e' -l 'editor' -d 'editor to compose toot'
complete -c toot -l 'scheduled-at' -d 'datetime at which to schedule'
complete -c toot -s 't' -l 'content-type' -d 'MIME type'
