complete -c topgrade -s 'c' -l 'cleanup' -d 'Cleanup temporary or old files'
complete -c topgrade -l 'disable-predefined-git-repos' -d 'Don'"'"'t pull the predefined git repos'
complete -c topgrade -s 'n' -l 'dry-run' -d 'Print what would be done'
complete -c topgrade -l 'edit-config' -d 'Edit the configuration file'
complete -c topgrade -s 'h' -l 'help' -d 'Prints help information'
complete -c topgrade -s 'k' -l 'keep' -d 'Prompt for a key before exiting'
complete -c topgrade -l 'no-retry' -d 'Do not ask to retry failed steps'
complete -c topgrade -s 't' -l 'tmux' -d 'Run inside tmux'
complete -c topgrade -l 'config-reference' -d 'Show config reference'
complete -c topgrade -l 'show-skipped' -d 'Show the reason for skipped steps'
complete -c topgrade -s 'V' -l 'version' -d 'Prints version information'
complete -c topgrade -s 'v' -l 'verbose' -d 'Output logs'
complete -c topgrade -l 'config' -d 'Alternative configuration file'
complete -c topgrade -l 'disable' -d 'Do not perform upgrades for the given steps'
complete -c topgrade -l 'only' -d 'Perform only the specified steps (experimental)'
complete -c topgrade -l 'remote-host-limit' -d 'A regular expression for restricting remote host execution'
complete -c topgrade -s 'y' -l 'yes' -d 'Say yes to package manager'"'"'s prompt'
