complete -c trash-put -s 'h' -l 'help' -d 'show help message'
complete -c trash-put -l 'print-completion' -d 'print shell completion script'
complete -c trash-put -s 'd' -l 'directory' -d 'ignored (for GNU rm compatibility)'
complete -c trash-put -s 'f' -l 'force' -d 'silently ignore nonexistent files'
complete -c trash-put -s 'i' -l 'interactive' -d 'prompt before every removal'
complete -c trash-put -s 'r' -s 'R' -l 'recursive' -d 'ignored (for GNU rm compatibility)'
complete -c trash-put -l 'trash-dir' -d 'specify trash folder'
complete -c trash-put -s 'v' -l 'verbose' -d 'be verbose'
complete -c trash-put -l 'version' -d 'show version number'
