complete -c travis -d 'Displays accounts and their subscription status'
complete -c travis -d 'Displays the most recent build for each branch'
complete -c travis -d 'Lists or deletes repository caches'
complete -c travis -d 'Cancels a job or build'
complete -c travis -d 'Interactive shell'
complete -c travis -d 'Disables a project'
complete -c travis -d 'Enables a project'
complete -c travis -d 'Encrypts values for the .travis.yml'
complete -c travis -d 'Encrypts a file and adds decryption steps to .travis.yml'
complete -c travis -d 'Displays or changes the API endpoint'
complete -c travis -d 'Show or modify build environment variables'
complete -c travis -d 'Helps you out when in dire need of information'
complete -c travis -d 'Displays a projects build history'
complete -c travis -d 'Generates a .travis.yml and enables the project'
complete -c travis -d 'Display warnings for a .travis.yml'
complete -c travis -d 'Authenticates against the API and stores the token'
complete -c travis -d 'Deletes the stored API token'
complete -c travis -d 'Streams test logs'
complete -c travis -d 'Live monitor for what'"'"'s going on'
complete -c travis -d 'Opens a build or job in the browser'
complete -c travis -d 'Prints out a repository'"'"'s public key'
complete -c travis -d 'Makes an (authenticated) API call and prints out the result'
complete -c travis -d 'Generates a report useful for filing issues'
complete -c travis -d 'Lists repositories the user has certain permissions on'
complete -c travis -d 'Lists recent requests'
complete -c travis -d 'Restarts a build or job'
complete -c travis -d 'Access repository settings'
complete -c travis -d 'Sets up an addon or deploy target'
complete -c travis -d 'Displays a build or job'
complete -c travis -d 'Checks, updates or deletes an SSH key'
complete -c travis -d 'Checks status of the latest build'
complete -c travis -d 'Triggers a new sync with GitHub'
complete -c travis -d 'Outputs the secret API token'
complete -c travis -d 'Outputs the client version'
complete -c travis -d 'Lists most recent builds'
complete -c travis -d 'Outputs the current user'
complete -c travis -s 'h' -l 'help' -d 'Display help'
complete -c travis -s 'i' -l 'interactive' -d 'Be interactive and colorful'
complete -c travis -l 'no-interactive' -d 'Don'"'"'t be interactive and colorful'
complete -c travis -s 'E' -l 'explode' -d 'Don'"'"'t rescue exceptions'
complete -c travis -l 'no-explode' -d 'Rescue exceptions'
complete -c travis -l 'skip-version-check' -d 'Don'"'"'t check if travis client is up to date'
complete -c travis -l 'skip-completion-check' -d 'Don'"'"'t check if auto-completion is set up'
