complete -c tshark -s '2' -d 'Perform a two-pass analysis'
complete -c tshark -s 'H' -d 'Read a list of entries from a "hosts" file'
complete -c tshark -s 'j' -d 'Protocol match filter used for ek|json|jsonraw|pdml output file types'
complete -c tshark -s 'J' -d 'Protocol match filter used, includes all child protocols'
complete -c tshark -s 'l' -d 'Flush the standard output after the information for each packet is printed'
complete -c tshark -s 'O' -d 'Show a detailed view of the comma-separated list of protocols'
complete -c tshark -s 'P' -l 'print' -d 'Decode and display packet summary or details'
complete -c tshark -s 'Q' -d 'When capturing packets, don'"'"'t display, on the standard error, the initial message'
complete -c tshark -s 'S' -d 'Set the line separator to be printed between packets'
complete -c tshark -s 'V' -d 'Causes TShark to print a view of packet details'
complete -c tshark -s 'W' -d 'Save extra information in the capture file if the format supports it'
complete -c tshark -s 'x' -d 'Print hex and ASCII dumps of packet data'
complete -c tshark -s 'M' -d 'Automatically reset internal session when reaching N packets'
complete -c tshark -l 'color' -d 'Enable coloring of packets according to standard Wireshark color filters'
complete -c tshark -l 'no-duplicate-keys' -d 'Merge duplicate keys in json output'
complete -c tshark -l 'elastic-mapping-filter' -d 'Only put specified protocols in an ElasticSearch mapping file'
complete -c tshark -l 'export-objects' -d 'Export all objects within a protocol into directory given destination directory'
