complete -c typst -l 'color' -d 'Set when to use color'
complete -c typst -l 'cert' -d 'Path to custom CA certificate'
complete -c typst -l 'version' -s 'v' -d 'Print version'
complete -c typst -l 'help' -s 'h' -d 'Print help'
complete -c typst -d 'Print help for the given subcommand(s)'
complete -c typst -d 'Compile an input file'
complete -c typst -d 'Watch an input file and recompile on changes'
complete -c typst -d 'Initialize a new project'
complete -c typst -d 'Process an input file to extract metadata'
complete -c typst -d 'List all discovered fonts'
complete -c typst -d 'Self update the Typst CLI'
complete -c typst -d 'Input file'
complete -c typst -l 'root' -d 'Project root (for absolute paths)'
complete -c typst -l 'input' -d 'String key-value pair for `sys.inputs`'
complete -c typst -l 'font-path' -d 'Additional directories to search for fonts'
complete -c typst -l 'diagnostic-format' -d 'Format to emit diagnostics in'
complete -c typst -l 'format' -s 'f' -d 'Format of the output file'
complete -c typst -l 'open' -d 'Open output file after compilation'
complete -c typst -l 'ppi' -d 'Pixels per inch for PNG export'
complete -c typst -l 'timings' -d 'Produce performance timings'
complete -c typst -d 'Template to use'
complete -c typst -d 'Project directory'
complete -c typst -l 'field' -d 'Extract just one field'
complete -c typst -l 'one' -d 'Retrieve exactly one element'
complete -c typst -l 'format' -d 'Format to serialize in'
complete -c typst -l 'variants' -d 'List style variants of each family'
complete -c typst -l 'force' -d 'Force a downgrade to an older version'
complete -c typst -l 'revert' -d 'Revert to the version from before the last update'
