complete -c udevadm -s 'h' -l 'help' -d 'Show help'
complete -c udevadm -s 'V' -l 'version' -d 'Show version info'
complete -c udevadm -s 'q' -l 'query' -d 'Query device information'
complete -c udevadm -s 'p' -l 'path' -d 'sysfs device path'
complete -c udevadm -s 'n' -l 'name' -d 'Node or symlink name'
complete -c udevadm -s 'r' -l 'root' -d 'Prepend dev directory'
complete -c udevadm -s 'a' -l 'attribute-walk' -d 'Print all key matches'
complete -c udevadm -s 'd' -l 'device-id-of-file' -d 'Print major:minor of device containing FILE'
complete -c udevadm -s 'x' -l 'export' -d 'Export key/value pairs'
complete -c udevadm -s 'P' -l 'export-prefix' -d 'Export key name with prefix'
complete -c udevadm -s 'e' -l 'export-db' -d 'Export content of udev database'
complete -c udevadm -s 'c' -l 'cleanup-db' -d 'Clean up the udev database'
complete -c udevadm -s 'v' -l 'verbose' -d 'Print device paths while running'
complete -c udevadm -s 'n' -l 'dry-run' -d 'Do not actually trigger'
complete -c udevadm -s 't' -l 'type' -d 'Type of events to trigger'
complete -c udevadm -s 'c' -l 'action' -d 'Event action value [change]'
complete -c udevadm -s 's' -l 'subsystem-match' -d 'Trigger devices matching subsystem'
complete -c udevadm -s 'S' -l 'subsystem-nomatch' -d 'Exclude devices matching subsystem'
complete -c udevadm -s 'a' -l 'attr-match' -d 'Trigger devices matching attribute'
complete -c udevadm -s 'A' -l 'attr-nomatch' -d 'Exclude devices matching attribute'
complete -c udevadm -s 'p' -l 'property-match' -d 'Trigger devices matching property'
complete -c udevadm -s 'g' -l 'tag-match' -d 'Trigger devices matching property'
complete -c udevadm -s 'y' -l 'sysname-match' -d 'Trigger devices matching /sys path'
complete -c udevadm -l 'name-match' -d 'Trigger devices matching /dev path'
complete -c udevadm -s 'b' -l 'parent-match' -d 'Trigger devices with parent device'
complete -c udevadm -s 't' -l 'timeout' -d 'Maximum time in seconds to wait'
complete -c udevadm -s 'E' -l 'exit-if-exists' -d 'Stop waiting if FILE exists'
complete -c udevadm -s 'e' -l 'exit' -d 'Exit the daemon'
complete -c udevadm -s 'l' -l 'log-priority' -d 'Set udev daemon log level'
complete -c udevadm -s 's' -l 'stop-exec-queue' -d 'Queue but do not execute events'
complete -c udevadm -s 'S' -l 'start-exec-queue' -d 'Execute events, flush queue'
complete -c udevadm -s 'R' -l 'reload' -d 'Reload rules and database'
complete -c udevadm -s 'p' -l 'property' -d 'Set property globally'
complete -c udevadm -s 'm' -l 'children-max' -d 'Max num of children'
complete -c udevadm -s 't' -l 'timeout' -d 'Max seconds to block for reply'
complete -c udevadm -s 'p' -l 'property' -d 'Print event properties'
complete -c udevadm -s 'k' -l 'kernel' -d 'Print kernel uevents'
complete -c udevadm -s 'u' -l 'udev' -d 'Print udev events'
complete -c udevadm -s 's' -l 'subsystem-match' -d 'Filter events by subsystem'
complete -c udevadm -s 't' -l 'tag-match' -d 'Filter events by tag'
complete -c udevadm -s 'a' -l 'action' -d 'Set action string'
complete -c udevadm -s 'N' -l 'resolve-names' -d 'When to resolve names'
