complete -c unrar -d 'Extract files to current directory'
complete -c unrar -d 'List archive'
complete -c unrar -d 'List archive (technical)'
complete -c unrar -d 'List archive (bare)'
complete -c unrar -d 'Print file to stdout'
complete -c unrar -d 'Test archive files'
complete -c unrar -d 'Verbosely list archive'
complete -c unrar -d 'Verbosely list archive (technical)'
complete -c unrar -d 'Verbosely list archive (bare)'
complete -c unrar -d 'Extract files with full path'
