complete -c usbip -d 'Attach a USB device to the host'
complete -c usbip -d 'Detach a USB device from the host'
complete -c usbip -d 'List USB devices on the host'
complete -c usbip -d 'Bind a USB device to a driver'
complete -c usbip -d 'Unbind a USB device from a driver'
complete -c usbip -d 'List USB ports on the host'
complete -c usbip -s 'r' -l 'remote' -d 'The machine with exported USB devices'
complete -c usbip -s 'b' -l 'busid' -d 'Busid of the device on <host>'
complete -c usbip -s 'd' -l 'device' -d 'Id of the virtual UDB on <host>'
complete -c usbip -s 'p' -l 'port' -d 'Vhci_hcd port the device is on'
complete -c usbip -s 'p' -l 'parsable' -d 'Parsable list format'
complete -c usbip -s 'r' -l 'remote' -d 'List the exportable USB devices on <host>'
complete -c usbip -s 'l' -l 'local' -d 'List the local USB devices'
complete -c usbip -s 'd' -l 'device' -d 'List the local USB gadgets bound to usbip-vudc'
complete -c usbip -s 'b' -l 'busid' -d 'Bind usbip-host.ko to device on <busid>'
complete -c usbip -s 'b' -l 'busid' -d 'Unbind usbip-host.ko to device on <busid>'
