complete -c useradd -s 'c' -l 'comment' -d 'A comment about this user'
complete -c useradd -s 'd' -l 'home' -d 'Home directory for the new user'
complete -c useradd -s 'G' -l 'groups' -d 'Supplementary groups'
complete -c useradd -s 'h' -l 'help' -d 'Display help message and exit'
complete -c useradd -s 'n' -d 'Create group with name of added user if -g is not specified'
complete -c useradd -s 'K' -l 'key' -d 'Overrides default key/value pairs from /etc/login'
complete -c useradd -s 'o' -l 'non-unique' -d 'Allow user account with a duplicate UID'
complete -c useradd -s 'p' -l 'password' -d 'The encrypted password, as returned by crypt(3)'
complete -c useradd -s 'e' -l 'expiredate' -d 'The date on which the user account is disabled'
complete -c useradd -s 'f' -l 'inactive' -d 'Number of days to disable account after password expiration'
