complete -c userdbctl -d 'Inspect user'
complete -c userdbctl -d 'Inspect group'
complete -c userdbctl -d 'Show users that are members of specified group(s)'
complete -c userdbctl -d 'Show groups the specified user(s) is a member of'
complete -c userdbctl -d 'Show enabled database services'
complete -c userdbctl -s 'h' -l 'help' -d 'Show help'
complete -c userdbctl -l 'version' -d 'Show version'
complete -c userdbctl -l 'no-pager' -d 'Do not pipe output into a pager'
complete -c userdbctl -l 'no-legend' -d 'Do not show the headers and footers'
complete -c userdbctl -l 'output' -d 'Select output mode'
complete -c userdbctl -s 'j' -d 'Equivalent to --output=json'
complete -c userdbctl -s 's' -l 'service' -d 'Query the specified service'
complete -c userdbctl -l 'with-nss' -d 'Control whether to include glibc NSS data'
complete -c userdbctl -s 'N' -d 'Do not synthesize or include glibc NSS data'
complete -c userdbctl -l 'synthesize' -d 'Synthesize root/nobody user'
