complete -c vagrant -d 'Manage boxes: installation, removal, etc.'
complete -c vagrant -d 'Manage Vagrant Cloud'
complete -c vagrant -d 'Stop and delete all traces of the vagrant machine'
complete -c vagrant -d 'Show status Vagrant environments for this user'
complete -c vagrant -d 'Stop a machine'
complete -c vagrant -d 'Show help for a subcommand'
complete -c vagrant -d 'Initialize a new Vagrant env by creating a Vagrantfile'
complete -c vagrant -d 'Package a running vagrant environment into a box'
complete -c vagrant -d 'Manages plugins: install, uninstall, update, etc.'
complete -c vagrant -d 'Connect to a machine via SSH'
complete -c vagrant -d 'Print ssh config to connect to machine'
complete -c vagrant -d 'Print status of a machine'
complete -c vagrant -d 'Suspend a machine'
complete -c vagrant -d 'Start and provision the environment'
complete -c vagrant -d 'Print current and latest version'
