complete -c valgrind -l 'help' -d 'Display help and exit'
complete -c valgrind -l 'help-debug' -d 'Display help and debug options'
complete -c valgrind -l 'version' -d 'Display version and exit'
complete -c valgrind -s 'q' -l 'quiet' -d 'Quiet mode'
complete -c valgrind -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c valgrind -l 'demangle'
complete -c valgrind -l 'gen-suppressions' -d 'Print suppressions for detected errors'
complete -c valgrind -l 'alloc-fn' -d 'Specify a function that allocates memory'
complete -c valgrind -l 'heap' -d 'Profile heap usage'
complete -c valgrind -l 'heap-admin' -d 'The number of bytes of heap overhead per allocation'
complete -c valgrind -l 'stacks' -d 'Profile stack usage'
complete -c valgrind -l 'depth' -d 'Depth of call chain'
complete -c valgrind -l 'format' -d 'Profiling output format'
