complete -c vbc -d 'Suppresses compiler banner information'
complete -c vbc -d 'Displays compiler output using UTF-8 encoding'
complete -c vbc -d 'Disable -utf8output'
complete -c vbc -d 'Outputs extra information during compilation'
complete -c vbc -d 'Disable -verbose'
complete -c vbc -d 'Specify the name of the source module'
complete -c vbc -d 'Specify a language for compiler output'
complete -c vbc -d 'Enable optimizations'
complete -c vbc -d 'Disable optimizations'
complete -c vbc -d 'Process documentation comments to an XML file'
complete -c vbc -d 'Disable -doc'
complete -c vbc -d 'Output identical assemblies for identical inputs'
complete -c vbc -d 'Sets the compiler to target the .NET Compact Framework'
complete -c vbc -d 'Specifies an output file'
complete -c vbc -d 'Outputs only a reference assembly'
complete -c vbc -d 'Specifies the output path of a reference assembly'
complete -c vbc -d 'Create a console application'
complete -c vbc -d 'Create a dynamic-link library'
complete -c vbc -d 'Create a module that can be added to an assembly'
complete -c vbc -d 'Create Windows application'
complete -c vbc -d 'Create Windows application that must be run in an app container'
complete -c vbc -d 'Create an intermediate file that can be converted to .winmd file'
complete -c vbc -d 'Add type information from provided files to the project'
complete -c vbc -d 'Specifies whether the assembly will be fully or partially signed'
complete -c vbc -d 'Disable -delaysign'
complete -c vbc -d 'Imports a namespace from a specified assembly'
complete -c vbc -d 'Specify a strong name key container'
complete -c vbc -d 'Specify a strong name key file'
complete -c vbc -d 'Specifies the location of assemblies referenced by the -reference option'
complete -c vbc -d 'Imports metadata from an assembly'
complete -c vbc -d 'Specifies the name of the assembly that a module will be a part of'
complete -c vbc -d 'Run the analyzers from this assembly'
complete -c vbc -d 'Files that analyzers can use to generate error or warning'
complete -c vbc -d 'Creates a file that contains information that makes it easy to report a bug'
complete -c vbc -d 'Produces debugging information'
complete -c vbc -d 'Disable -debug'
complete -c vbc -d 'Suppresses the compiler'"'"'s ability to generate warnings'
complete -c vbc -d 'Don'"'"'t display code for syntax-related errors and warnings'
complete -c vbc -d 'Disables integer overflow checking'
complete -c vbc -d 'Disable -removeintchecks'
complete -c vbc -d 'Promotes warnings to errors'
complete -c vbc -d 'Disable -warnaserror'
complete -c vbc -d 'Specify a ruleset file that disables specific diagnostics'
complete -c vbc -s '?' -d 'Displays the compiler options'
complete -c vbc -d 'Display the allowed values for language version'
complete -c vbc -d 'Specify latest major version as language version'
complete -c vbc -d 'Specify latest version (including minor releases) as language version'
complete -c vbc -d 'Enforces explicit declaration of variables'
complete -c vbc -d 'Disable -optionexplicit'
complete -c vbc -d 'Enforces strict type semantics'
complete -c vbc -d 'Disable -optionstrict'
complete -c vbc -d 'Enables the use of local type inference in variable declarations'
complete -c vbc -d 'Disable -optioninfer'
complete -c vbc -d 'Defines symbols for conditional compilation'
complete -c vbc -d 'Creates a link to a managed resource'
complete -c vbc -d 'Embeds a managed resource in an assembly'
complete -c vbc -d 'Inserts an .ico file into the output file'
complete -c vbc -d 'Inserts a Win32 resource into the output file'
complete -c vbc -d 'Specifies the base address of a DLL'
complete -c vbc -d 'Specify the code page for source code files'
complete -c vbc -d 'Specify if an executable supports high entropy ASLR'
complete -c vbc -d 'Disable -highentropyva'
complete -c vbc -d 'Specifies the class that contains the Sub Main procedure to use at startup'
complete -c vbc -d 'Do not compile with Vbc.rsp'
complete -c vbc -d 'Causes the compiler not to reference the standard libraries'
complete -c vbc -d 'Don'"'"'t embed any application manifest into the executable'
complete -c vbc -d 'Specify x86 as target platform'
complete -c vbc -d 'Specify AMD64 or EM64T as target platform'
complete -c vbc -d 'Specify Itanium as target platform'
complete -c vbc -d 'Specify ARM as target platform'
complete -c vbc -d 'Specify any platform as target'
complete -c vbc -d 'Specify any platform as target (32-bit process on 64-bit machine)'
complete -c vbc -d 'Searches subdirectories for source files to compile'
complete -c vbc -d 'Specifies a namespace for all type declarations'
complete -c vbc -d 'Specifies the location of Mscorlib.dll and Microsoft.VisualBasic.dll'
complete -c vbc -d 'Specify reference to VB Runtime Library or disable library referencing'
complete -c vbc -d 'Provide application manifest file'
complete -c vbc -d 'Specifies whether to use concurrent build'
complete -c vbc -d 'Disable -parallel'
complete -c vbc -d 'Use SHA1 to calculate the source file checksum'
complete -c vbc -d 'Use SHA256 to calculate the source file checksum'
