complete -c VBoxHeadless -l 'startvm' -s 's' -d 'Start given VM'
complete -c VBoxHeadless -l 'vrde' -s 'v' -d 'Enable or disamble VRDE server or don'"'"'t change setting'
complete -c VBoxHeadless -l 'vrdeproperty' -s 'e' -d 'Set VRDE property'
complete -c VBoxHeadless -l 'settingspw' -d 'Specify settings password'
complete -c VBoxHeadless -l 'settingspwfile' -d 'Specify file containing setting password'
complete -c VBoxHeadless -l 'start-paused' -d 'Start VM in paused state'
complete -c VBoxHeadless -l 'capture' -s 'c' -d 'Record VM screen output to file'
complete -c VBoxHeadless -l 'width' -s 'w' -d 'Frame width when recording'
complete -c VBoxHeadless -l 'height' -s 'h' -d 'Frame height when recording'
complete -c VBoxHeadless -l 'bitrate' -s 'r' -d 'Recording bit rate when recording'
complete -c VBoxHeadless -l 'filename' -s 'f' -d 'File name when recording'
