complete -c vim-addons -d 'list the names of the addons available in the system'
complete -c vim-addons -d 'show the status of the addons available in the system'
complete -c vim-addons -d 'install one or more addons under ~/.vim'
complete -c vim-addons -d 'remove one or more addons from ~/.vim'
complete -c vim-addons -d 'disable  one  or more addons to be used by the current user'
complete -c vim-addons -d 'undo the effects of a previous disable command'
complete -c vim-addons -d 'list, one per line, the files composing the specified addons'
complete -c vim-addons -d 'displays detailed information about the specified addons'
complete -c vim-addons -s 'h' -l 'help' -d 'show this usage message and exit'
complete -c vim-addons -s 'q' -l 'query' -d 'be quiet and make the output more parseable'
complete -c vim-addons -s 'r' -l 'registry-dir' -d 'set the registry directory'
complete -c vim-addons -s 's' -l 'source-dir' -d 'set the addons source directory'
complete -c vim-addons -s 't' -l 'target-dir' -d 'set the addons target directory'
complete -c vim-addons -s 'v' -l 'verbose' -d 'increase verbosity'
complete -c vim-addons -s 'y' -l 'system-dir' -d 'set the system-wide target directory'
complete -c vim-addons -s 'w' -l 'system-wide' -d 'set target directory to the system-wide one'
