complete -c vim -s 'c' -d 'Execute Ex command after the first file has been read'
complete -c vim -s 'S' -d 'Source file after the first file has been read'
complete -c vim -l 'cmd' -d 'Execute Ex command before loading any vimrc'
complete -c vim -s 'd' -d 'Use device as terminal (Amiga only)'
complete -c vim -s 'i' -d 'Set the viminfo file location'
complete -c vim -s 'o' -d 'Open horizontally split windows for each file'
complete -c vim -d 'Open two horizontally split windows'
complete -c vim -s 'O' -d 'Open vertically split windows for each file'
complete -c nvim -d 'Open two vertically split windows'
complete -c vim -s 'p' -d 'Open tab pages for each file'
complete -c nvim -d 'Open two tab pages'
complete -c vim -s 'q' -d 'Start in quickFix mode'
complete -c vim -s 'r' -d 'Use swap files for recovery'
complete -c vim -s 's' -d 'Source and execute script file'
complete -c vim -s 't' -d 'Set the cursor to tag'
complete -c vim -s 'T' -d 'Terminal name'
complete -c vim -s 'u' -d 'Use alternative vimrc'
complete -c vim -s 'U' -d 'Use alternative vimrc in GUI mode'
complete -c vim -s 'w' -d 'Record all typed characters'
complete -c vim -s 'W' -d 'Record all typed characters (overwrite file)'
complete -c vim -s 'A' -d 'Start in Arabic mode'
complete -c vim -s 'b' -d 'Start in binary mode'
complete -c vim -s 'C' -d 'Behave mostly like vi'
complete -c vim -s 'd' -d 'Start in diff mode'
complete -c vim -s 'D' -d 'Debugging mode'
complete -c vim -s 'e' -d 'Start in Ex mode'
complete -c vim -s 'E' -d 'Start in improved Ex mode'
complete -c vim -s 'f' -d 'Start in foreground mode'
complete -c vim -s 'F' -d 'Start in Farsi mode'
complete -c vim -s 'g' -d 'Start in GUI mode'
complete -c vim -s 'h' -d 'Print help message and exit'
complete -c vim -s 'H' -d 'Start in Hebrew mode'
complete -c vim -s 'L' -d 'List swap files'
complete -c vim -s 'l' -d 'Start in lisp mode'
complete -c vim -s 'm' -d 'Disable file modification'
complete -c vim -s 'M' -d 'Disallow file modification'
complete -c vim -s 'N' -d 'Reset compatibility mode'
complete -c vim -s 'R' -d 'Read only mode'
complete -c vim -s 'r' -d 'List swap files'
complete -c vim -s 's' -d 'Start in silent mode'
complete -c vim -s 'V' -d 'Start in verbose mode'
complete -c vim -s 'v' -d 'Start in vi mode'
complete -c vim -s 'x' -d 'Use encryption when writing files'
complete -c vim -s 'y' -d 'Start in easy mode'
complete -c vim -s 'Z' -d 'Start in restricted mode'
complete -c vim -d 'Become an editor server for NetBeans'
complete -c vim -l 'no-fork' -d 'Start in foreground mode'
complete -c vim -l 'echo-wid' -d 'Echo the Window ID on stdout (GTK GUI only)'
complete -c vim -l 'help' -d 'Print help message and exit'
complete -c vim -l 'literal' -d 'Do not expand wildcards'
complete -c vim -l 'noplugin' -d 'Skip loading plugins'
complete -c vim -l 'remote' -d 'Edit files on Vim server'
complete -c vim -l 'remote-expr' -d 'Evaluate expr on Vim server'
complete -c vim -l 'remote-send' -d 'Send keys to Vim server'
complete -c vim -l 'remote-silent' -d 'Edit files on Vim server'
complete -c vim -l 'remote-wait' -d 'Edit files on Vim server'
complete -c vim -l 'remote-wait-silent' -d 'Edit files on Vim server'
complete -c vim -l 'serverlist' -d 'List all Vim servers that can be found'
complete -c vim -l 'servername' -d 'Set server name'
complete -c vim -l 'version' -d 'Print version information and exit'
complete -c vim -l 'socketid' -d 'Run gvim in another window (GTK GUI only)'
complete -c vim -l 'clean' -d 'Factory defaults: skip vimrc, plugins, viminfo'
complete -c vim -l 'startuptime' -d 'Write startup timing messages to <file>'
