complete -c wajig -d 'Packages'
complete -c wajig -s 'q' -l 'quiet' -d 'Do system commands everything quietly.'
complete -c wajig -s 'n' -l 'noauth' -d 'Allow packages from unathenticated archives.'
complete -c wajig -s 't' -l 'teaching' -d 'Trace the sequence of commands performed.'
complete -c wajig -s 'y' -l 'yes' -d 'Assume yes for any questions asked.'
complete -c wajig -d 'Add a CD-ROM to the list of available sources of packages'
complete -c wajig -d 'Mark the alternative to be auto set (using set priorities)'
complete -c wajig -d 'Remove superseded deb files from the download cache'
complete -c wajig -d 'Do an update followed by a download of all updated packages'
complete -c wajig -d 'Perform an install without asking questions (non-interactive)'
complete -c wajig -d 'List versions of packages available for installation'
complete -c wajig -d 'Check reported bugs in package using the Debian Bug Tracker'
complete -c wajig -d 'Retrieve/unpack sources and build .deb for the named packages'
complete -c wajig -d 'Retrieve packages required to build listed packages'
complete -c wajig -d 'Retrieve latest changelog for the package'
complete -c wajig -d 'Remove all deb files from the download cache'
complete -c wajig -d 'List all the JIG commands and one line descriptions for each'
complete -c wajig -d 'Perform an update then a dist-upgrade'
complete -c wajig -d 'List of packages which depend/recommend/suggest the package'
complete -c wajig -d 'One line description of packages (-v and -vv for more detail)'
complete -c wajig -d 'One line description of new packages'
complete -c wajig -d 'Provide a detailed description of package (describe -vv)'
complete -c wajig -d 'Provide a detailed description of new packages (describe -vv)'
complete -c wajig -d 'Upgrade to new distribution (installed and new rqd packages)'
complete -c wajig -d 'Equivalent to help with -verbose=2'
complete -c wajig -d 'Download package files ready for an install'
complete -c wajig -d 'Download packages listed in file ready for an install'
complete -c wajig -d 'Install packages listed in a file'
complete -c wajig -d 'Remove packages listed in a file'
complete -c wajig -d 'Search for a file within installed packages'
complete -c wajig -d 'Search for an unofficial Debian package at apt-get.org'
complete -c wajig -d 'Perform dpkg --configure -a (to fix interrupted configure)'
complete -c wajig -d 'Perform apt-get -f install (to fix broken dependencies)'
complete -c wajig -d 'Perform apt-get --fix-missing upgrade'
complete -c wajig -d 'Install packages and ignore file overwrites and depends'
complete -c wajig -d 'Print documentation (detail depends on --verbose)'
complete -c wajig -d 'Place listed packages on hold so they are not upgraded'
complete -c wajig -d 'Initialise or reset the JIG archive files'
complete -c wajig -d 'Install (or upgrade) one or more packages or .deb files'
complete -c wajig -d 'Install package and associated recommended packages'
complete -c wajig -d 'Install package and recommended and suggested packages'
complete -c wajig -d 'Install package and associated suggested packages'
complete -c wajig -d 'Check the integrity of installed packages (through checksums)'
complete -c wajig -d 'List size of all large (>10MB) installed packages'
complete -c wajig -d 'Identify when an update was last performed'
complete -c wajig -d 'List the status and description of installed packages'
complete -c wajig -d 'List a one line description of given or all packages'
complete -c wajig -d 'List the objects that can have alternatives configured'
complete -c wajig -d 'List the contents of the download cache'
complete -c wajig -d 'List all the JIG commands and one line descriptions for each'
complete -c wajig -d 'List the daemons that JIG can start/stop/restart'
complete -c wajig -d 'List the files that are supplied by the named package'
complete -c wajig -d 'List those packages on hold'
complete -c wajig -d 'List packages (with optional argument substring) installed'
complete -c wajig -d 'List the contents of the install/remove log file (filtered)'
complete -c wajig -d 'List all known packages or those containing supplied string'
complete -c wajig -d 'List libraries not required by any installed package'
complete -c wajig -d 'List the control scripts of the package of deb file'
complete -c wajig -d 'List packages that belong to a specific section'
complete -c wajig -d 'List the sections that are available'
complete -c wajig -d 'Same as list but only prints first two columns, not truncated'
complete -c wajig -d 'Same as list but avoids truncating package names'
complete -c wajig -d 'Dist-upgrade using packages already downloaded'
complete -c wajig -d 'Upgrade using packages already downloaded, but not any others'
complete -c wajig -d 'Runs the madison command of apt-cache.'
complete -c wajig -d 'Move packages in the download cache to a local Debian mirror'
complete -c wajig -d 'List packages that became available since last update'
complete -c wajig -d 'Obtain the latest news about the package'
complete -c wajig -d 'List packages newly available for upgrading'
complete -c wajig -d 'List installed packages that do not meet the DFSG'
complete -c wajig -d 'List libraries not required by any installed package'
complete -c wajig -d 'Generate a .deb file for an installed package'
complete -c wajig -d 'From preferences file show priorities/policy (available)'
complete -c wajig -d 'Remove one or more packages and configuration files'
complete -c wajig -d 'Purge package and those it depend on and not required by others'
complete -c wajig -d 'Purge orphaned libraries (not required by installed packages)'
complete -c wajig -d 'Download package and any packages it depends on'
complete -c wajig -d 'Install package and associated recommended packages'
complete -c wajig -d 'Reconfigure the named installed packages or run gkdebconf'
complete -c wajig -d 'Reinstall each of the named packages'
complete -c wajig -d 'Reload daemon configs, e.g., gdm, apache (see list-daemons)'
complete -c wajig -d 'Remove one or more packages (see also purge)'
complete -c wajig -d 'Remove package and its dependees not required by others'
complete -c wajig -d 'Remove orphaned libraries (not required by installed packages)'
complete -c wajig -d 'Generate a .deb file for an installed package'
complete -c wajig -d 'Initialise or reset the JIG archive files'
complete -c wajig -d 'Stop then start a daemon, e.g., gdm, apache (see list-daemons)'
complete -c wajig -d 'Install a RedHat .rpm package'
complete -c wajig -d 'Convert a RedHat .rpm file to a Debian .deb file'
complete -c wajig -d 'Search for packages containing listed words'
complete -c wajig -d 'Find local Debian archives suitable for sources.list'
complete -c wajig -d 'Configure the sources.list file which locates Debian archives'
complete -c wajig -d 'Provide a detailed description of package [same as detail]'
complete -c wajig -d 'Trace the steps that a dist-upgrade would perform'
complete -c wajig -d 'Trace the steps that an install would perform'
complete -c wajig -d 'Trace the steps that a remove would perform'
complete -c wajig -d 'Trace the steps that an upgrade would perform'
complete -c wajig -d 'Print out the size (in K) of all, or listed, installed packages'
complete -c wajig -d 'Print out the size (in K) of all, or listed, installed packages'
complete -c wajig -d 'Generates list of package=version for all installed packages'
complete -c wajig -d 'Retrieve and unpack sources for the named packages'
complete -c wajig -d 'Start a daemon, e.g., gdm, apache (see list-daemons)'
complete -c wajig -d 'Show the version and available version of packages'
complete -c wajig -d 'Show the version and available version of matching packages'
complete -c wajig -d 'Show the version and available version of matching packages'
complete -c wajig -d 'Stop a daemon, e.g., gdm, apache (see list-daemons)'
complete -c wajig -d 'Install package and associated suggested packages'
complete -c wajig -d 'Run the Gnome task selector to install groups of packages'
complete -c wajig -d 'List packages with newer versions available for upgrading'
complete -c wajig -d 'Remove listed packages from hold so they are again upgraded'
complete -c wajig -d 'Search for an unofficial Debian package at apt-get.org'
complete -c wajig -d 'Update the list of down-loadable packages'
complete -c wajig -d 'Update default alternative for things like x-window-manager'
complete -c wajig -d 'Updates the local list of PCI ids from the internet master list'
complete -c wajig -d 'Updates the local list of USB ids from the internet master list'
complete -c wajig -d 'Upgrade all of the installed packages or just those listed'
complete -c wajig -d 'List version and distribution of (all) packages.'
complete -c wajig -d 'A synonym for describe'
complete -c wajig -d 'Find the package that supplies the given command or file'
