complete -c watchexec -d 'Watch a specific file or directory'
complete -c watchexec -d 'Clear screen before running command'
complete -c watchexec -d 'What to do when receiving events while the command is running'
complete -c watchexec -d 'Restart the process if it'"'"'s still running'
complete -c watchexec -d 'Send a signal to the process when it'"'"'s still running'
complete -c watchexec -d 'Signal to send to sstop the command'
complete -c watchexec -d 'Time to wait for the command to exit gracefully'
complete -c watchexec -d 'Time to wait for new events before taking action'
complete -c watchexec -d 'Exit when stding closes'
complete -c watchexec -d 'Don'"'"'t load gitignores'
complete -c watchexec -d 'Don'"'"'t load project-local ignores'
complete -c watchexec -d 'Don'"'"'t load global ignores'
complete -c watchexec -d 'Don'"'"'t use internal default ignores'
complete -c watchexec -d 'Don'"'"'t discover ignore files at all'
complete -c watchexec -d 'Wait until first change before running command'
complete -c watchexec -d 'Sleep before running the command'
complete -c watchexec -d 'Poll for filesystem changes'
complete -c watchexec -d 'Use a different shell'
complete -c watchexec -d 'Don#t use a shell'
complete -c watchexec -d '--emit-events=none'
complete -c watchexec -d 'Configure event emission'
complete -c watchexec -d 'Add env vars to the command'
complete -c watchexec -d 'Don'"'"'t use a process group'
complete -c watchexec -d 'Alert when commands start and end'
complete -c watchexec -d 'Set the project origin'
complete -c watchexec -d 'Set the working directory'
complete -c watchexec -d 'Filename extensions to filter to'
complete -c watchexec -d 'Filename patterns to filter to'
complete -c watchexec -d 'Files to load filters from'
complete -c watchexec -d 'Filename patterns to filter out'
complete -c watchexec -d 'Files to load ignores from'
complete -c watchexec -d 'Filesystem events to filter to'
complete -c watchexec -d 'Filesystem events to filter to'
complete -c watchexec -d 'Print events that trigger actions'
complete -c watchexec -d 'Set diagnostic log level'
complete -c watchexec -d 'Write diagnostic logs to a file'
complete -c watchexec -d 'Show the manual page'
complete -c watchexec -d 'Print help (see a summary with '"'"'-h'"'"')'
complete -c watchexec -d 'Print version'
