complete -c wg -d 'Shows the current configuration and device information'
complete -c wg -d 'Shows the current configuration of an interface'
complete -c wg -d 'Change the current configuration'
complete -c wg -d 'Applies a configuration to an interface'
complete -c wg -d 'Appends a configuration to an interface'
complete -c wg -d 'Synchronizes a configuration to an interface'
complete -c wg -d 'Generates a new private key'
complete -c wg -d 'Generates a new preshared key'
complete -c wg -d 'Computes public key given a private key'
complete -c wg -l 'help' -d 'View usage of the subcommand'
complete -c wg -d 'Wireguard Interface'
complete -c wg -d 'Configuration file'
complete -c wg -d 'Wireguard Interface'
complete -c wg -d 'Shows a list of interfaces'
complete -c wg -d 'Shows information for all interfaces'
complete -c wg -d 'Wireguard Interface'
complete -c wg -d 'Wireguard Interface'
