complete -c wget -s 'V' -l 'version' -d 'Display version and exit'
complete -c wget -s 'h' -l 'help' -d 'Display help and exit'
complete -c wget -s 'b' -l 'background' -d 'Go to background immediately after startup'
complete -c wget -s 'e' -l 'execute' -d 'Execute command as if part of .wgetrc'
complete -c wget -s 'o' -l 'output-file' -d 'Log all messages to logfile'
complete -c wget -s 'a' -l 'append-output' -d 'Append all messages to logfile'
complete -c wget -s 'd' -l 'debug' -d 'Turn on debug output'
complete -c wget -s 'q' -l 'quiet' -d 'Quiet mode'
complete -c wget -s 'v' -l 'verbose' -d 'Verbose mode'
complete -c wget -l 'non-verbose' -d 'Turn off verbose without being completely quiet'
complete -c wget -d 'Turn off verbose without being completely quiet'
complete -c wget -s 'i' -l 'input-file' -d 'Read URLs from file'
complete -c wget -s 'F' -l 'force-html' -d 'Force input to be treated as HTML'
complete -c wget -s 'B' -l 'base' -d 'Prepend string to relative links'
complete -c wget -l 'bind-address' -d 'Bind address on local machine'
complete -c wget -s 't' -l 'tries' -d 'Set number of retries to number'
complete -c wget -s 'O' -l 'output-document' -d 'Concatenate output to file'
complete -c wget -l 'no-clobber' -d 'Never overwrite files with same name'
complete -c wget -d 'Never overwrite files with same name'
complete -c wget -s 'c' -l 'continue' -d 'Continue getting a partially-downloaded file'
complete -c wget -s 'N' -l 'timestamping' -d 'Turn on time-stamping'
complete -c wget -s 'S' -l 'server-response' -d 'Print the headers/responses sent by servers'
complete -c wget -l 'spider' -d 'Do not download the pages, just check that they are there'
complete -c wget -s 'T' -l 'timeout' -d 'Set the network timeout'
complete -c wget -l 'dns-timeout' -d 'Set the DNS lookup timeout'
complete -c wget -l 'connect-timeout' -d 'Set the connect timeout'
complete -c wget -l 'read-timeout' -d 'Set the read (and write) timeout'
complete -c wget -l 'limit-rate' -d 'Limit the download speed'
complete -c wget -s 'w' -l 'wait' -d 'Wait the specified number of seconds between the retrievals'
complete -c wget -l 'waitretry' -d 'Wait time between retries'
complete -c wget -l 'random-wait' -d 'Wait random amount of time between retrievals'
complete -c wget -s 'Y' -l 'proxy' -d 'Toggle proxy support'
complete -c wget -s 'Q' -l 'quota' -d 'Specify download quota for automatic retrievals'
complete -c wget -l 'dns-cache' -d 'Turn off caching of DNS lookups'
complete -c wget -l 'no-directories' -d 'Do not create a hierarchy of directories'
complete -c wget -d 'Do not create a hierarchy of directories'
complete -c wget -s 'x' -l 'force-directories' -d 'Force creation of a hierarchy of directories'
complete -c wget -l 'no-host-directories' -d 'Disable generation of host-prefixed directories'
complete -c wget -d 'Disable generation of host-prefixed directories'
complete -c wget -l 'protocol-directories' -d 'Use the protocol name as a directory component'
complete -c wget -l 'cut-dirs' -d 'Ignore specified number of directory components'
complete -c wget -s 'P' -l 'directory-prefix' -d 'Set directory prefix'
complete -c wget -s 'E' -l 'html-extension' -d 'Force html files to have html extension'
complete -c wget -l 'http-user' -d 'Specify the http username'
complete -c wget -l 'http-passwd' -d 'Specify the http password'
complete -c wget -l 'no-cache' -d 'Disable server-side cache'
complete -c wget -l 'no-cookies' -d 'Disable the use of cookies'
complete -c wget -l 'load-cookies' -d 'Load cookies from file'
complete -c wget -l 'save-cookies' -d 'Save cookies to file'
complete -c wget -l 'keep-session-cookies' -d 'Save session cookies'
complete -c wget -l 'ignore-length' -d 'Ignore '"'"'Content-Length'"'"' header'
complete -c wget -l 'header' -d 'Define an additional-header to be passed to the HTTP servers'
complete -c wget -l 'proxy-user' -d 'Specify the proxy username'
complete -c wget -l 'proxy-password' -d 'Specify the proxy password'
complete -c wget -l 'referer' -d 'Set referer URL'
complete -c wget -l 'save-headers' -d 'Save the headers sent by the HTTP server'
complete -c wget -s 'U' -l 'user-agent' -d 'Identify as agent-string'
complete -c wget -l 'post-data' -d 'Use POST for all HTTP requests and send the specified data in the request body'
complete -c wget -l 'post-file' -d 'Use POST for all HTTP requests and send the specified file in the request body'
complete -c wget -l 'no-http-keep-alive' -d 'Turn off keep-alive for http downloads'
complete -c wget -l 'secure-protocol' -d 'Choose secure protocol'
complete -c wget -l 'https-only' -d 'Only follow secure HTTPS links'
complete -c wget -l 'no-check-certificate' -d 'Don'"'"'t validate the server'"'"'s certificate'
complete -c wget -l 'certificate' -d 'Client certificate file'
complete -c wget -l 'certificate-type' -d 'Client certificate type'
complete -c wget -l 'private-key' -d 'Private key file'
complete -c wget -l 'private-key-type' -d 'Private key type'
complete -c wget -l 'ca-certificate' -d 'File with the bundle of CAs'
complete -c wget -l 'ca-directory' -d 'Directory where hash list of CAs is stored'
complete -c wget -l 'crl-file' -d 'File with bundle of CRLs'
complete -c wget -l 'random-file' -d 'File with random data for seeding the SSL PRNG'
complete -c wget -l 'egd-file' -d 'File naming the EGD socket with random data'
complete -c wget -l 'no-hsts' -d 'Disable HSTS'
complete -c wget -l 'hsts-file' -d 'Path of HSTS database'
complete -c wget -l 'no-remove-listing' -d 'Don'"'"'t remove the temporary .listing files generated'
complete -c wget -l 'no-glob' -d 'Turn off FTP globbing'
complete -c wget -l 'passive-ftp' -d 'Use the passive FTP retrieval scheme'
complete -c wget -l 'retr-symlinks' -d 'Traverse symlinks and retrieve pointed-to files'
complete -c wget -s 'r' -l 'recursive' -d 'Turn on recursive retrieving'
complete -c wget -s 'l' -l 'level' -d 'Specify recursion maximum depth'
complete -c wget -l 'delete-after' -d 'Delete every single file downloaded'
complete -c wget -s 'k' -l 'convert-links' -d 'Convert the links in the document to make them suitable for local viewing'
complete -c wget -s 'K' -l 'backup-converted' -d 'Back up the original version'
complete -c wget -s 'm' -l 'mirror' -d 'Turn on options suitable for mirroring'
complete -c wget -s 'p' -l 'page-requisites' -d 'Download all the files that are necessary to properly display a given HTML page'
complete -c wget -l 'strict-comments' -d 'Turn on strict parsing of HTML comments'
complete -c wget -s 'A' -l 'accept' -d 'Comma-separated lists of file name suffixes or patterns to accept'
complete -c wget -s 'R' -l 'reject' -d 'Comma-separated lists of file name suffixes or patterns to reject'
complete -c wget -s 'D' -l 'domains' -d 'Set domains to be followed'
complete -c wget -l 'exclude-domains' -d 'Specify the domains that are not to be followed'
complete -c wget -l 'follow-ftp' -d 'Follow FTP links from HTML documents'
complete -c wget -l 'follow-tags' -d 'HTML tags to follow'
complete -c wget -l 'ignore-tags' -d 'HTML tags to ignore'
complete -c wget -s 'H' -l 'span-hosts' -d 'Enable spanning across hosts'
complete -c wget -s 'L' -l 'relative' -d 'Follow relative links only'
complete -c wget -s 'I' -l 'include-directories' -d 'Specify a comma-separated list of directories you wish to follow'
complete -c wget -s 'X' -l 'exclude-directories' -d 'Specify a comma-separated list of directories you wish to exclude'
complete -c wget -l 'no-parent' -d 'Do not ever ascend to the parent directory'
complete -c wget -d 'Do not ever ascend to the parent directory'
