complete -c windscribe -l 'help'
complete -c windscribe -d 'Output current account details'
complete -c windscribe -d 'Connect to Windscribe'
complete -c windscribe -d 'Disconnect from VPN'
complete -c windscribe -d 'Show usage examples'
complete -c windscribe -d 'View/Modify Firewall mode'
complete -c windscribe -d 'View/Modify Firewall LAN bypass'
complete -c windscribe -d 'Output list of all available server locations'
complete -c windscribe -d 'Login to Windscribe account'
complete -c windscribe -d 'Logout and disconnect'
complete -c windscribe -d 'View/Modify default Port'
complete -c windscribe -d 'View/Modify default Protocol'
complete -c windscribe -d 'View/Modify Proxy Settings'
complete -c windscribe -d 'Send the debug log to Support'
complete -c windscribe -d 'Test the connection speed'
complete -c windscribe -d 'Check status of Windscribe and connection'
complete -c windscribe -d 'View the debug log'
