complete -c $command -s 'h' -l 'help' -d 'Show help'
complete -c $command -s 'V' -l 'version' -d 'Show version'
complete -c $command -l 'country' -d 'Specify the country code'
complete -c $command -l 'gui' -d 'Show gui diagnostics'
complete -c $command -l 'isolate' -d 'Use the separate bottles for applications'
complete -c $command -l 'self-update' -d 'Update to the latest version'
complete -c $command -l 'update-rollback' -d 'Rollback the latest self-update'
complete -c $command -s 'k' -l 'keep_isos' -d 'Cache ISOs'
complete -c $command -l 'no-clean' -d 'Don'"'"'t delete temporary directories'
complete -c $command -s 'q' -l 'unattended' -d 'Don'"'"'t show any prompts'
complete -c $command -s 't' -l 'torify' -d 'Run downloads through torify'
complete -c $command -l 'virefy' -d 'Test verbs automaitally'
complete -c $command -s 'v' -l 'verbose' -d 'Show commands'
