complete -c $command -d 'Turn echo off'
complete -c $command -d 'Manage command extensions'
complete -c $command -d 'Show help'
complete -c $command -s 'h' -d 'Show help'
complete -c $command -s 'a' -d 'Eject all the CD drives'
complete -c $command -s 'u' -d 'Unmount the CD drives'
complete -c $command -d 'Use the single pain view'
complete -c $command -d 'Use the default view'
complete -c $command -d 'Show help'
complete -c $command -d 'Show help'
complete -c $command -d 'Show help'
complete -c $command -s 'h' -d 'Show help'
complete -c $command -s 'v' -d 'Show version'
complete -c $command -l 'help' -d 'Show help'
complete -c $command -l 'version' -d 'Show version'
