complete -c wlr-randr -s 'h' -l 'help' -d 'Show help'
complete -c wlr-randr -l 'json' -d 'Print as JSON'
complete -c wlr-randr -l 'dryrun' -d 'Dry run'
complete -c wlr-randr -l 'output' -d 'Output'
complete -c wlr-randr -l 'on' -d 'Turn on'
complete -c wlr-randr -l 'off' -d 'Turn off'
complete -c wlr-randr -l 'mode' -d 'Mode'
complete -c wlr-randr -l 'pos' -d 'Position'
complete -c wlr-randr -l 'left-of' -d 'Relative left position'
complete -c wlr-randr -l 'right-of' -d 'Relative right position'
complete -c wlr-randr -l 'above' -d 'Relative top position'
complete -c wlr-randr -l 'below' -d 'Relative bottom position'
complete -c wlr-randr -l 'transform' -d 'Transformation'
complete -c wlr-randr -l 'scale' -d 'Scale'
