complete -c wpa_cli -d 'get current WPA/EAPOL/EAP status'
complete -c wpa_cli -d 'get MIB variables (dot1x, dot11)'
complete -c wpa_cli -d 'show this usage help'
complete -c wpa_cli -d 'show interfaces/select interface'
complete -c wpa_cli -d 'change debug level'
complete -c wpa_cli -d 'show full wpa_cli license'
complete -c wpa_cli -d 'IEEE 802.1X EAPOL state machine logoff'
complete -c wpa_cli -d 'IEEE 802.1X EAPOL state machine logon'
complete -c wpa_cli -d 'set/list variables'
complete -c wpa_cli -d 'show PMKSA cache'
complete -c wpa_cli -d 'force reassociation'
complete -c wpa_cli -d 'force wpa_supplicant to re-read its config file'
complete -c wpa_cli -d 'force preauthentication'
complete -c wpa_cli -d 'configure identity for an SSID'
complete -c wpa_cli -d 'configure password for an SSID'
complete -c wpa_cli -d 'change password for an SSID'
complete -c wpa_cli -d 'configure pin for an SSID'
complete -c wpa_cli -d 'configure one-time-password for an SSID'
complete -c wpa_cli -d 'configure private key passphrase for an SSID'
complete -c wpa_cli -d 'set preferred BSSID for an SSID'
complete -c wpa_cli -d 'list configured networks'
complete -c wpa_cli -d 'select a network (disable others)'
complete -c wpa_cli -d 'enable a network'
complete -c wpa_cli -d 'disable a network'
complete -c wpa_cli -d 'add a network'
complete -c wpa_cli -d 'remove a network'
complete -c wpa_cli -d 'set/list network variables'
complete -c wpa_cli -d 'get network variables'
complete -c wpa_cli -d 'save the current configuration'
complete -c wpa_cli -d 'disconnect and wait for reassociate command before connecting'
complete -c wpa_cli -d 'request new BSS scan'
complete -c wpa_cli -d 'get latest scan results'
complete -c wpa_cli -d 'get capabilies'
complete -c wpa_cli -d 'request STAKey negotiation with <addr>'
complete -c wpa_cli -d 'set ap_scan parameter'
complete -c wpa_cli -d 'request STK negotiation with <addr>'
complete -c wpa_cli -d 'terminate wpa_supplicant'
