complete -c wpctl -s 'h' -l 'help' -d 'Show help options'
complete -c wpctl -s 'k' -l 'nick' -d 'Display device and node nicknames instead of descriptions'
complete -c wpctl -s 'n' -l 'name' -d 'Display device and node names instead of descriptions'
complete -c wpctl -s 'r' -l 'referenced' -d 'Show objects that are referenced in properties'
complete -c wpctl -s 'a' -l 'associated' -d 'Show associated objects'
complete -c wpctl -s 'p' -l 'pid' -d 'Selects all nodes associated to the given PID'
complete -c wpctl -s 'l' -l 'limit' -d 'Limit volume to below this value'
complete -c wpctl -s 'p' -l 'pid' -d 'Selects all nodes associated to the given PID'
complete -c wpctl -d 'Default Microphone'
complete -c wpctl -d 'Default Speakers'
complete -c wpctl -d 'Default Camera'
