complete -c xbps-pkgdb -s 'a' -d 'Process all registered packages, regardless of its state.'
complete -c xbps-pkgdb -s 'C' -d 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-pkgdb -s 'd' -d 'Enables extra debugging shown to stderr.'
complete -c xbps-pkgdb -s 'h' -d 'Show the help message.'
complete -c xbps-pkgdb -s 'm' -d 'Set mode of PKGNAME'
complete -c xbps-pkgdb -s 'r' -d 'Specifies a full path for the target root directory.'
complete -c xbps-pkgdb -s 'u' -d 'Updates the pkgdb format to the latest version making the necessary conversions.'
complete -c xbps-pkgdb -s 'v' -d 'Enables verbose messages.'
complete -c xbps-pkgdb -s 'V' -d 'Show the version information.'
