complete -c xbps-remove -s 'C' -d 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-remove -s 'c' -d 'Specifies a path to the cache directory, where binary packages are stored.'
complete -c xbps-remove -s 'd' -d 'Enables extra debugging shown to stderr.'
complete -c xbps-remove -s 'F' -d 'Forcefully remove package even if there are reverse dependencies and/or broke…'
complete -c xbps-remove -s 'f' -d 'Forcefully remove package files even if they have been modified.'
complete -c xbps-remove -s 'h' -d 'Show the help message.'
complete -c xbps-remove -s 'O' -d 'Cleans cache directory removing obsolete binary packages.'
complete -c xbps-remove -s 'o' -d 'Remove orphaned packages that were installed as dependencies'
complete -c xbps-remove -s 'R' -d 'Recursively remove packages installed by PKG not by any other package'
complete -c xbps-remove -s 'r' -d 'Specifies a full path for the target root directory.'
complete -c xbps-remove -s 'v' -d 'Enables verbose messages.'
complete -c xbps-remove -s 'y' -d 'Assume yes to all questions and avoid interactive questions.'
complete -c xbps-remove -s 'V' -d 'Show the version information.'
