complete -c xbps-checkvers -s 'C' -d 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-checkvers -s 'D' -d 'Specifies a full path to the void-packages repository.'
complete -c xbps-checkvers -s 'd' -d 'Enables extra debugging shown to stderr.'
complete -c xbps-checkvers -s 'f' -d 'Format according to the string format, inspired by printf.'
complete -c xbps-checkvers -s 'h' -d 'Show the help message.'
complete -c xbps-checkvers -s 'i' -d 'Ignore repositories defined in configuration files.'
complete -c xbps-checkvers -s 'I' -d 'Check for outdated installed packages rather than in repositories.'
complete -c xbps-checkvers -s 'm' -d 'Only process listed files.'
complete -c xbps-checkvers -s 'R' -d 'Repository to be added to the top of the list.'
complete -c xbps-checkvers -s 'r' -d 'Specifies a full path for the target root directory.'
complete -c xbps-checkvers -s 's' -d 'List all packages found in the void-packages tree and prints available version.'
complete -c xbps-checkvers -s 'V' -d 'Show the version information.'
