complete -c xbps-rindex -s 'd' -d 'Enable extra debugging shown to stderr'
complete -c xbps-rindex -l 'compression' -d 'Set the repodata compression format (default: zstd)'
complete -c xbps-rindex -s 'C' -d 'Check not only for file existence but for the correct file hash while cleaning'
complete -c xbps-rindex -s 'f' -d 'Forcefully register package into the local repo (overwriting)'
complete -c xbps-rindex -s 'h' -d 'Show the help message'
complete -c xbps-rindex -s 'V' -d 'Show the version information'
complete -c xbps-rindex -l 'signedby' -d 'Name and email of person signing the repository'
complete -c xbps-rindex -l 'privkey' -d 'Path to the private RSA key to sign the repository. Defaults to ~/.ssh/id_rsa'
complete -c xbps-rindex -s 'a' -d 'Register the binary package into the local repository'
complete -c xbps-rindex -s 'c' -d 'Remove obsolete entries found in the local repository'
complete -c xbps-rindex -s 'r' -d 'Remove obsolete and currently unregistered packages from the local repository'
complete -c xbps-rindex -s 's' -d 'Initialize a signed repository with your specified RSA key'
complete -c xbps-rindex -s 'S' -d 'Sign a binary package archive with your specified RSA key'
