complete -c xbps-query -s 'C' -d 'Use this XBPS configuration directory'
complete -c xbps-query -s 'c' -d 'Use this cache directory to store binary packages'
complete -c xbps-query -s 'd' -d 'Enable extra debugging shown to stderr'
complete -c xbps-query -s 'h' -d 'Show the help message'
complete -c xbps-query -s 'i' -d 'Ignore repositories defined in configuration files'
complete -c xbps-query -s 'M' -d 'For remote repositories, the data is fetched and stored in memory only'
complete -c xbps-query -s 'p' -d 'Match one or more package properties'
complete -c xbps-query -s 'R' -d 'Enable repository mode'
complete -c xbps-query -l 'repository' -d 'Append the specified repository to the top of the list'
complete -c xbps-query -l 'regex' -d 'Use Extended Regular Expressions'
complete -c xbps-query -l 'fulldeptree' -d 'Print a full dependency tree in the show dependencies mode'
complete -c xbps-query -s 'r' -d 'Use this path for the target root directory'
complete -c xbps-query -s 'v' -d 'Enables verbose messages'
complete -c xbps-query -s 'V' -d 'Show the version information'
complete -c xbps-query -s 'l' -d 'List registered packages in the package database (pkgdb)'
complete -c xbps-query -s 'H' -d 'List registered packages in the package database (pkgdb) that are on hold'
complete -c xbps-query -s 'L' -d 'List repositories and the number of packages contained on them'
complete -c xbps-query -s 'm' -d 'List packages in the package database (pkgdb) that were installed manually'
complete -c xbps-query -s 'O' -d 'List package orphans in the package database (pkgdb)'
complete -c xbps-query -s 'o' -d 'Search for installed package files by matching PATTERN'
complete -c xbps-query -s 'S' -d 'Shows information of an installed package'
complete -c xbps-query -s 's' -d 'Search for packages by matching PATTERN on pkgver or short_desc'
complete -c xbps-query -s 'f' -d 'Show the package files for PKG'
complete -c xbps-query -s 'x' -d 'Show the required dependencies for PKG.  Only direct dependencies are shown'
complete -c xbps-query -s 'X' -d 'Show the reverse dependencies for PKG'
complete -c xbps-query -s 'X' -d 'Show the reverse dependencies for PKG'
complete -c xbps-query -l 'cat' -d 'Prints the file FILE stored in binary package PKG to stdout'
