complete -c xbps-create -s 'A' -d 'The target architecture for this package (required)'
complete -c xbps-create -s 'B' -d 'The package builder string, free form'
complete -c xbps-create -s 'C' -d 'Package patterns this package conflicts with, separated by whitespaces'
complete -c xbps-create -s 'D' -d 'Package patterns this package depends on, separated by whitespaces'
complete -c xbps-create -s 'F' -d 'Configuration files this package provides, separated by whitespace'
complete -c xbps-create -s 'G' -d 'Set git revisions of the sourcepkg used to build binary package'
complete -c xbps-create -s 'H' -d 'The package homepage string'
complete -c xbps-create -s 'h' -d 'Show the help message'
complete -c xbps-create -s 'l' -d 'The package license'
complete -c xbps-create -s 'M' -d 'A list of mutable files this package provides, separated by whitespaces'
complete -c xbps-create -s 'm' -d 'The package maintainer name and/or email contact'
complete -c xbps-create -s 'P' -d 'Virtual packages this package provides, separated by whitespace'
complete -c xbps-create -s 'p' -d 'Preserve package files after being updated'
complete -c xbps-create -s 'q' -d 'Enable quiet operation'
complete -c xbps-create -s 'R' -d 'Package patterns this package replaces, separated by whitespaces'
complete -c xbps-create -s 'r' -d 'Versions this package reverts, separated by whitespaces'
complete -c xbps-create -s 'S' -d 'A long description for this package'
complete -c xbps-create -s 's' -d 'A short description for this package, one line under 80 characters'
complete -c xbps-create -s 't' -d 'Tags (categories) for this package, separated by whitespace'
complete -c xbps-create -s 'V' -d 'Show the version information'
complete -c xbps-create -l 'build-options' -d 'A string containing the build options used in package'
complete -c xbps-create -l 'compression' -d 'Set the binary package compression format (default: zstd)'
complete -c xbps-create -l 'shlib-provides' -d 'Provided shared libraries, separated by whitespace'
complete -c xbps-create -l 'shlib-requires' -d 'Required shared libraries, separated by whitespace'
complete -c xbps-create -l 'alternatives' -d 'Alternatives provided by this package, separated by whitespace'
complete -c xbps-create -s 'c' -d 'The package changelog string'
