complete -c xbps-install -s 'A' -d 'Install as a dependency'
complete -c xbps-install -s 'C' -d 'Use this XBPS configuration directory.'
complete -c xbps-install -s 'c' -d 'Use this cache directory to store binary packages'
complete -c xbps-install -s 'd' -d 'Enable extra debugging shown to stderr'
complete -c xbps-install -s 'D' -d 'Only download packages to the cache'
complete -c xbps-install -s 'f' -d 'Force downgrade/reinstall package (pass twice to reinstall config files as well)'
complete -c xbps-install -s 'h' -d 'Show the help message'
complete -c xbps-install -s 'I' -d 'Ignore detected file conflicts in a transaction'
complete -c xbps-install -s 'i' -d 'Ignore repositories defined in configuration files'
complete -c xbps-install -s 'M' -d 'For remote repositories, the data is fetched and stored in memory'
complete -c xbps-install -s 'R' -d 'Enable repository mode'
complete -c xbps-install -l 'repository' -d 'Append the specified repository to the top of the list'
complete -c xbps-install -s 'r' -d 'Use this target root directory'
complete -c xbps-install -s 'S' -d 'Synchronize remote repository index files'
complete -c xbps-install -s 'u' -d 'Performs a full system upgrade (except for packages on hold)'
complete -c xbps-install -s 'v' -d 'Enables verbose messages'
complete -c xbps-install -s 'y' -d 'Assume yes to all questions and avoid interactive questions'
complete -c xbps-install -s 'V' -d 'Show the version information'
