complete -c xclip -s 'i' -d 'Read text into X selection from stdin'
complete -c xclip -s 'o' -d 'Prints the selection to stdout'
complete -c xclip -s 'l' -d 'Number of selection requests to wait for before exiting'
complete -c xclip -s 'd' -d 'X display to connect to'
complete -c xclip -s 'h' -d 'Usage information'
complete -c xclip -d 'Selection to access'
complete -c xclip -d 'Use the given target atom'
complete -c xclip -d 'Version information'
complete -c xclip -d 'Errors only, run in background (default)'
complete -c xclip -d 'Running commentary'
