complete -c xdg-mime -d 'Query information'
complete -c xdg-mime -d 'Query default application for type'
complete -c xdg-mime -d 'Choose application'
complete -c xdg-mime -d 'Mimetype'
complete -c xdg-mime -d 'Add filetype description'
complete -c xdg-mime -d 'Set mode' -l 'mode'
complete -c xdg-mime -d 'Disable vendor check' -l 'novendor'
complete -c xdg-mime -d 'Remove filetype description'
complete -c xdg-mime -d 'Set mode' -l 'mode'
complete -c xdg-mime -l 'help' -d 'Display help'
complete -c xdg-mime -l 'manual' -d 'Diplay long help'
complete -c xdg-mime -l 'version' -d 'Print version'
