complete -c xpdf -s 'g' -d 'Set the initial window geometry'
complete -c xpdf -d 'Set the window title'
complete -c xpdf -d 'Install a private colormap'
complete -c xpdf -d 'Set the size of the largest RGB cube xpdf will try to allocate'
complete -c xpdf -d 'Set reverse video mode'
complete -c xpdf -d 'Set the background of the page display'
complete -c xpdf -d 'Set the color for background outside the page area'
complete -c xpdf -s 'z' -d 'Set the initial zoom factor'
complete -c xpdf -d 'Start in continuous view mode'
complete -c xpdf -d 'Enable or disable t1lib (Default: yes)'
complete -c xpdf -d 'Enable or disable FreeType (Default: yes)'
complete -c xpdf -d 'Enable or disable font anti-aliasing (Default: yes)'
complete -c xpdf -d 'Set the default file name for PostScript output'
complete -c xpdf -d 'Set the paper size'
complete -c xpdf -d 'Set the paper width, in points'
complete -c xpdf -d 'Set the paper height, in points'
complete -c xpdf -d 'Generate Level 1 PostScript'
complete -c xpdf -d 'Sets the encoding to use for text output'
complete -c xpdf -d 'Sets the end-of-line convention to use'
complete -c xpdf -d 'Specify the owner password for the PDF file'
complete -c xpdf -d 'Specify the user password for the PDF file'
complete -c xpdf -d 'Open xpdf in full-screen mode'
complete -c xpdf -d 'Start/contact xpdf remote server'
complete -c xpdf -d 'Reload xpdf remote server window'
complete -c xpdf -d 'Raise xpdf remote server window'
complete -c xpdf -d 'Kill xpdf remote server'
complete -c xpdf -d 'Print commands as they'"'"'re executed'
complete -c xpdf -s 'q' -d 'Don'"'"'t print any messages or errors'
complete -c xpdf -d 'Specify config file to use instead of ~/.xpdfrc'
complete -c xpdf -s 'v' -d 'Print copyright and version information'
complete -c xpdf -s 'h' -d 'Print usage information'
