complete -c xprop -d 'Display help and exit'
complete -c xprop -d 'Display grammar and exit'
complete -c xprop -d 'Select window by id'
complete -c xprop -d 'Select window by name'
complete -c xprop -d 'Display font properties'
complete -c xprop -d 'Select root window'
complete -c xprop -d 'Specify X server'
complete -c xprop -d 'Maximum display length'
complete -c xprop -d 'Do not show property type'
complete -c xprop -d 'Set format file'
complete -c xprop -d 'Select a window by clicking on its frame'
complete -c xprop -d 'Remove property'
complete -c xprop -d 'Set property'
complete -c xprop -d 'Examine property updates forever'
complete -c xprop -d 'Set format'
complete -c xprop -d 'Property'
