complete -c xrdb -d 'display to use'
complete -c xrdb -d 'do all resources [default]'
complete -c xrdb -d 'do screen-independent resources'
complete -c xrdb -d 'do screen-specific resources for one screen'
complete -c xrdb -d 'do screen-specific resources for all screens'
complete -c xrdb -d 'preprocessor to use [/usr/bin/mcpp]'
complete -c xrdb -d 'do not use a preprocessor'
complete -c xrdb -d 'query resources'
complete -c xrdb -d 'load resources from file [default]'
complete -c xrdb -d 'add in resources from file'
complete -c xrdb -d 'merge resources from file & sort'
complete -c xrdb -d 'edit resources into file'
complete -c xrdb -d 'backup suffix for -edit [.bak]'
complete -c xrdb -d 'show preprocessor symbols'
complete -c xrdb -d 'remove resources'
complete -c xrdb -d 'avoid server reset (avoid using this)'
