complete -c xsp -l 'help' -d 'Show help'
complete -c xsp -l 'version' -d 'Show version'
complete -c xsp -l 'address' -d 'Use the IP address to listen on'
complete -c xsp -l 'port' -d 'Use the port where the XSP server will listen to requests'
complete -c xsp -l 'backlog' -d 'Use the backlog of connections to set on the listener socket'
complete -c xsp -l 'minThreads' -d 'Specify minimum number of threads the threadpool allocates'
complete -c xsp -l 'filename' -d 'Use unix socket file name to listen on'
complete -c xsp -l 'root' -d 'Use root directory for XSP'
complete -c xsp -l 'appconfigfile' -d 'Add application definitions from the XML configuration file'
complete -c xsp -l 'master' -d 'Use this instance by mod_mono to create ASP.NET applications on demand'
complete -c xsp -l 'no-hidden' -d 'Do not protect hidden files/directories from being accessed by clients'
complete -c xsp -l 'https' -d 'Enable HTTPS support on the server'
complete -c xsp -l 'https-client-accept' -d 'Like --https enable HTTPS support on the server'
complete -c xsp -l 'https-client-require' -d 'Like --https enable HTTPS support on the server'
complete -c xsp -l 'p12file' -d 'Use to specify the PKCS#12 file to use'
complete -c xsp -l 'cert' -d 'Use to specify the server X.509 certificate file'
complete -c xsp -l 'pkpwd' -d 'Use password to decode the private key'
complete -c xsp -l 'terminate' -d 'Gracefully terminates a running mod-mono-server instance'
complete -c xsp -l 'verbose' -d 'Show more messages'
complete -c xsp -l 'pidfile' -d 'Redirect xsp4 PID output in stdout to file'
