complete -c xsv -d 'Concatenate by row or column'
complete -c xsv -d 'Count records'
complete -c xsv -d 'Makes all records have same length'
complete -c xsv -d 'Show one field per line'
complete -c xsv -d 'Format CSV output (change field delimiter)'
complete -c xsv -d 'Show frequency tables'
complete -c xsv -d 'Show header names'
complete -c xsv -d 'Show this usage message.'
complete -c xsv -d 'Create CSV index for faster access'
complete -c xsv -d 'Read CSV data with special quoting rules'
complete -c xsv -d 'Join CSV files'
complete -c xsv -d 'Randomly sample CSV data'
complete -c xsv -d 'Search CSV data with regexes'
complete -c xsv -d 'Select columns from CSV'
complete -c xsv -d 'Slice records from CSV'
complete -c xsv -d 'Sort CSV data'
complete -c xsv -d 'Split CSV data into many files'
complete -c xsv -d 'Compute basic statistics'
complete -c xsv -d 'Align CSV data into columns'
complete -c xsv -s 'h' -l 'help' -d 'Display help for this xsv command'
complete -c xsv -s 'h' -l 'help' -d 'Display xsv help'
complete -c xsv -l 'version' -d 'Display xsv version info'
complete -c xsv -l 'list' -d 'List all xsv commands'
