complete -c xterm -d 'Never highlight the text cursor'
complete -c xterm -d 'Enable active icon support'
complete -c xterm -d 'Disallow auto wraparound'
complete -c xterm -d 'Turn off cursor blinking'
complete -c xterm -d 'Enable the display of bold characters'
complete -c xterm -d 'Enable recognition of ANSI color-change escape sequences'
complete -c xterm -d 'Cut newlines in line-mode selections'
complete -c xterm -d 'Disable dynamic color changing'
complete -c xterm -d 'Normal and bold fonts have VT100 line-drawing characters'
complete -c xterm -d 'Turn off logging'
complete -c xterm -d 'Turn off support for encodings according the locale setting'
complete -c xterm -d 'Allow write access to the terminal'
complete -c xterm -d 'Enable underlining'
complete -c xterm -d 'Disable PC style bold colors'
complete -c xterm -d 'Enable characters with reverse attribute as color'
complete -c xterm -d 'Disable reverse-wraparound'
complete -c xterm -d 'Turn off asynchronous scrolling'
complete -c xterm -d 'Send title/icon change requests always'
complete -c xterm -d 'Move the screen to the bottom on input'
complete -c xterm -d 'VT102 mode'
complete -c xterm -d 'Display characters with underline attribute as color'
complete -c xterm -d 'Write to the system utmp log file'
complete -c xterm -d 'Print version number to the standard output'
complete -c xterm -d 'Print out a verbose message describing the options'
complete -c xterm -d 'Always highlight the text cursor'
complete -c xterm -d 'Disable active icon support'
complete -c xterm -d 'Allow auto wraparound'
complete -c xterm -d 'Turn on cursor blinking'
complete -c xterm -d 'Disable the display of bold characters'
complete -c xterm -d 'Set character class'
complete -c xterm -d 'Disable recognition of ANSI color-change escape sequences'
complete -c xterm -d 'Workaround for bug in more(1)'
complete -c xterm -d 'Enable dynamic color changing'
complete -c xterm -d 'Ensure compatibility between normal and bold fonts bounding boxes'
complete -c xterm -d 'Generate HP Function Key escape codes for function keys'
complete -c xterm -d 'Force insert mode'
complete -c xterm -d 'Treat C1 control characters as printable'
complete -c xterm -d 'Turn on support for encodings according the locale setting'
complete -c xterm -d 'Force scrollbar to the left side'
complete -c xterm -d 'Ring bell if the user types near the end of line'
complete -c xterm -d 'Disallow write access to the terminal'
complete -c xterm -d 'Use builtin version for the wide-character calculation'
complete -c xterm -d 'Disable underlining'
complete -c xterm -d 'Enable PC style bold colors'
complete -c xterm -d 'Raise window on Control-G'
complete -c xterm -d 'Force scrollbar to the right side'
complete -c xterm -d 'Disable characters with reverse attribute as color'
complete -c xterm -d 'Enable reverse-wraparound'
complete -c xterm -d 'Display scrollbar'
complete -c xterm -d 'Generate Sun Function Key escape codes for function keys'
complete -c xterm -d 'Move the screen to the bottom on key press while scrolling'
complete -c xterm -d 'Setup session manager callbacks'
complete -c xterm -d 'Assume Sun/PC keyboard'
complete -c xterm -d 'Display toolbar or menubar'
complete -c xterm -d 'Use UTF-8'
complete -c xterm -d 'Use visual bell insead of audio bell'
complete -c xterm -d 'Use wide characters'
complete -c xterm -d 'Wait the first time for the window to be mapped'
complete -c xterm -d 'Use as input/output channel for an existing program'
complete -c xterm -s 'e' -d 'Run program in xterm'
complete -c xterm -d 'Blinking cursor will be off for that many milliseconds'
complete -c xterm -d 'Blinking cursor will be on for that many milliseconds'
complete -c xterm -d 'Override xterm resource class'
complete -c xterm -d 'Color for the text cursor'
complete -c xterm -d 'xterm encoding'
complete -c xterm -d 'Bold font'
complete -c xterm -d 'FreeType font pattern'
complete -c xterm -d 'FreeType double-width font pattern'
complete -c xterm -d 'Font for active icons'
complete -c xterm -d 'Font size for FreeType font'
complete -c xterm -d 'Font for displaying wide text'
complete -c xterm -d 'Font for displaying bold wide text'
complete -c xterm -d 'Font for the preedit string in "OverTheSpot"'
complete -c xterm -d 'Color for highlighted text'
complete -c xterm -d 'Embed xterm into window'
complete -c xterm -d 'Set keyboard type'
complete -c xterm -d 'File name for the encoding converter'
complete -c xterm -d 'Log filename'
complete -c xterm -d 'Maximum time in milliseconds between multi-click selections'
complete -c xterm -d 'Color for the pointer cursor'
complete -c xterm -d 'Distance from the right end for ringing the margin bell'
complete -c xterm -d 'Number of scrolled off lines'
complete -c xterm -d 'Terminal identification'
complete -c xterm -d 'Terminal name for $TERM'
complete -c xterm -d 'zIconBeep percentage'
complete -c xterm -s 'b' -d 'Size of the inner border'
complete -c xterm -s 'j' -d 'Use jump scrolling'
complete -c xterm -s 'l' -d 'Turn on logging'
complete -c xterm -s 's' -d 'Turn on asynchronous scrolling'
complete -c xterm -s 't' -d 'Tektronix mode'
complete -c xterm -s 'C' -d 'This window should receive console output'
