complete -c yadm -l 'yadm-dir' -s 'Y' -d 'Override the yadm directory'
complete -c yadm -l 'yadm-repo' -d 'Override location of yadm repository'
complete -c yadm -l 'yadm-config' -d 'Override location of yadm configuration file'
complete -c yadm -l 'yadm-encrypt' -d 'Override location of yadm encryption configuration'
complete -c yadm -l 'yadm-archive' -d 'Override location of yadm encrypted files archive'
complete -c yadm -l 'yadm-bootstrap' -d 'Override location of yadm bootstrap program'
complete -c yadm -d 'Print yadm version'
complete -c yadm -d 'Initialize new repository for tracking dotfiles'
complete -c yadm -d 'Manage configuration for yadm'
complete -c yadm -d 'Print list of files managed by yadm'
complete -c yadm -d 'Execute bootstrap script'
complete -c yadm -d 'Encrypt files matched by encrypt spec file'
complete -c yadm -d 'Decrypt files matched by encrypt spec file'
complete -c yadm -d 'Setup and process alternate files'
complete -c yadm -d 'Update permissions'
complete -c yadm -d 'Run sub-shell with all git variables set'
complete -c yadm -d 'Pass options to git-crypt if installed'
complete -c yadm -d 'Pass options to the git config command'
complete -c yadm -d 'Migrate from v1 to v2'
complete -c yadm -d 'Report internal yadm data'
complete -c yadm -d 'Clone remote repository for tracking dotfiles'
complete -c yadm -s 'f' -d 'Overwrite existing repository'
complete -c yadm -s 'w' -d 'Override work-tree'
complete -c yadm -s 'f' -d 'Overwrite existing repository'
complete -c yadm -s 'w' -d 'Override work-tree'
complete -c yadm -s 'b' -d 'Use another branch'
complete -c yadm -l 'bootstrap' -d 'Force run the bootstrap script'
complete -c yadm -l 'no-bootstrap' -d 'Do not execute bootstrap script'
complete -c yadm -s 'a' -d 'List all files'
complete -c yadm -s 'l' -d 'List files without extracting'
complete -c yadm -l 'get' -d 'Get config with name'
complete -c yadm -l 'get-all' -d 'Get all values matching key'
complete -c yadm -l 'replace-all' -d 'Replace all matching variables'
complete -c yadm -l 'unset' -d 'Remove a variable'
complete -c yadm -l 'unset-all' -d 'Remove matching variables'
