complete -c yaourt -d 'Modify the package database'
complete -c yaourt -d 'Query the package database'
complete -c yaourt -d 'Manage .pac* files'
complete -c yaourt -s 'D' -l 'database' -d 'Modify the package database'
complete -c yaourt -s 'Q' -l 'query' -d 'Query the package database'
complete -c yaourt -s 'R' -l 'remove' -d 'Remove packages from the system'
complete -c yaourt -s 'S' -l 'sync' -d 'Synchronize packages'
complete -c yaourt -s 'T' -l 'deptest' -d 'Check dependencies'
complete -c yaourt -s 'U' -l 'upgrade' -d 'Upgrade or add a local package'
complete -c yaourt -s 'F' -l 'files' -d 'Query the files database'
complete -c yaourt -s 'V' -l 'version' -d 'Display version and exit'
complete -c yaourt -s 'h' -l 'help' -d 'Display help'
complete -c yaourt -s 'B' -l 'backup' -d 'Backup or restore alpm local database'
complete -c yaourt -s 'C' -d 'Manage .pac* files'
complete -c yaourt -s 'G' -l 'getpkgbuild' -d 'Get PKGBUILD from ABS or AUR'
complete -c yaourt -s 'P' -l 'pkgbuild' -d 'Build package from PKGBUILD found in a local directory'
complete -c yaourt -l 'stats' -d 'Show some statistics about your packages'
complete -c yaourt -s 'b' -l 'dbpath' -d 'Alternative database location'
complete -c yaourt -s 'r' -l 'root' -d 'Alternative installation root'
complete -c yaourt -s 'v' -l 'verbose' -d 'Output more status messages'
complete -c yaourt -l 'arch' -d 'Alternate architecture'
complete -c yaourt -l 'cachedir' -d 'Alternative package cache location'
complete -c yaourt -l 'config' -d 'Alternate config file'
complete -c yaourt -l 'debug' -d 'Display debug messages'
complete -c yaourt -l 'gpgdir' -d 'GPG directory to verify signatures'
complete -c yaourt -l 'hookdir' -d 'Hook file directory'
complete -c yaourt -l 'logfile' -d 'Specify alternative log file'
complete -c yaourt -l 'noconfirm' -d 'Bypass any question'
complete -c yaourt -l 'color' -d 'Force color'
complete -c yaourt -l 'force' -d 'Force installation or updates'
complete -c yaourt -l 'insecure' -d 'Allow to perform "insecure" SSL connections'
complete -c yaourt -l 'nocolor' -d 'Disable color'
complete -c yaourt -l 'confirm' -d 'Always ask for confirmation'
complete -c yaourt -l 'pager' -d 'Use $PAGER to show search results'
complete -c yaourt -l 'export' -d 'Export built packages and their sources to DIR'
complete -c yaourt -l 'tmp' -d 'Use DIR as temporary folder'
complete -c yaourt -s 'c' -l 'changelog' -d 'View the change log of PACKAGE'
complete -c yaourt -s 'd' -l 'deps' -d 'List only non-explicit packages (dependencies)'
complete -c yaourt -s 'e' -l 'explicit' -d 'List only explicitly installed packages'
complete -c yaourt -s 'k' -l 'check' -d 'Check if all files owned by PACKAGE are present'
complete -c yaourt -s 'l' -l 'list' -d 'List all files owned by PACKAGE'
complete -c yaourt -s 'm' -l 'foreign' -d 'List all packages not in the database'
complete -c yaourt -s 'o' -l 'owns' -d 'Search for the package that owns FILE'
complete -c yaourt -s 'p' -l 'file' -d 'Apply the query to a package file, not package'
complete -c yaourt -s 't' -l 'unrequired' -d 'List only unrequired packages'
complete -c yaourt -s 'u' -l 'upgrades' -d 'List only out-of-date packages'
complete -c yaourt -d 'Installed package'
complete -c yaourt -l 'backupfile' -d 'Query FILE instead of alpm/aur'
complete -c yaourt -l 'date' -d 'List queries result sorted by installation date'
complete -c yaourt -s 'c' -l 'cascade' -d 'Also remove packages depending on PACKAGE'
complete -c yaourt -s 'n' -l 'nosave' -d 'Ignore file backup designations'
complete -c yaourt -s 's' -l 'recursive' -d 'Also remove dependencies of PACKAGE'
complete -c yaourt -s 'u' -l 'unneeded' -d 'Only remove targets not required by PACKAGE'
complete -c yaourt -d 'Installed package'
complete -c yaourt -s 'c' -l 'clean' -d 'Remove [all] packages from cache'
complete -c yaourt -s 'l' -l 'list' -d 'List all packages in REPOSITORY'
complete -c yaourt -s 'u' -l 'sysupgrade' -d 'Upgrade all packages that are out of date'
complete -c yaourt -s 'u' -l 'sysupgrade' -d 'Also downgrade packages'
complete -c yaourt -s 'w' -l 'downloadonly' -d 'Only download the target packages'
complete -c yaourt -s 'y' -l 'refresh' -d 'Download fresh copy of the package list'
complete -c yaourt -s 'a' -l 'aur' -d 'Also search in AUR database'
complete -c yaourt -s 'A' -l 'ignorearch' -d 'Pass -A or --ignorearch option to makepkg'
complete -c yaourt -l 'aur-url' -d 'Specify a custom AUR url'
complete -c yaourt -s 'b' -l 'build' -d 'Build from sources(AUR or ABS)'
complete -c yaourt -s 'b' -l 'build' -d 'Also build all dependencies'
complete -c yaourt -l 'devel' -d 'Search an update for devel packages'
complete -c yaourt -l 'maintainer' -d 'Search packages by maintainer instead of name (AUR only)'
complete -c yaourt -l 'm-arg' -d 'Pass additional options to makepkg'
complete -c yaourt -d 'Mark PACKAGE as dependency'
complete -c yaourt -d 'Mark PACKAGE as explicitly installed'
complete -c yaourt -s 'k' -l 'check' -d 'Check database validity'
complete -c yaourt -d 'List files owned by given packages'
complete -c yaourt -l '-d'
complete -c yaourt -d 'Search packages for matching files'
complete -c yaourt -s '-d'
complete -c yaourt -s 'y' -l 'refresh' -d 'Refresh the files database'
complete -c yaourt -s 'l' -l 'list' -d 'List files owned by given packages'
complete -c yaourt -s 's' -l 'search' -d 'Search packages for matching files'
complete -c yaourt -s 'o' -l 'owns' -d 'Search for packages that include the given files'
complete -c yaourt -s 'q' -l 'quiet' -d 'Show less information'
complete -c yaourt -l 'machinereadable' -d 'Show in machine readable format'
complete -c yaourt -d 'Package file'
complete -c yaourt -d 'Clean all these files'
complete -c yaourt -s 'i' -l 'install' -d 'Also install the package'
