complete -c yast2 -d 'Module'
complete -c yast2 -s 'h' -l 'help' -d 'Show help'
complete -c yast2 -s 'l' -l 'list' -d 'List all available modules'
complete -c yast2 -l 'qt' -d 'Use the QT graphical user interface'
complete -c yast2 -l 'gtk' -d 'Use the GTK graphical user interface'
complete -c yast2 -l 'ncurses' -d 'Use the NCURSES text-mode user interface'
complete -c yast2 -s 'g' -l 'geometry' -d 'Default window size (qt only)'
complete -c yast2 -l 'noborder' -d 'No window manager border for main window'
complete -c yast2 -l 'fullscreen' -d 'Use full screen'
