complete -c yum -d 'Install the latest version of a package'
complete -c yum -d 'Update specified packages (defaults to all packages)'
complete -c yum -d 'Print list of available updates'
complete -c yum -d 'Remove the specified packages and packages that depend on them'
complete -c yum -d 'List available packages'
complete -c yum -d 'Describe available packages'
complete -c yum -d 'Find package providing a feature or file'
complete -c yum -d 'find packages matching description regexp'
complete -c yum -d 'Clean up cache directory'
complete -c yum -d 'Generate rss changelog'
complete -c yum -s 'h' -l 'help' -d 'Display help and exit'
complete -c yum -s 'y' -d 'Assume yes to all questions'
complete -c yum -s 'c' -d 'Configuration file'
complete -c yum -s 'd' -d 'Set debug level'
complete -c yum -s 'e' -d 'Set error level'
complete -c yum -s 't' -l 'tolerant' -d 'Be tolerant of errors in commandline'
complete -c yum -s 'R' -d 'Set maximum delay between commands'
complete -c yum -s 'c' -d 'Run commands from cache'
complete -c yum -l 'version' -d 'Display version and exit'
complete -c yum -l 'installroot' -d 'Specify installroot'
complete -c yum -l 'enablerepo' -d 'Enable repository'
complete -c yum -l 'disablerepo' -d 'Disable repository'
complete -c yum -l 'obsoletes' -d 'Enables obsolets processing logic'
complete -c yum -l 'rss-filename' -d 'Output rss-data to file'
complete -c yum -l 'exclude' -d 'Exclude specified package from updates'
complete -c yum -d 'List all packages'
complete -c yum -d 'List packages available for installation'
complete -c yum -d 'List packages with updates available'
complete -c yum -d 'List installed packages'
complete -c yum -d 'List packages not available in repositories'
complete -c yum -d 'List packages that are obsoleted by packages in repositories'
complete -c yum -d 'Delete cached package files'
complete -c yum -d 'Delete cached header files'
complete -c yum -d 'Delete all cache contents'
