complete -c zabbix_agentd -s 'c' -l 'config' -d 'Specify an alternate config-file.'
complete -c zabbix_agentd -s 'f' -l 'foreground' -d 'Run Zabbix agent in foreground.'
complete -c zabbix_agentd -s 'R' -l 'runtime-control' -d 'Perform administrative functions.'
complete -c zabbix_agentd -s 'p' -l 'print' -d 'Print known items and exit.'
complete -c zabbix_agentd -s 't' -l 'test' -d 'Test single item and exit.'
complete -c zabbix_agentd -s 'h' -l 'help' -d 'Display this help and exit.'
complete -c zabbix_agentd -s 'V' -l 'version' -d 'Output version information and exit.'
complete -c zabbix_agentd -s 'R' -l 'runtime-control'
complete -c zabbix_agentd -s 'R' -l 'runtime-control'
