complete -c zabbix_server -s 'c' -l 'config' -d 'Path to the configuration file.'
complete -c zabbix_server -s 'f' -l 'foreground' -d 'Run Zabbix server in foreground.'
complete -c zabbix_server -s 'h' -l 'help' -d 'Display this help message.'
complete -c zabbix_server -s 'V' -l 'version' -d 'Display version number.'
complete -c zabbix_server -s 'R' -l 'runtime-control' -d 'Perform administrative functions.'
complete -c zabbix_server -s 'R' -l 'runtime-control'
complete -c zabbix_server -s 'R' -l 'runtime-control'
complete -c zabbix_server -s 'R' -l 'runtime-control'
complete -c zabbix_server -s 'R' -l 'runtime-control'
complete -c zabbix_server -s 'R' -l 'runtime-control'
complete -c zabbix_server -s 'R' -l 'runtime-control'
