complete -c zef -s 'h' -l 'help' -d 'Display help text'
complete -c zef -l 'version' -d 'Detailed version information'
complete -c zef -l 'config-path' -d 'Load a specific Zef config file'
complete -c zef -l 'error' -d 'Verbosity level'
complete -c zef -l 'warn' -d 'Verbosity level'
complete -c zef -l 'info' -d 'Verbosity level (default)'
complete -c zef -s 'v' -l 'verbose' -d 'Verbosity level'
complete -c zef -l 'debug' -d 'Verbosity level'
complete -c zef -d 'Install specific distributions by name or path'
complete -c zef -d 'Uninstall specific distributions'
complete -c zef -d 'Download a single module and change into its directory'
complete -c zef -d 'Update package indexes for repositories'
complete -c zef -d 'Upgrade specific distributions (or all if no arguments)'
complete -c zef -d 'Show a list of possible distribution candidates for the given terms'
complete -c zef -d 'Show detailed distribution information'
complete -c zef -d 'Browse support urls (bugtracker etc)'
complete -c zef -d 'List available distributions'
complete -c zef -d 'List full dependencies for a given identity'
complete -c zef -d 'List all distributions directly depending on a given identity'
complete -c zef -d 'Lookup installed module information by short-name, name-path, sha1'
complete -c zef -d 'Run smoke testing on available modules'
complete -c zef -d 'Delete directory/prefix containing matching configuration path or CURLI name'
complete -c zef -l 'fetch'
complete -c zef -l 'build'
complete -c zef -l '/build' -d 'Skip the building phase'
complete -c zef -l 'test'
complete -c zef -l '/test' -d 'Skip the testing phase'
complete -c zef -l 'depends'
complete -c zef -l '/depends' -d 'Do not fetch runtime dependencies'
complete -c zef -l 'build-depends'
complete -c zef -l '/build-depends' -d 'Do not fetch build dependencies'
complete -c zef -l 'test-depends'
complete -c zef -l '/test-depends' -d 'Do not fetch test dependencies'
complete -c zef -l 'force' -d 'Ignore errors'
complete -c zef -l 'force-resolve' -d 'Ignore errors'
complete -c zef -l 'force-fetch' -d 'Ignore errors'
complete -c zef -l 'force-extract' -d 'Ignore errors'
complete -c zef -l 'force-build' -d 'Ignore errors'
complete -c zef -l 'force-test' -d 'Ignore errors'
complete -c zef -l 'force-install' -d 'Ignore errors'
complete -c zef -l 'timeout' -d 'Set a timeout (in seconds)'
complete -c zef -l 'fetch-timeout' -d 'Set a timeout (in seconds)'
complete -c zef -l 'extract-timeout' -d 'Set a timeout (in seconds)'
complete -c zef -l 'build-timeout' -d 'Set a timeout (in seconds)'
complete -c zef -l 'test-timeout' -d 'Set a timeout (in seconds)'
complete -c zef -l 'install-timeout' -d 'Set a timeout (in seconds)'
complete -c zef -l 'degree' -d 'Number of simultaneous jobs to process'
complete -c zef -l 'fetch-degree' -d 'Number of simultaneous jobs to process'
complete -c zef -l 'test-degree' -d 'Number of simultaneous jobs to process'
complete -c zef -l 'dry' -d 'Run all phases except the actual installations'
complete -c zef -l 'serial' -d 'Install each dependency after passing testing and before building/testing the next dependency'
complete -c zef -l 'update' -d 'Force a refresh for all module indexes or a specific ecosystem'
complete -c zef -l '/update' -d 'Skip refreshing all module indexes or a specific ecosystem'
complete -c zef -l 'exclude'
complete -c zef -l 'to' -d 'Short name or spec of CompUnit::Repository to install to'
complete -c zef -l 'install-to' -d 'Short name or spec of CompUnit::Repository to install to'
complete -c zef -l 'upgrade'
complete -c zef -l 'deps-only' -d 'Install only the dependency chains of the requested distributions'
complete -c zef -l 'contained' -d 'Install dependencies regardless if they are already installed globally'
complete -c zef -l 'from'
complete -c zef -l 'uninstall-from'
complete -c zef -l 'wrap'
complete -c zef -l 'open'
complete -c zef -l '/open'
complete -c zef -l 'max'
complete -c zef -s 'i' -l 'installed'
complete -c zef -l 'sha1'
complete -c zef -l 'confirm'
