complete -c zfs -s '?' -d 'Display a help message'
complete -c zfs -d 'Create a volume or filesystem'
complete -c zfs -d 'Destroy a dataset'
complete -c zfs -d 'Create a snapshot'
complete -c zfs -d 'Roll back a filesystem to a previous snapshot'
complete -c zfs -d 'Create a clone of a snapshot'
complete -c zfs -d 'Promotes a clone file system to no longer be dependent on its "origin" snapshot'
complete -c zfs -d 'Rename a dataset'
complete -c zfs -d 'List dataset properties'
complete -c zfs -d 'Set a dataset property'
complete -c zfs -d 'Get one or several dataset properties'
complete -c zfs -d 'Set a dataset property to be inherited'
complete -c zfs -d 'List upgradeable datasets, or upgrade one'
complete -c zfs -d 'Get dataset space consumed by each user'
complete -c zfs -d 'Get dataset space consumed by each user group'
complete -c zfs -d 'Mount a filesystem'
complete -c zfs -d 'Unmount a filesystem'
complete -c zfs -d 'Share a given filesystem, or all of them'
complete -c zfs -d 'Stop sharing a given filesystem, or all of them'
complete -c zfs -d 'Output a stream representation of a dataset'
complete -c zfs -d 'Write on disk a dataset from the stream representation given on standard input'
complete -c zfs -d 'Delegate, or display delegations of, rights on a dataset to (groups of) users'
complete -c zfs -d 'Revoke delegations of rights on a dataset from (groups of) users'
complete -c zfs -d 'Put a named hold on a snapshot'
complete -c zfs -d 'List holds on a snapshot'
complete -c zfs -d 'Remove a named hold from a snapshot'
complete -c zfs -d 'List changed files between a snapshot, and a filesystem or a previous snapshot'
complete -c zfs -s 'p' -d 'Create all needed non-existing parent datasets'
complete -c zfs -s 'o' -d 'Dataset property'
complete -c zfs -s 'V' -d 'Volume size'
complete -c zfs -s 's' -d 'Create a sparse volume'
complete -c zfs -s 'b' -d 'Blocksize'
complete -c zfs -s 'r' -d 'Recursively destroy children'
complete -c zfs -s 'R' -d 'Recursively destroy all dependents'
complete -c zfs -s 'f' -d 'Force unmounting'
complete -c zfs -s 'n' -d 'Dry run'
complete -c zfs -s 'p' -d 'Print machine-parsable verbose information'
complete -c zfs -s 'v' -d 'Verbose mode'
complete -c zfs -s 'd' -d 'Defer snapshot deletion'
complete -c zfs -d 'Dataset to destroy'
complete -c zfs -s 'r' -d 'Recursively snapshot children'
complete -c zfs -s 'o' -d 'Snapshot property'
complete -c zfs -d 'Dataset to snapshot'
complete -c zfs -s 'r' -d 'Destroy later snapshot and bookmarks'
complete -c zfs -s 'R' -d 'Recursively destroy later snapshot, bookmarks and clones'
complete -c zfs -s 'f' -d 'Force unmounting of clones'
complete -c zfs -d 'Snapshot to roll back to'
complete -c zfs -s 'p' -d 'Create all needed non-existing parent datasets'
complete -c zfs -s 'o' -d 'Clone property'
complete -c zfs -d 'Snapshot to clone'
complete -c zfs -d 'Clone to promote'
complete -c zfs -s 'p' -d 'Create all needed non-existing parent datasets'
complete -c zfs -s 'r' -d 'Recursively rename children snapshots'
complete -c zfs -d 'Dataset to rename'
complete -c zfs -s 'H' -d 'Print output in a machine-parsable format'
complete -c zfs -s 'r' -d 'Operate recursively on datasets'
complete -c zfs -s 'd' -d 'Maximum recursion depth'
complete -c zfs -s 'o' -d 'Property to list'
complete -c zfs -s 'p' -d 'Print parsable (exact) values for numbers'
complete -c zfs -s 's' -d 'Property to use for sorting output by ascending order'
complete -c zfs -s 'S' -d 'Property to use for sorting output by descending order'
complete -c zfs -s 't' -d 'Dataset type'
complete -c zfs -d 'Dataset whose properties to list'
complete -c zfs -d 'Property to set'
complete -c zfs -d 'Dataset whose property to set'
complete -c zfs -s 'r' -d 'Operate recursively on datasets'
complete -c zfs -s 'd' -d 'Maximum recursion depth'
complete -c zfs -s 'H' -d 'Print output in a machine-parsable format'
complete -c zfs -s 'o' -d 'Fields to display'
complete -c zfs -s 's' -d 'Property source to display'
complete -c zfs -s 'p' -d 'Print parsable (exact) values for numbers'
complete -c zfs -s 't' -d 'Dataset type'
complete -c zfs -d 'Property to get'
complete -c zfs -d 'Dataset whose property to get'
complete -c zfs -s 'r' -d 'Operate recursively on datasets'
complete -c zfs -s 'S' -d 'Revert to the received value if available'
complete -c zfs -d 'Dataset whose properties are to be inherited'
complete -c zfs -s 'v' -d 'Verbose mode'
complete -c zfs -s 'a' -d 'Upgrade all eligible filesystems'
complete -c zfs -s 'r' -d 'Operate recursively on datasets'
complete -c zfs -s 'V' -d 'Upgrade to the specified version'
complete -c zfs -d 'Filesystem to upgrade'
complete -c zfs -s 'n' -d 'Print UID instead of user name'
complete -c zfs -s 'n' -d 'Print GID instead of group name'
complete -c zfs -s 'H' -d 'Print output in a machine-parsable format'
complete -c zfs -s 'p' -d 'Print parsable (exact) values for numbers'
complete -c zfs -s 'o' -d 'Field to display'
complete -c zfs -s 's' -d 'Property to use for sorting output by ascending order'
complete -c zfs -s 'S' -d 'Property to use for sorting output by descending order'
complete -c zfs -s 't' -d 'Identity types to display'
complete -c zfs -s 't' -d 'Identity types to display'
complete -c zfs -s 'i' -d 'Translate S(amba)ID to POSIX ID'
complete -c zfs -d 'Dataset whose space usage to get'
complete -c zfs -s 'o' -d 'Temporary mount point property'
complete -c zfs -s 'v' -d 'Report progress'
complete -c zfs -s 'a' -d 'Mount all available ZFS filesystems'
complete -c zfs -d 'Filesystem to mount'
complete -c zfs -s 'f' -d 'Force unmounting if needed'
complete -c zfs -s 'a' -d 'Unmount all available ZFS filesystems'
complete -c zfs -d 'Filesystem to unmount'
complete -c zfs -s 'a' -d 'Share all eligible ZFS filesystems'
complete -c zfs -d 'Filesystem to share'
complete -c zfs -s 'a' -d 'Unshare all shared ZFS filesystems'
complete -c zfs -d 'Filesystem to unshare'
complete -c zfs -s 'i' -d 'Generate incremental stream from snapshot'
complete -c zfs -s 'I' -d 'Generate incremental stream from snapshot, even with intermediary snapshots'
complete -c zfs -d 'Dataset to send'
complete -c zfs -s 'v' -d 'Print verbose information about the stream and the time spent processing it'
complete -c zfs -s 'n' -d 'Dry run: do not actually receive the stream'
complete -c zfs -s 'F' -d 'Force rollback to the most recent snapshot'
complete -c zfs -s 'u' -d 'Unmount the target filesystem'
complete -c zfs -s 'd' -d 'Discard the first element of the path of the sent snapshot'
complete -c zfs -s 'e' -d 'Discard all but the last element of the path of the sent snapshot'
complete -c zfs -d 'Dataset to receive'
complete -c zfs -s 'l' -d 'Delegate permissions only on the specified dataset'
complete -c zfs -s 'd' -d 'Delegate permissions only on the descendents dataset'
complete -c zfs -s 'u' -d 'User to delegate permissions to'
complete -c zfs -s 'g' -d 'Group to delegate permissions to'
complete -c zfs -s 'e' -d 'Delegate permission to everyone'
complete -c zfs -s 'c' -d 'Delegate permissions only to the creator of later descendent datasets'
complete -c zfs -s 's' -d 'Create a permission set or add permissions to an existing one'
complete -c zfs -d 'Dataset on which delegation is to be applied'
complete -c zfs -s 'l' -d 'Remove permissions only on the specified dataset'
complete -c zfs -s 'd' -d 'Remove permissions only on the descendents dataset'
complete -c zfs -s 'u' -d 'User to remove permissions from'
complete -c zfs -s 'g' -d 'Group to remove permissions from'
complete -c zfs -s 'e' -d 'Remove permission from everyone'
complete -c zfs -s 'c' -d 'Remove permissions only on later created descendent datasets'
complete -c zfs -s 's' -d 'Remove a permission set or remove permissions from an existing one'
complete -c zfs -d 'Dataset on which delegation is to be removed'
complete -c zfs -s 'r' -d 'Apply hold recursively'
complete -c zfs -d 'Snapshot on which hold is to be applied'
complete -c zfs -s 'r' -d 'List holds recursively'
complete -c zfs -d 'Snapshot whose holds are to be listed'
complete -c zfs -s 'r' -d 'Release hold recursively'
complete -c zfs -d 'Snapshot from which hold is to be removed'
complete -c zfs -s 'F' -d 'Display file type (à la ls -F)'
complete -c zfs -s 'H' -d 'Print output in a machine-parsable format'
complete -c zfs -s 't' -d 'Display inode change time'
complete -c zfs -d 'Source snapshot for the diff'
