complete -c zpaq -d 'add'
complete -c zpaq -d 'Append files to archive if dates have changed'
complete -c zpaq -d 'extract'
complete -c zpaq -d 'Extract most recent versions of files'
complete -c zpaq -d 'list'
complete -c zpaq -d 'List or compare external files to archive'
complete -c zpaq -d 'Extract/list versions in N [4] digit directories'
complete -c zpaq -s 'f' -d '-force'
complete -c zpaq -d 'Append files if contents have changed'
complete -c zpaq -d 'Compare file contents instead of dates'
complete -c zpaq -d 'Overwrite existing output files'
complete -c zpaq -d 'Set the dedupe fragment size (64 2^N to 8128 2^N bytes)'
complete -c zpaq -d 'Create suffix for archive indexed by F, update F'
complete -c zpaq -d 'Create index F for archive'
complete -c zpaq -d 'Create or access encrypted archive with password X'
complete -c zpaq -d '-method N'
complete -c zpaq -d 'Compress level N (0..5 = faster..better, default 1)'
complete -c zpaq -d 'Ignore/don'"'"'t save file attributes or permissions'
complete -c zpaq -d 'Exclude. * and ? match any string or char'
complete -c zpaq -d 'Exclude. =[+-#^?] exclude by comparison result'
complete -c zpaq -d 'Include only matches (default: *)'
complete -c zpaq -d 'Extract to new archive F with key [X] (default: none)'
complete -c zpaq -d '-summary N'
complete -c zpaq -d 'If N > 0 show brief progress'
complete -c zpaq -d 'Show top N sorted by size. -1: show frag IDs'
complete -c zpaq -d 'Verify but do not write files'
complete -c zpaq -d '-threads N'
complete -c zpaq -d 'Use N threads (default: 0 = all cores)'
complete -c zpaq -d 'Rename files... to P... or all to P/all'
complete -c zpaq -d 'Roll back archive to N'"'"'th update or -N from end'
complete -c zpaq -d 'Set date D, roll back (UT, default time: 235959)'
