complete -c zpool -s '?' -d 'Display a help message'
complete -c zpool -d 'Add new virtual devices to pool'
complete -c zpool -d 'Attach virtual device to a pool device'
complete -c zpool -d 'Clear devices errors in pool'
complete -c zpool -d 'Create a new storage pool'
complete -c zpool -d 'Destroy a storage pool'
complete -c zpool -d 'Detach virtual device from a mirroring pool'
complete -c zpool -d 'Export a pool'
complete -c zpool -d 'Get one or several pool properties'
complete -c zpool -d 'Display pool command history'
complete -c zpool -d 'List importable pools, or import some'
complete -c zpool -d 'Display pool I/O stats'
complete -c zpool -d 'Remove ZFS label information from the specified device'
complete -c zpool -d 'List pools with health status and space usage'
complete -c zpool -d 'Take the specified devices offline'
complete -c zpool -d 'Bring the specified devices back online'
complete -c zpool -d 'Reset pool GUID'
complete -c zpool -d 'Remove virtual devices from pool'
complete -c zpool -d 'Reopen pool devices'
complete -c zpool -d 'Replace a pool virtual device'
complete -c zpool -d 'Start or stop scrubbing'
complete -c zpool -d 'Set a pool property'
complete -c zpool -d 'Create a pool by splitting an existing mirror one'
complete -c zpool -d 'Display detailed pool health status'
complete -c zpool -d 'List upgradeable pools, or upgrade one'
complete -c zpool -s 'f' -d 'Force use of virtual device'
complete -c zpool -s 'n' -d 'Dry run: only display resulting configuration'
complete -c zpool -d 'Pool to add virtual device(s) to'
complete -c zpool -s 'f' -d 'Force use of virtual device'
complete -c zpool -d 'Pool to attach virtual device to'
complete -c zpool -d 'Existing pool device to attach to'
complete -c zpool -d 'Pool to clear errors on'
complete -c zpool -d 'Virtual device to operate on'
complete -c zpool -s 'n' -d 'Dry run, only display resulting configuration'
complete -c zpool -s 'd' -d 'Do not enable any feature on the new pool'
complete -c zpool -s 'o' -d 'Pool property'
complete -c zpool -s 'O' -d 'Root filesystem property'
complete -c zpool -s 'R' -d 'Equivalent to "-o cachefile=none,altroot=ROOT"'
complete -c zpool -s 'm' -d 'Root filesystem mountpoint'
complete -c zpool -d 'Virtual device to add'
complete -c zpool -s 'f' -d 'Force unmounting of all contained datasets'
complete -c zpool -d 'Pool to destroy'
complete -c zpool -d 'Pool to detach device from'
complete -c zpool -d 'Physical device to detach'
complete -c zpool -s 'f' -d 'Force unmounting of all contained datasets'
complete -c zpool -d 'Pool to export'
complete -c zpool -s 'p' -d 'Print parsable (exact) values for numbers'
complete -c zpool -s 'H' -d 'Print output in a machine-parsable format'
complete -c zpool -d 'Properties to get'
complete -c zpool -d 'Pool to get properties of'
complete -c zpool -s 'i' -d 'Also display internal events'
complete -c zpool -s 'l' -d 'Display log records using long format'
complete -c zpool -d 'Pool to get command history of'
complete -c zpool -s 'c' -d 'Read configuration from specified cache file'
complete -c zpool -s 'd' -d 'Search for devices or files in specified directory'
complete -c zpool -s 'D' -d 'List or import destroyed pools only (requires -f for importation)'
complete -c zpool -s 'o' -d 'Mount properties for contained datasets'
complete -c zpool -s 'o' -d 'Properties of the imported pool'
complete -c zpool -s 'f' -d 'Force import'
complete -c zpool -s 'F' -d 'Recovery mode'
complete -c zpool -s 'a' -d 'Search for and import all pools found'
complete -c zpool -s 'm' -d 'Ignore missing log device (risk of loss of last changes)'
complete -c zpool -s 'R' -d 'Equivalent to "-o cachefile=none,altroot=ROOT"'
complete -c zpool -s 'N' -d 'Do not mount contained filesystems'
complete -c zpool -s 'n' -d 'Dry run: only determine if the recovery is possible, without attempting it'
complete -c zpool -d 'Pool to import'
complete -c zpool -s 'T' -d 'Display a timestamp using specified format'
complete -c zpool -s 'v' -d 'Print verbose statistics'
complete -c zpool -d 'Pool to retrieve I/O stats from'
complete -c zpool -s 'f' -d 'Treat exported or foreign devices as inactive'
complete -c zpool -d 'Device to clear ZFS label information from'
complete -c zpool -s 'H' -d 'Print output in a machine-parsable format'
complete -c zpool -s 'P' -d 'Display device full path'
complete -c zpool -s 'T' -d 'Display a timestamp using specified format'
complete -c zpool -s 'v' -d 'Print verbose statistics'
complete -c zpool -s 'o' -d 'Property to list'
complete -c zpool -d 'Pool to list properties of'
complete -c zpool -s 't' -d 'Temporarily offline'
complete -c zpool -d 'Pool to offline device from'
complete -c zpool -d 'Physical device to offline'
complete -c zpool -s 'e' -d 'Expand the device to use all available space'
complete -c zpool -d 'Pool to bring device back online on'
complete -c zpool -d 'Physical device to bring back online'
complete -c zpool -d 'Pool which GUID is to be changed'
complete -c zpool -d 'Pool to remove device from'
complete -c zpool -d 'Physical device to remove'
complete -c zpool -d 'Pool which devices are to be reopened'
complete -c zpool -s 'f' -d 'Force use of virtual device'
complete -c zpool -d 'Pool to replace device'
complete -c zpool -d 'Pool device to be replaced'
complete -c zpool -d 'Device to use for replacement'
complete -c zpool -s 's' -d 'Stop scrubbing'
complete -c zpool -d 'Pool to start/stop scrubbing'
complete -c zpool -d 'Property to set'
complete -c zpool -d 'Pool which property is to be set'
complete -c zpool -s 'n' -d 'Dry run: only display resulting configuration'
complete -c zpool -s 'R' -d 'Set altroot for newpool and automatically import it'
complete -c zpool -s 'o' -d 'Pool property'
complete -c zpool -d 'Pool to split'
complete -c zpool -s 'v' -d 'Verbose mode'
complete -c zpool -s 'x' -d 'Only display status for unhealthy or unavailable pools'
complete -c zpool -s 'T' -d 'Display a timestamp using specified format'
complete -c zpool -d 'Pool which status is to be displayed'
complete -c zpool -s 'a' -d 'Upgrade all eligible pools, enabling all supported features'
complete -c zpool -s 'v' -d 'Display upgradeable ZFS versions'
complete -c zpool -s 'V' -d 'Upgrade to the specified legacy version'
complete -c zpool -d 'Pool which status is to be displayed'
