complete -c zypper -d 'Package'
complete -c zypper -d 'Repo'
complete -c zypper -d 'Print help'
complete -c zypper -d 'Accept multiple commands at once'
complete -c zypper -d 'List all defined repositories'
complete -c zypper -d 'Add a new repository'
complete -c zypper -d 'Remove specified repository'
complete -c zypper -d 'Rename specified repository'
complete -c zypper -d 'Modify specified repository'
complete -c zypper -d 'Refresh all repositories'
complete -c zypper -d 'Clean local caches'
complete -c zypper -d 'List all defined services'
complete -c zypper -d 'Add a new service'
complete -c zypper -d 'Modify specified service'
complete -c zypper -d 'Remove specified service'
complete -c zypper -d 'Refresh all services'
complete -c zypper -d 'Install packages'
complete -c zypper -d 'Remove packages'
complete -c zypper -d 'Verify integrity of package dependencies'
complete -c zypper -d 'Install source packages and their build dependencies'
complete -c zypper -d 'Install newly added packages recommended by installed packages'
complete -c zypper -d 'Update installed packages with newer versions'
complete -c zypper -d 'List available updates'
complete -c zypper -d 'Install needed patches'
complete -c zypper -d 'List needed patches'
complete -c zypper -d 'Perform a distribution upgrade'
complete -c zypper -d 'Check for patches'
complete -c zypper -d 'Search for packages matching a pattern'
complete -c zypper -d 'Show full information for specified packages'
complete -c zypper -d 'Show full information for specified patches'
complete -c zypper -d 'Show full information for specified patterns'
complete -c zypper -d 'Show full information for specified products'
complete -c zypper -d 'List all available patches'
complete -c zypper -d 'List all available packages'
complete -c zypper -d 'List all available patterns'
complete -c zypper -d 'List all available products'
complete -c zypper -d 'List packages providing specified capability'
complete -c zypper -d 'Add a package lock'
complete -c zypper -d 'Remove a package lock'
complete -c zypper -d 'List current package locks'
complete -c zypper -d 'Remove unused locks'
complete -c zypper -d 'List requested locales (languages codes)'
complete -c zypper -d 'Add locale(s) to requested locales'
complete -c zypper -d 'Remove locale(s) from requested locales'
complete -c zypper -d 'Compare two version strings'
complete -c zypper -d 'Print the target operating system ID string'
complete -c zypper -d 'Print report about licenses and EULAs of installed packages'
complete -c zypper -d 'Download rpms specified on the commandline to a local directory'
complete -c zypper -d 'Download source rpms for all installed packages to a local directory'
complete -c zypper -d 'Check if the needs-reboot flag was set'
complete -c zypper -d 'List running processes still using deleted files'
complete -c zypper -d 'Lists available subcommands'
complete -c zypper -l 'help' -s 'h' -d 'Help'
complete -c zypper -l 'version' -s 'V' -d 'Output the version number'
complete -c zypper -l 'promptids' -d 'Output a list of zypper user prompts'
complete -c zypper -l 'config' -s 'c' -d 'Use specified config file instead of the default'
complete -c zypper -l 'userdata' -d 'User defined transaction id used in history and plugins'
complete -c zypper -l 'quiet' -s 'q' -d 'Suppress normal output, print only error messages'
complete -c zypper -l 'verbose' -s 'v' -d 'Increase verbosity'
complete -c zypper -l 'no-abbrev' -s 'A' -d 'Do not abbreviate text in tables'
complete -c zypper -l 'table-style' -s 's' -d 'Table style (integer)'
complete -c zypper -l 'rug-compatible' -s 'r' -d 'Turn on rug compatibility'
complete -c zypper -l 'non-interactive' -s 'n' -d 'Do not ask anything, use default answers automatically'
complete -c zypper -l 'non-interactive-include-reboot-patches' -d 'Do not treat patches as interactive, which have the rebootSuggested-flag set'
complete -c zypper -l 'xmlout' -s 'x' -d 'Switch to XML output'
complete -c zypper -l 'ignore-unknown' -s 'i' -d 'Ignore unknown packages'
complete -c zypper -l 'terse' -s 't' -d 'Terse output for machine consumption. Implies --no-abbrev and --no-color'
complete -c zypper -l 'reposd-dir' -s 'D' -d 'Use alternative repository definition file directory'
complete -c zypper -l 'cache-dir' -s 'C' -d 'Use alternative directory for all caches'
complete -c zypper -l 'raw-cache-dir' -d 'Use alternative raw meta-data cache directory'
complete -c zypper -l 'solv-cache-dir' -d 'Use alternative solv file cache directory'
complete -c zypper -l 'pkg-cache-dir' -d 'Use alternative package cache directory'
complete -c zypper -l 'no-gpg-checks' -d 'Ignore GPG check failures and continue'
complete -c zypper -l 'gpg-auto-import-keys' -d 'Automatically trust and import new repository signing keys'
complete -c zypper -l 'plus-repo' -s 'p' -d 'Use an additional repository'
complete -c zypper -l 'plus-content' -s 'p' -d 'Additionally use disabled repositories providing a specific keyword'
complete -c zypper -l 'disable-repositories' -d 'Do not read meta-data from repositories'
complete -c zypper -l 'no-refresh' -d 'Do not refresh the repositories'
complete -c zypper -l 'no-cd' -d 'Ignore CD/DVD repositories'
complete -c zypper -l 'no-remote' -d 'Ignore remote repositories'
complete -c zypper -l 'releasever' -d 'Set the value of $releasever in all .repo files'
complete -c zypper -l 'root' -s 'R' -d 'Operate on a different root directory'
complete -c zypper -l 'installroot' -d 'Operate on a different root directory, but share repositories with the host'
complete -c zypper -l 'disable-system-resolvables' -d 'Do not read installed packages'
complete -c zypper -l 'export' -s 'e' -d 'Export all defined repositories as a single local .repo file'
complete -c zypper -l 'alias' -s 'a' -d 'Show also repository alias'
complete -c zypper -l 'name' -s 'n' -d 'Show also repository name'
complete -c zypper -l 'refresh' -s 'r' -d 'Show also the autorefresh flag'
complete -c zypper -l 'uri' -s 'u' -d 'Show also base URI of repositories'
complete -c zypper -l 'priority' -s 'p' -d 'Show also repository priority'
complete -c zypper -l 'details' -s 'd' -d 'Show more information like URI, priority, type'
complete -c zypper -l 'service' -s 's' -d 'Show also alias of parent service'
complete -c zypper -l 'show-enabled-only' -s 'E' -d 'Show enabled repos only'
complete -c zypper -l 'sort-by-uri' -s 'U' -d 'Sort the list by URI'
complete -c zypper -l 'sort-by-name' -s 'N' -d 'Sort the list by name'
complete -c zypper -l 'sort-by-priority' -s 'P' -d 'Sort the list by repository priority'
complete -c zypper -l 'sort-by-alias' -s 'A' -d 'Sort the list by alias'
complete -c zypper -l 'repo' -s 'r' -d 'Just another means to specify a .repo file to read'
complete -c zypper -l 'check' -s 'c' -d 'Probe URI'
complete -c zypper -l 'no-check' -s 'C' -d 'Don'"'"'t probe URI, probe later during refresh'
complete -c zypper -l 'priority' -s 'p' -d 'Set the priority of the repository'
complete -c zypper -l 'keep-packages' -s 'k' -d 'Enable RPM files caching'
complete -c zypper -l 'no-keep-packages' -s 'K' -d 'Disable RPM files caching'
complete -c zypper -l 'gpgcheck' -s 'g' -d 'Enable GPG check for this repository'
complete -c zypper -l 'gpgcheck-strict' -d 'Enable strict GPG check for this repository'
complete -c zypper -l 'gpgcheck-allow-unsigned' -d 'Short hand for --gpgcheck-allow-unsigned-repo --gpgcheck-allow-unsigned-package'
complete -c zypper -l 'gpgcheck-allow-unsigned-repo' -d 'Enable GPG check but allow the repository metadata to be unsigned'
complete -c zypper -l 'gpgcheck-allow-unsigned-package' -d 'Enable GPG check but allow installing unsigned packages from this repository.'
complete -c zypper -l 'no-gpgcheck' -s 'G' -d 'Disable GPG check for this repository'
complete -c zypper -l 'default-gpgcheck' -d 'Use the global GPG check setting defined in /etc/zypp/zypp.conf'
complete -c zypper -l 'name' -s 'n' -d 'Specify descriptive name for the repository'
complete -c zypper -l 'enable' -s 'd' -d 'Add the repository as enabled'
complete -c zypper -l 'disable' -s 'd' -d 'Add the repository as disabled'
complete -c zypper -l 'refresh' -s 'f' -d 'Enable autorefresh of the repository'
complete -c zypper -l 'no-refresh' -s 'F' -d 'Disable autorefresh of the repository'
complete -c zypper -l 'loose-auth' -d 'Ignore user authentication data in the URI'
complete -c zypper -l 'loose-query' -d 'Ignore query string in the URI'
complete -c zypper -l 'all' -s 'a' -d 'Apply changes to all repositories'
complete -c zypper -l 'local' -s 'l' -d 'Apply changes to all local repositories'
complete -c zypper -l 'remote' -s 't' -d 'Apply changes to all remote repositories'
complete -c zypper -l 'medium-type' -s 'm' -d 'Apply changes to repositories of specified type'
complete -c zypper -l 'name' -s 'n' -d 'Set a descriptive name for the repository'
complete -c zypper -l 'disable' -s 'd' -d 'Disable the repository'
complete -c zypper -l 'enable' -s 'e' -d 'Enable the repository'
complete -c zypper -l 'refresh' -s 'f' -d 'Enable auto-refresh of the repository'
complete -c zypper -l 'no-refresh' -s 'F' -d 'Disable auto-refresh of the repository'
complete -c zypper -l 'priority' -s 'p' -d 'Set the priority of the repository'
complete -c zypper -l 'keep-packages' -s 'k' -d 'Enable RPM files caching'
complete -c zypper -l 'no-keep-packages' -s 'K' -d 'Disable RPM files caching'
complete -c zypper -l 'gpgcheck' -s 'g' -d 'Enable GPG check for this repository'
complete -c zypper -l 'gpgcheck-strict' -d 'Enable strict GPG check for this repository'
complete -c zypper -l 'gpgcheck-allow-unsigned' -d 'Short hand for --gpgcheck-allow-unsigned-repo --gpgcheck-allow-unsigned-package'
complete -c zypper -l 'gpgcheck-allow-unsigned-repo' -d 'Enable GPG check but allow the repository metadata to be unsigned'
complete -c zypper -l 'gpgcheck-allow-unsigned-package' -d 'Enable GPG check but allow installing unsigned packages from this repository.'
complete -c zypper -l 'no-gpgcheck' -s 'G' -d 'Disable GPG check for this repository'
complete -c zypper -l 'default-gpgcheck' -d 'Use the global GPG check setting defined in /etc/zypp/zypp.conf'
complete -c zypper -l 'all' -s 'a' -d 'Apply changes to all repositories'
complete -c zypper -l 'local' -s 'l' -d 'Apply changes to all local repositories'
complete -c zypper -l 'remote' -s 't' -d 'Apply changes to all remote repositories'
complete -c zypper -l 'medium-type' -s 'm' -d 'Apply changes to repositories of specified type'
complete -c zypper -l 'force' -s 'f' -d 'Force a complete refresh'
complete -c zypper -l 'force-build' -s 'b' -d 'Force rebuild of the database'
complete -c zypper -l 'force-download' -s 'd' -d 'Force download of raw metadata'
complete -c zypper -l 'build-only' -s 'B' -d 'Only build the database, don'"'"'t download metadata'
complete -c zypper -l 'download-only' -s 'D' -d 'Only download raw metadata, don'"'"'t build the database'
complete -c zypper -l 'repo' -s 'r' -d 'Refresh only specified repositories'
complete -c zypper -l 'services' -s 's' -d 'Refresh also services before refreshing repos'
complete -c zypper -l 'uri' -s 'u' -d 'Show also base URI of repositories'
complete -c zypper -l 'priority' -s 'p' -d 'Show also repository priority'
complete -c zypper -l 'details' -s 'd' -d 'Show more information like URI, priority, type'
complete -c zypper -l 'with-repos' -s 'r' -d 'Show also repositories belonging to the services'
complete -c zypper -l 'show-enabled-only' -s 'E' -d 'Show enabled repos only'
complete -c zypper -l 'sort-by-priority' -s 'P' -d 'Sort the list by repository priority'
complete -c zypper -l 'sort-by-uri' -s 'U' -d 'Sort the list by URI'
complete -c zypper -l 'sort-by-name' -s 'N' -d 'Sort the list by name'
complete -c zypper -l 'name' -s 'n' -d 'Set a descriptive name for the service'
complete -c zypper -l 'enable' -s 'd' -d 'Add the service as enabled'
complete -c zypper -l 'disable' -s 'd' -d 'Add the service as disabled'
complete -c zypper -l 'refresh' -s 'f' -d 'Enable autorefresh of the repository'
complete -c zypper -l 'no-refresh' -s 'F' -d 'Disable autorefresh of the repository'
complete -c zypper -l 'name' -s 'n' -d 'Set a descriptive name for the service'
complete -c zypper -l 'enable' -s 'e' -d 'Enable a disabled service'
complete -c zypper -l 'disable' -s 'd' -d 'Disable the service (but don'"'"'t remove it)'
complete -c zypper -l 'refresh' -s 'r' -d 'Enable auto-refresh of the service'
complete -c zypper -l 'no-refresh' -s 'R' -d 'Disable auto-refresh of the service'
complete -c zypper -l 'all' -s 'a' -d 'Apply changes to all services'
complete -c zypper -l 'local' -s 'l' -d 'Apply changes to all local services'
complete -c zypper -l 'remote' -s 't' -d 'Apply changes to all remote services'
complete -c zypper -l 'medium-type' -s 'm' -d 'Apply changes to services of specified type'
complete -c zypper -l 'ar-to-enable' -s 'i' -d 'Add a RIS service repository to enable'
complete -c zypper -l 'ar-to-disable' -s 'I' -d 'Add a RIS service repository to disable'
complete -c zypper -l 'rr-to-enable' -s 'j' -d 'Remove a RIS service repository to enable'
complete -c zypper -l 'rr-to-disable' -s 'J' -d 'Remove a RIS service repository to disable'
complete -c zypper -l 'cl-to-enable' -s 'k' -d 'Clear the list of RIS repositories to enable'
complete -c zypper -l 'cl-to-disable' -s 'K' -d 'Clear the list of RIS repositories to disable'
complete -c zypper -l 'loose-auth' -d 'Ignore user authentication data in the URI'
complete -c zypper -l 'loose-query' -d 'Ignore query string in the URI'
complete -c zypper -l 'force' -s 'f' -d 'Force a complete refresh'
complete -c zypper -l 'with-repos' -s 'r' -d 'Refresh also repositories'
complete -c zypper -l 'restore-status' -s 'R' -d 'Also restore service repositories enabled/disabled state'
complete -c zypper -l 'debug-solver' -d 'Create solver test case for debugging'
complete -c zypper -l 'force-resolution' -d 'Force the solver to find a solution (even an aggressive one)'
complete -c zypper -l 'no-force-resolution' -s 'R' -d 'Do not force the solver to find solution, let it ask'
complete -c zypper -l 'solver-focus' -d 'Create solver test case for debugging'
complete -c zypper -l 'recommends' -d 'Install also recommended packages in addition to the required'
complete -c zypper -l 'no-recommends' -d 'Do not install recommended packages, only required'
complete -c zypper -l 'allow-downgrade' -l 'no-allow-downgrade' -d 'Whether to allow downgrading installed resolvables'
complete -c zypper -l 'allow-name-change' -l 'no-allow-name-change' -d 'Whether to allow changing the names of installed resolvables'
complete -c zypper -l 'allow-arch-change' -l 'no-allow-arch-change' -d 'Whether to allow changing the architecture of installed resolvables'
complete -c zypper -l 'allow-vendor-change' -l 'no-allow-vendor-change' -d 'Whether to allow changing the vendor of installed resolvables'
complete -c zypper -l 'type' -s 't' -d 'Type of package'
complete -c zypper -l 'name' -s 'n' -d 'Select packages by plain name, not by capability'
complete -c zypper -l 'capability' -s 'C' -d 'Select packages by capability'
complete -c zypper -l 'details' -d 'Show the detailed installation summary'
complete -c zypper -l 'from' -d 'Select packages from the specified repository'
complete -c zypper -l 'oldpackage' -d 'Allow to replace a newer item with an older one.'
complete -c zypper -l 'allow-unsigned-rpm' -d 'Silently install unsigned rpm packages given as commandline parameters'
complete -c zypper -l 'force' -s 'f' -d 'Install even if the item is installed, downgraded or changes vendor/architecture'
complete -c zypper -l 'repo' -s 'r' -d 'Load only the specified repository'
complete -c zypper -l 'dry-run' -s 'D' -d 'Test the installation, do not actually install'
complete -c zypper -l 'replacefiles' -d 'Install even if it replaces files from other installed packages'
complete -c zypper -l 'auto-agree-with-licenses' -s 'l' -d 'Automatically say '"'"'yes'"'"' to third party license confirmation prompt'
complete -c zypper -l 'download' -d 'Set the download-install mode'
complete -c zypper -l 'download-only' -s 'd' -d 'Only download the packages, do not install'
complete -c zypper -l 'type' -s 't' -d 'Type of package'
complete -c zypper -l 'name' -s 'n' -d 'Select packages by plain name, not by capability'
complete -c zypper -l 'capability' -s 'C' -d 'Select packages by capability'
complete -c zypper -l 'details' -d 'Show the detailed installation summary'
complete -c zypper -l 'repo' -s 'r' -d 'Load only the specified repository'
complete -c zypper -l 'dry-run' -s 'D' -d 'Test the removal, do not actually remove'
complete -c zypper -l 'clean-deps' -s 'u' -d 'Automatically remove unneeded dependencies'
complete -c zypper -l 'no-clean-deps' -s 'U' -d 'No automatic removal of unneeded dependencies'
complete -c zypper -l 'debug-solver' -d 'Create solver test case for debugging'
complete -c zypper -l 'force-resolution' -d 'Force the solver to find a solution (even an aggressive one)'
complete -c zypper -l 'no-force-resolution' -s 'R' -d 'Do not force the solver to find solution, let it ask'
complete -c zypper -l 'solver-focus' -d 'Create solver test case for debugging'
complete -c zypper -l 'details' -d 'Show the detailed installation summary'
complete -c zypper -l 'dry-run' -s 'D' -d 'Test the repair, do not actually do anything to the system'
complete -c zypper -l 'download' -d 'Set the download-install mode'
complete -c zypper -l 'download-only' -s 'd' -d 'Only download the packages, do not install'
complete -c zypper -l 'repo' -s 'r' -d 'Load only the specified repository'
complete -c zypper -l 'build-deps-only' -s 'd' -d 'Install only build dependencies of specified packages'
complete -c zypper -l 'no-build-deps' -s 'D' -d 'Don'"'"'t install build dependencies'
complete -c zypper -l 'repo' -s 'r' -d 'Install packages only from specified repositories'
complete -c zypper -l 'download' -d 'Set the download-install mode'
complete -c zypper -l 'download-only' -s 'd' -d 'Only download the packages, do not install'
complete -c zypper -l 'details' -d 'Show the detailed installation summary'
complete -c zypper -l 'dry-run' -s 'D' -d 'Test the installation, do not actually install'
complete -c zypper -l 'download' -d 'Set the download-install mode'
complete -c zypper -l 'download-only' -s 'd' -d 'Only download the packages, do not install'
complete -c zypper -l 'repo' -s 'r' -d 'Load only the specified repositories'
complete -c zypper -l 'type' -s 't' -d 'Type of package'
complete -c zypper -l 'details' -d 'Show the detailed installation summary'
complete -c zypper -l 'best-effort' -d 'Accept updates to a lower than the latest version'
complete -c zypper -l 'replacefiles' -d 'Install even if it replaces files from other installed packages'
complete -c zypper -l 'repo' -s 'r' -d 'Load only the specified repository'
complete -c zypper -l 'with-interactive' -d 'Do not skip interactive updates'
complete -c zypper -l 'skip-interactive' -d 'Skip interactive updates'
complete -c zypper -l 'auto-agree-with-licenses' -s 'l' -d 'Automatically say '"'"'yes'"'"' to third party license confirmation prompt'
complete -c zypper -l 'dry-run' -s 'D' -d 'Test the update, do not actually update'
complete -c zypper -l 'download' -d 'Set the download-install mode'
complete -c zypper -l 'download-only' -s 'd' -d 'Only download the packages, do not install'
complete -c zypper -l 'type' -s 't' -d 'Type of package'
complete -c zypper -l 'best-effort' -d 'Accept updates to a lower than the latest version'
complete -c zypper -l 'all' -s 'a' -d 'List all packages with newer versions, even uninstalled'
complete -c zypper -l 'repo' -s 'r' -d 'List only updates from the specified repository'
complete -c zypper -l 'allow-downgrade' -l 'no-allow-downgrade' -d 'Whether to allow downgrading installed resolvables'
complete -c zypper -l 'allow-name-change' -l 'no-allow-name-change' -d 'Whether to allow changing the names of installed resolvables'
complete -c zypper -l 'allow-arch-change' -l 'no-allow-arch-change' -d 'Whether to allow changing the architecture of installed resolvables'
complete -c zypper -l 'allow-vendor-change' -l 'no-allow-vendor-change' -d 'Whether to allow changing the vendor of installed resolvables'
complete -c zypper -l 'all' -s 'a' -d 'List all patches, not only the needed ones'
complete -c zypper -l 'repo' -s 'r' -d 'List only patches from the specified repository'
complete -c zypper -l 'category' -s 'g' -d 'Select patches with the specified category'
complete -c zypper -l 'severity' -d 'Select patches with the specified severity'
complete -c zypper -l 'date' -d 'Select patches issued up to, but not including, the specified date'
complete -c zypper -l 'bugzilla' -s 'b' -d 'Select applicable patches for the specified Bugzilla issues'
complete -c zypper -l 'cve' -d 'Select applicable patches for the specified CVE issues'
complete -c zypper -l 'issues' -d 'Select issues matching the specified string'
complete -c zypper -l 'with-optional' -l 'without-optional' -d 'Whether applicable optional patches should be treated as needed or be excluded'
complete -c zypper -l 'from' -d 'Restrict upgrade to specified repository'
complete -c zypper -l 'details' -d 'Show the detailed installation summary'
complete -c zypper -l 'replacefiles' -d 'Install even if it replaces files from other installed packages'
complete -c zypper -l 'repo' -s 'r' -d 'Load only the specified repository'
complete -c zypper -l 'auto-agree-with-licenses' -s 'l' -d 'Automatically say '"'"'yes'"'"' to third party license confirmation prompt'
complete -c zypper -l 'dry-run' -s 'D' -d 'Test the upgrade, do not actually upgrade'
complete -c zypper -l 'download' -d 'Set the download-install mode'
complete -c zypper -l 'download-only' -s 'd' -d 'Only download the packages, do not install'
complete -c zypper -l 'updatestack-only' -d 'Consider only patches which affect the package management itself'
complete -c zypper -l 'repo' -s 'r' -d 'Check for patches only in the specified repository'
complete -c zypper -l 'with-optional' -l 'without-optional' -d 'Whether applicable optional patches should be treated as needed or be excluded'
complete -c zypper -l 'match-substrings' -d 'Search for a match to partial words (default)'
complete -c zypper -l 'match-words' -d 'Search for a match to whole words only'
complete -c zypper -l 'match-exact' -s 'x' -d 'Searches for an exact package name'
complete -c zypper -l 'provides' -d 'Search for packages which provide the search strings'
complete -c zypper -l 'requires' -d 'Search for packages which require the search strings'
complete -c zypper -l 'recommends' -d 'Search for packages which recommend the search strings'
complete -c zypper -l 'supplements' -d 'Search for packages which supplements the search strings'
complete -c zypper -l 'conflicts' -d 'Search packages conflicting with search strings'
complete -c zypper -l 'obsoletes' -d 'Search for packages which obsolete the search strings'
complete -c zypper -l 'suggests' -d 'Search for packages which suggest the search strings'
complete -c zypper -l 'type' -s 't' -d 'Search only for packages of the specified type'
complete -c zypper -l 'name' -s 'n' -d 'Search package name even with dependency options'
complete -c zypper -l 'file-list' -s 'f' -d 'Search for a match in the file list of packages'
complete -c zypper -l 'search-descriptions' -s 'd' -d 'Search also in package summaries and descriptions'
complete -c zypper -l 'case-sensitive' -s 'C' -d 'Perform case-sensitive search'
complete -c zypper -l 'details' -s 's' -d 'Show each available version in each repository on a separate line'
complete -c zypper -l 'verbose' -s 's' -d 'Like --details, with additional info (useful for search in dependencies)'
complete -c zypper -l 'sort-by-name' -d 'Sort packages by name (default)'
complete -c zypper -l 'sort-by-repo' -d 'Sort packages by repository'
complete -c zypper -l 'repo' -s 'r' -d 'Search only in the specified repository'
complete -c zypper -l 'installed-only' -s 'i' -d 'Show only packages that are already installed'
complete -c zypper -l 'not-installed-only' -s 'u' -d 'Show only packages that are not currently installed'
complete -c zypper -l 'match-substrings' -s 's' -d 'Print information for packages partially matching name'
complete -c zypper -l 'type' -s 't' -d 'Type of package'
complete -c zypper -l 'provides' -d 'Show provides'
complete -c zypper -l 'requires' -d 'Show requires and prerequires'
complete -c zypper -l 'conflicts' -d 'Show conflicts'
complete -c zypper -l 'obsoletes' -d 'Show obsoletes'
complete -c zypper -l 'recommends' -d 'Show recommends'
complete -c zypper -l 'supplements' -d 'Show supplements'
complete -c zypper -l 'suggests' -d 'Show suggests'
complete -c zypper -l 'repo' -s 'r' -d 'Work only with the specified repository'
complete -c zypper -l 'repo' -s 'r' -d 'Just another means to specify repository'
complete -c zypper -l 'orphaned' -d 'Show packages which are orphaned (without repository)'
complete -c zypper -l 'suggested' -d 'Show packages which are suggested'
complete -c zypper -l 'recommended' -d 'Show packages which are recommended'
complete -c zypper -l 'unneeded' -d 'Show packages which are unneeded'
complete -c zypper -l 'sort-by-name' -s 'N' -d 'Sort the list by package name'
complete -c zypper -l 'sort-by-repo' -s 'R' -d 'Sort the list by repository'
complete -c zypper -l 'repo' -s 'r' -d 'Just another means to specify repository'
complete -c zypper -l 'installed-only' -s 'i' -d 'Show only installed packages'
complete -c zypper -l 'not-installed-only' -s 'u' -d 'Show only packages which are not installed'
complete -c zypper -l 'repo' -s 'r' -d 'Just another means to specify repository'
complete -c zypper -l 'installed-only' -s 'i' -d 'Show only installed patterns'
complete -c zypper -l 'not-installed-only' -s 'u' -d 'Show only patterns which are not installed'
complete -c zypper -l 'xmlfwd' -d 'XML output only: Literally forward the XML tags found in a product file'
complete -c zypper -l 'repo' -s 'r' -d 'Just another means to specify repository'
complete -c zypper -l 'installed-only' -s 'i' -d 'Show only installed products'
complete -c zypper -l 'not-installed-only' -s 'u' -d 'Show only products which are not installed'
complete -c zypper -l 'repo' -s 'r' -d 'Restrict the lock to the specified repository'
complete -c zypper -l 'type' -s 't' -d 'Type of package'
complete -c zypper -l 'repo' -s 'r' -d 'Remove only locks with specified repository'
complete -c zypper -l 'type' -s 't' -d 'Type of package'
complete -c zypper -l 'only-duplicates' -s 'd' -d 'Clean only duplicate locks'
complete -c zypper -l 'only-empty' -s 'e' -d 'Clean only locks which doesn'"'"'t lock anything'
complete -c zypper -l 'packages' -s 'p' -d 'Show corresponding packages'
complete -c zypper -l 'all' -s 'a' -d 'List all available locales'
complete -c zypper -l 'no-packages' -s 'n' -d 'Do not install corresponding packages for given locale(s)'
complete -c zypper -l 'no-packages' -s 'n' -d 'Do not remove corresponding packages for given locale(s)'
complete -c zypper -l 'match' -s 'm' -d 'Takes missing release number as any release'
complete -c zypper -l 'label' -s 'l' -d 'Show the operating system label'
complete -c zypper -l 'repo' -s 'r' -d 'Clean only specified repositories'
complete -c zypper -l 'metadata' -s 'm' -d 'Clean metadata cache'
complete -c zypper -l 'raw-metadata' -s 'M' -d 'Clean raw metadata cache'
complete -c zypper -l 'all' -s 'a' -d 'Clean both metadata and package caches'
complete -c zypper -l 'updatestack-only' -d 'Consider only patches which affect the package management itself'
complete -c zypper -l 'with-update' -d 'Additionally try to update all packages not covered by patches'
complete -c zypper -l 'details' -d 'Show the detailed installation summary'
complete -c zypper -l 'replacefiles' -d 'Install even if it replaces files from other installed packages'
complete -c zypper -l 'repo' -s 'r' -d 'Load only the specified repository'
complete -c zypper -l 'category' -s 'g' -d 'Select patches with the specified category'
complete -c zypper -l 'severity' -d 'Select patches with the specified severity'
complete -c zypper -l 'date' -d 'Select patches issued up to, but not including, the specified date'
complete -c zypper -l 'bugzilla' -s 'b' -d 'Select applicable patches for the specified Bugzilla issues'
complete -c zypper -l 'cve' -d 'Select applicable patches for the specified CVE issues'
complete -c zypper -l 'with-optional' -l 'without-optional' -d 'Whether applicable optional patches should be treated as needed or be excluded'
complete -c zypper -l 'with-interactive' -d 'Do not skip interactive patches'
complete -c zypper -l 'skip-interactive' -d 'Skip interactive patches'
complete -c zypper -l 'auto-agree-with-licenses' -s 'l' -d 'Automatically say '"'"'yes'"'"' to third party license confirmation prompt'
complete -c zypper -l 'dry-run' -s 'D' -d 'Test the update, do not actually update'
complete -c zypper -l 'download' -d 'Set the download-install mode'
complete -c zypper -l 'download-only' -s 'd' -d 'Only download the packages, do not install'
complete -c zypper -l 'directory' -s 'd' -d 'Download all source rpms to this directory'
complete -c zypper -l 'delete' -d 'Delete extraneous source rpms in the local directory'
complete -c zypper -l 'no-delete' -d 'Do not delete extraneous source rpms'
complete -c zypper -l 'status' -d 'Show which source rpms are missing or extraneous'
complete -c zypper -l 'all-matches' -d 'Download all versions matching the commandline arguments'
complete -c zypper -l 'from' -d 'Select packages from the specified repository'
complete -c zypper -l 'repo' -s 'r' -d 'Work only with the specified repository'
complete -c zypper -l 'short' -s 's' -d 'Create a short table not showing the deleted files'
complete -c zypper -l 'print' -d 'For each associated system service print <format>'
complete -c zypper -l 'debugFile' -s 'd' -d 'Write debug output to file'
