/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   wcwidth_mktable.c                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lgamba <linogamba@pundalik.org>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/03/17 11:59:40 by lgamba            #+#    #+#             */
/*   Updated: 2025/03/17 11:59:41 by lgamba           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#include <shell/shell.h>

/**
 * @file Sorted list of non-overlapping intervals of non-spacing characters
 * generated by "uniset +cat=Me +cat=Mn +cat=Cf -00AD +1160-11FF +200B c"
 */

void
	mk_wcwidth1(struct s_codepoint_range *r)
{
	r[0] = (struct s_codepoint_range){0x0300, 0x036F};
	r[1] = (struct s_codepoint_range){0x0483, 0x0486};
	r[2] = (struct s_codepoint_range){0x0488, 0x0489};
	r[3] = (struct s_codepoint_range){0x0591, 0x05BD};
	r[4] = (struct s_codepoint_range){0x05BF, 0x05BF};
	r[5] = (struct s_codepoint_range){0x05C1, 0x05C2};
	r[6] = (struct s_codepoint_range){0x05C4, 0x05C5};
	r[7] = (struct s_codepoint_range){0x05C7, 0x05C7};
	r[8] = (struct s_codepoint_range){0x0600, 0x0603};
	r[9] = (struct s_codepoint_range){0x0610, 0x0615};
	r[10] = (struct s_codepoint_range){0x064B, 0x065E};
	r[11] = (struct s_codepoint_range){0x0670, 0x0670};
	r[12] = (struct s_codepoint_range){0x06D6, 0x06E4};
	r[13] = (struct s_codepoint_range){0x06E7, 0x06E8};
	r[14] = (struct s_codepoint_range){0x06EA, 0x06ED};
	r[15] = (struct s_codepoint_range){0x070F, 0x070F};
	r[16] = (struct s_codepoint_range){0x0711, 0x0711};
	r[17] = (struct s_codepoint_range){0x0730, 0x074A};
	r[18] = (struct s_codepoint_range){0x07A6, 0x07B0};
	r[19] = (struct s_codepoint_range){0x07EB, 0x07F3};
	r[20] = (struct s_codepoint_range){0x0901, 0x0902};
	r[21] = (struct s_codepoint_range){0x093C, 0x093C};
	r[22] = (struct s_codepoint_range){0x0941, 0x0948};
	r[23] = (struct s_codepoint_range){0x094D, 0x094D};
	r[24] = (struct s_codepoint_range){0x0951, 0x0954};
}

void
	mk_wcwidth2(struct s_codepoint_range *r)
{
	r[25] = (struct s_codepoint_range){0x0962, 0x0963};
	r[26] = (struct s_codepoint_range){0x0981, 0x0981};
	r[27] = (struct s_codepoint_range){0x09BC, 0x09BC};
	r[28] = (struct s_codepoint_range){0x09C1, 0x09C4};
	r[29] = (struct s_codepoint_range){0x09CD, 0x09CD};
	r[30] = (struct s_codepoint_range){0x09E2, 0x09E3};
	r[31] = (struct s_codepoint_range){0x0A01, 0x0A02};
	r[32] = (struct s_codepoint_range){0x0A3C, 0x0A3C};
	r[33] = (struct s_codepoint_range){0x0A41, 0x0A42};
	r[34] = (struct s_codepoint_range){0x0A47, 0x0A48};
	r[35] = (struct s_codepoint_range){0x0A4B, 0x0A4D};
	r[36] = (struct s_codepoint_range){0x0A70, 0x0A71};
	r[37] = (struct s_codepoint_range){0x0A81, 0x0A82};
	r[38] = (struct s_codepoint_range){0x0ABC, 0x0ABC};
	r[39] = (struct s_codepoint_range){0x0AC1, 0x0AC5};
	r[40] = (struct s_codepoint_range){0x0AC7, 0x0AC8};
	r[41] = (struct s_codepoint_range){0x0ACD, 0x0ACD};
	r[42] = (struct s_codepoint_range){0x0AE2, 0x0AE3};
	r[43] = (struct s_codepoint_range){0x0B01, 0x0B01};
	r[44] = (struct s_codepoint_range){0x0B3C, 0x0B3C};
	r[45] = (struct s_codepoint_range){0x0B3F, 0x0B3F};
	r[46] = (struct s_codepoint_range){0x0B41, 0x0B43};
	r[47] = (struct s_codepoint_range){0x0B4D, 0x0B4D};
	r[48] = (struct s_codepoint_range){0x0B56, 0x0B56};
	r[49] = (struct s_codepoint_range){0x0B82, 0x0B82};
}

void
	mk_wcwidth3(struct s_codepoint_range *r)
{
	r[50] = (struct s_codepoint_range){0x0BC0, 0x0BC0};
	r[51] = (struct s_codepoint_range){0x0BCD, 0x0BCD};
	r[52] = (struct s_codepoint_range){0x0C3E, 0x0C40};
	r[53] = (struct s_codepoint_range){0x0C46, 0x0C48};
	r[54] = (struct s_codepoint_range){0x0C4A, 0x0C4D};
	r[55] = (struct s_codepoint_range){0x0C55, 0x0C56};
	r[56] = (struct s_codepoint_range){0x0CBC, 0x0CBC};
	r[57] = (struct s_codepoint_range){0x0CBF, 0x0CBF};
	r[58] = (struct s_codepoint_range){0x0CC6, 0x0CC6};
	r[59] = (struct s_codepoint_range){0x0CCC, 0x0CCD};
	r[60] = (struct s_codepoint_range){0x0CE2, 0x0CE3};
	r[61] = (struct s_codepoint_range){0x0D41, 0x0D43};
	r[62] = (struct s_codepoint_range){0x0D4D, 0x0D4D};
	r[63] = (struct s_codepoint_range){0x0DCA, 0x0DCA};
	r[64] = (struct s_codepoint_range){0x0DD2, 0x0DD4};
	r[65] = (struct s_codepoint_range){0x0DD6, 0x0DD6};
	r[66] = (struct s_codepoint_range){0x0E31, 0x0E31};
	r[67] = (struct s_codepoint_range){0x0E34, 0x0E3A};
	r[68] = (struct s_codepoint_range){0x0E47, 0x0E4E};
	r[69] = (struct s_codepoint_range){0x0EB1, 0x0EB1};
	r[70] = (struct s_codepoint_range){0x0EB4, 0x0EB9};
	r[71] = (struct s_codepoint_range){0x0EBB, 0x0EBC};
	r[72] = (struct s_codepoint_range){0x0EC8, 0x0ECD};
	r[73] = (struct s_codepoint_range){0x0F18, 0x0F19};
	r[74] = (struct s_codepoint_range){0x0F35, 0x0F35};
}

void
	mk_wcwidth4(struct s_codepoint_range *r)
{
	r[75] = (struct s_codepoint_range){0x0F37, 0x0F37};
	r[76] = (struct s_codepoint_range){0x0F39, 0x0F39};
	r[77] = (struct s_codepoint_range){0x0F71, 0x0F7E};
	r[78] = (struct s_codepoint_range){0x0F80, 0x0F84};
	r[79] = (struct s_codepoint_range){0x0F86, 0x0F87};
	r[80] = (struct s_codepoint_range){0x0F90, 0x0F97};
	r[81] = (struct s_codepoint_range){0x0F99, 0x0FBC};
	r[82] = (struct s_codepoint_range){0x0FC6, 0x0FC6};
	r[83] = (struct s_codepoint_range){0x102D, 0x1030};
	r[84] = (struct s_codepoint_range){0x1032, 0x1032};
	r[85] = (struct s_codepoint_range){0x1036, 0x1037};
	r[86] = (struct s_codepoint_range){0x1039, 0x1039};
	r[87] = (struct s_codepoint_range){0x1058, 0x1059};
	r[88] = (struct s_codepoint_range){0x1160, 0x11FF};
	r[89] = (struct s_codepoint_range){0x135F, 0x135F};
	r[90] = (struct s_codepoint_range){0x1712, 0x1714};
	r[91] = (struct s_codepoint_range){0x1732, 0x1734};
	r[92] = (struct s_codepoint_range){0x1752, 0x1753};
	r[93] = (struct s_codepoint_range){0x1772, 0x1773};
	r[94] = (struct s_codepoint_range){0x17B4, 0x17B5};
	r[95] = (struct s_codepoint_range){0x17B7, 0x17BD};
	r[96] = (struct s_codepoint_range){0x17C6, 0x17C6};
	r[97] = (struct s_codepoint_range){0x17C9, 0x17D3};
	r[98] = (struct s_codepoint_range){0x17DD, 0x17DD};
	r[99] = (struct s_codepoint_range){0x180B, 0x180D};
}

void
	mk_wcwidth5(struct s_codepoint_range *r)
{
	r[100] = (struct s_codepoint_range){0x18A9, 0x18A9};
	r[101] = (struct s_codepoint_range){0x1920, 0x1922};
	r[102] = (struct s_codepoint_range){0x1927, 0x1928};
	r[103] = (struct s_codepoint_range){0x1932, 0x1932};
	r[104] = (struct s_codepoint_range){0x1939, 0x193B};
	r[105] = (struct s_codepoint_range){0x1A17, 0x1A18};
	r[106] = (struct s_codepoint_range){0x1B00, 0x1B03};
	r[107] = (struct s_codepoint_range){0x1B34, 0x1B34};
	r[108] = (struct s_codepoint_range){0x1B36, 0x1B3A};
	r[109] = (struct s_codepoint_range){0x1B3C, 0x1B3C};
	r[110] = (struct s_codepoint_range){0x1B42, 0x1B42};
	r[111] = (struct s_codepoint_range){0x1B6B, 0x1B73};
	r[112] = (struct s_codepoint_range){0x1DC0, 0x1DCA};
	r[113] = (struct s_codepoint_range){0x1DFE, 0x1DFF};
	r[114] = (struct s_codepoint_range){0x200B, 0x200F};
	r[115] = (struct s_codepoint_range){0x202A, 0x202E};
	r[116] = (struct s_codepoint_range){0x2060, 0x2063};
	r[117] = (struct s_codepoint_range){0x206A, 0x206F};
	r[118] = (struct s_codepoint_range){0x20D0, 0x20EF};
	r[119] = (struct s_codepoint_range){0x302A, 0x302F};
	r[120] = (struct s_codepoint_range){0x3099, 0x309A};
	r[121] = (struct s_codepoint_range){0xA806, 0xA806};
	r[122] = (struct s_codepoint_range){0xA80B, 0xA80B};
	r[123] = (struct s_codepoint_range){0xA825, 0xA826};
	r[124] = (struct s_codepoint_range){0xFB1E, 0xFB1E};
}
